### ISSUE TITLE
[Spec]  #920 Timezone Change Event

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#1000]
# [The feature] 
Timezone change events are not globally exposed, instead all platforms offer a seperate entry  point for this event. See #920 for more.

### Events

| API | Description |
| ------------- | ------------- |
| [TimezoneChanged] | [Fires on change, we do not want to forward automatically by one hour, that is the consumers decision.] |
 
# Scenarios

# Platform Compatibility
- Target Frameworks: All, see #920
# Difficulty : [low]

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
