### ISSUE TITLE
[Bug] Launcher API not working on iOS

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Essentials#1003]
### Description
It seems that Launcher API is not working on iOS.

Here is my code

```
private async void Button_Clicked(object sender, System.EventArgs e)
{
    if (await Launcher.CanOpenAsync("fb://"))
    {
        await Launcher.OpenAsync("fb://page/1757128791000664");
    }
}
```

I have added my custom URL scheme to the Info.plist

```
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>Facebook</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fb</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
		</dict>
	</array>
```

On Android clicking the button launches Facebook app. On iOS nothing happens.

### Steps to Reproduce

1. Install Facebook app on your iOS device and log in to it.
2. Add custom URL scheme to Info.plist like it is shown above.
3. Create a button in XAML and add "Button_Clicked" event handler to it.
4. Launch the app and click the button
5. As you can see nothing happens.

### Expected Behavior
Facebook app should open.

### Actual Behavior
Nothing happens.

### Basic Information

- Version with issue: 1.3.1
- IDE: Visual Studio 2019 16.3.10
- Platform Target Frameworks: 
  - iOS:  13.6.0.12

**Comment by Mikilll94** [comment]
@jamesmontemagno 
Finally, I have found a solution.

**CFBundleURLTypes** in Info.plist should not be present because this is used just for defining for own url schemes.

Here is the solution:

```
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>fb</string>
</array>
```

You need to add **LSApplicationQueriesSchemes** to your Info.plist. The reason for this is described here:
https://stackoverflow.com/questions/30987986/ios-9-not-opening-instagram-app-with-url-scheme

The Launcher docs should be updated to include this, because without **LSApplicationQueriesSchemes** the Launcher API is not working on iOS.

**Comment by jamesmontemagno** [comment]
I have added a PR to documentation. Thanks!
