### ISSUE TITLE
[Bug] Most Struct Equality operations allocate

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#1004]
### Description
At some point it was decided to use the same pattern for all equality operators, but most of them allocate needlessly because they are not written correctly. For reference, check DisplayInfo.
### Steps to Reproduce

1. Compare DisplayInfo with op_eq
2. allocates boxes needlessly, as it calls object.equals(obj a, obj b)
3. compare with displayinfo.equals() => no allocations

### Expected Behavior
op_eq does not allocate
### Actual Behavior
it does
- Version with issue: The first pr on my side introducing readonly structs used the resharper generated version during the first commits which does not allocate
- Last known good version: None released
- IDE:
- Platform Target Frameworks: All
- Nuget Packages: All
- Affected Devices: All

### Reproduction Link

``` ini

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.18362
Intel Core i7-4790 CPU 3.60GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.0.100
  [Host]  : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), 64bit RyuJIT  [AttachedDebugger]
  DryClr  : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.8.4018.0
  DryCore : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), 64bit RyuJIT

IterationCount=1  LaunchCount=1  RunStrategy=ColdStart  
UnrollFactor=1  WarmupCount=1  

```
|        Method |     Job | Runtime |       Mean | Error | Gen 0 | Gen 1 | Gen 2 | Allocated | Method |
|-------------- |-------- |-------- |-----------:|------:|------:|------:|------:|----------:|----------:|
| EqTest_Allocs | DryCore |    Core |   959.8 us |    NA |     - |     - |     - |      80 B | op_eq |
| EqTest_Doesnt | DryCore |    Core |   530.7 us |    NA |     - |     - |     - |         - | displayinfo.eq |

**Comment by terrajobst** [comment]
> 1. Compare DisplayInfo with op_eq
> 2. allocates boxes needlessly, as it calls object.equals(obj a, obj b)
> 3. compare with displayinfo.equals() => no allocations

Nit: it can't be `op_Equality` because the C# compiler won't let you compile against a value type that hasn't defined `operator==`. You probably mean the `Equals` method.

That being said, there is reason why we say this in the guidelines:

[1.](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/equality-operators#equality-operators-on-value-types) ✓ DO overload the equality operators on value types, if equality is meaningful
[2.](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/struct) ✓ DO implement IEquatable<T> on value types

**Comment by terrajobst** [comment]
Nevermind, I just saw [the implementation](https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Types/DisplayInfo.shared.cs#L27-L31):

```C#
public static bool operator ==(DisplayInfo left, DisplayInfo right) =>
    Equals(left, right);

public static bool operator !=(DisplayInfo left, DisplayInfo right) =>
    !Equals(left, right);
```

This code calls `Object.Equals(object, object)`. Chang the code to call your locally defined `Equals(DisplayInfo)` which doesn't box:

```C#
public static bool operator ==(DisplayInfo left, DisplayInfo right) =>
    left.Equals(right);

public static bool operator !=(DisplayInfo left, DisplayInfo right) =>
    !left.Equals(right);
```

**Comment by jamesmontemagno** [comment]
@terrajobst -> https://github.com/xamarin/Essentials/pull/1019 look alright?
