### ISSUE TITLE
[Enhancement] Ability to send custom HTTP headers using `Browser`

### ISSUE THREAD

**Issue by cocowalla** [xamarin/Essentials#1005]
## Summary
[Browser](https://docs.microsoft.com/en-gb/xamarin/essentials/open-browser) provides a simple abstraction for opening web pages. But compared with `WebView`, it's _too_ simple.

The proposal is to add the ability to customise at least the initial web request, but ideally all web requests.

## API Changes

1. Add a new, optional property to `BrowserLaunchOptions`, to allow setting static HTTP headers:

```c#
public IDictionary<string, string> Headers { get; set; }
```

All configured headers would be sent either on the first request, or on all requests - would like some discussion on this point.

Headers configured here would be merged with any standard ones.

2. Add a new, optional property to `BrowserLaunchOptions` to allow intercepting HTTP calls and dynamically settings request headers:

```c#
public Func<HttpWebRequest, IDictionary<string, string>> RequestInterceptAction { get; set; }
```

The developer can then provide a function that takes the HTTP request as a parameter (before it's sent!), and returns a list of HTTP header to be used when the request is made.

## Intended Use Case
The typical use case here is for setting the `Authorization` header, in particular to set a bearer token.

This functionality would also be useful in a variety of cases where custom headers are required.

**Comment by dan-matthews-takeda** [comment]
This is good juju.

**Comment by dan-matthews** [comment]
This is good juju.

**Comment by jamesmontemagno** [comment]
I don't believe there are APIs for this, we are just calling into Chrome Custom Tabs/SF Safari View.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
