### ISSUE TITLE
[Enhancement] Extend FileSystem

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Essentials#1006]
## Summary
Allow create directories or files, read and write file's content

## API Changes
Add:
CreateDirectory(parentPath, directoryName);
DeleteDirectory(path, isRecursive);
IsDirectoryExists(path)

CreateFile(directoryPath, fileName)
DeleteFile(path)
WriteFile(directoryPath, filename, content)
ReadFile(path)
IsFileExists(path)

## Intended Use Case
This scenarios can be achieved by System.IO.File and System.IO.Directory, but UWP doesn't work as expected with them, so it requires create custom service for file/directory operations and use IStorageFolder2.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
