### ISSUE TITLE
Sometime getting exception while opening PDF in browser.

### ISSUE THREAD

**Issue by JaiAtExfo** [xamarin/Essentials#1007]
### Description
I am using blow line of code in my project. It is working file to open pdf flie in browse on iPhone and Android. But sometime I am getting exception.
try
                {
                    await Xamarin.Essentials.Browser.OpenAsync(pageURL);
                }
                catch (Exception ex)
                {
                    this.LogException(ex);
                }
### Steps to Reproduce

1.  Open user manual file from server url. 
2. Try to open several time.
3. Some time getting exception.

### Expected Behavior

PDF file should be open.

### Actual Behavior

{System.InvalidOperationException: Could not find current view controller.
  at Xamarin.Essentials.Platform.GetCurrentViewController (System.Boolean throwIfNull) [0x0007f] in D:\a\1\s\Xamarin.Essentials\Platform\Platform.ios.cs:60 
  at Xamarin.Essentials.Browser+<PlatformOpenAsync>d__7.MoveNext () [0x00049] in D:\a\1\s\Xamarin.Essentials\Browser\Browser.ios.cs:19 
--- End of stack trace from previous location where exception was thrown ---

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
Where you calling this code from? Looks like you may be doing it in a location from which the current UI viewcontroller can not be found.

**Comment by jamesmontemagno** [comment]
@JaiAtExfo would really like to know where you are making the call from so we can try to reproduce it. It is very dependent on your code as the ViewController could not be located.

**Comment by jamesmontemagno** [comment]
[Essentials907.zip](https://github.com/xamarin/Essentials/files/4020730/Essentials907.zip)

Was unable to reproduce at all here with both an alert open and not open. Attached is sample. Please open a new ticket with sample code showing off the issue if you can reproduce.

**Comment by chrisfoulds** [comment]
my app randomly gets these in both testing and production.
Unfortunately I have yet to find a way to reproduce.
In my case it is just opening web links

**Comment by chrisfoulds** [comment]
```
            MainThread.BeginInvokeOnMainThread(async () =>
            {
                if (item.Url != null && item.Url.Length > 1)
                {
                    await Browser.OpenAsync(item.Url, new BrowserLaunchOptions
                    {
                        LaunchMode = BrowserLaunchMode.SystemPreferred,
                        TitleMode = BrowserTitleMode.Show,
                        PreferredToolbarColor = Color.AliceBlue,
                        PreferredControlColor = Color.Violet
                    });

                }
            });
```

**Comment by chrisfoulds** [comment]
Sequence found. Display Alert -> Open Modal -> Close Modal -> Open Browser

**Comment by xleon** [comment]
I'm getting this too, not only with PDFs, buy on any url. 
![image](https://user-images.githubusercontent.com/145087/145610422-8c911ac8-5621-43a0-8daf-e9c54b6fe996.png)
![image](https://user-images.githubusercontent.com/145087/145610466-0ee01607-b9d0-4412-8002-f99961f08eb0.png)

Looking at the library code I can see 2 ways you are using to get the current window: 
- https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/Platform/Platform.ios.tvos.watchos.cs#L83
- https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/Platform/Platform.ios.tvos.watchos.cs#L83

Clearly there are some race conditions where those methods do not return the current window (potentially in iOS 15+ devices). 
I've been investigating this issue for a couple of days, which is also an issue in [Rg.Plugins.Popup](https://github.com/rotorgames/Rg.Plugins.Popup/pull/717)

According to this [SO answer](https://stackoverflow.com/a/58031897/1850606), a better solution to get the window might look like this:
```csharp
public static UIWindow GetKeyWindow(this UIApplication application)
{
    if (!UIDevice.CurrentDevice.CheckSystemVersion(13, 0)) 
        return application.KeyWindow; // deprecated in iOS 13
    
    var window = application
        .ConnectedScenes
        .ToArray()
        .OfType<UIWindowScene>()
        .SelectMany(scene => scene.Windows)
        .FirstOrDefault(window => window.IsKeyWindow);

    return window;
}
```

**Comment by xleon** [comment]
Turns out Essentials has a way to override how it resolves the current view controller. So this is my workaround for now:

```csharp
Xamarin.Essentials.Platform.Init(UiHelper.GetTopViewController);


public static UIViewController GetTopViewController()
{
    var window = UIApplication.SharedApplication.GetKeyWindow();
    var vc = window?.RootViewController;
    while (vc is { PresentedViewController: { } })
        vc = vc.PresentedViewController;

    if (vc is UINavigationController { ViewControllers: { } } navController) 
        vc = navController.ViewControllers.Last();

    return vc;
}

public static UIWindow GetKeyWindow(this UIApplication application)
{
    if (!UIDevice.CurrentDevice.CheckSystemVersion(13, 0)) 
        return application.KeyWindow; // deprecated in iOS 13
    
    var window = application
        .ConnectedScenes
        .ToArray()
        .OfType<UIWindowScene>()
        .SelectMany(scene => scene.Windows)
        .FirstOrDefault(window => window.IsKeyWindow);

    return window;
}
```
