### ISSUE TITLE
Connectivity or CrossConnectivity?

### ISSUE THREAD

**Issue by frankygoop** [xamarin/Essentials#1013]
Sorry, not sure where to ask. I am confused with the Connectivity from Essentials and the CrossConnectivity from Xam.plugin.connectivity. 
Which one is most developed? The connectivity from Essentials seems to be abandoned. Am I right?

thanks

**Comment by acaliaro** [comment]
I think Xam.Plugin has been added to Essentials. @jamesmontemagno is it right?

**Comment by jamesmontemagno** [comment]
Correct. Nearly all of the features are here in Essentials. Only reason to continue to use my plugin is if it has feature or platforms that you would like to keep supporting.
