### ISSUE TITLE
[Enhancement] DisplayRotation should return rotation value if cast to int

### ISSUE THREAD

**Issue by MSiccDev** [xamarin/Essentials#1017]
## Summary
DisplayRoation enum represents rotation degrees. If a value is cast to int, it should return the degree value. Unknown may return -1.

## API Changes
none

## Intended Use Case
use int value of enum for calculations without the need of additional conversions

**Comment by mattleibow** [comment]
Sadly, we can't change this now. Breaking changes will be bad.
