### ISSUE TITLE
[Enhancement] Email: specify attachment name

### ISSUE THREAD

**Issue by sejerpz** [xamarin/Essentials#1018]
## Summary

Add the possibility to specify the attachment filename (display name) when sending an email

## API Changes

Make the property AttachmentName of the class FileBase public or add an equivalent property in the EmailAttachment.

## Intended Use Case
Give a meaningful name to attachment when created from app data.

**Comment by mattleibow** [comment]
This sounds like a good thing to have. I often will generate a random file with a guid in the cache. Emailing this with a useful name is needed.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
