### ISSUE TITLE
[Bug] MainThread.BeginInvokeOnMainThread crashes on Windows if called too early

### ISSUE THREAD

**Issue by tipa** [xamarin/Essentials#1020]
### Description
If MainThread.BeginInvokeOnMainThread is called to early, it crashes with 
```
System.InvalidOperationException: 'A method was called at an unexpected time.
Could not create a new view because the main window has not yet been created'
```

### Steps to Reproduce
Execute  `MainThread.BeginInvokeOnMainThread` in app constructor

### Expected Behavior
No crash, exception is caught and code is executed on current thread

### Actual Behavior
It crashes here: https://github.com/xamarin/Essentials/blob/b018723477f848b108cb9a67adecb3608d0ab686/Xamarin.Essentials/MainThread/MainThread.uwp.cs#L16

### Basic Information
- Version with issue: Xamarin.Essentials 1.3.1

### Reproduction Link
[App3.zip](https://github.com/xamarin/Essentials/files/3959698/App3.zip)

**Comment by jamesmontemagno** [comment]
Hmmm, i'll give it a try. this is master: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/MainThread/MainThread.uwp.cs i wonder what isn't null.

**Comment by jamesmontemagno** [comment]
I see, it basically throws an exception when we check :(

![image](https://user-images.githubusercontent.com/1676321/70819851-1600ce80-1d8c-11ea-935e-d7d10d731044.png)
