### ISSUE TITLE
[Enhancement] ActivityRecognition APIs

### ISSUE THREAD

**Issue by nexxuno** [xamarin/Essentials#1023]
## Summary
API users should be able to understand if the end user is walking, driving, standing still. Both android and ios already have APIs for this. 

## API Changes
The simplest API would be an extension of the Location class:
Location.CurrentActivity

where CurrentActivity is an enum:
Still, Walking, Cycling, Driving, Running

Optionally an ActivityChanged event could be added together with StartListeningActivityChanged and StopListeningActivityChanged.

Platforms API:
https://developers.google.com/android/reference/com/google/android/gms/location/DetectedActivity

https://developer.apple.com/documentation/coremotion/cmmotionactivity

## Intended Use Case
Any scenario where coders need to understand the kind of activity that is going on.

**Comment by jamesmontemagno** [comment]
I really like this, except Android required Google Play Services packages to be brought in and we don't want to take dependencies on that.

**Comment by nexxuno** [comment]
So it could be implemented mixing sensors data and location data but I guess it would become too complicated.

**Comment by AndreiZachi** [comment]
Up

**Comment by pasha-o** [comment]
Hello @jamesmontemagno, curious to know if this will be completed at some point? There are also a bunch of new permissions that need to be added for Android 12.
