### ISSUE TITLE
KeepScreenOn don't work on Android Tablet

### ISSUE THREAD

**Issue by Zukka** [xamarin/Essentials#1025]
### Description
I add Xamarin.Essentials.DeviceDisplay.KeepScreenOn = true; in my page and works fine on iOS and Android phone, but on Android Tablet Samsung Galaxy Tab A don't work.
### Steps to Reproduce

1. Set in device display setting a sleep timer to 15 seconds
2. Open app 
3. Wait

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio Professional 2019 - Ver. 16.3.10
- Platform Target Frameworks: 
  - iOS:  11
  - Android: min version supported 5.0 (API 21) - Destination Ver. 9.0 (API 28)

**Comment by jamesmontemagno** [comment]
It may be that the device itself doesn't respect this flag. It is the official api that we use: https://developer.android.com/training/scheduling/wakelock

you can try this in your main activity to validate:

```csharp
this.Window.AddFlags(WindowManagerFlags.KeepScreenOn)
```

Not much we can do unfortunately.

**Comment by jamesmontemagno** [comment]
Closing as this is device specific and the API call is all we can do.
