### ISSUE TITLE
[Enhancement] Some struct equality comparisons still allocate. 

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#1029]
### Description
Some struct equality operations still allocate after the latest 'fix', caused by using the generic enum Equals method. This happens in the Equals method, which is called by the == operator as well.
### Steps to Reproduce
1.  Compare two DisplayInfo structs either via == or Equals
2. Other enum value is boxed

### Expected Behavior
Just use the equality operator instead of the equals function for enums
### Actual Behavior
object.equals is called for enums
### Basic Information

- Version with issue: All
- Last known good version: None
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
[proof](https://imgur.com/a/lNqszxt) that it applies generally, see DisplayInfo as an example

**Comment by jamesmontemagno** [comment]
Iss this a duplicate of https://github.com/xamarin/Essentials/issues/965 at all?

**Comment by Mrnikbobjeff** [comment]
No, this issue is solely for the DisplayInfo struct, as it is the only struct containing an enum being compared with object.equals.

**Comment by Mrnikbobjeff** [comment]
Closed, James apparently fixed this somewhen for the only struct where it occurred

**Comment by mattleibow** [comment]
Very nice of him.
