### ISSUE TITLE
[Enhancement] Set Device WallPaper 

### ISSUE THREAD

**Issue by dlandi** [xamarin/Essentials#1035]
## Summary
The user's code presents a choice of images to set the device's new wallpaper. Boom.

## API Changes

Need to wrap device-specific methods of setting wallpaper image.

Android example:
https://docs.microsoft.com/en-us/samples/xamarin/monodroid-samples/livewallpaperdemo/

In IOS:
It is not possible to set wallpaper directly, but you can programmatically add the image to the ios photo album and then prompt the user to make the change:
https://www.hackingwithswift.com/example-code/media/uiimagewritetosavedphotosalbum-how-to-write-to-the-ios-photo-album

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
