### ISSUE TITLE
Xamarin Essentials inserted OnRequestPermissionsResult override and breaks code

### ISSUE THREAD

**Issue by shidem** [xamarin/Essentials#1042]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
It appears XE is attempting to replace your permissions plugin. Unfortunately, it fails miserably for me. There appears to be no API for checking and requesting permissions (primarily Android).

The biggest surprise to me occurred when I created a new Xam Forms project in VS2019. Lo and behold, the OnRequestPermissionsResult override was inserted into MainActivity. I thought "Great, less cut and paste!". I then got your Plugin.Permission from NuGet and assumed I could proceed as I always had.

The problem was when I invoke CrossPermissions.Current.RequestPermissionsAsync(permissions), it never returned! After wasting a few hours, I saw that the auto-inserted override code invoked the following -
Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);

Finally replaced it with your original plugin contribution (thank you, BTW!) -
PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);

And all works as I desired. Two comments -
1. XE should not inject unusable code.
2. XE should provide a documented permissions API. All I could find was PermissionsException, which is as useful as tits on a bull. This is either an incomplete work in progress or I am blind to the intended usage.

### Steps to Reproduce

1.  Create a blank Xam Forms app for Android and iOS.
2. Set permissions desired in the project manifest.
3. Attempt to request permissions and get permission status. No API in XE. Your plugin actually popped up the request, but I never got the return status

### Expected Behavior
User is prompted allow or deny  and status is returned.

### Actual Behavior
No returned status upon invocation of RequestPermissionsAsync.

### Basic Information
If I stick with your plugin and guidance I have no problems. The issue lies with Xam Essentials.

- Version with issue:
Xam Essentials 1.3.1

- Last known good version:
Not applicable.

- IDE:
VS2019 Enterprise 16.4.2

- Platform Target Frameworks:
 Not applicable.

- Nuget Packages:
Xam Essentials 1.3.1

- Affected Devices:
Not applicable.

**Comment by jamesmontemagno** [comment]
If you want to use the permission plugin & this one together you need to insert both lines into this override. See the setup instructions for Essentials here: https://docs.microsoft.com/en-us/xamarin/essentials/get-started?tabs=windows%2Candroid Essentials will prompt for permissions it needs (camera/location) automatically.

You would do:

```csharp
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Android.Content.PM.Permission[] grantResults)
{
    Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);
   PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
    base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
}
```

We are introducing a permissions api in 1.4.0 as well so you wont need my plugin eventually.
