### ISSUE TITLE
[Enhancement] Ability to exclude activities in share (iOS)

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#1044]
## Summary
Some apps simply don't work when sharing items such as Reminders and Facebook. Having the ability to filter out would be ideal on iOS and it is an API that exists:

https://stackoverflow.com/questions/31792506/how-to-exclude-notes-and-reminders-apps-from-the-uiactivityviewcontroller

## API Changes

Up for discussion

## Intended Use Case
Would fix issues such as #942

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
