### ISSUE TITLE
Connectivity not working on expired mobile data

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#1045]
Hi,

Reading [this](https://docs.microsoft.com/en-us/xamarin/essentials/connectivity?tabs=android#limitations), I understand that when the user is connected to WiFi but no internet access then it's part of the limitation (although I hope there will be a fix for it)

But what if the user has no data enabled in his mobile data?

For example, I tried an app on a prepaid mobile where data needs to be topped up and it was ok but when the data is finished the I will still get Internet from NetworkAccess although there is no internet and mobile data is expired

Is there any workaround for this?

Thanks,
[Jassim](https://www.angelsemirates.com)

**Comment by jamesmontemagno** [comment]
Yes, there is no API to detect this. On windows it may return ConstrainedItnernet, but there is no way to detect behind, you have to then make a call to your web server and see what happens there and have that case.
