### ISSUE TITLE
Can't find a geolocation on UWP. Catches exception with null value

### ISSUE THREAD

**Issue by DannyTimms** [xamarin/Essentials#1046]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
Can't find a location on UWP but works fine on iOS & Android.

### Steps to Reproduce

1. Enter postcode as string in entry and click search
2. Function catches exception

### Expected Behavior
function should return an "Address" object which is created when passing a British postcode in the search box.

### Actual Behavior
Catches exception on UWP:

Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll
System.ArgumentNullException: Value cannot be null.
Parameter name: MapServiceToken
   at Xamarin.Essentials.Geocoding.ValidateMapServiceToken()
   at Xamarin.Essentials.Geocoding.<PlatformGetPlacemarksAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FireAppD1.MiscFunctions.<FindAddress>d__1.MoveNext()

### Basic Information

- Version with issue:  1.3.1
- Last known good version: N/A
- IDE:
- Platform Target Frameworks:
  - UWP:   
- Nuget Packages: Xamarin Essentials
- Affected Devices: UWP Windows 10

**Comment by jamesmontemagno** [comment]
Do you have the code that you are specifically calling?

**Comment by jamesmontemagno** [comment]
Looks like you didn't setup your API key: https://docs.microsoft.com/en-us/xamarin/essentials/geocoding?tabs=uwp this is why you will get this

**Comment by DannyTimms** [comment]
Ahh. My bad.

Thank you very much.

**Comment by jamesmontemagno** [comment]
No problem at all. I am going to do a pull request in to give a better error message there so it is more obvious as it is pretty hidden there.
