### ISSUE TITLE
[Bug] Permissions CheckStatusAsync always return Denied on Android

### ISSUE THREAD

**Issue by tranb3r** [xamarin/Essentials#1051]
Using Xamarin.Essentials 1.4.0-pre, call Permissions CheckStatusAsync on Android. 
It always returns Denied.

Looking at the code, it's obvious that it cannot work (status is initalized to Denied instead of Granted).

Could you please fix that ?

**Comment by jamesmontemagno** [comment]
Whoa! Good catch! We will ship out a -pre2 asap!
