### ISSUE TITLE
[Bug] Verify Android Permission - Speech

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#1053]
https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Permissions/Permissions.android.cs#L346

**Comment by Redth** [comment]
I think this is fine as is.  Speech is maybe poorly named for Speech Recognition, which on Android requires record audio permission.

**Comment by jamesmontemagno** [comment]
Although is it different than Microphone? That is the same permission?

**Comment by craftindo** [comment]
I suggest to use the same word RecordAudio to replace Microphone as this different words will result in confusion and unnecessary extra mapping work.
