### ISSUE TITLE
[Bug] SecureStorage.SetAsync fails on Tizen if key already exists

### ISSUE THREAD

**Issue by DamianMehers** [xamarin/Essentials#1055]
### Description
Calling `SecureStorage.SetAsync` with a key that already exists fails on Tizen (`[Tizen.Security.SecureRepository] Failed to save data. alias=test, error=Provided alias already exists in the database`)

### Steps to Reproduce

Create a simple Xamarin app that calls 

``` c#
    await Xamarin.Essentials.SecureStorage.SetAsync("test", "one");
    await Xamarin.Essentials.SecureStorage.SetAsync("test", "two");
```

### Expected Behavior

Calling `SetAsync` twice with the same key should overwrite the existing entry.

### Actual Behavior
On Tizen you get an exception

```
D/kanbann (26499):    at Interop.CheckNThrowException(Int32 err, String msg)
D/kanbann (26499):    at Tizen.Security.SecureRepository.DataManager.Save(String alias, Byte[] data, Policy policy)
D/kanbann (26499):    at Xamarin.Essentials.SecureStorage.PlatformSetAsync(String key, String data)
D/kanbann (26499):    at Xamarin.Essentials.SecureStorage.SetAsync(String key, String value)
D/k
```

### Basic Information

Tizen.NET 6.0.0.14995
Xamarin Essentials 1.3.1

**Comment by DamianMehers** [comment]
The underlying [DataManager.Save](https://developer.tizen.org/dev-guide/csapi/api/Tizen.Security.SecureRepository.DataManager.html) API has no way to overwrite the existing value, so the solution may be to remove and then save.  That is what I will do to work around this behavior.

**Comment by DamianMehers** [comment]
I've created a fix and added a test in my local repository [here](https://github.com/DamianMehers/Essentials/pull/1/commits) but I need to test.  I've not had time to set up my dev machine to be able to build and test Essentials locally.  Can I easily run my changes through the Essentials CI bot?

**Comment by jamesmontemagno** [comment]
@DamianMehers if you do a PR it will fire off a CI build :)

**Comment by DamianMehers** [comment]
> @DamianMehers if you do a PR it will fire off a CI build :)

[Done](https://github.com/xamarin/Essentials/pull/1061).  Builds and tests pass now.  Thanks!
