### ISSUE TITLE
[Bug] Inconsistent Permission Status returned for CheckStatusAsync()

### ISSUE THREAD

**Issue by dsdilpreet** [xamarin/Essentials#1063]
### Description
When the following line is executed before Requesting Permission, it seems to return PermissionStatus.Denied for Android and PermissionStatus.Unknown for iOS.

`await Permissions.CheckStatusAsync<Permissions.LocationWhenInUse>();`

I was wondering if this is expected or can be improved please?

### Steps to Reproduce

1. Create a new Application.
2. Run the code described in description.
3. You should get inconsistent results between iOS and Android.

### Expected Behavior
In my opinion, PermissionStatus.Unknown should be returned if permission is checked before requesting it and if the user denies it on request, then PermissionStatus.Denied should be returned.
I am not sure if that's possible.

### Basic Information

- Version with issue: 1.4.0 pre 2
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  iOS 12.4.4
  - Android:  Android 10

**Comment by jamesmontemagno** [comment]
Yes, this is unfortunatelly how it has to be implemented. We will have it documented. iOS returns unknown until it is denied and android only returns denied or granted.
