### ISSUE TITLE
Permission's RequestAsync()

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#1064]
Hi,

I suggest you add an extension to the CheckStatusAsync which will force to RequestAsync when permission is not Granted without having to write it in a separate line (CheckStatusAsync and later RequestAsync)

so it will be like this:

`PermissionStatus status = await Permissions.CheckStatusAsync<Permissions.LocationWhenInUse>().RequestAsync();`

Thanks,
[Jassim](https://www.angelsemirates.com)

**Comment by EvoPulseGaming** [comment]
Doesn't android have a "don't ask me again" option when denying permissions? The only way to handle this would be to automatically return false for an embedded RequestAsync like this if the user did so. 

CheckStatusAsync is used when it is assumed that permissions have already been asked for, that way you can tailor your app if the user denied a permission.

If you want really want to do this, just use RequestAsync every time, at least on android once approved by the user, it will automatically return granted. Effectively doing what you want in one shot. (Still wont work if the android user clicks on the "don't ask me again" button.......)

**Comment by jamesmontemagno** [comment]
Thanks for the recommendation, however at this time we will put this in the developers hands to keep them separate.
