### ISSUE TITLE
Allow object in SecureStorage's value

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#1065]
Hi,

It will be great if you allow all objects in SecureStorage and not just string so the syntax will be like this:

`SecureStorage.SetAsync(string key, object value)`

Thanks,
Jassim

**Comment by Mrnikbobjeff** [comment]
This would entail bringing the same support to preferences, as SecureStorage just uses Preferences under the hood. I am currently doing some digging to see whether there are any glaring limitations. Might I instead suggest though that you just use the string overload and pass in a serialized version of your object? This is the only thing I see us doing if this were implemented, and the only options available to us without restricting the type passed are BinaryFormatter and DataContractSerializer.

**Comment by jamesmontemagno** [comment]
Secure storage itself just takes strings on most platforms, so for this we will leave it up to you to serialize out the data to a string and back. 

Thanks for the suggestion though.

**Comment by biapar** [comment]
```
            var tokenResponse = await SecureStorage.GetAsync(airbeesense.Constant.token_user_key);
            var jsontokenResponse = JsonConvert.DeserializeObject<TokerResponseModel>(tokenResponse);

                var jsontokenResponse = JsonConvert.SerializeObject(tokenResponse);

                await SecureStorage.SetAsync(airbeesense.Constant.token_user_key, jsontokenResponse);
```
