### ISSUE TITLE
[Bug] [iOS] Permissions.RequestAsync() Dialog box keeps on disappearing

### ISSUE THREAD

**Issue by dsdilpreet** [xamarin/Essentials#1066]
### Description
When the following line of code is executed, user is presented with dialog box but that box keeps on disappearing before user could interact with it. The problem only seems to be happening on iOS for me, Android seems okay.

`await Permissions.RequestAsync<Permissions.LocationWhenInUse>();`

### Steps to Reproduce

1. Run the code linked in reproduction link on iOS simulator / device
2. Click the button and the dialog should should come and go

### Expected Behavior
The dialog box should not disappear without user's interaction. 

### Actual Behavior
As described above

### Basic Information

- Version with issue: v1.4.0 pre 2
- Last known good version:
- IDE: Visual Studio 2019 16.4.3
- Platform Target Frameworks: 
  - iOS:  Tested on iOS 13.3 and 12.4.4 and both are affected.
  - Android:  9.0

### Screenshots
[iPhone 8 iOS 13.3 2020-01-20 09-17-29.zip](https://github.com/xamarin/Essentials/files/4083568/iPhone.8.iOS.13.3.2020-01-20.09-17-29.zip)

### Reproduction Link
https://github.com/dsdilpreet/xamarin-essentials-permissions-issue

**Comment by jamesmontemagno** [comment]
Can you try to narrow this down and just have a button that is clicked that prompts for the permission? In our tests that is working just fine.

**Comment by dsdilpreet** [comment]
Hi @jamesmontemagno ,

Sorry, I should have included this info before. 

If I don't use the task, then it still disappears but it stays a bit longer than before.

I am developing an application which depends heavily on location, so I need to check the location in a task and bring up certain view to the user, that is why I had a binding attached to visibility of button.

Here is the updated code and video.

[Updated_required_pages_and_video.zip](https://github.com/xamarin/Essentials/files/4120388/Updated_required_pages_and_video.zip)

**Comment by jamesmontemagno** [comment]
Oh, i think i know what this is......

**Comment by jamesmontemagno** [comment]
Could you test out this NuGet @dsdilpreet  https://dev.azure.com/xamarin/public/_build/results?buildId=13207&view=artifacts&type=publishedArtifacts

**Comment by dsdilpreet** [comment]
> Could you test out this NuGet @dsdilpreet https://dev.azure.com/xamarin/public/_build/results?buildId=13207&view=artifacts&type=publishedArtifacts

@jamesmontemagno , this is better. The permission dialog does not seem to disappear anymore.
