### ISSUE TITLE
[Bug] Android Geolocation - NoSuchMethodError "isFromMockProvider"

### ISSUE THREAD

**Issue by DouglasGiovanella** [xamarin/Essentials#1069]
### Description

The Android Geolocation is not checking the Android version before accessing the [IsFromMockProvider](https://github.com/xamarin/Essentials/blob/c5e0e873d3a3f94c2781164683a46ea61dc573ef/Xamarin.Essentials/Types/LocationExtensions.android.cs#L33) property when building the Location object.

This property is only available from API 18 onwards :c

https://developer.android.com/reference/android/location/Location#isFromMockProvider()

**Comment by jamesmontemagno** [comment]
I will put a check in there, however we only officially support API 19+ on Android.
