### ISSUE TITLE
MainThread.BeginInvokeOnMainThread invokes immediately unlike Device.BeginInvokeOnMainThread

### ISSUE THREAD

**Issue by DamianMehers** [xamarin/Essentials#1070]
@jamesmontemagno @Redth ... the [Tizen implementation](https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/MainThread/MainThread.tizen.cs) of `MainThread.BeginInvokeOnMainThread` checks if the current thread is the main thread, and if so, it invokes the action immediately.  I think it should queue the action for invocation later whether or not the current thread is the main thread.

**Am I right in this expectation?**  If so I'll flesh out this bug report and fix and create a pull request.

**Comment by DamianMehers** [comment]
I updated my code to use the Forms `Device.BeginInvokeOnMainThread` and it works.

**Comment by Redth** [comment]
Hmmm 🤔 that is a good observation. Begin insinuates fire and immediately return. I looked briefly at the other platforms and I think they are ok. 

I agree, at least Tizen behaviour should be changed.

**Comment by DamianMehers** [comment]
> Hmmm 🤔 that is a good observation. Begin insinuates fire and immediately return. I looked briefly at the other platforms and I think they are ok.
> 
> I agree, at least Tizen behaviour should be changed.

Thanks.  Thinking about how to test this, how does this look (apart from the wrong formatting and probably wrong test syntax)?  I use an initial `BeginInvokeOnMainThread` to get onto the main thread and then a second `BeginInvokeOnMainThread` to change a captured variable ... it should not change immediately. I'm assumung the task won't be context switched/timesliced

``` c#
public async Task Test() {
  // We use this to wait for background tasks to complete
  var tcs = new TaskCompletionSource<bool>();
  MainThread.BeginInvokeOnMainThread(() => {
    // This should not change immediately when BeginInvokeOnMainThread
    // is invoked
    bool shouldNotChange = true;
    MainThread.BeginInvokeOnMainThread(() => {
      shouldNotChange = false;
    });
    tcs.SetResult(shouldNotChange);
  });
  Assert.True(await tcs.Task);
}
```

**Comment by Redth** [comment]
@sung-su could you add some comments here?  I feel like maybe the actual implementation should avoid even checking if it's the main thread and regardless, just do:

```csharp
static void PlatformBeginInvokeOnMainThread(Action action)
    =>  EcoreMainloop.PostAndWakeUp(action);
```

Which shouldn't exactly be a big perf hit if we're already on the main thread.  I realize we do try and work around this on other platforms, but it doesn't seem feasible here.

@DamianMehers I'm not sure I follow your logic in the test code.  I suppose the inner BeginInvoke should in theory happen _after_ the tcs.SetResult since you're already invoking something on the main thread, but I wonder in practice there are two many things that could go wrong to not guarantee that (compiler optimizations being one).  I'm not sure it's hugely critical to add a test like this.

**Comment by DamianMehers** [comment]
@Redth Makes sense ... I was struggling to find a meaningful test.  Your change is what I had in mind - it is essentially what the other platforms do.  The Xamarin Forms Tizen [Device.BeginInvokeOnMainThread](Xamarin.Forms.Platform.Tizen/TizenPlatformServices.cs) does it slightly differently.

I've noticed that [MainThread.shared.cs](https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/MainThread/MainThread.shared.cs) invokes immediately if on the main thread ...

**Comment by DamianMehers** [comment]
Consider the following code:

``` c#
  public class MyViewModel : ViewModelBase {
    private string _someProperty;

    public string SomeProperty {
      get => _someProperty;
      set => SetProperty(ref _someProperty, value);
    }

    // Load properties that the UI is bound to
    public void Load() {
      MainThread.BeginInvokeOnMainThread(async () => {
        await Task.Delay(TimeSpan.FromSeconds(2));
        // Now do something you want to do after UI loads
      });
      SomeProperty = "some value";
    }
  }
```

The `SomeProperty` property won't be initialized until after the two second delay, which is not what most people expect from their experience of the Xamarin Forms `Device.BeginInvokeOnMainThread` ...

**Comment by sung-su** [comment]
```
static void PlatformBeginInvokeOnMainThread(Action action)
    =>  EcoreMainloop.PostAndWakeUp(action);
```
above code seems to no issue.

**Comment by jamesmontemagno** [comment]
If it is on the main thread already it should invoke it. If it is not then it should be queued.

**Comment by DamianMehers** [comment]
> If it is on the main thread already it should invoke it. If it is not then it should be queued.

Ok I was surprised it didn't mimic 'Device.BeginInvokeOnMainThread' but if it is by design then that's that. Closing it.
