### ISSUE TITLE
[Bug] Preferences in iOS incorrectly using the default value, works after setting same prefs again in 2nd app load

### ISSUE THREAD

**Issue by Bejasc** [xamarin/Essentials#1073]
### Description
Seems to only be a problem after upgrading XCode and Visual Studio. All builds compiled since the upgrade have had problems reading values from the settings. 

I have tried this with CrossSettings.Current, and with the new Xamarin.Essentials.Preferences - I'm experiencing the same behaviour from both. 

Android builds are working as expected / no change in behavior. This functionality had been working for months up until now. 

It seems to occasionally be reading the default value - even though the value has been saved already.

### Steps to Reproduce
**(Most frequently reproduced like so)**
Fresh install of App. 
First load - set the preferences. Shut app.
Second load - Read the preferences. Only reading defaults. Set the preferences again. Shut App
Third load - Reads preferences correctly
Every other consecutive load - Reads preferences correctly

### Expected Behavior
Preferences are read correctly each time

### Actual Behavior
Preferences are only read correctly after being set again in the 2nd load

### Basic Information

- Version with issue: 1.3.1
- Last known good version: Unknown, was previously using the [SettingsPlugin](https://github.com/jamesmontemagno/SettingsPlugin) where the same behaviour is exhibited (see [issue](https://github.com/jamesmontemagno/SettingsPlugin/issues/158))
- IDE: VS 2017
- Platform Target Frameworks: 
  - iOS:

**Comment by jamesmontemagno** [comment]
So, i tried to reproduce this on my iOS 13.3 emulator today and was working fine. I deleted and re-tried the app 4 times. Can you provide a source code sample?

**Comment by Bejasc** [comment]
Hi James,
I beleive the issue may have had something to do with updating VS/Mono on the mac that was being used to build this release. 

I notice at the time, that mono pushed quite a few updates in a short amount of time. 
After updating past what I'm assuming was a bad version, everything seems to be working as intended. 

Apologies, I don't have access to the machine at the moment to mention specific version numbers that were causing headaches. 

Feel free to close this one for now - if it rears it's head again I will re-raise with more info.

**Comment by Bejasc** [comment]
Hi @jamesmontemagno 
I've started to encounter the issue again, but I believe it sits at the other end of the chain (AddOrUpdateValue).

For context, the value that I am trying to save via this method is an object that has been serialized to a json string. The string is very large (4,966,375 characters). 

However, the issue is only seen on iPhone X running iOS 13.3.1. 
The same build on a device running iPhone 8 running iOS 12.0.1 sees no problem.

Using Xamarin Essentials 1.3.1.

Is there some undocumented limit to the size of the string that can be stored? The troubled device has well over 100gb of free space, so I don't think there's any issue there.
