### ISSUE TITLE
[Enhancement] Add platform support for WPF

### ISSUE THREAD

**Issue by peterfoot** [xamarin/Essentials#1075]
## Summary
We use Xamarin.Forms regularly across many platforms and increasingly use Xamarin.Essentials for abstracting platform functionality. Please consider adding a .NET WPF platform implementation. I have partial implementations of some key APIs ready to go. Not all APIs would be expected to be implemented.

## API Changes

This is a platform implementation and no changes to the public API are proposed.

I have code to enabled the following on WPF:-
* AppInfo
* Battery
* Browser
* Clipboard
* Connectivity
* DeviceDisplay
* DeviceInfo
* Email
* FileSystem
* Launcher
* Locale
* MainThread
* Preferences

## Intended Use Case
To allow the library to be used in projects targeting Windows Desktop (WPF)

**Comment by jamesmontemagno** [comment]
Thanks, we track additional platform support here: https://github.com/xamarin/Essentials/issues/662

**Comment by mattleibow** [comment]
@peterfoot, I would also say just open a PR and then we can talk. I have an open PR for macOS that has been there for a while, so a wpf one will be great. And, as we find more things we can add, we will be able to add them to that PR.
