### ISSUE TITLE
[Bug] SecureStorage Tizen implementation should check for existing alias instead of throwing.

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#1076]
### Description
A few hours ago code was introduced in master which "fixed" our SecureStorage Tizen implementation. It has a nasty try/catch which is needlessly called and may lead to excessive exceptions. We should use the given DataManager.GetAliases and check for alias existance this way instead of deleting on every preference set. See [here](https://samsung.github.io/TizenFX/API5/api/Tizen.Security.SecureRepository.DataManager.html)

**Comment by jamesmontemagno** [comment]
@DamianMehers Looking at the docs you could call `GetAliases()` and check to see if it exists, and if so then remove it and then add again.

**Comment by DamianMehers** [comment]
The catch only gets called if the data doesn't exist, which is the first time the alias is written.  I'm not sure that getting all aliases every time will be be less expensive, given that the exception is only thrown the first time data is written.

So the choice is - the cost of
- throwing and catching an exception once, the very first time a specific key is written.
- getting **all** values every time the key is written, and check.

I'm not sure that throwing the exception just the first time is such a big deal, but I'm fine with doing it ... you'll always have the cost of deleting before writing if the key is not new.

**Comment by Mrnikbobjeff** [comment]
We had an application where we used dynamically generated keys to store objects, these objects were removed after every application version update. Many settings were never read again (based on app usage). We would have an exception every time we set a new key, which is superfluous imo. I took a peek at the source code to check exactly what goes on, here are my findings:
1. The return type is always a list, no idea why they decay to ienumerable.
2. The amount of allocations happening are definitely more expensive than the allocations, expecially because:
3. The Tizen source only acts as an interop wrapper for ckm, and marshalling is expensive because the overloads take a char* and have to be marshalled accordingly
4. The ckm library does not expose the means to check for single key existence, instead it returns an error code if the key does exist when trying toset the key. 

The optimal solution is to make a pr to the Tizen SDK to implement this functionality, as they simply should not throw if that error code is thrown, instead expose a way to override existing parameters (deleting and then setting). We could also do this ourselves, which is not as nice as we would have to maintain that code. For now though I have to agree, the exception is probably less expensive.

**Comment by DamianMehers** [comment]
It would indeed be much better if the Tizen API `Set` API allowed overwrites, and their `Delete` API returned `false` if a value does not exist, rather than throwing Exceptions.  I think the current solution is the "least worst" but it is not ideal.

FWIW I just released a Samsung Galaxy Watch/Tizen app that uses Xamarin Essentials, and hit these issues while developing it, so these are real issues for me.

> For now though I have to agree, the exception is probably less expensive.

Should we close this bug?

**Comment by jamesmontemagno** [comment]
Will close for now.

**Comment by Mrnikbobjeff** [comment]
I added a PR for TizenFX exposing the required functionality. Will ping this once it is merged and published in the next Tizen API update if it should  come this far
