### ISSUE TITLE
[Enhancement] Email: Open only email apps

### ISSUE THREAD

**Issue by valerii-sovytskyi** [xamarin/Essentials#1081]
### Description

`Email.ComposeAsync` method sends a prepared message through default or existing email application on Android and iOS platforms. On the iOS platform, it opens a default device email application, but on Android, it asks a user to open all email applications and not only.

For example on Android the code below will open email applications only
`Device.OpenUri(new Uri("mailto:valerii.sovytskyi@test.com"));`

### Expected Behavior

Open only email applications like Gmail or Outlook

### Actual Behavior

On the Android platform, it asks a user to open all installed messaging applications like Gmail, Outlook, Skype, even Save to Drive, etc.

### Basic Information

- Version with issue: 1.3.1

**Comment by jamesmontemagno** [comment]
I believe that this is because we use "Action_Send" and message/rfc822 as the MIME Type. Which is actually correct, but multiple apps can handle it technically.

You could use "Launcher.OpenAsync("mailto:valerii.sovytskyi@test.com")".

There are a lot of threads out there that SENDTo will work without attachments, but you need to use different mime type when using it. So I think we can optimize it based on what is being sent.

**Comment by mathmul** [comment]
Where would one use `Launcher.OpenAsync("mailto:valerii.sovytskyi@test.com")`?

Also when choosing the app to use amongst all referenced in the "Actual Behavior" Android system offers to use the selected app "Just once" or "Always", but "Always" option doesn't actually remember the app, so you always have to go and search for e.g. Gmail in "more" section.

**Comment by Mikilll94** [comment]
I have also the same problem. I want just to open email apps on Android. Not the other ones.

@jamesmontemagno 
But if I use `Launcher.OpenAsync("mailto:valerii.sovytskyi@test.com")`  then how I will pass the topic, message, and attachments?

**Comment by bill2004158** [comment]
android guid already explained this:

> If you want to ensure that your intent is handled only by an email app (and not other text messaging or social apps), then use the **ACTION_SENDTO** action and include the "**mailto**:" data scheme.

https://developer.android.com/guide/components/intents-common#Email

**Comment by Mikilll94** [comment]
@jamesmontemagno 
Is this fixed in 1.5.3? I have updated Xamarin.Essentials to 1.5.3.1 and I still see that non-email apps (like Google Drive, Bluetooth) are available to select.

**Comment by jamesmontemagno** [comment]
Yes, this is in 1.5.3.1: https://github.com/xamarin/Essentials/pull/1235

So, it depends... if you do just email address with no attachments then you will get an email app that must accept mailto:

If you have attachments then other apps may open, but it is pretty limited. There is no API that I can find that allows only email with attachements.

Closing as implemented.
