### ISSUE TITLE
[Question] Geolocation API - Restrict API to fetch the geo location only from GPS sensor  

### ISSUE THREAD

**Issue by soooraj** [xamarin/Essentials#1082]
Is there any way to restrict the API to fetch the geolocation to be fetched only from GPS sensor? I think right now it is trying to fetch the geolocation from WIFI / Cellular provider in case the GPS sensor fails.

I have posted a stackoverflow post related to the same doubt (https://stackoverflow.com/questions/60090968/retrieve-location-information-only-from-gps-sensor-in-xamarin-android)

Please help.

**Comment by jamesmontemagno** [comment]
Essentials uses both Network and GPS providers: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Geolocation/Geolocation.android.cs#L63-L66 we do not use passive at all or local_database. There is no filtering, however the accuracy that you set will determine what android uses: https://developer.android.com/reference/android/location/Criteria

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Essentials is now in maintenance mode, this will not happen anymore for Xamarin.Essentials. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
