### ISSUE TITLE
[Bug] Open a PWA application with Launcher

### ISSUE THREAD

**Issue by sotnaspina** [xamarin/Essentials#1085]
### Description
When I use Xamarin.Essentials.Launcher I cannot open a PWA application. Is there any way to do this?

What would be the best way to do this?

**Comment by jamesmontemagno** [comment]
Oh Android? iOS? Windows?

Do you have a launch URI for the PWA? Would be similar to opening the browser I assume....

**Comment by jamesmontemagno** [comment]
I installed twitter.com on my Android device as a PWA and then used Launcher.OpenAsync("https://www.twitter.com") and it launched for me.

I don't know if that PWAs can do that on WIndows/iOS. I would look into the config and see if there is native urls to link into it.

**Comment by sotnaspina** [comment]
Hello! @jamesmontemagno Hello! Thank you for your attention. It seems to be working now. Thankful!
