### ISSUE TITLE
dotnet restore fails

### ISSUE THREAD

**Issue by Legends** [xamarin/Essentials#1090]
git cloned Essentials repo, yesterday.

dotnet restore fails --> `Xamarin.Essentials.sln`

**Especially the last line is confusing:**

> D:\SysFolder\Downloads\Essentials>dotnet restore
> D:\SysFolder\Downloads\Essentials\Samples\Samples.Android\Samples.Android.csproj : warning NU1503: Skipping restore for project 'D:\SysFolder\Downloads\Essentials\Samples\Samples.Android\Samples.Android.csproj'. The project file may be invalid or missing targets required for restore. [D:\SysFolder\Downloads\Essentials\Xamarin.Essentials.sln]
> D:\SysFolder\Downloads\Essentials\Samples\Samples.iOS\Samples.iOS.csproj : warning NU1503: Skipping restore for project 'D:\SysFolder\Downloads\Essentials\Samples\Samples.iOS\Samples.iOS.csproj'. The project file may be invalid or missing targets required for restore. [D:\SysFolder\Downloads\Essentials\Xamarin.Essentials.sln]
> D:\SysFolder\Downloads\Essentials\Samples\Samples.UWP\Samples.UWP.csproj : warning NU1503: Skipping restore for project 'D:\SysFolder\Downloads\Essentials\Samples\Samples.UWP\Samples.UWP.csproj'. The project file may be invalid or missing targets required for restore. [D:\SysFolder\Downloads\Essentials\Xamarin.Essentials.sln]
> D:\SysFolder\Downloads\Essentials\DeviceTests\DeviceTests.Android\DeviceTests.Android.csproj : warning NU1503: Skipping restore for project 'D:\SysFolder\Downloads\Essentials\DeviceTests\DeviceTests.Android\DeviceTests.Android.csproj'. The project file may be invalid or missing targets required for restore. [D:\SysFolder\Downloads\Essentials\Xamarin.Essentials.sln]
> D:\SysFolder\Downloads\Essentials\DeviceTests\DeviceTests.iOS\DeviceTests.iOS.csproj : warning NU1503: Skipping restore for project 'D:\SysFolder\Downloads\Essentials\DeviceTests\DeviceTests.iOS\DeviceTests.iOS.csproj'. The project file may be invalid or missing targets required for restore. [D:\SysFolder\Downloads\Essentials\Xamarin.Essentials.sln]
> D:\SysFolder\Downloads\Essentials\DeviceTests\DeviceTests.UWP\DeviceTests.UWP.csproj : warning NU1503: Skipping restore for project 'D:\SysFolder\Downloads\Essentials\DeviceTests\DeviceTests.UWP\DeviceTests.UWP.csproj'. The project file may be invalid or missing targets required for restore. [D:\SysFolder\Downloads\Essentials\Xamarin.Essentials.sln]
> C:\Program Files\dotnet\sdk\3.1.200-preview-014883\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(257,5): warning NETSDK1023: A PackageReference for 'Tizen.NET' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs [D:\SysFolder\Downloads\Essentials\Samples\Samples.Tizen\Samples.Tizen.csproj]
> C:\Program Files\dotnet\sdk\3.1.200-preview-014883\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(257,5): warning NETSDK1023: A PackageReference for 'Microsoft.NETCore.UniversalWindowsPlatform' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs [D:\SysFolder\Downloads\Essentials\DeviceTests\DeviceTests.Shared\DeviceTests.Shared.csproj]
> C:\Program Files\dotnet\sdk\3.1.200-preview-014883\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(257,5): warning NETSDK1023: A PackageReference for 'Tizen.NET' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs [D:\SysFolder\Downloads\Essentials\Xamarin.Essentials\Xamarin.Essentials.csproj]
> C:\Program Files\dotnet\sdk\3.1.200-preview-014883\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(257,5): warning NETSDK1023: A PackageReference for 'Microsoft.NETCore.UniversalWindowsPlatform' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs [D:\SysFolder\Downloads\Essentials\Xamarin.Essentials\Xamarin.Essentials.csproj]
> C:\Program Files\dotnet\sdk\3.1.200-preview-014883\NuGet.targets(124,5): error : **The local source 'C:\Users\MyUser\Downloads\AspNetCore.Docs-master\aspnetcore\fundamentals\host\platform-specific-configuration\samples\2.x\HostingStartupPackage\bin\Debug' doesn't exist. [D:\SysFolder\Downloads\Essentials\Xamarin.Essentials.sln]**

**Comment by jamesmontemagno** [comment]
I just cloned and had no issues here.... Looks like maybe you have some config perhaps as your error is referencing a different project.

```
PS C:\Users\james> cd C:\Users\james\Downloads\Essentials-master\Essentials-master
PS C:\Users\james\Downloads\Essentials-master\Essentials-master> dotnet restore
C:\Users\james\Downloads\Essentials-master\Essentials-master\Samples\Samples.Android\Samples.Android.csproj : warning NU                                                    1503: Skipping restore for project 'C:\Users\james\Downloads\Essentials-master\Essentials-master\Samples\Samples.Android                                                    \Samples.Android.csproj'. The project file may be invalid or missing targets required for restore. [C:\Users\james\Downl                                                    oads\Essentials-master\Essentials-master\Xamarin.Essentials.sln]
C:\Users\james\Downloads\Essentials-master\Essentials-master\Samples\Samples.iOS\Samples.iOS.csproj : warning NU1503: Sk                                                    ipping restore for project 'C:\Users\james\Downloads\Essentials-master\Essentials-master\Samples\Samples.iOS\Samples.iOS                                                    .csproj'. The project file may be invalid or missing targets required for restore. [C:\Users\james\Downloads\Essentials-                                                    master\Essentials-master\Xamarin.Essentials.sln]
C:\Users\james\Downloads\Essentials-master\Essentials-master\Samples\Samples.UWP\Samples.UWP.csproj : warning NU1503: Sk                                                    ipping restore for project 'C:\Users\james\Downloads\Essentials-master\Essentials-master\Samples\Samples.UWP\Samples.UWP                                                    .csproj'. The project file may be invalid or missing targets required for restore. [C:\Users\james\Downloads\Essentials-                                                    master\Essentials-master\Xamarin.Essentials.sln]
C:\Users\james\Downloads\Essentials-master\Essentials-master\DeviceTests\DeviceTests.Android\DeviceTests.Android.csproj                                                     : warning NU1503: Skipping restore for project 'C:\Users\james\Downloads\Essentials-master\Essentials-master\DeviceTests                                                    \DeviceTests.Android\DeviceTests.Android.csproj'. The project file may be invalid or missing targets required for restor                                                    e. [C:\Users\james\Downloads\Essentials-master\Essentials-master\Xamarin.Essentials.sln]
C:\Users\james\Downloads\Essentials-master\Essentials-master\DeviceTests\DeviceTests.iOS\DeviceTests.iOS.csproj : warnin                                                    g NU1503: Skipping restore for project 'C:\Users\james\Downloads\Essentials-master\Essentials-master\DeviceTests\DeviceT                                                    ests.iOS\DeviceTests.iOS.csproj'. The project file may be invalid or missing targets required for restore. [C:\Users\jam                                                    es\Downloads\Essentials-master\Essentials-master\Xamarin.Essentials.sln]
C:\Users\james\Downloads\Essentials-master\Essentials-master\DeviceTests\DeviceTests.UWP\DeviceTests.UWP.csproj : warnin                                                    g NU1503: Skipping restore for project 'C:\Users\james\Downloads\Essentials-master\Essentials-master\DeviceTests\DeviceT                                                    ests.UWP\DeviceTests.UWP.csproj'. The project file may be invalid or missing targets required for restore. [C:\Users\jam                                                    es\Downloads\Essentials-master\Essentials-master\Xamarin.Essentials.sln]
C:\Program Files\dotnet\sdk\3.1.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(257,5): warnin                                                    g NETSDK1023: A PackageReference for 'Tizen.NET' was included in your project. This package is implicitly referenced by                                                     the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs [C:\Users\james\Downloads\Essentials-master\Essentials-master\Samples\Samples.Tizen\Samples.Tizen.csproj]C:\Program Files\dotnet\sdk\3.1.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(257,5): warning NETSDK1023: A PackageReference for 'Microsoft.NETCore.UniversalWindowsPlatform' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs [C:\Users\james\Downloads\Essentials-master\Essentials-master\DeviceTests\DeviceTests.Shared\DeviceTests.Shared.csproj]
C:\Program Files\dotnet\sdk\3.1.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(257,5): warning NETSDK1023: A PackageReference for 'Tizen.NET' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs [C:\Users\james\Downloads\Essentials-master\Essentials-master\Xamarin.Essentials\Xamarin.Essentials.csproj]
C:\Program Files\dotnet\sdk\3.1.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(257,5): warning NETSDK1023: A PackageReference for 'Microsoft.NETCore.UniversalWindowsPlatform' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs [C:\Users\james\Downloads\Essentials-master\Essentials-master\Xamarin.Essentials\Xamarin.Essentials.csproj]   Restore completed in 413.65 ms for C:\Users\james\Downloads\Essentials-master\Essentials-master\Samples\Samples\Samples.csproj.
  Restore completed in 415.43 ms for C:\Users\james\Downloads\Essentials-master\Essentials-master\Samples\Samples.Tizen\Samples.Tizen.csproj.
  Restore completed in 742.54 ms for C:\Users\james\Downloads\Essentials-master\Essentials-master\Xamarin.Essentials\Xamarin.Essentials.csproj.
  Restore completed in 1.59 sec for C:\Users\james\Downloads\Essentials-master\Essentials-master\Tests\Tests.csproj.
  Restore completed in 3.9 sec for C:\Users\james\Downloads\Essentials-master\Essentials-master\DeviceTests\DeviceTests.Shared\DeviceTests.Shared.csproj.
  Restore completed in 5.63 sec for C:\Users\james\Downloads\Essentials-master\Essentials-master\Samples\Sample.Server.WebAuthenticator\Sample.Server.WebAuthenticator.csproj.
PS C:\Users\james\Downloads\Essentials-master\Essentials-master> dotnet --version
3.1.100
```

After that I ran a `msbuild Xamarin.Essentials.sln` and worked great here.

**Comment by Legends** [comment]
@jamesmontemagno 

Yes, the error points to a totally different project, hence I wonder, how is this possible?
What kind of config do you mean? 
Or what could cause such a weird issue?

I mean, what has `Essentials `to do with the local `AspNetCore.Docs-master` repo...nothing.
Very strange. 

If you could give me a hint what could cause such an error, as I can't remember that I have configure anything :-)

**Comment by jamesmontemagno** [comment]
Yeah, i am not sure at all to be honest, could just be some random nuget global config perhaps. We don't use the dotnet command line just yet on Xamarin libraries and apps so you would want to go with:
`msbuild -restore Xamarin.Essentials.sln` 

can you try this.

**Comment by Legends** [comment]
I tried `msbuild restore` same error... hmm.

**Comment by jamesmontemagno** [comment]
Seems like you have a config somewhere trying to find a folder that doesn't exist: https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior check that. Seems like a nuget issue :(

**Comment by Legends** [comment]
Aaa thanks a lot! 👍👍👍

My nuget config under `appdata/roaming` had the following entry, but don't ask me how it got there.

`  <add key="local test" value="C:\Users\xxx\Downloads\AspNetCore.Docs-master\aspnetcore\fundamentals\host\platform-specific-configuration\samples\2.x\HostingStartupPackage\bin\Debug" />`

removing it, solved the issue....

Wonder what I have executed n my machine, in order to be added there..
