### ISSUE TITLE
Can't detect if device is an XBox with Xamarin Essentials

### ISSUE THREAD

**Issue by BillyMartin1964** [xamarin/Essentials#1091]
Please add XBox to the list of devices in Xamarin Essentials Device Info. James Montemagno's Device Info plugin has a great enum of device's if you need one.

There are certain things that need to be done if the device is an XBox as opposed to a Laptop.

You are Microsoft, after all!  (:

**Comment by jamesmontemagno** [comment]
Hmmm could add in IoT, Xbox, SurfaceHub in there. Sees doable.

**Comment by BillyMartin1964** [comment]
Appreciate it, @jamesmontemagno , @Redth  !

**Comment by jamesmontemagno** [comment]
Hmmm I guess the question will be.... the Platform is Windows... but the Idiom would be GameConsole... maybe TV? 

I know for DeviceInfo plugin i put it in platform, but I don't know if that is correct... need to think about it.

**Comment by BillyMartin1964** [comment]
Well, I find myself writing... if it's UWP and if it's XBox... does that help?  LOL

**Comment by mattleibow** [comment]
I think this was added some time ago. The `DeviceIdiom` will now return `TV` on Xbox.

**Comment by BillyMartin1964** [comment]
@mattleibow , are you saying i would have to test for UWP and TV to get XBox? Android and TV to get Fire TV?

**Comment by jamesmontemagno** [comment]
That sounds correct yes
