### ISSUE TITLE
HTML Parser

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#1092]
Hi,

It will be great if you add website parser just like [HTMLAgilityPack](https://html-agility-pack.net/) then user can get the website data similar to what other apps are doing, e.g whatisapp, linkedin, facebook, twitter, etc

This includes, website, title and other meta tags, website images, etc..

Thanks,
[Jassim](https://www.emiratesangels.org)

**Comment by jamesmontemagno** [comment]
This would be out of the scope of essentials as that is already a cross-platform API best left to another library and isn't a platform API. Thanks for the suggestion though.
