### ISSUE TITLE
[Enhancement] UNO (WASM WebAssembly) Plattform specific implementation

### ISSUE THREAD

**Issue by ericbrunner** [xamarin/Essentials#1093]
## Summary
As Droid, iOS and UWP targets the WASM (WebAssembly) target of the UNO Plattform should be officially supported.
Like described for Xamarin.Forms here: https://platform.uno/xamarin-forms/

Current issue that convinced me to file that feature request: https://github.com/unoplatform/uno/issues/2619#issuecomment-583873545

## API Changes
No API changes. 

## Intended Use Case
In WASM project of a UNO Platform based Xamarin.Forms solution

**Comment by jamesmontemagno** [comment]
Uno sits on top of Android/iOS/UWP so by its nature any platform that does this would be supported such as MvvmCross, MonoGame, etc. Having an ever growing list of platforms on top of the library doesn't make a lot of sense to continuously update. The goal is to document the base frameworks Essential is compatible with. As far as new platforms we have a list we track: https://github.com/xamarin/Essentials/issues/662
