### ISSUE TITLE
[Enhancement] Context Menu (activated via long-press/right-click)

### ISSUE THREAD

**Issue by SmartmanApps** [xamarin/Essentials#1098]
## Summary
As far as I can see, context menus are only currently supported in a ListView. I have a need to bring them up in an Entry, and can easily see uses for it in Buttons and Labels as well. e.g. there is currently no way for a user to copy/paste text from a Label in a Xamarin app (I have a partial work-around of I just automatically put the most recent output into Clipboard so that users can paste that. e.g. when they get an error message). Context menu should be activated via long-press on mobile, and right-click on desktop.

## API Changes
1. need LongPress events (which I can see is close to ready https://github.com/xamarin/Xamarin.Forms/issues/3480)
2. need RightClick events. As far as I can tell, not currently supported.
3. add ContextActions to Entry, Label, Button, etc.

## Intended Use Case
The most obvious example is copy/paste text from screen. Select required text, from a Label say, then long-press/right-click brings up context menu from which one can select copy/cut/paste/share etc. Another case is an Entry for barcodes, where one can type in barcode, or (hopefully) do a long-press/right-click and activate a barcode scanner which upon scanning then puts the barcode into the Entry (I'd like to do this directly, but happy to do it from a context menu as that has wider applications, though an option to do directly if only 1 item in the context menu would be good to bypass that step. i.e. just bring up the menu if it contains more than 1 option, otherwise directly run the 1 defined option).

**Comment by mattleibow** [comment]
I think this is more a thing for Xamarin.Forms, since Xamarin.Essentials has no actual UI component?

**Comment by SmartmanApps** [comment]
Hi @mattleibow Yeah, fair comment. Someone suggested raising an issue, and directed me here, so this is where I put it. :-) Totally fine with you moving it or whatever you do in that case (or I can raise it again in a new spot - just let me know where).

**Comment by mattleibow** [comment]
I would just do the same issue here: https://github.com/xamarin/Xamarin.Forms

**Comment by SmartmanApps** [comment]
Ok, done. https://github.com/xamarin/Xamarin.Forms/issues/9540
Is this comment all I need to do to reference the new issue? Want to make sure referenced properly before closing this one, and not sure of the usual protocol.

**Comment by mattleibow** [comment]
That's good enough. The Forms team will take over.

**Comment by SmartmanApps** [comment]
@mattleibow Yeah I see that. That would be good. That issue never appeared when I created this one. It told me there were 4 "similar" issues, but that wasn't one of them (has a fairly interesting idea of what "similar" is!). Thanks.
