### ISSUE TITLE
[Enhancement] Provide accuracy of altitude in GeoLocation API

### ISSUE THREAD

**Issue by janusw** [xamarin/Essentials#1099]
## Summary

Currently, the `Xamarin.Essentials.Location` class only includes one `Accuracy` property, which (I assume) describes the horizontal (or overall?) accuracy of the location. However, the vertical accuracy (concerning the altitude) can differ from the horizontal accuracy quite substantially, e.g. depending on whether a barometer is available or not.

## API Changes

In the simplest case, an additional property `Xamarin.Essentials.Location.AltitudeAccuracy` could be added.

Alternatively, one could introduce a new class for representing altitude information, which could include properties like `Value` and `Accuracy` (or similar). This would be a more disruptive change of API, though.

## Intended Use Case

The primary use case would be any situation where the user needs a good estimate of how accurate his own location is known, both horizontally and vertically. I'm mainly having augmented-reality scenarios in mind, but there are certainly other applications where this is important.

**Comment by janusw** [comment]
For Android, there is [Android.Locations.Location.hasVerticalAccuracy](https://developer.android.com/reference/android/location/Location.html#hasVerticalAccuracy()) and [Android.Locations.Location.getVerticalAccuracyMeters](https://developer.android.com/reference/android/location/Location.html#getVerticalAccuracyMeters()).

For iOS: [CoreLocation.CLLocation.verticalAccuracy](https://developer.apple.com/documentation/corelocation/cllocation/1423550-verticalaccuracy)

**Comment by janusw** [comment]
And finally UWP: [Geocoordinate.AltitudeAccuracy](https://docs.microsoft.com/en-us/uwp/api/windows.devices.geolocation.geocoordinate.altitudeaccuracy)

**Comment by mattleibow** [comment]
Ooh, nice. Is there a PR coming soon?

**Comment by janusw** [comment]
> Ooh, nice. Is there a PR coming soon?

Um, yeah. Probably soon. As you can see I've already started the implementation (but haven't tested it yet). Do you think the commit above is sufficient, or is anything missing?

**Comment by mattleibow** [comment]
It looked good so far. Not sure what Tizen would do - or if they even have this feature. But, yeah, open a PR as soon as you think it good enough. The community will give some extra feedback - if they have any.

Thanks for the work so far!

**Comment by janusw** [comment]
> It looked good so far. Not sure what Tizen would do - or if they even have this feature.

For `LocationExtensions`, there is not even a .tizen.cs file, so I wouldn't really know where to start ...

Another problem that I hit is that on Android the vertical accuracy is only available for recent API levels (26+). I solved that via conditional compilation.

By now this is complete from my side (and rudimentarily tested via the Samples app), so I'll open a PR for it.

**Comment by Redth** [comment]
Thanks for the PR's!
