### ISSUE TITLE
add final tag for release 1.4.0

### ISSUE THREAD

**Issue by janusw** [xamarin/Essentials#1100]
Currently there only is a tag for 1.4.0-pre2 (from January), but it seems there is no final tag for release 1.4.0 yet, and the latest stable release available via nuget is still 1.3.1.

Could you please add a final release for 1.4.0, or are there still any showstoppers for this? It seems development on master has already continued. I have used 1.4.0-pre2 intensively for a couple of weeks and found no issues with it at all ...

**Comment by Mikilll94** [comment]
@jamesmontemagno 
Could you take a look at this? When will be 1.4.0 stable release?

**Comment by janusw** [comment]
I see that the tag has landed at 309d95ffe9b075d350e2a676490e2b489ec6098e. Thanks, @Redth!
