### ISSUE TITLE
[Bug] Launcher.OpenAsync() crashes in iOS 9.3.5

### ISSUE THREAD

**Issue by Magendanz** [xamarin/Essentials#1102]
### Description
On older iOS releases, Launcher.OpenAsync() crashes the app rather than opening the Uri.

### Steps to Reproduce

1. Call method (e.g. Launcher.OpenAsync(new Uri(String.Format(page, authToken)))

### Expected Behavior
Should open browser at target URL.

### Actual Behavior
App immediately quits.  No crash report from AppCenter.

### Basic Information
Works fine in iOS 12.  I haven't checked interim releases.

- Version with issue: iOS 9.3.5
- Last known good version: iOS 12.4.5
- IDE:
- Platform Target Frameworks:
  - iOS:  13.10.0.17
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms v4.4.0.991640
- Affected Devices: iOS

For now, I'm reverting to Device.Open(), but that API is deprecated.

**Comment by Magendanz** [comment]
Okay, I got a crash report from AppCenter:

0xd0000 + 23567048
SIGABRT: Objective-C exception thrown. Name: NSInvalidArgumentException Reason: -[UIApplication openURL:options:completionHandler:]: unrecognized selector sent to instance 0x15e45e80 Native stack trace: 0 CoreFoundation 0x22753933 <redacted> + 150 1 libobjc.A.dylib 0x21eeee17 objc_exception_throw + 38 2 CoreFoundation 0x227592b5 <redacted> + 0 3 CoreFoundation 0x22756ee1 <redacted> + 700 4 CoreFoundation 0x22682238 _CF_forwarding_prep_0 + 24 5 TRC.iOS 0x010b37f0 gc.safepoint_poll + 16090400 6 TRC.iOS 0x01106e08 gc.safepoint_poll + 16431928 7 TRC.iOS 0x01106fac gc.safepoint_poll + 16432348 8 TRC.iOS 0x01329a48 gc.safepoint_poll + 18671480 9 TRC.iOS 0x013299b0 gc.safepoint_poll + 18671328 10 TRC.iOS 0x00175e54 gc.safepoint_poll + 109444 11 TRC.iOS 0x0078e9cc gc.safepoint_poll + 6502140 12 TRC.iOS 0x0078ef40 gc.safepoint_poll + 6503536 13 TRC.iOS 0x0018eeec gc.safepoint_poll + 211996 14 TRC.iOS 0x0077ebc0 gc.safepoint_poll + 6437104 15 TRC.iOS 0x00846f24 gc.safepoint_poll + 7257172 16 TRC.iOS 0x0089c06c gc.safepoint_poll + 7605660 17 TRC.iOS 0x0089bfcc gc.safepoint_poll + 7605500 18 TRC.iOS 0x00636674 gc.safepoint_poll + 5092260 19 TRC.iOS 0x0027b248 gc.safepoint_poll + 1179512 20 TRC.iOS 0x015eb75b gc.safepoint_poll + 21562507 21 TRC.iOS 0x0167c89f gc.safepoint_poll + 22156751 22 TRC.iOS 0x0167f3e7 gc.safepoint_poll + 22167831 23 TRC.iOS 0x00117321 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 15308 24 TRC.iOS 0x00117135 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 14816 25 UIKit 0x26e0311b <redacted> + 1126 26 UIKit 0x26ebe477 <redacted> + 306 27 UIKit 0x26f774c9 <redacted> + 268 28 UIKit 0x26f837db <redacted> + 90 29 UIKit 0x26cc1b1d <redacted> + 84 30 CoreFoundation 0x227156c9 <redacted> + 20 31 CoreFoundation 0x227139cd <redacted> + 280 32 CoreFoundation 0x22713dff <redacted> + 958 33 CoreFoundation 0x22663229 CFRunLoopRunSpecific + 520 34 CoreFoundation 0x22663015 CFRunLoopRunInMode + 108 35 GraphicsServices 0x23c53ac9 GSEventRunModal + 160 36 UIKit 0x26d37189 UIApplicationMain + 144 37 TRC.iOS 0x010c51e8 gc.safepoint_poll + 16162584 38 TRC.iOS 0x011069c8 gc.safepoint_poll + 16430840 39 TRC.iOS 0x01106934 gc.safepoint_poll + 16430692 40 TRC.iOS 0x001933c8 gc.safepoint_poll + 229624 41 TRC.iOS 0x0027b248 gc.safepoint_poll + 1179512 42 TRC.iOS 0x015eb75b gc.safepoint_poll + 21562507 43 TRC.iOS 0x0167c89f gc.safepoint_poll + 22156751 44 TRC.iOS 0x01681347 gc.safepoint_poll + 22175863 45 TRC.iOS 0x015cedb1 gc.safepoint_poll + 21445345 46 TRC.iOS 0x01747e74 xamarin_release_block_on_main_thread + 32492 47 TRC.iOS 0x00142fb3 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 194654 48 libdyld.dylib 0x2230b873 <redacted> + 2

Stack trace:
Runtime.ThrowNSException (System.IntPtr ns_exception)
Runtime.throw_ns_exception (System.IntPtr exc)
(wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)

**Comment by Redth** [comment]
Do you know the actual URL causing the crash?

**Comment by Magendanz** [comment]
Well, it's crashed on every URL that I've tried.  Most in my app are pointing to "https://start.voter-science.com/login/direct?auth={0}" with additional query params.  The simplest is the one on the about box that just links to "https://canvas.voter-science.com/fwd/trc".

**Comment by jamesmontemagno** [comment]
Yes, this would crash because we do not support iOS 9 and we use the Async version of the OpenUrl which was introduced in iOS 10.

However, I think we can do this check. Workaround is to use Browser.OpenAsync and use External, that has the check in it.

**Comment by loic-git** [comment]
Hello,

I am confused about this ticket.
Of what I understand, this issue should be solved since Essentials 1.5.0.
But I still have the problem with 1.5.0 and 1.5.3.2.
In the callstack reported in AppCenter, I can see the call to OpenUrl in async meanwhile the code is executed on iPad with iOS 9.3.5.
The problem is that I don't have an iOS 9.3.5 to investigate and this bug occur in production.

Does the only way to fix it is to use Browser.OpenAsync?
I have the feeling the fix has been done only on Launcher.TryOpenAsync but not Launcher.OpenAsync?

Thanks for your help,

Regards,

Loïc

**Comment by mattleibow** [comment]
I think we only fixed this for some APIs, which was not the best. We have now fixed it for all in #1542
