### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by atrodriguez88** [xamarin/Essentials#1105]
### Description
Geocoding.GetPlacemarksAsync return different AdminArea.

### Steps to Reproduce

```
var lat = 25.7700;
var lon = -80.18;
var placemarks = await Geocoding.GetPlacemarksAsync(lat, lon);
placemark = placemarks?.FirstOrDefault();
```

### Expected Behavior

iOS (Emulator or Device)
`placemark.AdminArea = "FL"`
Android (Emulator or Device)
`placemark.AdminArea = "FL"`

### Actual Behavior

iOS (Emulator or Device)
`placemark.AdminArea = "FL"`

Android (Emulator or Device)
`placemark.AdminArea = "Florida"`
All placemark.AdminArea returns for different latitudes and longitudes are the name city 

### Basic Information

- Nuget Packages: Xamarin.Essentials 1.3.1

**Comment by jamesmontemagno** [comment]
Not much we can do here at that is what is returned by the Android API which should return "CA"/"FL" https://developer.android.com/reference/android/location/Address#getAdminArea() the device may just be returning something different, so it is out of out control. Sorry.
