### ISSUE TITLE
[Bug] [Android] PhoneDialer.Open() with PhoneWords not working on some Android Phones

### ISSUE THREAD

**Issue by maexsp** [xamarin/Essentials#1109]
### Description
Using PhoneDialer.Open(...) does not work correctly on some Android phones when using phonewords as phone numbers. E.g. +1-800-Flowers or +1-514-AUTOBUS 

On Android emulator or E.g. Samsung Galaxy phones the Phone number is correctly interpreted and shown on the Dialpad correctly. So using +1-800-Flowers is shown as +1 800-356-9377.

But when using E.g. Huawai phone P20 lite running Android 9.0 the dialpad opens with number +1800 only. 

### Steps to Reproduce

1. Use Android Huawai phone
2. Execute Xamarin.Essential method: PhoneDialer.Open(+1-800-Flowers)
2. Dialpad shows only "+1800"

### Expected Behavior
Dialpad should show +1-800-Flowers or should show +1 800-356-9377

### Actual Behavior
Dialpad shows only "+1800"

### Basic Information

- Version with issue: Android 9.0, Xamarin.Essentials 1.4.0 , Xamarin.Forms 4.4.0.991640
- Last known good version: 
- IDE: VS2019
- Platform Target Frameworks: <
  - Android: Android 9.0 Pie, API Level 28
- Android Support Library Version:
- Nuget Packages: Xamarin.Essentials 1.4.0 , Xamarin.Forms 4.4.0.991640
- Affected Devices: Android Huawai phones and probably many others also.

**Comment by Redth** [comment]
Seems like maybe a safe approach could be to format the phone number by replacing letters with their number.  Not much we can do about specific implementations of android.  We could build this into the API i suppose.  I'm not sure if there are any negative implications in doing so...

**Comment by jamesmontemagno** [comment]
I guess does it work in some java implementation? If so then we can integrate that, but perhaps it just isn't supported. I don't know how much we want to validate besides throwing an exception, but documentation of it should be numbers only for best results.

**Comment by Mrnikbobjeff** [comment]
I just checked RFC 3966 which outlines the Tel scheme, and phonewords need not be supported by a confirming implementation. In fact they are not even mentioned.

**Comment by maexsp** [comment]
Thanks for the info. I also now checked RFC 3966 and finally phonewords are mentioned indirectly in section [5.1.2.  Alphabetic Characters Corresponding to Digits] at https://tools.ietf.org/html/rfc3966 
Links than to standards of E.161 and T1.703 for phonewords.

**Comment by Mrnikbobjeff** [comment]
Indeed I did miss the reference. The text does still say they are unsupported though

>  In some countries, it is common to write phone numbers with
   alphabetic characters corresponding to certain numbers on the
   telephone keypad.  The URI format does not support this notation, as
   the mapping from alphabetic characters to digits is not completely
   uniform internationally, although there are standards [E.161][T1.703]
   addressing this issue.

**Comment by jamesmontemagno** [comment]
Will close ^ as this would be something pretty tricky for us to handle.
