### ISSUE TITLE
[Enhancement] Consider reopening the AppState ticket

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#1111]
## Summary
I did some work in my offtime on some rejected components, such as the AppState pull request for other projects. I would ask you to reconsider opening a ticket for this feature, as I believe we can flesh out a better API to make it workable.
## API Changes

[Flag]
enum AppState
{
Unknown,
Active,
Foreground,
Background,
PictureInPicture,
Split
}
Some of these flags will never appear on platforms (e.g. PiP on watchos is impossible AFAIK.)
The active flag will designate primary activities or focused applications, so if you were to tab out of an uwp application it may still be in the foreground but no longer active. SplitScreen on Android would have Active, Foreground and Split set for the active splitscreen application, and Active|Split for the secondary application. Android and UWP offer full support for these modes detection wise, on iOS we have the problem that PiP is avaiable over the video player only (please correct me here if I am missing something). We would either have to hook into the VideoPlayer logic by requiring every call to be made through a decorator for the start/stopPiP methods (ugly) or use a weakobservable which has to be setup before video player use on iOS to monitor the pip status proeprties (better and doable if the app requires setting up PIP tracking on iOS). Tizen does not export PiP availability to .NET, so we may not be able to track all states on that platform. Otherwise I believe we could make it work this way. Before I start integrating my work with Essentials again I would like to know whether we can reopen dicussion about this feature.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
