### ISSUE TITLE
[Bug] Essentials 1.4 missing WebAuthenticatorAPI

### ISSUE THREAD

**Issue by djcparker** [xamarin/Essentials#1114]
### Description

Updated to version 1.4 to try the webAuthenticator Api as per https://docs.microsoft.com/en-us/xamarin/essentials/release-notes/1.4

### Steps to Reproduce

1. update any solution to essentials 1.4
2. try to reference any aspect of the webauthenticator api

### Expected Behavior

Classes and functionality would be there

### Actual Behavior

Appears to be missing.  
Checked the source in branches: 1.4.0 and live, no webauthenticator classes.

### Basic Information

- Version with issue: 1.4
- Last known good version: n/a

### Screenshots

n/a

### Reproduction Link

n/a.
Install the nuget version of 1.4

**Comment by jamesmontemagno** [comment]
My fault, thought it made it. Updating Release notes, should be in 1.5.0-pre though
