### ISSUE TITLE
[Bug] Xamarin ios Geocoding.GetLocationsAsync()

### ISSUE THREAD

**Issue by ikeoriaku123** [xamarin/Essentials#1117]
### Description
I have an app I am building in xamarin ios. Whenever I pass an address to this method await Geocoding.GetLocationsAsync($"{street}, {city}, {country}");, it never returns. I have set these
NSLocationAlwaysUsageDescription
your reason to access location.
NSLocationAlwaysAndWhenInUseUsageDescription
your reason to access location
NSLocationWhenInUseUsageDescription
your reason to access location

in the info.plist file as well as enabling location update but for some reason the method never returns. Please can anyone help.

### Steps to Reproduce

1. Pass address
2. Call method Geocoding.GetLocationsAsync()
3. 

### Expected Behavior
Should return list of locations

### Actual Behavior
Method never returns

### Basic Information

- Version with issue: 1.4.0
- Last known good version: None
- IDE: Visual Studio 2019 for Mac
- Platform Target Frameworks: 
  - iOS:  13.2
- Nuget Packages: xamarin.essentials
- Affected Devices: iphone 7 plus

**Comment by CartBlanche** [comment]
@ikeoriaku123  how did you fix this issue?

**Comment by ssm3ll** [comment]
I am still encountered into this problem using latest 1.6.1 version. if i will provide some dummy address it just hangs. I use this API method call to validate provided Address.
