### ISSUE TITLE
Fail to install Xamarin.Essentials on iOS

### ISSUE THREAD

**Issue by anders9ustafsson** [xamarin/Essentials#1118]
### Description
I have tried to upgrade *Xamarin.Essentials* NuGet package from 1.3.1 to 1.4.0. For my iOS projects, the attempt fails with the following error message:

>Failed to add reference. The package 'Xamarin.Essentials' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

Un- and re-installing does not help; error message the same.

### Basic Information

- Version with issue: 1.4.0
- Last known good version: 1.3.1
- IDE: Visual Studio on Windows 16.4.5
- Platform Target Frameworks: 
  - iOS:  10

### Note

It does appear like the package is correctly included in my build if I manually edit the *.csproj* and *packages.config* files with the 1.4.0 version number.

**Comment by Redth** [comment]
Are you able to share a project which reproduces this?

**Comment by jamesmontemagno** [comment]
Thread: https://github.com/xamarin/xamarin-macios/issues/7249

**Comment by anders9ustafsson** [comment]
@Redth I cannot share the failing project, unfortunately. I have tried to create new Xamarin iOS projects, but these templates do not provide the *packages.config* approach, and thus I have no issue upgrading to latest *Xamarin.Essentials*. 

I will follow @jamesmontemagno advice and upgrade the project to package references. 

Thanks both for helping out.

**Comment by jamesmontemagno** [comment]
Will close as the workaround fix is this and open issue with XI

**Comment by grockland** [comment]
Still a problem with VS 16.9 nuget for ios.  Can not update to package references because of incompatible item. Has the original problem of 'System.Drawing.Common.dll' which was not found in the GAC, been solved?

**Comment by bzd3y** [comment]
I am also running in to this problem. Is there any update on this?

**Comment by jamesmontemagno** [comment]
Right click on packages.config and convert to package references. All nugets are compatible.

**Comment by bzd3y** [comment]
@jamesmontemagno Thanks, but when I try that it fails to restore packages in the new style and then seems to fail to roll back. That might be a problem with my project so I'll have to keep looking into what is going on.
