### ISSUE TITLE
[Enhancement] Add Xam.Plugin.Media to Xamarin.Essentials

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Essentials#1119]
## Summary
Xam.Plugin.Media (https://github.com/jamesmontemagno/MediaPlugin) is a very useful plugin in Xamarin development when handling the camera. However, it seems that this plugin is no longer maintained. The last stable version (4.0.1.5) was released 03.08.2018.

My idea is to transfer this plugin to Xamarin.Essentials.

**Comment by Redth** [comment]
It's high on our list!

**Comment by Redth** [comment]
#176 and #177 

We are working on the File Picker functionality first, and we will add photo/video after.
