### ISSUE TITLE
[Bug] Xamarin Forms GetLocationAsync never returns on Android

### ISSUE THREAD

**Issue by dalton5** [xamarin/Essentials#1122]
Hi,

When I use  Geolocation.GetLocationAsync(request); the method never returns.

My code is: 

GeolocationRequest request = new GeolocationRequest(GeolocationAccuracy.Medium, TimeSpan.FromSeconds(10));

 var location = await Geolocation.GetLocationAsync(request);

Do I miss something?

Thanks,

**Comment by jamesmontemagno** [comment]
Can you please provide a reproduction project

**Comment by jamesmontemagno** [comment]
If you are running on an emulator you may need to push the location to it via the emulator settings

**Comment by dalton5** [comment]
Ok I pushed and tried on a phone and it stops but returns null.

What's wrong in my code?

`        public async Task<PlaceDto> GetLocation()
        {

            try
            {
            start: UserDialogs.Instance.HideLoading();
                var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);
                if (status != Plugin.Permissions.Abstractions.PermissionStatus.Granted)
                {
                    var prompt = await UserDialogHelper.CustomPromptAsync(L.Localize("Grant permission for location"));
                    if (prompt == DialogResult.Yes)
                    {
                        if (await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Permission.Location))
                        {

                        }
                        var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);
                        status = results[Permission.Location];
                    }
                }

             

                if (status == Plugin.Permissions.Abstractions.PermissionStatus.Granted)
                {
                    GeolocationRequest request = new GeolocationRequest(GeolocationAccuracy.Medium, TimeSpan.FromSeconds(10));
                    var location = await Geolocation.GetLocationAsync(request);
                    if (location == null)
                        return null; // Always return null*************************
                }

           
            }
            catch (Exception ex)
            {
                await UserDialogHelper.Error(L.Localize("Error in authorization Location"), ex.Message);
            }

            return null;
        }`

**Comment by dalton5** [comment]
Ok i found why. It s because location service was not enabled on the phone.
