### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by reynolds087** [xamarin/Essentials#1125]
### Description

The Android Forms Preview Renderer crashes with a null exception error when using code that contains "FileSystem.AppDataDirectory"

### Steps to Reproduce

1. Build any simple project that renders properly in the Android Forms designer (Preview Renderer)
2. Add the Xamarin.Essentials reference to MainPage.xaml.cs
3. create a new var that points to FileSystem.AppDataDirectory
4.Clean and rebuild the project

### Expected Behavior

The designer should still render the preview correctly

### Actual Behavior

Preview rendering will throw System.NullReferenceException

### Basic Information

- Version with issue: 1.4.0
- Last known good version:
- IDE: Visual Studio Community 2017 v15.9.20
- Platform Target Frameworks: 
  - Android: 9.0 API 28
- Android Support Library Version: 28.0.0.3
- Nuget Packages:NETStandard.Library 2.0.3, Xamarin.Android.Support.Design 28.0.0.3, Xamarin.Android.Support.v4 28.0.0.3, Xamarin.Android.Support.v7.AppCompat 28.0.0.3, Xamarin.Android.Support.v7.CardView 28.0.0.3, Xamarin.Android.Support.v7.MediaRouter 28.0.0.3, Xamarin.Essentials 1.4.0, Xamarin.Forms 4.4.0.991640
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/32722984/75377406-a11b3c00-5886-11ea-875c-b6466ba77c75.png)

**Comment by jamesmontemagno** [comment]
Thanks for the report. You will want to put in a check for design time: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/?pivots=windows#detect-design-mode additionally we recommend turning off DesignTimeVisible on your page.

```csharp
[DesignTimeVisible(false)]
```
