### ISSUE TITLE
[Bug] Sharing content generates exception on Android

### ISSUE THREAD

**Issue by MorneStreicherCapitec** [xamarin/Essentials#1128]
## Description

When creating a new demo Xamarin.Forms project in VS 2017 and add Xamarin.Essentials 1.5.0 to the project, the project compiles and is able to make use of Email functionality.

However, Sharing does not seem to work on Android. I get the exception:

Unhandled Exception:

System.TypeLoadException: Could not set up parent class, due to: Could not load type of field 'Xamarin.Essentials.ShareRequestBase:<PresentationSourceBounds>k__BackingField' (1) due to: Could not resolve type with token 0100008e from typeref (expected class 'System.Drawing.Rectangle' in assembly 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') assembly:System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.Drawing.Rectangle member:(null) assembly:/storage/emulated/0/Android/data/com.companyname.EssensialTestApp1/files/.__override__/Xamarin.Essentials.dll type:ShareRequestBase member:(null) occurred

The source code generating the exception, is:

                    Share.RequestAsync(new ShareTextRequest
                    {
                        Title = "Subject...",
                        Text = "Text..."
                    });

### Steps to Reproduce

Create a Hello world Xamarin.Forms project in Visual Studio 2017, add Xamarin.Essentials and Share some text content.

### Expected Behavior

The content should be shared.

### Actual Behavior

An exception is generated.

### Basic Information

1. Visual Studio 2017 15.9.13
2. Xamarin.Android SDK 9.1.7.0
3. Xamarin Forms 4.4.0.991640
4. Xamarin.Essentials 1.4.0

**Comment by jamesmontemagno** [comment]
Hmmm that is fascinating. Are you using PackageReferences or the older packages.config file for your NuGets?

**Comment by jamesmontemagno** [comment]
I can confirm and open-tk or the nuget doesn't fix it. 

Repro:
[App50.zip](https://github.com/xamarin/Essentials/files/4262939/App50.zip)

**Comment by mattleibow** [comment]
We got a build fix here that magically does corrects all the wrong: https://github.com/xamarin/XamarinComponents/tree/master/Util/Xamarin.Build.TypeRedirector

Just add this to the csproj:
```xml
<PackageReference Include="Xamarin.Build.TypeRedirector" Version="0.1.2-preview" PrivateAssets="all" />
```

It is a build-only thing that does not affect the end usage.

**Comment by jamesmontemagno** [comment]
So, looks like it is a .NET Standard issue and not Xamarin.Android issue from my finding as in VS 2017 Rectangle.Zero is what they use, but it is now Rectangle.Empty :( 

I have a PR building that we can test out soon.

**Comment by jamesmontemagno** [comment]
[nuget.zip](https://github.com/xamarin/Essentials/files/4263371/nuget.zip)
You can give this a try

**Comment by jamesmontemagno** [comment]
Actually, can you try: 
[nuget.zip](https://github.com/xamarin/Essentials/files/4264067/nuget.zip)

Confirmed working well here
