### ISSUE TITLE
[Spec] Added send sms silently API for Android and UWP

### ISSUE THREAD

**Issue by soroshsabz** [xamarin/Essentials#1130]
# Send SMS silently

I think is very good if we can send SMS background and silently when user permit our. this API useful for any app that need send SMS automatically.

It is also available at https://github.com/cjlotz/Xamarin.Plugins

# API

### Properties

| API | Description |
| ------------- | ------------- |
| CanComposeSilently | Gets or sets support of this feature in specific platform. |

### Methods

| API | Description |
| ------------- | ------------- |
| ComposeSilentlyAsync | Send SMS silently. |

# Platform Compatibility
- Target Frameworks: 
  - iOS: Not supported
  - Android: Supported 
  - UWP: Supported 
  - Tizen: Supported
# Backward Compatibility
There is no backward compatibility issue

# Difficulty : Low

**Comment by soroshsabz** [comment]
see cjlotz#47

**Comment by mattleibow** [comment]
As mentioned in https://github.com/xamarin/Essentials/pull/1338#issuecomment-673699506, we will not be adding the ability to send sms messages directly.
