### ISSUE TITLE
[Spec]  Add SMS status

### ISSUE THREAD

**Issue by soroshsabz** [xamarin/Essentials#1131]
# Status of SMS

I think it is very useful to get some status of SMS like sent or delivery

# API

### Properties

| API | Description |
| ------------- | ------------- |
| Status | Gets status of SMS like delivered or sent. |

### Events

| API | Description |
| ------------- | ------------- |
| OnSent | Fire when this SMS receive sent notification |
| OnDelivered | Fire when this SMS receive delivered notification |

# Platform Compatibility
- Target Frameworks: 
  - iOS:  Not supported
  - Android: Support on Android for the API
  - UWP: Support on UWP for the API
  - Tizen: Support on Tizen for the API
# Backward Compatibility
There is no backward compatibility issue

# Difficulty : medium

**Comment by soroshsabz** [comment]
see #1130

**Comment by Happypig375** [comment]
>Tizen: Support on UWP for the API

Tizen: Support on _Tizen_ for the API

**Comment by mattleibow** [comment]
As mentioned in https://github.com/xamarin/Essentials/pull/1338#issuecomment-673699506, we will not be adding the ability to send sms messages directly.
