### ISSUE TITLE
[Bug] App freeze when use SecureStorage.GetAsync without use await

### ISSUE THREAD

**Issue by huangjinshe** [xamarin/Essentials#1140]
### Description
I can't use async and await in my method for some reason. but when I use .Result  get it, it will freeze all app in UWP.
### Steps to Reproduce

1. Save it first:

```
private void Button_Set_Clicked(object sender, EventArgs e)
        {
             SecureStorage.SetAsync("TEST_LANG_INDEX", "0");
            SecureStorage.SetAsync("TEST_ADMIN_NO", "1000");
            SecureStorage.Remove("TEST_PASSWORD_NO");
            SecureStorage.SetAsync("TEST_ISSAVEPASSWORD", "False");
            SecureStorage.SetAsync("TEST_SERVER_IP", "192.168.1.100");

            DisplayAlert("info", "Success!", "cancel");
        }
```

2. Get it , and it will freeze:

```
 private void Button_Get_Clicked(object sender, EventArgs e)
        {
            string a1 = SecureStorage.GetAsync("TEST_LANG_INDEX").Result;
            string a2 = SecureStorage.GetAsync("TEST_ADMIN_NO").Result;
            string a3 = SecureStorage.GetAsync("TEST_PASSWORD_NO").Result;
            string a4 = SecureStorage.GetAsync("TEST_ISSAVEPASSWORD").Result;
            string a5 = SecureStorage.GetAsync("TEST_SERVER_IP").Result;

             DisplayAlert("info", "Success!", "cancel");
        }
```

### Expected Behavior
I expect it not freeze.
### Actual Behavior
It freeze my app.
### Basic Information

- Version with issue:1.5.0
- Last known good version: Nope
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
- UWP:  **1903**

**Comment by Happypig375** [comment]
Use an async event handler. [Do NOT use `Result`.](https://stackoverflow.com/questions/17248680/await-works-but-calling-task-result-hangs-deadlocks)
```cs
        private async void Button_Set_Clicked(object sender, EventArgs e)
        {
            await SecureStorage.SetAsync("TEST_LANG_INDEX", "0");
            await SecureStorage.SetAsync("TEST_ADMIN_NO", "1000");
            SecureStorage.Remove("TEST_PASSWORD_NO");
            await SecureStorage.SetAsync("TEST_ISSAVEPASSWORD", "False");
            await SecureStorage.SetAsync("TEST_SERVER_IP", "192.168.1.100");

            DisplayAlert("info", "Success!", "cancel");
        }
```
```cs
        private async void Button_Get_Clicked(object sender, EventArgs e)
        {
            string a1 = await SecureStorage.GetAsync("TEST_LANG_INDEX");
            string a2 = await SecureStorage.GetAsync("TEST_ADMIN_NO");
            string a3 = await SecureStorage.GetAsync("TEST_PASSWORD_NO");
            string a4 = await SecureStorage.GetAsync("TEST_ISSAVEPASSWORD");
            string a5 = await SecureStorage.GetAsync("TEST_SERVER_IP");

             DisplayAlert("info", "Success!", "cancel");
        }
```
This issue is not specific to Xamarin.Essentials and also there is nothing that this library can do about this. This issue should be closed.

**Comment by jamesmontemagno** [comment]
See above ^

**Comment by TheNicor** [comment]
Why did you close this issue ?
It is an issue.
It is ok with Android but freeze with UWP.
II don't want to use an async void.

**Comment by TheNicor** [comment]
If you try to work no async the application freeze

**Comment by jamesmontemagno** [comment]
If you are inside of a click handler you must use as `async void` as you can not change it to a Task. This is just how events are unfortunately. Using .Result locks your user interface.

Please read through https://devblogs.microsoft.com/xamarin/getting-started-with-async-await/ as this will  help guide you in setting up your code.

**Comment by sekhonitconsultants** [comment]
Getting very same issue on UWP/ - works fine for Android and iOS,
For UWP data is not being saved to secure storage on Win10 latest build.
No exception no errors, tried with all suggested ways mentioned in various threads, looks like some is broken in the secure storage library.
