### ISSUE TITLE
[Bug] Cannot install in Nuget

### ISSUE THREAD

**Issue by JimmyPun610** [xamarin/Essentials#1141]
### Description
Cannot install in Nuget
### Steps to Reproduce

1.  Find Xamarin.Essential 1.5
2.  Install to all projects

### Expected Behavior
Installation complete
### Actual Behavior
Package Manager Console return this message
Failed to add reference. The package 'Xamarin.Essentials' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

### Basic Information

- Version with issue: 1.4, 1.5
- Last known good version: 1.3.1
- IDE: Visual Studio 2019

**Comment by jamesmontemagno** [comment]
We do have a fix incoming for 1.5.1 that I believe addresses it, however our recommendation is to update to PackageReferences in your projects as this will get rid of the issue.
