### ISSUE TITLE
Error running OrientationSensor : System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Berets** [xamarin/Essentials#1148]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
System.ArgumentOutOfRangeException: 'Specified argument was out of the range of valid values.
Parameter name: index'

### Steps to Reproduce
1. Create an empty  XamarinForms project
2. Add every permission on Android project
3. In MainPage constructor add:

                       OrientationSensor.ReadingChanged += (sss, eee) =>
                        {
                            lblLatConv.Text = eee.Reading.Orientation.X.ToString();
                            lblLongConv.Text = eee.Reading.Orientation.Y.ToString();
                            lblAltConv.Text = eee.Reading.Orientation.Z.ToString();
                        };
                        
                        OrientationSensor.Start(SensorSpeed.Fastest);
Run on device, but also in simulator

### Expected Behavior
Return Quaternion
### Actual Behavior
System.ArgumentOutOfRangeException
### Basic Information

- Version with issue: 1.5.0
- Last known good version: Unknown
- IDE: Visual studio 2019
- Platform Target Frameworks:
  - iOS:  Not tested
  - Android: 28 
  - UWP:  Not tested
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
Hmmm interesting. Do you have the stack trace?

The only thing I could think is that the sensor isn't returning all 4, we should probably check the length of it.

**Comment by Berets** [comment]
**System.ArgumentOutOfRangeException:** 'Specified argument was out of the range of valid values.
Parameter name: index'

03-06 10:04:12.082 D/Mono    (21502): DllImport attempting to load: '/system/lib64/liblog.so'.
03-06 10:04:12.085 D/Mono    (21502): DllImport loaded library '/system/lib64/liblog.so'.
03-06 10:04:12.085 D/Mono    (21502): DllImport searching in: '/system/lib64/liblog.so' ('/system/lib64/liblog.so').
03-06 10:04:12.085 D/Mono    (21502): Searching for '__android_log_print'.
03-06 10:04:12.085 D/Mono    (21502): Probing '__android_log_print'.
03-06 10:04:12.086 D/Mono    (21502): Found as '__android_log_print'.
03-06 10:04:12.102 I/MonoDroid(21502): UNHANDLED EXCEPTION:
03-06 10:04:12.109 I/MonoDroid(21502): System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
03-06 10:04:12.109 I/MonoDroid(21502): Parameter name: index
03-06 10:04:12.109 I/MonoDroid(21502):   at Android.Runtime.JavaArray`1[T].get_Item (System.Int32 index) [0x0000d] in <4a189ea3b82b48a089ac9002b2abc206>:0 
03-06 10:04:12.109 I/MonoDroid(21502):   at Xamarin.Essentials.OrientationSensorListener.Android.Hardware.ISensorEventListener.OnSensorChanged (Android.Hardware.SensorEvent e) [0x00000] in d:\a\1\s\Xamarin.Essentials\OrientationSensor\OrientationSensor.android.cs:46 
03-06 10:04:12.109 I/MonoDroid(21502):   at Android.Hardware.ISensorEventListenerInvoker.n_OnSensorChanged_Landroid_hardware_SensorEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e) [0x00011] in <4a189ea3b82b48a089ac9002b2abc206>:0 
03-06 10:04:12.109 I/MonoDroid(21502):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.18(intptr,intptr,intptr)
03-06 10:04:12.134 W/GpsPen.Android(21502): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
03-06 10:04:12.142 D/Mono    (21502): DllImport searching in: '__Internal' ('(null)').
03-06 10:04:12.142 D/Mono    (21502): Searching for 'java_interop_jnienv_throw'.
03-06 10:04:12.142 D/Mono    (21502): Probing 'java_interop_jnienv_throw'.
03-06 10:04:12.142 D/Mono    (21502): Found as 'java_interop_jnienv_throw'.
**System.ArgumentOutOfRangeException:** 'Specified argument was out of the range of valid values.
Parameter name: index'

**Comment by jamesmontemagno** [comment]
Perfect, this is great. I think the sensor is returning invalid data, which is strange. I have added some checks for the next release.

If you want to pull down this nuget and test it out that would be great: https://dev.azure.com/xamarin/public/_build/results?buildId=15005&view=artifacts&type=publishedArtifacts

**Comment by Redth** [comment]
Fixed!
