### ISSUE TITLE
[Bug] Missing WebAuthenticator docs

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Essentials#1159]
There is no documentation for the new WebAuthenticator API.

https://docs.microsoft.com/en-us/xamarin/essentials/

**Comment by jamesmontemagno** [comment]
We are filling in the docs now :)

**Comment by mrlacey** [comment]
There are now docs at https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.webauthenticator

But they're very bare bones. Where can I find more information about using WebAuthenticator? Is there a sample anywhere?

**Comment by Mikilll94** [comment]
@mrlacey 
Because these are API docs. The main docs are still missing.

**Comment by jamesmontemagno** [comment]
There is a sample inside of this repo with a full ASP.NET Core backend :) We are working on full docs and blog now for it :)

**Comment by jamesmontemagno** [comment]
Now live: https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator
