### ISSUE TITLE
[Bug] Permissions.RequestAsync 

### ISSUE THREAD

**Issue by nicolas-garcia** [xamarin/Essentials#1161]
### Description

**The issue is only present on iOS.**

On iOS, requesting the permission `Permissions.LocationWhenInUse` while location service is disabled, the system dialog asking the user to open the settings close by itself and do nothing. 

### Steps to Reproduce

The code for requesting the permission :

```cs
var permissionStatus = await Permissions.CheckStatusAsync<Permissions.LocationWhenInUse>();
if (permissionStatus != PermissionStatus.Granted)
{
    var requestResult = await Permissions.RequestAsync<Permissions.LocationWhenInUse>();
    if (requestResult != PermissionStatus.Granted)
        throw new PermissionException($"Permission '{typeof(Permissions.LocationWhenInUse).Name}' request to the user failed with status '{requestResult}'");
}
```

1. Disable the location service on the device in Settings > Privacy > Location Services >Switch off Location Services
2. Call the code I wrote above in your app (or use the repro app)
3. Enjoy the issue 😄 

### Expected Behavior

The dialog should not close by itself I suppose? And clicking on "Settings" button should open the settings.

### Actual Behavior

The dialog close itself randomly, and if I click on "Settings" button, it just close and nothing happen.

### Basic Information

- Version with issue: 1.5.1
- Last known good version:
- IDE: Visual Studio for Mac 8.4.8
- Platform Target Frameworks: 
  - iOS:  latest (13.2 I guess ?)
  - Android: Seems OK.
  - UWP: Not tested
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

See attached .zip for video of the issue.

### Reproduction Link

The following zip contains a video of the issue and a repro solution.
(I'm sorry, I forgot to switch the emulator language to English)

[RequestLocationBugRepro.zip](https://github.com/xamarin/Essentials/files/4310872/RequestLocationBugRepro.zip)

**Comment by jamesmontemagno** [comment]
Temp workaround would be to check if it is disabled before requesting

**Comment by jamesmontemagno** [comment]
My fix wont request it anymore and let the developers handle it, which i think is best IMHO.
