### ISSUE TITLE
Ability to retrieve info about iOS/Android latest app info installed on the respective store.

### ISSUE THREAD

**Issue by developer9969** [xamarin/Essentials#1165]
## Summary
Ability to retrieve info about iOS/Android latest app info installed on the respective store.

## Intended Use Case
In order to force an update it would be nice if xamarin essentials in their "version Tracking"  could also have a method  "GetAppInfoFromStore" this will return all possible info about the app  eg:

Version number
Supported version of the app eg (Min MarshMallow  Default= Android 10

This will allow to easily implement functionalities like force update

thanks

**Comment by jamesmontemagno** [comment]
I don't think there is actually an API in each of the OSes to do this. Also an app may not be on an official app store or could just be internal. Also app stores now have smaller incremental rollouts of apps and betas, so tricky. 

What I have seen best is that a developer have the active version on their server that they query. 

Based on this, wont be on our feature list to add, but would make a great community plugin. Thanks for the suggestion.

**Comment by developer9969** [comment]
Thanks for the feedback I understand
