### ISSUE TITLE
[Bug] [iOS] Launcher.OpenAsync doesn't actually open the file

### ISSUE THREAD

**Issue by ChaseFlorell** [xamarin/Essentials#1166]
### Description
Based on the documentation for `Launcher` under the _Files_ section
>This features enables an app to request other apps to open and view a file.

Using the following code, when a file is downloaded to the local device, the save dialog is shown and allows me to pick where I want to save the file, but the file isn't actually opened. I have to manually leave the app and locate the file in order to open it.

```csharp
public async Task OpenFile(string url, string fileName)
{
    _client = _client ?? _httpClientFactory.Create();

    if (!url.StartsWith("https", StringComparison.OrdinalIgnoreCase))
        throw new InvalidOperationException("iOS and Android Require Https");

    var file = Path.Combine(FileSystem.CacheDirectory, fileName);

    var bytes = await _client.GetByteArrayAsync(url);
    File.WriteAllBytes(file, bytes);
    
    var target = new ReadOnlyFile(file);
    var request = new OpenFileRequest{File = target};
    await Launcher.OpenAsync(request);
}
```

I have attempted to add the following to my info.plist, but it didn't make any difference.
```xml
    <key>LSSupportsOpeningDocumentsInPlace</key>
    <true/>
```

### Steps to Reproduce

1. use the method in the above example to open a url

### Expected Behavior
Should prompt me to save the file, and once saved, should open the file

### Actual Behavior
Prompts to save, and saves. Does NOT open the file

### Basic Information

- Version with issue: 1.5.1
- Last known good version: n/a
- IDE: Rider
- Platform Target Frameworks: 
  - iOS:  xcode 11.3.1 
  - Android: not tested
  - UWP:  not tested
- Android Support Library Version: n/a
- Nuget Packages:
- Affected Devices: tested on iOS 13.3 sim

**Comment by jamesmontemagno** [comment]
What is the file extension/type of file you are trying to launch?

**Comment by jamesmontemagno** [comment]
in the sample app when you do a .txt file you get
![image](https://user-images.githubusercontent.com/1676321/76453273-cd0ee500-638f-11ea-92f5-527216a450a6.png)

**Comment by ChaseFlorell** [comment]
I’ve tried PDF, XLXS, ZIP, and JSON
If I open them from the files app, I can see it I believe as a preview. 
If I just run the code in the method, it saves and then the dialog disappears, returning me to where I left off in the app.

I can get as far as you have in the screenshot, but the documentation says

> This features enables an app to request other apps to open and view a file.

 Which to me indicates that it should actually open the file.

**Comment by jamesmontemagno** [comment]
yeah, i mean each app handles what it can actually do... so the files app may just preview it. If you open xlxs in office it should open it too. You can also try share, which will send the file to that app too. 

https://developer.apple.com/documentation/uikit/uidocumentinteractioncontroller is what we use. So from what you describe sounds like working as expected.

**Comment by jamesmontemagno** [comment]
Going to close out as expected behavior based on file type. Let me know if you need me to re-open.

**Comment by Filisyevav** [comment]
I faced the same issue. When I try to open a txt or jpeg file, I get the same as on the screenshot above and that's it - no option to open a file in an appropriate app, moreover 'Save to Files' button doesn't work. Please note that I am able to open the same image file in Photos.
@jamesmontemagno could you please explain what the expected behavior is? I'm asking because I believe that this popup doesn't work as documentation states (it cannot open any file actually).

**Comment by Softtinn** [comment]
@jamesmontemagno We have the same problem. In iOS we get the choice to save the file locally, but after doing so it doesn't open the file automatically. A better option would have been a similar behavior like android, where you get to choose from a number of apps to view your pdf in.  The MIME type is application/pdf.
