### ISSUE TITLE
[Enhancement] Version Tracking Release Date

### ISSUE THREAD

**Issue by davidadams1975** [xamarin/Essentials#1168]
## Summary
Version Tracking release date would provide access to the application's version/build date.

## API Changes

Please add:
VersionTracking.CurrentVersionReleaseDate;

Usage:
var currentReleaseDate = VersionTracking.CurrentVersionReleaseDate;
Label.Text = currentReleaseDate.ToString();

We are currently doing the following to get the release date:
Assembly assembly = Assembly.GetExecutingAssembly();
FileInfo fileInfo = new FileInfo(assembly.Location);
DateTime lastModified = fileInfo.LastWriteTime;

However, this method doesn't work with UWP in release mode with the .NET Native Tool Chain.

## Intended Use Case
I want to be able to display the Release date for the current version of the application on the about page.

Thank you for your consideration.

**Comment by jamesmontemagno** [comment]
Thanks for the recommendation. This isn't a native API to abstract and what you wrote is already cross-platform. So we wouldn't apply this to Essentials as technically that could be compile time and not actual release date on the store.
