### ISSUE TITLE
[Bug] Permissions failing to set camera permission for use in CrossMedia plugin

### ISSUE THREAD

**Issue by BenPrice851** [xamarin/Essentials#1169]
### Description
I'm currently building an app which has a custom content view that needs to have it's binding context set to a model stored in another view model.

My issue is that when attempting to take a photo, we request permission using the Essentials Permissions, grant said permission to use the camera and then immediately after this the CrossMedia TakePhotoAsync method throws an exception of 

> ex = {Plugin.Media.Abstractions.MediaPermissionException: Camera permission(s) are required.

### Steps to Reproduce

1. Create your class with your permission and take photo methods inside of it, as well as the command to do so.
2. Add your class as a property to a view model bound to your main page (or other xaml.cs)
2. Create a custom view with a button that triggers the take photo command 
3. Add the custom control to your main page (or other xaml) and bind it's binding context to your class property.

### Expected Behavior
When clicking the take photo button we should get asked for permission, and then upon accepting permission be able to take a photo.

### Actual Behavior
When clicking the take photo button we get asked for permission, and then upon accepting permission and trying to take a photo the app throws an error saying we don't have permission to use the camera.

### Basic Information

- Version with issue: 1.5.0
- IDE: Visual Studio 2019
- Platform Target Frameworks:
  - Android: 9.0
- Nuget Packages: Xam.Plugin.Media
- Affected Devices: HUAWEI CPN-W09

### Reproduction Link
I have created a sample project which recreates the issue below
[https://github.com/BenPrice851/IssueProjects](url)

**Comment by BenPrice851** [comment]
This turned out to be an issue where I had not included the CurrentActivity NuGet plugin, which caused my errors.

**Comment by MitchBomcanhao** [comment]
You might also want to get the newer Media plugin.
