### ISSUE TITLE
HowTo: Use Preferences or something else to expose custom settings in the Device OS Settings for our apps?

### ISSUE THREAD

**Issue by dfarrNTST** [xamarin/Essentials#1175]
With Xamarin Forms, we need to be able to create custom settings for our app that allows a user to go into the device's OS settings, find our app, and set custom app settings without having to run our app first...how do we accomplish this with Xamarin Essentials Preferences or another Xamarin pattern?

We've only seen ways to access settings by creating our own custom classes and pages to manage this data within the app and save it with our own code...but that requires the user having to run the app first...we are not able to do that for one of our apps.

For example, we need to create an "Environment" app setting for our app that shows up in the device's "Settings" app area that the user can set a value of "Dev", "QA", or "Production" before running the app.  When our app launches it always immediately redirects to an OAuth url for authentication as the very first action...we are not allowed to let the user see or touch the app before authenticating, such as showing a custom settings page.  We must know which of the 3 url's to redirect to based upon the "Environment" setting.  How do we expose an Application settings for iOS and Android so the user can go to the device's "Settings" app, find our app, and set the settings for the app.  We see this for many other apps on our devices but have not found any guidance on how to accomplish this with Xamarin Forms.  This also allows the user to change the app's OAuth redirection to a different environment whenever they need to outside of the app.

**Comment by jamesmontemagno** [comment]
Yes, on iOS you can do this outside of your app. It is the only platform that you can actually. You can follow some of the guides I outline here: https://jamesmontemagno.github.io/SettingsPlugin/SystemSettings.html

I will integrate this into the docs for reference though.
