### ISSUE TITLE
[Bug] “Link SDK Frameworks only” linker option causes compile error in iOS

### ISSUE THREAD

**Issue by poliahrameshkumar** [xamarin/Essentials#1176]
### Description
I am using Xamarin.Essentials in my project. If I have linker option as "Link SDK Frameworks only", I am getting the below error.

MTOUCH: Error MT2101: Can't resolve the reference 'System.Void Xamarin.Essentials.ShareRequestBase::set_Title(System.String)', referenced from the method 'System.Void *ViewModel/<<get_ExportCommand>b__52_0>d::MoveNext()' in 'Xamarin.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101) (*.iOS)

If linker option is "Don't link" It compiles without error. May I know how can I resolve the error as "Don't link" linker option increases the app size considerably.
### Steps to Reproduce

1. Install latest version of Xamarin.Essentials 1.5.1
2. Set linker option as Link SDK Frameworks only
3. Try to build. It gives the above error

### Expected Behavior
Runs with out compilation errors
### Actual Behavior
Gives compilation errors
### Basic Information

- Version with issue:1.5.1
- Last known good version:None
- IDE: VisualStudio for Mac
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
Hey there! Can you let us know what version of Visual Studio for Mac and Xamarin.iOS you have?

Did you write any code at all accessing Xamarin.Essentials? A small repo would be nice if you can add.

**Comment by poliahrameshkumar** [comment]
@jamesmontemagno I am using upto date visual studio and xamarin.ios as of now and below is the code I am using.

await Share.RequestAsync(new ShareFileRequest
                {
                    Title = "Results",
                    File = new ShareFile(csvFile),
                    PresentationSourceBounds = DeviceInfo.Platform == DevicePlatform.iOS && DeviceInfo.Idiom == DeviceIdiom.Tablet
                        ? new System.Drawing.Rectangle((int) Application.Current.MainPage.Width - 110, 60, 0, 0)
                        : System.Drawing.Rectangle.Empty
                });

**Comment by poliahrameshkumar** [comment]
Another nuget package was internally using xamarin.essentials 1.0.0. App tried to take 1.0.0 version of the package instead of 1.4.0. I think that is the issue. If I remove that package, share is working fine. So, can someone please let me know how to force the app to take latest version instead of old package which is in another package?

**Comment by jamesmontemagno** [comment]
Hmmm that is a good question. Additional types and items may have been added since 1.0.0 so they may just need to upgrade and put out a new library. Is it one of ours?

**Comment by poliahrameshkumar** [comment]
No. It is not one of yours. The essentials in the package was upgraded to latest version. Now it is working fine. So, this is not xamarin.essentials bug though earlier we had the similar error when upgrading to 1.4.0 and updating xamarin.ios fixed the issue. Thank you.

**Comment by poliahrameshkumar** [comment]
It is not a bug but version conflict issue.
