### ISSUE TITLE
Location.Altitude not consistent between Android and iOS

### ISSUE THREAD

**Issue by janusw** [xamarin/Essentials#1177]
### Description

This is an issue that I have been wondering about for some time already (and by now I think I have some idea how the behavior comes about) ...

I observe strongly differing heights being returned in Location.Altitude on Android and iOS:

* On iOS I obtain what seems to be the correct altitude above mean sea level (MSL). If I stand on the ground, it agrees with the elevation obtained via the Google Elevation API.
* On Android I get height values that are roughly 50m above the iOS values. The difference is not exactly 50m, of course, but it always seems to be in the same order of magnitude and larger than the reported accuracies.

### Steps to Reproduce

1. Open the Xamarin.Essentials app on an Android and an iOS device.
2. Select the 'Geolocation' page.
3. Hit 'Refresh'.
4. Observe the Altitude.
5. Possibly compare to the altitude reported by other apps or devices.

### Expected Behavior

The altitude values obtained on Android and iOS should be compatible with each other (within accuracy), and in particular they should be given with respect to the same reference level.

### Actual Behavior

The altitudes are not compatible. I suspect that different reference points are used. The difference is roughly the size of the undulation at my location (central Europe) AFAICT.

### Basic Information

- Version with issue: 1.4.0, 1.5.0, 1.5.1 
- Last known good version: ---
- IDE: VS for Mac
- Platform Target Frameworks:
  - iOS:  8.0
  - Android: 10.0
  - UWP:  ---
- Android Support Library Version: ?
- Nuget Packages: ?
- Affected Devices: tried e.g. on Zenfone 6, iPhone 8

**Comment by janusw** [comment]
Checking the documentation of the relevant API calls ...

* [Xamarin](https://docs.microsoft.com/de-de/dotnet/api/xamarin.essentials.location.altitude?view=xamarin-essentials#Xamarin_Essentials_Location_Altitude): `Gets the Altitude, if available in meters above sea level.`
* [Android](https://developer.android.com/reference/android/location/Location#getAltitude()): `Get the altitude if available, in meters above the WGS 84 reference ellipsoid. If this location does not have an altitude then 0.0 is returned.`
* [iOS](https://developer.apple.com/documentation/corelocation/cllocation/1423820-altitude): `The altitude, measured in meters. Positive values indicate altitudes above sea level. Negative values indicate altitudes below sea level.`

I think this pretty much explains the differences I'm seeing: The WGS84 ellipsoid is not identical to mean sea level (MSL)! The difference between both is called undulation. iOS gives the correct value wrt the Xamarin documentation. Android is wrong.

Any ideas on how to fix this?

**Comment by janusw** [comment]
Here is a nice article that explain different altitude references:

https://www.esri.com/news/arcuser/0703/geoid1of3.html

**Comment by janusw** [comment]
It seems we have to correct for the geoid altitude offset wrt to the WGS84 ellipsoid.

One possible way to go:
* rely on [GeographicLib](https://geographiclib.sourceforge.io)
* this has [C# bindings](https://geographiclib.sourceforge.io/html/NET/)
* alternatively there also is a [port to C#](https://github.com/suryapratap/GeographicLib)
* the library can be used to calculate the [geoid height](https://geographiclib.sourceforge.io/html/geoid.html)

**Comment by janusw** [comment]
> One possible way to go:
> 
>     * rely on [GeographicLib](https://geographiclib.sourceforge.io)
> 
>     * this has [C# bindings](https://geographiclib.sourceforge.io/html/NET/)
> 
>     * alternatively there also is a [port to C#](https://github.com/suryapratap/GeographicLib)

There is another more recent C# port: https://github.com/PyxisInt/GeographicLib
This one is even available via nuget: https://www.nuget.org/packages/PyxisInt.GeographicLib/

**Comment by janusw** [comment]
It seems that both of the C# ports actually do not include the `Geoid` class. So, regarding GeographicLib, only the original C# wrapper appears to be feasible for calculating the geoid height.

One other alternative might be [GeoidHeightsDotNet](https://github.com/MatejFranceskin/GeoidHeightsDotNet) (also available via nuget).

**Comment by jamesmontemagno** [comment]
This is super good information! I think this is just best left documented and enable the developer to implement the conversion as we can't take additional dependencies in the library.

I have sent a PR to the docs to point this out! <3

**Comment by janusw** [comment]
> I have sent a PR to the docs to point this out! <3

Where's that PR? Could you provide a link, please?

**Comment by jamesmontemagno** [comment]
Here is what I am adding, we have a private staging area we use for internal prs:

## Platform Differences

Altitude is calculated differently on each platform.

# [Android](#tab/android)

On Android, [altitude](https://developer.android.com/reference/android/location/Location#getAltitude()), if available, is returned in meters above the WGS 84 reference ellipsoid. If this location does not have an altitude then 0.0 is returned.

# [iOS](#tab/ios)

On iOS, [altitude](https://developer.apple.com/documentation/corelocation/cllocation/1423820-altitude) is measured in meters. Positive values indicate altitudes above sea level, while negative values indicate altitudes below sea level.

# [UWP](#tab/uwp)

On UWP, altitude is returned in meters. See the [AltitudeReferenceSystem](https://docs.microsoft.com/uwp/api/windows.devices.geolocation.geopoint.altitudereferencesystem#Windows_Devices_Geolocation_Geopoint_AltitudeReferenceSystem) documentation for more information.

-----

**Comment by janusw** [comment]
> Here is what I am adding, we have a private staging area we use for internal prs:

Thanks for the info. A docu fix is certainly a good first step, but it's not sufficient IMHO. In the end I need reliable height values across different platforms (iOS and Android at least). They need to be normalized to the same reference level, otherwise one can not compare them.

I'm not really happy with this issue being closed so fast, even before the documentation is fixed (let alone the actual root problem). Could you maybe reopen it?

**Comment by jamesmontemagno** [comment]
Re-opened for discussion.

I do agree that they should be normalized across each platform. The library can not take a third-party dependency. In this case there are only two options that I see:

1.) Document the differences in altitude per platform.
2.) Remove Altitude as it can not be provided as a consistent measurement. 

I tend towards option 1 as this is what developers would need to do anyways if they were accessing the native APIs.

I looked across other abstractions online for Xamarin, Flutter, React Native, and Cordova and no one does any conversion.

**Comment by jamesmontemagno** [comment]
Also sorry as sometimes I go to quick to close things.

**Comment by janusw** [comment]
> Re-opened for discussion.

Thanks!


> I do agree that they should be normalized across each platform. The library can not take a third-party dependency. In this case there are only two options that I see:
> 
> 1.) Document the differences in altitude per platform.

This is the least one can do. Since it's simple and you already seem to have a PR, this should be done right away, regardless of whether one takes any further steps.


> 2.) Remove Altitude as it can not be provided as a consistent measurement.

I don't think this is a reasonable option. Having altitudes that differ across platforms (but are documented as such) is still way better than having nothing.

Additional options that come to mind:

3.) Check if one can get the altitude in iOS relative to the ellipsoid instead of MSL.

I'm not sure if it is possible, but in any case altitude above ellipsoid is usually what's returned by the GPS chip, so iOS might have the information. This would be a bit of a downgrade (since height above MSL is what is usually needed), but at least it would be consistent.

4.) Convert the altitude on Android to MSL.

From a user perspective, this would be my favorite solution by far, but it involves non-trivial conversions. If third-party dependencies are not an option, then one might add the conversion code into XE directly, if it is sufficiently compact.

**Comment by jamesmontemagno** [comment]
Is there anything you would like added to the PR for docs?

**Comment by janusw** [comment]
> Is there anything you would like added to the PR for docs?

No, the additions you proposed above sound good to me.

**Comment by jamesmontemagno** [comment]
merging in now

**Comment by janusw** [comment]
> merging in now

Thanks for your support here.
Is there any commit I should see? Because I don't ...

You wrote earlier:

> Here is what I am adding, we have a private staging area we use for internal prs:

So I assume the commit is still in your private staging area? Since this is a public issue report, why not use a public PR, so that it can get public reviews ...?

**Comment by jamesmontemagno** [comment]
1.)
It is live now: https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?context=xamarin%2Fandroid&tabs=android#platform-differences

2.) It is just a flow the docs team has for internal PRs. I don't make the policy. This is why I recommend community send down a PR instead of filing an issue. Makes everything easier!

**Comment by janusw** [comment]
> 1.)
> It is live now: https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?context=xamarin%2Fandroid&tabs=android#platform-differences

Great, thank you!

Apart from the place where you added it (in the general Geolocation docu), I think the platform differences would also be useful (maybe even more so) in the API docu of Location.Altitude:

https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.location.altitude

Since previously you only told me _what_ you're adding but not _where_, I was not able to give this feedback earlier.


> 2.) It is just a flow the docs team has for internal PRs. I don't make the policy, but I will inquire about this type of change because I would like some public feedback sometimes.

Well, I'm not trying to argue with your policy. My stupid questions are probably just a result of my ignorance of your internal processes (or their intransparency ;)

So, it seems like the API docu is part of the Xamarin.Essentials repo, but the general Xamarin docu that you modified is not? Does is have a separate repo that is publicly visible, or is it entirely private?

**Comment by jamesmontemagno** [comment]
If you would like you can make a PR to the develop branch as the docs live here, else I will do it this week.

Correct, the API docs live here and the general docs live: https://github.com/microsoftdocs/xamarin-docs You can hit edit on any page on the docs to do a PR!
![image](https://user-images.githubusercontent.com/1676321/77236916-42dd3280-6b80-11ea-9a53-141700868bb1.png)

**Comment by janusw** [comment]
> If you would like you can make a PR to the develop branch as the docs live here, else I will do it this week.

Will do ...


> Correct, the API docs live here and the general docs live: https://github.com/microsoftdocs/xamarin-docs

Thanks for the pointer!

**Comment by janusw** [comment]
Coming back to the original problem: Instead of converting all the altitudes to the same reference system, it might be easier to extend the approach of UWP to all platforms, by adding a property to the Location class, which specifies the reference system of the altitude value.

**Comment by jamesmontemagno** [comment]
Hmmmm I like that idea! What to give it a go?

**Comment by janusw** [comment]
Yes, I will give it a try. I'm not able to assign myself to the issue, though ...

**Comment by jamesmontemagno** [comment]
Fixes will be shipped in 1.6.0
