### ISSUE TITLE
[Bug] [Android] Browser.OpenAsync creates new task

### ISSUE THREAD

**Issue by rickclephas** [xamarin/Essentials#1180]
### Description

The implementation of `Browser.OpenAsync` is always starting a new task for the CustomTabs:
https://github.com/xamarin/Essentials/blob/9e74d1ce176233b87ff5e9a86a363e49da43357d/Xamarin.Essentials/Browser/Browser.android.cs#L30

This means the users will see the CustomTab as a separate app in their recent apps list and won't return to the app when they switch between apps.

### Steps to Reproduce

1. Call `Browser.OpenAsync` with `BrowserLaunchMode.SystemPreferred`
2. When the CustomTab is open switch to another app (without closing the CustomTab) 
3. Now switch back to the CustomTab via the recent apps. 
    You will notice that the CustomTab and the test app are both in the list. 
    But we'll select the CustomTab since that is where we left off.
4. Close the CustomTab

### Expected Behavior

After closing the CustomTab in step 4 you should return to the test app.

### Actual Behavior

After closing the CustomTab in step 4 you return to the home screen.
It looks like the app crashed but it is actually just in the background in another task.

### Basic Information

- Version with issue: 1.5.1
- Platform Target Frameworks:
  - Android: 10
- Affected Devices:
  - Google Pixel 3a XL
  - Samsung Galaxy S20+
  - _Presumably every other device as well_

**Comment by rickclephas** [comment]
The `NewTask` flag was added in #228 to fix #225 .
Opening the CustomTab (or browser) from within the app should be within the same taks to preserve the flow. A new task should only be started if we don't have a running activity.

**Comment by rickclephas** [comment]
When this is fixed it would probably also fix #798.

**Comment by jamesmontemagno** [comment]
Hmmmmm yes, I agree with you here as I never did this before... Curious why this was put in...

Here is my old code: https://github.com/jguertl/SharePlugin/blob/master/Share/Share.Plugin.Android/ShareImplementation.cs#L41

**Comment by jamesmontemagno** [comment]
Although I guess what would happen if you are on a dual screen device and  you want it to launch on the second screen... that flag would need to be there....

**Comment by rickclephas** [comment]
> Although I guess what would happen if you are on a dual screen device and you want it to launch on the second screen... that flag would need to be there....

The flag would indeed be required to launch  it on a second screen (or in multi window mode).
Though I think this should be up to the developer of the app. 
In most situations I guess you would want it to be the same task (looking at other apps like Twitter, LinkedIn and Github).

**Comment by Redth** [comment]
Fixed in #1183
