### ISSUE TITLE
[Enhancement] Add Temporary Directory to File System Helpers

### ISSUE THREAD

**Issue by MarkIvanDev** [xamarin/Essentials#1187]
## Summary
Add Temporary Directory to access each platform's temporary folder.

## API Changes
We could add a new `TemporaryDirectory` static property to FileSystem class

    public static string TemporaryDirectory => PlatformTemporaryDirectory

**UWP**

    ApplicationData.Current.TemporaryFolder.Path

**iOS**

    Path.Combine(Environment.GetFolderPath (Environment.SpecialFolder.MyDocuments), "..", "tmp")

**Android**

    Android.OS.Environment.DownloadCacheDirectory

## Intended Use Case
The Cache directory is a great place for files that are easily recreated when lost but currently we don't have a way of accessing a directory for temporary files.

**Comment by Happypig375** [comment]
Why is [`System.IO.Path.GetTempPath()`](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.gettemppath?view=netstandard-2.0&tabs=windows) not sufficient?

**Comment by MarkIvanDev** [comment]
> Why is [`System.IO.Path.GetTempPath()`](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.gettemppath?view=netstandard-2.0&tabs=windows) not sufficient?

I had reservations if all of the Platforms implemented that method as the docs is not clear if it will return the temp directory that will be accessible from the app. I also read somewhere that in iOS, this method is missing?

> In Xamarin.iOS
> Method System.IO.Path.GetTempPath() is missing.
> [source](https://forums.xamarin.com/discussion/867/how-to-obtain-directory-to-store-temporariy-files)

**Comment by MarkIvanDev** [comment]
I researched more on this issue and I have found that `System.IO.Path.GetTempPath()` really does the job. Will be closing this issue now. Thanks!

**Comment by jamesmontemagno** [comment]
Here is a good breakdown of where all standard system.io paths go: https://github.com/dotnet-ad/Standard.SpecialFolders
