### ISSUE TITLE
[Feature Proposal] Geo-hashing and proximity search

### ISSUE THREAD

**Issue by sps014** [xamarin/Essentials#1189]
#### Aim: 
 Provide a GeoHashing and Proximity Search API via Xamarin Essential.

#### Problem
Currently to write a uber-like location-driven app, we need to implement our GeoHashing and proximity search algorithm. There is no builtin support or any API to help user quickly do proximity searches.

#### Solution
Provide a High-Level API for GeoHashing and Proximity searching.

**Comment by jamesmontemagno** [comment]
Would this be similar to what is in: https://github.com/shinyorg/shiny

**Comment by sps014** [comment]
@jamesmontemagno there are various libraries that can do the work that xamarin essential performs.
We have external libraries for Geo Location,Flash Light etc but what we want is a unified easy to use API.I guess  we have solid reason to add this suggest such as there are many application that requires querying nearby areas within a given radius.
With xamarin essential it is one or two line of code.

**Comment by sps014** [comment]
I have ported one of the JS GeoHashing libraries to C# DotnetCore myself,
want you guys to review so I can start porting the library to Xamarin essential and I can submit a PR,
Currently completed GeoHashing which is aimed to be a separate class.

Please provide your suggest https://github.com/sps014/GeoQuery/blob/master/GeoQuery/GeoQuery.netstandard.cs

**Comment by sps014** [comment]
I came to realize that a proximity search on the client-side is a waste of resources and time.

**Comment by sps014** [comment]
Added a PR https://github.com/xamarin/Essentials/pull/1196
