### ISSUE TITLE
Text-To-Speech API's

### ISSUE THREAD

**Issue by Redth** [xamarin/Essentials#12]
Make devices speak arbitrary text

## TextToSpeech
```csharp
public static class TextToSpeech
{
    public static int MaxSpeechInputLength { get; }

    public static Task SpeakAsync (string text, CancellationToken cancelToken = default(CancellationToken));
    public static Task SpeakAsync (string text, SpeakSettings settings, CancellationToken cancelToken = default(CancellationToken));

    public static Task GetLocalesAsync ();
}
```

## SpeakSettings (struct)
```csharp
public struct SpeakSettings
{
    public Locale Locale;
    public float? Pitch;
    public float? SpeakRate;
    public float? Volume;
}
```

## Locale
```csharp
public static class Locale
{
    public string Language { get; }
    public string Country { get; }
    public string Name { get; }
}
```

**Comment by Redth** [comment]
The table above tries to show what each platform does. Android is mostly just "1.0" is normal and then multiply. iOS has specific ranges and defaults. UWP follows the SSML and appears to support an "enum"-based method as well as a flat percentage-based method. We could use the "enum" values and just map them to the platform restrictions. Or we could go with a percentage based and just clip them when they exceed the range for a particular platform.

![tts-table](https://user-images.githubusercontent.com/271950/36624540-84bc3c7e-18de-11e8-83e0-d5609c55e86e.png)

**Comment by alfredmyers** [comment]
Any reason for creating a new class (Locale) instead of using [CultureInfo](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo)?

**Comment by Redth** [comment]
This is a great point @alfredmyers I suspect it was from the old plugin which may have been done for reasons before netstandard.

We should change this

**Comment by jamesmontemagno** [comment]
I think the difference is that the codes each engine uses for culture info may not match the .NET codes.... however we would have to validate this.

**Comment by Redth** [comment]
If that's the case it's plausible we could write a mapping. That could be a useful API regardless of text to speech.

**Comment by alfredmyers** [comment]
From what I could grasp going through the different TextToSpeech implementations in @jamesmontemagno 's [TextToSpeechPlugin](https://github.com/jamesmontemagno/TextToSpeechPlugin), the only one that needs a `MaxSpeechInputLength` property is the implementation for Android.

If that is the case, and we could solve the issue splitting the text from within the implementation for Android, would exposing `MaxSpeechInputLength` on the API still be necessary?

**Comment by Redth** [comment]
Yes I love this idea!

**Comment by alfredmyers** [comment]
@mattleibow 

> - there may be languages that don't use punctuation
> - there may be languages that are backwards
> - there may be languages that have multi-byte characters

I have a prototype of a method that splits the string on the nearest [punctuation mark](https://docs.microsoft.com/en-us/dotnet/api/system.char.ispunctuation) or [white space](https://docs.microsoft.com/en-us/dotnet/api/system.char.iswhitespace) just before MaxSpeechInputLength.

I really don't have experience with RTL languages, but I still have a copy of [Developing International Software](https://www.amazon.com/Developing-International-Software-Developer-Reference/dp/0735615837/) lying around. Best case, if it is only a matter of iterating over the string in reverse order, I can take a look into it.

**Comment by moljac** [comment]
@alfredmyers I did not have time to finish and test the whole SplitText method, but I ended up iterating from the buffer end in reverse order searching for `Char.IsPunctuation` and `Char.IsWhitespace`. From that position the process is repeated.

> I really don't have experience with RTL languages,

My experience is not huge in that area, but I asked some people that did something with TTS in Persian. I have received an answer, but waiting for more info.

**Comment by SoheilAlizade** [comment]
Hi guys, I'm the Persian language. @moljac say to me that **we** have the problem with spiting RTL text.

I don't have experience with TTS but can help with issues. 

In the first case, I present a Persian TTS Project that it's **ParsKhan**. This open source project developed by iranian programmers ( that solved many matters in RTL).

ParsKhan does not have code quality ( i refactor it somewhat) but we don't need project codes, just use algorithms and scenarios.

ParsKhan has the doc but doc language is Persian ( if it's necessary I translate it ).

ParsKhan Repo is [here](https://github.com/SoheilAlizade/ReDesignParsKhan)
