### ISSUE TITLE
[Bug] [iOS] TextToSpeech crash in Release

### ISSUE THREAD

**Issue by ilyalehchylin** [xamarin/Essentials#1207]
### Description
App crashes in release (TestFlight) when using TextToSpeech (there is everything alright in debug though). I logged the exception and it throws the following message:

> The lazily-initialized type does not have a public, parameterless constructor.

### Steps to Reproduce

Call `TextToSpeech.SpeakAsync` (release mode)

### Expected Behavior

Voice is starting to pronounce text.

### Actual Behavior

App crashes.

### Basic Information

- Version with issue: 1.5.1, 1.5.2
- Last known good version: N/A
- IDE: Visual Studio for Mac Community 8.5.1 (build 42)
- Platform Target Frameworks: 
  - iOS: 
    - Deployment target: 8.0
    - Tested device version: 13.3.1
- Affected Devices: iPhone 8 Plus

### Reproduction Link

[Here](https://github.com/ilyalehchylin/educats-xamarin/blob/7c1ca437ad8d1fb3eab0d65388a56802b57a5778/source/EduCATS/Helpers/Devices/AppDevice.cs#L93) you can find how the code used.

**Comment by jamesmontemagno** [comment]
Looks like the linker is being a bit aggressive. That code was re-architected with a lazy so let me update and get you a nuget to try asap.

**Comment by jamesmontemagno** [comment]
I am curious as a workaround if you do something like this in your AppDelegate:

``
var test = new AVSpeechSynthesizer();
``

that may keep it linked in.

**Comment by jamesmontemagno** [comment]
Can I bother you to try this one: https://dev.azure.com/xamarin/public/_build/results?buildId=16434&view=artifacts&type=publishedArtifacts

I did a different work around that I think is better. Sorry to keep asking :)

**Comment by ilyalehchylin** [comment]
No problem, you may contact me as much as you need 🙂 

Unfortunately, with this NuGet app crashes. I will check the error.

**Comment by ilyalehchylin** [comment]
The same error: `TextToSpeech error: The lazily-initialized type does not have a public, parameterless constructor`.

**Comment by jamesmontemagno** [comment]
Got it! Let me try one more thing :)

**Comment by jamesmontemagno** [comment]
Alright, one more for ya to test out: https://dev.azure.com/xamarin/public/_build/results?buildId=16525&view=artifacts&type=publishedArtifacts

**Comment by ilyalehchylin** [comment]
Yup, it's working

**Comment by jamesmontemagno** [comment]
YAY! <3 thanks!

**Comment by ilyalehchylin** [comment]
No problem, I'm glad I was able to help with this issue 🙂

**Comment by jamesmontemagno** [comment]
Will be in 1.5.3

**Comment by nikhildpardasani** [comment]
Hi @jamesmontemagno Can you tell us by when can we expect release 1.5.3 ?

**Comment by rscholey** [comment]
Any estimate when 1.5.3 will be out?

**Comment by jamesmontemagno** [comment]
We are working on getting it out soon.

For a workaround just add this to your AppDelegate:
```
var test = new AVSpeechSynthesizer();
```
