### ISSUE TITLE
[BUG]LocationAlways returns granted even if the user grants only the in-use permission

### ISSUE THREAD

**Issue by nexxuno** [xamarin/Essentials#1211]
### Description
When asking for permission LocationAlways returns granted even if the user grants only the in-use permission
### Steps to Reproduce

1. Request LocationAlways permission
2. Accept only the in-use part of the permission (it's one of the 3 choices: grant, only in use, deny)
3. Check LocationAlways permission

### Expected Behavior
LocationAlways returns Denied
### Actual Behavior
LocationAlways returns Granted
### Basic Information

- Version with issue: 1.5
- Last known good version:-
- IDE:Visual Studio for Windows
- Platform Target Frameworks: 
  - Android: 9 and 10
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
What platform are you experiencing this issue on?

**Comment by nexxuno** [comment]
Tested only on Android 10 at the moment, built with target sdk 9 and 10.

**Comment by jamesmontemagno** [comment]
If you are running it on Android 10, you must **compile** and **target** against Android 10.  If you are doing it against anything lower that check would not matter and a normal check would only have the older permissions. In that case you would then need to add: AccessBackgroundLocation to your permissions. If you have a small repo that would help out.

**Comment by nexxuno** [comment]
I will test as soon as I can. Thanks.

**Comment by cachely** [comment]
I'm having the same issue and I just tested this by setting the compile and target to android 10 and it is still returning granted when it is not.

**Comment by jamesmontemagno** [comment]
Thanks @cachely I will give it a try real quick here.

**Comment by jamesmontemagno** [comment]
Working perfect for me. Here is a repo you can test. https://github.com/jamesmontemagno/AndroidBackgroundTest

Note that I have the following settings, which are required:

![image](https://user-images.githubusercontent.com/1676321/78607620-4a553a80-7814-11ea-9550-dc79986dd7e5.png)


![image](https://user-images.githubusercontent.com/1676321/78607634-504b1b80-7814-11ea-895b-06437a4f71bb.png)

And these permissions: 

```
//Location settings
[assembly: UsesPermission(Android.Manifest.Permission.AccessCoarseLocation)]
[assembly: UsesPermission(Android.Manifest.Permission.AccessFineLocation)]
[assembly: UsesPermission(Android.Manifest.Permission.AccessBackgroundLocation)]

```


See video: https://github.com/jamesmontemagno/AndroidBackgroundTest/blob/master/screencapture-1586208991868.mp4?raw=true

**Comment by cachely** [comment]
Thanks @jamesmontemagno  I'll double check a few things and give it a go.

**Comment by nexxuno** [comment]
work good, I guess I didn't add the new 

[assembly: UsesPermission(Android.Manifest.Permission.AccessBackgroundLocation)]

For me this can be closed.
