### ISSUE TITLE
Access camera

### ISSUE THREAD

**Issue by GraemeDeprez** [xamarin/Essentials#1214]
Hello,

I want to use the camera in a Xamarin application. I see the camera as one of the essentials in an mobile app. I read there is work in progress, but can't find anything recent. I was wondering of you guys are still working on an API to have access to the camera. Other solutions I can find on the internet are not suitable for my application. I want to have a live view of the camera inside of my form (and not in an externaly popup window). I need to process each frame to see if the frame meets some criteria. So the internet solutions doesn't fit my needs.

**Comment by newky2k** [comment]
@GraemeDeprez I can't find anything about us working on a camera API and this feels more like a UI function, as it feels like you want to embed it in a view.  Are you using Xamarin forms or is this native only? 

Regards

**Comment by mattleibow** [comment]
Camera features are being added into the Xamarin Community Toolkit: https://github.com/xamarin/XamarinCommunityToolkit
