### ISSUE TITLE
[BUG]AppInfo.RequestedTheme always return "Light" on UWP 

### ISSUE THREAD

**Issue by gmbertolotto** [xamarin/Essentials#1218]
Bug report [Submitting Issues]
(https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

On Windows 10 italian version AppInfo.RequestedTheme always return LIGHT. On iOS and Android it's all ok.

### Steps to Reproduce
1. Create new app Xamarin UWP platform 
2. Add code on MainPage.xamls.cs (see image 1)
3. Add code on App.xaml.cs (see image 2)
### Expected Behavior
When in Control Panel on WIndows 10 I set the Theme to Dark the AppInfo.RequestedTheme must return Dark (see image 3)
### Actual Behavior
AppInfo.RequestedTheme always return Light  

### Basic Information
- IDE: VS 2019 **16.5.3**
- Platform Target Frameworks: 
  - iOS:  OK
  - Android: OK
  - UWP:  SDK  18362 
- Nuget Packages: 
     - Xamrin Essentials 1.5.2
     - Xamarin Forms; 4.5.0.617
- Affected Devices:
  WIndow 10 Italian language
### Screenshots
![1](https://user-images.githubusercontent.com/30554389/79064100-57f04180-7ca6-11ea-90b1-84c949f440c2.PNG)
![2](https://user-images.githubusercontent.com/30554389/79064101-5b83c880-7ca6-11ea-9273-46e70cdef8a2.PNG)
![3](https://user-images.githubusercontent.com/30554389/79064156-cc2ae500-7ca6-11ea-86e8-e78d93a253ad.PNG)

**Comment by jamesmontemagno** [comment]
Double check your App.xaml inside of your UWP project.

If you have a requested theme in your App.xaml then it will always return Light if you have that: https://github.com/xamarin/Essentials/blob/develop/Samples/Samples.UWP/App.xaml#L6

**Comment by gmbertolotto** [comment]
Sorry, my mistake! Thanks for the immediate reply.
