### ISSUE TITLE
What are best practices for logging out when using WebAuthenticator?

### ISSUE THREAD

**Issue by jeyoor** [xamarin/Essentials#1223]
We are working on a mobile application that uses OAuth2/AppAuth to authorize access to some backend APIs.

Our understanding is that Xamarin.Essentials WebAuthenticator is the recommended replacement for Xamarin.Auth for our use case going forward.

When working with Xamarin.Auth, logging out would require sending the user's browser to a logout URL to clear the cookies. See, for example: xamarin/Xamarin.Auth#204

We could do something like opening the user's browser to our logout URL like this:

```
public class Logout
{
    public async Task<bool> OpenLogoutPage(Uri logoutUri)
    {
        return await Browser.OpenAsync(logoutUri, BrowserLaunchMode.SystemPreferred);
    }
}
```

From a user experience point of view, this can seem odd/jarring.

Is this still the required/recommended way to log out when using Xamarin.Essentials WebAuthenticator?

Thank you for your work on Xamarin.Essentials!

**Comment by jamesmontemagno** [comment]
It would be the same thing here and launch the logout URI as under the hood we are using very similar functionality of the browser recommendations. There aren't direct APIs that enable cookies to be removed. 

I think in iOS 13 we could actually have an option to turn on private session so it is unique each time. 
 https://developer.apple.com/documentation/authenticationservices/authenticating_a_user_through_a_web_service

However, there isn't anything for Chrome Custom Tabs.

For UWP I think it doesn't save cookies at all from what I can see: https://docs.microsoft.com/en-us/windows/uwp/security/web-authentication-broker

**Comment by jeyoor** [comment]
Thank you for the help! This information is exactly what I needed.

**Comment by Lydecker** [comment]
@jamesmontemagno please can clarify your recommendation here:

`It would be the same thing here and launch the logout URI as under the hood we are using very similar functionality of the browser recommendations.`

Are you saying we should:

a) continue to use Browser.OpenAsync() to loggout
b) use WebAuthenticator with the logout URL as the first argument to the call?

Thanks

**Comment by Lydecker** [comment]
@jeyoor  - are you using ` Browser.OpenAsync()` for logout?

If so, how do you handle closing the Safari window on iOS given there is no Browser.CloseAsync() option in Essentials?

Thanks

**Comment by jeyoor** [comment]
@Lydecker great question.We ended up building a custom post-logout page into our web backend system. The post-logout page redirects the user to the appropriate data uri for our app.Hope this helps,JeyOn Jun 1, 2020 7:12 PM, Lydecker <notifications@github.com> wrote:
@jeyoor  - are you using  Browser.OpenAsync() for logout?
If so, how do you handle closing the Safari window on iOS given there is no Browser.CloseAsync() option in Essentials?
Thanks

**Comment by Lydecker** [comment]
Hi @jeyoor - thanks for your quick reply.

So currently we have a custom post-logout page on our web backend which redirects the user to the custom uri for the app - so we did the same as you - however what I'm not understanding is how you automatically close the Browser in the app on iOS once the custom uri is received after logout?

Thanks

**Comment by jeyoor** [comment]
@Lydecker,Thank you for the feedback. I am not quite sure how our team specifically implemented closing the browser on iOS.I assumed that when we redirected back to the app they detected this in the AppDelegate.cs OpenUrl method and displayed an appropriate view that moved the browser to the background, but perhaps there was more to it than this...If I get more info to share I'll let you know.On Jun 1, 2020 7:51 PM, Lydecker <notifications@github.com> wrote:
Hi @jeyoor - thanks for your quick reply.
So currently we have a custom post-logout page on our web backend which redirects the user to the custom uri for the app - so we did the same as you - however what I'm not understanding is how you automatically close the Browser in the app on iOS once the custom uri is received after logout?
Thanks

**Comment by hiraldesai** [comment]
I submitted an app update to iOS which was rejected when I used `Browser` calls to do OAuth. I ended up doing something like this based on [the example](https://github.com/Redth/Xamarin.AspNetCore.Authentication) @jamesmontemagno had shared in #763. I haven't had a chance to explore the new authentication extension from `Xamarin.Essentials` yet but my custom implementation did this.

Login call in app

```C#
                try
                {
                    var authResult = await DependencyService.Get<IAuthenticator>().AuthenticateAsync(new Uri("yourappuri://"), new Uri("url-to-oatuth-provider"));
                    if (authResult != null)
                    {
                        // Store auth result token and user account info to device
                    }
                }
                catch (Exception ex) when (ex is TaskCanceledException || ex is OperationCanceledException)
                {
                    // Intentional - user closed browser
                }
```
Logout call in app

```C#
            try
            {
                await DependencyService.Get<IAuthenticator>().LogoutAsync(new Uri("yourappuri://"), new Uri("url-to-oatuth-provider"));
            }
            catch (Exception ex) when (ex is TaskCanceledException || ex is OperationCanceledException)
            {
                // Intentional - user closed browser
            }
```

Shared IAuthenticator interface
```C#
    public interface IAuthenticator
    {
        Task<AuthResult> AuthenticateAsync(Uri appCallbackUri, Uri uri);
        Task LogoutAsync(Uri appCallbackUri, Uri uri);
    }
```

Custom AuthResult that extracts oAuth response into what your app needs
```C#
    public class AuthResult
    {
        public ApiToken ApiToken { get; set; }
        public UserAccount UserAccount { get; set; }
        public bool IsAuthenticated { get; set; }
    }
```

I then have separate `IAuthenticator` implementations for each platform that uses `CustomTabsActivityManager` for Android, `SFSafariViewController` for iOS and `WebAuthenticationBroker` for UWP to give me full control of the views presented to the user.

To answer your question @Lydecker - the iOS implementation for `IAuthenticator` would then have a static `UIViewController` that holds reference to your `SFSafariViewController` opened by the `AuthenticateAsync` or `LogoutAsync` calls from the app. Then the `OpenUrl` calls from the `AppDelegate` would call `DismissViewControllerAsync` on that `SFSafariViewController` to close the auth/logout session.

**Comment by Lydecker** [comment]
Thanks for this detailed reply @hiraldesai 

We have done the same thing - have a reference to SFSafariViewController which we then Dismiss when logging out. 

Do you know when your rejection happened, and on what version of Forms you were on? Given Browser just calls SFSafariViewController under the hood, that should not lead to rejection.

I'm wondering if your rejection was linked to this: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows#uiwebview-deprecation-and-app-store-rejection-itms-90809

Which is mentioned here #1241 

I haven't submitted anything to Apple yet - but had everything working using my own  SFSafariViewController implementation. The WebAuthenticator from Essentials is amazing makes integration so simple - however I still need my own SFSafariViewController implementation as well for the logout part which is a pain. If the Browser implemented the Close command for SFSafariViewController, it would make life so much simpler.

**Comment by hiraldesai** [comment]
The rejection happened months ago and it was an older Xamarin.Forms verison - so it must have been linked to that deprecation only. I wasn't aware that Browser APIs had internally started using SFSafariViewController now, so you should be fine.

When I get a chance I'd also like to rip off all of that custom stuff and use WebAuthenticator from Essentials.

**Comment by samt1925** [comment]
> I submitted an app update to iOS which was rejected when I used `Browser` calls to do OAuth. I ended up doing something like this based on [the example](https://github.com/Redth/Xamarin.AspNetCore.Authentication) @jamesmontemagno had shared in #763. I haven't had a chance to explore the new authentication extension from `Xamarin.Essentials` yet but my custom implementation did this.
> 
> Login call in app
> 
> ```cs
>                 try
>                 {
>                     var authResult = await DependencyService.Get<IAuthenticator>().AuthenticateAsync(new Uri("yourappuri://"), new Uri("url-to-oatuth-provider"));
>                     if (authResult != null)
>                     {
>                         // Store auth result token and user account info to device
>                     }
>                 }
>                 catch (Exception ex) when (ex is TaskCanceledException || ex is OperationCanceledException)
>                 {
>                     // Intentional - user closed browser
>                 }
> ```
> 
> Logout call in app
> 
> ```cs
>             try
>             {
>                 await DependencyService.Get<IAuthenticator>().LogoutAsync(new Uri("yourappuri://"), new Uri("url-to-oatuth-provider"));
>             }
>             catch (Exception ex) when (ex is TaskCanceledException || ex is OperationCanceledException)
>             {
>                 // Intentional - user closed browser
>             }
> ```
> 
> Shared IAuthenticator interface
> 
> ```cs
>     public interface IAuthenticator
>     {
>         Task<AuthResult> AuthenticateAsync(Uri appCallbackUri, Uri uri);
>         Task LogoutAsync(Uri appCallbackUri, Uri uri);
>     }
> ```
> 
> Custom AuthResult that extracts oAuth response into what your app needs
> 
> ```cs
>     public class AuthResult
>     {
>         public ApiToken ApiToken { get; set; }
>         public UserAccount UserAccount { get; set; }
>         public bool IsAuthenticated { get; set; }
>     }
> ```
> 
> I then have separate `IAuthenticator` implementations for each platform that uses `CustomTabsActivityManager` for Android, `SFSafariViewController` for iOS and `WebAuthenticationBroker` for UWP to give me full control of the views presented to the user.
> 
> To answer your question @Lydecker - the iOS implementation for `IAuthenticator` would then have a static `UIViewController` that holds reference to your `SFSafariViewController` opened by the `AuthenticateAsync` or `LogoutAsync` calls from the app. Then the `OpenUrl` calls from the `AppDelegate` would call `DismissViewControllerAsync` on that `SFSafariViewController` to close the auth/logout session.

What should i do on server side to log off? I just don't want to open new view for logout. My WebAuthenticator always skip login page if i already enter info and give me same token for user. Im just need to open login form for a new user. Please help.

**Comment by shanwayne** [comment]
For anyone trying to force a new logon - add the optional query string "prompt=logon".

See [OpenID](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.2.1) spec for 'prompt' options. Hope this helps!

**Comment by markrobert194** [comment]
Any updates on how you guys implemented this?

**Comment by SShaw1985** [comment]
I dont know why this issue is closed as the only way to get this to work is to do a workaround. signing out and in again as another user is pretty common requirement and should be accommodated

**Comment by veringm** [comment]
Hi - I'm aware that this ticket has been closed. Just wanted to share how we do logout. We simply use the Eseentials WebAuthenticator, but call AuthenticateAsync with the logout-uri instead of the login-uri. Like this

```
 await WebAuthenticator.AuthenticateAsync(
                new Uri(logoutUri),
                new Uri(Callback));

```
It has the drawback, that iOS pops up a message asking the use to confirm that our app wants to 'sign-**in**' using our service - we are not signing in now, rather signing out, but don't know if we could communicate that to iOS. The WebAuthenticator contains no 'LogoutAsync' method.

**Comment by Lydecker** [comment]
This is exactly what we do too. Thanks for sharing!

**Comment by veringm** [comment]
@Lydecker : No problem ;) I often found so much valuable information here.
Have you found a simple way to circumvent the "sign-in" confirm-message from iOS when user actually requests sign-out?

**Comment by Lydecker** [comment]
No way unfortunately. We haven't tried @shanwayne technique above yet - but
that looks promising as an alternate solution.

**Comment by NicMD** [comment]
@veringm, @Lydecker You can circumvent the iOS popup using the newly added WebAuthenticatorOptions like below

`await WebAuthenticator.AuthenticateAsync(new WebAuthenticatorOptions
            {
                Url = url,
                CallbackUrl = callbackUrl,
                PrefersEphemeralWebBrowserSession = true
            });`

**Comment by samirgcofficial** [comment]
Does anyone have any ideas on how to log out a user in Android? The log out process works fine in iOS, but in Android, after revoking the authentication token, calling `await WebAuthenticator.AuthenticateAsync` does not create a new session even though the tokens have expired.

**Comment by DaveMcCrady** [comment]
> Does anyone have any ideas on how to log out a user in Android? The log out process works fine in iOS, but in Android, after revoking the authentication token, calling `await WebAuthenticator.AuthenticateAsync` does not create a new session even though the tokens have expired.

Anyone have an answer for this, I am experiencing the same thing.
