### ISSUE TITLE
[Feature Request] Use Fallback MIME type if not found on files.

### ISSUE THREAD

**Issue by flish** [xamarin/Essentials#1225]
### Description

Sending an email with a single attachment using await Email.ComposeAsync(message); on iOS crashes with a null reference as per below stack trace, attachment is a text file with file name debug.log and is less than 0.5MB in size.  Shared code in Android project works fine.

Using Xamarin.Essentials 1.5.2 nuget with Xamarin Forms 4.4.0991640

### Steps to Reproduce

Code example

```
var message = new EmailMessage
{
    Subject = "test with attach",
    Body = "test email body<br/>",
    To = "test@test.com"
};

message.BodyFormat = EmailBodyFormat.PlainText;
if (File.Exists(attachmentPath))
{
    message.Attachments.Add(new EmailAttachment(attachmentPath));
}

await Email.ComposeAsync(message);
```

### Expected Behavior

Popup iOS mail app with precomposed email and attachment

### Actual Behavior

Unhandled Exception;

```
NullReferenceException: Object reference not set to an instance of an object
  File "d:\a\1\s\Xamarin.Essentials\FileSystem\FileSystem.ios.tvos.watchos.cs", line 53, col 13, in PlatformGetContentType
    System.String PlatformGetContentType(System.String)
  File "d:\a\1\s\Xamarin.Essentials\FileSystem\FileSystem.shared.cs", line 69, col 17, in GetContentType
    System.String GetContentType()
  File "d:\a\1\s\Xamarin.Essentials\FileSystem\FileSystem.shared.cs", line 55, col 20, in get_ContentType
    System.String get_ContentType()
  File "d:\a\1\s\Xamarin.Essentials\Email\Email.ios.cs", line 57, col 21, in ComposeWithMailCompose
    System.Threading.Tasks.Task ComposeWithMailCompose(Xamarin.Essentials.EmailMessage)
  File "d:\a\1\s\Xamarin.Essentials\Email\Email.ios.cs", line 29, col 17, in PlatformComposeAsync
    System.Threading.Tasks.Task PlatformComposeAsync(Xamarin.Essentials.EmailMessage)
  File "d:\a\1\s\Xamarin.Essentials\Email\Email.shared.cs", line 23, col 13, in ComposeAsync
    System.Threading.Tasks.Task ComposeAsync(Xamarin.Essentials.EmailMessage)
  File "/Users/runner/runners/2.166.2/work/1/s/WorstApps/WorstLibrary/Utilities/Email.cs", line 67, col 5, in SendEmailWithAttachment
    Void MoveNext()
```

### Basic Information

- Version with issue: 1.5.2
- Last known good version: Unknown
- IDE: VS for Mac
- Platform Target Frameworks: 
  - iOS: 12.0
- Nuget Packages:
- Affected Devices: iPhone X

### Screenshots

None

### Reproduction Link

None

**Comment by jamesmontemagno** [comment]
So, this can occur when the content type can't be figured out. Can you rename it to .txt and see what happens.

**Comment by flish** [comment]
Will do, probably early next week

**Comment by flish** [comment]
> So, this can occur when the content type can't be figured out. Can you rename it to .txt and see what happens.

Thanks @jamesmontemagno can confirm that changing the file extension works, so that solves my immediate problem (attaching debug logs to an email for a user getting support.  However, next stage was to attach a copy of the sqlite database so I can see what they see, extension is .db and that generates the same exception)

Is it worth returning a default mime type (application/txt or similar) so that 'something' gets returned?  Don't want to step on toes so if in hand cool, else I can play at this end and maybe push a PR given some suggested direction?

Ta

**Comment by jamesmontemagno** [comment]
Yeah, i think that may be a good idea as a fallback and have an option there. @Redth thoughts?

One thing you can do is pass in the content type when creating the emailattachment:

var file = new EmailAttachment(file.log, "application/txt");

They all come from: http://www.iana.org/assignments/media-types/media-types.xhtml you can see what the contenttype is on the file though.

**Comment by flish** [comment]
Thanks @jamesmontemagno  hadn't spotted that, that's my immediate solved - let me know if you @Redth want to me to look at PR'ing something to avoid the exception

**Comment by mattleibow** [comment]
I think a PR will be awesome. We could probably fall back to the generic "application/octet-stream"...

**Comment by flish** [comment]
> I think a PR will be awesome. We could probably fall back to the generic "application/octet-stream"...

👍 Will see where the day job and the night job leaves me and will have a go
