### ISSUE TITLE
[Bug] No response from Permissions.RequestAsync<Permissions.ContactsRead>();

### ISSUE THREAD

**Issue by ykoorb** [xamarin/Essentials#1227]
### Description
Hi there,

I *think* there is an issue when calling Permissions.RequestAsync<T>()
I recently switched to using this and the first time i call it, i don't seem to get anything returned. The user is shown the permissions popup, but on allowing, nothing further seems to happen.

After the next call to the same function, the permission status is returned correctly (but doesn't need to show the popup this time, so must know in the backend that permission was granted).
 

### Steps to Reproduce

This is the code i am using

```csharp
        public async Task<bool> RequestAccessPhoneContacts()
        {
            PermissionStatus status = PermissionStatus.Denied;

            status = await MainThread.InvokeOnMainThreadAsync<PermissionStatus>(async () =>
            {
                return await Permissions.RequestAsync<Permissions.ContactsRead>();
            });

            return (status == PermissionStatus.Granted);
        }
```

### Expected Behavior
Permissions.RequestAsync<Permissions.ContactsRead>() should return PermissionStatus.Granted

### Actual Behavior
nothing is returned

### Basic Information

- Version with issue: 1.5.2
- IDE: VS 2019
- Platform Target Frameworks: 
  - Android: 9.0 

I also placed an item on stackoverflow because i thought it may be a 'my code' issue.
https://stackoverflow.com/questions/61252633/how-do-i-request-permissions-when-not-on-the-ui-thread?noredirect=1#comment108384310_61252633

**Comment by mattleibow** [comment]
Did you add the `OnRequestPermissionsResult` member to the main activity?

```csharp
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Android.Content.PM.Permission[] grantResults)
{
    Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);

    base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
}
```

Have a quick look at https://docs.microsoft.com/en-us/xamarin/essentials/get-started?tabs=windows%2Candroid

**Comment by ykoorb** [comment]
If I could rewind time 24 hours and read some documentation properly... 

I'd just migrated over from https://github.com/jamesmontemagno/PermissionsPlugin and missed that change! Sorry for being a silly time waster :)

**Comment by mattleibow** [comment]
No prob! We all have lost 24 hours at one point or another... Sometimes lots of 24 hours 😢
