### ISSUE TITLE
AppInfo RequestedTheme not working. Always returns Light Mode

### ISSUE THREAD

**Issue by kiamajuliet** [xamarin/Essentials#1237]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
On and iPhone 11 iOS 13.3.1 (physical device) and iPhone 11 iOS 13.4 (simulator), AppInfo.RequestedTheme always return LIGHT

### Steps to Reproduce

1. Add SetTheme code App.cs (image 1)
2. Run the device/simulator and change the themes from settings

### Expected Behavior
After setting Dark Appearance from settings, the AppInfo.RequestedTheme should return Dark Mode

### Actual Behavior
AppInfo.RequestedTheme always return Light

### Basic Information

- Version with issue:

- IDE:
- Platform Target Frameworks: 
Xamarin.iOS: 13.16.0.13
Xamarin.Mac: 6.16.0.13
Xamarin.Android: 10.2.0.100
Mac OS X 10.15.4

- Nuget Packages:
Xamrin Essentials 1.5.3
Xamarin Forms; 4.5.0.617

- Affected Devices:
iPhone 11 13.3.1 (physical device)
iPhone 11 iOS 13.4 (simulator)

### Screenshots

![image](https://user-images.githubusercontent.com/49218022/79939158-f5aaf400-8490-11ea-9cd9-b0e61d305a2f.png)

![image](https://user-images.githubusercontent.com/49218022/79939239-2ee36400-8491-11ea-9880-125cd3cfd79d.png)

**Comment by jamesmontemagno** [comment]
See: https://github.com/xamarin/Essentials/issues/1218

**Comment by kiamajuliet** [comment]
Thanks for the link but even when I update it to DarkTheme or Default Theme in app.xaml it still returns light.

**Comment by jamesmontemagno** [comment]
Oh, i see you were talking about iOS, my fault here. 

I have tested this api locally and working well for me.

This would seem like you have 
```
<key>UIUserInterfaceStyle</key>
```
in your info.plist which forces a mode.

**Comment by kiamajuliet** [comment]
Yes, this was the issue _<key>UIUserInterfaceStyle</key>_ I had set it to light mode. Thank you.
