### ISSUE TITLE
[Bug] iOS: Browser: Deprecated API Usage - App rejected

### ISSUE THREAD

**Issue by zoli13** [xamarin/Essentials#1241]
### Description
Calling `await Browser.OpenAsync(url);` works fine, but when IPA is uploaded to App Store Connect to publish, it's rejected by:

**ITMS-90809**: Deprecated API Usage - Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview). 

- Version with issue: 1.5.2

**Comment by zoli13** [comment]
Ok, after investigation, this is not related to Browser code, it's XF issue: https://github.com/xamarin/Xamarin.Forms/issues/7323
Sorry for logging.

**Comment by Lydecker** [comment]
Did you resolve this by updating your Xamarin.Forms version? If so - to what?

Thanks

**Comment by AmrAlSayed0** [comment]
I didn't resolve this yet but I want to point out that the email you get from the App Store about Deprecated API Usage is just a warning and not a rejection of the build. You can still continue with processing your build an publish your app.

**Comment by Lydecker** [comment]
> I didn't resolve this yet but I want to point out that the email you get from the App Store about Deprecated API Usage is just a warning and not a rejection of the build. You can still continue with processing your build an publish your app.

What version of XF are you using? I thought this was resolved in 4.5.x?
