### ISSUE TITLE
[Bug] Xamarin.Essentials WebAuthenticator on iOS crash using Universal Link callback

### ISSUE THREAD

**Issue by mattallscripts** [xamarin/Essentials#1242]
### Description
When authentication is completed and the authentication modal view controller is dismissed, the app is "broken". The user can no longer interact with the app and it appears from the application output that mono experienced a crash.

```
> =================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

> =================================================================
	Native stacktrace:
=================================================================
	0x10e941f75 - /Users/[REDACTED]/Library/Developer/CoreSimulator/Devices/6E6FD2B8-2550-47ED-99F4-EF36EE23BEA4/data/Containers/Bundle/Application/A8E508A2-B9E0-496C-AE79-629335F91BE9/WebAuthTest.iOS.app/WebAuthTest.iOS : mono_dump_native_crash_info
	0x10e936205 - /Users/[REDACTED]/Library/Developer/CoreSimulator/Devices/6E6FD2B8-2550-47ED-99F4-EF36EE23BEA4/data/Containers/Bundle/Application/A8E508A2-B9E0-496C-AE79-629335F91BE9/WebAuthTest.iOS.app/WebAuthTest.iOS : mono_handle_native_crash
	0x10e948ec8 - /Users/[REDACTED]/Library/Developer/CoreSimulator/Devices/6E6FD2B8-2550-47ED-99F4-EF36EE23BEA4/data/Containers/Bundle/Application/A8E508A2-B9E0-496C-AE79-629335F91BE9/WebAuthTest.iOS.app/WebAuthTest.iOS : mono_sigsegv_signal_handler_debug
	0x7fff51b2f5fd - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x7fff51b08113 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_malloc.dylib : nanov2_allocate
	0x7fff519a49ba - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_blocks.dylib : _Block_release
	0x7fff519a49ba - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_blocks.dylib : _Block_release
	0x7fff519a49ba - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_blocks.dylib : _Block_release
	0x7fff4842ca5e - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIPresentationController transitionDidFinish:]
	0x7fff48431404 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.503
	0x7fff48549ae7 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[_UIViewControllerTransitionContext completeTransition:]
	0x7fff49083098 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UITransitionView notifyDidCompleteTransition:]
	0x7fff49082d1b - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UITransitionView _didCompleteTransition:]
	0x1155705ab - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/AccessibilityBundles/UIKit.axbundle/UIKit : -[UITransitionViewAccessibility _didCompleteTransition:]
	0x7fff490bcb90 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:]
	0x7fff4908d81d - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIViewAnimationState sendDelegateAnimationDidStop:finished:]
	0x7fff4908de14 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIViewAnimationState animationDidStop:finished:]
	0x1155b08c4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/AccessibilityBundles/UIKit.axbundle/UIKit : -[UIViewAnimationStateAccessibility animationDidStop:finished:]
	0x7fff4908df9a - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIViewAnimationState animationDidStop:finished:]
	0x1155b08c4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/AccessibilityBundles/UIKit.axbundle/UIKit : -[UIViewAnimationStateAccessibility animationDidStop:finished:]
	0x7fff2b4c0c64 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/QuartzCore.framework/QuartzCore : _ZN2CA5Layer23run_animation_callbacksEPv
	0x7fff519128cb - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdispatch.dylib : _dispatch_client_callout
	0x7fff5191ecdb - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdispatch.dylib : _dispatch_main_queue_callback_4CF
	0x7fff23d9da89 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
	0x7fff23d985d9 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopRun
	0x7fff23d97ac4 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x7fff38b2fc1a - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x7fff48bc7f80 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x11547bdba - Unknown
	0x1153c7f03 - Unknown
	0x1153be633 - Unknown
	0x10e94c291 - /Users/[REDACTED]/Library/Developer/CoreSimulator/Devices/6E6FD2B8-2550-47ED-99F4-EF36EE23BEA4/data/Containers/Bundle/Application/A8E508A2-B9E0-496C-AE79-629335F91BE9/WebAuthTest.iOS.app/WebAuthTest.iOS : mono_jit_runtime_invoke
	0x10ea6f808 - /Users/[REDACTED]/Library/Developer/CoreSimulator/Devices/6E6FD2B8-2550-47ED-99F4-EF36EE23BEA4/data/Containers/Bundle/Application/A8E508A2-B9E0-496C-AE79-629335F91BE9/WebAuthTest.iOS.app/WebAuthTest.iOS : mono_runtime_invoke_checked
	0x10ea75d35 - /Users/[REDACTED]/Library/Developer/CoreSimulator/Devices/6E6FD2B8-2550-47ED-99F4-EF36EE23BEA4/data/Containers/Bundle/Application/A8E508A2-B9E0-496C-AE79-629335F91BE9/WebAuthTest.iOS.app/WebAuthTest.iOS : mono_runtime_exec_main_checked
	0x10e8ababc - /Users/[REDACTED]/Library/Developer/CoreSimulator/Devices/6E6FD2B8-2550-47ED-99F4-EF36EE23BEA4/data/Containers/Bundle/Application/A8E508A2-B9E0-496C-AE79-629335F91BE9/WebAuthTest.iOS.app/WebAuthTest.iOS : mono_jit_exec
	0x10eb9ee3d - /Users/[REDACTED]/Library/Developer/CoreSimulator/Devices/6E6FD2B8-2550-47ED-99F4-EF36EE23BEA4/data/Containers/Bundle/Application/A8E508A2-B9E0-496C-AE79-629335F91BE9/WebAuthTest.iOS.app/WebAuthTest.iOS : xamarin_main
	0x10e865cf7 - /Users/[REDACTED]/Library/Developer/CoreSimulator/Devices/6E6FD2B8-2550-47ED-99F4-EF36EE23BEA4/data/Containers/Bundle/Application/A8E508A2-B9E0-496C-AE79-629335F91BE9/WebAuthTest.iOS.app/WebAuthTest.iOS : main
	0x7fff519521fd - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdyld.dylib : start

> =================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fff50aed94b):0x7fff50aed93b  0f 1f 44 00 00 48 85 ff 74 02 79 01 c3 48 8b 07  ..D..H..t.y..H..
0x7fff50aed94b  f6 40 20 04 74 0a be 01 00 00 00 e9 0d 00 00 00  .@ .t...........
0x7fff50aed95b  48 8b 35 9e 51 0f 39 ff 25 18 15 d5 36 55 48 89  H.5.Q.9.%...6UH.
0x7fff50aed96b  e5 41 57 41 56 41 55 41 54 53 48 83 ec 28 41 89  .AWAVAUATSH..(A.

> =================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x00259>
	  at UIKit.UIApplication:Main <0x000b2>
	  at UIKit.UIApplication:Main <0x00132>
	  at WebAuthTest.iOS.Application:Main <0x00092>
	  at <Module>:runtime_invoke_void_object <0x00198>
================================================================= 
```

### Steps to Reproduce

1. Create a brand new Xamarin.Forms solution
2. Update Xamarin.Essentials and Xamarin.Forms to latest
3. In AppDelegate.cs add this code to support Universal Link:

```
public override bool ContinueUserActivity(UIApplication application, NSUserActivity userActivity, UIApplicationRestorationHandler completionHandler)
{
        if (Xamarin.Essentials.Platform.OpenUrl(null, userActivity.WebPageUrl, new NSDictionary()))
                return true;
        return false;
}
```
        
3. In App.cs add this code:

```
protected override void OnStart()
{
        // Give this a delay to make sure app has finished launching.
        // I've tried this in many parts of our app with the same result
        Device.StartTimer(TimeSpan.FromSeconds(5), () =>
        {
                var ssoInitiationUri = new Uri("https://thirdpartyidp.com/saml2/sso/intiate");
                Xamarin.Essentials.WebAuthenticator.AuthenticateAsync(ssoInitiationUri, new Uri("https://universallink.yourcompany.com"));
                return false;
        });
}
```

4. Run the app and complete authentication successfully. When authentication modal view controller is dismissed, app left in unstable state and mono crash appears in application output.
### Expected Behavior
App should not crash

### Actual Behavior
When authentication modal view controller is dismissed, app left in unstable state and mono crash appears in application output.

### Basic Information

- Version with issue: Xamarin.Essentials v1.5.3.1
- Last known good version: N/A
- IDE: Visual Studio S for Mac 8.5.4 build 12 with Xamarin.Forms 4.5.0.657
- Platform Target Frameworks: 
  - iOS: 13.4, 11.3
- Affected Devices: Both Simulator and Device

Using Universal Link for entry point

**Comment by mattallscripts** [comment]
I've found the reason; the crash happens here:
was?.Dispose();
...which disposes of the ASWebAuthenticationSession before the iOS operating system is finished. 

The OS is supposed to dismiss the view controller, the code is assuming that iOS has already dismissed the authentication modal view controller.

However it hasn't yet because Apple's ASWebAuthenticationSession unfortunately does not support using a Universal Link as the callback.

There is a radar open for this:
40809553: ASWebAuthenticationSession and HTTPS Callback URLs

**Comment by jamesmontemagno** [comment]
Gotcha... hmmmm @Redth should we not dispose of it? That may get rid of the warning I think too.

**Comment by Redth** [comment]
@mattallscripts so do you believe calling `was?.Dispose()` will work once Apple fixes the bug to support ASWebAuthenticatorSession? 

We could for now add a platform specific flag to tell the API when you're using a Universal App Link as the callback and skip to using one of the fallback API's instead.

**Comment by jamesmontemagno** [comment]
Could be linked to: #1210

**Comment by mattallscripts** [comment]
> @mattallscripts so do you believe calling `was?.Dispose()` will work once Apple fixes the bug to support ASWebAuthenticatorSession?
> 
> We could for now add a platform specific flag to tell the API when you're using a Universal App Link as the callback and skip to using one of the fallback API's instead.

Hi Redth, yes I believe that Dispose will be fine if/when Apple adds support for Universal Link as the callback. Meanwhile if there is a way to manually dismiss the view controller (without calling Dispose) then you could do that; looking at the AsWebAuthenticationSession documentation I only see "cancel" as a possibility. I'll give it a try and let you know how it goes...

**Comment by mattallscripts** [comment]
Yup @Redth that worked.
```
                    was.Start();
                    var result = await tcsResponse.Task;
                    was?.Cancel();
                    was?.Dispose();
                    was = null;
                    return result;
```

I kept was?.Dispose() after Cancel and didn't get any error in the Application Output.

**Comment by mattallscripts** [comment]
Mind you this is a bit of a hack since it cancels the authentication session, so I don't know what repercussions it has, but it seems to work for our case.

**Comment by jamesmontemagno** [comment]
Can you try: Can you try: https://dev.azure.com/xamarin/public/_build/results?buildId=17479&view=artifacts&type=publishedArtifacts

**Comment by jamesmontemagno** [comment]
I just removed the dispose and nulling out

**Comment by mattallscripts** [comment]
The Dispose can actually stay if it's needed for proper disposal;

The business logic can be something like this;

if(scheme == https)
{
    was?.Cancel();
}
was?.Dispose();

Right now the Dispose seems to be prematurely destroying the ASWebAuthenticationSession so the second effect is that thee iOS operating system is attempting to dismiss the view controller and that also results in an exception.

If we "Cancel" the ASWebAuthenticationSession first and *then* Dispose then I think it's fine to destroy the ASWebAuthenticationSession because by then will it have terminated.

**Comment by jamesmontemagno** [comment]
Hmmmm i guess the question is do we even need to cancel if the OS is doing to do it and do we even need to dispose..... or will GC clean it up (which I assume after the OS clears it). We weren't before.

**Comment by jamesmontemagno** [comment]
I am also curious what happens on SF SafariView... if you can test on an iOS 11 device... that would kick in.

**Comment by jamesmontemagno** [comment]
So, i went deeper and yeah, from what I find neither ASWebAuthenticationSession or SFsfauthenticationsession support universal links. You are expected to use a custom uri :(

As documented: callbackURLScheme
The custom URL scheme that the app expects in the callback URL. https://developer.apple.com/documentation/authenticationservices/authenticating_a_user_through_a_web_service

**Comment by mattallscripts** [comment]
Hi again @jamesmontemagno so Apple doesn't support a Universal Link callback but the WebAuthenticator API could by using this workaround
```
if(scheme == https)
{
    was?.Cancel();
}
was?.Dispose();
```
We want to use WebAuthenticator instead of SFSafariViewController because we wants ASWebAuthenticationSession's shared cookies with Safari, however since we use a Universal Link on iOS and an App Link on Android for security reasons, we'd like a cross-platform secure solution that doesn't use a custom url scheme.

I think the above code is fairly safe, so my team will branch WebAuthenticator until if/when this is integrated into the official Xamarin.Essentials.WebAuthenticator. I can share with you the final tested version of our branch, though it'll have a lot of the backwards compatibility stripped out since we're targeting iOS 12/13.

**Comment by mattallscripts** [comment]
Hi @jamesmontemagno  @Redth here is an update and a new recommendation after having scheduled a 1-1 with Apple engineering during WWDC 2020. This is their feedback:

> **Our Question**: It appears that the ASWebAuthenticationSession API requires a url scheme callback instead of a Universal Link callback. However our security team as well as Apple documentation states that Universal Links are preferable to custom url schemes because “the system verifies the association through the Apple App Site Association file on your website, eliminating the possibility that other apps might claim your scheme and redirect your URLs” (Source). Why doesn’t ASWebAuthenticationSession support Universal Links?

> > **Paraphrased Answer**: You _can_ actually use a Universal Link as the callback by (1) passing nil for the callback url scheme, (2) listening in the app delegate for the universal link openWithOptions and then (3) Cancel the existing AsWebAuthenticationSession. However the _use of a url scheme is still encouraged_ because AsWebAuthenticationSession **does** actually guarantee that your app will be the only app to receive the callback and **in fact you don’t even need to register the custom url scheme with your app**, you can pass in whatever custom url scheme you expect to be called at the end of authentication. AsWebAuthenticationSession simply watches the url redirects in the web view and waits for the custom url scheme to appear.

>  
> **Our Question**: Currently using SFSafariViewController instead of ASWebAuthenticationSession for SAML-based SSO. Are we going to get any pushback from app review for this?
> > **Paraphrased Answer**; No, you should be fine. ASWebAuthenticationSession is just a wrapper around SFSafariViewController with the convenient addition of the callback url scheme.

Our conclusion is to continue using a Universal Link as the callback for a few reasons:

1. The Xamarin API is cross-platform, and until and when we can obtain an equivalent guarantee of privacy/security, our Android will still need to continue using a Universal Link as the callback instead of a custom url scheme to guarantee that it's the only app that will receive the callback.
2. At least one of our supported IdPs required the authentication to use an external browser instead of the system modal browser, which we enable with runtime configuration. Universal Links are the only secure option on both iOS and Android to redirect back to our app from the external system browser. Note in this scenario, we'd not use Xamarin.Essentials WebAuthenticator, but rather Xamarin.Essentials Browser.OpenAsync with the 'External' flag.

Based on all the above, I think the code would need to be updated with the following:

**File: WebAuthenticator.ios.tvos.cs**
Only perform check for pre-registered url scheme if **not** using AsWebAuthenticationSession (iOS 11 or below):
1. Apple said we do not need to register custom url scheme, it could be any callback that that SSO protocol implementation uses.
2. Apple said we can even pass in nil can to use Universal Link with AsWebAuthenticationSession.

```
// **NEW**: Only iOS 9 or later supports Universal Links so enforce custom url scheme
if(UIDevice.CurrentDevice.CheckSystemVersion(9, 0) == false && scheme.BeginsWith('https'))
{
                    tcsResponse.TrySetException(new InvalidOperationException("Universal Links are only supported on iOS 9 or later."));
                    return await tcsResponse.Task;
}

// **NEW**: If using a custom url scheme on iOS 9 or below then require pre-registered custom url scheme since SFSafariViewController will be used
if (UIDevice.CurrentDevice.CheckSystemVersion(10, 0) == false && scheme.BeginsWith('https') == false)
{
                if (!VerifyHasUrlSchemeOrDoesntRequire(scheme))
                {
                    tcsResponse.TrySetException(new InvalidOperationException("You must register your URL Scheme handler in your app's Info.plist!"));
                    return await tcsResponse.Task;
                }
}
```

**Comment by mattleibow** [comment]
I think this is a duplicate of #1519. That issue has a simpler way to test as it doesn't require universal links.

I'm going to close this now, and I'll re-open if this turns out to be a separate issue.
Let me know if I am wrong and this is not related, but the native stack trace looks exactly the same.
