### ISSUE TITLE
[Enhancement] iOS Location permission "AskNextTime"

### ISSUE THREAD

**Issue by cgk-joes** [xamarin/Essentials#1251]
## Summary
At this moment we can check the location permission on iOS with the options:  
``` c#
XamEssentials.Permissions.CheckStatusAsync<XamEssentials.Permissions.LocationAlways>();
// OR
XamEssentials.Permissions.CheckStatusAsync<XamEssentials.Permissions.LocationWhenInUse>();
```

## Problem
When the user allowed the permission, but changes it in the app specific settings to `Ask Next Time` the previous call to `CheckStatusAsync` will return a `PermissionStatus.Unknown`.
This in turn gives us no handle to react adequate to it.

## API Changes
Include an option like (preferred):  
``` c#
XamEssentials.Permissions.CheckStatusAsync<XamEssentials.Permissions.LocationAskNextTime>();
```
Or return a different status like:
``` c#
PermissionStatus.Ask
```

## Intended Use Case
When the user has set the permission to ask next time, we would like to be able to check it and react to it adequate.
My excuses if this can be solved already with the current code base. I searched in the source code, thought about different flows in my own code, but I cannot seem to find a proper solution.

**Comment by mattleibow** [comment]
If the permissible status is unknown, can you just request it again?

**Comment by cgk-joes** [comment]
What are the conditions for the API to return unknown? Because we don't want to annoy the user with the question to allow this permission if it was not needed. 

```c#
public enum PermissionStatus
{
	/// <summary>The permission hasn't been granted or requested and is in an unknown state.</summary>
	Unknown,
	/// <summary>The user has denied the permission.</summary>
	Denied,
	/// <summary>The permission is disabled for the app.</summary>
	Disabled,
	/// <summary>The user has granted permission.</summary>
	Granted,
	/// <summary>The permission is in a restricted state.</summary>
	Restricted
}
```
In my example, when the user had selected "Ask Next Time", it will return the "Unknown" status, but that means the "Unknown" status can have multiple types of definitions. How are we then able to handle the "Ask Next Time" in a good manner, and ignore the others?

**Comment by jamesmontemagno** [comment]
On iOS you will get an "Unknown" response. You then only get one prompt to ask them for permission.

On Android you will get a Denied by default. Then you can prompt them as many times as you would like.

On Android we have added a new "ShouldShowRationale" which means it was previously denied and you should give reason why you are prompting again. 

iOS does not have this concept. 

Will close out as I have added some new documentation.
