### ISSUE TITLE
[Enhancement] detect where the app was installed from

### ISSUE THREAD

**Issue by tele-bird** [xamarin/Essentials#1252]
## Summary
Detect the source of the app installation.  For example, whether it was installed from TestFlight, App Store, App Center, Google Play, Google Play Beta, etc..

## API Changes

Probably all that's needed is a property that return an enum value.  Enum would list all the possible app sources.

## Intended Use Case
We want to have different behavior depending on whether it is an internal (beta testing) app or Production app.  Specifically, for internal CI/CD builds, we want to let internal users select the non-production operating environment of their choice.  Obviously, we don't want production users to be able to select non-production environments!  And, we don't want to achieve this via different (prod/non-prod) build targets because we want a single build, whose output is unmodified (or rebuilt) while different internal parties test and approve the functionality on the way to approval and publish to app stores.  We find that rebuilding with different build targets along the way causes a lot of extra smoke testing, so we are trying to eliminate that.

**Comment by jamesmontemagno** [comment]
The question we usually for something like this is if this is a native API or not.

I know App Center does something like this....

https://stackoverflow.com/questions/18282326/how-can-i-detect-if-the-currently-running-app-was-installed-from-the-app-store

Do you have it currently implemented?

**Comment by tele-bird** [comment]
No, at this point, I'm just looking around for solutions.  Not sure whether that old stackoverflow post solution will work anymore.

**Comment by jamesmontemagno** [comment]
Gotcha, i don't know if there are official solutions provided from Apple/Google/Microsoft so we will have to do some research as we only abstract out official stable APIs.

**Comment by tele-bird** [comment]
For Android, it appears to be [PackageManager.getInstallerPackageName()](https://developer.android.com/reference/android/content/pm/PackageManager#getInstallerPackageName(java.lang.String)) until R when it was deprecated.  Guidance to use [PackageManager.getInstallSourceInfo()](https://developer.android.com/reference/android/content/pm/PackageManager#getInstallSourceInfo(java.lang.String)) instead.

**Comment by tele-bird** [comment]
Apple responded to my support ticket about this by saying that Bundle.main.appStoreReceiptURL not being null is an indication that the app was installed from the App Store.  However, there are cases where it **will** be null, even though it **was** installed from the App Store, such as when device data was restored from backup without an internet connection.

Moreover, they went on to say that "the presence or absence of the appStoreReceipt has never been documented as a means to test whether the app was installed from the App Store or not the App Store..  Also note that you cannot distinguish as to whether the app was installed from Test Flight or installed on an App Review device."

So, probably this means there's no reliable way to achieve this on iOS. 👎

**Comment by mattleibow** [comment]
Closing this as it appears that this API is not very reliable. If there is ever a native API to do this, then we can revisit.
