### ISSUE TITLE
GPS Location Enable in Xamarin Forms

### ISSUE THREAD

**Issue by kerberosargos** [xamarin/Essentials#1257]
Hello, firstly thank you for your good works. I have a method as below. I would like to force android device's gps when **FeatureNotEnabledException** invoke. 

May be open android gps control window. is there any bult-in method or your suggestion approach? Thank you in advance.  

```

private async void GetLocationAsync()
        {

            PermissionStatus locationPermissionStatus = await Permissions.CheckStatusAsync<Permissions.LocationWhenInUse>();

            if (locationPermissionStatus == PermissionStatus.Granted)
            {

                var knownLocation = await Geolocation.GetLastKnownLocationAsync();

                if (knownLocation != null)
                {
                    GetLocationDetailsAsync(knownLocation.Latitude, knownLocation.Longitude);
                    Debug.WriteLine($"Latitude: {knownLocation.Latitude}, Longitude: {knownLocation.Longitude}, Altitude: {knownLocation.Altitude}");
                }
                else
                {

                    try
                    {
                        var request = new GeolocationRequest(GeolocationAccuracy.Best);
                        var location = await Geolocation.GetLocationAsync(request);

                        if (location != null)
                        {
                            GetLocationDetailsAsync(location.Latitude, location.Longitude);
                            Debug.WriteLine($"Latitude: {location.Latitude}, Longitude: {location.Longitude}, Altitude: {location.Altitude}");
                        }
                    }
                    catch (FeatureNotSupportedException featureNotSupportedException)
                    {

                    }
                    catch (FeatureNotEnabledException featureNotEnabledException)
                    {
                        //> I would like to force to enable device's gps in this line
                    }
                    catch (PermissionException permissionException)
                    {
                        AppInfo.ShowSettingsUI();
                        GetLocationAsync();
                    }
                    catch (Exception exception)
                    {
          
                    }
                }
            }
            else
            {
                await Permissions.RequestAsync<Permissions.LocationWhenInUse>();
                GetLocationAsync();
            }
        }

```

**Comment by mattleibow** [comment]
I don't think there is a real way to do that... Privacy and all... But, the typical approach is to show a message and pop the app settings.

**Comment by jamesmontemagno** [comment]
That is correct, you can pop open the settings or just ask the user to turn it on. There isn't a direct API for this sorry.

**Comment by kerbooo** [comment]
Hello everyone, I have achieve that as below. May be you can want to implement that to **Xamarin Essentials.**

**IGpsDependencyService.cs**

```
namespace DemoApp.Services
{
    public interface IGpsDependencyService
    {
        void OpenSettings();
        bool IsGpsEnable();
    }  
}
```

**Android > GpsDependencyService.cs**

```
using Android.Content;
using Android.Locations;
using DemoApp.Droid.Customizers;
using DemoApp.Services;
using Xamarin.Forms;

[assembly: Dependency(typeof(GpsDependencyService))]
namespace MengerlerRoadService.Droid.Customizers
{
    public class GpsDependencyService : IGpsDependencyService
    {
        public bool IsGpsEnable()
        {
            LocationManager manager = (LocationManager)Android.App.Application.Context.GetSystemService(Context.LocationService);
            return manager.IsProviderEnabled(LocationManager.GpsProvider);
        }

        public void OpenSettings()
        {
            Android.App.Application.Context.StartActivity(new Android.Content.Intent(Android.Provider.Settings.ActionLocat‌​ionSourceSettings));
        }

    }
}
```
**iOS > GpsDependencyService**

```
using CoreLocation;
using Foundation;
using DemoApp.iOS.Customizers;
using DemoApp.Services;
using UIKit;
using Xamarin.Forms;

[assembly: Dependency(typeof(GpsDependencyService))]
namespace MengerlerRoadService.iOS.Customizers
{
    public class GpsDependencyService : IGpsDependencyService
    {

        public bool IsGpsEnable()
        {
            if (CLLocationManager.Status == CLAuthorizationStatus.Denied)
            {
                return false;
            }
            else
            {
                return true;
            }
        }

        public void OpenSettings()
        {
            var WiFiURL = new NSUrl("prefs:root=WIFI");
            
            if (UIApplication.SharedApplication.CanOpenUrl(WiFiURL))
            {   //> Pre iOS 10
                UIApplication.SharedApplication.OpenUrl(WiFiURL);
            }
            else
            {   //> iOS 10
                UIApplication.SharedApplication.OpenUrl(new NSUrl("App-Prefs:root=WIFI"));
            }
        }
    }
}
```
**Prism > DemoGpsViewModel.cs**

```
using System;
using DemoApp.Services;
using Prism.Mvvm;
using Prism.Navigation;
using Xamarin.Forms;

namespace DemoApp.ViewModels
{
    public class HomePageViewModel : BindableBase, IInitialize
    {
        public void Initialize(INavigationParameters parameters)
        {
            Device.StartTimer(TimeSpan.FromSeconds(1), () =>
            {
                IsGpsEnable = Xamarin.Forms.DependencyService.Get<IGpsDependencyService>().IsGpsEnable();

                if (!IsGpsEnable)
                {
                    Xamarin.Forms.DependencyService.Get<IGpsDependencyService>().OpenSettings();
                }
                return true;

            });
        }

        private bool _isGpsEnable;
        public bool IsGpsEnable
        {
            get => _isGpsEnable;
            set => SetProperty(ref _isGpsEnable, value);
        }
    }
      
}

```

**Comment by kerbooo** [comment]
Hello everyone, I have achieve that as below. May be you can want to implement that to **Xamarin Essentials.**

**IGpsDependencyService.cs**

```
namespace DemoApp.Services
{
    public interface IGpsDependencyService
    {
        void OpenSettings();
        bool IsGpsEnable();
    }  
}
```

**Android > GpsDependencyService.cs**

```
using Android.Content;
using Android.Locations;
using DemoApp.Droid.Customizers;
using DemoApp.Services;
using Xamarin.Forms;

[assembly: Dependency(typeof(GpsDependencyService))]
namespace MengerlerRoadService.Droid.Customizers
{
    public class GpsDependencyService : IGpsDependencyService
    {
        public bool IsGpsEnable()
        {
            LocationManager manager = (LocationManager)Android.App.Application.Context.GetSystemService(Context.LocationService);
            return manager.IsProviderEnabled(LocationManager.GpsProvider);
        }

        public void OpenSettings()
        {
            Android.App.Application.Context.StartActivity(new Android.Content.Intent(Android.Provider.Settings.ActionLocat‌​ionSourceSettings));
        }

    }
}
```
**iOS > GpsDependencyService**

```
using CoreLocation;
using Foundation;
using DemoApp.iOS.Customizers;
using DemoApp.Services;
using UIKit;
using Xamarin.Forms;

[assembly: Dependency(typeof(GpsDependencyService))]
namespace MengerlerRoadService.iOS.Customizers
{
    public class GpsDependencyService : IGpsDependencyService
    {

        public bool IsGpsEnable()
        {
            if (CLLocationManager.Status == CLAuthorizationStatus.Denied)
            {
                return false;
            }
            else
            {
                return true;
            }
        }

        public void OpenSettings()
        {
            var WiFiURL = new NSUrl("prefs:root=WIFI");
            
            if (UIApplication.SharedApplication.CanOpenUrl(WiFiURL))
            {   //> Pre iOS 10
                UIApplication.SharedApplication.OpenUrl(WiFiURL);
            }
            else
            {   //> iOS 10
                UIApplication.SharedApplication.OpenUrl(new NSUrl("App-Prefs:root=WIFI"));
            }
        }
    }
}
```
**Prism > DemoGpsViewModel.cs**

```
using System;
using DemoApp.Services;
using Prism.Mvvm;
using Prism.Navigation;
using Xamarin.Forms;

namespace DemoApp.ViewModels
{
    public class HomePageViewModel : BindableBase, IInitialize
    {
        public void Initialize(INavigationParameters parameters)
        {
            Device.StartTimer(TimeSpan.FromSeconds(1), () =>
            {
                IsGpsEnable = Xamarin.Forms.DependencyService.Get<IGpsDependencyService>().IsGpsEnable();

                if (!IsGpsEnable)
                {
                    Xamarin.Forms.DependencyService.Get<IGpsDependencyService>().OpenSettings();
                }
                return true;

            });
        }

        private bool _isGpsEnable;
        public bool IsGpsEnable
        {
            get => _isGpsEnable;
            set => SetProperty(ref _isGpsEnable, value);
        }
    }
      
}

```

**Comment by newky2k** [comment]
@kerbooo Could you turn this into a pull request so we can look at merging it in.

Thanks in advane

**Comment by kerbooo** [comment]
> 
> 
> @kerbooo Could you turn this into a pull request so we can look at merging it in.
> 
> Thanks in advance

Hello. I have not so much experience for github. How to turn this into a pull request? Could you help me please? Also I have edited Android Dependency Service code post.

**Comment by newky2k** [comment]
@kerboo I typically start of by forking the repo and then making the changes directly to the code in my copy.  Once i have completed the code changes and comitted them into my fork,  Github make it really easy to create a Pull Request to enable your changed to be merged into the main code tree.

Gihub has a great tutorial on this -> https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

Thanks in advance

**Comment by gsgou** [comment]
@kerbooo is your app still passing the App Store Rejection rules?

The "app-prefs" URL scheme is not supported by Apple, prefs URLs are considered as private APIs, the only documented preference URL is the UIApplicationOpenSettingsURLString.
Refer
https://stackoverflow.com/questions/49486705
https://stackoverflow.com/questions/52301580

**Comment by kerbooo** [comment]
Thank you very much for your information.

19 Tem 2020 Paz 10:51 tarihinde Giorgos Sgouridis <notifications@github.com>
şunu yazdı:

**Comment by angelru** [comment]
> Hola a todos, lo he logrado de la siguiente manera. Puede que desee implementar eso en **Xamarin Essentials.**
> 
> **IGpsDependencyService.cs**
> 
> ```
> namespace DemoApp.Services
> {
>     public interface IGpsDependencyService
>     {
>         void OpenSettings();
>         bool IsGpsEnable();
>     }  
> }
> ```
> 
> **Android> GpsDependencyService.cs**
> 
> ```
> using Android.Content;
> using Android.Locations;
> using DemoApp.Droid.Customizers;
> using DemoApp.Services;
> using Xamarin.Forms;
> 
> [assembly: Dependency(typeof(GpsDependencyService))]
> namespace DemoApp.Droid.Customizers
> {
>     public class GpsDependencyService : IGpsDependencyService
>     {
> 
>  public bool IsGpsEnable()
>         {
>             LocationManager locationManager = (LocationManager)Android.App.Application.Context.GetSystemService(Context.LocationService);
>             return locationManager.IsProviderEnabled(LocationManager.GpsProvider);
>         }
> 
>         public void OpenSettings()
>         {
> 
>             Intent intent = new Intent(Android.Provider.Settings.ActionLocat‌​ionSourceSettings);
>             intent.SetFlags(ActivityFlags.ClearTop | ActivityFlags.NewTask);
>             
>             try
>             {
>                 Android.App.Application.Context.StartActivity(intent);
>       
>             }
>             catch (ActivityNotFoundException activityNotFoundException)
>             {
>                 System.Diagnostics.Debug.WriteLine(activityNotFoundException.Message);
>                 Android.Widget.Toast.MakeText(Android.App.Application.Context, "Error: Gps Activity", Android.Widget.ToastLength.Short).Show();
>             }
>          
>         }
> 
> }
> }
> ```
> 
> **iOS> GpsDependencyService.cs**
> 
> ```
> using CoreLocation;
> using Foundation;
> using DemoApp.iOS.Customizers;
> using DemoApp.Services;
> using UIKit;
> using Xamarin.Forms;
> 
> [assembly: Dependency(typeof(GpsDependencyService))]
> namespace DemoApp.iOS.Customizers
> {
>     public class GpsDependencyService : IGpsDependencyService
>     {
> 
>         public bool IsGpsEnable()
>         {
>             if (CLLocationManager.Status == CLAuthorizationStatus.Denied)
>             {
>                 return false;
>             }
>             else
>             {
>                 return true;
>             }
>         }
> 
>         public void OpenSettings()
>         {
>             var WiFiURL = new NSUrl("prefs:root=WIFI");
>             
>             if (UIApplication.SharedApplication.CanOpenUrl(WiFiURL))
>             {   //> Pre iOS 10
>                 UIApplication.SharedApplication.OpenUrl(WiFiURL);
>             }
>             else
>             {   //> iOS 10
>                 UIApplication.SharedApplication.OpenUrl(new NSUrl("App-Prefs:root=WIFI"));
>             }
>         }
>     }
> }
> ```
> 
> **Prisma> DemoGpsViewModel.cs**
> 
> ```
> using System;
> using DemoApp.Services;
> using Prism.Mvvm;
> using Prism.Navigation;
> using Xamarin.Forms;
> 
> namespace DemoApp.ViewModels
> {
>     public class DemoGpsViewModel: BindableBase, IInitialize
>     {
>         public void Initialize(INavigationParameters parameters)
>         {
>             Device.StartTimer(TimeSpan.FromSeconds(1), () =>
>             {
>                 IsGpsEnable = Xamarin.Forms.DependencyService.Get<IGpsDependencyService>().IsGpsEnable();
> 
>                 if (!IsGpsEnable)
>                 {
>                     Xamarin.Forms.DependencyService.Get<IGpsDependencyService>().OpenSettings();
>                 }
>                 return true;
> 
>             });
>         }
> 
>         private bool _isGpsEnable;
>         public bool IsGpsEnable
>         {
>             get => _isGpsEnable;
>             set => SetProperty(ref _isGpsEnable, value);
>         }
>     }
>       
> }
> ```

Esto funciona actualmente?

**Comment by dazlab** [comment]
What is the rationale behind doing it this way? Can't you just implement the GpsDependancyService as a standard class, and then reference the IsGpsEnable() method? Have tested this way as I couldn't get the posted solution to work. It kept erroring with "children could not be evaluated".

I changed it to a standard class with a static member:

```
public static bool IsGpsTurnedOn()
        {
#if ANDROID
            LocationManager locationManager = 
            (LocationManager)Android.App.Application.Context.GetSystemService(Context.LocationService);
            return locationManager.IsProviderEnabled(LocationManager.GpsProvider) ;
#else
            return false;
#endif
        }
```

`bool IsGpsEnabled = GpsDependencyService.IsGpsTurnedOn();`

This correctly returns the appropriate response. It's probably really bad practice, but what is wrong about using it in this way?

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
