### ISSUE TITLE
[Bug] Email.ComposeAsync(emailMessage) throws FeatureNotSupportedException

### ISSUE THREAD

**Issue by KevinHu-au** [xamarin/Essentials#1259]
### Description
Email.ComposeAsync(emailMessage) throws FeatureNotSupportedException on Android device. Although the device has email clients configured.

This happens when email body format is Html and Text.
### Steps to Reproduce

1.  Create a simple email message .
            EmailMessage emailMessage = new EmailMessage
            {
                To = new List<string> { "support@gmail.com" },
                Body = "Testing email",
                BodyFormat = EmailBodyFormat.PlainText,
                Subject = "subject"
            };
2. Create a method to call the "await Email.ComposeAsync(emailMessage);"
3. And the ComposeAsync() throws the "FeatureNotSupportedException"

### Expected Behavior
The email compose view should shows up
### Actual Behavior
throws the "FeatureNotSupportedException"
### Basic Information

- Version with issue:  Xamarin.Essentials 1.5.3
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - Android: Android 10(Q)
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Samsung S7 and Samsung A20

**Comment by luizous** [comment]
I'm having this bug with ios device. Someone knows what can be?
