### ISSUE TITLE
after opening the chrome from android, we would like to push a sequence of  buttons

### ISSUE THREAD

**Issue by moustafa991982** [xamarin/Essentials#1260]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
After we have triggered the opening of the browser on a certain website, we would like to code a p sequence of pressing buttons at the website we opened , so for example the code could select a certain menu and press on some buttons at this opened website
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
Thanks for the suggestion here. The Browser api is just to open the browser. You would want to actually use a built in browser control and then invoke javascript to achieve this.
