### ISSUE TITLE
[Bug] A case where Permissions.CheckStatusAsync fails in UWP.

### ISSUE THREAD

**Issue by WillAutioItrax** [xamarin/Essentials#1261]
### Description
A case where Permissions.CheckStatusAsync fails in UWP.
### Steps to Reproduce

1. run the attached app
2. navigate to About

### Expected Behavior
The text is displayed.
### Actual Behavior
Get an exception:
'The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))

### Basic Information

- Version with issue: VS 16.5.4
- Last known good version: First try
- IDE: 
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   16299 plus
- Android Support Library Version: 
- Nuget Packages:
Xamarin.Forms" Version="4.6.0.726"
Xamarin.Essentials" Version="1.5.3.1
Microsoft.NETCore.UniversalWindowsPlatform" Version="6.1.9"

- Affected Devices:
Local machine
### Reproduction Link
https://github.com/WillAutioItrax/PermissionFail2

**Comment by jamesmontemagno** [comment]
You added `.ConfigureAwait(false)` which means it will not resume on the UI thread.

Remove this from your code and it will work.

**Comment by WillAutioItrax** [comment]
@jamesmontemagno Thanks for the explanation.
