### ISSUE TITLE
[Bug] WebAuthenticator - User closes dialog box

### ISSUE THREAD

**Issue by rkilhams** [xamarin/Essentials#1263]
### Description
When using the WebAuthenticator.AuthenticateAsync method on a UWP application, if the user closes the windows dialog box (Connecting to a service) by clicking the X button, an exception is thrown.
### Steps to Reproduce

1. Call the AuthenticateAsync method with the appropriate StartUrl/RedirctUri
2. When the login page is shown in the Windows dialog box, close the window by clicking the X in the top right hand corner

### Expected Behavior
I expected the return value of this method to be null if the user cancels the operation

### Actual Behavior
An exception is thrown

### Basic Information

- Version with issue: 1.5.3.1

**Comment by mattleibow** [comment]
Fixed in https://github.com/xamarin/Essentials/pull/1281
