### ISSUE TITLE
WebAuthenticator not returning to app.

### ISSUE THREAD

**Issue by solomonfried** [xamarin/Essentials#1266]
I am trying to implement WebAuthenticator on my app. I am starting with the UWP version. I have created a NETCore service on Azure and am running the code pretty much as taken from the example pages

```
 .AddGoogle(g =>
                {
                    IConfigurationSection googleAuthNSection =
                        Configuration.GetSection("Authentication:Google");

                    g.ClientId = googleAuthNSection["ClientId"];
                    g.ClientSecret = googleAuthNSection["ClientSecret"];
                    g.SaveTokens = true;
                });
```
On the client I call Xamarin.Essentials.WebAuthenticator.AuthenticateAsync(authUrl, callbackUrl); 
It displays the Google Login screen.
Once I enter my userid and password, I get a message in the login Window

"We can't connect to the service you need right now. Check your network connection or try this again later."

When I close that windows I catch this Exception
"The specified protocol is unknown. (Exception from HRESULT: 0x800C000D)"

I have been using Xamarin.OAuth till now and that works.  I am switching to gain the security of keeping my ClientIDs out of the app and also the need to support Apple Sign in. 

Any assistance or ideas would be appreciated.

(Also, is there a way for the Google login screen to display my App Name instead of the Auth web site name?)

### Expected Behavior
Application should return after WebAuthenticator.AuthenticateAsync

### Actual Behavior
Callback is not executed

### Basic Information

- Version with issue:
Xamarin.Essentials 1.5.3.1

- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: 
  - UWP:  18362

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/36649129/81232765-70acf800-8fc3-11ea-855c-ef3b9261a6eb.png)

![image](https://user-images.githubusercontent.com/36649129/81232814-92a67a80-8fc3-11ea-8b2f-d89e8197d72b.png)

**Comment by rkilhams** [comment]
Hi, not sure if it is any help but did you add the Protocol to the Package.appxmanifest file? This is the first part of my RedirectUri

**Comment by solomonfried** [comment]
Thanks for the reply.

When debugging the service, it is responding with a URL
classtars://#access_token=XXXXXXXXXXXXXXXXXXXXXXX&expires=1590072786

(so far so good)

My app manifest looks like this

**Comment by solomonfried** [comment]
Somehow started working after trying changes to my protocol name (but then reverted and it still works). 
Never-the-less the issue seems to be resolved.
