### ISSUE TITLE
[Enhancement] Return information from provider using access token.

### ISSUE THREAD

**Issue by solomonfried** [xamarin/Essentials#1267]
## Summary
The WebAuthenticator returns an access token and expiration date to the client. In practically all cases, the client will then call the underlying provider to get the Email, and possibly other information (Name, Image, etc...)

It would be great if the WebAuthenticator provided this service for the major providers.

## API Changes
Add Provider Enum

```
public enum AuthenticatorProvider{
  Apple,
  Google,
  Facebook
  ….
}
```

Add static call to WebAuthenticor.
`public static Dictionary<string, string> WebAuthenticator.GetUserInformation(string accessToken, AuthenticatorProvider provider);
`

e.g.

```
token = await AppleSignInAuthenticator.AuthenticateAsync();
userinfo = WebAuthenticator.GetUserInformation(token.AccessToken, AuthenticatorProvider.Apple); 

```
.

**Comment by solomonfried** [comment]
I did manage to get the email information from the server call
`Request.HttpContext.AuthenticateAsync(scheme);`
and return it to the client.

If you look at the WebAuth controller example here...
[https://github.com/xamarin/Essentials/blob/develop/Samples/Sample.Server.WebAuthenticator/Controllers/MobileAuthController.cs](https://github.com/xamarin/Essentials/blob/develop/Samples/Sample.Server.WebAuthenticator/Controllers/MobileAuthController.cs)

I modified the code in the Get as follows:
```
if (!auth.Succeeded
                    || auth.Principal == null
                    || !auth.Principal.Identities.Any(id => id.IsAuthenticated)
                    || string.IsNullOrEmpty(auth.Properties.GetTokenValue("access_token")))
                {
                    // Not authenticated, challenge
                    await Request.HttpContext.ChallengeAsync(scheme);
                }
                else
                {
                   // ADDED THE FOLLOWING
                    var claims = auth.Principal.Identities.FirstOrDefault()?.Claims;
                    string email = string.Empty;
                    if (claims != null)
                        email = claims.FirstOrDefault(c =>
                                c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress")
                            ?.Value;
                    // Get parameters to send back to the callback
                    var qs = new Dictionary<string, string>
                    {
                        {"access_token", auth.Properties.GetTokenValue("access_token")},
                        {"refresh_token", auth.Properties.GetTokenValue("refresh_token") ?? string.Empty},
                        {"expires", (auth.Properties.ExpiresUtc?.ToUnixTimeSeconds() ?? -1).ToString()},
                        {"email", email}
                    };
```

A you can see, I can get the email from the Claims (not sure in what situation multiple identities would be returned, but I am taking the Claims from the first one.

I then add the email to the returning Dictionary.

On the client the code is

**Comment by newky2k** [comment]
@solomonfried If you could add this as a pull request then we could take a look at it and try to get it into a future release.

Regards

**Comment by solomonfried** [comment]
I have created a pull request

https://github.com/xamarin/Essentials/pull/1287

Thank you

**Comment by newky2k** [comment]
@solomonfried  Thats great thank you, i'll take a look at you PR

**Comment by solomonfried** [comment]
Documentation was updated on GitHub. 
https://github.com/xamarin/Essentials/blob/develop/Samples/Sample.Server.WebAuthenticator/Controllers/MobileAuthController.cs
