### ISSUE TITLE
[Bug] Keep on getting the console logs in Android for 360 degree orientation changes of the Android device 

### ISSUE THREAD

**Issue by iamvignesh** [xamarin/Essentials#1274]
### Description
The Xamarin.Essentials is tracking all 360 degree change of the device instead of desired Landscape or Portrait
And also emitting the orientation changes console logs if registered

### Steps to Reproduce

1. Install The Xamarin.Essentials 1.5.3.2 in Xamarin.Form multiplatform app with .NetStandard code sharing
2. Then Subscribe the orientation event with Xamarin.Essentials.DeviceDisplay.MainDisplayInfoChanged
3. If you run the application in the device you will see the console logs for 360 degree orientation changes
like "[OrientationEventListener] Orientation is:24 X:2.1050115 Y:-4.6380877 Z:-8.40415"

### Expected Behavior
Expected to be Landscape or portrait,And It is much helpful If console logs are not emitted from the Xamarin.Essentials
### Actual Behavior
Seeing Console logs "[OrientationEventListener] Orientation is:24 X:2.1050115 Y:-4.6380877 Z:-8.40415"
### Basic Information

- Version with issue: 1.5.3.2
- IDE:Visual Studio for mac 8.4.5
- Platform Target Frameworks:
  - Android: Android 9.0(pie)
- Affected Devices: Vivo 

### Screenshots

<img width="821" alt="Screenshot 2020-05-14 at 12 11 42 PM" src="https://user-images.githubusercontent.com/7777632/81901522-48815280-95dc-11ea-8bd7-1b832e106c9f.png">

**Comment by mattleibow** [comment]
The orientation sensor is for orientation in 3D space. You probably want DeviceDisplay's main display orientation...

**Comment by mattleibow** [comment]
And I'll look at those logs. Thanks for reporting.

**Comment by mattleibow** [comment]
Wait a minute... We log nothing. That is the Android just filling the logs... Imagine how fast Android would be if it logged less. Unless that is just in developer mode...

**Comment by mattleibow** [comment]
Wait a minute... We log nothing. That is the Android just filling the logs... Imagine how fast Android would be if it logged less. Unless that is just in developer mode...

**Comment by jamesmontemagno** [comment]
Yup, can confirm we log nothing in our source code.
