### ISSUE TITLE
[Enhancement] Finished Sharing Handling

### ISSUE THREAD

**Issue by AndyNetDuma** [xamarin/Essentials#1275]
## Summary
This would allow you to detect if a user successfully finished sharing a file, if they clicked cancel or if an error occured.

## API Changes

This could be done in 3 ways.
Method 1 would be to only return from awaitted share.RequestAsync after the user has provided a response.
While this is the C# way to do it, it would break backwards compatibility

The second option would be to add a callback property to the request class like so
```
await Share.RequestAsync(new ShareFileRequest
{
    Title = "A title",
    File = new ShareFile(path),
    Callback = (status) => SomeHandling();
});
```
This works however the change would have to apply to all request types. Not knowiing the code I don't know if this could be inherited.

Finally you could add it as a polymorphic call to RequestAsync like so
```
await Share.RequestAsync(new ShareFileRequest
{
    Title = "A title",
    File = new ShareFile(path),
}, Callback = (status) => SomeHandling());
```
There are probably other ways I haven't thought of.

## Intended Use Case
This can be used to provide feedback to the user and help with large files
In my case I wish to share a large file. Due to the large size I want to delete it once it has been shared however it also contains important information so it would be an issue if I accidentally deleted it when the user pressed cancel. On top of that I don't know when the file finishes copying even when shared successfully.

**Comment by jamesmontemagno** [comment]
Adding context: https://developer.apple.com/documentation/uikit/uiactivityviewcontrollercompletionwithitemshandler?language=objc

**Comment by jamesmontemagno** [comment]
I think the biggest issue with probably adding something like this is that only iOS has a callback. From what I can see I don't think Android or UWP do, but I need to research a bit more. 

If it did I think we would just return a "Task<bool>" instead of a "Task"... then you could check the bool for status. No need for the callback as the Task itself would be telling you this.

For the time being though I would just create your own implementation for your iOS app.

**Comment by AndyNetDuma** [comment]
> only iOS has a callback
That's unfortunate.

I have at least a few months before I actually have to have it so I will leave it for now and watch this thread
If you make any progress do let me know. Worst case I can spin my own version but I'm trying to stay away from platform specific code as much as possible to save time.
Thanks for looking into it
