### ISSUE TITLE
[Question] Geolocation Listener and PositionChanged?

### ISSUE THREAD

**Issue by LittleCornerDev** [xamarin/Essentials#1276]
I was looking into possibly migrating a Xamarin.Forms app from using `Plugin.Geolocator` to `Xamarin.Essentials.Geolocation` but couldn't find the corresponding method for `StartListeningAsync` and `PositionChanged`.

Does Xamarin.Essentials.Geolocation also have a way where we can specify the time interval and/or distance after which to check location changes?   

Am currently using an event handler for PositionChanged that triggers a page refresh.

**Comment by newky2k** [comment]
@LittleCornerDev  It looks like Xamarin.Essentials is not designed to work the way you are currently working, via the Plugin.Geolocator library.  Essentials is only, currently, providing current location on request queries and no event driven location API is available.

This could be something that is added to the API later, especially if you can provide a PR with the required changes,

Thanks

**Comment by Loongle** [comment]
I've been waiting for this listening event

**Comment by Loongle** [comment]
This is a feature used at high frequencies

**Comment by LartAceIgnacio** [comment]
Are there any plans to have the listening event for this one?? 

Thanks for the reply
