### ISSUE TITLE
[Enhancement] Implementation of ShouldShowRequestPermissionRationale

### ISSUE THREAD

**Issue by devWaleed** [xamarin/Essentials#1277]
## Summary
Using the ShouldShowRequestPermissionRationale we can check if user has denied a permissions peprmanently. This way we can redirect user to settings app/page instead of request permissions.

## Intended Use Case
For example, i request camera permission and its already denied, i still request again and it will give user to deny permanently. In this case, now if i request permission for the third time, it will not show popup, instead my code will simply give me denied request. 

In other plugins there is a way to know if popup can be showing using AppCompat.ShouldShowRequestPermissionRationale. 

If we can know that popup will not show, we can show a custom dialog or message instead of request again and again.

**Comment by jamesmontemagno** [comment]
Will be in 1.6: https://github.com/xamarin/Essentials/pull/1200
