### ISSUE TITLE
[Bug/Question] Error when building from iOS buildpipeline

### ISSUE THREAD

**Issue by TimHi** [xamarin/Essentials#1278]
I'm trying to build via our build pipeline, however it fails with "MTOUCH : error MT2001: Could not link assemblies.". On my machine it builds fine 

I think the following error causes the problem:

> MTOUCH : error MT2001: Could not link assemblies. [iOS.csproj]
>   	Type: `Xamarin.Essentials.AuthManager`
>   	Assembly: `Xamarin.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`
>   Reason: Value cannot be null.
>   Parameter name: key

Did anyone encounter this issue already?

**Comment by jamesmontemagno** [comment]
What build pipeline are you using?

Are you using WebAuthenticator?

**Comment by TimHi** [comment]
Azure dev ops, but I think we already found the problem, I'm building locally with a higher iOS SDK Version (13) than the pipeline (12), using 13 in the pipeline solved this issue.

**Comment by Monikaprime** [comment]
I am also getting same error while build in ios from visual studio 2017 in windows
but i m not using any authmanager why this error is coming

**Comment by TimHi** [comment]
@Monikaprime Check your iOS SDK version thats the only tip i can give

**Comment by Monikaprime** [comment]
done thanks
