### ISSUE TITLE
[Bug] ShowSettingsUI returns before settings UI is opened

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Essentials#1279]
ShowSettingsUI is a synchronous method that opens the device's settings UI. A common use case for opening the app's settings is to ask the user to enable some permissions for the app.

However, ShowSettingsUI instantly returns while the device settings open at a later time, making it impossible to do (pseudo) code like:

if (PromptToOpenSettings() == "YES")
{
    ShowSettingsUI();
    AskForPermissions(); <--- this will execute before the settings UI is shown
}

Could AskForPermissions either wait until the settings dialog has been opened, or add an async variant? I don't know what good the current one will do as you can't react to any settings changes.

Thanks.

**Comment by Tommigun1980** [comment]
I was able to work around this by adding a service that listens to all resume and pause events (also from native Android side as it works differently than Application's life cycle events on iOS), and another service that has an asynchronous method that calls PromptToOpenSettings, while waiting for the next resume event from the main activity. It actually works flawlessly so if someone else is in a pinch go for it, but it's a ton of unnecessary code so I'd still appreciate native support for it.

Thanks!

**Comment by jamesmontemagno** [comment]
Yeah, that seems like better route of doing it. I mean we just send the event, it isn't meant to wait until it returns. This is implemented as designed today as each platform doesn't offer a way of waiting for it to come back to your app.

**Comment by Tommigun1980** [comment]
> Yeah, that seems like better route of doing it. I mean we just send the event, it isn't meant to wait until it returns. This is implemented as designed today as each platform doesn't offer a way of waiting for it to come back to your app.

Alright! Makes sense if not all platforms support waiting for it. Thanks.
