### ISSUE TITLE
Web Authenticator is not working in local development environment

### ISSUE THREAD

**Issue by spodugu** [xamarin/Essentials#1283]
### Description
I am unable to configure Web Authenticator to work on local development environment inside Android emulator

### Steps to Reproduce

1. In the Web API project, same AuthController is included similar to the demo. It is running on https://localhost:44311/api

2. To call the API from emulator, API url is referenced as https://10.0.2.2:43411/api

3. Now, I am able to call the API url in Xamarin forms using await  WebAuthenticator.AuthenticateAsync(apiUrl, callbackUrl)

4. But, when API tries to invoke Google authentication via await Request.HttpContext.ChallengeAsync(scheme);, below error is returned from Google.

Error 400: invalid_request, device-id and device-name are required for the private IP: https://10.0.2.2:4311/signin-google

5. As I understand, it is expecting request originated from the server instead of IP address like https://<servername>

6. Is there a seamless way to integrate the Google sign-in for the local Android development

**Comment by spodugu** [comment]
It is a feature request instead

**Comment by n6ither** [comment]
@spodugu did you manage to solve this?
