### ISSUE TITLE
[Enhancement] Support Multi-Window applications with Dispatcher pattern for MainThread

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#1284]
## Summary
Multi-Window applications apparently are incompatible with our static MainThread invocation approach. With Maui approaching, it would be nice if we could use as much Xamarin.Essentials code in Maui projects without such concers, as mentioned in the [Issue](https://github.com/dotnet/maui/issues/19)

## API Changes
Copy the forms dispatcher pattern
## Intended Use Case
Multiwindow applications which will approach with Maui

**Comment by jamesmontemagno** [comment]
Yup, this is on our map and having discussions here on moving this forward.

**Comment by mattleibow** [comment]
Closing this here as the new versions of Xamarin.Forms which will support multiple windows needs to support this. In fact, Essentials should probably never have added this API as there is no way to know which window the API is running on.

We will have to have a look if there is a way to even do this in the future. 

Imagine an app that has a background task that check connectivity or something. If it wants to pop a notification, then how is it supposed to know about the UI or where it is running?
