### ISSUE TITLE
Flashlight API: Object reference is not set [Bug] 

### ISSUE THREAD

**Issue by jbollman7** [xamarin/Essentials#1285]
### Description
Followed the guide and the video https://docs.microsoft.com/en-us/xamarin/essentials/flashlight?context=xamarin%2Fxamarin-forms&tabs=android 
### Steps to Reproduce

1. Use class file and assemblyinfo.cs file contents
2. Build to emulator
3. Display popups with relevant exception.

### Expected Behavior
Flashlight turns on
### Actual Behavior
My Errors (On emulators)
On Android: Object reference not set to an instance of an object. (tested on api version 23-28)
IOS: Specified method is not supported.
### Basic Information
`public class MainViewViewModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        public ICommand PowerButtonCommand { get; set;  }

        public MainViewViewModel()
        {
            PowerButton();
        }

       private void PowerButton()
        {
            PowerButtonCommand = new Command(async () =>
            {
                try
                {
                    await Flashlight.TurnOnAsync();
                }
                catch (FeatureNotSupportedException ex)
                {
                    await Application.Current.MainPage.DisplayAlert("Alert", $"Unable toggle flashlight: {ex.Message}", "OK");

                    // Handle not supported on device exception
                }
                catch (PermissionException ex)
                {
                    await Application.Current.MainPage.DisplayAlert("Alert", $"Unable toggle flashlight: {ex.Message}", "OK");
                    // Handle permission exception
                }
                catch (NullReferenceException ex)
                {
                    await Application.Current.MainPage.DisplayAlert("Alert", $"Unable toggle flashlight: {ex.Message}", "OK");
                }
                catch (Exception ex)
                {
                    await Application.Current.MainPage.DisplayAlert("Alert", $"Unable toggle flashlight: {ex.Message}", "OK");
                    // Unable to turn on/off flashlight
                    
                }
            });
        }
    }`
**AssemblyInfo.cs** file under the Properties folder and add:
`// Flash camera access
[assembly: UsesPermission(Android.Manifest.Permission.Flashlight)]
[assembly: UsesPermission(Android.Manifest.Permission.Camera)]
`
**AndroidManifest.cs** 
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.windrock.testblankflash">
	<uses-sdk android:minSdkVersion="20" />
	<uses-permission android:name="android.permission.FLASHLIGHT" />
	<uses-permission android:name="android.permission.CAMERA" />
	<application android:label="testblankflash"></application>
</manifest>`
On stable version
- IDE:
- Platform Target Frameworks: Stable channel
  - iOS 13.18.1.31
  - Android: 10.3.1.0
  VS for Mac 8.6.0

- Android Support Library Version: 
- Nuget Packages: Xamarin Forms, Xamarin.Essentials (stable for both)
- Affected Devices: Pixel 2 API 28. Pixel 3 API 29

**Comment by jamesmontemagno** [comment]
Flashlight is only supported on device, not on emulator at all as no light exists, however I will check the exception.

**Comment by jbollman7** [comment]
Closing issue. James, i do think you are correct. 
I finally got a physical device, the code ran flawlessly on the physical device, failed on the emulator.
