### ISSUE TITLE
Add Attachments to Email

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Essentials#129]
This needs to be investigated as there are some limitations and additional steps on each platform.

> VS bug [#735679](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735679)

**Comment by mfeingol** [comment]
This would be fantastic. I'm looking to replace platform-specific code in my app with Xamarin.Essentials, and this is very important functionality for me.

**Comment by transis2** [comment]
Here we have the implementation for iOS, Android, UWP and Tizen

https://github.com/cjlotz/Xamarin.Plugins/blob/master/Messaging/Plugin.Messaging.iOSUnified/EmailTask.cs

https://github.com/cjlotz/Xamarin.Plugins/blob/master/Messaging/Plugin.Messaging.Android/EmailTask.cs

https://github.com/cjlotz/Xamarin.Plugins/blob/master/Messaging/Plugin.Messaging.UWP/EmailTask.cs

https://github.com/cjlotz/Xamarin.Plugins/blob/master/Messaging/Plugin.Messaging.Tizen/EmailTask.cs

**Comment by mfeingol** [comment]
Will this ever be merged?

**Comment by jamesmontemagno** [comment]
@mfeingol we are actively working on locking down 1.0 apis and will be including more features after that. There is no full PR for this besides just are first investigation into the file provider.

**Comment by ephraimf** [comment]
Is an IEmailTask.cs file available?
I don't have a definition for the fields in the interface or for the interface itself.

**Comment by minaairsupport** [comment]
this important feature to include as soon as possible  , I can do it for you and make pull request if you will accept

**Comment by ephraimf** [comment]
Will there be support for multiple attachments?

**Comment by mattleibow** [comment]
@ephraimf Yes. There should be support for an arbitrary number of arbitrary files. Unless the platform specifically does not support it - but I haven't found that.

**Comment by robsoft** [comment]
Any likely eta on this, please? I need to get something into a demo in the next couple of days, trying to decide if I should just use Xam.Plugins.Messaging for the time being (and not sure what impact adding that might have on my Xamarin.Essentials stuff already in the app). If it was to drop in the next few days, I'd kick myself!

**Comment by amirvenus** [comment]
Would be nice to have it implemented as I am currently using DI for sending an email that has attachment(s).

**Comment by choirunnisa** [comment]
When can we expect to see th attachment functionality?

**Comment by ephraimf** [comment]
Thank you very much.

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '1.1.0' that is not in the list of supported values
