### ISSUE TITLE
[Bug] Cannot complete Google Authentication if Two-factor authentication is enabled on account

### ISSUE THREAD

**Issue by maxal1917** [xamarin/Essentials#1292]
### Description
When two factor authentication is enabled on Google Account, and same phone is used as second factor, as soon as password is entered on login screen, the process is interrupted by Android system popup to confirm that the attempt is legitimate. Unfortunately, as result the authentication is also interrupted with an exception "Task was cancelled".

Without two-factor authentication I can complete sign in process.

I was able to reproduce it in Sample app.

### Steps to Reproduce

1. Implement server side mobil-auth endpoint as it is demonstrated in Sample from Xamarin.Forms.Essentials.
2. authResult = await Xamarin.Essentials.WebAuthenticator.AuthenticateAsync(new Uri(_authEndpoint + schema),
                    new Uri("tennis-umpire://authentication-callback"));

### Expected Behavior
Authentication is completed

### Actual Behavior
Exception with "Task cancelled" message is thrown

### Basic Information

- Version with issue:
- Last known good version: None
- IDE: Visual Studio
- Platform Target Frameworks: 
  - Android: 10.x
- Android Support Library Version: Not Applicable
- Nuget Packages: None
![Screenshot_20200527-234059](https://user-images.githubusercontent.com/10283632/83096609-1c51e100-a074-11ea-9a1c-32bdeac8ddbb.png)
![Screenshot_20200527-234112](https://user-images.githubusercontent.com/10283632/83096611-1eb43b00-a074-11ea-8ae8-1bc8719ba616.png)

- Affected Devices: Tested on Google Pixel 3

**Comment by mattleibow** [comment]
Hmm, this is going to be very annoying. I'll have a look now and see.

**Comment by mattleibow** [comment]
I can't actually tests this... I need to figure out a way to sign out first - which is probably #1344

**Comment by maxal1917** [comment]
> I can't actually tests this... I need to figure out a way to sign out first - which is probably #1344

If you clear you browser cookies, it should ask you to sign in again.

**Comment by mattleibow** [comment]
I think I found the issue, I'll be trying it out. Seems that we need to use a intermediate activity or change how we launch the browser.

**Comment by DrMozze** [comment]
Hello,

Is it supposed to be solved in the current version of Xamarin.Essentials (1.6.1) ? I am still not able to do the whole auth process with 2AF. Google display the verification number behind the browser in which the auth process is being displayed. If I try to look at the Google popup, the authentication process is aborted with error.

Thank you !

**Comment by maxal1917** [comment]
> Hello,
> 
> Is it supposed to be solved in the current version of Xamarin.Essentials (1.6.1) ? I am still not able to do the whole auth process with 2AF. Google display the verification number behind the browser in which the auth process is being displayed. If I try to look at the Google popup, the authentication process is aborted with error.
> 
> Thank you !

2AF worked for me when I tried it, but then I had to rollback back to 1.5.3 because of the issue #1667 that was introduced in 1.6.x.

**Comment by DrMozze** [comment]
Thank you for your answer @maxal1917.

I will keep digging on my side, I don't understand why the auth process is not properly working with WebAuthenticator calling a backend web api which deal with social authentication...
