### ISSUE TITLE
[Bug] iOS: WebAuthenticator leaks on cancel

### ISSUE THREAD

**Issue by MKuckert** [xamarin/Essentials#1295]
### Description

The WebAuthenticator leaks the `ASWebAuthenticationSession` or `SFAuthenticationSession` on iOS if the login attempt is being cancelled.

### Steps to Reproduce

Steps for iOS 12+

1. Call `WebAuthenticator.AuthenticateAsync`
2. Cancel the opening authentication view controller
3. Examine the field `WebAuthenticator.was`. It's non-null and still holds the `ASWebAuthenticationSession`

### Expected Behavior

The session is disposed in all cases.

### Actual Behavior

The session is only disposed in the successful case. The session leaks for the cancelled or failing cases.

### Basic Information

- Version with issue: latest
- Last known good version: none (known to me)
- IDE: independent of any IDE
- Platform Target Frameworks: 
  - iOS:  13
- Nuget Packages: none. Reproducible with the sample app
- Affected Devices: every iOS device

### Reproduction Link

One can reproduce with the sample app.

**Comment by mattleibow** [comment]
This was fixed in #1296
