### ISSUE TITLE
[Bug] (iOS) WebAuthenticator.AuthenticateAsync: `Foundation.NSErrorException` cannot be explicitly caught in a try/catch block in .NET Standard library

### ISSUE THREAD

**Issue by brminnick** [xamarin/Essentials#1299]
### Description

On iOS, after calling `WebAuthenticator.AuthenticateAsync`, when the user cancels the authentication session a `Foundation.NSErrorException` is thrown. 

`Foundation.NSErrorException` is an iOS-specific API that can't be explicitly caught in a try/catch block in a .NET Standard project. 

### Recommendation

Create `public class AuthenticationException : Exception` that can be referenced from a .NET Standard project.

**Implement `AuthenticationException`**

```csharp
public class AuthenticationException : Exception
{
    public AuthenticationException(Exception exception) : base("Authentication Failed", exception)
    {
    }
}
```

**Throw `AuthenticationException`**
_From [Xamarin.Essentials.WebAuthenticator.ios.tvos.cs ](https://github.com/xamarin/Essentials/blob/4de77262db9d98092f4643a32a970e48530518e6/Xamarin.Essentials/WebAuthenticator/WebAuthenticator.ios.tvos.cs#L110-L113) source code_

```csharp
catch (Exception ex)
{
    tcsResponse.TrySetException(new AuthenticationException(ex));
}
```

### Workaround

Here's an example of how to catch this exception in a .NET Standard project:
https://github.com/brminnick/GitTrends/blob/cc1f1bdb141beb3e3f6193b96ae36cca23783f4c/GitTrends/ViewModels/Base/GitHubAuthenticationViewModel.cs#L94-L97

```csharp
try
{
    var authResult = await WebAuthenticator.AuthenticateAsync(new Uri("https://github.com/login/oauth/authorize?client_id=9b010a6d0dfb3354fdb5&scope=public_repo%20read:user"), new Uri(OAuthConstants.CallbackUrl));
}
catch (Exception e) when (e.GetType().FullName.Contains("NSErrorException"))
{
    //On iOS, Foundation.NSErrorException is thrown by Xamarin.Essentials if the user clicks 'X' on the browser to return to the app
}
```

### Steps to Reproduce

1. Download/Clone this repo: https://github.com/brminnick/WebAuthenticatorRepro/
2. In Visual Studio, open `WebAuthenticatorRepro.sln`
3. In Visual Studio, set the startup project to WebAuthenticator.iOS
4. In Visual Studio, build/deploy WebAuthenticator.iOS to an iOS Device/Simulator 
5. On the iOS device, click `Connect to GitHub`
6. On the iOS device, on the popup, click cancel
7. Confirm WebAuthenticator.iOS crashes with `Foundation.NSErrorException`

### Expected Behavior

To aid cross-platform solutions, Xamarin.Essentials should throw an `Exception` that can be explicitly caught in a try/catch block in a .NET Standard project, like so:

```csharp
try
{
    var authResult = await WebAuthenticator.AuthenticateAsync(new Uri("https://github.com/login/oauth/authorize?client_id=9b010a6d0dfb3354fdb5&scope=public_repo%20read:user"), new Uri(OAuthConstants.CallbackUrl));
}
catch (WebAuthenticatorException e)
{
  // ...
}
```

### Actual Behavior

Because `Foundation.NSErrorException` cannot be referenced in a .NET Standard project, we must use reflection and a hard-coded string to explicitly catch the exception:

```csharp
try
{
    var authResult = await WebAuthenticator.AuthenticateAsync(new Uri("https://github.com/login/oauth/authorize?client_id=9b010a6d0dfb3354fdb5&scope=public_repo%20read:user"), new Uri(OAuthConstants.CallbackUrl));
}
catch (Exception e) when (e.GetType().FullName.Contains("NSErrorException"))
{
    //On iOS, Foundation.NSErrorException is thrown by Xamarin.Essentials if the user clicks 'X' on the browser to return to the app
}
```

### Basic Information

- Version with issue: v1.5.3.2
- Last known good version: Unknown
- Platform Target Frameworks: 
- iOS:  13.20.0.22

### Screenshots

![](https://user-images.githubusercontent.com/13558917/83820592-f20aaf80-a681-11ea-9902-58bf4c2bc8cc.gif)

### Reproduction Link

https://github.com/brminnick/WebAuthenticatorRepro/

**Comment by mattleibow** [comment]
Fixed in #1507
