### ISSUE TITLE
FileProvider for Android

### ISSUE THREAD

**Issue by Redth** [xamarin/Essentials#130]
Doing things like attaching files to emails and sharing files with DataTransfer is difficult on android since one must get a URI from a file provider in newer versions of android.

We should add some functionality to help get a proper URI from an existing filename the developer passes to us which we then transfer into a file provider friendly filename.

# What's needed

## XML Resource

You must specify the paths you intend to use in an xml resource file.  Most users would want to use one or both of these paths:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<paths>
  <external-path path "caboodle" name="caboodle/" />

  <!-- NOT NEEDED: -->
  <!-- <external-path path="Android/data/com.some.package/" name="files_root" /> -->
  <!-- <external-path path="." name="external_storage_root" /> -->
</paths>
```

**EDIT:** We probably only need to do something like `<external-path path "caboodle" name="caboodle" />` or similar... We don't need external storage and we don't need the package name in the path it appears.. so this is good.

We can just add this as a resource in the library itself.

## Provider declaration in AndroidManifest.xml

The AndroidManifest.xml file needs this declared:
```xml
<provider
  android:name="android.support.v4.content.FileProvider" 
  android:authorities="${applicationId}.fileProvider"
  android:grantUriPermissions="true"
  android:exported="false">
    <meta-data 
      android:name="android.support.FILE_PROVIDER_PATHS"
      android:resource="@xml/file_paths" />
</provider>
```

I don't believe we can accomplish this currently with C# attributes (there doesn't seem to be an `[assembly: Provider(..)]` attribute.

Also note the `@xml/file_paths` resource name needs to be known for this declaration.

We could get the user to add this manually (again, not nice). Or we can use a custom build task.

## Content URI
Finally we get the actual content uri:

```csharp
var contentUri = Android.Support.V4.Content.FileProvider.GetUriForFile(context, "com.some.package", new Java.IO.File(filename));
```

We can use this uri for things like starting an intent chooser:

```csharp
var intent = new Android.Content.Intent(Android.Content.Intent.ActionSend);
intent.PutExtra(Android.Content.Intent.ExtraStream, contentUri);
intent.SetFlags(Android.Content.ActivityFlags.GrantReadUriPermission);

var intentChooser = Android.Content.Intent.CreateChooser(intent, "Title");

context.StartActivity(intentChooser);
```

> VS bug [#732192](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732192)

**Comment by jamesmontemagno** [comment]
This is what I currently have to document in Media Plugin:

Android File Provider Setup
You must also add a few additional configuration files to adhere to the new strict mode:

1.) Add the following to your AndroidManifest.xml inside the <application> tags:
```
<provider android:name="android.support.v4.content.FileProvider" 
          android:authorities="${applicationId}.fileprovider" 
          android:exported="false" 
          android:grantUriPermissions="true">
          
	  <meta-data android:name="android.support.FILE_PROVIDER_PATHS" 
                     android:resource="@xml/file_paths"></meta-data>
</provider>
2.) Add a new folder called xml into your Resources folder and add a new XML file called file_paths.xml
```
Add the following code:
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-files-path name="my_images" path="Pictures" />
    <external-files-path name="my_movies" path="Movies" />
</paths>
```

My thoughts here are that we will have to include this in the documentation, add them to the templates, and maybe add them to a readme.txt pop up..

**Comment by mattleibow** [comment]
We can cheat a bit by creating a custom file provider class and adding the [Provider] attribute. This is what PhoneGap does I think - they have a custom provider that just inherits from FileProvider.

**Comment by Redth** [comment]
So conceivable we could maybe cheat with:

```csharp
[ContentProvider(
    new[] { "${applicationId}.fileProvider" },
    Name = "android.support.v4.FileProvider",
    Exported = false,
    GrantUriPermissions = true)]
[MetaData(
    "android.support.FILE_PROVIDER_PATHS",
    Resource = "@xml/caboodle_file_paths")]
public class CustomProvider : Android.Support.V4.Content.FileProvider
{
}
```

**Comment by Redth** [comment]
^ This may not be totally correct, we need our own name essentially and can probably drop metadata since we can look that up ourselves...

**Comment by Redth** [comment]
So I think we can do this without a custom build task then.  We can probably make it as simple as a `Platform.GetUriForFile(string filename)` method.

**Comment by softlion** [comment]
Hi,
just tryed that in an android library and it works fine!

```csharp
[ContentProvider(new[] { "vapolia.mvvmcross.picturepicker.fileProvider" }, Exported = false, GrantUriPermissions = true)]
[MetaData("android.support.FILE_PROVIDER_PATHS", Resource = "@xml/vapolia_picturepicker_paths")]
public class VapoliaPicturePickerFileProvider : FileProvider
{
}
```

The resource in the android library:
```xml
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <external-files-path name="my_images" path="Pictures" />
  <external-files-path name="my_movies" path="Movies" />
</paths>
```

**Comment by piolo94** [comment]
I want to share something that blocked us for days:  the fileprovider code must be inserted between the application tags and not after it. It may be trivial, but it's never specified, and I thought that I could have helped someone!

**Comment by Pippiuz** [comment]
Grazie @piolo94!! E' stato utilissimo. Quel problema ha bloccato anche noi per giorni.

**Comment by piolo94** [comment]
I am glad I was able to help!! :)

**Comment by Mrnikbobjeff** [comment]
I would like to see this getting integrated. #129  also seems to depend on solving this. I tried to follow @softlion 's instructions but did not get it to work. Once this is done several other file related api's could follow suit and be integrated.

**Comment by softlion** [comment]
> but did not get it to work

It's working fine though. Maybe you missed something ?

**Comment by Redth** [comment]
Many other features/api's will depend on this which is why we want to get this right.  We are going to be looking at this as one of the first things after a 1.0 release.

**Comment by mattleibow** [comment]
We need to get this reviewed as we have several features waiting on this.

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '1.1.0' that is not in the list of supported values

**Comment by itrice** [comment]
1、动态申请权限
    ```

protected override void OnResume()
 {
        base.OnResume();
        #region 权限请求
        if (ActivityCompat.CheckSelfPermission(this, Manifest.Permission.WriteExternalStorage) != Permission.Granted)
        {
            ActivityCompat.RequestPermissions(this, new[] { Manifest.Permission.ReadExternalStorage, Manifest.Permission.WriteExternalStorage },0);
        }
        #endregion
    }
```
2、路径地址：/storage/emulated/0/
3、viewer显示
 		```
var rs = System.IO.File.Exists(filepath);
        if (rs)
        {
            var context = Android.App.Application.Context;
            var file = new Java.IO.File(filepath);

            //var uri = FileProvider.GetUriForFile(context, "com.jzxy.duoke.provider", new Java.IO.File(filepath));
            //var uri = FileProvider.GetUriForFile(MainActivity.AppContext, MainActivity.AppContext.PackageName+ ".provider", new Java.IO.File(filepath));
            var uri = Android.Net.Uri.FromFile(file);
            try
            {
                var intent = new Intent(Intent.ActionView);
                intent.AddCategory(Intent.CategoryDefault);
                intent.SetFlags(ActivityFlags.GrantReadUriPermission);
                intent.SetFlags(ActivityFlags.ClearWhenTaskReset | ActivityFlags.NewTask);
                intent.SetDataAndType(uri, mimeType);
                Forms.Context.StartActivity(Intent.CreateChooser(intent, "选择打开的程序"));
            }
            catch (Exception e)
            {
                Toast.MakeText(context, e.Message, ToastLength.Long).Show();
            }
        }
```
