### ISSUE TITLE
Is this plugin supports for Visual studio 2019 Xamarin Projects

### ISSUE THREAD

**Issue by ShaileshBhatNP** [xamarin/Essentials#1300]
## Summary
Is this plugin supports for Visual studio 2019 Xamarin Projects?

Hi, I need to build an Xamarin app using VS2019 and this plugin. Is it possible?. I was confused, after searching for a day..If yes, **Can I get the sample in VS2019**..I have tried with many samples, but no one is supporting/running in VS2019

**Comment by davehump** [comment]
@ShaileshBhatNP  You should have no problem running and compiling Essentials in Visual studio 2019 as long as you are on 16.3(Windows) ior 8.3(mac) or above.

What platform are you having issues with and what is the problem you are experiencing?

**Comment by VladislavAntonyuk** [comment]
default Xamarin.Forms template includes Xamarin.Essentials.

**Comment by jamesmontemagno** [comment]
Absolutely, checkout the full getting started docs: https://docs.microsoft.com/xamarin/essentials Like others have said they are also included with the templates.
