### ISSUE TITLE
[Bug] Android Email with Outlook App not sending email until you reopen Outlook

### ISSUE THREAD

**Issue by IainS1986** [xamarin/Essentials#1302]
### Description
When sending an email using the ComposeAsync call (with attachments), if I send via the Outlook app - upon pressing send in Outlook the Outlook app instantly closes back to my app but the email is not sent.

If I try to switch to the outlook app via task switching it just says "App isn't available" but if I open the Outlook app via app launcher, I then see a toast appear for 'Email sent' and the email arrives.

GMail app however works fine. I can switch to the app after sending fine and the email is sent as my app returns to foreground.

### Steps to Reproduce

1. Ensure Outlook app installed
2. Call ComposeAsync with attachements
3. Pick Outlook as the app you want to send the email with
4. Hit send
5. Notice your app is shown instantly
6. Notice no email will arrive
7. Try to switch to the Outlook app. Notice you can't
8. Open Outlook app via launcher and see Sent toast appear

### Expected Behavior
Email should be sent before closing

### Actual Behavior
Email not sent before app context switches back immediately.

### Basic Information

- Version with issue: 1.5.3.2
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - Android: 9.0 (28)

Completely understand this is likely an Outlook app issue as Gmail works fine. Just wondered if this was a known issue, or others had seen the same, or if it is in fact something wrong with the Intent launching.

**Comment by IainS1986** [comment]
Some more information. What i'm actually doing is attempting to port over an existing app (in Xamarin) to a newer setup. That app also has its own email attachments usage and it seems to work fine with Outlook app. I'm using Xamarin essentials in the new app.

Differences I can see from a UI/UX pov...

1 - Previous app animates to and from current app to Outlook app as expected (left/right transition). My app with Xamarin essentials just 'pops' from one app to the other with no animation.
2 - Previous app, on returning from Outlook, I can switch to outlook app fine. My app with Xamarin essentials fails in switching back saying App is Unavailable (I assume its died)
3 - Previous app, email arrives fine. New app I have to reload Outlook

It feels like Outlook is dying before it sends in Xamarin essentials.

Fishing around the previous code (its a bit of a mess), I can see it builds the email as such (some lines ommited)...

`var email = new Intent(Android.Content.Intent.ActionSendMultiple);
 email.PutExtra(Android.Content.Intent.ExtraEmail, new string[] { EMAILADDRESS });
email.SetType("message/rfc822");    // email type!
var uris = new List<IParcelable>();
email.PutParcelableArrayListExtra(Intent.ExtraStream, uris);
email.SetFlags(ActivityFlags.GrantReadUriPermission);
StartActivity(Intent.CreateChooser(email, "Send support email ..."))`

**Comment by IainS1986** [comment]
Only difference I can see looking through Essentials code compared to this apps original code is simply that the Intent is set to ActivityFlags.ClearTop | ActivityFlags.NewTask and ActivityFlags.LaunchAdjacent on api 24+

**Comment by IainS1986** [comment]
Investigated a bit more, copied over the code for Android Email (essentials) into my project to mess around.

I seem to have it working nicely with Outlook now, animating to and from the app and the email sending fine, but I had to make the following changes to get something working nicely...

1 - Removed *all* the flags on the intent (not great I know)
2 - Then launched via CrossCurrentActivity plugin instead of Application.Context. 

'    CrossCurrentActivity.Current.Activity.StartActivity(intent);'

**Comment by mattleibow** [comment]
I tested this with 1.6 and emails with attachments send using Outlook the first time. Maybe it was a bug in a previous version that cause this?
