### ISSUE TITLE
[Enhancement] Push notifications permission

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Essentials#1305]
## Summary
Add the possibility to check push notifications permission. 

## API Changes
```
var status = await Permissions.CheckStatusAsync<Permissions.PushNotifications>();
```

Of course, you cannot request push notifications permission from the app (enabling/disabling push notifications can be only done from settings), so this will be just read-only permission. Thus you cannot write this:

```
var status = await Permissions.RequestAsync<Permissions.PushNotifications>();
```

This should throw an exception.

## Intended Use Case
I want to check if the user granted permission for push notifications in my Android/iOS app.

**Comment by softlion** [comment]
Is there any specific difficulty to add this permission I should know about before creating a PR ?

**Comment by Muhammadfaizann** [comment]
How can I ask for permission in Xamarin if the notification permission is disabled?
