### ISSUE TITLE
[Enhancement] Remove 64KB limit to Launcher API

### ISSUE THREAD

**Issue by bobwhitten** [xamarin/Essentials#1308]
## Summary
Launcher can open an app passing a "uri" string.  At least for iOS, in a native app this string can be aribtrarily long (at least 10MB).   But, the Xamarin.Essentials code is limited to about 64KB, apparently due to using the .NET URI Class.

## API Changes
None

## Intended Use Case
While often a URI is limited to 2KB (e.g., as an HTTP request), increasingly this is used for other things, and the 64KB limitation will prevent some of these.

**Comment by Mrnikbobjeff** [comment]
I do not think this is feasable as the [uri docs](https://docs.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=netcore-3.1#System_Uri__ctor_System_String_) explicitely state a length limit of 65519 characters.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
