### ISSUE TITLE
[Bug] SetTextAsync when text is long numeric text and paste text value is　Scientific notation

### ISSUE THREAD

**Issue by Jockeyvb** [xamarin/Essentials#1309]
### Description
 Clipboard.SetTextAsync('21054546132568633666941323655866565')

paste text value is  2.10545461325686E+34
### Basic Information
Xamarin.Essentials v1.5.3.2
- Version with issue: 
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:12.4.4  
  - Android:  v8.1  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:Xamarin.Essentials v1.5.3.2
- Affected Devices:

**Comment by jamesmontemagno** [comment]
Are you seeing this on both iOS and Android? or just one platform?

**Comment by Jockeyvb** [comment]
@jamesmontemagno 
ios and Android then same.
 #I don't think there is anything we can do because we are setting a string. Are you converting data back and forth?

yes ,copy a string ,and paste result is numeric type.

**Comment by jamesmontemagno** [comment]
Can you please share your code that you are using so we can try to duplicate it?

**Comment by Jockeyvb** [comment]
sure 

`        public static void ClipboardCopy(string sInfo)
        {
            
            Clipboard.SetTextAsync(sInfo);
    }
`
and call : ClipboardCopy("2020050122001409081445886845")

on iphone or android  paste result is : 2.02005012200141E+27

**Comment by jamesmontemagno** [comment]
Was unable to reproduce this. Worked fine for me here....

![image](https://user-images.githubusercontent.com/1676321/85760984-314b7f80-b6c7-11ea-8bb1-ddd26f64d1d0.png)
![image](https://user-images.githubusercontent.com/1676321/85761047-3f999b80-b6c7-11ea-9dce-90be6b997fc6.png)
![image](https://user-images.githubusercontent.com/1676321/85761080-47f1d680-b6c7-11ea-87f7-550d628aeb27.png)
[App42.zip](https://github.com/xamarin/Essentials/files/4832657/App42.zip)

**Comment by Jockeyvb** [comment]
OH,I am found point 

use using System.Reflection; 

and try can  convert string to numeric first  

so code bug not plusin bug. thank you
