### ISSUE TITLE
Error while build app

### ISSUE THREAD

**Issue by Monikaprime** [xamarin/Essentials#1310]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT2001: Could not link assemblies.
2>  	Type: `Xamarin.Essentials.AuthManager`
2>  	Assembly: `Xamarin.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`
2>  Reason: Value cannot be null.
2>  Parameter name: key

but not using xamarin.essentials.authmanager

**Comment by Monikaprime** [comment]
error MT2001: Could not link assemblies.
2>  	Type: `Xamarin.Essentials.AuthManager`
2>  	Assembly: `Xamarin.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`
2>  Reason: Value cannot be null.
2>  Parameter name: key
2>  --- inner exception
2>  System.ArgumentNullException: Value cannot be null.
2>  Parameter name: key
2>    at System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) [0x00008] in <98fac219bd4e453693d76fda7bd96ab0>:0 
2>    at System.Collections.Generic.Dictionary`2[TKey,TValue].TryGetValue (TKey key, TValue& value) [0x00000] in <98fac219bd4e453693d76fda7bd96ab0>:0 
2>    at Xamarin.Tuner.DerivedLinkContext.GetCustomAttributes (Mono.Cecil.ICustomAttributeProvider provider, System.String storage_name) [0x00017] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/DerivedLinkContext.cs:89 
2>    at Xamarin.Tuner.DerivedLinkContext.GetCustomAttributes (Mono.Cecil.ICustomAttributeProvider provider, System.String namespace, System.String name) [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/DerivedLinkContext.cs:120 
2>    at Xamarin.Linker.MobileExtensions.HasCustomAttribute (Mono.Cecil.ICustomAttributeProvider provider, Xamarin.Tuner.DerivedLinkContext context, System.String namespace, System.String name) [0x00017] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/MobileExtensions.cs:32 
2>    at Xamarin.Linker.Steps.CoreMarkStep.MarkInterfaceImplementation (Mono.Cecil.TypeDefinition type, Mono.Cecil.InterfaceImplementation iface) [0x0001a] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/CoreMarkStep.cs:294 
2>    at Mono.Linker.Steps.MarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x0015e] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs:907 
2>    at Xamarin.Linker.Steps.MobileMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/MobileMarkStep.cs:71 
2>    at Xamarin.Linker.Steps.CoreMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00090] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/CoreMarkStep.cs:172 
2>    at MonoTouch.Tuner.MonoTouchMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/MonoTouch.Tuner/MonoTouchMarkStep.cs:84 
2>    at Mono.Linker.Steps.MarkStep.InitializeType (Mono.Cecil.TypeDefinition type) [0x0005b] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs:104 
2>    at Mono.Linker.Steps.MarkStep.InitializeAssembly (Mono.Cecil.AssemblyDefinition assembly) [0x00034] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs:88 
2>    at Mono.Linker.Steps.MarkStep.Initialize () [0x00016] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs:78 
2>    at Mono.Linker.Steps.MarkStep.Process (Mono.Linker.LinkContext context) [0x00008] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker.Steps/MarkStep.cs:71 
2>    at Xamarin.Linker.Steps.MobileMarkStep.Process (Mono.Linker.LinkContext context) [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/MobileMarkStep.cs:33 
2>    at Xamarin.Linker.Steps.CoreMarkStep.Process (Mono.Linker.LinkContext context) [0x00017] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/CoreMarkStep.cs:32 
2>    at MonoTouch.Tuner.MonoTouchMarkStep.Process (Mono.Linker.LinkContext context) [0x0001d] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/linker/MonoTouch.Tuner/MonoTouchMarkStep.cs:36 
2>    at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) [0x0001f] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/external/linker/linker/Linker/Pipeline.cs:127 
2>    at MonoTouch.Tuner.Linker.Process (MonoTouch.Tuner.LinkerOptions options, MonoTouch.Tuner.MonoTouchLinkContext& context, System.Collections.Generic.List`1[Mono.Cecil.AssemblyDefinition]& assemblies) [0x000e0] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Tuning.cs:80 
2>  ---
2>    at MonoTouch.Tuner.Linker.Process (MonoTouch.Tuner.LinkerOptions options, MonoTouch.Tuner.MonoTouchLinkContext& context, System.Collections.Generic.List`1[Mono.Cecil.AssemblyDefinition]& assemblies) [0x003ad] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Tuning.cs:122 
2>    at Xamarin.Bundler.Target.LinkAssemblies (System.Collections.Generic.List`1[Mono.Cecil.AssemblyDefinition]& assemblies, System.String output_dir, System.Collections.Generic.IEnumerable`1[T] sharedCodeTargets) [0x00256] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Target.cs:522 
2>    at Xamarin.Bundler.Target.ManagedLink () [0x00720] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Target.cs:669 
2>    at Xamarin.Bundler.Target.ProcessAssemblies () [0x000c2] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Target.cs:873 
2>    at Xamarin.Bundler.Application.ProcessAssemblies () [0x0002f] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:1411 
2>    at Xamarin.Bundler.Application.BuildManaged () [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:839 
2>    at Xamarin.Bundler.Application+<>c.<BuildAll>b__140_1 (Xamarin.Bundler.Application v) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:787 
2>    at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x0001e] in <98fac219bd4e453693d76fda7bd96ab0>:0 
2>    at Xamarin.Bundler.Application.BuildAll () [0x00050] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:787 
2>    at Xamarin.Bundler.Driver.Main2 (System.String[] args) [0x00423] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/mtouch.cs:1402 
2>    at Xamarin.Bundler.Driver.Main (System.String[] args) [0x00015] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/mtouch.cs:934

**Comment by jamesmontemagno** [comment]
Looks like you are using Visual Studio 2017? Can you tell me what specific version you are using?

Also what version of Xamarin.Essentials?

**Comment by Monikaprime** [comment]
done installed latest xcode and done from visual studio 2019 issue got resolved
