### ISSUE TITLE
[Question] Is there a way to force display of login screen (ignore cached ids)

### ISSUE THREAD

**Issue by solomonfried** [xamarin/Essentials#1311]
## Summary
I am using WebAuthenticator and once a user authenticates with a provider (Google or Facebook or Apple) the call to authenticate does not present the login screen but returns the previous connected auth information without displaying any login screen. So if a user want to logon with an alternate gmail address, they cannot. 

Is there a way to force the display of the logon page so that they can connect with a secondary id?

**Comment by rj-thomas** [comment]
We really need this function as well.  Some of our customers have multi-person devices and we need to be able to clear the local cookie/token that the WebAuthenticator is holding onto, especially if they choose 'Remember Me' with MS login. Currently can not find anyway of doing this which is quite limiting.

**Comment by Bibz87-CG** [comment]
We need this functionality, too.

**Comment by berhir** [comment]
most providers like Google, Facebook, Microsoft, etc. are using OpenId Connect.
you can pass the `prompt=login` parameter to force showing the login screen again.
see the [OpenId Connect documentation](https://openid.net/specs/openid-connect-core-1_0.html) for details. be aware that not all providers are offering all features of OIDC. you must check the provider documentation too.

**Comment by solomonfried** [comment]
@berhir 
Where would a developer add prompt=login using WebAuthenticator or on the server Request.HttpContext.AuthenticateAsync

Thx

**Comment by berhir** [comment]
@solomonfried as I wrote before, there are differences between providers.
If you want to force showing the login page for google, you can try it this way:
```cs
[HttpGet("{scheme}")]
public async Task Get([FromRoute] string scheme)
{
    ....
    if (scheme == GoogleDefaults.AuthenticationScheme)
    {
        // Google supports none, consent and select_account
        // https://developers.google.com/identity/protocols/oauth2/openid-connect#authenticationuriparameters
        await HttpContext.ChallengeAsync(scheme, new GoogleChallengeProperties { Prompt = "consent" }); 
    }
    ....
}
```

This code was not tested, please try and let me know if it works.

**Comment by solomonfried** [comment]
Thank you.

Just changed "consent" to "select_account" and it worked!!! 

From the google documentation [https://developers.google.com/identity/protocols/oauth2/openid-connect#authenticationuriparameters](https://developers.google.com/identity/protocols/oauth2/openid-connect#authenticationuriparameters)

- select_account
  The authorization server prompts the user to select a user account. This allows a user who has multiple accounts at the authorization server to select amongst the multiple accounts that they may have current sessions for.

**Comment by solomonfried** [comment]
Thanks to @berhir for the solution.
