### ISSUE TITLE
[Bug] NRE thrown in VS2019 preview

### ISSUE THREAD

**Issue by nodoid** [xamarin/Essentials#1312]
### Description
VS2019 fails to show design due to NRE being thrown from Xam.Essentials (only tested on android)

### Steps to Reproduce
1.  Create a XAML page - something as simple as a webview
2. In the code behind, reference a view model that has refs GetVersionString
3. 

### Expected Behavior
UI shows
### Actual Behavior
NRE thrown

[2020-06-18 11:36:16.6] ERROR: : The renderer encountered an error while rendering this file: System.NullReferenceException: Object reference not set to an instance of an object
Xamarin.Essentials.AppInfo.PlatformGetVersionString () in d:\a\1\s\Xamarin.Essentials\AppInfo\AppInfo.android.cs:26
Xamarin.Essentials.AppInfo.get_VersionString () in d:\a\1\s\Xamarin.Essentials\AppInfo\AppInfo.shared.cs:11
CorpServ.ProviderApp.App..ctor ()
<unknown method>
System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) in D:\j\workspace\archive-mono\2020-02\android\release\mcs\class\corlib\System.Reflection\RuntimeMethodInfo.cs:936

[2020-06-18 11:36:16.6] ERROR: : AndroidXamlRenderer had a rendering error: System.NullReferenceException: Object reference not set to an instance of an object
Xamarin.Essentials.AppInfo.PlatformGetVersionString () in d:\a\1\s\Xamarin.Essentials\AppInfo\AppInfo.android.cs:26
Xamarin.Essentials.AppInfo.get_VersionString () in d:\a\1\s\Xamarin.Essentials\AppInfo\AppInfo.shared.cs:11
CorpServ.ProviderApp.App..ctor ()
<unknown method>
System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) in D:\j\workspace\archive-mono\2020-02\android\release\mcs\class\corlib\System.Reflection\RuntimeMethodInfo.cs:936

### Basic Information

- Version with issue: 1.5.3.2
- IDE: VS2019 - 16.6.2
- Platform Target Frameworks: Android
  - iOS:  11
  - Android: 10
- Android Support Library Version: AndroidX

**Comment by nodoid** [comment]
16.6.2 is not preview - it's release ;)

**Comment by jamesmontemagno** [comment]
Are you saying in the Xamarin.Forms Previewer? 

You will want to check if the design mode is running and not run platform code: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/?pivots=macos#detect-design-mode

**Comment by jamesmontemagno** [comment]
Closing as work around is listed above^
