### ISSUE TITLE
Allow to share URL with preset meta data

### ISSUE THREAD

**Issue by albert-pun** [xamarin/Essentials#1316]
## Summary
Allow to share URL using Essential Share API with preset meta data instead of fetching from web, such as Icon and Title, to provide better user experience and minimize traffic delay.

## API Changes
Add a new MetaData member into ShareTestRequest class to store user defined meta data, such as
MetaData ShareTextRequest.MetaData
```
class MetaData
{
    string ShortcutIcon {get; set;}
    string Title {get; set;}
    string ShortcutIconType {get; set;}
...
}
```
e.g.

To define meta data for Share, user create a ShareTextRequest and add new meta data into it before calling Share.RquestAsync.

    public async Task ShareUri(string uri)
    {
        var testRequest = new ShareTextRequest
            {
                Uri = uri,
                Title = "Share Web Link"
            });
        // new start
        testRequest .MetaData.Add(@"https://c.s-microsoft.com/favicon.ico?v2","image/x-icon");
        testRequest .MetaData.Add("Microsoft - Official Home Page");
       // new end

        await Share.RequestAsync(textRequest);
    }

**Comment by mattleibow** [comment]
Do the native platform APIs support arbitrary metadata?

**Comment by albert-pun** [comment]
> Do the native platform APIs support arbitrary metadata?

I believe so https://developer.apple.com/wwdc19/262

**Comment by AlexanderMelchers** [comment]
I'd also really like to have the ability to set a custom title on iOS. Or, put differently, I'd also like iOS to use the title I'm setting for use by the other platforms.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
