### ISSUE TITLE
[Enhancement] Support title in share dialog on iOS

### ISSUE THREAD

**Issue by AlexanderMelchers** [xamarin/Essentials#1317]
## Summary
Currently the title of the share dialog can be set on both Android and UWP, but is ignored on iOS ([as per documentation](https://docs.microsoft.com/en-us/xamarin/essentials/share?tabs=uwp#platform-differences)). It'd be great if we could also set the title on iOS, either through the same or through a different property on the sharing-classes.

## API Changes

In it's simplest implementation does not require an API-change, as the `Title`-property is already available in both `ShareTextRequest` and `ShareFileRequest`. It would just need to actually be used on iOS.

Since normal behaviour on iOS seems to be to load the title attributes of the sharing-dialog from the passed URI, API-changes might be needed to indicate the requested title-behaviour. One could envision something like:

```
await Share.RequestAsync(new ShareTextRequest
{
	Uri = uri,
	Title = "Share Web Link",
	AutoLoadTitleInfo = false
});
```

Where:

1. `AutoLoadTitleInfo = true` by default.
2. `AutoLoadTitleInfo == true` maintains the current behaviour of allowing iOS to load title-data from the URI by itself (even if `Title` is set).
3. `AutoLoadTitleInfo == false` would allow us to override the title-data using our custom title.

Alternatively, and may be more readable: 

```
await Share.RequestAsync(new ShareTextRequest
{
	[...]
	TitleInfo = AutoLoad | Custom
});
```

(i.e. turn it into an `enum`-flag with the values indicating the desired behaviour - `AutoLoad` being default again)

## Intended Use Case
Right now we're using the URI-sharing feature in Essentials to share a URI with an accompanying message. On Android we're moreover setting an additional title to describe what will be shared. However, on iOS only the app's icon shows up. We'd like to specify our own text as the dialog title.

**Comment by AlexanderMelchers** [comment]
Seems related to #1316.

**Comment by Syed-Esqimo** [comment]
Upvoted!!!

**Comment by irinakush** [comment]
Upvoted

**Comment by jfversluis** [comment]
I think this is implemented now!
