### ISSUE TITLE
[Bug] ShareFileRequest 'Title' Not Working Android

### ISSUE THREAD

**Issue by brsusta** [xamarin/Essentials#1320]
### Description
Cross Platfrom Android ShareFileRequest 'Title' Not Working 

Image successful

            var img = "xx.png";
            var file = Path.Combine(FileSystem.CacheDirectory, img);

            byte[] imgb= null;
            imgb= (byte[])(DT.Rows[0]["Image"]);

            File.WriteAllBytes(file, imgb);
            var title = "Share";

            await Share.RequestAsync(new ShareFileRequest
            {
               
                File = new ShareFile(file),
                Title = title.ToString()
            });
Basic Information
Version with issue: 1.5.3.2
 Last known good version: None
 IDE: Visual Studio 2019 Platform
 Target Frameworks: 
Android:9.0

**Comment by jamesmontemagno** [comment]
Where do you expect it to be? This is set in the intent chooser https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/Share/Share.android.cs#L54
