### ISSUE TITLE
[Bug] Clipboard.HasText always appears to return true

### ISSUE THREAD

**Issue by gceaser** [xamarin/Essentials#1321]
### Description
When running a UWP Xamarin forms projects, the Clipboard.HasText property always returns true. 
### Steps to Reproduce

1. Implement Clipboard.HasText in your project
2. set a break point in your code on the line that checks the Clipboard.HasText property
3. run the application and hit the breakpoint in step 2.
4. before evaluating the Clipboard.HasText property, open a command window and clear the clipboard using the following command:  
echo off | clip
5. verify the clipboard is empty by opening notepad and pressing ctrl+v.  Nothing should be pasted into the notepad document as the clipboard is empty.
6.  Execute the line of code the evaluates the Clipboard.HasText property and it will still return true.

### Expected Behavior
the Clipboard.HasText property should return false.
### Actual Behavior
the Clipboard.HasText property always returns true.
### Basic Information

- Version with issue: 1.5.3.2
- Last known good version:
- IDE: Visual Studio 2019 Pro on Windows
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by erdugen** [comment]
The same problem exists in the Xamarin Forms Android project.

**Comment by mattleibow** [comment]
When accessing the text, what is the result?

When we process this property, we are basically just asking Windows directly: `WindowsClipboard.GetContent().Contains(StandardDataFormats.Text);`

**Comment by jamesmontemagno** [comment]
I don't think that echo off | clip fully clears out the clipboard on Windows 10.

If you go into settings and type in clipboard you can clear it there:
![image](https://user-images.githubusercontent.com/1676321/98322620-be1f1780-1f9c-11eb-863e-d8e0440568bb.png)

I think on Android we are checking the primary clip which is correct, but that doesn't mean that android has text. https://stackoverflow.com/questions/31610165/getprimaryclip-returns-clipdata-text-plain-null 

we could just grab the text and check against null @mattleibow
