### ISSUE TITLE
[Bug] iOS Crash in Permissions.LocationWhenInUse on WiFi iPhone XR

### ISSUE THREAD

**Issue by teamtam** [xamarin/Essentials#1325]
### Description

I'm experience a crash using Xamarin.Essentials 1.5.3.2 with `Permissions.RequestAsync<Permissions.LocationWhenInUse>()`. This has been forked from https://github.com/xamarin/Essentials/issues/1238.

`System.NullReferenceException: Object reference not set to an instance of an object at Xamarin.Essentials.Permissions+LocationWhenInUse+<>c__DisplayClass6_0.<RequestLocationAsync>g__LocationAuthCallback|0 (System.Object sender, CoreLocation.CLAuthorizationChangedEventArgs e) [0x0004d] in d:\a\1\s\Xamarin.Essentials\Permissions\Permissions.ios.tvos.watchos.cs:185 at Xamarin.Essentials.Permissions+LocationWhenInUse.RequestAsync () [0x0005f] in d:\a\1\s\Xamarin.Essentials\Permissions\Permissions.ios.tvos.watchos.cs:109`

### Steps to Reproduce

This crash can be reproduced consistently in the app I'm working on an iPhone XR by:

1. App requests `LocationWhenInUse` permission
2. User selects `Allow Once`
3. User stop, restarts app
4. App crashes at the same spot when it requests `LocationWhenInUse` permission

### Basic Information

- Version with issue: 1.5.3.2
- Last known good version: ?
- IDE: Visual Studio for Mac 8.6.5 (build 23)
- Platform Target Frameworks:
  - iOS:  13.18.2.1
- Affected Devices: iPhone XR on iOS 13.5.1

**Comment by teamtam** [comment]
### Update

After some additional debugging in the app I'm working on, this is some additional context to reproduce the issue.

1. App requests `LocationWhenInUse` permission
2. Before the user gets a chance to answer, app again requests `LocationWhenInUse` permission from a different thread
3. User selects `Allow Once`, in response to whichever dialog is on top
4. App crashes

**Comment by rlasker-b2w** [comment]
We are seeing this same issue. ATM it is unknown if our steps are the same.

**Comment by brandonward34** [comment]
We too are getting the same issue.

**Comment by robertmadril** [comment]
We experienced the same crash reported on a device with the same specs listed in the original comment.

**Comment by jamesmontemagno** [comment]
Are you requesting the permission twice? An exception would be thrown if you are canceling it. Can you please attach a small sample project.
