### ISSUE TITLE
[Bug]  Share feature doesnt work as intended 

### ISSUE THREAD

**Issue by pirhano** [xamarin/Essentials#1326]
### Description
I have used the code mentioned in the documentation for sharing files 
      await Share.RequestAsync(new ShareFileRequest
                {
                    Title = "Share",
                    File = new ShareFile(file),
                    
                });
but the list of items shows empty
"All apps associated with this action have been disabled, blocked, or are not installed"
using SM-T560NU version 7.1.1
### Steps to Reproduce

1. Using Share.RequestAsync with ShareFileRequest ShareFile();

### Expected Behavior
Share using window includes "via bluetooth, GMail, Messenger, ...."
### Actual Behavior
"All apps associated with this action have been disabled, blocked, or are not installed"
### Basic Information

- Version with issue: 1.5.3.2
- Last known good version: N/A
- IDE: Visual Studio
- Platform Target Frameworks: 
  - Android: 8.1
- Nuget Packages: Xamarin.Essentials
- Affected Devices: samsung SM-T560NU

### Screenshots

![Untitled](https://user-images.githubusercontent.com/11685560/87236158-283afd80-c3ab-11ea-8d62-9ea9f3450e77.png)

**Comment by jamesmontemagno** [comment]
What type of file are you trying to share?

**Comment by jamesmontemagno** [comment]
Seems like an old samsung bug : https://stackoverflow.com/questions/43283383/all-apps-associated-with-this-action-have-been-disabled-blocked-or-are-not-ins perhapss it doesn't know how to handle file types. You shoudl be able to pass in the contetype as "*/*"
