### ISSUE TITLE
[Bug] Why does Preferences work on iOS etc, but not on MacOS when it uses NSUserDefaults under the hood?

### ISSUE THREAD

**Issue by CartBlanche** [xamarin/Essentials#1330]
#1126 # Description
Using `Preference.Get()` on MacOS throws NotImplemented Exception

### Steps to Reproduce

1. Create MacOS project
2. Add the Nuget to the project
3. Within your code call the following `theme = Preferences.Get ("Theme", 0);`

### Expected Behavior

As the whole iOS back end for preferences seems to hook into NSUserDefaults

as per:
https://github.com/xamarin/Essentials/blob/develop/Xamarin.Essentials/Preferences/Preferences.ios.tvos.watchos.cs

Shouldn't this "Just work(TM" on MacOS too?

### Actual Behavior
Throws the following exception :
<img width="454" alt="Screenshot 2020-07-19 at 12 24 46" src="https://user-images.githubusercontent.com/271363/87873609-e61d4780-c9ba-11ea-99af-bfdc9a470bd6.png">

### Basic Information

- Version with issue: 1.5.3.2
- Last known good version: 
  - Works in iOS and Android
- IDE: VS 4 Mac 8.6.5.23
- Platform Target Frameworks:
  - MacOS:  11.5
- Nuget Packages:
- Affected Devices: MacOS

I'm hoping this is an easy fix :)

**Comment by jamesmontemagno** [comment]
macOS was added in 1.6.0
