### ISSUE TITLE
[Enhancement] I would like to add a shaking force property in Accelerometer  like Accelerometer.ShakingForce = ShakingForce.Medium 

### ISSUE THREAD

**Issue by nouredine98** [xamarin/Essentials#1332]
## Summary
Please provide a brief summary of your proposal. Two to three sentences is best here.

## API Changes

Include a list of all API changes, additions, subtractions as would be required by your proposal. These APIs should be considered placeholders, so the naming is not as important as getting the concepts correct. If possible you should include some "example" code of usage of your new API.  You should also provide details of the level of availability for the feature on each of the supported platforms.

e.g.

In order to facilitate the new Shiny Button api, a bool is added to the Button class. This is done as a bool because it is simpler to data bind and other reasons...

    var button = new Button ();
    button.MakeShiny = true; // new API

The MakeShiny API works even if the button is already visible.

## Intended Use Case
Provide a detailed example of where your proposal would be used and for what purpose.

**Comment by jamesmontemagno** [comment]
There are a few ways of doing it...

Allowing users to set the property itself... 13^2 is the default...

Or we can have 
Light - 11
Medium - 13
Hard - 15

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
