### ISSUE TITLE
[Enhancement] Add support for SFSafariViewController in Launcher when opening URIs in iOS

### ISSUE THREAD

**Issue by baarhus** [xamarin/Essentials#1342]
## Summary
Apple is now rejecting app submissions for apps that open certain pages (platform registration, password recovery) in Safari instead of the Safari View Controller

## API Changes

Update PlatformOpenAsync(Uri uri) in the Launcher.ios.tvo.cs file to implement SFSafariViewController when a device is on iOS 9 or greater.

## Intended Use Case
In our app we have links on the sign in page that open to a portal page for user registration, password recovery, and username recovery. Up until our most recent update, we were achieving this by using Device.OpenUri (deprecated). We are adopting the essential Launcher, but apple is denying the update submission on the grounds of poor user experience.

**Comment by jamesmontemagno** [comment]
You will want to use "Browser", not Launcher. https://docs.microsoft.com/en-us/xamarin/essentials/open-browser?context=xamarin%2Fxamarin-forms&tabs=android

**Comment by baarhus** [comment]
My mistake. Thank you.
