### ISSUE TITLE
[Spec]  XImage

### ISSUE THREAD

**Issue by SaqibS** [xamarin/Essentials#1343]
# XImage (pronounced CrossImage)

There are various common image manipulation tasks performed in mobile apps. The XImage class abstracts away _some_ platform-specific APIs to provide for easier cross-platform coding. Note, however, that his is not meant to complete do away with the use of platform-specific image classes - it would be unrealistic to have a purely cross-platform image, but instead just to abstract away common manipulations.

While other libraries, like SkiaSharp, provide similar functionality, they have high overhead for these simpler operations, which could each be achieved in 10 or so lines of platform-specific code.

# API

Note that in the below, types such as Size, Rectangle, and Color come from System.Drawing.

### Constructors

| API | Description |
| ------------- | ------------- |
| XImage(UIImage/Bitmap image) | Creates a new XImage, which wraps this UIImage (iOS) / Bitmap (Android) |

### Properties

| API | Description |
| ------------- | ------------- |
| Size Size | Gets the size of the image. |

### Methods

| API | Description |
| ------------- | ------------- |
| XImage Resize(Size newSize) | Resizes the image. |
| XImage Crop(Rectangle region) | Crops the image. |
| XImage Rotate(int degrees) | Rotates the image. |
| byte[] ToJpeg(float compressionQuality) | Returns a JPEG representation of the image. |
| Color[] GetPixels() | Returns a one-dimensional array of the pixels in the image. |
| UIImage ToUIImage() / Bitmap ToBitmap() | Return a reference to the underlying platform image. |
 
# Scenarios

Simple image manipulation, including crop, rotate, and resize, plus access to the underlying pixel buffer.

# Platform Compatibility
- Target Frameworks: 
  - iOS:  
  - Android: 
  - UWP: 

# Backward Compatibility

# Difficulty : [low/medium/high]

Low-to-medium

**Comment by jamesmontemagno** [comment]
I think that this is a task best left to https://github.com/SixLabors/ImageSharp or other libraries out there as it is extremely difficult.

**Comment by mattleibow** [comment]
Or SkiaSharp 😉

**Comment by SaqibS** [comment]
Valid points. In this case, I'm planning to spin this up as a separate library as a side project, and see how it goes - I'm still at that optimistic phase where this feels easy enough to do.

I have a lot of respect for both ImageSharp and SkiaSharp - indeed, I use SkiaSharp in some of our projects. However, it feels like quite a chunky dependency for this use-case.

I've started coding a first draft of CrossImage - I'll report back in a week to let you know how it goes! My vision for this library is that it will actually only be a single class, with perhaps 5 methods; never growing beyond 10. Coded using native platform APIs like Core Graphics on iOS. Each method looks to be 5-10 lines of code, so easy to understand what the dependency you're pulling into your app does.

**Comment by mattleibow** [comment]
Have you checked out NGraphics? I think this is probably what you are going to do...

**Comment by mattleibow** [comment]
Closing this as I don't think this is the best place for this particular feature.

For a comprehensive framework, I would suggest SkiaSharp or ImageSharp.
For the basics, but not too limited, use NGraphics.
