### ISSUE TITLE
 Launcher.OpenAsync(new OpenFileRequest { File = new ReadOnlyFile(filePath) }); now working on ios 

### ISSUE THREAD

**Issue by viveknegi51288** [xamarin/Essentials#1348]
await Launcher.OpenAsync(new OpenFileRequest { File = new ReadOnlyFile(filePath) }); open and close suddenly.

 ### Steps to Reproduce

1. Xamarin forms version 4.8
2. Xamarin Essential 1.5.3.2

It should open normally to select the application.

**Comment by jamesmontemagno** [comment]
What kind of file is it? Do you have a repro for this?

Additionally, what device are you testing it on?

**Comment by Redth** [comment]
Closed for #1376
