### ISSUE TITLE
[Bug] FileNotFoundException is thrown when internet is turned off and user closes WAB dialog in uwp

### ISSUE THREAD

**Issue by IlGalvo** [xamarin/Essentials#1357]
### Description
When internet is turned off and user closes `WebAuthenticationBroker` dialog, `FileNotFoundException` is thrown.

### Steps to Reproduce
1.  Download Xamarin Essentials Samples
2.  Turn off internet.
3. Try to use `Web Authenticator` in UWP.

### Expected Behavior
When the dialog is closed, `WebAuthenticationStatus.UserCancel` is returned and then `TaskCanceledException` is thrown.

### Actual Behavior
FileNotFoundException is thrown

### Basic Information
- Version with issue: All
- Last known good version: None
- IDE: Visual Studio Community 2019
- Platform Target Frameworks: Xamarin Essentials Samples

### Screenshots
![Immagine1](https://user-images.githubusercontent.com/17992288/90956828-3c821800-e48a-11ea-89d9-15f212cea91b.jpg)
![Immagine2](https://user-images.githubusercontent.com/17992288/90956832-4441bc80-e48a-11ea-8710-67827cafc443.jpg)

**Comment by mattleibow** [comment]
Merged in https://github.com/xamarin/Essentials/pull/1358
