### ISSUE TITLE
await SecureStorage.GetAsync("fcm_token"); returns null

### ISSUE THREAD

**Issue by glintpursuit** [xamarin/Essentials#1359]
### Description

1. await SecureStorage.GetAsync("fcm_token"); returns null for Android OS. 
2. SecureStorage works everywhere else in Xamarin forms project.
3. It even works if I store value in  IFunction2 >> Invoke & try to retrieve it. 
4. Value are not getting preserved in MainActivity>>OnCreate too.

### Steps to Reproduce

- Reproduce 1

1.  Store token in MyFirebaseMessagingService (firebase service)>> OnNewToken
2. Try to retrive token in callbase IFunction2 >> Invoke
3. returns null.

- Reproduce 2

1. Store some string in main activity >> on create 
2. try to retrieve it in second run
3. returns null

### Expected Behavior
string should be persisted

### Actual Behavior
null result 

### Basic Information

- Version with issue: 1.5.3.2
- Last known good version: not known 
- IDE: VS for mac 
- Platform Target Frameworks: 
  - Android: 10 
- Nuget Packages: Xamarin.Essentials 
- Affected Devices: S10

**Comment by jamesmontemagno** [comment]
It looks like you are trying to receive this in a background service? 

I am not sure if that will work based on how we store it. I have to do some testing as I think it is aware of the context.

I would perhaps try `Preferences` and see if that works.

**Comment by glintpursuit** [comment]
@jamesmontemagno 

Thanks for response. 

I am currently using  Xamarin.Forms.Application.Current.Properties & its working for now.

**Comment by jamesmontemagno** [comment]
Yeah, if you use -> https://docs.microsoft.com/en-us/xamarin/essentials/preferences?context=xamarin%2Fxamarin-forms&tabs=android

You most likely don't need this to be encrypted and just stored private so `Preferences` or `Xamarin.Forms.Application.Current.Properties` would work.

**Comment by kiddailey** [comment]
I'm also experiencing a similar issue when trying to retrieve a previously set value on iOS.

If I set and then immediately get the value in the same function (just like in the DeviceTests.iOS unit tests), everything works fine.

If I set the value in one function and then immediately try to retrieve it in a separate function, I always get NULL.  If I set the value, exit the app and then try to get the value after relaunching the app, I always get NULL.  The ValueForKey() function in SecureStorage.ios.tvos.watchos.macos.cs never gets a Success for SecStatusCode in these cases.

I even just tried modifying the unit tests to include a case for a SecureStorage value saved separate from the retrieval and got the same NULL.

**Comment by johannperez** [comment]
If the SecureStorage is not the right way, what would be a good way to get secrets from a background service? For example an access_token

**Comment by douglassimaodev** [comment]
Hi, I am facing same problem, I have this in my app.xaml

private static string bearerToken;
        
        public async static Task<string> GetBearerToken()
        {
            if (string.IsNullOrEmpty(bearerToken))
                bearerToken = await SecureStorage.GetAsync(nameof(bearerToken));

            return bearerToken;
        }
        
   and I notice after a while after closing the application, when I open it  GetBearerToken() returns null
   
   does it get "deleted" after a while once the app is closed?

**Comment by flipper09112** [comment]
I get null in some ocasions too. Some idea? Occurs in both platforms

**Comment by YuliaLoyko** [comment]
why is it closed? i'm experiencing same issue as well
