### ISSUE TITLE
[Bug] Sharing files does not work on iPads

### ISSUE THREAD

**Issue by oskarskog** [xamarin/Essentials#1360]
### Description

Using the share API to share a file does not work on iPad.

### Steps to Reproduce

1. Call `Share.RequestAsync` with appropriate parameters.

### Expected Behavior
The sharing UI pops up.

### Actual Behavior
Nothing happens

### Basic Information

- Version with issue: 1.5.3.2
- Last known good version: Don't know
- IDE: VS for Mac
- Platform Target Frameworks: 
  - iOS: 13.6   
  - Android: N/A  
  - UWP: N/A  
- Android Support Library Version: N/A 
- Nuget Packages: Xamarin.Forms 4.4
- Affected Devices: 
iPad Pro (simulator)
iPad Mini

**Comment by jamesmontemagno** [comment]
Are you setting the `PresentationSourceBounds` ? https://docs.microsoft.com/en-us/xamarin/essentials/share?context=xamarin%2Fxamarin-forms&tabs=ios#presentation-location

**Comment by oskarskog** [comment]
Thank you, James! That was it.
