### ISSUE TITLE
[Bug] Error build MonkeyChat project in Visual Studio 2019 (https://github.com/jamesmontemagno/app-monkeychat)

### ISSUE THREAD

**Issue by hikarusai1991** [xamarin/Essentials#1363]
### Description

I took the source project MonkeyChat (https://github.com/jamesmontemagno/app-monkeychat) and started building with Visual Studio 2019 but always error. I tried to fix it but there are still a few errors:
    1. CS0103 The name 'MessagesListView' does not exist in the current context
    2. In project MonkeyChat.Droid cannot load nugets
I don't see where to build, can you show me how to fix it. Thank you very much.

![MonkeyChat_Error](https://user-images.githubusercontent.com/39739821/91297913-52187a00-e7c9-11ea-84e3-e920631b8052.png)

**Comment by hikarusai1991** [comment]
@jamesmontemagno can you help me?

**Comment by hikarusai1991** [comment]
I add the error
    3. CS0246 The type or namespace name 'ITwilioMessenger' could not be found
![ITwilioMessenger](https://user-images.githubusercontent.com/39739821/91328087-9bc88b00-e7f0-11ea-8764-affccc9caf5a.png)

**Comment by jamesmontemagno** [comment]
Can you please file a bug on that repo.
