### ISSUE TITLE
[Bug] iOS Xamarin.Essentials: Browser - Open a video page can not fullscreen on landscape mode

### ISSUE THREAD

**Issue by rex232** [xamarin/Essentials#1372]
### Description
On iOS platform, calling Browser.OpenAsync function with SystemPreferred mode  to open a video html page, when click the full screen button , the video can show on full screen but can't change orientation to landscape.  But it is work on same video page when using External mode.

### Expected Behavior
Can show the full screen video on landscape  mode

**Comment by jamesmontemagno** [comment]
We just link out to SFSafariView. So could just be a bug with theirs. It is inside of your app, so if you are locking your app rotation that may be it too.

**Comment by mattleibow** [comment]
Closing this as we cannot control the actions of things inside the safari views.
