### ISSUE TITLE
[Enhancement] iOS 14 permissions

### ISSUE THREAD

**Issue by softsan** [xamarin/Essentials#1375]
## Summary
With iOS 14, they'll change asking permission from user especially photo and location. 

## API Changes
in iOS 14, the permission for photos and locations changed as follows.
Photos:
<img width="366" alt="Screenshot 2020-09-07 at 11 00 51 PM" src="https://user-images.githubusercontent.com/7391319/92409508-7fb4da00-f15e-11ea-8e86-48c0797ec2d3.png">

Locations:
<img width="369" alt="Screenshot 2020-09-07 at 11 01 03 PM" src="https://user-images.githubusercontent.com/7391319/92409522-8cd1c900-f15e-11ea-9e27-44448c723a73.png">

## Intended Use Case
So can we keep it only one permission option like it is in iOS 13 such as Allow and Don't allow especially for Photos?

**Comment by jamesmontemagno** [comment]
Nothing should change at all.

Basically how this will work is:

You request permission (same as today). If they select either Allow Once or Allow While Using App you will get granted back. If they select "While using app" then you are good to go until they manually revoke the permission.

if they select "allow once" apple will revoke it at some point after you access the API, so you should check before every call to Photos.

**Comment by saadsaifse** [comment]
What about the Precise location option? Is there already a way to check if the user has turned off the precise location? if yes then is there a way to ask the user to allow precise location?
