### ISSUE TITLE
[Enhancement] UWP can share data between apps

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Essentials#1377]
## Summary

Some publishers may have multiple apps and wish to share data.

https://docs.microsoft.com/uwp/api/windows.storage.applicationdata.getpublishercachefolder

## API Changes

Not sure how this would look, so this issue will probably need to be fleshed out.

iOS uses the keychain at least.

Not sure about Android or Tizen.

## Intended Use Case

A company that has multiple apps, say one for the shipping department and one for sales. Instead of having login tokens or theme preferences per app, a shared feature will be great.

**Comment by jamesmontemagno** [comment]
Pretty neat API. Android I know you can do it somehow... with owner rights or something magical. I think?

**Comment by jamesmontemagno** [comment]
Another question is if it works with System.IO? I assume so? Maybe?

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
