### ISSUE TITLE
[Enhancement] Add SaveAsync method to FilePicker class

### ISSUE THREAD

**Issue by djordje200179** [xamarin/Essentials#1386]
## Summary
I think that it would be nice if we could show a picker using which a user could save a file. It would behave like `FileSavePicker` in Windows/UWP. 

## API Changes
Add `public static async Task<FileResult> SaveAsync(SaveOptions options = null);` method to `FilePicker` class.

## Intended Use Case
This functionality could be used when developers want to give a user ability to save a file (or an image), that was created in an app, in any folder that the user wants.

**Comment by mattleibow** [comment]
Just want to check... How does this differ from a share? Is this basically putting the file onto the filesystem and never going to a new app?

**Comment by djordje200179** [comment]
If you have an app that edits images or creates documents, and latter the user wants to save the file to internal storage.

**Comment by VladislavAntonyuk** [comment]
I think it is responsibility of the fileSystem: https://github.com/xamarin/Essentials/issues/1006

**Comment by 1Cor125** [comment]
Putting it in the `FileSystem` API could cause some confusion. I see the `FileSystem` API being enhanced to allow for saving files _within the scope of the app_ (sandbox, permitted folders) whereas saving a file _out of the app's scope_ (to an external location on the device, or to the cloud) seems to be a separate concern. I like the semantics in UWP for this. They call it `FileSavePicker` (under `Windows.Storage.Pickers`). Or if that is too fine-grained, it could be an enhancement to the `FilePicker` API as suggested by @djordje200179.

**Comment by MikDal002** [comment]
> Just want to check... How does this differ from a share? Is this basically putting the file onto the filesystem and never going to a new app?

It differs this way, user sometimes just want to save something outside app without opening it (backup with possibility to share file later). Additionally, I meet androids where sharing doesn't allow saving JSON files on disk.

**Comment by MuzzyA** [comment]
Any update on this?  Seems to be a pretty simple change.  Change the 'Open' button to say 'Save', then remove the check for a valid file when you click the button.  Just need the file path.  It's up to the developer to determine how the file is saved.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.

There is now a FileSave API in the .NET MAUI Community Toolkit available that allows you to save files!
