### ISSUE TITLE
Add synchronous API for SecureStorage: Get / Set

### ISSUE THREAD

**Issue by Pinox** [xamarin/Essentials#1395]
@jamesmontemagno   Hi James , please reconsider this pull request again as the code that I'm writing in property getter and setters are really really ugly.   This is also not very user friendly especially for beginners , surely the Xamarin.Essentials package should be approachable even for beginners and  it's not.  

Previous pull request on this :
https://github.com/xamarin/Essentials/pull/857

**Comment by mattleibow** [comment]
Closing this as we cannot really do this in a cross-platform manner. 

The methods are asynchronous for a reason as they require a fair bit of processing or encryption to store. And, some platforms are async-only. It is not a long time, maybe a few milliseconds, but this is long in CPU time.

Maybe I don't understand exactly, but it sounds like you are using the secure storage as a backing for some set of properties?

Also, James left this same comment: https://github.com/xamarin/Essentials/issues/856#issuecomment-513905836

**Comment by Pinox** [comment]
@mattleibow - it stems more from the fact that **Microsoft's new design guidelines** includes **async + sync**.  It was mentioned by one of the Microsoft engineers on a dotnet core thread if I remember correctly.  As someone already made the effort to do the coding and commit a push request regarding this , I think it's really poor form to firstly not embrace these MS guidelines and secondly not helping in creating a cohesive and all inclusive language paradigm embracing both sync + async.

**Comment by mattleibow** [comment]
That may be, but there is no sync API for all platforms. For example, UWP, so we can't do anything.

**Comment by Pinox** [comment]
@mattleibow, I hear you, but this is where MS should knock on UWP teams door and say plse add these sync api's if that is the minimum requirement for xamarin essentials. It makes the .net ecosystem approachable even for beginners/students without resorting to writing "sync wrappers" or rewriting existing code where sync was the norm for the majority of non secure preferences. In my instance I would prefer to store my JWT to secure storage but the async call now has a massive ripple effect through my code base as all other preferences are sync.

I just think the .net ecosystem should be **all inclusive** and more effort should be made especially in a library like Essentials to be approachable.
