### ISSUE TITLE
[Enhancement] Add support for popover file pickers

### ISSUE THREAD

**Issue by 1Cor125** [xamarin/Essentials#1396]
## Summary
I’m very pleased to see the FilePicker and MediaPicker API’s shaping up on 1.6-pre. Thank you! I notice that there is no support for a popover file picker on iOS. Is this on the roadmap? We have a requirement for displaying file and media pickers as a popover with iPads. 

## API Changes
I suppose an anchor view would have to be passed in and I’m not sure the best way to do that with a shared API. For our homemade FilePicker library we just overload the same method with one that takes an anchor view (e.g. UIView, UIBarButtonItem). For Essentials, it might be cleaner to create extension methods off the FilePicker and MediaPicker classes. These methods would only live in iOS land. I'd be happy to contribute toward this.

## Intended Use Case
Anchor a popover to a particular view element on an iPad instead of always having to show a full screen file or media picker.

**Comment by velocitysystems** [comment]
Would love to see support added for this too. We're also relying on a home-grown library for this, and would nice to be able to consolidate into using XE.

**Comment by mattleibow** [comment]
I think this was recently added into the works. I see code for setting popovers and locations.

I am trying to get the new preview out and if it is not working as you expect, then just reopen.

**Comment by mattleibow** [comment]
I see this was just added to media picker.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Essentials is now in maintenance mode, this will not happen anymore for Xamarin.Essentials. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
