### ISSUE TITLE
[Enhancement] Add locale support for PlatformGetPlacemarksAsync and PlatformGetLocationsAsync

### ISSUE THREAD

**Issue by ujentzell** [xamarin/Essentials#1400]
## Summary
The Geocoding methods **PlatformGetPlacemarksAsync** and **PlatformGetLocationsAsync** don't support locale today and therefore returns the location names in the phone language, this can be a problem when extracting e.g. city name that needs to be in English (e.g Gothenburg) but the phone is set to e.g Swedish (Göteborg).

## API Changes
Add new argument to support locale (e.g. CultureInfo locale) to  method 
**`static async Task<IEnumerable<Placemark>> PlatformGetPlacemarksAsync(double latitude, double longitude)`**
located in the Geocoding class => 
**`static async Task<IEnumerable<Placemark>> PlatformGetPlacemarksAsync(double latitude, double longitude, CultureInfo locale = null)`**

Add new argument to support locale (e.g. CultureInfo locale) to  method 
**`static async Task<IEnumerable<Location>> PlatformGetLocationsAsync(string address)`** 
located in the Geocoding class => 
**`static async Task<IEnumerable<Location>> PlatformGetLocationsAsync(string address, CultureInfo locale = null)`**

iOS
https://developer.apple.com/documentation/corelocation/clgeocoder

Android
https://developer.android.com/reference/android/location/Geocoder

## Intended Use Case
Adding locale will provide functionality to extract city name with a forced language, this to language normalize geolocations for e.g. analytics purpose etc.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
