### ISSUE TITLE
[Enhancement] Contacts Get All

### ISSUE THREAD

**Issue by dimonovdd** [xamarin/Essentials#1403]
There is already a method for getting one item from the contact list ([Pull Request](https://github.com/xamarin/Essentials/pull/1349))
But there is no method for getting all the contact list
I have drafts that will help solve this issue on Android, iOS and UWP

 **API**
`Task<List<Contact>> Contacts.GetAll()`

**Difficulty : [low]**

**Comment by mattleibow** [comment]
What happens if a device has say 1000 contacts. Will there be some delay/perf issues?

Can we look at some IAsyncEnumerable or something? Maybe we need a paging system? This is probably the same issue for the Calendar API, but if we can get a nice solution here, then we can grow.

**Comment by pictos** [comment]
@mattleibow I did the GetAll in one of the first implementations of this feature... I remember that takes a huge time if we have a lot of contacts (and it's possible), I can't remember right now how I _solved_ this issue, but I guess that I used the [ManualResetEvent](https://docs.microsoft.com/en-us/dotnet/api/system.threading.manualresetevent?view=netcore-3.1). In right level, I did this:

1. Created an event handler to the dev subscribe, where the EventArgs was the Collection of Contacts and the ManualResetEvent object ;
2. When the method get 20 contacts it stops and fires the event;
3. The dev read the Collection and resume or stop the Task using the ManualResetEvent object

**Comment by mattleibow** [comment]
Maybe we can have a custom return type that wraps all this? So getall returns a contacts collection which is an ienumeable the can get on demand. Hiding whatever mechanism is used under the hood.

class Contacts Collection : IEnumerable<Contact>

That sort of thing. The API just sets it up and on Android it hides the ICursor things.

**Comment by dimonovdd** [comment]
@mattleibow 
I'll make a draft of the merging request and we'll be able to discuss it in more detail.
I think we should do it, this function is very useful
