### ISSUE TITLE
[Enhancement] Add FilePickerFileType.Pdf to FilePicker

### ISSUE THREAD

**Issue by ivarlovlie** [xamarin/Essentials#1404]
## Summary
Add option for picking PDFs on all supported platforms. I realize we could use a FilePickerFileType for all possible filetypes (or maybe a parser), but PDFs is such a common format that i think it justifies the addition.

## API Changes
To make it simpler for developers to pick PDFs we add `FilePickerFileType.Pdf` to the FilePicker API for all supported platforms.

## Intended Use Case
Picking PDFs

**Comment by RodgerLeblanc** [comment]
I'll work on this one.

**Comment by RodgerLeblanc** [comment]
As this issue is in the 1.6.0 milestone, should the PR be sent to `1.6.0` branch instead of `develop`?

**Comment by vividos** [comment]
@mattleibow @Redth We probably should either provide some more common types or remove the existing altogether, so that the user has to provide the file types him/herself. My guess is that there will be several tickets for this after the 1.6.0 release...

**Comment by vividos** [comment]
@RodgerLeblanc The 1.6.0 branch was already merged to develop, so I think this branch was for integration purposes.

**Comment by ivarlovlie** [comment]
@vividos 

> We probably should either provide some more common types or remove the existing altogether, so that the user has to provide the file types him/herself. My guess is that there will be several tickets for this after the 1.6.0 release...

We already have the option to provide our own filetypes, but since we potentially need to look up three different filetype representations (mime, UtType, file extension) these collections is convenient.

**Comment by vividos** [comment]
Of course it's convenient, but where should Essentials stop? Should the types that I most often use, KML and KMZ, also have a constant in Essentials?

**Comment by ivarlovlie** [comment]
I think PDFs is a nice spot to stop :) as stated initially:
> I realize we could use a FilePickerFileType for all possible filetypes (or maybe a parser), but PDFs is such a common format that i think it justifies the addition.

I would like to think that this is the reason png, images and videos was added initially.

**Comment by vividos** [comment]
I added just these few types in the initial PR to have some pre-existing examples, but we never discussed to provide more types. Let's see what the Essentials devs think about it...

**Comment by mattleibow** [comment]
I need to clean up the branches, just work from `main`. develop and 1.6 are all merged in there.

**Comment by mattleibow** [comment]
This probably needed more thought. I think we did images and png, but we probably should do some of the most basic types. Like video, mp4, jpeg, pdf.

This library is supposed to be useful, so I think we can have a look at what types of files someone would pick. Obviously there are infinite possibilities, but what would 80% of apps pick?
