### ISSUE TITLE
[Bug] Launcher http://maps.apple.com opens safari and then maps in iOS 14

### ISSUE THREAD

**Issue by jthegeman** [xamarin/Essentials#1409]
using iOS 14

await Launcher.OpenAsync($"http://maps.apple.com/?q={FormatForMapApp}");

Opens Safari and then Open Maps, which prevents the return to application action previously available.

in iOS 13.x it directly opened the maps app.

**Comment by jamesmontemagno** [comment]
Should report to Apple, we do not have control over what the maps app does.

Is there a reason you aren't just using the Maps API: https://docs.microsoft.com/xamarin/essentials/maps?tabs=android&amp;WT.mc_id=docs-twitter-jamont it opens maps directly.
