### ISSUE TITLE
DeviceInfo: Returning wrong device name

### ISSUE THREAD

**Issue by ruby-verma** [xamarin/Essentials#1417]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/main/SUBMITTING-ISSUES.md)

### Description
DeviceInfo API is returning device model as a device name

### Expected Behavior
The device name and the model must be different.

### Actual Behavior
The device name and the model are the same. 

### Basic Information

- Version with issue: 1.5.3.2
- Last known good version: unknown
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: Android 10
- Android Support Library Version: AndroidX 1.1.0
- Nuget Packages: Xamarin.Essentials
- Affected Devices: Pixel (OS 10)

My Device name is - Pixel123
Device Model: Pixel
Device Name: Pixel

**Comment by mattleibow** [comment]
I see you opened some PRs and now everything is closed.

What is the reason for this? Did you manage to resolve the issue?

**Comment by ruby-verma** [comment]
Hi @mattleibow ,
I wasn't able to set the reviewer for my PR thus have to close. I resolved the issue by directly using Android API
var name = Android.Provider.Settings.Global.GetString(Xamarin.Essentials.Platform.AppContext.ContentResolver, "device_name");

Please check my comment on https://github.com/xamarin/Essentials/issues/675

**Comment by mattleibow** [comment]
I don't think you can set the reviewer since you are not a coffee owner.

Just open the PR, if it is still valid, and then we can have a look.

**Comment by ruby-verma** [comment]
Hi @mattleibow ,

Please have a look at https://github.com/xamarin/Essentials/pull/1424

Thanks,
Ruby
