### ISSUE TITLE
[Enhancement] Exception types do not match intended target

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#1419]
Currently we throw PlatformNotSupportedExceptions with a message, when we have a self declared exception type which is already used for this scenario. PlatformNotSupportedException is declared in System.Runtime.Serialization which simply adds namespace clutter and confusing docs, as that exception should not be used in our scenario. Docs:

> 
        // Summary:
        //     Provides Microsoft.Win32.RegistryKey objects that represent the root keys in
        //     the Windows registry, and static methods to access key/value pairs.

Instead we should throw a NotImplementedException with a message as we already do in a couple of places. This is probably best adressed in a a larger exception handling project as #1415 and #963 as well as #457 relate to this.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Essentials is now in maintenance mode, this will not happen anymore for Xamarin.Essentials. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
