### ISSUE TITLE
[Bug] Error encountered opening camera app on UWP

### ISSUE THREAD

**Issue by 1Cor125** [xamarin/Essentials#1421]
### Description

Camera app does not open successfully on UWP.

### Steps to Reproduce

1. Using the Samples.UWP app on the `main` branch of this repo, attempt to capture a photo or video using the buttons on the MediaPicker page.
2. The native Camera app opens but it shows an error screen. Two errors are shown in succession. 1) `PageOpenFailed` and then 2) `WindowShowFailed`. Screenshots with the error details are shown below.

### Expected Behavior

The Camera app should open and show the default camera UI. The Camera app works fine when opened directly (not via the Samples.UWP app).

### Actual Behavior

The Camera app should open and display the default camera UI.

### Basic Information

- Version with issue: 1.6.0-pre2 (running Samples.UWP app from `main` branch)
- Platform Target Frameworks:
  - UWP:  The samples app is compiled using 10.0.18362. The Surface Book 2 is running 10.0.19041
- Affected Devices: Surface Book 2

### Screenshots

![first_error](https://user-images.githubusercontent.com/10599524/95118471-5a44cd00-0718-11eb-8605-186adf594f60.png)
![second_error](https://user-images.githubusercontent.com/10599524/95118480-603aae00-0718-11eb-8062-0cb2890222ba.png)

**Comment by velocitysystems** [comment]
I can confirm this failure also. Would be great to see a fix in an upcoming release of XE.

**Comment by DennisWelu** [comment]
I'm not sure if this is related or not but worth mentioning....I have observed that the app runs but camera permission is never obtained (it's not supported in XE on UWP currently, my understanding). So the camera does not work (in Release builds) but manually switching the camera permission "on" in windows app settings and the camera will start working.

**Comment by mattleibow** [comment]
I am not able to reproduce this. Are you doing anything specific on your machine?
I have had times where my camera stops working and a restart fixed it.
