### ISSUE TITLE
Xamarin.Essentials: Web Authenticator - CallBack not work

### ISSUE THREAD

**Issue by 78fede78** [xamarin/Essentials#1428]
Good morning

my aim is to integrate facebook authentication with my mobile application that i made with xamarin form.

For this purpose I followed this procedure:

https://devblogs.microsoft.com/xamarin/authentication-xamarin-essentials-aspnet/

The web api part, on the other hand, is made using NET Core 3.

I created my application from

https://developers.facebook.com/

At first I had problems with the lack of domain.

I was accessing the web api directly via the ip address and without https and this gave me problems.

Now I have fixed these problems but it is not clear how the return callback should be handled.

I did as written in the documentation

```
 var callbackUrl = new Uri ("myapp://");

 r = await WebAuthenticator.AuthenticateAsync (authUrl, callbackUrl);
```
 
Actually this callBackurl is IGNORED and the url that is called is the default callback url which is:

https://www.mywebapi.eu/signin-facebook?code=xxxxxxx

This page is not present in my web api project and therefore it all ends with a sad 404 error.

in the example it is not clear if a signin-facebook control should be created.

I would have expected the callback to call my app again and have permission to read the necessary user information.

**Comment by mattleibow** [comment]
This might not be the app error, but the Facebook setup. Did you let Facebook know to use that callback in the developer portal?

@redth, is my logic correct?

**Comment by Redth** [comment]
The flow is supposed to be:

```
Mobile  ->   Web API                           -> Facebook -> Web API                       -> Mobile
                    (/mobileauth/facebook)                             (/signin-facebook/...)        (myapp://...)
```

You need to [configure your web API](https://github.com/xamarin/Essentials/blob/main/Samples/Sample.Server.WebAuthenticator/Startup.cs#L38-L43) to add facebook auth support, and then configure your facebook oauth token to use the redirect url that goes back to `/signin-facebook` which would ultimately redirect back to `/mobileauth` after it's authenticated at which point your [custom mobileauth controller](https://github.com/xamarin/Essentials/blob/main/Samples/Sample.Server.WebAuthenticator/Controllers/MobileAuthController.cs) logic will redirect to `myapp://`.
