### ISSUE TITLE
How does InvokeOnMainThreadAsync handle multi Threading

### ISSUE THREAD

**Issue by SOliasS** [xamarin/Essentials#1431]
I was wondering how exactly does InvokeOnMainThreadAsync handles it when multiple Tasks try to access the main thread at the same Time.
I have multiple services which could try to access the Main Thread at the same time and now i was wondering if InvokeOnMainThreadAsync can handle it or if i have to implement a queuing system to handle this kind of workload.
So on thread doesn't take the Main thread away from another one.

**Comment by mattleibow** [comment]
`InvokeOnMainThreadAsync` does all the work to queue it up for you, so only one operation can run at a time. This is not really a special feature, it is just how threads work - they can only physically run one thing at a time.
