### ISSUE TITLE
[Bug] Screenshot in UWP fails with exception (0x8001010E (RPC_E_WRONG_THREAD))

### ISSUE THREAD

**Issue by zleao** [xamarin/Essentials#1432]
### Description
This issue is related to the functionality introduced in [PR 744](https://github.com/xamarin/Essentials/pull/744).
Using the screenshot API with the UWP sample, provided in the Xamarin Essentials repository, fails with a system exception, related to cross thread access (0x8001010E (RPC_E_WRONG_THREAD).
This only happened to me in UWP. I've tried the Android and iOS implementations and the result was successful.

### Steps to Reproduce

1. Run Xamarin Essentials sample app for UWP
2. Go to Screenshot -> Take Screenshot

### Expected Behavior
Screenshot taken and shown in the app

### Actual Behavior
Exception is thrown:
`System.Exception: 'The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))'
`
### Basic Information

- Version with issue: Main branch from current code repository (after tag 1.6.0-pre2)
- Last known good version: 
- IDE: Visual Studio 2019 (16.7.5)
- Platform Target Frameworks:
  - UWP:  16299
- Affected Devices: Windows 10 Pro 2004

### Screenshots

![image](https://user-images.githubusercontent.com/3188042/95453759-bbb0aa00-096b-11eb-905e-e1662c0bda9a.png)

### Aditional Info

I tracked down the exception source to the [Screenshot UWP implementation line 39](https://github.com/xamarin/Essentials/blob/0dba844e8085f7cb36d62115b005620d541e0fbd/Xamarin.Essentials/Screenshot/Screenshot.uwp.cs#L39), when trying to access the `bmp.PixelWidth`. The problem is that the caller of the `ScreenshotResult` constructor is passing a object instance that was created in a different thread, since we have a `ConfigureAwait(false)` on line 24.
A quick solution could be setting it to `ConfigureAwait(true)` or removing the instruction all together.
Once this issue is confirmed as valid, I can make the PR myself.

**Comment by mattleibow** [comment]
Thanks for catching this.

Maybe go ahead with a PR that explicitly sets it to true and maybe add a comment just in case a future dev gets excited and wants to remove it.

**Comment by mattleibow** [comment]
I can't actually seem to repro this... Very weird... But I'll merge your fix in for now to potentially avoid any issues.
