### ISSUE TITLE
GetStream() for CapturePhotoAsync

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#1434]
Hi,

Please add GetStream() to the Media's CapturePhotoAsync() for easy reading the stream without having to write anything else so it will be something like this:

var stream = CapturePhotoAsync().GetStream();

Thanks,
[Jassim](https://www.emiratesangels.org)

**Comment by mattleibow** [comment]
You can already do that with the `OpenReadAsync` method on the `FileResult`:

```csharp
var photo = await MediaPicker.PickPhotoAsync();
var stream = await photo.OpenReadAsync();
```
