### ISSUE TITLE
[Enhancement] Prefer custom safehandles over IntPtr

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#1436]
For some extern methods we have IntPtr as part of the method signature. In cases where we do not expect IntPtr.Zero to work and where we need custom cleanup (as in the current macos PR for Screenshots) we should consider switching to SafeHandle derived classes. This removes the need to write a correct finalizer in most cases and has a clearer intent as a IntPtr. In the case of the screenshot pr we should probably not switch as CGImage is the class which emulates safehandle behaviour, but simply looking over the wpf pr offers enough examples where this is useful

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
