### ISSUE TITLE
[Enhancement] Harden Xamarin.Essentials for Culture Invariance

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#1437]
## Summary
I thought about this issue when looking over the tizen calender PR, after working on roslyn analyzers for a while which offer an analyzer for culture relevant comparisons or calls to string methods which might behave differently than expected. Explicitely I thought about api calls where we convert between integers and strings, as different cultures might format strings differently. If we then pass them back in we might get the expected results, even though these are the values we returned.

## API Changes

All would be internal. I would recommend installing the roslyn globalization analyzers which flag this behaviour. See [CA1307](https://docs.microsoft.com/de-de/dotnet/fundamentals/code-analysis/quality-rules/ca1307?view=vs-2019)

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
