### ISSUE TITLE
[Enhancement] DeviceDisplay/DisplayInfo should report refresh rate

### ISSUE THREAD

**Issue by janusw** [xamarin/Essentials#1443]
## Summary

[DisplayInfo](https://docs.microsoft.com/de-de/dotnet/api/xamarin.essentials.displayinfo) already contains various information about the display, like width/height, density, orientation, rotation, etc. It should also include the device's screen refresh rate.

## API Changes

The DisplayInfo struct should obtain a new property called `RefreshRate` or similar:

    public readonly struct DisplayInfo : IEquatable<DisplayInfo>
    {
        [...]
        public double RefreshRate { get; }
        [...]
    }

Example usage:

    // Get Metrics
    var mainDisplayInfo = DeviceDisplay.MainDisplayInfo;
    
    // display refresh rate in Hz (i.e. "frames per second")
    var rate = mainDisplayInfo.RefreshRate;

## Intended Use Case

The refresh rate can be useful for example in connection with sensor update rates, which are configurable via `SensorSpeed` (or can be throttled manually). If one knows the screen refresh rate, one can make sharper constraints on the necessary sensor rates. E.g. if my screen updates only with 30 Hz, I probably don't need to sample the OrientationSensor with 50 Hz, because the information can not be displayed that quickly. Or the other way around: If I know that my screen updates with 60 or even 120 Hz, then I might want to increase the sensor updates accordingly, so that I can get a smoother display (e.g. think of an "augmented-reality"-type camera overlay).

## Implementation

Some pointers that might be useful for the implementation:
* Android: https://docs.microsoft.com/en-us/dotnet/api/android.views.display.refreshrate
* iOS: https://developer.apple.com/documentation/uikit/uiscreen/2806814-maximumframespersecond

**Comment by janusw** [comment]
Getting the refresh rate on iOS and Android seems to be straightforward, but I did not find a way to obtain it on MacOS :(

The class `AppKit.NSScreen`, which is already being used in `DeviceDisplay.macos.cs` does not seem to provide anything in this direction: https://developer.apple.com/documentation/appkit/nsscreen

In principle there is a `CGDisplayMode.refreshRate` in Apple's CoreGraphics for MacOS: https://developer.apple.com/documentation/coregraphics/cgdisplaymode/1454661-refreshrate

However, in the .NET APIs for Xamarin.Mac, I only find a [CGDisplay](https://docs.microsoft.com/de-de/dotnet/api/coregraphics.cgdisplay?view=xamarin-mac-sdk-14) class, but no way to get a fresh rate or even just a `CGDisplayMode`.

**Comment by janusw** [comment]
> In principle there is a `CGDisplayMode.refreshRate` in Apple's CoreGraphics for MacOS: https://developer.apple.com/documentation/coregraphics/cgdisplaymode/1454661-refreshrate
> 
> However, in the .NET APIs for Xamarin.Mac, I only find a [CGDisplay](https://docs.microsoft.com/de-de/dotnet/api/coregraphics.cgdisplay?view=xamarin-mac-sdk-14) class, but no way to get a fresh rate or even just a `CGDisplayMode`.

Maybe one should open a feature request in https://github.com/xamarin/xamarin-macios (or am I just missing something)?

**Comment by janusw** [comment]
> Maybe one should open a feature request in https://github.com/xamarin/xamarin-macios (or am I just missing something)?

Just did that: xamarin/xamarin-macios#9958

**Comment by janusw** [comment]
Finally, the following might be relevant for an UWP implementation: https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.core.hdmidisplaymode.refreshrate

**Comment by mattleibow** [comment]
Thanks for all the work and research on this one!
