### ISSUE TITLE
[Bug] Flashlight error (Java.Lang.IllegalArgumentException: Bad argument passed to camera service)

### ISSUE THREAD

**Issue by holecekp** [xamarin/Essentials#1454]
### Description
I am using Micorsoft AppCenter for reporting crashes in my application. Today, I received the following report:

**FlashlightOutput.SendSignalAsync (System.Int32 milliseconds)**
Java.Lang.IllegalArgumentException: Bad argument passed to camera service

**Stack trace:**
![flashlight error](https://user-images.githubusercontent.com/24872113/96287020-93672200-0fe1-11eb-8dbc-438e369ba3dc.png)

**Device:** Redmi Note 4
**OS version:** Android 6.0

AppCenter reports 5 exceptions from this device this day so it seems that it will be an issue that occurs constantly on some devices. However, I have tested the application on two physical devices and it works without problem. So the crash probably occurs only on some devices.

### Steps to Reproduce

I am unable to reproduce the crash on my device. Probably, it will be connected only to some devices.

### Expected Behavior

Flashlight.TurnOnAsync() should not crash the application.

### Actual Behavior

Flashlight.TurnOnAsync() causes crash on some devices.

### Basic Information

- Version with issue: 1.5.3.2
- Last known good version: ?
- IDE: VS 2019
- Platform Target Frameworks: 
  - Android: targeting android 10, the bug is reported for device with android 6
- Android Support Library Version: 
- Nuget Packages:

Microsoft.AppCenter.Crashes - 3.4.3
Xamarin.AndroidX.AppCompat.Resources -1.1.0.1
Xamarin.AndroidX.MediaRouter - 1.1.0.5
Xamarin.Essentials - 1.5.3.2
Xamarin.Forms -4.8.0.1534

- Affected Devices: crash reported for Redmi Note 4

**Comment by jamesmontemagno** [comment]
Do you have the code in which you re trying it? are you try/catching the exception?

**Comment by holecekp** [comment]
The code transmits a Morse code using a flashlight.

```csharp
        private async Task SendSignalAsync(int milliseconds)
        {
            await Xamarin.Essentials.Flashlight.TurnOnAsync().ConfigureAwait(false);
            await Task.Delay(milliseconds).ConfigureAwait(false);
            await Xamarin.Essentials.Flashlight.TurnOffAsync().ConfigureAwait(false);
        }
```

This is called repeatedly and there is again Task.Delay between the calls.

The values of the _milliseconds_ parameter for SendSignalAsync are generally tens, or hundreds of milliseconds. The lowest value of the _milliseconds_ is 40 milliseconds. The shortest delay between SendSignalAsync calls is also 40 milliseconds (and also the usual values are tens or hundreds of milliseconds).

This is all placed in a try/catch block and the exceptions are reported to AppCenter.

**Comment by jamesmontemagno** [comment]
https://github.com/xamarin/Essentials/pull/1563 should also fix it I think
