### ISSUE TITLE
[Bug] GetLocationAsync stops after user permission request

### ISSUE THREAD

**Issue by matteomonizza** [xamarin/Essentials#1458]
### Description

On iOS GetLocationAsync fails after the user permission is asked

### Steps to Reproduce

1. Reset the privacy to Ask
2. Start GetLocationAsync()
3. The user select to allow one time and after the selection the task ends

### Expected Behavior

Locations are returned

### Actual Behavior

Task stops

### Basic Information

- Version with issue: 1.5/1.6
- Last known good version: //
- IDE: Visual studio for mac
- Platform Target Frameworks: iOS
  - iOS:  14.0
- Nuget Packages: Xamarin Essentials
- Affected Devices: Simulator and real device

### Code

I've create a simple project with one ViewController and override ViewDidAppear

        public override async void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);

            var Locations = await Xamarin.Essentials.Geolocation.GetLocationAsync();

            Console.WriteLine(Locations.ToString()); //Code never reached
        }

**Comment by seanrodda** [comment]
Is this a repeat of https://github.com/xamarin/Essentials/issues/1390 ?

**Comment by matteomonizza** [comment]
I think yes, thank you for the answer

**Comment by mattleibow** [comment]
Duplicate of https://github.com/xamarin/Essentials/issues/1390
