### ISSUE TITLE
[Enhancement] FilePicker limit shown files to allowed filtypes

### ISSUE THREAD

**Issue by ludas96** [xamarin/Essentials#1461]
## Summary
Is it possible to filter out invalid/not allowed filetypes when browsing through the files? Currently every single file is shown but greyed out if not allowed - and only the allowed filetypes can be selected. But could this be further optimized and actually filtering out the unwanted filetypes?

## Intended Use Case
Easier for the user to know which files to select and not only relying on colorscheme to give the user hints.

**Comment by dimonovdd** [comment]
It depends on the file Manager you choose

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Essentials is now in maintenance mode, this will not happen anymore for Xamarin.Essentials. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
