### ISSUE TITLE
[Enhancement] AppAction: UIApplicationShortcutIcon

### ISSUE THREAD

**Issue by Suplanus** [xamarin/Essentials#1463]
## Summary
With iOS you can use pre defined icons: https://developer.apple.com/documentation/uikit/uiapplicationshortcuticon/icontype

## API Changes
You can pass the name of the enum value, like `IconType.play`.

**Comment by mattleibow** [comment]
Di any other olfactory have this concept?

**Comment by Suplanus** [comment]
I don't think so. Here is the [Android docu](https://developer.android.com/guide/topics/ui/shortcuts/creating-shortcuts).

**Comment by jamesmontemagno** [comment]
Could be a platform specific API, but couldn't be done cross platform. So we could expose the API only on iOS.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
