### ISSUE TITLE
[Bug] Upgrade to iOS 14 erases values stored in Secure Storage

### ISSUE THREAD

**Issue by ericvandamme** [xamarin/Essentials#1464]
### Description
Upgrade to iOS 14 causes SecureStorage values to be removed. Code works fine if reinstalled on iOS 14. In my use case, a randomly generated encryption key is stored in SecureStorage. This was reported with iOS 13 upgrades from iOS 12 #961 

### Steps to Reproduce

1. Configure app in iOS 13.x
2. Upgrade to iOS 14
3. Some settings stored in SecureStorage are missing

### Expected Behavior
Settings that were stored in SecureStorage in iOS 13 would remain after the upgrade to iOS 14.

### Actual Behavior
Settings that were stored in SecureStorage in iOS 13 would be cleared after the upgrade to iOS 14.

### Basic Information

- Version with issue: Appears to be all
- Last known good version: Not known
- IDE: Microsoft Visual Studio Professional 2019 Preview - Version 16.8.0 Preview 2.1
- Platform Target Frameworks:
  - iOS:  8.0
- Nuget Packages:
  - Xamarin.Forms 4.8.0.1451
  - Xamarin.Essentials 1.5.3.2
  - slite-net-sqlcipher 1.7.335 (the package which uses the stored property)

- Affected Devices:
  - iOS 14 devices previously running iOS 13

**Comment by jamesmontemagno** [comment]
I would say the same thing as last time as I haven't seen this myself, but you can report a radar to apple as we store the credentials in keychain and that is all we do.

**Comment by mattleibow** [comment]
We are just using the native APIs, so this might be a bug in iOS.

I'll close this for now, and maybe if you can get a response from Apple then you can reopen.

**Comment by Lelelo1** [comment]
For me the stored values are never stored between uninstall/install of the app, iOS 14
