### ISSUE TITLE
[Bug] DeviceDisplay.MainDisplayInfo Not sure returns correct size

### ISSUE THREAD

**Issue by developer9969** [xamarin/Essentials#1466]
Hi all
Not sure if it 's a bug or not, or what we use to detect big or small device function below is flawed.

They way we handle small vs big devices is using the approach outlined here

https://devblogs.microsoft.com/xamarin/styling-for-multiple-device-resolutions/

In short we use the function below and load the respective style (e.g small or big)

`
	       const int smallWightResolution = 768;
		const int smallHeightResolution = 1280;

	public static bool IsASmallDevice()
	{
				// Get Metrics
				var mainDisplayInfo = DeviceDisplay.MainDisplayInfo;

				// Width (in pixels)
				var width = mainDisplayInfo.Width;

				// Height (in pixels)
				var height = mainDisplayInfo.Height;
				return (width <= smallWightResolution && height <= smallHeightResolution);
	}
`

However I have noticed that on some "old" android phones even though it detects being a "big" device in reality it should be a small one.
Could it be that DeviceDisplay.MainDisplayInfo does not actually return the real width and Height in pixel?

Not sure how to provide a repo as it happens on old android phones using (android 7 and android 9)

hope the above makes sense.

for android how can I do this natively to check if a problem with xamarin essentials or not

Any suggestions?

**Comment by jamesmontemagno** [comment]
It returns the pixel width/height reported by the device. https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.android.cs#L34

You will want to also incorporate the Density into the mix as that has influence over detecting the screen size of the device. 

for example:

```
var metrics= DeviceDisplay.MainDisplayInfo;
var minSize = Math.Min(metrics.Width, metrics.height);
                        var isWide = minSize * metrics.Density >= tabletCrossover;
                        currentIdiom = isWide ? DeviceIdiom.Tablet : DeviceIdiom.Phone;
```

Just depends what the device is returning and what the density of it is.

**Comment by developer9969** [comment]
Hi 
thank you for replying and your example.
I am not sure  what the formula is to incorporate density into the mix and apply your sample in my context.
I didnt cater for tablet as the app is phone only.

The question is how can I detect if is a smalldevice or not so that I can merge the correct style into the dictionary?
The assumption here was that anything less or equal than 768 x 1280 is small.

I am open to any suggestions!! It would be nice if essentials would have an opinionated view and have a method "IsSmallDevice"


		public static bool IsSmallDevice()
        { 
            //we don't support tablet so tablet don't apply.

            int smallWidthResolution = 768;
            int smallHeightResolution = 1280;
            double screenWidth;
            double screenHeight;
            bool isSmallDevice;
			
            var metrics = DeviceDisplay.MainDisplayInfo;
			
            switch (Xamarin.Forms.Device.RuntimePlatform)
            {
                case Xamarin.Forms.Device.Android:
                    //Android not sure how to sort of correctly detect if is a small device
                    screenWidth = (metrics.Width - 0.5f) / metrics.Density;
                    screenHeight = (metrics.Height - 0.5f) / metrics.Density;
                    isSmallDevice = "???????";
                    break;
                case Xamarin.Forms.Device.iOS:
                    //ios no changes 
                    isSmallDevice = metrics.Width <= smallWidthResolution
                                    && metrics.Height <= smallHeightResolution;
                    break;
            }

            return isSmallDevice;
        }

**Comment by mattleibow** [comment]
Just adding a link for an FYI for my future self:
https://developer.android.com/training/multiscreen/screensizes

![image](https://user-images.githubusercontent.com/1096616/100945897-dab25f00-350a-11eb-99b6-8f7c6158c7bb.png)

**Comment by jamesmontemagno** [comment]
I think best to reach out to the author of the blog and get insight as the API is working correct.
