### ISSUE TITLE
[Enhancement] implement FolderPicker

### ISSUE THREAD

**Issue by jp-weber** [xamarin/Essentials#1468]
## Summary
It would be nice if a FolderPicker would be added, as it was already done similarly with the FilePicker.
Relevant for the FolderPicker would be that the start folder can also be set for the respective platforms.

## Intended Use Case
I am currently writing an app that works on the basis of an encrypted data file (synchronised via WebDAV or a cloud storage client). In this context it is relevant that a file can be read (selected via FilePicker), but also a folder can be selected in which the file should be written (FolderPicker).

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.

Also, this is now part of the .NET MAUI Community Toolkit!
