### ISSUE TITLE
[Bug] 1.6.0-pre2 release PhoneDialer "FeatureNotSupportedException" on Android 11

### ISSUE THREAD

**Issue by shahbaaz90** [xamarin/Essentials#1469]
### Steps to Reproduce

1. invoke Xamarin.Essentials.PhoneDialer.Open("99-99999") on android 11 emulator/real device

### Expected Behavior
opens the dialer with the phone number entered

### Actual Behavior
getting a "FeatureNotSupportedException" on Android 11 devices. works fine on android 10 and lower

### Basic Information

- Version with issue: 1.6.0-pre2
- Last known good version: 1.5.3.2
- IDE: VS 2019 Mac
- Platform Target Frameworks: 
  - iOS:  14.0
  - Android: 11
  - UWP: none
- Android Support Library Version: latest
- Nuget Packages: 
- Affected Devices: devices with Android 11 OS

### Screenshots

![PhoneError](https://user-images.githubusercontent.com/9108018/97146024-fb0f3100-1788-11eb-9048-6e13cf182c6e.png)

**Comment by shahbaaz90** [comment]
update: I have just pulled in the code from 
https://github.com/xamarin/Essentials/blob/1.6.0/Xamarin.Essentials/PhoneDialer/PhoneDialer.android.cs

and ran it locally as part of my code base. and it seems to be running fine. could this be a nuget package or AndroidX issue ?

**Comment by jamesmontemagno** [comment]
You will need to add query when you target and compile against Android 11:

```
<queries>
  <intent>
    <action android:name="android.intent.action.DIAL" />
    <data android:scheme="tel"/>
  </intent>
</queries>
```

I am updating the docs. see: https://devblogs.microsoft.com/xamarin/android-11-package-visibility/

**Comment by mattleibow** [comment]
@jamesmontemagno thanks for this. I would have wondered around for a bit before I even thought of what changed.

**Comment by shahbaaz90** [comment]
@jamesmontemagno thanks a lot :) yea it was difficult to track down what was going wrong here.. this makes sense
