### ISSUE TITLE
[Enhancement] Generic types for Preferences

### ISSUE THREAD

**Issue by Brosten** [xamarin/Essentials#1471]
## Summary
Essentials.Preferences is great in all it's "simpleness". But, would it be possible to get a version supporting generics?

Behind the scenes, json conversion could be used to serialize/deserialize the values if needed.
I don't think I'm he only one, currently doing my own serialization into strings and using the string setting option for unsupported types. This is useful both for types like Guid, DateTimeOffset etc, that's currently not supported and for smaller custom classes in need of being saved. At the same time, the support for nullable values would be fixed. Today you'll need to use Contains and Remove for dealing with nullables. It works, but could be smoother.

## API Changes

```
Get<T>(string key)
Set<T>(string key, T value)
```

some examples
```
Properties.Get<Guid?>("myKey"); // Returning a Guid?
Properties.Get<MyCustomClass>("myOtherKey"); // Returning a MyCustomClass
```
Perhaps with optional default values...

```
Properties.Set<Guid?>("myKey", myGuid); 
Properties.Set<MyCustomClass>("myOtherKey", myCustomClass); 
```

## Intended Use Case
I use this helper code to get/set nullabe guids
```
      public static Guid? GetNullableGuid(string key)
      {
         if (Preferences.ContainsKey(key))
            return Guid.Parse(Preferences.Get(key, string.Empty));
         else
            return null;
      }

      public static void SetNullableGuid(string key, Guid? value)
      {
         if (value.HasValue)
            Preferences.Set(key, value.Value.ToString());
         else
            Preferences.Remove(key);
      }

```
With generics, I could use
```
      public static Guid? UserId
      {
         get => Preferences.Get<Guid?>("userId");
         set => Preferences.Set<Guid?>("userId", value);
      }
```

Same thing goes for storing small custom classes.

**Comment by jamesmontemagno** [comment]
Unfortunatelly the underlying systems do not support generic types and can cause serious issues with converting back and forth, which is why we do not recommend doing this. Storing such data in a database or cache system is the preferred method for complex data.

**Comment by jamesmontemagno** [comment]
I think the option of supporting nullables is different though and could be talked about, but really the default value is the same so removing it is the recommended path IMHO. 

Adding more I think just opens up a can of worms @mattleibow

**Comment by Brosten** [comment]
Thanks for a quick answer @jamesmontemagno. Keep up the good work everyone around XF!

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
