### ISSUE TITLE
[Bug] DisplayInfo.Density: documentation is incomplete

### ISSUE THREAD

**Issue by janusw** [xamarin/Essentials#1474]
https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.displayinfo.density simply says:

> Gets a value representing the screen density.

and

> **Property Value**
> Double
> The screen density.

No word about the unit or how to interpret this value at all.

Looking at the source code (https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/DeviceDisplay/DeviceDisplay.uwp.cs#L60) one can guess that the number represents multiples of 96 dpi, at least on UWP. No idea if it will be the same on all platforms (but I certainly hope so).

**Comment by janusw** [comment]
Hi Matt,
thanks for your quick reaction to this bug report. Your additions to the documentation are definitely an improvement, but they still leave some questions open for me ...

Do I understand correctly that the density value is a platform-dependent scaling factor? I was hoping it would give me a connection between the number of pixels and the corresponding physical size, but apparently it is platform-specific:
* for UWP (as mentioned above), it seems that density=1 corresponds to 96 dpi
* for Android (see https://developer.android.com/reference/android/util/DisplayMetrics#density), it seems that density=1 corresponds to 160 dpi
* for iOS (cf. https://developer.apple.com/documentation/uikit/uiscreen/1617836-scale) the documentation does not mention any physical sizes
* same for MacOS (https://developer.apple.com/documentation/appkit/nsscreen/1388385-backingscalefactor)

It would be great to have a platform-independent way of determining the physical density (e.g. dots per inch) of the screen. Is such a thing available in Xamarin.Essentials? If not, would it be feasible to add it?

**Comment by mattleibow** [comment]
Maybe open an issue so we can track that. I think that might need to be checked. I am not sure it all the platforms support that. Maybe it will just be a matter getting some constants.

As you say, I don't know about iOS as I never actually saw something like that.
