### ISSUE TITLE
[Bug] MediaPicker.PickPhotoAsync() always returns a null FileResult on iOS simulator

### ISSUE THREAD

**Issue by PloxsyBop** [xamarin/Essentials#1479]
### Description
When calling MediaPicker.PickPhotoAsync(), a null is always returned.

### Steps to Reproduce

1. Call the MediaPicker.PickPhotoAsync() method on the iOS simulator or
2. Use the sample app I uploaded which demonstrates this behaviour.

### Expected Behavior
The gallery is displayed so that an image can be picked, and then the fileResult is returned.

### Actual Behavior
The gallery starts to load, but just a white viewController displays, and then quickly disappears again before the method returns with null.

### Basic Information

- Version with issue: 1.6.0-pre2
- Last known good version: N/A (new feature in this version)
- IDE: Visual Studio 2019 16.7.6
- Platform Target Frameworks:
  - iOS:  14.1
- Nuget Packages: NETStandardLibrary 2.0.3; Xamarin.Essentials 1.6.0-pre2; Xamarin.Forms 4.8.0.1560
- Affected Devices: iOS simulator

### Reproduction Link
I have uploaded a zip of a sample that demonstrates the issue: [PhotoPicker.zip](https://github.com/xamarin/Essentials/files/5447309/PhotoPicker.zip)

**Comment by Alextorres950325** [comment]
1.6.0-pre2, iOS: 14.2, XF 4.8.0.1687 works fine

**Comment by mattleibow** [comment]
Is this working now? Was it just an issue in the older preview?

**Comment by mattleibow** [comment]
Closing this as my latest tests did not have this issue.

**Comment by Saccomani** [comment]
Please check this vídeo!

https://www.youtube.com/watch?v=_1j5IAwoLDM
