### ISSUE TITLE
[Bug] Using MediaPicker.CapturePhotoAsync(); Gets Error

### ISSUE THREAD

**Issue by ibrahimdarahem** [xamarin/Essentials#1481]
### Description
when using **MediaPicker.CapturePhotoAsync();** get error "Object reference not set to an instance of an object"

I got this error when testing on **Android**.  

### Steps to Reproduce
            var result = await MediaPicker.CapturePhotoAsync();
            var stream = await result.OpenReadAsync();
            imgDocImage.Source = ImageSource.FromStream(() => stream);
just when running first line after shot the photo on phone gets the error :  "Object reference not set to an instance of an object"
on the first line, I mean before get a value in "result".

Test on Xiaomi note 9 (Android 10)

1. 
2. 
3. 

### Basic Information

- Version with issue: 1.6.0 pre2
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  

- Android Support Library Version: 
- Nuget Packages: Xamarin.Essentials  1.6.0-pre2
- Affected Devices:   Xiaomi Redmi note 9   (Android 10)

**Comment by Sunnya93** [comment]
I have Same Bug. In my Galaxy Note 9..

**Comment by mchlkoval** [comment]
Likewise, for me I am using: 
- Xamarin.Essentials 1.6.0-pre2
- Xamarin.Forms 4.8.0.1560

On my OnePlus 5T (Android 10). After capturing a photo I get a shot of it with three options at the bottom: Retake, Approve, and Cancel. Clicking Retake or Cancel does what it should without any issues. However, clicking the check box for approval results in a null reference exception that I suspect is outside of my code's scope as it never hits my catch statement. 

I suspect that perhaps there is a missing handler or listener for that type of workflow? CaptureVideo works fine, but as I recall videos don't provide a preview of what you just took in order for you to approve/discard what you captured.

**Comment by leijae** [comment]
Same issue with:
Xamarin Essentials 1.6pre4
Android 11 API 30 
Pixel 2 x86_x64
XF 4.8
