### ISSUE TITLE
[Bug] Crash CapturePhotoAsync on real phones

### ISSUE THREAD

**Issue by zunjae** [xamarin/Essentials#1484]
### Description

After calling CapturePhotoAsync(), I receive a NPE on real devices (Galaxy S10 running Android 10). Unable to reproduce this on a virtual device (Pixel 2 R 11.0). This leads to a "Object reference not set to an instance of an object"

### Steps to Reproduce

var photo = await MediaPicker.CapturePhotoAsync();
await LoadPhotoAsync(photo);

Good thing to know: this issue does not happen on PickPhotoAsync

Issue is only reproducable on a real device such as a Galaxy S10

### Expected Behavior
No crashy

### Actual Behavior
It crashy

### Basic Information

- Version with issue: 1.6.0-pr.1480.1
- Last known good version: there's no such thing
- IDE: Visual Studio 2019 version 16.7.6
- Platform Target Frameworks: Android Q (10)
- Affected Devices: Galaxy S10

**Comment by fzany** [comment]
I have the exact same issue with the preview version 1.6.0-pre2.

**Comment by zunjae** [comment]
> I have the exact same issue with the preview version 1.6.0-pre2. 

There's a different GitHub issue here that explains how to get an early release version that fixes this issue. It worked for me

**Comment by fzany** [comment]
> > I have the exact same issue with the preview version 1.6.0-pre2.
> 
> There's a different GitHub issue here that explains how to get an early release version that fixes this issue. It worked for me

Help me with the link to the issue.

**Comment by fzany** [comment]
Thanks, @zunjae. I found the feed and the right version to use.

**Comment by MdAsaduzzaman01** [comment]
@fzany
> Thanks, @zunjae. I found the feed and the right version to use.

What version is the right?

**Comment by zunjae** [comment]
> @fzany
> 
> > Thanks, @zunjae. I found the feed and the right version to use.
> 
> 
> 
> What version is the right? 

The one that works for you. Keep trying!

**Comment by MdAsaduzzaman01** [comment]
> > @fzany
> > > Thanks, @zunjae. I found the feed and the right version to use.
> > 
> > 
> > What version is the right?
> 
> The one that works for you. Keep trying!

That means not sure which version is right for me. Am I right?
