### ISSUE TITLE
[Bug] Error Compiling Android Apps

### ISSUE THREAD

**Issue by sharpninja** [xamarin/Essentials#1486]
### Description
Error CS0234: The type or namespace name 'Content' does not exist in the namespace 'Win10.UI.FaceOff.Xamarin.Android' (are you missing an assembly reference?)

### Steps to Reproduce

1. Create a new Android Xamarin App in VS 2019 Community Preview
2. Build

### Expected Behavior

Successfully compile.

### Actual Behavior

```
1>------ Build started: Project: Win10.UI.FaceOff.Xamarin.Android, Configuration: Debug Any CPU ------
1>E:\GitHub\Win10UiFaceOff\Win10.UI.FaceOff.Xamarin.Android\MainActivity.cs(52,114,52,121): error CS0234: The type or namespace name 'Content' does not exist in the namespace 'Win10.UI.FaceOff.Xamarin.Android' (are you missing an assembly reference?)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

### Basic Information

- Version with issue: 1.5.3.2
- Last known good version: Unknown
- IDE: VS 2019 Preview Version 16.8.0 Preview 6.0
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: 
- Affected Devices:

### Reproduction Link

https://github.com/sharpninja/Win10UiFaceOff/tree/master/Win10.UI.FaceOff.Xamarin.Android

**Comment by jamesmontemagno** [comment]
This is because you ended your project with the word .Android. This causes an issue with the namespaces of Android, so it thinks your app is the Android namespace instead of the Android APIs. Recreate your project so it doesn't have Android try Droid.

**Comment by jamesmontemagno** [comment]
@jonathanpeppers is there anything in the IDE we can do to make sure this doesn't happen ^

**Comment by jonathanpeppers** [comment]
I tried with the `dotnet new` templates we are working on for .NET 6 here: https://github.com/xamarin/xamarin-android/pull/5348

> mkdir Foo.Android
> cd Foo.Android
> dotnet new android
> dotnet build

And it seems like it works fine at the moment, but these templates are really simple. I'll make sure we have a test where the name includes `.Android` -- so we can make sure this works going forward.
