### ISSUE TITLE
[Bug] Preferences.Clear() does not clear key

### ISSUE THREAD

**Issue by Cheesebaron** [xamarin/Essentials#1490]
# Description

`Preferences.Clear()` does not remove the value for a key.

### Steps to Reproduce

1. Save some value to a key: `Preferences.Set("herp", "derp")`
2. Retrieve value for key with: `Preferences.Get("herp", string.Empty)` - yields `"derp"` as value
3. Call `Preferences.Clear("herp")`
4. Retrieve value for key with: `Preferences.Get("herp", string.Empty)`

### Expected Behavior

The last `Get` call returns `string.Empty` as key was cleared.

### Actual Behavior

The last `Get` call in 4. still returns `"derp"`

### Basic Information

- Version with issue:
- Last known good version: dunno
- IDE: Rider
- Platform Target Frameworks: 
  - Android: 9.0
- Affected Devices:
 - Custom kiosk device

**Comment by Cheesebaron** [comment]
I guess it is not a bug, but rather by design. I could have just read the XML docs when I used it. However, the naming is not per se very clear.

I would probably have distinguished between `Clear(string key)` and a `ClearAll(string sharedName)` to control whether to keep keys with default value or to remove them.

**Comment by Ruddy2007** [comment]
@Cheesebaron Can you explain why this is not a bug and what Clear really does? I am a little confused by the docs and would love to know why it does not work the way you have said above.
