### ISSUE TITLE
DeviceInfo.DeviceType wrong when running on Android 11 Emulator Image

### ISSUE THREAD

**Issue by JMan7777** [xamarin/Essentials#1491]
### Steps to Reproduce

Run the following code inside an app which you debug inside the Android Emulator with an Android 11 image.

### Expected Behavior

DeviceInfo.DeviceType should report DeviceType.Virtual

### Actual Behavior

DeviceInfo.DeviceType reports DeviceType.Physical

### Version Information

Windows OS: 20H2 - Build 19042.572
Microsoft Visual Studio: Community 2019 Version 16.7.7
Android Emulator: 30.1.5
Emulator OS: R 11.0 - API 30 (x86_64)

**Comment by jpobst** [comment]
Looks like this is some API in Xamarin.Essentials?

https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.deviceinfo.devicetype

Transferring to Xamarin.Essentials repository.

**Comment by jamesmontemagno** [comment]
It is returning Virtual for me.

i created a new R x86_64 emlator.


Build.Hardware returns ranchu for me.

Can you run -
```
var isEmulator =
    (Build.Brand.StartsWith("generic", StringComparison.InvariantCulture) && Build.Device.StartsWith("generic", StringComparison.InvariantCulture)) ||
    Build.Fingerprint.StartsWith("generic", StringComparison.InvariantCulture) ||
    Build.Fingerprint.StartsWith("unknown", StringComparison.InvariantCulture) ||
    Build.Hardware.Contains("goldfish") ||
    Build.Hardware.Contains("ranchu") ||
    Build.Model.Contains("google_sdk") ||
    Build.Model.Contains("Emulator") ||
    Build.Model.Contains("Android SDK built for x86") ||
    Build.Manufacturer.Contains("Genymotion") ||
    Build.Manufacturer.Contains("VS Emulator") ||
    Build.Product.Contains("emulator") ||
    Build.Product.Contains("google_sdk") ||
    Build.Product.Contains("sdk") ||
    Build.Product.Contains("sdk_google") ||
    Build.Product.Contains("sdk_x86") ||
    Build.Product.Contains("simulator") ||
    Build.Product.Contains("vbox86p");
```

**Comment by JMan7777** [comment]
Hi,

I attach you a small test project (Test.zip) which I used. Maybe you can reproduce the error.

It reports to the console the DeviceType and the result from your code:

```
11-04 01:06:29.907 I/mono-stdout( 7001): DeviceType: Physical
11-04 01:06:29.918 I/mono-stdout( 7001): isEmulator: True
```

Additionally find attached my built output and my debug output, as well as the Android Image used.

Thx a lot.

**Built output:**

[built_output.txt](https://github.com/xamarin/Essentials/files/5484967/built_output.txt)

**Debug output:**

[debug_output.txt](https://github.com/xamarin/Essentials/files/5484969/debug_output.txt)

**Android image:**

![image](https://user-images.githubusercontent.com/39986400/98058183-09db9f00-1e7f-11eb-9cca-784e13816ebe.png)

**Test project:**

[Test.zip](https://github.com/xamarin/Essentials/files/5484946/Test.zip)

**Comment by jamesmontemagno** [comment]
Ah, yes this was fixed in 1.6.0-pre which if you upgrade to that you will be good to go :)

**Comment by JMan7777** [comment]
Thx a lot.

Will wait for the final 1.6.0 version to come out.

**Comment by sauravchaudhary94** [comment]
Again I am getting this issue, I want to know whether it is fixed or not? @jamesmontemagno
