### ISSUE TITLE
[Bug] App crashes on iOS 10 when the internal implementation attempts to set `AllowsMultipleSelection`

### ISSUE THREAD

**Issue by 1Cor125** [xamarin/Essentials#1492]
### Description
App crashes when calling `PickFileAsync` on iOS 10.

### Steps to Reproduce
1. Call `PickFileAsync(options)` on iOS 10.
2. App crashes with` UIDocumentPickerViewController.set_AllowsMultipleSelection (System.Boolean value)
SIGABRT: This API is not supported on this version of iOS`

### Expected Behavior
We should be wrapping [this line of code](https://github.com/xamarin/Essentials/blob/044c92dc18b44c5f37a0156c5de227a14a4317cd/Xamarin.Essentials/FilePicker/FilePicker.ios.cs#L32) in a version check but we are only checking the version at the beginning of the method when deciding whether to respect the `allowMultiple` parameter.

### Actual Behavior
We should be doing this:
```cs
if (Platform.HasOSVersion(11, 0))
    documentPicker.AllowsMultipleSelection = allowMultiple;
```
### Basic Information

- Version with issue: 1.6.0-pre2
- Platform Target Frameworks: 
  - iOS:  10.3.3 (any pre 11 version)

**Comment by mattleibow** [comment]
I think this was fixed in a different way:
https://github.com/xamarin/Essentials/blob/044c92dc18b44c5f37a0156c5de227a14a4317cd/Xamarin.Essentials/FilePicker/FilePicker.ios.cs#L16-L17

But, I think to be consistent, it should not throw and just allow single files to be picked.

**Comment by 1Cor125** [comment]
Thanks for the response @mattleibow. Yeah the trouble is even if allowMultiple is false we still attempt to set the property so even when the user correctly uses the API (only using PickFileAsync on iOS 10) it blows up.

**Comment by mattleibow** [comment]
Ah yeah. I didn't even notice that. Not very smart of us.
