### ISSUE TITLE
[Bug] iOS - MediaPicker.PickPhotoAsync() never returns if the user swipes down to dismiss the photo gallery

### ISSUE THREAD

**Issue by iupchris10** [xamarin/Essentials#1493]
There seems to be a bug in PickPhotoAsync(), in which the Task never returns a FileResult (or null) if the user swipes down to dismiss the gallery, rather than pressing the Cancel button. This can cause problems if the developer is expecting a result from the awaitable Task.

### Steps to Reproduce

1. Add code: await Xamarin.Essentials.MediaPicker.PickPhotoAsync()
2. Set a breakpoint on the line following await Xamarin.Essentials.MediaPicker.PickPhotoAsync().
3. Run your app
4. Invoke the code from step 1
5. Grab the top of the photo gallery with finger or cursor and pull down until it's gone.

### Expected Behavior

PickPhotoAsync should either return null, or throw a TaskCanceledException.

### Actual Behavior

The awaitable Task never returns anything. The breakpoint from step 2 is never hit. 

### Basic Information

- Version with issue: 1.6.0-pre2
- Last known good version:  n/a
- IDE:  Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS: 13.7
  - Android: n/a
  - UWP:  n/a
- Android Support Library Version: n/a
- Nuget Packages:
- Affected Devices: iPhone 11

### Reproduction Link

https://www.icloud.com/iclouddrive/0WlrNk8mArEp-uCJ_SnJpMkFA#PickPhotoAsyncIssue

**Comment by FelipeFC** [comment]
I have the same problem.
Does anyone have any solution?

**Comment by mattleibow** [comment]
@FelipeFC  I see @BjornVanslembrouck has a nice PR that I will merge as soon as CI is green. Then, it will appear in the preview feed: https://aka.ms/xamarin-essentials-ci/index.json
You can use that for testing and then I'll push it to NuGet if all goes well on your side.
