### ISSUE TITLE
[Bug] Share.RequestAsync does not open a Share Sheet on iOS 14.1/14.2 (may be more) on iPads

### ISSUE THREAD

**Issue by FIELDPOINT** [xamarin/Essentials#1496]
### Description
Share.RequestAsync does not open a Share Sheet on iOS 14.1/14.2 (may be more) on iPads. Works on iPhones.

### Steps to Reproduce

1. Call Share.RequestAsync
2. 
3. 

### Expected Behavior
Should open a share sheet but it does not. It seems like its trying to open something off screen though.
### Actual Behavior
No share sheet appears on the screen
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
Xamarin Forms: 4.6.0.847
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
Did you set the presentation source bounds -> https://docs.microsoft.com/en-us/xamarin/essentials/share?context=xamarin%2Fxamarin-forms&tabs=android#presentation-location

**Comment by FIELDPOINT** [comment]
Thanks @jamesmontemagno. That was it. Sorry that was my bad.
BTW big fan of channel 9 and your vids. Keep up the good work, it really makes a difference.
