### ISSUE TITLE
[Bug] CapturePhotoAsync shows video capture on UWP

### ISSUE THREAD

**Issue by cbs-cbt** [xamarin/Essentials#1504]
### Description
CapturePhotoAsync shows **video** capture on UWP

### Steps to Reproduce
1. Call `await MediaPicker.CapturePhotoAsync();` in your code, this show up video capture instead of photo capture on UWP

### Expected Behavior
Should show photo capture screen

### Actual Behavior
Should show video capture screen

### Basic Information
- Version with issue: 1.6.0-pre2
- Last known good version:none
- IDE:
- Platform Target Frameworks:
  - UWP: Windows 10, version 1903 (10.0; Build 18362)

### Correction
Please correct the line 44 of the file Essentials/Xamarin.Essentials/MediaPicker/MediaPicker.uwp.cs:
[https://github.com/xamarin/Essentials/blob/afb692d710a4240f109d032dd4ebc8c9b329802d/Xamarin.Essentials/MediaPicker/MediaPicker.uwp.cs#L44](url)
This should be:
`=> CaptureAsync(options, true);` and not `=> CaptureAsync(options, false);`

**Comment by mattleibow** [comment]
Thanks for reporting this issue. I fixed it and it will be in the next release as well as available in the preview feed as soon as CI is complete.
