### ISSUE TITLE
[Bug] iOS 14 Clipboard.HasText access warning with xamarin.essentials 1.6.0-pre3

### ISSUE THREAD

**Issue by Px7-941** [xamarin/Essentials#1510]
### Description
The new preview version of Xamarin.Essentials 1.6.0-pre3 with bugfix #1502 from bug report #1321 has a side effect.
The iOS warning is displayed again. 
### Steps to Reproduce

1. Use Xamarin.Essentials 1.6.0-pre3 nuget
2. Implement Clipboard.HasText in your project
3. e.g. copy text from the Safari App
4. run the app and access Clipboard.HasText

### Expected Behavior
The Clipboard.HasText property should return true and no iOS warning.

### Actual Behavior
An iOS 14 warning is shown.
### Basic Information

- Version with issue: 1.6.0-pre3
- Last known good version: 1.6.0-pre2
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  14 (tested on 14.2)
- Android Support Library Version: 
- Nuget Packages: 
- Affected Devices:

**Comment by mattleibow** [comment]
Just a note on the actual "warning" is the the tiny toast at the top with "<app-name pasted from <app-name>"?

**Comment by Px7-941** [comment]
@mattleibow Yes I meant this toast message.
