### ISSUE TITLE
Browser target window

### ISSUE THREAD

**Issue by mdbill** [xamarin/Essentials#1516]
### Description
Provide a way to do Browswer.OpenAsync over and over again and re-use the same tab instead of opening a new tab.  BrowserLaunchMode, BrowserLaunchOptions, BrowserLaunchFlags don't have anything to do that.
Like how HTML has <a Target="_self" (etc.)

Xamarin Forms app, but I've been working with UWP.

**Comment by jamesmontemagno** [comment]
That isn't a possibility as it launches an intent out to the system. You would need an embedded browser like the Xamarin.Forms control has.
