### ISSUE TITLE
[Bug][iOS] Getting Permission ContactsWrite and ContactsRead

### ISSUE THREAD

**Issue by dimonovdd** [xamarin/Essentials#1521]
### Description
Second permission request throws an ObjectDisposedException.
I think this error is not related to Essentials. Most likely, this happens in Xamarin.iOS
[ABAddressBook Dispose incorrectly.](https://github.com/xamarin/Essentials/blob/3f3b41b5d326ea389273888a314071fa39339229/Xamarin.Essentials/Permissions/Permissions.ios.cs#L118)

### Reproduction on this GIF 

![Запись-экрана-2020-11-16-в-00 28 25](https://user-images.githubusercontent.com/59065470/99197828-cc8fdf00-27a5-11eb-811b-6a75375a9093.gif)

**Comment by mattleibow** [comment]
The real reason: https://github.com/xamarin/xamarin-macios/issues/9580
