### ISSUE TITLE
[iOS] Add support for detecting whether the granted location is Precise

### ISSUE THREAD

**Issue by RomanNakonechnyi** [xamarin/Essentials#1523]
## Summary
Currently in Xamarin.Essentials there is no way to get info whether location is granted as Precise or Not

## API Changes
https://medium.com/@bnshah.dev/how-to-keep-the-app-location-ready-with-ios-14-permission-changes-7cea859a5fc2
there is more info about changes

## Intended Use Case
If you are developing a tracking app you need a precise location. For that reason it is crucial to know which location you are getting, precise or not.

**Comment by mattleibow** [comment]
Good issue. Thanks for the links and detail.

**Comment by jfversluis** [comment]
Fixed by #1739
