### ISSUE TITLE
Text to Speak using wrong Output on Iphone [Bug] 

### ISSUE THREAD

**Issue by SOliasS** [xamarin/Essentials#1533]
### Description
I m using the essential text to Speak. 
On Android everything works as expected.
But on iOS the Output is via the Phone Speaker and not the Musik/Normal Speaker...
So it behaves like a call and not like an media output.
This causes iOS to be not very loud and also stops music for example.
Is it possible to change the Output?
### Basic Information

- Version with issue:
  - iOS:  14.2
xamarin essentials 1.5.3.2

**Comment by SOliasS** [comment]
So it seems something in my app is changing my AudioSettings for iOS.
I had to add a Dependcy Service which sets the global Audiooptions for ios.
It would be a nice to have if this could be included in the essentials api....

The Solution:

` public void SetAudioSettings()
        {
            //https://developer.apple.com/documentation/avfoundation/avaudiosessioncategoryoptions
            NSError error = AVFoundation.AVAudioSession.SharedInstance().SetCategory(AVFoundation.AVAudioSessionCategory.PlayAndRecord, AVFoundation.AVAudioSessionCategoryOptions.DefaultToSpeaker);
            if (error == null)
            {
                //https://developer.apple.com/documentation/avfoundation/avaudiosession/mode
                if (AVFoundation.AVAudioSession.SharedInstance().SetMode(AVFoundation.AVAudioSession.ModeSpokenAudio, out error))
                {
                    if (AVFoundation.AVAudioSession.SharedInstance().OverrideOutputAudioPort(AVFoundation.AVAudioSessionPortOverride.Speaker, out error))
                    {
                        error = AVFoundation.AVAudioSession.SharedInstance().SetActive(true);

                        if (error != null)
                        {
                        }
                    }
                    else
                    {
                    }
                }
                else
                {
                }
            }
            else
            {
            }
        }

    }`

**Comment by mattleibow** [comment]
When do you run this code?

Is your app redirecting the audio to the phone speaker, and then you are trying to get the TTS to come over the normal speaker?

**Comment by SOliasS** [comment]
Atm i'm using the code before using the Feature, to be sure it's set to the right output all the time.

By default the audio seems to be set to the Phone and not the Media Playback(not by me).
 I'm using the LUI(Azure language) Nuget i think that might be the culprit.

**Comment by EmilAlipiev** [comment]
Good catch this needs to be included in essentials . Essentials works totally wrong
