### ISSUE TITLE
[Bug] iOS FilePicker.PickAsync never returns after picker is dismissed

### ISSUE THREAD

**Issue by 1Cor125** [xamarin/Essentials#1544]
## Description
`FilePicker.PickAsync` never returns if the document picker controller is dismissed using a method other than tapping the Cancel button. 

### Steps to Reproduce

1. Make a call to `PickAsync`
2. In the app, dismiss the document picker by swiping it down on the iPhone, or clicking outside the bounds of the document picker on iPad (do not tap the Cancel button).

### Expected Behavior

The method should return null.

### Actual Behavior

The method never returns (it never sets a value on the `TaskCompletionSource`).

### Basic Information

- Version with issue: 1.6.x versions
- Affected Devices: iPhone or iPad

**Comment by 1Cor125** [comment]
I see that `WasCancelled` is implemented. So I need to investigate this further. Perhaps something else is going wrong. Closing this.

**Comment by 1Cor125** [comment]
So using the Xamarin Essentials app the method never returns unless the picker is closed using the Cancel button. So this is a problem. I'm just not sure how to fix it. Will keep investigating to see if I can come up with a recommendation.

**Comment by mattleibow** [comment]
Is this still happening? @BjornVanslembrouck just fixed this in https://github.com/xamarin/Essentials/pull/1518

**Comment by 1Cor125** [comment]
Forgot to mention that this is on iOS 14.2

**Comment by 1Cor125** [comment]
I remember having to fix this on our own homemade file picker @mattleibow. I think what did it was handling the newer `DidPickDocumentAtUrls` and, of course, `WasCancelled` and that seemed to cover all the scenarios.

**Comment by 1Cor125** [comment]
Update @mattleibow I just tried my suggestion above locally and it did not work.

**Comment by BjornVanslembrouck** [comment]
@mattleibow, I fixed it on the `ImagePicker` not sure if it happens on the `FilePicker` as well.
I'll try and have a look this evening.

**Comment by BjornVanslembrouck** [comment]
@mattleibow, @1Cor125, I created a PR that should fix the issue: https://github.com/xamarin/Essentials/pull/1546.

Tested both the swiping down on iPhone and the clicking outside bounds on iPad and both return a canceled action now.

**Comment by 1Cor125** [comment]
This looks great! Thanks @BjornVanslembrouck and @mattleibow
