### ISSUE TITLE
[Enhancement] [Contacts] Adding  and Types

### ISSUE THREAD

**Issue by dimonovdd** [xamarin/Essentials#1545]
## Summary
This issue is a continuation of these pull requests:
#1349 
#1405 

we need to implement 
- adding contacts
- EmailType and PhoneType ( work, home, main, mobile ... )

[This and next comments](https://github.com/xamarin/Essentials/pull/1405#issuecomment-732298702) should be taken into account when making a decision

The previous implementation of types is saved in [this branch](https://github.com/dimonovdd/Essentials/tree/draftContactsTypes)

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
