### ISSUE TITLE
Xamarin Essentials Versioning in Documentation

### ISSUE THREAD

**Issue by xshiiiidev** [xamarin/Essentials#1552]
As a newbie to Xamarin.Forms I encountered frustrating documentation with Xamarin.Essentials because of the documentation.

I am testing features from the documentation literally copy pasted but it's not working.

Then I realized it's because the documentation is already for Xamarin.Essentials 1.6 even though the latest version of Xamarin.Essentials in the Nuget Package Manager is only Xamarin.Essentials 1.5.

I hope to add the version selection in the documentation so we know what we are working with specially with newbies like me.

Reference: https://github.com/MicrosoftDocs/xamarin-docs/issues/3162

**Comment by jfversluis** [comment]
I think (hope?) this is addressed by now long ago and hope your experience is better.
