### ISSUE TITLE
[Enhancement] Indicate selected number when picking a contact 

### ISSUE THREAD

**Issue by Brosten** [xamarin/Essentials#1559]
## Summary
I love the new and super easy to use Contact picker dialog. 
Xamarin.Essentials.Contacts.PickContactAsync()
However, since the contacts are listed with all their numbers "selectable" in the dialogue, the user get a feeling that he can select an individual number. And in my case, it's only the phone number I'm interested in. As it is now, I have to present a new list of numbers for the selected user.

## API Changes
Add some indication of wich phone number was selected

## Intended Use Case
- The user of my app needs to pick a number from his contact list in order to send a message/SMS from my app.
- User opens contact dialog
- The contact to be used actually have three phonenumbers registered, so he clicks on a specific number
- Now, the user expect the selected number to be used/set in my app, however, I need to present a new dialogue with the contacts three different numbers and let the user select again.

**Comment by Brosten** [comment]
I see now, that the iOS implementation looks different. On iOS the contacts are presented in a list without showing any individual numbers. In this case it makes more sense. So, this enhancment is related to how it looks on android.

**Comment by dimonovdd** [comment]
@pictos what do you think about this?

I just now noticed that the behaviour of the picker on android is different from other platforms (iOS, UWP, Tizen)
