### ISSUE TITLE
[Bug] UWP MediaPicker.PickPhotoAsync does not always open to Photos library 

### ISSUE THREAD

**Issue by 1Cor125** [xamarin/Essentials#1560]
### Description

In some circumstances, `MediaPicker.PickPhotoAsync` does not open to the Photos library on UWP.

### Steps to Reproduce

1. Using `FilePicker.PickFileAsync`, choose a file from the Downloads folder.
2. Make a call to `MediaPicker.PickPhotoAsync`.

### Expected Behavior

The call to `MediaPicker.PickPhotoAsync` should open to Photos.

### Actual Behavior

The file picking window opens to the Downloads folder.

### Basic Information

- Version with issue: 1.6.0-pre4
- Platform Target Frameworks: 
  - UWP:  17763

**Comment by mattleibow** [comment]
I know this is not what I read just now: https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.fileopenpicker.suggestedstartlocation?view=winrt-19041

> The SuggestedStartLocation is not always used as the start location for the file picker. To give the user a sense of consistency, the file picker remembers the last location that the user navigated to and will generally start at that location.

I'll look and see if there is a way to change this behaviour.

**Comment by mattleibow** [comment]
According to my searches, there doesn't seem to be a way. This is a "feature". I am not too happy but that is the only picker we have on UWP.

😭

**Comment by 1Cor125** [comment]
Thanks for the "helpful feature" Windows 🙄
