### ISSUE TITLE
[Bug] WebAuthenticator.AuthenticateAsync not closing Android browser

### ISSUE THREAD

**Issue by jsureke** [xamarin/Essentials#1569]
### Description
WebAuthenticator.AuthenticateAsync not closing Android browser
### Steps to Reproduce

1. Build out everything for using AuthenticateAsync.
2. Login using (in my case) Okta

### Expected Behavior
Login browser app should close.
### Actual Behavior
It does not close. I had to set the callback activity to LaunchMode.SingleTask instead of the documented SingleTop in order to get back to the calling application. Otherwise, it stayed behind the browser.
### Basic Information

- Version with issue: Xamarin.Essentials 1.5.3.2
- Last known good version: N/A
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android: Android 10 (Q) 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by mattleibow** [comment]
This was fixed in the 1.6 previews that you can check out on the preview feed: https://aka.ms/xamarin-essentials-ci/index.json or try out preview 4 on NuGet.org: https://www.nuget.org/packages/Xamarin.Essentials/1.6.0-pre4
