### ISSUE TITLE
[Bug] Unprecise UIColor conversion

### ISSUE THREAD

**Issue by tipa** [xamarin/Essentials#1572]
### Description
The precision of the color conversion for UIColor (and perhaps also for NSColor & other platforms) can be improved.

### Steps to Reproduce

1. Show `UIColorPickerViewController` and enter `Display P3 Hex Color : #663399`
2. Get UIColor object from `UIColorPickerViewController` & call `ToSystemColor` on it
3. Print Color as Hex string

### Expected Behavior
#663399

### Actual Behavior
#653299

This is because the CGColor has these components:
Red: 101.999986320734
Green: 50.9999969601631
Blue: 153.000021278858

With the current conversion, the values are rounded down:
https://github.com/xamarin/Essentials/blob/0dba844e8085f7cb36d62115b005620d541e0fbd/Xamarin.Essentials/Types/PlatformExtensions/ColorExtensions.ios.tvos.watchos.cs#L15

I think this would be a better conversion method:
 
```
return Color.FromArgb((int)Math.Round(alpha * 255), (int)Math.Round(red * 255), (int)Math.Round(green * 255), (int)Math.Round(blue * 255)); 
```

**Comment by jamesmontemagno** [comment]
Love it :)

**Comment by tipa** [comment]
Am I too picky? 😀
I just think when someone *really* wants to set their very favorite color for something, they would enter it as HEX and when returning to the color picker they expect the same HEX color to still be there

**Comment by jamesmontemagno** [comment]
I think you are correct, it should output the same numbers, and we should use Math.Round... the question is do you round up or down?

**Comment by tipa** [comment]
Not exactly sure what you mean. `Math.Round` rounds to nearest, so up or down depending on the number. So that `101.999986320734` would be rounded to `102` and not to `101`.
Or are you asking what should be done in a the case like `101.5`?

**Comment by tipa** [comment]
@jamesmontemagno created a PR in case this makes the change more likely to be merged :)

**Comment by jamesmontemagno** [comment]
I guess my question is what Midpoint rounding should we use? https://docs.microsoft.com/en-us/dotnet/api/system.math.round?view=net-5.0#System_Math_Round_System_Double_System_Int32_System_MidpointRounding_

**Comment by tipa** [comment]
In my PR I used the default Math.Round without specifying a Midpoint rounding. I think the default is using `AwayFromZero` which is what I would have used if I had to provide that parameter
