### ISSUE TITLE
[Bug] Contact Picker only returned a value the first time tested

### ISSUE THREAD

**Issue by jmichas** [xamarin/Essentials#1573]
### Description
I'm not sure this is a bug exactly but I had a lot of issues integrating the Contact picker into my XF project running on iOS.
I have an app using Prism and Unity as a container, I was testing on an actual device.
I first tried to use the static essentials Contacts in my view model command. The picker would open the first time I tried and when I selected a contact I would get a contact back and could use it as expected. The second time I tried (in the same debug session) the picker would open and when I selected a contact I would get no error/exception and my break point on the next line where I check my returned contact == null would never get hit. Somehow the returned contact was just swallowed up.

I tried to wrap the essentials call in a service and also tried running it using Device.InvokeOnMainThread. Nothing seemed to fix the problem of it only working the very first time I tested it, then it would not work. I was unable to get any debugging info to help.

Eventually I lifted the iOS relevant code from here and made my own ContactPickerService in my iOS project. I tweaked some stuff so I could get a usable phone type enum for work, mobile, home, etc. But the point is my version works perfectly. I didn't change any of the underpinnings of the Delegate, just massaged the Contact and ContactPhone into versions that worked better for me. So, I am just wondering whether the extensive use of static classes is the culprit here. I don't know, but it seems odd that the same code works perfectly as a non static typical service pattern.
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by pictos** [comment]
@jmichas can you attach a sample that reproduces your issue?

**Comment by dimonovdd** [comment]
@jmichas what essentials version are you using?

**Comment by dimonovdd** [comment]
@jmichas can you create a sample app?
Maybe you should also try  1.6.0-rc1.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/59065470/102749300-d6909900-4374-11eb-8f63-e3caa2cce099.png">

**Comment by jfversluis** [comment]
No response anymore, going to be optimistic and assume this was fixed!
