### ISSUE TITLE
[Enhancement] Enrich the WebAuthenticator API

### ISSUE THREAD

**Issue by jonsa** [xamarin/Essentials#1575]
## Summary
It would be nice if WebAuthenticator exposed an API to configure the underlying request being made. Or at the very least take a CancellationToken so the request can be aborted.

## API Changes
```C#
public static class WebAuthenticator
{
    public static Task<WebAuthenticatorResult> AuthenticateAsync(Uri url, Uri callbackUrl, Action<RequestOptions> requestOptions);
}

public class RequestOptions
{
    public int Timeout { get; set; }
    // ...
}
```

```C#
public static class WebAuthenticator
{
    public static Task<WebAuthenticatorResult> AuthenticateAsync(Uri url, Uri callbackUrl, CancellationToken cancellationToken);
}
```
## Intended Use Case
When you fire off a WebAuthenticator request you have pretty much zero control afterwards. In my case when the authentication endpoint is not responding, I have no means of cancelling the request but have to wait until the default timeout is hit.

**Comment by jfversluis** [comment]
Hey @jonsa thanks for the suggestion! Unfortunately, we won't be adding this for Xamarin.Essentials anymore. If this is still something that interest you, make sure to check out the .NET MAUI repo and open an issue there. Thanks!
