### ISSUE TITLE
Create route on map with multiple waypoints

### ISSUE THREAD

**Issue by sarthak1995-26** [xamarin/Essentials#1583]
It would be a nice if we could add multiple stops lat lng in between start lat lng and end lat lng and then the route will go from start point to end point intersecting all the in between stops.I thinks it's possible for GoogleMap intent on android but not sure iOS maps provide such kind of functionality.

Draw path between two location current it does take only one Position which draws a path from user current location to that position what if anyone want to draw a path between to position's with multiple waypoints in it on default map app. I know it's possible on android as I have achieved the same through Launcher api but found this for iOS 

https://stackoverflow.com/questions/43371045/how-to-show-route-in-apple-maps-with-multiple-points-in-ios

Not sure MapKit provides something :(

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
