### ISSUE TITLE
[Bug] WebAuthenticator - Android - Null Reference Exception WebAuthenticatorIntermediateActivity.android.cs

### ISSUE THREAD

**Issue by JohnGalt1717** [xamarin/Essentials#1586]
### Description

On Android SDK 30, with 1.6 pre 5 of Xamarin Essentials, on launch of the browser tabs page for login,  on line 24 of WebAuthenticatorIntermediateActivity.android.cs I get a null reference exception.  extras is null. savedInstanceState is null, and Intent.Extras is also null.

I have the activity setup per the docs (direct copy with my own callback_scheme)  The error is a very unhelpful "Null Reference Exception" message with 0 stack or anything. I had to add the actual Xamarin Essentials project from github to get it to fail on this.

### Steps to Reproduce

1.  Create a Xamarin Forms project 
2. Update Android to Target SDK 30 (not sure if this is required)
3.  Call the standard WebAuthenticator.AuthenticateAsync (I'm on local network calling into my dev machine that has the port opened and works fine for UWP)
4. The browser launches and THEN before you can type in your login the app crashes.

### Expected Behavior
Should go through like UWP does.

### Actual Behavior
Crash on browser launch for login and password.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - Android:  30
- Affected Devices: Pixel C emulator created by AVD Manager.

**Comment by mattleibow** [comment]
Can you test on an actual device? Does the sample in this repo work for you?

I can't seem to repro this with our sample. In fact, this should not happen. Intent should not be null as that was the intent used to launch the activity. Bot, not only that, the Extras should not be null because we _always_ add an extra to that intent to launch. That is how the browser is being launched... In fact, in order for the browser to be launched, it had to have loaded the extras and read the browser intent from there...

I tried on a device and the emulator and was not able to repro.

**Comment by JohnGalt1717** [comment]
I'm trying to find a real device but my emulator is a Pixel C emulator using SDK 30 created in the AVD Manager.

This is all I get: System.NullReferenceException
  Message=Object reference not set to an instance of an object.


Are you set to Android 30 as your target sdk?

I created a brand new emulator and in that case, because of no caching the error occurs when it comes back from the google chrome tabs.

**Comment by tipa** [comment]
Same problem here - tested on a physical Pixel 5.
I think it has something to do with targeting Android 30 and the privacy changes that came with it: https://developers.google.com/web/android/custom-tabs/implementation-guide
Adding this snippet to the AndroidManifest fixed the problem for me:
```
<queries>
    <intent>
        <action android:name="android.support.customtabs.action.CustomTabsService" />
    </intent>
</queries>
```

**Comment by tipa** [comment]
The team working on the MSAL lib is tracking a similar, related problem: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2139

**Comment by pablo-gasparinid** [comment]
I am able to reproduce it on a real device, I've tried on a Google Pixel running Android 10 with the android project targeting Android API Level 29.

**Comment by MorneZaayman** [comment]
I can confirm the above issue is present in Android API 30, but not in Android API 29. The solution for me was to add that intent to the queries node in the manifest file. The documentation should be updated to indicate that. I can make a PR for that a bit later when I get a chance.

Perhaps the code could also be updated to make developers aware of the issue - I noticed something similar when using the MediaPicker.CapturePhotoAsync API. The exception thrown there provides you with a link to the Android documentation explaining why this new snipped is required in the XML.

**Comment by maxal1917** [comment]
I tried to add <queries> manifest, but still see same errors in production logs. Didn't help. I tried to fix my bug #1667

**Comment by isayneigh** [comment]
Is this change released yet?  If not, why is this issue closed?  It doesn't seem like Xamarin.Essentials has a version beyond 1.6,1 in which this issue still persists.

**Comment by nziosys** [comment]
I have a same issue (same exception, probably same reason) when authenticating on android 6 with the other browser (called "internet" on the emulator). After installing chrome it works fine. I hope the [#1687](url) fixes it.

Any plans and infos on when the release of 1.6.2 will be?

**Comment by ckapatch** [comment]
I also ran into this same problem today with a user that had DuckDuckGo as their default browser. Once we switched over to Chrome the authentication ran through as expected.
