### ISSUE TITLE
[Bug] File picker not working with ios hot restart

### ISSUE THREAD

**Issue by marciosouzajunior** [xamarin/Essentials#1587]
### Description

When the app is being debugged with hot restart, the file picker does not work. It opens but nothing happens when file is picked.

### Steps to Reproduce

1. Debug the project with hot restart
2. Open a file picker via FilePicker.PickAsync
3. Pick a file

### Expected Behavior

PickAsync returns a FileResult representing the selected file.

### Actual Behavior

PickAsync does not return.

### Basic Information

- Version with issue: 1.6.0-pre5
- IDE: Microsoft Visual Studio Community 2019 Version 16.7.7
- Platform Target Frameworks:
  - iOS:  Xamarin.iOS SDK 14.2.0.12
- Nuget Packages: Xamarin.Essentials 1.6.0-pre5
- Affected Devices: iPhone 5s (iOS 12)

### Reproduction Link

[FilePickerTest.zip](https://github.com/xamarin/Essentials/files/5682482/FilePickerTest.zip)

**Comment by mattleibow** [comment]
I think I also noticed this when using the apple sign in.

Might be related to some entitlements?

**Comment by keerthinathganjam** [comment]
I am also facing the same problem, not able to select any file in the file picker when it popped up to select file window [clicking on the desired file dosen't do anything] . I tried in prelease versions and as well as latest rc1 version as well.

**Comment by jamesmontemagno** [comment]
Is this issue only with Hot Restart? Does it work fine without it? May just be a limitation.

**Comment by marciosouzajunior** [comment]
@jamesmontemagno it's been working fine on release build.

**Comment by jamesmontemagno** [comment]
Thanks! will close for now and will note on docs
