### ISSUE TITLE
[Bug] EmailAttachment filename extension results in a crash -> FeatureNotSupportedException

### ISSUE THREAD

**Issue by maexsp** [xamarin/Essentials#1591]
### Description
On iOS Xamarin.Essential returns FeatureNotSupportedException: 'Specified method is not supported.' if a file extension is used which is (probably) not known by the system. On some iPhones/iPads it can work but on some also not. 

E.g. if using Email.ComposeAsync(message) with an attached file "AppLogfile.bad" it always crashes with FeatureNotSupportedException. When using "AppLogfile.log" it crashes only on several devices. When using "AppLogfile.txt" it does not crash at all.

### Steps to Reproduce

1. run the following code to create a textfile/logfile with a special file extension:

                var message = new EmailMessage()
                {
                    To = { "email@gmail.com" },
                    Subject = "Testmail with attachment",
                    Body = "Test",
                };

                var logFile = "AppLogfile.bad";
                var file = Path.Combine(FileSystem.CacheDirectory, logFile);
                File.WriteAllText(file, "log file data");
                message.Attachments = new List<EmailAttachment>(new []{ new EmailAttachment(file) });
                
                await Email.ComposeAsync(message);

### Expected Behavior
Do not return exception. Just create a email with the attachements. It should be no mather if adding textfile or images or other custom files.

### Actual Behavior
Crash by throwing FeatureNotSupportedException: 'Specified method is not supported.' 

### Basic Information

- Version with issue:  Xamaing.Essential 1.5.3.2, Xamarin.Forms 4.8.0.1451 
- Last known good version: unknown
- IDE: VS2019 16.8.2
- Platform Target Frameworks: 
  - iOS:  Seeon on iOS 13.3, 14.1 and 14.2, 
- Nuget Packages: Xamaing.Essential 1.5.3.2, Xamarin.Forms 4.8.0.1451 
- Affected Devices: iPad, iPhone

### Reproduction Link
https://github.com/maexsp/XamarinFormAndroidIdiom

### Stacktrace

    Xamarin.Essentials
    FileBase.PlatformGetContentType (System.String extension)    Xamarin.Essentials
    FileBase.GetContentType ()    Xamarin.Essentials
    FileBase.get_ContentType ()    Xamarin.Essentials
    Email.ComposeWithMailCompose (Xamarin.Essentials.EmailMessage message)    Xamarin.Essentials
    Email.PlatformComposeAsync (Xamarin.Essentials.EmailMessage message)    Xamarin.Essentials
    Email.ComposeAsync (Xamarin.Essentials.EmailMessage message)    MyApp.Presentation.Services
    SystemService.ComposeEmail (System.String emailTo, System.String subject, System.String body, System.String[] attachmentFilePaths)

**Comment by mattleibow** [comment]
What happens if you set an explicit `ContentType`? For example `application/octet-stream`

**Comment by maexsp** [comment]
Hi @mattleibow. Thx for reply.
On latest 1.6 RC this is fixed. 
With the actual Xamaing.Essential 1.5.3.2 it also can be fixed by setting `ContentType` explicitly to `application/octet-stream`

**Comment by mattleibow** [comment]
Closing this as it was fixed in the latest versions.

Thanks for reporting.
