### ISSUE TITLE
[Bug] iOS: Launcher.OpenAsync() Bugs out

### ISSUE THREAD

**Issue by Edgaras91** [xamarin/Essentials#1592]
### Description
Using Xamarin.Forms, iOS device OpenAsync overlay that appears in iPhone bugs out.
Other apps do below without any issues.
File is  .xlsx format.
### Steps to Reproduce

1. Save file to iPhone using this:
```
            string path = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
            string filePath = Path.Combine(path, filename.xlsx);
            try
            {
                FileStream fileStream = File.Open(filePath, FileMode.Create);
                fileStream.Write(bytes);
                fileStream.Flush();
                fileStream.Close();
            }
```
2. Open File: 
`await Launcher.OpenAsync(new OpenFileRequest { File = new ReadOnlyFile(filePath) });`
3. Select "Save to Files"
4. Press Cancel
5. Select "Save to Files" again
6. It will bug out - not go in to "Save to Files", screen flash and stay where it is

### Expected Behavior
To be able to "Save to Files" when you go back and forth in the menu.
### Actual Behavior
Not able to "Save to Files" on 2nd attempt in the same overlay session
### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  14.2 
  - Android: 11.0 (N/A)
- Nuget Packages: 
Xamarin.Essentials. 1.6.0-pre2
Xamarin.Forms 4.8.0.1687

- Affected Devices:
Simulator and Physical, both iPhone 12 Pro Max (iOS 14.2)
### Screenshots
![image](https://user-images.githubusercontent.com/32236075/102375649-ab93f700-3fba-11eb-8dd8-e5fc2b161ded.png)

**Comment by dimonovdd** [comment]
I also encountered this problem

> File is .xlsx format.

this applies to files with different extensions

**Comment by dimonovdd** [comment]
this correctly work on iPhone 7 Plus with iOS 13.5

**Comment by dimonovdd** [comment]
@mattleibow I noticed that it works on ios 14, but the opening "save to files" dialog takes a very long time. But the second and next times the opening is fast.
it works faster on ios 13.

**Videos**:
1. [iOS 13.6](https://yadi.sk/i/gbH71xc__SV9UQ)
2. [ iOS 14.3](https://yadi.sk/i/V46BhVQbIeW94A)

**Comment by mattleibow** [comment]
Thanks for the PR.
