### ISSUE TITLE
[Bug/Question] [Android] What is the point of calling Platform.OnResume when using the Web Authenticator?

### ISSUE THREAD

**Issue by tipa** [xamarin/Essentials#1593]
### Description
Reading the docs for the web authenticator (https://docs.microsoft.com/de-de/xamarin/essentials/web-authenticator?tabs=android), it is mentioned that one should call `Xamarin.Essentials.Platform.OnResume`

![image](https://user-images.githubusercontent.com/2863198/102406216-8b7c2c00-3fea-11eb-879e-05f570aed523.png)

But when calling this method without parameter - like in the docs - the method does just nothing:
https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/Platform/Platform.android.cs#L103-L107
So what's the point of it? Outdated docs? The auth seems to work just fine without calling it

**Comment by jamesmontemagno** [comment]
Isn't needed, just for app actions. I probably copy/pasted it over wrong.

**Comment by mattleibow** [comment]
Fixed in https://github.com/MicrosoftDocs/xamarin-docs/pull/3199
