### ISSUE TITLE
[Bug] [Android] Email.ComposeAsync returns FeatureNotSupportedException if no EmailClient App available

### ISSUE THREAD

**Issue by maexsp** [xamarin/Essentials#1594]
### Description
On Android Xamarin.Essential Email.ComposeAsync returns FeatureNotSupportedException: 'Specified method is not supported.' if no email client app is available on the device to send an email. 

### Steps to Reproduce
1. Remove any email app from Android System and disable Gmail App within Android: Settings -> Apps -> Gmail "Deactivate"
2. Run the following code and exception FeatureNotSupportedException: 'Specified method is not supported.' is thrown:

                var message = new EmailMessage()
                {
                    To = { "email@gmail.com" },
                    Subject = "Testmail",
                    Body = "Test",
                };

                await Email.ComposeAsync(message);

### Expected Behavior
Return a specific exception like "NoEmailClientAvailableException". So App Developer can show custom message or choose an alternative way to handle this situation.

On iOS E.g. a default system message is already shown in this case:
![grafik](https://user-images.githubusercontent.com/15746917/102481395-f4eb5180-4061-11eb-8fbb-5c05c903271a.png)

### Actual Behavior
FeatureNotSupportedException: 'Specified method is not supported.' is thrown

### Basic Information

- Version with issue:  Xamaing.Essential 1.5.3.2, Xamarin.Forms 4.8.0.1451 
- Last known good version: unknown
- IDE: VS2019 16.8.2
- Platform Target Frameworks: 
  - iOS:  Seeon on iOS 13.3, 14.1 and 14.2, 
- Nuget Packages: Xamaing.Essential 1.5.3.2, Xamarin.Forms 4.8.0.1451 
- Affected Devices: iPad, iPhone

### Reproduction Link
Use this repo, but remove the email attachments code before: https://github.com/maexsp/XamarinFormAndroidIdiom

### Stacktrace
Xamarin.Essentials.FeatureNotSupportedException: Specified method is not supported.
Xamarin.Essentials Email.ComposeAsync (Xamarin.Essentials.EmailMessage message)

**Comment by LucaZiegler** [comment]
It's even not working on Android with Gmail installed.

**Comment by jamesmontemagno** [comment]
@LucaZiegler  you will need to add the required intent queries -> https://docs.microsoft.com/en-us/xamarin/essentials/email?context=xamarin%2Fxamarin-forms&tabs=android

If there is no email client installed that exception is thrown and expected. It is unfortunate that Apple doesn't have a working API now to detect correctly. So here unfortunately there isn't anything we can do here. 

I think this falls more inline with -> https://github.com/xamarin/Essentials/issues/77 as maybe having an API to detect if an email client is present would be beneficial.

Based on this, i am going to close.

**Comment by rajababusharma** [comment]
I am also getting the same issue in .NET Maui.
"Microsoft.Maui.ApplicationModel.FeatureNotSupportedException: Specified method is not supported
Below is my code:
 List<string> Recipients = new List<string>() { "sharmayogiraj5@gmail.com","nayanasharma7124@gmail.com" };
 try
 {
     var message = new EmailMessage
     {
         Subject = "Testin email default client",
         Body = "Testin email default client",
         To = Recipients,
         BodyFormat = EmailBodyFormat.PlainText
     };
     await Email.ComposeAsync(message);
 }
 catch (Exception ex)
 {
     var error = ex.ToString();
 }

**Comment by rajababusharma** [comment]
This but is fixed by adding below code in AndroidManifest file
<queries>
  <intent>
    <action android:name="android.intent.action.SENDTO" />
    <data android:scheme="mailto" />
  </intent>
</queries>
