### ISSUE TITLE
[Enhancement] Use PHPickerViewController for MediaPicker implementation on iOS 14

### ISSUE THREAD

**Issue by leonluc-dev** [xamarin/Essentials#1595]
iOS 14 introduced [PHPickerViewController](https://developer.apple.com/documentation/photokit/phpickerviewcontroller), which allows users to select photos and videos from their library without requiring any additional permissions.

Using this picker for `PickPhotoAsync` and `PickVideoAsync` is especially helpful on iOS 14 since it introduced the "select photos" permission dialog for use of the PhotoLibrary source of UIImagePickerController, which is ignored by the UIImagePickerController itself. This can lead to confusion for the users.

**Comment by AmrAlSayed0** [comment]
Already done #1475, still not merged.

**Comment by leonluc-dev** [comment]
I missed that one. Thanks for the heads up. 
I have closed this issue since it's basically a duplicate of #1402
