### ISSUE TITLE
[Enhancement] Support for Public Directories in Xamarin.Essentials File System Helpers

### ISSUE THREAD

**Issue by koddek** [xamarin/Essentials#1599]
## Summary
This is a very nice easy to use API, but it feels like something is missing.
Please add support for public directories eg:
* FileSystem.ImagesDirectory
* FileSystem.VideosDirectory
* FileSystem.AudioDirectory
* FileSystem.DownloadsDirectory

as it stands, there is no easy way of accessing these directories from Xamarin.Forms so it would be a welcomed addition to Xamarin.Essentials.

ps. The reason for the request is I am currently working on an app that needs to create a document in the downloads folder, that the user can edit with another app even after my app is uninstalled, and it is very difficult to accomplish in a cross-platform way.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
