### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by valerio13** [xamarin/Essentials#1602]
### Description
I'm executing my proyect in debug mode.
The error appears in Android.
After executed MediaPicker.CapturePhotoAsync() line the camera window is opend but my application stops (the Visual Studio stops the application execution).
After take the picture and press the camera application "ok" button it returns to mobile home window.

### Steps to Reproduce

1.  Execute in Visual Studio (Debug mode) the code line:

            `try`
            `{`
               `var photo = await MediaPicker.CapturePhotoAsync();`

2. The camera application is opened
3. The VS stops the execution but it doesn't execute the catch()
4. The camera reamains opened
5. After taken the picture the camera windows closed and the phone resturns to its home window.

### Expected Behavior
After photo picture taken it must continue my application execution.

### Actual Behavior
It stops the application execution.

### Basic Information

- Version with issue: Xamarin.Essentials 1.6.0
- Last known good version:
- IDE: Microsoft Visual Studio Community 2019 Version 16.8.3
Microsoft .NET Framework Version 4.8.03752
Xamarin   16.8.000.260 (d16-8@fd405a2)
- Platform Target Frameworks: 
  - Android:  Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e) 
- Android Support Library Version: 

- Nuget Packages:
Xamarin.Essentials 1.6.0

- Affected Devices:
Xiaomi Redmi Note 8T
MIUI Global 12.0.1
Android 10 QKQ1.200114.002

**Comment by mattleibow** [comment]
I tried to repro this on an Android 9 and 11 device, but couldn't get it to fail.

Make sure you have the permissions. Is there an exception?

**Comment by jamesmontemagno** [comment]
Going to close we need more information or a repro
