### ISSUE TITLE
Allow option to pick excel files 

### ISSUE THREAD

**Issue by mikkelAtVisma** [xamarin/Essentials#1604]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/main/SUBMITTING-ISSUES.md)

### Description
I am uncertain if this is a bug or a missing feature, but I am not able of picking excel files from the FilePicker plugin.

### Steps to Reproduce

1.  Define an option object that expects .xls or .xlsx files:

``            var supportedFileEndings = new[] {
                "application/xml", 
                "text/xml",
                "application/xlsx",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            };
``
2. Use the option object to pick files for xls
`            var fileTypes =
                new FilePickerFileType(new Dictionary<DevicePlatform, IEnumerable<string>>
                {
                    { DevicePlatform.iOS, supportedFileEndings}, // or general UTType values
                    { DevicePlatform.Android, supportedFileEndings },
                    { DevicePlatform.Tizen, supportedFileEndings },
                    { DevicePlatform.Unknown, supportedFileEndings },
                    { DevicePlatform.macOS, supportedFileEndings },
                    { DevicePlatform.tvOS, supportedFileEndings },
                    { DevicePlatform.watchOS, supportedFileEndings },
                    { DevicePlatform.UWP, supportedFileEndings },
                });
`

### Expected Behavior
I should be able of picking .xlsx files
### Actual Behavior
I am not capable of picking .xlsx files, they are grayed out

**Comment by mattleibow** [comment]
Which platform? Does it not work for any platform?

**Comment by dimonovdd** [comment]
@mattleibow @mikkelAtVisma everything works great. 

this code is suitable for getting docx
```csharp
{ DevicePlatform.iOS, new[] { "org.openxmlformats.wordprocessingml.document" } },
{ DevicePlatform.Android, new[] { "application/vnd.openxmlformats-officedocument.wordprocessingml.document" } }
```

**Comment by mikkelAtVisma** [comment]
> Which platform? Does it not work for any platform?

I've so far only been able of testing it on Android, where I had no success.

> @mattleibow @mikkelAtVisma everything works great.
> 
> this code is suitable for getting docx
> 
> ```cs
> { DevicePlatform.iOS, new[] { "org.openxmlformats.wordprocessingml.document" } },
> { DevicePlatform.Android, new[] { "application/vnd.openxmlformats-officedocument.wordprocessingml.document" } }
> ```

Hi domnovdd - I will have to close this then! Thanks for the insight. @dimonovdd is it possible for you to share an overview of file types for the platforms? I can't seem to find this.

Best,

**Comment by dimonovdd** [comment]
@mikkelAtVisma Hi. I don't have such a list, I just searched the google for each type for the platform

**Comment by mikkelAtVisma** [comment]
Found a list on “the google” myself! Thanks.

**Comment by freezersharp** [comment]
> Found a list on google myself! Thanks.

Share with the community.

**Comment by carlosgdelvalle** [comment]
For anyone looking for xlsx datatype: 

"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
