### ISSUE TITLE
[Bug] Connectivity.ConnectionProfiles contains "Wifi" even if disconnected / turned off on iOS

### ISSUE THREAD

**Issue by AndreasReitberger** [xamarin/Essentials#1613]
### Description
I'm using `bool WifiOn = Connectivity.ConnectionProfiles.Contains(ConnectionProfile.WiFi);` in the `ConnectivityChanged` event to detect if my mobile device is connected to the wifi or not.
However the bool WifiOn is true on my device, even if the Wifi is snoozed or completely turned off in the settings.
If I turn on the flight mode, it works and the wifi connection is detected as off.

I'm also setting the `bool WifiOn = Connectivity.ConnectionProfiles.Contains(ConnectionProfile.WiFi);` on startup of the app. But even with the wifi turned off this returns true at the app's startup.

### Steps to Reproduce

1. Install Xamarin.Forms 5.0.0.1829-pre6 & Xamarin.Essentials v1.6.0
2. Check `bool WifiOn = Connectivity.ConnectionProfiles.Contains(ConnectionProfile.WiFi);` on a real device
3. 

### Expected Behavior
The Wifi profile should not be included in the ConnectionProfiles if turned off or snoozed.

### Actual Behavior
The Wifi profile is included in the ConnectionProfiles even if the wifi is turned off or snoozed.
### Basic Information

- Version with issue: Xamarin.Essentials v1.6.0 / Xamarin.Forms 5.0.0.1829-pre6
- IDE: Visual Studio 19 Community
- Platform Target Frameworks:
  - iOS:  14.2
- Affected Devices: Only tested on Iphone 11

**Comment by demoh2019** [comment]
There is a solution?

**Comment by gemelo-hh** [comment]
Hi,

I have had the same issue with current stable Xamarin Forms 5.0.0.1874.

Will be glad to here from yours.

Kind regards

Thies

**Comment by jamesmontemagno** [comment]
What does `NetworkAccess` return?

**Comment by jamesmontemagno** [comment]
From what I can see NetworkReachability flags are returning IsWWAN. Will need to look deeper into it.

**Comment by gemelo-hh** [comment]
> What does `NetworkAccess` return?

NetworkAccess returns NetworkAccess.Internet

**Comment by gemelo-hh** [comment]
Now I tried to go back to XF 4.8.0.1821 and had the same issue.

**Comment by gemelo-hh** [comment]
> From what I can see NetworkReachability flags are returning IsWWAN. Will need to look deeper into it.

And thanks for looking deeper into it... :-)

**Comment by gemelo-hh** [comment]
btw: I tested your "old" https://github.com/jamesmontemagno/ConnectivityPlugin and that is working as expected...

**Comment by jamesmontemagno** [comment]
Interesting... I will look at the difference in code between the Connectivity Plugin and this one. Xamarin.Essentials and Xamarin.Forms are completely separate packages and are independent so that is why you see the same thing.

**Comment by jamesmontemagno** [comment]
@gemelo-hh  were you using 3.2.0 of the plugin or the 4.0 beta stuff?

**Comment by jamesmontemagno** [comment]
I figured it out ;)

**Comment by gemelo-hh** [comment]
> @gemelo-hh were you using 3.2.0 of the plugin or the 4.0 beta stuff?

I'm using 3.2.0...

**Comment by mattleibow** [comment]
@jamesmontemagno  I can't seem to repro this on my iPhone X with iOS 14.3...

On startup and in the event it has the correct values when wifi is off and off in the settings.

**Comment by janvdp** [comment]
fwiw just tested the preview2 build and wifi test seems to be working now. Thanks for the fix!

**Comment by mattleibow** [comment]
Thanks for the feedback!

**Comment by jamesmontemagno** [comment]
I did the same thing @mattleibow as my test phone has no sim and you have to have a sim to see the problem lol
