### ISSUE TITLE
[Bug] PhoneDialer.Open doesn't work on UWP Desktop

### ISSUE THREAD

**Issue by Almis90** [xamarin/Essentials#1615]
### Description
When I call PhoneDialer.Open it doesn't open anything nor it throws any exception.

### Steps to Reproduce

1. Just call PhoneDialer.Open("AnyNumberHere");

### Expected Behavior
It's obvious that you cannot dial on Windows Desktop but I was expecting to get same result with Launcher.TryOpenAsync("tel:AnyPhoneNumber") or an exception.

### Actual Behavior
Instead it just did nothing, didn't open any window neither throwed any exception.

### Basic Information

- Version with issue: 1.6.0
- Last known good version: None
- IDE: Microsoft Visual Studio Community 2019 Version 16.8.3
- Platform Target Frameworks: 
  - UWP:  Windows 10, version 1903 (10.0; Build 18362)

**Comment by jamesmontemagno** [comment]
We call the ShowPhoneCallUI so it would be up to this API to do something here.
`
 internal static bool IsSupported =>
             ApiInformation.IsTypePresent("Windows.ApplicationModel.Calls.PhoneCallManager");

        static void PlatformOpen(string number)
        {
            ValidateOpen(number);

            PhoneCallManager.ShowPhoneCallUI(number, string.Empty);
        }
```
