### ISSUE TITLE
[Bug] GetLocationAsync not awaiting correctly

### ISSUE THREAD

**Issue by sisaacks** [xamarin/Essentials#1617]
### Steps to Reproduce
NOTE:  Make sure you do not have location permissions yet
1. IsBusy = true;
2. GeolocationRequest request = new GeolocationRequest(GeolocationAccuracy.Best, TimeSpan.FromSeconds(5));
    var location = await Geolocation.GetLocationAsync(request);
3.  var test = IsBusy /*Somehow this is false now.....for some reason the call above is setting IsBusy to false*/

### Expected Behavior
I would expect the busy spinner to show while we waiting for location to return
### Actual Behavior
For some reason.....IsBusy is being set to false
### Basic Information
Here is the method...this happens on a button click...nothing else would be setting IsBusy to False.  This only happens if the permission has not yet been granted.  If the permission is granted already everything works perfectly.  But if I have to grant permission....when the permission is granted it does not seem to work correctly

internal async Task CheckLocationPermissionAndGetGeoLocation(bool isFromPopUp = false)
        {
            Plugin.Permissions.Abstractions.PermissionStatus permissionStatus = await PermissionCheck(Permission.Location);

            if (permissionStatus == Plugin.Permissions.Abstractions.PermissionStatus.Granted)
            {

                IsBusy = true;
                GeolocationRequest request = new GeolocationRequest(GeolocationAccuracy.Best, TimeSpan.FromSeconds(5));
                var location = await Geolocation.GetLocationAsync(request);
                if(location != null)
                {
                    var test = IsBusy;
                    await SaveGeolocation(location, isFromPopUp);
                    await SolveAndSend();
                    IsBusy = false;
                }
                else
                {
                    IsBusy = false;
                    PopUpUtility.ShowPopUp("Warning", "Latitude and Altitude could not be retrieved.");
                }

            }
            
        }

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by Jakar510** [comment]
I have the same issue occurring; however, when permission is granted, it never gives the location. I waited for 15 seconds, debug points before and after, and the after never triggered.

**Comment by sisaacks** [comment]
@Jakar510 I never did get a fix for this, what I had to do was remove the call on startup.  Then it just seems to work.

**Comment by Jakar510** [comment]
It worked after I remove the call on startup.

**Comment by jamesmontemagno** [comment]
Will close as it is not recommended to check permissions or make calls before app is fully started. and resolved for OP
