### ISSUE TITLE
MediaPicker Exif Orientation

### ISSUE THREAD

**Issue by Luckre** [xamarin/Essentials#1619]
## Summary
Please help us get the Exif Data like the AndroidX - exifinterface.

## API Changes
Will you please add to the FileResult properties the file Exif attributes. Especially the picture orientation.

## Intended Use Case
I tested it on my project on an old Samsung Galaxy S4 Android 5.0. It works perfectly, except all pictures are displayed in landscape. The reason that these phones save it in landscape mode and add to its metadata the orientation.
If you can add this as a property to the FileResult so I can rotate it. Because there is no way I can get these info.

Thank you

**Comment by prestanneth** [comment]
_Because there is no way I can get these info._

This doesn't work?

`using ExifInterface = AndroidX.ExifInterface.Media.ExifInterface;`

`  ExifInterface exif = new ExifInterface(filePath);`
` Orientation orientation = (Orientation)exif.GetAttributeInt(ExifInterface.TagOrientation, (int)Orientation.Undefined);`

then rotate, according to received orientation.

**Comment by archergod** [comment]
But that is for Andriod Only, how we handle it in iPhone ?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Essentials is now in maintenance mode while we transition it to .NET MAUI, this will not happen anymore for Xamarin.Essentials. We're only adding bugfixes and stability fixes at this point.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
