### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by broteam168** [xamarin/Essentials#1627]
### Description
I have met this issue when using xamarin.essential to use FilePicker.But when i only use this line code
FilePicker.PickAsync()
It said expexted FilePicker.FileResult in Xamarin.Essential.1.6
### Expected Behavior
I hope you can help me to sole this error
### Basic Information

- Version with issue:
- Last known good version:
- IDE:Visual studio pro 2019
- Platform Target Frameworks: 
  - Android: 9.0
- Xamarin.Essentials Packages:1.6
- Affected Devices:Android device (Samsung A10 device)

**Comment by jamesmontemagno** [comment]
Hey there, be sure to read through the docs: https://docs.microsoft.com/en-us/xamarin/essentials/file-picker?tabs=android I am not positive exactly what the issue is. Please follow the docs and open a new issue with a reproduction project if you continue to have an issue.
