### ISSUE TITLE
[Bug] Permissions CheckStatusAsync always returns 'Granted' on UWP

### ISSUE THREAD

**Issue by matthewskillington** [xamarin/Essentials#1629]
### Steps to Reproduce

1. Create a blank app and add essentials
2. Create a button or something to trigger a method and call `CheckStatusAsync<Permissions.Camera>();
3. Run the app on UWP and set a breakpoint to or log the result from the call

### Expected Behavior
The method would return the correct status.

### Actual Behavior
The method always returns 'Granted'

### Basic Information

- Version with issue: 1.6.0
- Last known good version: Unknown
- IDE: Visual Studio 2019
- Platform Target Framework
  - UWP:  
- Nuget Packages: Xamarin.Essentials
- Affected Devices: 

### Reproduction Link

[UWPPermissionsTest.zip](https://github.com/xamarin/Essentials/files/5795317/UWPPermissionsTest.zip)

**Comment by jamesmontemagno** [comment]
Yes, this is not supported -> https://docs.microsoft.com/en-us/xamarin/essentials/permissions?context=xamarin%2Fxamarin-forms&tabs=android#available-permissions there is no API on UWP to check this permission

**Comment by matthewskillington** [comment]
@jamesmontemagno. Cool, thanks for confirming
