### ISSUE TITLE
Unavailable files in FilePicker iOS

### ISSUE THREAD

**Issue by manuelrb98** [xamarin/Essentials#1633]
### Description
Good morning, 
I've implemented the FIlePicker in my app, it works perfectly on Android but on iOS every file is visible but unselectable. I already set `LSSupportsOpeningDocumentsInPlace` to `true`

### Steps to Reproduce

1. Create a Xamarin Forms app in Visual Studio 2019.
2. Create a button and implement the following code in code behind:

 ```
 private async void OpenFilePicker(object sender, EventArgs e)
        {

            var customFileType =
                new FilePickerFileType(new Dictionary<DevicePlatform, IEnumerable<string>>
                {
                    //Excel, Word, PDF
                    { DevicePlatform.iOS, new[] { "com.microsoft.excel.xls", "com.microsoft.word.doc", "LSItemContentTypes" } }, // or general UTType values
                    { DevicePlatform.Android, new[] { "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/pdf" } }, //MIME TYPE
                    
                });

            var result = await FilePicker.PickAsync(new PickOptions
            {
                FileTypes = customFileType,
                PickerTitle = "File Selection"
            });

            if (result != null)
            {
                if (File.Exists(result.FullPath))
                {
                    return;
                }
                else
                {
                    File.Copy(result.FullPath, Environment.GetFolderPath(Environment.SpecialFolder.Personal)); 
                    
                }


            }

        }
```
3. Set `LSSupportsOpeningDocumentsInPlace` to `true` in `info.plist`
4. Run App in iOS device with testflight.

### Expected Behavior
Opening of the iOS file system with the option of select files and copy them to the specified path
### Actual Behavior
Opening of the iOS file system with all files visible but unselectable.
### Basic Information

- Version with issue:
- Xamarin Forms: 5.0.0.1874
- Xamarin essentials: 1.60
- IDE: Visual Studio 2019

### Screenshots

![image](https://user-images.githubusercontent.com/30731465/104607570-f4d57600-564e-11eb-8d2d-1ec13c4f2517.png)

**Comment by dimonovdd** [comment]
it may be related to [issue 1604](https://github.com/xamarin/Essentials/issues/1604)
