### ISSUE TITLE
[Bug] [iOS] Exif and other metadata is missing when capturing photos with MediaPicker

### ISSUE THREAD

**Issue by IngweLand** [xamarin/Essentials#1638]
### Description
There is no EXIF and some other metadata included into file when capturing photos with MediaPicker

### Steps to Reproduce

1. Capture photo
2. Check metadata

### Expected Behavior

Metadata should be present

### Actual Behavior

Metadata is absent

### Basic Information

- Version with issue: 1.6.0
- Last known good version: none
- IDE: VS 16.8.4
- Platform Target Frameworks: 
  - iOS:  14.3
  
- Affected Devices: all

**Comment by jfversluis** [comment]
Thanks for the report! More on this and the background can be found in this issue #1514

TL;DR We won't be able to add this to Xamarin.Essentials anymore, you can either use the MediaGallery plugin or consider voting for adding it to the .NET MAUI Community Toolkit for the time being. Thanks!
