### ISSUE TITLE
[Enhancement] Implement all features of jamesmontemagno / MediaPlugin

### ISSUE THREAD

**Issue by groege** [xamarin/Essentials#1640]
## Summary
Before my company can migrate from https://github.com/jamesmontemagno/MediaPlugin we need some of the old features:
1. PickPhotosAsync: If you have to select multiple pictures, its a chore having to open the picker multiple times, so it should be possible to pick multiple pictures at once (#1410)
2. For picking photos & capturing photos at least these properties should be added:
- CompressionQuality(#1541), MaxWidthHeigth, SaveMetaData(#1638, #1619, #1630), RotateImage(#1562, #1556, #1514, #1669)
- when capturing a photo add the "SaveToAlbum" flag as well as the "Directory" where the picture should be saved when SaveToAlbum is selected (#1455, #1548, #1668)

## API Changes
Implement this similar to the jamesmontemagno/MediaPlugin:
Example 1:
```
var fileTask = MediaPicker.CapturePhotoAsync(new MediaPickerOptions
{
    AllowCropping = true,
    CompressionQuality = 50,
    MaxWidthHeight = 1024,
    Name = "test.jpg"
    SaveMetaData = true,
    RotateImage = true,
    SaveToAlbum = true
    Directory = "MyFolderInsideTheGallery",
});
```
Example 2:
```
var fileTask = MediaPicker.CapturePhotosAsync(new MediaPickerOptions
{
    AllowCropping = true,
    CompressionQuality = 50,
     MaxWidthHeight = 1024,
    Name = "test.jpg"
    SaveMetaData = true,
    RotateImage = true
}, new MediaMultiPickeOptions {
    MaximumImagesCount = 5,
    DoneButtonTitle ="Some localized text",
    AlbumSelectTitle ="Some localized text",
    BackButtonTitle = "Some localized text",
    LoadingTitle = "Some localized text",
    PhotoSelectTitle = "Some localized text",
});
```

The option to supply localized texts should be added, see #1657

Hope I'm not the only one hoping for these features ;)

If you are reading this and are waiting for these features as well, please put a thumbs up :thumbsup:.

**Comment by Brosten** [comment]
We are kind of blocked for the same reason. We'd love to have the new possibility to select multiple files from cameraroll, but can't really update yet.

**Comment by IngweLand** [comment]
For multi picker, they will have to use new API (on iOS). That's already somewhere in issues. However, it will support only iOS 14+. Be prepared for that.

**Comment by IngweLand** [comment]
Also, it's way better to create issues per single item. this will be more granular, and people can vote on them individually

**Comment by groege** [comment]
> Also, it's way better to create issues per single item. this will be more granular, and people can vote on them individually

We can link other requests here, but I think all features should be done because this lib is the replacement of jamesmontemagnos version... therefore it should have ALL its features...

**Comment by RhomGit** [comment]
I agree with being unable to migrate because of the issues raise in OP.

Item 1 issue is a duplicate and is discussed here: https://github.com/xamarin/Essentials/issues/1410

**Comment by groege** [comment]
Save to gallery
https://github.com/xamarin/Essentials/issues/1455

**Comment by groege** [comment]
#1455

**Comment by groege** [comment]
> For multi picker, they will have to use new API (on iOS). That's already somewhere in issues. However, it will support only iOS 14+. Be prepared for that.

I can live with that

**Comment by groege** [comment]
@jamesmontemagno @mattleibow 
Is there any info on what features are planned to be supported, not supported?

**Comment by IngweLand** [comment]
One of my biggest confusion here is what to do with options passed to media picker. Currently, we have single class `MediaPickerOptions`. There will be different options for picking and capturing media.

**Comment by groege** [comment]
I don't think we should be afraid of breaking changes here, since it shouldn't be too much work updating...
For those who need to switch from the Jamesmontemagno lib have to do this anyway...
For those already using Essentials I doubt they call the API many times in different places in their code so breaking changes should be a minor nuisance.

**Comment by LloydNicholson** [comment]
Is there any update on when this will be finished? Quite a critical feature. The only property accessible on MediaOptions is Title.

**Comment by lazmeister** [comment]
> Is there any update on when this will be finished? Quite a critical feature. The only property accessible on MediaOptions is Title.

Don't hold your breath, I still feel this push to MediaPicker was too fast without having a fully tested solution. It may take until later in the year to actually see some of these features. I have already decided to go to another framework from this lack of consistency.

**Comment by mmunchandersen** [comment]
Any update on this critical issue? What is everyone else doing? (apart from switching away from Xamarin)

**Comment by dimonovdd** [comment]
Folks, you can not only ask to add these functions, but also implement them yourself and make a pull request.
You can also help with tests and reviews already created PRs.

- [Captured file metadata](https://github.com/xamarin/Essentials/pull/1639)
- [Save To Gallery](https://github.com/xamarin/Essentials/pull/1628)

**Comment by GUOLDEV** [comment]
@dimonovdd do you mean implementing PickPhotosAsync is not going to be possible?

**Comment by dimonovdd** [comment]
@GUOLDEV
No, I'm saying that everyone can contribute to solving this issue.

**Comment by mmunchandersen** [comment]
@GUOLDEV FYI we migrated from MediaPligin to Essential, but faced an issue with incorrectly rotated images after IOS was upgraded to v14. We had to move back to MediaPligin once it supported IOS v14

**Comment by IngweLand** [comment]
> @GUOLDEV FYI we migrated from MediaPligin to Essential, but faced an issue with incorrectly rotated images after IOS was upgraded to v14. We had to move back to MediaPligin once it supported IOS v14

Incorrectly rotated images on iOS is basically a metadata issue, which I have fixed in https://github.com/xamarin/Essentials/pull/1639 However, I requested to postpone that PR until the specs for this issue are all set.

**Comment by bmacombe** [comment]
Here is a workaround for the iOS image rotation issue using FFImageLoading if it helps anyone.

```C#
// Capture the photo
var photo = await MediaPicker.CapturePhotoAsync();
if (photo == null)
	return;

// Use FFImageLoading to make it a reasonable size and other transformations
var t = ImageService.Instance.LoadStream(async c => await photo.OpenReadAsync());

// iOS doesn't rotate the image to match the device orientation, so we have to rotate it 90 degrees here
if (Device.RuntimePlatform == Device.iOS)
	t.Transform(new RotateTransformation(90));
	
// Get the transformed image as a PNG
using var imageStream = await t.AsPNGStreamAsync();
```

**Comment by Samoykin** [comment]
Hi. Does anyone used a plugin [Xamarin.MediaGallery]( https://github.com/dimonovdd/Xamarin.MediaGallery)?
It has multiple picking of photos and videos.
It's alfa version but pretty useful.

**Comment by lazmeister** [comment]
> Hi. Does anyone used a plugin [Xamarin.MediaGallery](https://github.com/dimonovdd/Xamarin.MediaGallery)?
> It has multiple picking of photos and videos.
> It's alfa version but pretty useful.

Yes! Someone actually doing the work of supporting the current plugin that is used in most likely thousands of users applications. Thanks for the link

**Comment by IeuanWalker** [comment]
Xamarin.essentials version is way too buggy to use, I'm migrating back to Media.Plugin for now

**Comment by Brosten** [comment]
@IeuanWalker: That's where I ended up as well... Well, never actually left Media.Plugin. But still hoping to see improvements in the Essentials version. Don't know which one is more abandoned right now...

**Comment by IeuanWalker** [comment]
@Brosten lol at least the one works for now

**Comment by lazmeister** [comment]
> @IeuanWalker: That's where I ended up as well... Well, never actually left Media.Plugin. But still hoping to see improvements in the Essentials version. Don't know which one is more abandoned right now...

don't hold your breath. Basically all available resources are now on .NET 6 and MAUI

**Comment by jfversluis** [comment]
> Basically all available resources are now on .NET 6 and MAUI. 

Nope, I'm here! And it looks like this is something that a lot of people are waiting for. No solid promises, but let me see what I can do. Hopefully you'll lend me a hand!

**Comment by dimonovdd** [comment]
@jfversluis Is there anything I can do to help? I'm really already going to add some features to my plugin. I really don't want to do it. But for now I have no other way

**Comment by jfversluis** [comment]
> 

Let's make sure we obsolete that plugin of yours ;) let's talk on Discord and see what we can do

**Comment by jfversluis** [comment]
Haha I know! It was a joke. I mean that we should add all the things to Essentials so that there is no reason for your plugin to exist anymore :)

**Comment by dimonovdd** [comment]
@jfversluis I want to do it more than you want

**Comment by Brosten** [comment]
Let me know if I can help with any testing etc.

When it comes to taking photo with camera, we have started to look at the camera view from Community toolkit. Mostly because some Samsung devices with low ram kills our app, while it's backgrounded by the camera app. 
Or... could this problem be solved, still letting us use Essentials version of taking a photo?

**Comment by michaldivis** [comment]
I'll be happy to help with the testing as well, this feature is critical for me.

**Comment by jfversluis** [comment]
Hey everyone, let's please centralize our conversation in this issue about all of this: #1514

**Comment by Raystorm7** [comment]
> 

Hi, if I use this code the image is cut and shrunk.
How can I avoid this behavior?

With the code:
![IMG_5811](https://user-images.githubusercontent.com/7420345/148777165-c7e50afd-5b24-4dad-9769-56e3b7fbd5b7.PNG)

Without the code:
![IMG_5810](https://user-images.githubusercontent.com/7420345/148777190-85f264d1-e5b1-4aad-a4d1-54a2060e165d.PNG)
