### ISSUE TITLE
[Bug] [Android] Request for LocationAlways permission is always denied since Android 11

### ISSUE THREAD

**Issue by cpraehaus** [xamarin/Essentials#1642]
### Steps to Reproduce

1. On Android 11 call ``await Permissions.RequestAsync<Permissions.LocationAlways>()`` 

### Expected Behavior
Android permission dialog is shown and ``PermissionStatus.Granted`` is returned if user accepts it.

### Actual Behavior
Android permission dialog is **NOT shown** and ``PermissionStatus.Denied`` is returned.

### Basic Information

Since Android 11 the system enforces that foreground location permissions and the permission for accessing location while in background are requested separately:
https://developer.android.com/about/versions/11/privacy/location#request-background-location-separately

As I can see this affects all Xamarin.Essentials versions.

If desired, I can prepare a PR for this issue.

### Screenshots
NA

### Reproduction Link
On request.

**Comment by PCabral90** [comment]
I have the same problem

**Comment by volinc** [comment]
I have the same issue... Any news?

**Comment by jamesmontemagno** [comment]
If you use LocationAlways and you are on Q you need to add

```csharp
Manifest.Permission.AccessBackgroundLocation
```

**Comment by jamesmontemagno** [comment]
I am updating the documentation now, but the code is all ready and set to handle this scenario.

https://github.com/xamarin/Essentials/issues/1142

**Comment by cpraehaus** [comment]
> I am updating the documentation now, but the code is all ready and set to handle this scenario.
> 
> #1142

So users of XE must be aware that request for ``LocationAlways`` might always be rejected on Android if not requesting ``LocationWhenInUse`` before? Wouldn't it be worth a thought to let XE handle this platform detail (which might change in the future again), i.e. as a user of XE I only request ``LocationAlways`` (since this is what I want) and XE internally requests them (foreground / background perms) separately so that Android is happy?

**Comment by rsbepvb** [comment]
Just checking to confirm no one has found a work around on this yet for Android 11.0/API 30 or higher other than asking a user to go to settings (and the App) and turn "Always Allow" on for the app (which is a big ask for the typical user).status = await Permissions.RequestAsync<Permissions.LocationAlways>(); does not open a dialog for that and I can't seem to find any way to do that.

**Comment by samir05051994** [comment]
hello @jamesmontemagno i have given below permission on android manifest still face the same issue (no permission popup is showing up)

<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
  <uses-feature android:name="android.hardware.location" android:required="false" />
  <uses-feature android:name="android.hardware.location.gps" android:required="false" />
  <uses-feature android:name="android.hardware.location.network" android:required="false" />
  
  but when I call 
  
  await new LocationAlways().RequestAsync();
  
  no popup by android is coming up.

**Comment by IliyanPopov** [comment]
I have hit the same problem on Android 11 device. Latest nuget versions installed.

calling await Permissions.RequestAsync<Permissions.LocationAlways>() always returns status: denied.

How I was able to fix it.
I have installed this package extra:
Xamarin.AndroidX.SwipeRefreshLayout

Initially 
Instead of calling Permissions.LocationAlways, I called 
Permissions.RequestAsync<Permissions.WhileInUse> => this correctly showed the pop-up.

After that when calling Permissions.RequestAsync<Permissions.LocationAlways>() 
The settings screen with location permission choice is automatically shown.

Cheers

**Comment by knumat** [comment]
In case anyone else runs across this issue in a search, it seems to be expected that on Android 11+ you need to request LocationWhenInUse first, followed by LocationAlways:
https://github.com/xamarin/Essentials/issues/1580#issuecomment-742691701

More info here:
https://developer.android.com/training/location/permissions#request-only-foreground

**Comment by bbcsolution** [comment]
after requesting permission ReadExternalStorage its still been denied, so how could i resolve it?
please give a solution.
Xamarin.Android
