### ISSUE TITLE
[Bug] Android Preferences data remains after removing and reinstalling the application

### ISSUE THREAD

**Issue by Alex-Dobrynin** [xamarin/Essentials#1647]
I have need to store username and some app settings using Xamarin.Essentials.Preferences. When I remove or reinstall my app, I can get those preferences and they will not be empty. reproduces only in android. I have OnePlus 6 and android 10. Also it reproduces on ondroid 8.1

**Comment by mattleibow** [comment]
This might help https://docs.microsoft.com/en-us/xamarin/essentials/preferences?tabs=ios#persistence

Basically, you can disable that feature

**Comment by jamesmontemagno** [comment]
That is correct :)
