### ISSUE TITLE
[Bug] Regular app launch opens as shortcut after using shortcut (Xamarin Essential App Action)

### ISSUE THREAD

**Issue by noormahdi** [xamarin/Essentials#1648]
### Description
Once the app actions (shortcuts) are used in android, regular app launch too starts as shortcut and displays deep linked data instead of main page.

Found this issue in Android, but I have not tested this in iOS

### Steps to Reproduce
1. Set up app actions on your XF application as described here https://docs.microsoft.com/en-us/xamarin/essentials/app-actions?context=xamarin%2Fandroid&tabs=android
2. Launch app normally and verify if main page is displayed
3. Close the app
4. Launch app via shortcut and verify if deep-linked page is displayed
5. Close the app
6. Launch app normally again and it displays deep-linked page instead of main page

### Expected Behavior
Main page must be displayed when app is launched normally and not via the shortcut at step 6 from the repro steps enlisted above

### Actual Behavior
Deep linked page is displayed instead of main page when app is launched normally at step 6 of the repro steps

### Basic Information
Versions:
XF: v5.0.0.1905
Xamarin Essentials: v1.6.0
Android Min API Level: 23
Android Target API Level: 29
Visual Studio 2019: v16.8.2

Nuget Packages:
App project:
Acr.UserDialogs Version="7.1.0.470"
Autofac Version="6.1.0"
Microsoft.AppCenter.Analytics Version="4.1.0" 
Microsoft.AppCenter.Crashes Version="4.1.0" 
Newtonsoft.Json Version="12.0.3" 
sqlite-net-sqlcipher Version="1.7.335" 
Xamarin.Forms Version="5.0.0.1905"
Xamarin.Essentials Version="1.6.0" 

Android project:
Acr.UserDialogs  <Version>7.1.0.470</Version>
Plugin.CurrentActivity  <Version>2.1.0.4</Version>
Xamarin.AndroidX.Legacy.Support.Core.Utils  <Version>1.0.0.6</Version>
Xamarin.Forms Version="5.0.0.1905"
Xamarin.Essentials Version="1.6.0"
Xamarin.Forms.AppLinks  <Version>5.0.0.1905</Version>
Xamarin.Forms.Visual.Material  <Version>5.0.0.1905</Version>

**Comment by mattleibow** [comment]
Are you able to reproduce this with the essentials sample app? I am trying here and it seems to be working.

Maybe you can attach a sample or a screen recording? When I use the shortcuts, the app launches fine the next time I use the main launcher.
