### ISSUE TITLE
[Bug] File Picker access files even after denying permissions

### ISSUE THREAD

**Issue by aniruthg** [xamarin/Essentials#1649]
### Description
File Picker permission check does not work. Denying permissions still access files

### Steps to Reproduce

1. Use FilePicker.PickAndShow
2. Install the app for the first time in device
3. Deny permissions and still the app have access to files 

### Expected Behavior
Deny permissions, should not have access to files

### Actual Behavior
Deny permissions, Have access to files.

### Basic Information

- Version with issue: 1.6.0-pre4, 1.6.0, 1.6.1-preview2
- Last known good version:
- IDE:
- Platform Target Frameworks: Android & iOS
  - iOS:  
  - Android: 10

**Comment by mattleibow** [comment]
Thanks for reporting! I'll fix that now.
