### ISSUE TITLE
[Enhancement] Platform formatting

### ISSUE THREAD

**Issue by leonluc-dev** [xamarin/Essentials#1650]
## Summary
Several platforms (iOS and Android for example) support non-standard app display language and region formatting combinations. (Fully separate selection on iOS and a few non-standard combinations on Android)

This separation allows apps to run in non standard locales. For example:
"en_JP" (English display language with Japanese region/formatting)
"de_US" (German display language with USA region/formatting)

The `CultureInfo` class doesn't seem to support these non standard locales out of the box. In Xamarin apps `CultureInfo.CurrentCulture` seems to default to the app display language. (For example, "en_JP" would map to "en-US". "de_US" would map to "de-DE"). Which means the user's region settings get ignored in formatting relying on `CultureInfo.CurrentCulture`

However, the native locale/formatting APIs (`SimpleDateFormatter`, `NSLocale`, `NSDateFormatter` etc.) do take these non-standard combinations (partially) into account during formatting.
Allowing these native APIs to be called from Xamarin apps through Essentials would make (something close to) the user's preferred format a bit easier to use.

## API Changes

Among other possibilities, several of the DateTime formatting methods could have a platform based variant (ex. `ToPlatformShortDateString`)

I've recently experimented with this in my own fork: https://github.com/leonluc-dev/Essentials/tree/LocalizationDates/Xamarin.Essentials/DateTimeFormatting

Using the extension methods defined in the fork in the following (iOS) example:
 ```
var dt = DateTime.Now;
Console.WriteLine($"CurrentCulture locale: {CultureInfo.CurrentCulture}");
Console.WriteLine($"CurrentCulture short datetime: {dt.ToShortDateString()} {dt.ToShortTimeString()}");
Console.WriteLine($"CurrentCulture long datetime: {dt.ToLongDateString()} {dt.ToLongTimeString()}");

Console.WriteLine($"Native locale: {NSLocale.CurrentLocale.LocaleIdentifier}");
Console.WriteLine($"Native short datetime: {dt.ToPlatformShortDateString()} {dt.ToPlatformShortTimeString()}");
Console.WriteLine($"Native long datetime: {dt.ToPlatformLongDateString()} {dt.ToPlatformLongTimeString()}");
```

Would result in the following output examples:

App display language: English
Device region setting: Japan

```
CurrentCulture locale: en-US
CurrentCulture short datetime: 1/21/2021 3:05 PM
CurrentCulture long datetime: Thursday, January 21, 2021 3:05:56 PM

Native locale: en_JP
Native short datetime: 2021/01/21 15:05
Native long datetime: January 21, 2021 15:05:56
```

App display language: German
Device region setting: United States

```
CurrentCulture locale: de-DE
CurrentCulture short datetime: 21.01.2021 15:20
CurrentCulture long datetime: Donnerstag, 21. Januar 2021 15:20:53

Native locale: de_US
Native short datetime: 1/21/21 3:20 PM
Native long datetime: 21. Januar 2021 3:20:53 PM
```

While not perfect, the native formatting is more accurate to what someone with those regional settings would expect.

## Intended Use Case

This kind of API would allow developers to easily use native formatting options in Xamarin apps. This allows them to present the user with date/time formatting (or potentially stuff like number and currency formatting) based on the user's region settings rather than the app display language.

**Comment by mattleibow** [comment]
I had a look and this might be something worth adding. Not sure if it is worth returning the actual locale...

Also, what other things need converting? You have dates and you also mentioned currency. Might be worth seeing if there was maybe a way to create some sort of Localization/Internationalization type that has these members...

**Comment by leonluc-dev** [comment]
I don't think the locale identifier itself needs to be exposed either.

On iOS, MacOS, TV OS, Android, UWP and Tizen the region setting seems to commonly handle:

-Datetime formatting. (Handled through [NSDateFormatter](https://developer.apple.com/documentation/foundation/nsdateformatter) on iOS and [DateFormat](https://developer.android.com/reference/java/text/DateFormat) on Android).
-Number (specifically decimal, percentage and currency) formatting (Handled through [NSNumberFormatter](https://developer.apple.com/documentation/foundation/nsnumberformatter) on iOS and [DecimalFormat](https://developer.android.com/reference/java/text/DecimalFormat) on Android).

This includes both formatting and parsing of these values.
Some platforms support more out of the box localized formatting types (such as fractions on Android and ordinals on iOS/MacOS) but since they aren't available on all platforms, I reckon they aren't a good fit for a Xamarin.Essentials API.

Potential other options for a localization/internationalization type (instead of just formatting) could include:

-Measurement system. Using [NSLocale.usesMetricSystem](https://developer.apple.com/documentation/foundation/nslocale/key/1410780-usesmetricsystem) and [LocaleData.getMeasurementSystem](https://developer.android.com/reference/android/icu/util/LocaleData#getMeasurementSystem(android.icu.util.ULocale)). Although this would require API Level 28 on Android.

**Comment by jamesmontemagno** [comment]
I sort of want to avoid these as the test matrix is crazy and really should be a core .NET experience and return the same things. Mono and .NET updates would be required here I think.

**Comment by jamesmontemagno** [comment]
Would be worth running by @terrajobst perhaps.

**Comment by terrajobst** [comment]
Not sure I fully understand. My understanding is that `CurrentUICulture` is the display language we use for looking up resource strings and `CurrentCulture`, which we use for formatting, so .NET generally supports the separation. However, it's possible that the way we integrate with the OS doesn't preserve the behavior. @tarekgh is the expert here.

**Comment by leonluc-dev** [comment]
After reading @jamesmontemagno and @terrajobst's comments I looked around for similar Mono and .NET related issues a bit and it seems to be a Mono issue rather than a disperancy between .NET and native localization.
The issue seemingly involves the mapping of native culture settings (combined to one locale identifier on iOS, Android and MacOS) to the .NET CurrentCulture/CurrentUICulture split: https://github.com/mono/mono/issues/16827

Should that Mono mapping issue be fixed in the future it would render the proposed API pretty much obsolete.

**Comment by leonluc-dev** [comment]
Since this request is basically a workaround for a mono bug rather than a proper feature, I have closed it.
