### ISSUE TITLE
[Bug] FilePicker.PickAsync always returns null on the POCO F2 Pro

### ISSUE THREAD

**Issue by josesimas** [xamarin/Essentials#1654]
### Description
Calling FilePicker.PickAsync or FilePicker.PickMultipleAsync returns null for all types of files on the POCO F2 Pro. It works correctly on other Android phones (LG and Samsung phones tested).

This used to work on this phone and stopped working, I suspect, after the phone updated itself (I did not monitor this). Since this uses MIUI this bug may affect other phones.

### Steps to Reproduce
1. Create a new Xamarin Forms project, update all nugets to latest, change Android Target Framework to 10 or 11, rebuild solution.
2. Add a button with the following code on clicked: var fp = await FilePicker.PickAsync();
3. Set a breakpoint on the line above and debug the app. Press the button

### Expected Behavior
fp contains FileResult object

### Actual Behavior
fp is null

### Basic Information
- Version with issue: 1.6.1, 1.6.0
- Last known good version: ?
- IDE: VS2019, 16.8.4
- Platform Target Frameworks: Android 10 and 11 tested
- Nuget Packages: Xamarin.Essentials
- Affected Devices: POCO F2 PRO, MIUI version (for POCO) 12.2.4 Stable, 12.2.4.0 (RJKEUXM), Android version 11 RKQ1.200826.002

### Reproduction Link

Simple project duplicating the issue attached
[PicketTest.zip](https://github.com/xamarin/Essentials/files/5873100/PicketTest.zip)

**Comment by josesimas** [comment]
I found the solution to this and this is not a Xamarin Essentials bug. On the Poco phone (and other MIUI phones, I suspect), in the Developer Options there is the option "Turn on MIUI optimisation" which is on by default. If you turn it off then the above "bug" manifests itself. The reason why the FilePicker stops working is because any access to disk outside the apps private space throws an access denied exception under these conditions.
The reason you may want to turn off this option for development is that it shows pop ups if you app has NFC permissions and does not save the "don't bother me again" answer. I am going to close this report.

Apparently though, the FilePicker is silencing the exception and I only found out the solution because of unrelated code that is accessing the disk without the FilePicker. This should be changed.

**Comment by petthreer** [comment]
Thanks still relevant. I probably would never have found a solution. In my case, there is a little catch anyway. If I remove app from phone it is not possible to build it back to device. So I have to turn the optimisation off to install app after installation turn the optimisation on and media picker works again. Anyway thanks
