### ISSUE TITLE
Partial Screenshots

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#1655]
Hi,

Please add an option for partial screenshots..

Thanks,
Jassim

**Comment by mattleibow** [comment]
What do you mean "partial"? Just a view? An arbitrary rectangle?

**Comment by jrahma** [comment]
I mean select a part of the screen, like a specific StackLayout

**Comment by mattleibow** [comment]
This might help for now: https://twitter.com/dimonovdd/status/1353045802265010176?s=20

https://github.com/dimonovdd/ImageFromXamarinUI

Once the essentials and forms repos unite, then we can have a crossover episode of this feature.

**Comment by jfversluis** [comment]
Unfortunately this won't be happening for Xamarin.Essentials anymore!
