### ISSUE TITLE
[Android][MediaPicker] behaves like FilePicker

### ISSUE THREAD

**Issue by dimonovdd** [xamarin/Essentials#1663]
### Description
When using the MediaPicker, a file manager opens immediately and we can't select a gallery
I think this behavior is happening precisely because of [this line of code](https://github.com/xamarin/Essentials/blob/b0fc1bbb7e1d6f450fe3b18e7d9970b628074479/Xamarin.Essentials/MediaPicker/MediaPicker.android.cs#L27). This change was made in [this commit](https://github.com/xamarin/Essentials/commit/efce8e5bb4c5eabb98310e0a529b3defd9f84506#)
I think @Redth changed it for a reason, and maybe we should just leave it at that.

|______________| Actual Behavior | Expected Behavior |______________|
|:----------------:|:----------------:|:------------------:|:----------------:|
||![Actual](https://user-images.githubusercontent.com/59065470/106187665-f6f31500-61b6-11eb-9c10-9b72f5a4ad51.mp4)|![Expected](https://user-images.githubusercontent.com/59065470/106189737-bb0d7f00-61b9-11eb-977f-095df6fd44c2.mp4)||

**Comment by mattleibow** [comment]
Maybe we are just missing the logic to show the chooser.

**Comment by dimonovdd** [comment]
I think I understand why it was done this way. 
https://github.com/dimonovdd/Xamarin.MediaGallery/pull/5
