### ISSUE TITLE
SecureStorage data isn't persistent when a Json formatted string is storaged 

### ISSUE THREAD

**Issue by kado** [xamarin/Essentials#1664]
I'm working on project and I spent one day struggling with this one. I successfully stored a json string from serialized relative small 
object: "{\"\Name"\:"\XXXXXXXX"\ , "\Password"\:"XXXXXXX", "\LicensePlate"\:"\XXXAAA"\ }"

When app is running I can successfully store and retrieve the data. When application ends and starts again, SecureStorage.GetAsync is returning null for that particular key.

**Comment by jamesmontemagno** [comment]
What platform are you having this issue on?

It is possible on Android that if you are debugging that data is not stored between sessions. So when you say it is working when running it is probably working. I would recommend launching without debugging and testing it out.

**Comment by kado** [comment]
Thanks for the reply. The platform is Android, I'm going to try your recommendation, but when I stored simple strings they stay persist even on debug.

**Comment by jamesmontemagno** [comment]
I'll give it a try too

**Comment by jamesmontemagno** [comment]
I have tested this out and can not reproduce this in our sample app.
