### ISSUE TITLE
[Enhancement] Store Image to the Photo Gallery

### ISSUE THREAD

**Issue by fdmomtaz** [xamarin/Essentials#1668]
## Summary
Just like the Media Picker let's the user pick an image, there should be a way for the app to store an image to the user's photo gallery.

## API Changes
The File System Helpers can be extended in the following ways to implement this feature.
`public static string FileSystem.PhotoGallery {get;}`

Another way to handle this enhancement is to create a new feature module.
`public static System.Threading.Tasks.Task<Bool> MediaStore.StorePhotoAsync(System.IO.Stream PhotoStream)`

## Intended Use Case
A photo editing app can be a possible use case.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Essentials is now in maintenance mode, this will not happen anymore for Xamarin.Essentials. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
