### ISSUE TITLE
Capture Image Rotate

### ISSUE THREAD

**Issue by LumiProj** [xamarin/Essentials#1669]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/main/SUBMITTING-ISSUES.md)

### Steps to Reproduce

1. When I capture image it rotates automatically.
2. 
3. 

### Expected Behavior
Image capture with correct orientation.
### Actual Behavior
 Image rotates automatically.
### Basic Information

- Version with issue: Latest
- Last known good version:
- IDE: Mac Visual Studio
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by groege** [comment]
Another duplicate, check the referenced Issue, there you will find references to others

**Comment by jfversluis** [comment]
As pointed out, duplicate :)
