### ISSUE TITLE
Audit cases of nested classes

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Essentials#167]
We should be consistent with nested vs not-nested classes.

This is very "person preference" and doesn't appear to have any real pros/cons, but, consistency should be maintained.

**Comment by mattleibow** [comment]
Moved all classes out of the nest.

**Comment by jamesmontemagno** [comment]
For those how do we access them? DeviceInfo.Platforms.Android or "Platforms.Android"?

I think DeviceInfo.Platforms.Android is correct, which would mean static is good. I need to update docs if so. This should be documented somewhere in Wiki of when we nest vs not nest

**Comment by mattleibow** [comment]
Currently it is `DeviceInfo.Platforms.Android`.

**Comment by jamesmontemagno** [comment]
Hmmmmmmmmmmmmmmmm.........

Xamarin.Forms has it in "Device.Android" I think....@redth?

**Comment by Redth** [comment]
I seem to recall not wanting to 'clash' with Forms either... I personally always thought the change to Forms was confusing, I quite like DeviceInfo.Platforms.Android

**Comment by jamesmontemagno** [comment]
let's keep it then. Devs can always do a using static
