### ISSUE TITLE
Determine Airplane mode on Xamarin.Native (not Forms) project

### ISSUE THREAD

**Issue by GreatSummit** [xamarin/Essentials#1670]
Hi,

Connectivity returns NetworkAccess.Internet on airplane mode on both iOS and Android.
(Xamarin.iOS/Android)

Could you fix this issue as soon as possible?

Thanks.

**Comment by GreatSummit** [comment]
public static bool IsOnline()
{
            return 
                Xamarin.Essentials.Connectivity.NetworkAccess != Xamarin.Essentials.NetworkAccess.None &&
                Xamarin.Essentials.Connectivity.NetworkAccess != Xamarin.Essentials.NetworkAccess.Unknown;
}

This is my code for checking network connections.
But Xamarin.Essentials.Connectivity.NetworkAccess returns always Xamarin.Essentials.Connectivity.NetworkAccess.Internet on Airplane mode.

Hopefully, be fixed soon.

Thanks.

**Comment by jamesmontemagno** [comment]
Mine returns None on both iOS and Android.

**Comment by nickpeppers** [comment]
> Mine returns None on both iOS and Android.

@jamesmontemagno I'm seeing something similar at least on Android 10 using my Moto G Stylus. It behaves as expected using an Android 10 simulator but on my device, it always returns `NetworkAccess.Internet` when switched to airplane mode.

**Comment by GreatSummit** [comment]
I am using v1.6.1
![image](https://user-images.githubusercontent.com/29710877/108318322-99bd1300-71fa-11eb-887c-93354d94771e.png)

And I tested on many real devices. Unfortunately never working on Airplane mode.

![image](https://user-images.githubusercontent.com/29710877/108318471-da1c9100-71fa-11eb-8d7a-55b8c717c843.png)

So, I am depending on manual checking for airplane mode on droid. but iOS does not support the way to detect airplane mode, Hence, I am using the basic way to request HTTP to google.com...
Reachability package also not working for airplane mode.
I think Xamarin.Essential package is the best but it has a disadvantage for airplane mode.

**Comment by GreatSummit** [comment]
A question.
I am using Xamarin.Native not Forms.
Did you try to test on Xamarin.Native project?

**Comment by nickpeppers** [comment]
> A question.
> I am using Xamarin.Native not Forms.
> Did you try to test on Xamarin.Native project?

Our project is Xamarin.Forms but for this case shouldn't really matter. Also, we're not trying to necessarily detect if the device is in airplane mode I was just turning it on to test internet connectivity loss when I noticed on my particular device it was still returning `NetworkAccess.Internet` instead of `NetworkAccess.None` unlike the simulator.

**Comment by GreatSummit** [comment]
No problem for droid because droid supports the way to detect airplane mode.
But iOS does not support it. How can I detect airplane mode on iOS?

**Comment by nickpeppers** [comment]
> No problem for droid because droid supports the way to detect airplane mode.
> But iOS does not support it. How can I detect airplane mode on iOS?

There's no easy perfect answer for iOS since Apple may reject your app depending on how you do it or it may not work for every case you had in mind. All the options looked kind of hacky but I'd check out this [stackoverflow post](https://stackoverflow.com/questions/4804398/detect-airplane-mode-on-ios).

**Comment by jamesmontemagno** [comment]
I can not reproduce this at all on my iPhone SE (2nd gen) running iOS 14.4

When I am on Cellular or Wifi it returns "Internet" and the moment I flip on Airplane mode it switches to None

```csharp

        protected override void OnAppearing()
        {
            base.OnAppearing();
            Connectivity.ConnectivityChanged += Connectivity_ConnectivityChanged;
        }

        private void Connectivity_ConnectivityChanged(object sender, ConnectivityChangedEventArgs e)
        {
            LabelInfo.Text = $"Changed: {e.NetworkAccess}";
        }

        private void Button_Clicked(object sender, EventArgs e)
        {
            LabelInfo.Text = $"Manual: {Connectivity.NetworkAccess}";
        }
```

very simpel code in a file ->new project

**Comment by jamesmontemagno** [comment]
@nickpeppers there could be something device specific. The best thing you could do to debug it is run the sample app and step through this code https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/Connectivity/Connectivity.android.cs#L45

On my pixel 2 xl it is working flawless. This is code that I have tested for the last 5+ years at this point with my connectivity plugin. There are a lot of weird things that can happen in Android of course as the device could just randomly return a network info stack to us.

**Comment by GreatSummit** [comment]
> I can not reproduce this at all on my iPhone SE (2nd gen) running iOS 14.4
> 
> When I am on Cellular or Wifi it returns "Internet" and the moment I flip on Airplane mode it switches to None
> 
> ```cs
>         protected override void OnAppearing()
>         {
>             base.OnAppearing();
>             Connectivity.ConnectivityChanged += Connectivity_ConnectivityChanged;
>         }
> 
>         private void Connectivity_ConnectivityChanged(object sender, ConnectivityChangedEventArgs e)
>         {
>             LabelInfo.Text = $"Changed: {e.NetworkAccess}";
>         }
> 
>         private void Button_Clicked(object sender, EventArgs e)
>         {
>             LabelInfo.Text = $"Manual: {Connectivity.NetworkAccess}";
>         }
> ```
> 
> very simpel code in a file ->new project

Thanks, but I don't need the event for connection changed, I just need to check the network connection whenever call backend apis because they requires long time.
I have to keep the network connection state on your idea. If that's working (ConnectivityChanged event) well, let me consider that way... but I would like to get the correct result by calling a method without event.

**Comment by nickpeppers** [comment]
> @nickpeppers there could be something device specific. The best thing you could do to debug it is run the sample app and step through this code https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/Connectivity/Connectivity.android.cs#L45
> 
> On my pixel 2 xl it is working flawless. This is code that I have tested for the last 5+ years at this point with my connectivity plugin. There are a lot of weird things that can happen in Android of course as the device could just randomly return a network info stack to us.

Yeah, it wouldn't be the first time I've seen Motorola screw something up with how they modified Android so wouldn't be surprised if it was device-specific. I just thought I'd mention it in case he was seeing something similar but for the most part, sounded like he was looking more for a way to detect airplane mode in general.

**Comment by GreatSummit** [comment]
No problem for android.
There are some other ways to detect network connectivity on droid as following
![image](https://user-images.githubusercontent.com/29710877/108728861-ebe89600-7564-11eb-9152-864b708cb017.png)

And no problem for android because Android supports detecting Airplane mode.
![image](https://user-images.githubusercontent.com/29710877/108729001-0c185500-7565-11eb-9a1a-1d5b3a2364a6.png)

The problem is iOS.
Of course, I did not test with the way by using Connectivity_Changed event yet because I completed my project by using manual checking as following.
![image](https://user-images.githubusercontent.com/29710877/108729290-539ee100-7565-11eb-979f-214d6ff247e6.png)

I hope you help us (xamarin developers who like Xamarin.Essentials package) by fixing even ios issue as soon as possible.
Sincerely.

**Comment by jamesmontemagno** [comment]
As you can see here ->
```
        private void Button_Clicked(object sender, EventArgs e)
        {
            LabelInfo.Text = $"Manual: {Connectivity.NetworkAccess}";
        }
```

I test it manually as well and it is working great for me. Here is a super small sample  that I am testing ->
[App12.zip](https://github.com/xamarin/Essentials/files/6023866/App12.zip)

Beyond that I would say if you can grab this repo and you can debug through it and see.

**Comment by timahrentlov** [comment]
Debugging on my iPad Pro with iOS 14.4.1.  

var current = Connectivity.NetworkAccess 

always returns NetworkAccess.Internet regardless of flight mode or wifi on/off.

Connectivity.ConnectivityChanged is never called when toggling flight or wifi on/off.

And using Shiny.Net's below does not work either.

connectivity.WhenInternetStatusChanged().Subscribe((isInternetAvailable) =>
{
    InternetAccess = isInternetAvailable;
});

**Comment by timahrentlov** [comment]
For me it was my VPN (Mullvad/WireGuard) that made Connectivity always report wifi. Probably something to do with the TransientConnection flag. Disabling VPN fixed the problem.

It can be tested using the Connectivity sample.

**Comment by nickpeppers** [comment]
> For me it was my VPN (Mullvad/WireGuard) that made Connectivity always report wifi. Probably something to do with the TransientConnection flag. Disabling VPN fixed the problem.
> 
> It can be tested using the Connectivity sample.

You know what thinking back I probably did have Block This! VPN adblocker on that could have been doing something similar

**Comment by jamesmontemagno** [comment]
Going to close as unable to reproduce.

**Comment by pavshr** [comment]
> For me it was my VPN (Mullvad/WireGuard) that made Connectivity always report wifi. Probably something to do with the TransientConnection flag. Disabling VPN fixed the problem.
> 
> It can be tested using the Connectivity sample.

+1 for that, looks like if you have any active VPN and turn off Wi-Fi, Cellular or turn on airplane mode on iOS, the `Connectivity.NetworkAccess` is still set to `NetworkAccess.Internet`.

**Comment by pavshr** [comment]
NordVPN in my case.

**Comment by kerberosargos** [comment]
Same issue is here for me. I do not use VPN. When I turn on Air Plane mode on my iPhone XS device  (15.5) it can not throw None. But it is working on Android Air Plane mode.
