### ISSUE TITLE
Move Xamain.Auth and Social to Essentials

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#1671]
Hi,

As Xamarin.Auth and Social are almost dead and there are a lot of new stuff needed by developers, I suggest to move Xamarin.Auth under Essentials to be like this:

using Xamarin.Essentials;

```
Auth.FacialRecognition
Auth.Finerprint
Auth.Facebook
Auth.Microsoft
Auth.Apple
Auth.Google

```

```
Social<Facebook>.Post(....)
Social<Linkedin>.Post(....)
Social<Twitter>.Post(....)
Social<Instagram>.Post(....)

```

```
Social<Facebook>.Get(....)
Social<Linkedin>.Get(....)
Social<Twitter>.Get(....)
Social<Instagram>.Get(....)
```

**Comment by jamesmontemagno** [comment]
This is already done actually with WebAuthenticator and SecureStorage :)

There isn't specific namespaces, but it is all in there. We do have a few things like biometrics and such to add. For now will clsoe as specific features shoudl be the request as the main areas are done.
