### ISSUE TITLE
[Bug] Android VersionTracking.Track() crash

### ISSUE THREAD

**Issue by vtkachen111** [xamarin/Essentials#1672]
### Description

With android 11 and multidex enabled VersionTracking.Track() crashes with exception:

Java.Lang.ClassNotFoundException: 'Didn't find class "androidx.core.content.pm.PackageInfoCompat" on path: DexPathList

### Steps to Reproduce
1.  Launch on a device running android 11

### Workaround
Disable EITHER multi-dex or code shrinker

### Actual Behavior
Throws exception
### Basic Information

- Version with issue: Android 11
- Last known good version: Android 10
- IDE:Visual studio 2019
- Platform Target Frameworks: 
  - Android: 10.0, 11.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Samsung s10+

### Sample:
[TestAndroid11.zip](https://github.com/xamarin/Essentials/files/5914679/TestAndroid11.zip)

**Comment by jamesmontemagno** [comment]
In your progaurd file you may need to add 
`androidx.core.content.pm.PackageInfoCompat`

or you could place this code in your activity so it doesn't get linked out:

```
static string PlatformGetBuild()
        {
            var pm = Platform.AppContext.PackageManager;
            var packageName = Platform.AppContext.PackageName;
            using (var info = pm.GetPackageInfo(packageName, PackageInfoFlags.MetaData))
            {
#if __ANDROID_28__
                return PackageInfoCompat.GetLongVersionCode(info).ToString(CultureInfo.InvariantCulture);
#else
#pragma warning disable CS0618 // Type or member is obsolete
                return info.VersionCode.ToString(CultureInfo.InvariantCulture);
#pragma warning restore CS0618 // Type or member is obsolete
#endif
            }
        }
```

**Comment by jfversluis** [comment]
No response, going to assume this was fixed!
