### ISSUE TITLE
[Bug]  When StorageRead permission is denied, PermissionException occurs.

### ISSUE THREAD

**Issue by pulmuone** [xamarin/Essentials#1676]
### Description
Android 11.0
When StorageRead permission is denied, PermissionException occurs.

### Steps to Reproduce

            var status = await Permissions.CheckStatusAsync<Permissions.StorageRead>();

            if (status != PermissionStatus.Granted)
            {
                var results = await Permissions.RequestAsync<Permissions.StorageRead>();  <- Excepton occurs
                
            }

**Xamarin.Essentials.PermissionException:** 'StorageRead permission was not granted: Denied'

Version : 1.6.1

**Comment by mattleibow** [comment]
I was not able to reproduce this. The only time that exception is thrown is when you actually use an API that requires it, such as FilePicker and MediaPicker.

[App13.zip](https://github.com/xamarin/Essentials/files/5962255/App13.zip)

**Comment by jamesmontemagno** [comment]
Will close as unable to reproduce.
