### ISSUE TITLE
Cancel Permission

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#1682]
Hi,

Please add an option to cancel permission, something like this:

`var status = Permissions.CancelPermissionAsync<Permissions.LocationWhenInUse>();`

Same thing with all other permissions.

Thanks,
Jassim

**Comment by jamesmontemagno** [comment]
I don't think there is an underlying permission for this. You would just launch the user into the settings of the app.

**Comment by jrahma** [comment]
What I want is to provide a switch control in my app for the user to enable / disable the location without having him going to Settings.. I think I have seen some apps doing that..

**Comment by jamesmontemagno** [comment]
Yeah that one would be different and is this one: https://github.com/xamarin/Essentials/issues/1058
