### ISSUE TITLE
[Bug] Lat Long not return on a Huawei P20 pro but every other device does

### ISSUE THREAD

**Issue by ColdstarJoey** [xamarin/Essentials#1685]
When using GetLastKnownLocation() every device I use works fine (Samsung) but a friend who has a P20 pro is getting nothing but his android location permissions are allowed and mobile data is on. anybody have a clue why?

**Comment by mattleibow** [comment]
`GetLastKnownLocation` is not guaranteed to work:

* https://developer.android.com/training/location/retrieve-current#last-known
* https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient.html#getLastLocation()

> If a location is not available, which should happen very rarely, null will be returned. The best accuracy available while respecting the location permissions will be returned.

Does getting the normal location work fine? `GetLastKnownLocation` is meant to be a first attempt if the OS keeps track of the location. Do you have access to any other Huawei devices?
