### ISSUE TITLE
[Bug] [Bug] in iOS 14 aawait CrossPermissions.Current.RequestPermissionAsync<LocationPermission>() does not return after the pop-up is closed

### ISSUE THREAD

**Issue by sisaacks** [xamarin/Essentials#1686]
### Description
in iOS 14 when permission is accepted and right after the pop-up is closed
await CrossPermissions.Current.RequestPermissionAsync<LocationPermission>()
never returns, or throws an exception the first time called.
### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
in iOS 14 when permission is accepted and right after the pop-up is closed
await CrossPermissions.Current.RequestPermissionAsync<LocationPermission>()
returns PermissionStatus.Granted.
### Basic Information
Version with issue: 1.6.1
Last known good version: not known
IDE: Visual Studio For Windows 16.8.4
Platform Target Frameworks:
iOS: Xamarin.iOS 14.0.0.0
Affected Devices: Simulator iPhone 11, iOS 14.0

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by mattleibow** [comment]
That I think there is a disconnect between the bug title and this repo. This is Xamarin.Essentials and the title seems to indicate @jamesmontemagno's plug-ins.

Are you sure you have the right repo and/or code?

**Comment by sisaacks** [comment]
@mattleibow I realized after I had posted I had the wrong one.  I posted on @jamesmontemagno but he never ever responds. For now I found a workaround.

**Comment by mattleibow** [comment]
James is a very busy guy these days. Busy running MS and all that :)

**Comment by sisaacks** [comment]
I figured as much, which is why I went with the work around for now
