### ISSUE TITLE
[Enhancement] Wrapper for shared app storage

### ISSUE THREAD

**Issue by DennisWelu** [xamarin/Essentials#1688]
## Summary
Provide a consistent API for access to shared app storage.
On iOS, there are app groups. This is accessible via System.IO filepath operations.
On UWP, there is the shared publisher cache. This is accessible via System.IO filepath operations.
On Android, …there is not an equivalent "formal" grouping of applications like on iOS and UWP. Up until Android 10 you could read/write to a shared (outside of hidden app storage) filepath using System.IO operations. In Android 11 security constraints are clamped down, so **starting on Android 11 writing cross platform code accessing a common storage location is not possible due to System.IO operations being rejected.**

*Background Info*
It's important to understand the difference in behavior between the iOS/UWP "app grouping" mechanisms and Android. For iOS/UWP, a shared hidden location is given to the app as an option for System.IO operations. User permission is not required to read/write to this location. When the first app in the group is installed, that shared folder can be written to. When the last app in the group is uninstalled, that shared folder is removed. Whereas on Android, you basically had to designate some folder that both applications could reach (many options there, some indexable, some not). Prior to Android 11 this arbitrary shared location could be created without user interaction but it wouldn't automatically be removed with uninstall of the last app in the group. With Android 11, there is more security/isolation enforced, but there still isn't a formal app grouping mechanism that provides a shared space for apps. The arbitrary approach can still be accomplished by prompting the user IN EACH APP to pick the shared location they want to use. That gives the app permission to read/write to the shared folder. It's a degraded user experience. Further trouble is the fact that System.IO operations cannot be used to access the folder chosen by the user. Android Storage Access Framework (SAF) API's must be used instead. And that means code is no longer cross-platform.

## API Changes

I'm not really sure what the API should be. One part of the API has to do with resolving the shared location for storage without needing to know platform specific paths etc. If you were to look at it from a System.IO standpoint, the API would provide the root folder of the  shared app location.

    On iOS: NSFileManager.DefaultManager.GetContainerUrl(GroupIdentifier).Path
    On UWP: ApplicationData.Current.GetPublisherCacheFolder(PublisherCacheFolder).Path
    On Android: Various ways…YMMV

If System.IO operations worked, you would just use that path for standard directory and file creation and read/write. If System.IO is not an option going forward…then there needs to be some common API for read/write. Perhaps using a model similar to the UWP StorageFolder and StorageFile system.

The problem with an API approach is it will require 3rd party libraries that provide file based services to adapt to accommodate it somehow e.g. a Sqlite database wrapper library such as Akavache. Currently a library such as that just requires a file folder and database file name to get started.

So...I'm certainly open to ideas!

## Intended Use Case
Shared app storage space is required any time you have more than 1 application that needs to share a local data cache.

A primary example would be an enterprise set of applications that allow offline modes of operation. Locally cached data is expensive to download (may be large quantities of records, or maybe is a cache of map tiles, etc.), and multiple apps are created for marketing reasons and/or because each app is tailored to different disciplines/roles in the organization (where any given person might need 1 or more/all apps in the suite). It's just not practical to create a single app that "does everything" in enterprise business scenarios.

## Reference

- This issue was previously posted to SO looking for an "immediate" answer and it doesn't seem there was any: https://stackoverflow.com/questions/65688560/system-io-write-operations-not-working-in-android-11-outside-of-app-sandbox

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.

**Comment by mgernand** [comment]
Is there any way to do this in .NET MAUI?

**Comment by DennisWelu** [comment]
No. Android has never provided a way to do this and it apparently isn't a common enough requirement to develop any kind of API-driven equivalent to fill the gap there.
