### ISSUE TITLE
Battery Model Info

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#1689]
Hi,

Please Battery Model & Manufacturer info to the Battery API.

Thank you

**Comment by jamesmontemagno** [comment]
I don't believe these are available APIs from the platform. All feature requests should link to APIs and docs about the feature please.

**Comment by jrahma** [comment]
I saw this:

[https://datalogic.github.io/xamarin-sdk-docs/html/T_Com_Datalogic_Device_Battery_BatteryInfo.htm](https://datalogic.github.io/xamarin-sdk-docs/html/T_Com_Datalogic_Device_Battery_BatteryInfo.htm)

**Comment by acaliaro** [comment]
> I saw this:
> 
> https://datalogic.github.io/xamarin-sdk-docs/html/T_Com_Datalogic_Device_Battery_BatteryInfo.htm

These are OEM libraries. Every oem can create its sdk that give you the possibility to get/set some properties, but are not Android api
