### ISSUE TITLE
[Bug] WebAuthenticator: Closes before user can save password

### ISSUE THREAD

**Issue by monkeypro** [xamarin/Essentials#1691]
When using WebAuthenticator.AuthenticateAsync method, the authentication window closes before the user has a chance to answer the "Save password"-dialog

### Steps to Reproduce

1. Activate Password autofill on the device
2. Show login page by calling WebAuthenticator.AuthenticateAsync(...)
3. After successful login a dialog to save password is shown

### Expected Behavior
The login window stays open until the user has answered the "Save password"-question

### Actual Behavior
The browser window is closed immediately, before the user has a chance to save password

### Basic Information

- Version with issue: 1.6.1
- Affected Devices: iOS and Android (do not know about UWP)

### Screenshots
![SavePassword_iOS](https://user-images.githubusercontent.com/2150723/108034592-05a24e80-7036-11eb-81cc-1f3de5dce5e3.jpg)

**Comment by monkeypro** [comment]
I just found this post in the Apple Developer Forum
[ASWebAuthenticationSession closes before user can answer save password prompt](https://developer.apple.com/forums/thread/127979)

**Comment by jamesmontemagno** [comment]
So, i think we are in a catch 22.... the sessions closes because it was successful, but doesn't wait for it for success of adding a password or not. This unfortunately seems to be on Apple. :(
