### ISSUE TITLE
[Bug] Launcher.OpenAsync fails to open URL and doesn't even provide any exception

### ISSUE THREAD

**Issue by afzalali15** [xamarin/Essentials#1693]
### Description
OpenAsync silently fails and it is not able to open the URL 

### Steps to Reproduce

1. Create new project
2. Add a button
3. OnClick add this code `await Launcher.OpenAsync("fb://profile/1755395518116701");`
4. Run on the **iPhone device/simulator** where Facebook is not installed

### Expected Behavior
OpenAsync should inform if any exception happened or it was not able to open

### Actual Behavior
Nothing happens after calling the above line

### Basic Information

- Version with issue: 1.5.3.2

**Comment by mshuf** [comment]
+1 - I'm seeing something similar since updating the Xamarin Essentials library, except I receive the following exception when calling: `await Browser.OpenAsync("https://google.com", BrowserLaunchMode.External);`

**Xamarin.Essentials.FeatureNotSupportedException: 'Specified method is not supported.'**

**Comment by jamesmontemagno** [comment]
Did you add the query schema? https://docs.microsoft.com/en-us/xamarin/essentials/launcher?tabs=ios#additional-platform-setup

**Comment by jamesmontemagno** [comment]
Closing as documented above.

**Comment by jmichas** [comment]
I think this should be reopened as a bug. You do not need to put the scheme in info.plist if you merely want to open another app via url. We have an app where it is impractical for us to keep all partner app schemes in the plist.

In the debug log we see  `[default] Failed to open URL...` if we try and open an app that is not installed on the device. This is a valid use case. We could then prompt the user to download the missing app. The fact that the "exception" is logged and not surfaced to the calling code is a bug, everything is already there, just throw or rethrow on the line after the failed to open logging.
