### ISSUE TITLE
[Enhancement] Permissions UI

### ISSUE THREAD

**Issue by procopio** [xamarin/Essentials#1694]
## Summary
Create a unified UI for asking permissions. Android and iOS recommend to add a screen explaining the reasons of the permissions we are asking. Would be great if we have an unique library where we just have to add the explanatory text and the library make the beautiful job creating the screens with icons, texts and buttons.
Just like the image bellow:

![image](https://user-images.githubusercontent.com/418238/108277763-3f7c6d80-717a-11eb-8dca-182ee1d291f3.png)

**Comment by jamesmontemagno** [comment]
This would be a great external package from the community. Xamarin.Essentials does not create UI as it is just for core platform features.
