### ISSUE TITLE
Image Loading Library

### ISSUE THREAD

**Issue by nikossaperas** [xamarin/Essentials#1695]
Hello,

I would like to propose a feature for Xamarin Essentials.
At the time beeing available libraries for image loading are SquarePicasso, FFimageLoading and GlideX.
However the first two have many unresolved issues quite some time now. Probably not maintained any more and GlideX is for Xamarin Forms.

It would be great to see image loading as part of Xamarin Essentials, available for Xamarin Native and Xamarin Forms.

Thanks very much.

**Comment by jamesmontemagno** [comment]
This is a bit out of our scope for Xamarin.Essentials and is best to live in Xamarin.Forms and .NET MAUI for UI specifics.

**Comment by nikossaperas** [comment]
@jamesmontemagno Thank you very much for the response. Just a quick follow up question: 
If somethig lives in Xamarin Forms and .NET MAUI will it be available for Xamarin Native also?
