### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by KevinHu-au** [xamarin/Essentials#1698]
### Description
TextToSpeech on Android 10 cannot speech the decimal value in the text properly. 

### Steps to Reproduce

1. Call TextToSpeech.SpeakAsync("In 1.5 kilometers, turn right on Kiama Close."); 
2. Hear the speech from the Android device
3. 

### Expected Behavior
The voice should be like "In one point five kilometers, turn right on Kiama Close."
### Actual Behavior
The actual voice is ""In one point kilometers, turn right on Kiama Close." (The 5 after the point missed in the voice!)
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:   11.0.2
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
We simply send the text over to the TTS engine, so this would need to be filed with Android
