### ISSUE TITLE
[Bug] mono.java.lang.RunnableImplementor.run RunnableImplementor.java, line 30 Java.Lang.IllegalArgumentException: View=DecorView@d126374[MediaPickerActivity] not attached to window manager

### ISSUE THREAD

**Issue by sbs-Arockia-Jenitha** [xamarin/Essentials#1701]
### Description
JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
Dialog.Dismiss ()
AndHUD.<DismissCurrent>b__30_0 ()
AndHUD+<>c__DisplayClass30_0.<DismissCurrent>b__1 (System.Object state)
SyncContext+<>c__DisplayClass3_0.<Send>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.26(intptr,intptr)
java.lang.IllegalArgumentException: View=DecorView@778cd33[MediaPickerActivity] not attached to window manager
android.view.WindowManagerGlobal.findViewLocked WindowManagerGlobal.java:597
android.view.WindowManagerGlobal.removeView WindowManagerGlobal.java:501
android.view.WindowManagerImpl.removeViewImmediate WindowManagerImpl.java:146
android.app.Dialog.dismissDialog Dialog.java:676
android.app.Dialog.dismiss Dialog.java:658
mono.java.lang.RunnableImplementor.n_run(Native Method)
mono.java.lang.RunnableImplementor.run RunnableImplementor.java:30
android.os.Handler.handleCallback Handler.java:938
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loop Looper.java:246
android.app.ActivityThread.main ActivityThread.java:8456
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:596
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1130

Android: 11
Android Build: RP1A.200720.012
Manufacturer: samsung
Model: SM-G991B
CrashReporter Key: 423e06f0-ec37-4b16-8f7e-9f63cc3754b4
Start Date: 2021-02-23T15:46:29.396Z
Date: 2021-02-24T09:56:11.163Z

Xamarin Exception Stack:
Java.Lang.IllegalArgumentException: View=DecorView@778cd33[MediaPickerActivity] not attached to window manager
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <b0bcbc4d7c9647a0b22ce77472cfa335>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <b0bcbc4d7c9647a0b22ce77472cfa335>:0
  at Android.App.Dialog.Dismiss () [0x0000a] in <21771fd42f1b4026bc98df066c13f434>:0
  at AndroidHUD.AndHUD.<DismissCurrent>b__30_0 () [0x00019] in <a4dd75a72c8244ad8bdba54b31441bb5>:0
  at AndroidHUD.AndHUD+<>c__DisplayClass30_0.<DismissCurrent>b__1 (System.Object state) [0x00000] in <a4dd75a72c8244ad8bdba54b31441bb5>:0
  at Android.App.SyncContext+<>c__DisplayClass3_0.<Send>b__0 () [0x00000] in <21771fd42f1b4026bc98df066c13f434>:0
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <21771fd42f1b4026bc98df066c13f434>:0
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <21771fd42f1b4026bc98df066c13f434>:0
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.26(intptr,intptr)
  at java.lang.IllegalArgumentException: View=DecorView@778cd33[MediaPickerActivity] not attached to window manager
  at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:597)
  at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:501)
  at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:146)
  at android.app.Dialog.dismissDialog(Dialog.java:676)
  at android.app.Dialog.dismiss(Dialog.java:658)
  at mono.java.lang.RunnableImplementor.n_run(Native Method)
  at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
  at android.os.Handler.handleCallback(Handler.java:938)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:246)
  at android.app.ActivityThread.main(ActivityThread.java:8456)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Thread 2:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:1736)
2   java.lang.Thread.getAllStackTraces(Thread.java:1812)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:1140)
4   com.microsoft.appcenter.crashes.WrapperSdkExceptionManager.saveWrapperException(WrapperSdkExceptionManager.java:58)
5   mono.java.lang.RunnableImplementor.n_run(RunnableImplementor.java:-2)
6   mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
7   android.os.Handler.handleCallback(Handler.java:938)
8   android.os.Handler.dispatchMessage(Handler.java:99)
9   android.os.Looper.loop(Looper.java:246)
10  android.app.ActivityThread.main(ActivityThread.java:8456)
11  java.lang.reflect.Method.invoke(Method.java:-2)
12  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
13  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

Thread 32851:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:442)
2   java.lang.Object.wait(Object.java:568)
3   java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:217)
4   java.lang.Daemons$Daemon.run(Daemons.java:139)
5   java.lang.Thread.run(Thread.java:923)

Thread 32853:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:442)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
4   java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:273)
5   java.lang.Daemons$Daemon.run(Daemons.java:139)
6   java.lang.Thread.run(Thread.java:923)

Thread 32854:
0   java.lang.Thread.sleep(Thread.java:-2)
1   java.lang.Thread.sleep(Thread.java:442)
2   java.lang.Thread.sleep(Thread.java:358)
3   java.lang.Daemons$FinalizerWatchdogDaemon.sleepForNanos(Daemons.java:390)
4   java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:419)
5   java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:325)
6   java.lang.Daemons$Daemon.run(Daemons.java:139)
7   java.lang.Thread.run(Thread.java:923)

Thread 32864:
0   sun.misc.Unsafe.park(Unsafe.java:-2)
1   java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
2   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2067)
3   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
4   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
5   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
6   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
7   java.lang.Thread.run(Thread.java:923)

Thread 32869:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)
3   android.os.HandlerThread.run(HandlerThread.java:67)

Thread 32871:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)
3   android.os.HandlerThread.run(HandlerThread.java:67)

Thread 32872:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)
3   android.os.HandlerThread.run(HandlerThread.java:67)

Thread 32883:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)
3   android.os.HandlerThread.run(HandlerThread.java:67)

Thread 32887:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:442)
2   java.lang.Object.wait(Object.java:568)
3   com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:313)
4   com.android.okhttp.okio.AsyncTimeout.access$000(AsyncTimeout.java:42)
5   com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:288)

Thread 33669:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:106)
2   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
3   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
4   java.lang.Thread.run(Thread.java:923)

Thread 33692:
0   sun.misc.Unsafe.park(Unsafe.java:-2)
1   java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
2   java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:459)
3   java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
4   java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:920)
5   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
6   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
7   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
8   java.lang.Thread.run(Thread.java:923)

Thread 33712:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)
3   android.os.HandlerThread.run(HandlerThread.java:67)

### Steps to Reproduce
unknown

### Expected Behavior
App will be not crash

### Actual Behavior
App crash

### Basic Information

- Android Support Library Version: 
- Nuget Packages: Xamarin.Essentials 1.6.1
- Affected Devices:

**Comment by adambarath** [comment]
Is there any update on this?

**Comment by sbs-Arockia-Jenitha** [comment]
> Is there any update on this?

No update from them.  Are you facing same issue in yours? @adambarath

**Comment by adambarath** [comment]
> > Is there any update on this?
> 
> No update from them. Are you facing same issue in yours? @adambarath

Yes. My code snippet:
```
var options = new PickOptions
{
    PickerTitle = TextProvider.GetText(null, null, "attachment_type_document"),
    FileTypes = new FilePickerFileType(new Dictionary<DevicePlatform, IEnumerable<string>>
    {        { DevicePlatform.Android, new[] { "application/pdf" } },       }),
};

var result = await FilePicker.PickAsync(options);
```
Variable 'result' is not null. App gets back the picked file and after 1-2 second crash appears.

**Comment by adambarath** [comment]
I think I got the solution. I call FilePicker on mainthread, so it works properly.

```
await MainThread.InvokeOnMainThreadAsync(async () =>
  {
      var fileResult = await FilePicker.PickAsync(options);
      .... 
  }).ConfigureAwait(false);
```

**Comment by sbs-Arockia-Jenitha** [comment]
ok @adambarath I will check and revert back.

**Comment by jamesmontemagno** [comment]
It looks like this is cleared up or an issue with AndHUD and how it is being called. Please open a new issue with a reproduction if this is not the case.
