### ISSUE TITLE
Screenshot.CaptureAsync does not show the contents of OpenGLView[Bug] 

### ISSUE THREAD

**Issue by pfafft33** [xamarin/Essentials#1702]
### Description
Screenshot.CaptureAsync does NOT show the contents of OpenGLView
### Steps to Reproduce

1. Create a page with an OpenGLView displaying graphics
2. Execute Screenshot.CaptureAsync
3. The resulting photo shows everything on the page EXCEPT the contents of the OpenGLView
4. The OpenGLView just shows up as an empty frame

### Expected Behavior
I expect that the photo captured will capture EVERYTHING on the page, including the graphics which are currently being displayed in the OpenGLView.

### Actual Behavior
The Android "3-finger salute" captures the ENTIRE contents of the screen as expected, but Screenshot.CaptureAsync does NOT capture the contents of the OpenGLView.
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
I am going to close this as this will have to do with the underlying controls and not the screenshot api as @dimonovdd mentioned.

**Comment by pfafft33** [comment]
@jamesmontemagno - So, you closed this issue because it has to do with the underlying controls and not the screenshot API. So, did you OPEN a new issue related to the underlying controls, then, or are you just tossing this out!

**Comment by jamesmontemagno** [comment]
So yeah looks like you would need a custom render and tap into that opengl view -> https://stackoverflow.com/questions/5514149/capture-screen-of-glsurfaceview-to-bitmap.

But let me transfer the issue over to the Xamarin.Forms repo as a feature request.
