### ISSUE TITLE
Launcher [iOS] - Photos app not showing up when trying to open image files (jpg, png)

### ISSUE THREAD

**Issue by JRallee** [xamarin/Essentials#1703]
### Description
My app allows importing and viewing of different file types. When I try to open an image file (png, jpg etc), the file open options from ios does not display the Photos app. I have tried some solutions of listing the same in info.plist etc. but of no help. 

Is there a workaround or solution for this?

### Steps to reproduce
1. Have a screen where files are displayed
2. Clicking on a file downloads the same to local temp location (in iOS, the My documents special folder)
3. Post download, I do, await Launcher.OpenAsync(File = ReadOnly....)
4. File opening options are displayed

### Expected Behavior
Photos app should be shown for image files

### Actual Behavior
Photos app is not visible. Even if we tap on More, the same does not appear

- Version with issue: All Xamarin components on latest version

**Comment by keerthinathganjam** [comment]
I am also facing the Same issue. Is there any alternative to Launcher?

**Comment by dimonovdd** [comment]
@keerthinathganjam @JRallee Can you show an example of an application where it works?

**Comment by keerthinathganjam** [comment]
Hi @dimonovdd,
 I have tried and couldn't find any app which opens up photos app for images, but for other formats like pdf, word, excle, it shows appropriate apps to open. Is there an specific reason for not showing Photos app?

**Comment by dimonovdd** [comment]
This is not provided by the operating system and the photo app. You can easily show photos and images in your app. But for example it is better and easier to display a dock file in a special application

**Comment by jamesmontemagno** [comment]
The operating system declares what can be opened based on the file, so this is out of our control at this point.
