### ISSUE TITLE
Xamarin Essentails MediaPicker issue permissions when Picker Photo on Android

### ISSUE THREAD

**Issue by krmWorkAccnt** [xamarin/Essentials#1708]
The MediaPicker.PickPhotoAsync() invokes the permission dialog where permissions hasn't been granted, however if the user denies the permission the action still takes user to select a photo.

### Steps to Reproduce

1.  Create a new project with a button -- In the code behind just had this to button event var result = await MediaPicker.PickPhotoAsync(new MediaPickerOptions() 
            {
                Title = "Select a photo"
            });
2. When the permission dialog is presented, press Deny, this will still take user through to select a photo.
3. 

### Expected Behavior
This should deny user from selecting a photo
### Actual Behavior
Pressing deny allows user to select a photo
### Basic Information

- Version with issue:
- 1.6.1 including preview versions.
- Last known good version:
- N/A

Work Around:
Use below check -- This takes away the responsibility for permission being checked in MediaPicker.PickPhotoAsync
var status = await Permissions.CheckStatusAsync<Permissions.StorageRead>();
            if (status != PermissionStatus.Granted)
            {
                await Permissions.RequestAsync<Permissions.StorageRead>();
                status = await Permissions.CheckStatusAsync<Permissions.StorageRead>();
                if (status != PermissionStatus.Granted)
                    return; // Or some exception or dialog box
            }

NOTE -- There seems to be a different issue with await Permissions.RequestAsync<>() in Essentials 1.6.0 where if the user selects deny, then the above request won't be invoked again -- This however doesn't seem to be an issue with 1.6.1

**Comment by jamesmontemagno** [comment]
I am unable to reproduce this in 1.6.1 and it works for me here.
