### ISSUE TITLE
[QUESTION]  MainThread.BeginInvokeOnMainThread

### ISSUE THREAD

**Issue by angelru** [xamarin/Essentials#1709]
I have to update the ui (ObservableCollection) through an event synchronous (SignalR) it may be that at that moment the application is not with that view visible because the user is in another view. I went to test with MainThread.BeginInvokeOnMainThread and it didn't work, but with Device.BeginInvokeOnMainThread it got updated. Are there big differences?

**Comment by jamesmontemagno** [comment]
Would need to compare code. What platform?

**Comment by dimonovdd** [comment]
A colleague at my work, also faced with this on iOS. The difference is in the if else construct.
Unfortunately he didn't have the sample code saved

```csharp
public static bool IsMainThread =>
    PlatformIsMainThread;

public static void BeginInvokeOnMainThread(Action action)
{
    if (IsMainThread)
    {
        action();
    }
    else
    {
        PlatformBeginInvokeOnMainThread(action);
    }
}
```

- [Essentials](https://github.com/xamarin/Essentials/blob/7218ab88f7fbe00ec3379bd54e6c0ce35ffc0c22/Xamarin.Essentials/MainThread/MainThread.shared.cs#L12)
- [Forms](https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Core/Device.cs#L106)

**Comment by angelru** [comment]
It happened to me on android, to see if I take the time and do the example.

**Comment by angelru** [comment]
@dimonovdd and what was the solution?
