### ISSUE TITLE
[Enhancement] Add two new options to FilePicker ...

### ISSUE THREAD

**Issue by ajtruckle** [xamarin/Essentials#1711]
## Summary
Make it easier to extra the file title and file extension. This is useful when you have selected multiple files of differing types in one go.

## API Changes

At the moment I use the following to do what I need:

```
Path.GetExtension(fileResult.FileName) == ".xsl"
Path.GetFileNameWithoutExtension(fileResult.FileName)
```

Proposal is to add extra methods to `FileResult` object:

- `FileExtension()`
- `FileTitle()`

This provides more consistency since we already have `FileName` and `FilePath`.

I would like this as a minimum to be working on Android, iOS and macOS. 

## Intended Use Case
This is what I have at the moment:

        async private void InstallStyleButton_Clicked(object sender, EventArgs e)
        {
            var customFileType =
                new FilePickerFileType(new Dictionary<DevicePlatform, IEnumerable<string>>
                {
                    {DevicePlatform.Android, new[] { "text/css"} },
                    {DevicePlatform.iOS, new[] { "public.css" } },
                    {DevicePlatform.macOS, new[] {"xsl", "css"} }
                });

            var pickResult = await FilePicker.PickMultipleAsync(new PickOptions
            {
                FileTypes = customFileType,
                PickerTitle = "Select file(s) to install"
            });

            if(pickResult != null)
            {
                foreach(var fileResult in pickResult)
                {
                    // Build target path (don't use hardcoded path)
                    string targetFile = Path.Combine(_pageModel.StylesPath, fileResult.FileName);

                    // OK to install?
                    if(!File.Exists(targetFile)) 
                    {
                        // Install
                        File.Copy(fileResult.FullPath, targetFile);

                        // Only copy XSL files to the drop-list
                        if (Path.GetExtension(fileResult.FileName) == ".xsl")
                        {
                            // Add it
                            var fileTitle = Path.GetFileNameWithoutExtension(fileResult.FileName);
                            StylesPicker.ItemsSource.Add(fileTitle);

                            // We don't select it because the might install more than one XSL file
                        }
                    }     
                }    
            }
        }

My request is a nicety more than anything else. 😊

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
