### ISSUE TITLE
FileSaver API

### ISSUE THREAD

**Issue by DmitryBorodiy** [xamarin/Essentials#1717]
Hello, Microsoft end .NET Xamarin Community!
So, FilePicker API is cool, but Xamarin Forms need a FileSaver API for save files.
Please implement this in Xamarin.Essentials.

Thanks!
Best wishes!

**Comment by davidortinau** [comment]
How would this differ from System.IO and saving files? Essentials gives you the different storage path options in a nice xplat manner.

**Comment by Dmitiry-hub** [comment]
> How would this differ from System.IO and saving files? Essentials gives you the different storage path options in a nice xplat manner.

This will work similarly to FilePicker, only it will not select files, but create and save.

**Comment by Dmitiry-hub** [comment]
This is should work like this.

```
var file = await FileSaver.SaveAndPickFileAsync(FileMode.ReadWrite);

if(file != null)
{
        //Do something with FileStream... 
}

```

**Comment by dimonovdd** [comment]
@davidortinau Hi
I think it's talking about a similar 'SaveFileDialog' from WPF

**Comment by Dmitiry-hub** [comment]
> @davidortinau Hi
> I think it's talking about a similar 'SaveFileDialog' from WPF

Yes!

**Comment by Dmitiry-hub** [comment]
> @davidortinau Hi
> I think it's talking about a similar 'SaveFileDialog' from WPF

Or FileSavePicker on UWP.

**Comment by dimonovdd** [comment]
This issue has already been created. But I don't think it's possible

https://github.com/xamarin/Essentials/issues/1386

**Comment by Dmitiry-hub** [comment]
> This issue has already been created. But I don't think it's possible
> 
> #1386

Why?

**Comment by Dmitiry-hub** [comment]
FilePicker is implemented, but FileSaver not...

**Comment by Dmitiry-hub** [comment]
Creating own FileSaver dialog...
It's slow and uncomfortable.
But Xamarin.Essentials can resolve this problem if you add FileSaver API.

**Comment by dimonovdd** [comment]
Can you provide an sample of an application where this feature is made?
This is non-standard behavior. You can use [Share](https://docs.microsoft.com/en-us/xamarin/essentials/share) or [Launcher](https://docs.microsoft.com/en-us/xamarin/essentials/launcher). 

On ios, the user can choose to save to files. I just recently fixed this [feature](https://github.com/xamarin/Essentials/pull/1609).

On android, the user can choose a file manager that supports file saving.

If you want to save media files, it's better to use something like [this](https://github.com/xamarin/Essentials/pull/1628)

**Comment by Dmitiry-hub** [comment]
> Can you provide an sample of an application where this feature is made?
> This is non-standard behavior. You can use [Share](https://docs.microsoft.com/en-us/xamarin/essentials/share) or [Launcher](https://docs.microsoft.com/en-us/xamarin/essentials/launcher).
> 
> On ios, the user can choose to save to files. I just recently fixed [this feature](https://github.com/xamarin/Essentials/pull/1609).
> 
> On android, the user can choose a file manager that supports file saving.
> 
> If you want to save media files, it's better to use something like [this](https://github.com/xamarin/Essentials/pull/1628)

So, In my Xamarin.Forms app I implement my own FileSavePicker for UWP and Android but it's not cross-platform...

**Comment by Dmitiry-hub** [comment]
Why FilePicker can't save files?

**Comment by Dmitiry-hub** [comment]
FilePickers - it's standart comfortable logic for open and save files...

**Comment by dimonovdd** [comment]
You may notice that many cross-platform applications support "Save As" function (Save File dialog) on macOS, Windows and Linux, but on mobile devices apps use an analog of Essential.Launcher or Essential.Share

**Comment by Dmitiry-hub** [comment]
But Android have DirectoryPicker and FilePicker intent...
User can enter the file name in prompt dialog and select folder...
The program can create and write file in this folder.

**Comment by Dmitiry-hub** [comment]
This is a Windows 10 Mobile user logic😀😀😀

**Comment by Dmitiry-hub** [comment]
And it's more comfortable if you want write text files too

**Comment by Jakar510** [comment]
For those that need it, [FileSaver API](https://github.com/Jakar510/Jakar.Api/blob/master/src/Jakar.Api/FileSystem.cs). I also have helpers to share and use those files.

**Comment by MuzzyA** [comment]
> For those that need it, [FileSaver API](https://github.com/Jakar510/Jakar.Api/blob/master/src/Jakar.Api/FileSystem.cs). I also have helpers to share and use those files.

Link is no longer valid.

Still not seeing a FileSave dialog anywhere.  Isn't there something?  Even if it's UWP specific, that's fine by me.  If FilePicker exists, it's a very small change to make it a FileSaver as well.  It's just returning a directory and a file name.

The FilePicker can only be used as a 'FileSaver' if the file already exists.  But, you need to be able to specify a new file.

**Comment by Jakar510** [comment]
> > For those that need it, [FileSaver API](https://github.com/Jakar510/Jakar.Api/blob/master/src/Jakar.Api/FileSystem.cs). I also have helpers to share and use those files.
> 
> Link is no longer valid.
> 
> Still not seeing a FileSave dialog anywhere. Isn't there something? Even if it's UWP specific, that's fine by me. If FilePicker exists, it's a very small change to make it a FileSaver as well. It's just returning a directory and a file name.
> 
> The FilePicker can only be used as a 'FileSaver' if the file already exists. But, you need to be able to specify a new file.

Here's the updated [link](https://github.com/Jakar510/Jakar.Extensions/blob/master/Jakar.Extensions.Xamarin.Forms/FileSystemApi.cs)

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.

Also, this one is now available in the .NET MAUI Community Toolkit!
