### ISSUE TITLE
[Bug]  FilePicker in xamarin.essential not working

### ISSUE THREAD

**Issue by Barshan-Mandal** [xamarin/Essentials#1718]
Cant select multiple files

**Comment by dimonovdd** [comment]
Hi. 
Can you describe this issue more detail or provide a sample?

**Comment by Barshan-Mandal** [comment]
when i want to get fullpath of a file ...It is showing that ...could not find some parts of filepath

**Comment by Barshan-Mandal** [comment]
![image](https://user-images.githubusercontent.com/74092409/110227950-5adfca80-7f27-11eb-88a7-106e8214c77d.png)

**Comment by Barshan-Mandal** [comment]
xamarin.android problem

**Comment by dimonovdd** [comment]
@Barshan-Mandal See the [documentation](https://docs.microsoft.com/en-us/xamarin/essentials/file-picker?context=xamarin%2Fxamarin-forms&tabs=ios#pick-file)
You should use `OpenReadAsync` method. The path you see is a temporary path. 
If you need the path to the file, look at [this sample](https://github.com/xamarin/Essentials/blob/7218ab88f7fbe00ec3379bd54e6c0ce35ffc0c22/Samples/Samples/ViewModel/FilePickerViewModel.cs#L114).

**Comment by Barshan-Mandal** [comment]
But i want to directly point to that directory's file...no copy paste..........how to do that

**Comment by Barshan-Mandal** [comment]
I need that string

**Comment by Barshan-Mandal** [comment]
FilePicker.PickMultipleAsync() using this line is throwing that error..............what can i do

**Comment by Barshan-Mandal** [comment]
![Uploading image.png…]()

**Comment by Barshan-Mandal** [comment]
FilePicker.PickMultipleAsync() using this line is throwing that error..............what can i do

**Comment by Barshan-Mandal** [comment]
![Uploading image.png…]()

**Comment by Barshan-Mandal** [comment]
FilePicker.PickMultipleAsync() using this line is throwing that error..............what can i do

**Comment by Barshan-Mandal** [comment]
exception at FilePicker.PickMultipleAsync() this line

**Comment by Barshan-Mandal** [comment]
![Uploading image.png…]()

**Comment by Barshan-Mandal** [comment]
![Uploading Captudddddddddre.PNG…]()

**Comment by Barshan-Mandal** [comment]
![image](https://user-images.githubusercontent.com/74092409/110274098-428bb080-7ff8-11eb-9ce3-a5819dc9dd4b.png)

**Comment by Barshan-Mandal** [comment]
FilePicker.PickMultipleAsync() using this line is throwing that error..............what can i do

**Comment by Barshan-Mandal** [comment]
why haven't you fixed the issue even after a long time???

**Comment by Fox4148** [comment]
> 
> 
> why haven't you fixed the issue even after a long time???

This is open source; fork the repo and try to fix it yourself.

**Comment by Barshan-Mandal** [comment]
Do xamarine community sleep all the time?

**Comment by Barshan-Mandal** [comment]
Why are not you helping me bro

**Comment by dimonovdd** [comment]
You are a member of the community just like everyone else. Why don't you create a pull request to fix this issue?
I think the Microsoft developers are busy with MAUI now, and the community is fixing what's important to it.

**Comment by Barshan-Mandal** [comment]
@dimonovdd  You help me then making a new package

**Comment by dimonovdd** [comment]
> @dimonovdd  You help me then making a new package

What's the new package?

**Comment by Barshan-Mandal** [comment]
@dimonovdd   Make a cross platform filepicker ..Ok?

**Comment by dimonovdd** [comment]
I don't quite understand what do you want? Do you want me to make a new plugin?

**Comment by Barshan-Mandal** [comment]
@dimonovdd    yes bro

**Comment by Barshan-Mandal** [comment]
@dimonovdd  Do you fear?If not then make it

**Comment by jamesmontemagno** [comment]
I am closing this issue as I am unable to reproduce. I have also locked this thread.
