### ISSUE TITLE
[Bug] Share.RequestAsync does not await dialog close.

### ISSUE THREAD

**Issue by nixkuroi** [xamarin/Essentials#1720]
Share.RequestAsync returns as Task object which implies that it can be awaited.  When placing an await before Share.RequestAsync("title","text"), it only awaits the share popup appearing, but does not wait for the share to take place before continuing to the next line.

This makes impossible to await a share, and then perform any other action, especially a navigation action.  Consider the following code:

await Share.RequestAsync("title","text");  
await GetRootNavigation().Navigation.PopModalAsync(true);

### Steps to Reproduce

1.  create code that implements await Share.RequestAsync("title","text");  and on the following line, navigates somewhere else.
2. Execute this code and watch the navigation code fire immediately after the share dialog is opened, effectively closing the share dialog.
3.  Since the share dialog has been dismissed by the navigation code, it is impossible to share.

### Expected Behavior
The await Share.RequestAsync code should fire, display the share dialog, wait for the title/text to be shared in whatever way is selected, then once the share dialog is closed, execute the following line.  

### Actual Behavior
The await Share.RequestAsync code fires, briefly displays the share dialog, then the navigation code fires almost immediately and kills the share dialog.  

### Basic Information

- Version with issue:  Xamarin.Essentials 1.6.1
- Last known good version: ??
- IDE:  Visual Studio Professional 2019
- Platform Target Frameworks: 
  - iOS: 14.14.2.5 on mac, 14.8.0 on windows
  - Android: N/A
  - UWP:  N/A
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

n/a

### Reproduction Link

[ShareRequestAsyncAwaitBugRepro.zip](https://github.com/xamarin/Essentials/files/6099284/ShareRequestAsyncAwaitBugRepro.zip)

**Comment by jamesmontemagno** [comment]
Yes, this is the expected behavior as there is not APIs specifically to wait for a callback from other devices. It is more fire and forget.
