### ISSUE TITLE
bug  Failed to initialize Text to Speech engine. Exception.      

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/Essentials#1721]
Android has this error. Uwp is OK

await TextToSpeech.SpeakAsync("Hello World");

**Comment by jamesmontemagno** [comment]
It is possible that this can fail to initialize on devices that don't have tts engines like some emulators, please try it on a device.

**Comment by tenhilltree** [comment]
According to [https://developer.android.com/reference/android/speech/tts/TextToSpeech.Engine]

Apps targeting Android 11 that use text-to-speech should declare [INTENT_ACTION_TTS_SERVICE](https://developer.android.com/reference/android/speech/tts/TextToSpeech.Engine#INTENT_ACTION_TTS_SERVICE) in the queries elements of their manifest:
 <queries>
   ...
  <intent>
      <action android:name="android.intent.action.TTS_SERVICE" />
  </intent>
 </queries>
