### ISSUE TITLE
[Bug][WebAuthenticator] View=DecorView@6916c96[WebAuthenticatorIntermediateActivity] not attached to window manager

### ISSUE THREAD

**Issue by vincentcastagna** [xamarin/Essentials#1722]
### Description

- Using `AuthenticateAsync` through any provider with `WebAuthenticator`, if users cancel the login flow, once `TaskCanceledException` is raised, wait a few seconds until the exception stated is raised and causes a crash.

### Steps to Reproduce

1. Use Xamarin Essentials **1.6.0-pre4 or superior** 
2. Launch a simple web auth through `AuthenticateAsync `
3. Cancel the authentication flow
4. Notice, a `TaskCanceledException` is thrown, which is expected
5. Wait for a few seconds, the app will crash with the `"View=DecorView@6916c96[WebAuthenticatorIntermediateActivity] not attached to window manager" error 
`
### Expected Behavior

- No crash when cancelling flow 

### Actual Behavior

- Crash the app on **1.6.0-pre4 or superior**, previous versions works fine.

### Basic Information

- Version with issue:  >= 1.6.0-pre4 
- Last known good version: 1.6.0-pre3 or any previous version (was using 1.5.3.2 previous to update working too)
- IDE: VS 16.8.4
- Platform Target Frameworks: 
  - Android: 10 SDK 
- Android Support Library Version: Support 28.0.0.3 
- Nuget Packages: 
  - Xamarin Forms 5.0.0.2012 
  - Prism Forms 8.0.0.1909 
   - Acr User dialogs 7.1.0.442
   - PancakeView 2.1.0.714

- Affected Devices: ALL (tested on Android 11 & 10 & 9 )

Only changes I noticed in 1.6.0-pre4 from pre3 (which works) is this commit : https://github.com/xamarin/Essentials/commit/1bd8b652094f5ae29e8a27f4df82e3b724165a36

### Reproduction Link

I was unable for now to do a reproduction sample without all my projects source. I'm working on it. 
Tried on this Repo sample, updating to same forms version as stated (5.0.0.2012), but no issue ... So there might be something related to 1.6.0-pre4 and other packages.

**Comment by vincentcastagna** [comment]
Small update as I can't get to reproduce it consistantly in a sample. However it seems this happens also on 1.6.0-pre3 when the app is in background for a long time, and is reopen after a while (hours/days) 

```
JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
Java.Lang.IllegalArgumentException: View=DecorView@9c94c5d[WebAuthenticationCallbackActivity] not attached to window manager

JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
Dialog.Dismiss ()
AndHUD.<DismissCurrent>b__30_0 ()
AndHUD+<>c__DisplayClass30_0.<DismissCurrent>b__1 (System.Object state)
SyncContext+<>c__DisplayClass3_0.<Send>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.5(intptr,intptr)
java.lang.IllegalArgumentException: View=DecorView@9c94c5d[WebAuthenticationCallbackActivity] not attached to window manager
android.view.WindowManagerGlobal.findViewLocked WindowManagerGlobal.java:517
android.view.WindowManagerGlobal.removeView WindowManagerGlobal.java:426
android.view.WindowManagerImpl.removeViewImmediate WindowManagerImpl.java:126
android.app.Dialog.dismissDialog Dialog.java:389
android.app.Dialog.dismiss Dialog.java:371
mono.java.lang.RunnableImplementor.n_run(Native Method)
mono.java.lang.RunnableImplementor.run(Unknown Source:0)
android.os.Handler.handleCallback Handler.java:883
android.os.Handler.dispatchMessage Handler.java:100
android.os.Looper.loop Looper.java:241
android.app.ActivityThread.main ActivityThread.java:7604
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:492
com.android.internal.os.ZygoteInit.main ZygoteInit.java:941
```

@jamesmontemagno Maybe you got an idea ... or tracks that I can help investigate it ...

**Comment by jamesmontemagno** [comment]
Did you update to 1.6.1. 

It looks like this is coming from AndHUD -> https://github.com/xamarin/Xamarin.Forms/issues/8044

I would try without any dependencies to see where the issue is coming from.

**Comment by vincentcastagna** [comment]
Thank you for your answer. 

Yes I tried 1.6.1. I updated from 1.5.3.2 to 1.6.1 that's when I first met the issue. 
I said 1.6.0-pre4 or superior, because I don't reproduce it on 1.6.0-pre3. 
Link provided might help as I also have acr as dependency. 
Will provide more information as long as I investigate more.

**Comment by vincentcastagna** [comment]
@jamesmontemagno good catch. My eyes were blocked on the `View=DecorView@9c94c5d[WebAuthenticationCallbackActivity] `. 

So its not really ACR user dialogs that is to blame, but more how we implemented it. We show a snackbar when an error occured with the message inside. ACR will display it on top of the current activity. If the WebAuthenticator is closed to early, ACR might try to display the snackbar on a destroyed activity resulting in this error. Also confirmed it as I had the same error with your InAppBilling plugin sometimes.

Thanks !

**Comment by jamesmontemagno** [comment]
That makes sense :) Windows are tricky tricky!
