### ISSUE TITLE
[Bug]FilePicker in xamarin.essential not working

### ISSUE THREAD

**Issue by Barshan-Mandal** [xamarin/Essentials#1723]
FilePicker in xamarin.essential not working
![image](https://user-images.githubusercontent.com/74092409/110572044-db4e3780-8182-11eb-93cf-5632f2733337.png)

**Comment by Barshan-Mandal** [comment]
| Name | Value | Type
-- | -- | -- | --
◢ | $exception | {System.IO.DirectoryNotFoundException: Could not find a part of the path "/2203693cc04e0be7f4f024d5f9499e13/bb257b564d0140b69252fd25cfa7c064/file-sample_150kB.pdf".   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x00177] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.IO/FileStream.cs:223    at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.IO/FileStream.cs:96    at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int)   at System.IO.File.Create (System.String path, System.Int32 bufferSize) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:91    at System.IO.File.Create (System.String path) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:83    at Xamarin.Essentials.FileSystem.CacheContentFile (Android.Net.Uri uri) [0x0008f] in D:\a\1\s\Xamarin.Essentials\FileSystem\FileSystem.android.cs:252    at Xamarin.Essentials.FileSystem.EnsurePhysicalPath (Android.Net.Uri uri, System.Boolean requireExtendedAccess) [0x00034] in D:\a\1\s\Xamarin.Essentials\FileSystem\FileSystem.android.cs:87    at Xamarin.Essentials.FilePicker+<>c__DisplayClass2_0.<PlatformPickAsync>g__OnResult\|0 (Android.Content.Intent intent) [0x0003c] in D:\a\1\s\Xamarin.Essentials\FilePicker\FilePicker.android.cs:50    at Xamarin.Essentials.IntermediateActivity.OnActivityResult (System.Int32 requestCode, Android.App.Result resultCode, Android.Content.Intent data) [0x00035] in D:\a\1\s\Xamarin.Essentials\Platform\Platform.android.cs:398  --- End of stack trace from previous location where exception was thrown ---    at Xamarin.Essentials.FilePicker.PlatformPickAsync (Xamarin.Essentials.PickOptions options, System.Boolean allowMultiple) [0x0013e] in D:\a\1\s\Xamarin.Essentials\FilePicker\FilePicker.android.cs:56    at Atik_Last_Sure.AppShell.MenuItem_Clicked (System.Object sender, System.EventArgs e) [0x0002c] in F:\Atik Last Sure\Atik Last Sure\AppShell.xaml.cs:26 } | System.IO.DirectoryNotFoundException

**Comment by Barshan-Mandal** [comment]
Do xamarin community sleeps?Why dont they reply?

**Comment by jamesmontemagno** [comment]
I am unable to reproduce this locally.

**Comment by Barshan-Mandal** [comment]
May I send you the source code?

**Comment by jamesmontemagno** [comment]
If you can upload it to a github repo that would be deal.

**Comment by Barshan-Mandal** [comment]
But github doesn't allow to upload a file more than 25 mb.please download it from google drive
href="https://drive.google.com/drive/folders/1o6JQg13PSMdZHHu08_rnl8zA6Q19b02j?usp=sharing"

**Comment by jamesmontemagno** [comment]
Add a gitignore file to your root directly and then sync it with github.

https://github.com/xamarin/Essentials/blob/main/.gitignore

**Comment by Barshan-Mandal** [comment]
https://github.com/Barshan-Mandal/Problem-In-Code

**Comment by softlion** [comment]
Use fileData.OpenReadAsync(), don't use FullPath

**Comment by jfversluis** [comment]
This seems to be resolved 🎉
