### ISSUE TITLE
WebAuthenticator crashes in Android 11

### ISSUE THREAD

**Issue by 78fede78** [xamarin/Essentials#1724]
I wanted to report that webauthenticator crashes on Android11 (api level 30).

var authUrl = new Uri(Settings.Website + "/mobileauth/" + scheme);
var callbackUrl = new Uri("cxxx://");
r = await WebAuthenticator.AuthenticateAsync(authUrl, callbackUrl);

The same code on previous Android versions works perfectly. 
i am using the latest versions released on nuget.

Xamarin.Essential 1.6.1

The target framework is Android 11.0 R
I am attaching the log file traced by AppCenter
[log.txt](https://github.com/xamarin/Essentials/files/6117634/log.txt)

**Comment by vincentcastagna** [comment]
Can you try with release 1.6.0-pre3 checking if you don't have the exception, and then try with 1.6.0-pre4 checking if you got it too. 
Not the same error in your logs, but, might be related to #1722

**Comment by 78fede78** [comment]
Thank you very much for your work.
 I solved my problem.
Just add this to AndroidManifest.xml:
```
<queries>
    <intent>
      <action android:name="android.support.customtabs.action.CustomTabsService" />
    </intent>
 </queries>
 
```
 I followed these links: 
 
  https://github.com/xamarin/Essentials/issues/1586 
 
 https://github.com/Px7-941/IssueWebAuthenticator1626/tree/main/LoginTest.Android
