### ISSUE TITLE
[Enhancement] Enable/Disable IdleTimer

### ISSUE THREAD

**Issue by Hackmodford** [xamarin/Essentials#1725]
## Summary

Proposal for the ability to keep the screen awake.

## API Changes

Could be a very simple API.

`DisableIdleTimer()`
`EnableIdleTimer()`

## Intended Use Case

For those cases where one wishes to stop the device from turning the screen off.
Example: Player controls in a media app.

**Comment by jamesmontemagno** [comment]
This exists :) https://docs.microsoft.com/en-us/xamarin/essentials/device-display

```
 DeviceDisplay.KeepScreenOn = true;
```

**Comment by Hackmodford** [comment]
Thanks! I searched for that and failed to find it. Thought I must have been missing something.
