### ISSUE TITLE
[Bug] UWP App failing to decrypt data from SecureStorage following windows update

### ISSUE THREAD

**Issue by MitchBomcanhao** [xamarin/Essentials#1727]
### Description
Following a Windows update, the app can no longer access secure storage to retrieve previously saved values, failing with the following message:
```
<PlatformGetAsync>d__5.MoveNext ()
d:\a\1\s\Xamarin.Essentials\SecureStorage\SecureStorage.uwp.cs at 23, line 13
System.Exception: The specified data could not be decrypted
```

10.0.18363.1379 - original windows build
10.0.18363.1440 - windows build after update

Has anyone ever had a similar problem?

### Basic Information

- Version with issue: 1.5.3.2
- Last known good version: n/a
- Platform Target Frameworks: 
  - UWP:  19041

**Comment by MitchBomcanhao** [comment]
Our only lead at the moment is a Known issue in the relevant windows update:
`System and user certificates might be lost when updating a device from Windows 10, version 1809 or later to a later version of Windows 10`
So my assumption is that the user will have to rollback the system to the previous version and/or reinstall our application.

**Comment by jamesmontemagno** [comment]
Yeah, in this case you may want to try/catch it and then remove the key and re-add it. Can't do much if it is an OS level thing....


Just using standard APIs -> https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/SecureStorage/SecureStorage.uwp.cs 

Unfortunate would have to be reported to the Windows API team as it is an issue with the core.
