### ISSUE TITLE
[Bug] Android - App Action fires on every resume if Single Task app initially started using an App Action

### ISSUE THREAD

**Issue by GingerSquid** [xamarin/Essentials#1728]
### Description
If you have an Android app with launch mode set to Single Task, and launch the app initially with an App Action, every time the app resumes from that point on will trigger the App Action the app was initially launched with.

### Steps to Reproduce

1. Make sure the Xamarin Essentials Sample app is configured to use launchMode="singleTask"
2. Install the Xamarin Essentials Sample app and launch it via an App Action
3. Open a different app so the Xamarin Essentials Sample app moves to the background
4. Use task switcher to switch back to the Xamarin Essentials Sample app 

### Expected Behavior
The Xamarin Essentials Sample app resumes without triggering the initial App Action

### Actual Behavior
The Xamarin Essentials Sample app resumes and triggers the initial App Action again

### Basic Information

- Version with issue: 1.6.1
- Last known good version: ??
- IDE: Visual Studio 2019 Enterprise
- Platform Target Frameworks:
  - Android: 10
- Affected Devices:
  - Pixel 2

**Comment by jamesmontemagno** [comment]
I wasn't able to reproduce this. We follow what the intent passes us, so if it is coming in as an App Action from Android itself then that is what is triggered.

**Comment by TrofimovEugene** [comment]
I got the exact same bug. The command is executed every time the application is taken out of the background if it was started with this action. Also in my case it doesn't depend on launchMode.
