### ISSUE TITLE
OpenAsync Launcher or browser how to restrict file access

### ISSUE THREAD

**Issue by ymebrugts** [xamarin/Essentials#1732]
Hi,

In Android webview you can set `setAllowFileAccess(false);` to restrict file access. 
How can I do the same for Launcher/Browser.OpenAsync? 

Greetings,
Yme

**Comment by jamesmontemagno** [comment]
When you launch with Launcher it launches an external app so isn't part of your app. Browser uses chrome custom tabs which again isn't part of your app so won't have file access.
