### ISSUE TITLE
GetLastKnownLocationAsync returns null when network service is closed

### ISSUE THREAD

**Issue by ValentinCerneanu** [xamarin/Essentials#1737]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/main/SUBMITTING-ISSUES.md)

### Steps to Reproduce

1. Turn off the internet
2. Turn off the location
3. Turn on the location (we still have no internet connection, no wifi, no carrier)
4. GetLocationAsync() and GetLastKnownLocationAsync() return null

### Expected Behavior
We expect to get location. Given the fact that the device has no internet connection we understand why GetLocationAsync return null, but why GetLastKnownLocationAsync return null? Why is there no cached data?

### Actual Behavior
GetLastKnownLocationAsync returns null

### Basic Information

- Version with issue: I tested with 1.2.0 - 1.4.0
- Last known good version: -
- IDE: Visual Studio
- Platform Target Frameworks:
  - Android: 10
- Android Support Library Version: 

Code:

```
        var request = new GeolocationRequest(GeolocationAccuracy.Best);
        var cancellation = new CancellationTokenSource();
        cancellation.CancelAfter(timeoutInMilliseconds);      

        var task = Task.Run(async () => await Geolocation.GetLocationAsync(request, cancellation.Token));
        var location = task.Result;

        var task2 = Task.Run(async () => await Geolocation.GetLastKnownLocationAsync());
        var lastLocation = task2.Result;
        
        //location and lastLocation are null in scenario described above
        Location finalLocation;
        if (location != null)
             finalLocation = location;
        if (lastLocation != null)
             finalLocation = lastLocation
```

**Comment by jamesmontemagno** [comment]
Every device will handle this different and when they turn on providers. I have mostly seen the getlocation work fine after this. Test on my pixel 2 and my emulator here and that worked just fine. Last known location is most likely wipped out after. There is nothing here we can do as this is at the Android level.
