### ISSUE TITLE
So, for this you will have to migrate to Package References instead of the old packages.config file. Simply open up VS 2019 right click on that packages.config and click migrate! Everything in your life will be better!

### ISSUE THREAD

**Issue by grockland** [xamarin/Essentials#1740]
So, for this you will have to migrate to Package References instead of the old packages.config file. Simply open up VS 2019 right click on that packages.config and click migrate! Everything in your life will be better!

_Originally posted by @jamesmontemagno in https://github.com/xamarin/Essentials/issues/1204#issuecomment-607467372_

**Comment by grockland** [comment]
I am not able to migrate to Package References for certain reasons, and have not been able to load Xamarin.Essentials from nuget with the characteristic error as suggested in the original post.  Has there been a fix for the bug that made going from the .config file to Package References necessary?

**Comment by jamesmontemagno** [comment]
Sorry, unfortunately this is a requirement due to limitations.
