### ISSUE TITLE
[Bug] FilePicker.PickAsync returns different path for Android 10 and 11.

### ISSUE THREAD

**Issue by gayugokhale** [xamarin/Essentials#1746]
### Description
When I try to pick file from file explorer in Android 10 & 11 devices, It copies picked file to App specific folder. and returns the path of app specific folder instead of returning the actual file path(for example Downloads). Also the file copied to app folder can not be opened so getting corrupt file error when trying to access that file path in the code.
### Steps to Reproduce

     string filepath = string.Empty;
        async Task PickAndShow()
        {
            try
            {
                var result = await FilePicker.PickAsync(PickOptions.Default);
                if (result != null)
                {
                    filepath = result.FullPath;
                }
            }
            catch (Exception ex)
            { }
        }

the `result.FullPath` contains path like this `/storage/emulated/0/Android/data/com.companyname.appname/cache/2203693cc04e0be7f4f024d5f9499e13/8bba0b6ad0d24292922d2bf729d82856/ItemMaster_20210408103306.xlsx`. 

### Expected Behavior

It should contain actual path for that file. In this case `Downloads` folder path.

### Actual Behavior

Not getting correct path for android 10 & 11. But working fine on Android 7.1.2

### Basic Information

- IDE: Visual Studio & Visual studio for mac
- Platform Target Frameworks: 
  - Android: Android 10 & 11 
- Affected Devices: Not working on Samsung M31(Android 11) & Realmi narzo 20A(Android 10).
- Working on : Redmi 4(Android 7.1.2)

**Comment by Jakar510** [comment]
See [IFileService](https://github.com/Jakar510/Jakar.Api/blob/master/src/Jakar.Api/Share.cs). This will allow you to share/access the file. Google changed how apps can access files with Android 10+. Also, see [SO Post](https://stackoverflow.com/questions/62839083/how-do-i-download-a-file-on-both-android-x-and-ios-that-is-publicly-available-u)

Note that iOS cannot do this. Apple, *in their infinite wisdom*, prevents apps from directly sharing files with another app (deep linking for example) except when you share it to an app you own (app group, I believe they call it?) You *must* share and have the user manually select the other app.

**Comment by dimonovdd** [comment]
See the [documentation](https://docs.microsoft.com/en-us/xamarin/essentials/file-picker?context=xamarin%2Fxamarin-forms&tabs=ios#pick-file)
You should use `OpenReadAsync` method. The path you see is a temporary path. 
If you need the path to the file, look at [this sample](https://github.com/xamarin/Essentials/blob/7218ab88f7fbe00ec3379bd54e6c0ce35ffc0c22/Samples/Samples/ViewModel/FilePickerViewModel.cs#L114).

Don't use `FullPath`.

**Comment by jamesmontemagno** [comment]
As noted this is the correct functionality

**Comment by snice1981** [comment]
Hi

I understand that Google changed its APIs regarding the file access, but how can I achieve such scenario:

1. Prompt user to select an existing csv file (typically in Download folder)
2. Do some change inside that file
3. Save it in original location (e.g: Download folder)

I know I can copy it locally as suggested by @dimonovdd but that's not what I need because the app is doing stuff and record its state in that file. So if I copy it each time, it will lose its state.
