### ISSUE TITLE
Map.OpenAsync prompt for Installed map apps

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#1752]
Hi,

Please make the Map.OpenAsync to optionally prompt for installed apps or go to the default map app on the device.

Currently, I have Apple Maps and Google Maps on my iPhone and it's going to Apple Maps.

Something like this will do:

```
    public async Task NavigateToBuilding25()
    {
        var location = new Location(47.645160, -122.1306032);
        var options =  new MapLaunchOptions { Name = "Microsoft Building 25", **DefaultMap = true** };

        try
        {
            await Map.OpenAsync(location, options);
        }
        catch (Exception ex)
        {
            // No map application available to open
        }
    }

```

DefaultMap [true | false]
if DefaultMaps set to true it will open the default map app
if DefaultMaps set to false it will prompt to select which map app
if DefaultMaps set to false and only one map is installed it will ignore and it will open the default app

Thanks,
Jassim

**Comment by jamesmontemagno** [comment]
You can use Launcher to do this today with the "geo:" url.
