### ISSUE TITLE
Null Problem in Location

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#1753]
Hi,

In the attached project, I am not able to get the location details, and lat and long shows zero.

Kindly advice..

[LocationApp.zip](https://github.com/xamarin/Essentials/files/6303684/LocationApp.zip)

Thanks,
Jassim

**Comment by jamesmontemagno** [comment]
You must set permissions in your projects -> https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?context=xamarin%2Fxamarin-forms&tabs=android

![image](https://user-images.githubusercontent.com/1676321/114575120-bab84800-9c2e-11eb-83c6-8b9e23f7c0a5.png)

**Comment by jamesmontemagno** [comment]
You also need to change your method to:

```csharp
public async Task GetLocationDetails()
```


The error in your code is that you actually create 2 `location` properties

```
        Location location;

        public async Task GetLocationDetails()
        {
            try
            {
                var request = new GeolocationRequest(GeolocationAccuracy.Default);

                //THIS CAUSES AN ISSUE! Remove var or remove your private variable
                var location = await Geolocation.GetLastKnownLocationAsync();

                if (location == null)
                {
                    location = await Geolocation.GetLocationAsync(request);
                }
```
