### ISSUE TITLE
[Bug] iOS: Swipe down to close MediaPicker.PickPhotoAsync navigates back to initial viewcontroller

### ISSUE THREAD

**Issue by MikaelStalvik** [xamarin/Essentials#1757]
### Description
If you swipe down the MediaPicker.PickPhotoAsync on iOS to cancel the modal dialog, the ViewController is dismissed and the user is navigated back to the applications root page.

### Steps to Reproduce

1. Open the PickPhoto modal dialog on iOS 
2. Swipe down to cancel

### Expected Behavior

The modal shall close just in the same way as if Cancel were pressed and the application shall be able to handle the result.

### Actual Behavior

The modal is closed and the user is navigated back to the root page. 
Swipe down to close the modal dialog shall work in the same was as if you are pressing Cancel and trigger the same code.

### Basic Information

- Version with issue: 1.6.1
- Last known good version: -
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  13.x+
- Affected Devices: iOS devices

**Comment by rhult** [comment]
Could be good to add that it's probably the following line that it causing the issue: 
https://github.com/xamarin/Essentials/blob/7218ab88f7fbe00ec3379bd54e6c0ce35ffc0c22/Xamarin.Essentials/MediaPicker/MediaPicker.ios.cs#L83
When the user swipes down, the modal is already dismissed, so the parent view controller will be dismissed.

**Comment by dimonovdd** [comment]
I do not think that this is a bug, the method works correctly and returns null.

https://user-images.githubusercontent.com/59065470/114756334-5054f400-9d63-11eb-97c8-ea057f85d3b7.mov

**Comment by rhult** [comment]
If you present the picker from a modal vc, the line above will dismiss the modal vc. When the user swipes down, the dismissing has already been done on the picker. You can't call dismiss at that point, you are dismissing a vc you don't own.

**Comment by dimonovdd** [comment]
@rhult @MikaelStalvik Can you send a sample?

**Comment by MikaelStalvik** [comment]
@dimonovdd Here's a sample:
https://www.dropbox.com/s/2avuqc5sq3uja5d/EssentialsNav.zip?dl=0

To reproduce the issue, perform these steps:
1) Start app. A blue screen is shown for two seconds, then a red screen appears
2) From the red screen, click "Pick photo"
3) Click the Cancel button => the modal dialog disappears and the red screen remains
4) Click "Pick photo"
5) Swipe-down to hide the modal dialog

Actual result:
You can see that the blue screen is showed for a while and after that the red screeen opens again.

Expected result:
Closing the modal dialog with swipe-down shall behave in the same way as in step 3 above.

**Comment by dimonovdd** [comment]
I'll watch it this weekend
