### ISSUE TITLE
[Enhancement] Possibility to select ModalPresentationStyle in MediaPicker.PickPhotoAsync for iOS

### ISSUE THREAD

**Issue by MikaelStalvik** [xamarin/Essentials#1758]
## Summary
Today the modal is not covering the full screen since it does use the default value, PageSheet.

## API Changes
Possibly this can be introduced as a property in MediaPickerOptions?
It does only apply to iOS.

## Intended Use Case
It's not always sure that you would like to provide the possibility to cancel the photo picker dialog via a slide down.
By displaying this dialog in optional full-screen the end-user will not be able to cancel the dialog via swipe-down.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
