### ISSUE TITLE
[Bug] WebAuthenticator -> You must subclass the `WebAuthenticatorCallbackActivity` and create an IntentFilter for it which matches your `callbackUrl`.

### ISSUE THREAD

**Issue by denz96** [xamarin/Essentials#1764]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/main/SUBMITTING-ISSUES.md)

### Steps to Reproduce

1.  use "xamarinessentials://ABC" in the WebAuthenticationCallbackActivity subclass
2.  use "xamarinessentials://ABC" in the webauthenticator.authenticationasync callback uri

### Expected Behavior
app should open website for login
### Actual Behavior
error encountered You must subclass the `WebAuthenticatorCallbackActivity` and create an IntentFilter for it which matches your `callbackUrl`.
### Basic Information

- Version with issue:
- Last known good version: unknown

- IDE: Visual studio for mac
- Platform Target Frameworks: android
  - iOS:  
  - Android: API 29
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: xamarin essentials
- Affected Devices:

### Screenshots
<img width="880" alt="Screen Shot 2021-04-17 at 9 47 12 AM" src="https://user-images.githubusercontent.com/8554222/115098337-2b7a9f80-9f62-11eb-8655-2cd7e74745ef.png">
<img width="661" alt="Screen Shot 2021-04-17 at 9 47 35 AM" src="https://user-images.githubusercontent.com/8554222/115098342-2fa6bd00-9f62-11eb-9779-1545a2d8fd72.png">
<img width="1017" alt="Screen Shot 2021-04-17 at 9 48 00 AM" src="https://user-images.githubusercontent.com/8554222/115098343-30d7ea00-9f62-11eb-8618-0ff5b3c4cfa8.png">

**Comment by jamesmontemagno** [comment]
This is an example:

```csharp
    [Activity(NoHistory = true, LaunchMode = LaunchMode.SingleTop)]
    [IntentFilter(new[] { Intent.ActionView }, Categories = new[] { Intent.CategoryDefault, Intent.CategoryBrowsable }, DataScheme = "xamarinessentials")]
    public class WebAuthenticationCallbackActivity : Xamarin.Essentials.WebAuthenticatorCallbackActivity
    {
    }
```

**Comment by denz96** [comment]
hi @jamesmontemagno,

In the Webauthenticator.Authenticateasync method, the 2nd parameter is a callbackuri, the callbackuri to be inputted there is the one we registered in the backend side? or it will not matter since we already added the registered callbackuri in the authorizeurl passed in the 1st paramete?
