### ISSUE TITLE
[Bug] Geocoder not recognizing some zip codes on Android only

### ISSUE THREAD

**Issue by johnsheatjx** [xamarin/Essentials#1767]
### Description
Giving the Geocoder certain zip codes as input strings is causing it to return a result of 0 for both lat and long. 
### Steps to Reproduce

1. call GetPositionsForAddressAsync() with a string input of "06333"

### Expected Behavior
The call should return a Location object with the coordinates for "East Lyme, CT"
### Actual Behavior
The call is returning a Location object with the longitude and latitude set to 0.
### Basic Information
This is strange behavior as this was working fine before with the exact same input but is not not working. Note that other zip codes we try are accurate, including ones right around it. Even searching with the text "East Lyme, CT" is working.  Also failing for the zip codes 06332 & 12029
- Version with issue: v1.6.1
- This seemed to be working in v1.5.3.2 as well but is not anymore
- IDE: Visual Studio Community Mac v8.9.2
- Platform Target Frameworks: 
  - Android: 
    SDK Tools Version: 26.1.1
    SDK Platform Tools Version: 31.0.1
    SDK Build Tools Version: 30.0.2 
    Xamarin Android: Version: 11.2.2.1 (Visual Studio Community)

**Comment by jamesmontemagno** [comment]
This would be a core issue with the Android platform as we call the native APIs.
