### ISSUE TITLE
[Enhancement] Consider making IsSupported Public

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#1768]
## Summary
An internal property exists on most sensors called IsSupported indicating feature support on the device. When having to monitor different sensors at the same time this results in very ugly codes with repeating try/catch blocks as the only way to see whether the feature is supported is try/catching around the start method. 
## API Changes

Add public IsSupported boolean on several sensors (Gyroscope, barometer, accelerometer etc.)

## Intended Use Case
Reduce the try catch blocks to check for feature availability, which is also way less expensive than catching exceptions as some checks for support are a simple null check

**Comment by dimonovdd** [comment]
dublicate #77

**Comment by rdeveen** [comment]
Agree, now you have to cache FeatureNotSupportedException if the device does not support sensor. Would be better to check if de sensor is supported befoure using it.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
