### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Nikitkao** [xamarin/Essentials#1769]
var locationWhenInUseRequest = await Permissions.RequestAsync<Permissions.LocationWhenInUse>();
if(locationWhenInUseRequest != PermissionStatus.Granted)
{
    return false;
}

var locationAlwaysRequest = await Permissions.RequestAsync<Permissions.LocationAlways>();
if (locationAlwaysRequest != PermissionStatus.Granted)
{
    return false;
}

return true;

### Expected Behavior

That code will trigger system popup that ask location permission and if you accept while in use then another popup will ask you to change for location always permission

### Actual Behavior

Second popup, with location always request skipped and in code that line "await Permissions.RequestAsync<Permissions.LocationAlways>();" just freeze.

### Basic Information

- Version with issue: 1.6.1
- Last known good version:
- IDE: vs for mac
- Platform Target Frameworks: ios
  - iOS: Version: 14.14.2.5 (Visual Studio Community)
- Nuget Packages: 
- Affected Devices: iphone x

**Comment by jamesmontemagno** [comment]
[App1.zip](https://github.com/xamarin/Essentials/files/6354282/App1.zip)
Worked fine for me, check your info.plist for all 3 settings
