### ISSUE TITLE
Pick Photo API

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#177]
## Description of the Feature

Ability to pick a photo from the camera roll.

## API Declaration

- MediaFile ImagePicker.PickPhotoAsync();
- IEnumerable<MediaFile> ImagePicker.PickPhotosAsync();

## Additional Classes or Structs needed
- Media File is an option here with the stream, information?

## Documentation links for supported platforms

* [Android Document](https://developer.android.com/guide/topics/media/camera.html)
* [iOS Document](https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture)
* [UWP Document](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/)

> VS bug [#735677](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735677)

**Comment by Redth** [comment]
Multi picker is a good idea, we should look at this.

**Comment by pictos** [comment]
Can not this be added to issue #251 ?

**Comment by pictos** [comment]
In this plugin, for [FilePicker](https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows) you can get any file type in the device. To me mades more sense create a global file picker and use the type of file to handle...

If we want to get a PDF file, just configure the FilePicker to filter the files ends with ".pdf", if you want a image, configure the filter to get ".jpg, .png,.gif". 

 I think my english isn't good, so here's an example: Please [look this sample](https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/blob/4c485c0df57840adddfc92033617c5b6a95fdccf/samples/Plugin.FilePicker.Sample.Forms/Forms/MainPage.xaml.cs#L19)

**Comment by Redth** [comment]
I think we'll have some sort of generic FilePicker as well.  The point here is that Photo picking is a very common use case for this, so it may be a superset of the FilePicker.  You'd still be able to make the FilePicker pick photos, but we want a super easy API for getting photos specifically.

**Comment by pictos** [comment]
We can do that, just call the FilePicker internally and pass the extentions as parameters. If you want i can try do this.

**Comment by Redth** [comment]
Before any implementation is started, we need to agree on a spec internally which is only partially completed for this.

**Comment by Mikilll94** [comment]
Ping! Is there any progress on this?

**Comment by minaairsupport** [comment]
we need this badly now after you implement permissions inside Xamarin essential 

when I tried to implement an image picker after removing Plugin. Permissions it's not working on the first time, so I bring permissions plugin back again 

```
 var photoStatus = await Permissions.RequestAsync<Permissions.Photos>();
                var storageStatus = await Permissions.RequestAsync<Permissions.StorageRead>();
                if (photoStatus == PermissionStatus.Granted && storageStatus == PermissionStatus.Granted)
                {
                    var mediaFile = await CrossMedia.Current.PickPhotoAsync();
                    await CompleteImageProcessing(mediaFile);
                }

...... // mainActivity
 public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            Plugin.Permissions.PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
```

**Comment by michaldivis** [comment]
Is this getting done anytime soon?

**Comment by lazmeister** [comment]
@michaldivis It looks like its planned. With Covid, it could take longer :(
