### ISSUE TITLE
[Bug] PermissionException: Permission request must be invoked on the main thread (with Geolocation on UWP)

### ISSUE THREAD

**Issue by janusw** [xamarin/Essentials#1771]
### Description

A `Xamarin.Essentials.PermissionException` is thrown whenever `Geolocation.GetLocationAsync` is called outside of the main thread ("Permission request must be invoked on the main thread"). This happens even if I make sure that the permission has been granted beforehand.

AFAICS it is ok to make a location request outside of the main thread, only requesting the permission must be done on the main thread. The problem is that each call to `Geolocation.GetLocationAsync` seems to trigger a permission request, even if the permission has already been granted. This effectively makes it impossible to query the location outside of the main thread on UWP. On Android and iOS this works fine.

### Steps to Reproduce

1. Check out the branch `janusw:uwp_geoloc_bug_repro` (https://github.com/janusw/Essentials/commits/uwp_geoloc_bug_repro)
2. Run Samples.UWP.
3. Go to the Geolocation section.
4. Click the lower Refresh button.

### Expected Behavior

The current location info is shown.

### Actual Behavior

Exception thrown: 'Xamarin.Essentials.PermissionException'
Unable to detect Location. Exception: Permission request must be invoked on the main thread.

### Basic Information

- Version with issue: 1.6.1
- Last known good version: ?
- IDE: VS 2019
- Platform Target Frameworks: 
  - UWP:  18362 (Windows 10 v1903)

### Reproduction Link

https://github.com/janusw/Essentials/commits/uwp_geoloc_bug_repro

**Comment by jfversluis** [comment]
See https://github.com/xamarin/Essentials/pull/1777#issuecomment-1845430702
