### ISSUE TITLE
[Enhancement] iOS ResizeImageWithAspectRatio option from jamesmontemagno / MediaPlugin

### ISSUE THREAD

**Issue by irinakush** [xamarin/Essentials#1773]
## Summary
Ability to resize image maintain aspect ratio.

Refer to ResizeImageWithAspectRatio in jamesmontemagno / MediaPlugin.

## API Changes && Intended Use Case

Implement this similar to the jamesmontemagno/MediaPlugin:

```
float percent = 0.5f;
var image = new UIImage(path);
image = image.ResizeImageWithAspectRatio(percent);
```

**Comment by dimonovdd** [comment]
#1640
#1541
