### ISSUE TITLE
[Enhancement] IsCameraAvailable option from jamesmontemagno / MediaPlugin

### ISSUE THREAD

**Issue by irinakush** [xamarin/Essentials#1774]
## Summary
Ability to check if a camera is available on the device.

Refer to IsCameraAvailable in jamesmontemagno / MediaPlugin.

## API Changes && Intended Use Case

Implement this similar to the jamesmontemagno/MediaPlugin:

```
if (MediaPicker.IsCameraAvailable)
    ...
```

**Comment by dimonovdd** [comment]
#77 
#1640
