### ISSUE TITLE
Record Audio API

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#178]
## Description of the Feature

Ability to record audio into a stream

## API Declaration

- Task AudioRecorder.StartAsync();
- AudioFile AudioRecorder.StopAsync();

## Additional Classes or Structs needed
- Audio File is an option here with the stream, information?

## Documentation links for supported platforms
* [Android Document](https://developer.android.com/guide/topics/media/camera.html)
* [iOS Document](https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture)
* [UWP Document](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/)

> VS bug [#735676](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735676)

**Comment by AmrAlSayed0** [comment]
Shouldn't Android documentation point to [MediaRecorder](https://developer.android.com/reference/android/media/MediaRecorder) instead of [Camera](https://developer.android.com/guide/topics/media/camera) ?

**Comment by Redth** [comment]
I'm not sure it's reasonable to do anything but record to some sort of temporary/intermediate file here.  

Is there a particular audio format and bitrate that is neutral / optimal across all the platforms?  
AudioFile is probably going to look something like:

```csharp
public Stream ReadAsStreamAsync();
int Bitrate { get; }
AudioFormat Format { get; }
```

**Comment by Redth** [comment]
And it's not a problem to record with a consistent audio bitrate cross the platforms?

Does PInvoke on UWP cause any issues or require special considerations for the app store?

**Comment by Mrnikbobjeff** [comment]
No, consistent Bitrate should not be a problem. While we may not be able to guarantee a specific bitrate for every device, we can definitely allow the user to query supported bitrates and select their preset. For 99%+ of devices this will be a value supported on all platforms. As for your second question, to be more specific we don't need PInvoke but rather COM Interop, I threw together the terms though. I am not 100% sure that it absolutely requires it, but the Implementation we used to work with used it to manipulate native unmanaged buffers. With the MediaCapture class I can not learn enough from the docs to be able to evaluate whether their behaviour matches that of other platforms.

**Comment by jamesmontemagno** [comment]
Probably something like Adrian's https://github.com/adrianstevens/Xamarin-Plugins/tree/master/SimpleAudioRecorder

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
