### ISSUE TITLE
Support write file access for Launcher in Android

### ISSUE THREAD

**Issue by pp111** [xamarin/Essentials#1793]
## Summary
Currently files opened with 
`
var openFileRequest = new Xamarin.Essentials.OpenFileRequest(title, new Xamarin.Essentials.ShareFile(filePath));
Xamarin.Essentials.Launcher.OpenAsync(openFileRequest);
`

are opened read only on Android. If the target application tries to save the file an error is raised.

## API Changes

To allow write access:

In the file:
`Xamarin.Essentials/Launcher/Launcher.android.cs`

Function:
`static Task PlatformOpenAsync(OpenFileRequest request)`

Just change:
`intent.SetFlags(ActivityFlags.GrantReadUriPermission);`

by
`intent.SetFlags(ActivityFlags.GrantReadUriPermission | ActivityFlags.GrantWriteUriPermission);`

## Intended Use Case
Edit application files using external tools

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
