### ISSUE TITLE
Xamarin.Essentials.Connectivity is never working on Xamarin.iOS/Android (not forms)

### ISSUE THREAD

**Issue by GreatSummit** [xamarin/Essentials#1798]
- Xamarin.Essentials.Connectivity always returns NetworkAccess.Internet on Xamarin.iOS/Android project
- Connectivity.ConnectivityChanged is never called whenever change my phone's connectivity.

**Comment by GreatSummit** [comment]
I had tested with other some utilities.
Xam.Plugin.Connectivity, Reachability.Net etc are also return always Connection enabled.
strange...
Could you help me, guys?
I need on Xamarin native (Xamarin.iOS and Android) not Forms.
Thanks.

**Comment by jamesmontemagno** [comment]
Will depend on your device that you have. Can you share your project? What device are you using? Did you try airplane mode?

**Comment by GreatSummit** [comment]
I am testing on iPhone 6 Plus with ios 12.5.2.
on iOS, I just checked only Connectivity.NetworkAccess before calling the backend API.
Always returns NetworkAccess.Internet in no wifi and air plane mode.
You can test that in the empty project (Xamarin.iOS native not Forms).

**Comment by GreatSummit** [comment]
Dear jamesmontemagno,
Could you help me with fixing this package so that it works on xamarin native (iOS/android) well?
It's urgent.
Thanks.

**Comment by GreatSummit** [comment]
Please try to create a new project by Xamarin.iOS not forms.
Xamarin.Essentials.Connectivity will not work.

**Comment by GreatSummit** [comment]
Dear jamesmontemagno, did you make the Xam.Plugin.Connectivity too?
That package is better than Xamarin.Essentials for Xamarin native (iOS/Android)?

**Comment by jamesmontemagno** [comment]
The two packages use the same code and logic as Xamarin.Essentials is an iteration on top of my old library and is the replacement. I can not reproduce it here as it is working for me.

Have you tried it on newer version of iOS?

Also, have you check the connection profiles? you can also check those to see what is returned.

**Comment by GreatSummit** [comment]
I tested on iphone 6 plus without SIM. and I turn off wifi.
but it returns NetworkAccess.Internet and Connection Profiles is "wifi".

**Comment by GreatSummit** [comment]
![image](https://user-images.githubusercontent.com/29710877/120412619-72ddb380-c389-11eb-9b6b-63cc38495ee6.png)
As you can see, I added 3 packages in each iOS and Droid projects and called them in shared project.
All 3 packages are not working (IsOnline method returns always true even though no wifi)

**Comment by GreatSummit** [comment]
> The two packages use the same code and logic as Xamarin.Essentials is an iteration on top of my old library and is the replacement. I can not reproduce it here as it is working for me.
> 
> Have you tried it on newer version of iOS?
> 
> Also, have you check the connection profiles? you can also check those to see what is returned.

**Comment by GreatSummit** [comment]
Hey, jamesmontemagno
Could you help please?
Please let me know how I can implement in Xamarin native not forms.
Thanks.

**Comment by jamesmontemagno** [comment]
For iOS you can try adding the code we use directly -> this file https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/Connectivity/Connectivity.ios.tvos.macos.reachability.cs

Then specifically this code -> https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/Connectivity/Connectivity.ios.tvos.macos.cs#L43-L51

**Comment by GreatSummit** [comment]
Thanks, but not working. I turned wifi off and tried also airplane mode, both returns Network Connection is ok.

**Comment by GreatSummit** [comment]
using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using CoreTelephony;
using CoreFoundation;
using SystemConfiguration;

namespace Reporto.iOS
{
    enum NetworkStatus
    {
        NotReachable,
        ReachableViaCarrierDataNetwork,
        ReachableViaWiFiNetwork
    }

    static class ConnectivityHelper
    {
        static readonly Lazy<CTCellularData> cellularData = new Lazy<CTCellularData>(() => new CTCellularData());
        internal static CTCellularData CellularData => cellularData.Value;

        public static bool IsConnected
        {
            get
            {
                var restricted = CellularData.RestrictedState == CTCellularDataRestrictedState.Restricted;
                var internetStatus = Reachability.InternetConnectionStatus();
                if ((internetStatus == NetworkStatus.ReachableViaCarrierDataNetwork && !restricted) || internetStatus == NetworkStatus.ReachableViaWiFiNetwork)
                    return true;

                var remoteHostStatus = Reachability.RemoteHostStatus();
                if ((remoteHostStatus == NetworkStatus.ReachableViaCarrierDataNetwork && !restricted) || remoteHostStatus == NetworkStatus.ReachableViaWiFiNetwork)
                    return true;

                return false;
            }
        }
    }

    static class Reachability
    {
        internal const string HostName = "www.microsoft.com";

        internal static NetworkStatus RemoteHostStatus()
        {
            using (var remoteHostReachability = new NetworkReachability(HostName))
            {
                var reachable = remoteHostReachability.TryGetFlags(out var flags);

                if (!reachable)
                    return NetworkStatus.NotReachable;

                if (!IsReachableWithoutRequiringConnection(flags))
                    return NetworkStatus.NotReachable;

#if __IOS__
                if ((flags & NetworkReachabilityFlags.IsWWAN) != 0)
                    return NetworkStatus.ReachableViaCarrierDataNetwork;
#endif

                return NetworkStatus.ReachableViaWiFiNetwork;
            }
        }

        internal static NetworkStatus InternetConnectionStatus()
        {
            var status = NetworkStatus.NotReachable;

            var defaultNetworkAvailable = IsNetworkAvailable(out var flags);

            // If it's a WWAN connection..
            if ((flags & NetworkReachabilityFlags.IsWWAN) != 0)
                status = NetworkStatus.ReachableViaCarrierDataNetwork;

            // If the connection is reachable and no connection is required, then assume it's WiFi
            if (defaultNetworkAvailable)
            {
                status = NetworkStatus.ReachableViaWiFiNetwork;
            }

            // If the connection is on-demand or on-traffic and no user intervention
            // is required, then assume WiFi.
            if (((flags & NetworkReachabilityFlags.ConnectionOnDemand) != 0 || (flags & NetworkReachabilityFlags.ConnectionOnTraffic) != 0) &&
                 (flags & NetworkReachabilityFlags.InterventionRequired) == 0)
            {
                status = NetworkStatus.ReachableViaWiFiNetwork;
            }

            return status;
        }

        internal static IEnumerable<NetworkStatus> GetActiveConnectionType()
        {
            var status = new List<NetworkStatus>();

            var defaultNetworkAvailable = IsNetworkAvailable(out var flags);

            // If it's a WWAN connection.
            if ((flags & NetworkReachabilityFlags.IsWWAN) != 0)
            {
                status.Add(NetworkStatus.ReachableViaCarrierDataNetwork);
            }
            else if (defaultNetworkAvailable)
            {
                status.Add(NetworkStatus.ReachableViaWiFiNetwork);
            }
            else if (((flags & NetworkReachabilityFlags.ConnectionOnDemand) != 0 || (flags & NetworkReachabilityFlags.ConnectionOnTraffic) != 0) &&
                     (flags & NetworkReachabilityFlags.InterventionRequired) == 0)
            {
                // If the connection is on-demand or on-traffic and no user intervention
                // is required, then assume WiFi.
                status.Add(NetworkStatus.ReachableViaWiFiNetwork);
            }

            return status;
        }

        internal static bool IsNetworkAvailable(out NetworkReachabilityFlags flags)
        {
            var ip = new IPAddress(0);
            using (var defaultRouteReachability = new NetworkReachability(ip))
            {
                if (!defaultRouteReachability.TryGetFlags(out flags))
                    return false;

                return IsReachableWithoutRequiringConnection(flags);
            }
        }

        internal static bool IsReachableWithoutRequiringConnection(NetworkReachabilityFlags flags)
        {
            // Is it reachable with the current network configuration?
            var isReachable = (flags & NetworkReachabilityFlags.Reachable) != 0;

            // Do we need a connection to reach it?
            var noConnectionRequired = (flags & NetworkReachabilityFlags.ConnectionRequired) == 0;

            // Since the network stack will automatically try to get the WAN up,
            // probe that
            if ((flags & NetworkReachabilityFlags.IsWWAN) != 0)
                noConnectionRequired = true;

            return isReachable && noConnectionRequired;
        }
    }

    class ReachabilityListener : IDisposable
    {
        NetworkReachability defaultRouteReachability;
        NetworkReachability remoteHostReachability;

        internal ReachabilityListener()
        {
            var ip = new IPAddress(0);
            defaultRouteReachability = new NetworkReachability(ip);
            defaultRouteReachability.SetNotification(OnChange);
            defaultRouteReachability.Schedule(CFRunLoop.Main, CFRunLoop.ModeDefault);

            remoteHostReachability = new NetworkReachability(Reachability.HostName);

            // Need to probe before we queue, or we wont get any meaningful values
            // this only happens when you create NetworkReachability from a hostname
            remoteHostReachability.TryGetFlags(out var flags);

            remoteHostReachability.SetNotification(OnChange);
            remoteHostReachability.Schedule(CFRunLoop.Main, CFRunLoop.ModeDefault);
        }

        internal event Action ReachabilityChanged;

        void IDisposable.Dispose() => Dispose();

        internal void Dispose()
        {
            defaultRouteReachability?.Dispose();
            defaultRouteReachability = null;
            remoteHostReachability?.Dispose();
            remoteHostReachability = null;
        }

        void OnRestrictedStateChanged(CTCellularDataRestrictedState state)
        {
            ReachabilityChanged?.Invoke();
        }

        async void OnChange(NetworkReachabilityFlags flags)
        {
            // Add in artifical delay so the connection status has time to change
            // else it will return true no matter what.
            await Task.Delay(100);

            ReachabilityChanged?.Invoke();
        }
    }
}

------------------------------------

var isOnline = Reporto.iOS.ConnectivityHelper.IsConnected;
// isOnline is always true.

**Comment by GreatSummit** [comment]
![image](https://user-images.githubusercontent.com/29710877/120518705-6cd8e880-c404-11eb-9f10-babd1037e6fe.png)
As you can see, 4 methods all returns always true.

**Comment by jamesmontemagno** [comment]
what are the values of `restricted`, `internetStatus`, and `remoteHostStatus`?

```csharp
 var restricted = CellularData.RestrictedState == CTCellularDataRestrictedState.Restricted;
            var internetStatus = Reachability.InternetConnectionStatus();
            if ((internetStatus == NetworkStatus.ReachableViaCarrierDataNetwork && !restricted) || internetStatus == NetworkStatus.ReachableViaWiFiNetwork)
                return true;

            var remoteHostStatus = Reachability.RemoteHostStatus();
            if ((remoteHostStatus == NetworkStatus.ReachableViaCarrierDataNetwork && !restricted) || remoteHostStatus == NetworkStatus.ReachableViaWiFiNetwork)
                return true;
```

**Comment by GreatSummit** [comment]
restricted is false

**Comment by GreatSummit** [comment]
My final option is the following:
![image](https://user-images.githubusercontent.com/29710877/120519691-7ca4fc80-c405-11eb-9642-0f23c0c81c43.png)

But this disadvantage is to be frozen for a second approximately.
So I want to use the powerful package - Xamarin.Essentials.Connectivity.

**Comment by jamesmontemagno** [comment]
So it is saying you have WiFi... so I need to know what all values are being returned via: 
https://github.com/xamarin/Essentials/blob/7218ab88f7fbe00ec3379bd54e6c0ce35ffc0c22/Xamarin.Essentials/Connectivity/Connectivity.ios.tvos.macos.reachability.cs#L45-L72

**Comment by GreatSummit** [comment]
Let me check now

**Comment by jamesmontemagno** [comment]
Yeah, i mean i would not do what you are doing. I mean you would just call your API and if there is no interent then it will throw an exception... aka don't make a webrequest to test a connection if you are just about to make a web request.

**Comment by GreatSummit** [comment]
![image](https://user-images.githubusercontent.com/29710877/120520495-706d6f00-c406-11eb-9ead-b802f81c0b0c.png)

**Comment by GreatSummit** [comment]
Sorry, but do you have any xamarin.ios project (not forms)?

**Comment by GreatSummit** [comment]
![image](https://user-images.githubusercontent.com/29710877/120521339-6e57e000-c407-11eb-8c17-d565eca3fccc.png)

I am testing with turning on/off like on above screenshot.

**Comment by jamesmontemagno** [comment]
There is no difference between a Xamarin.Forms app and a Xamarin.iOS app when it comes to this functionality.

So we are getting closer... as the `defaultNetworkAvaialble` is returning true... so it thinks there is internet.

So, the important stuff is now in here -> https://github.com/xamarin/Essentials/blob/7218ab88f7fbe00ec3379bd54e6c0ce35ffc0c22/Xamarin.Essentials/Connectivity/Connectivity.ios.tvos.macos.reachability.cs#L105-L133


we need to really see what is in IsReachableWithoutRequiringConnection as it will tell us the reachability and if no connection is.

Also, it doesn't look like airplane mode is on in your photo, it looks like cellular is on.

**Comment by jamesmontemagno** [comment]
I just tested it on my iPhone 6 running iOS 12 and it worked perfect in airplane mode. Are you on the latest version of Xamarin.Essentials 1.6.1?

**Comment by jamesmontemagno** [comment]
[App3.zip](https://github.com/xamarin/Essentials/files/6586780/App3.zip)

here is an app working perfect out of the box with a single line of code form Xamarin.Essentials on my Iphone 6 with iOS 12

**Comment by GreatSummit** [comment]
Thanks for your sample project.
I tested App3 project.
Click Me button displays always "Internet" on airplane mode and no-wifi.
Maybe it seems to be phone problem.

**Comment by jamesmontemagno** [comment]
Yeah, seems to be a phone problem, maybe a vpn issue? do you have that on?

**Comment by GreatSummit** [comment]
Yep, I am using vpn.

**Comment by jamesmontemagno** [comment]
yeah, a VPN active will always return it is connected, so in this case you will have to turn off the VPN as it is taking credit for a connection. I will make sure this is documented.

**Comment by rameshkec85** [comment]
@jamesmontemagno I have enabled Network Link Conditions> 100% Loss , which means there is active connection but packets are dropping. So how can i check this there is no internet connection. As earlier i have used 

`CrossConnectivity.Current.IsRemoteReachable`
