### ISSUE TITLE
Enhancement: Launcher TryOpen return codes

### ISSUE THREAD

**Issue by czuck** [xamarin/Essentials#1816]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/main/SUBMITTING-ISSUES.md)

### Description
Currently Launcher.TryOpenAsync returns true or false.  Change this to return a code that indicates ok, app not installed, or app not authorized (on iOS).  This will allow me to display the proper message to the user, that they either need to install their app or update the app they are using to get a new info.plist.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Essentials is now in maintenance mode, this will not happen anymore for Xamarin.Essentials. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
