### ISSUE TITLE
[Bug] Access to DeviceDisplay.MainDisplayInfo crashes App on iOS 10.2

### ISSUE THREAD

**Issue by cpraehaus** [xamarin/Essentials#1818]
### Steps to Reproduce

1. Access DeviceDisplay.MainDisplayInfo on iOS 10.2

### Expected Behavior
Display info is returned.

### Actual Behavior
App crashes.

### Basic Information

- Version with issue: 1.6.1
- Last known good version: 1.5.3.2
- IDE:
- Platform Target Frameworks: 
  - iOS:  10.2
- Affected Devices: iPhone/iPad with iOS 10.2 or lower

The feature merged with #1443 accesses property ``maximumFramesPerSecond`` which was added with iOS 10.3 but is not supported/known on earlier iOS versions. Thus the app crashes with the following error:
[UIScreen maximumFramesPerSecond]: unrecognized selector sent to instance 0x10615b610

### Screenshots
NA

### Reproduction Link
NA

**Comment by cpraehaus** [comment]
Maybe related to #1679 ?

**Comment by Redth** [comment]
Fixed by #1731
