### ISSUE TITLE
Do Not Disturb API

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#1821]
Hi,

Please add a feature to enable and disable Do Not Disturb which is needed for video chat and video players app as well as EdTech apps

Something like:

```
await DoNotDisturb.TurnOnAsync();
await DoNotDisturb.TurnOffAsync();

await DoNotDisturb.TurnOnAsync().Until("1 hour/minutes, etc");


```
Thanks,
Jassim

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
