### ISSUE TITLE
[Enhancement] WPF Support for FilePicker

### ISSUE THREAD

**Issue by GeoDirk** [xamarin/Essentials#1827]
## Summary
FilePicker works great for Android,iOS, and UWP.  But WPF isn't supported.  Should be an easy one.

## Intended Use Case
For those of us who are using Xamarin Forms with a WPF front end.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
