### ISSUE TITLE
Cross platform geometey

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#183]
Rectangle, point, size, etc

**Comment by mattleibow** [comment]
Just a note:
https://docs.microsoft.com/en-us/dotnet/api/system.drawing?view=netstandard-2.0

`Point`, `Rectangle` and `Size` are available in .NET Standard 2.0

**Comment by jamesmontemagno** [comment]
nice! maybe we should have helpers to go to and from on each specific platform. maybe we drop netstandard1.0?
