### ISSUE TITLE
Liveness check of an image which is in front of Camera in Xamarin.Forms

### ISSUE THREAD

**Issue by jangra1981** [xamarin/Essentials#1831]
## Summary
Dear Team,

We are developing attendance app using Xamarin Forms and FACE API of Cognitive services. What we are doing is like this.

Registering Photo : When user clicks on this button we open the mobile camera , user click his/her photograph and then we submit that image to Face API . No issue in that we have successfully implemented/registered the same using Cognitive Face API services.

Verify User : When user clicks on this button again we open the camera, user click his/her photograph and then we send this image to FACE api for verification . No issue in that we have successfully implemented the same.

Now what issue we are facing is :-

On verification button, user shows his/her old saved photograph to camera and click its photo not the real live image. Obviously that matches the same and got verified successfully. Here we always want to take his/her live photo not the fake one because its attendance application also used to field staff. Any body can fool the app.

We want to stop clicking the fake images. We want to track liveness of the photo. If something available at camera level which can tell user not to show fake photos using any API

## API Changes

The MakeShiny API works even if the button is already visible.

## Intended Use Case
Provide a detailed example of where your proposal would be used and for what purpose.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
