### ISSUE TITLE
[Enhancement] Full functional Contacts management API

### ISSUE THREAD

**Issue by hxmcn** [xamarin/Essentials#1838]
## Summary
Add FULL functional APIs for read/list, write, update, remove contact(s) of the mobile phone contacts book.

## API Changes
I know there is Device.Contacts class for retrieve information from the Contacts (see [Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.contacts?view=xamarin-essentials) ),  but presently it only provides read contacts, no write/ update/remove methods for it.
Can add methods like:
bool Add(Contact c);
bool Update(Contact c);
bool Remove(Contact c);

**Comment by dimonovdd** [comment]
https://github.com/xamarin/Essentials/issues/1545

**Comment by jamesmontemagno** [comment]
Duplicated of #1545
