### ISSUE TITLE
[Bug] Detaching Connectivity Changes in App.xaml does not work in iOS 

### ISSUE THREAD

**Issue by developer9969** [xamarin/Essentials#1839]
### Description
I have added ConnectityChanged event in the app.xaml .All works in android.
In iOS it I cannot make it work and let me explain why

### Steps to Reproduce

1. sliding down the screen in iOS Physical device
2.  Put the phone in Plane Mode and remove wifi
3. Sleep event is fired and removed connectivity
4. ConnectivityChanged now is removed and therefore this never fires.
5. Noticed that in android the sleep event is not hit (as it should be) when you set the phone in plane mode

```
//App.Xaml

protected override void OnSleep()
{
    Connectivity.ConnectivityChanged -= OnConnectivityChanged;
}

protected override void OnStart()
{
    Connectivity.ConnectivityChanged += OnConnectivityChanged;
}



protected override void OnResume()
{
     Connectivity.ConnectivityChanged += OnConnectivityChanged;
}
```

Is this an issue with iOS and sleep firing when it shouldn't?

Should app.xaml not be used to handle connectivity changes?

**Comment by jamesmontemagno** [comment]
You are removing the event when you sleep, which is correct, but you wont get an update when you swipe down. You should check connectivity when you app resumes/starts.
