### ISSUE TITLE
Ios localization support for Permissions module

### ISSUE THREAD

**Issue by ForkBug** [xamarin/Essentials#1840]
Permissions module calls IsKeyDeclaredInInfoPlist before doing anything.
IsKeyDeclaredInInfoPlist  only checks Info.plist, But the privacy statements are in InfoPlist.strings files when the app has been localized.

**Comment by dimonovdd** [comment]
If you do everything correctly, the localization will be correct. For example delete the values from info.plist and leave only the keys.

**Comment by ForkBug** [comment]
> 
> 
> If you do everything correctly, the localization will be correct (This works in my app). For example delete the values from info.plist and leave only the keys.

You are right. 
Previously we left the values in the Info.plist file, and the localization didn't work.
And then we remove both the keys and values, the localization worked but no lucky for Essentials.Permissions.
Now we only remove the content of values, leaving <string></string>. It works fine!
Thank you!

**Comment by dimonovdd** [comment]
@ForkBug I'm glad I helped you
