### ISSUE TITLE
[Bug] Permissions.LocationWhenInUse adding ACCESS_BACKGROUND_LOCATION

### ISSUE THREAD

**Issue by wagenheimer** [xamarin/Essentials#1844]
### Description
I only use on my App :
`await Permissions.RequestAsync<Permissions.LocationWhenInUse>();`

On my AndroidManifest.xml I only have
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

But on uploading my executable to google, it's complaining :
![image](https://user-images.githubusercontent.com/315513/125304515-0baa0c00-e304-11eb-9092-fa609d0c71e7.png)

### Steps to Reproduce

1. Change AndroindManifest.xml and add permission ACCESS_FINE_LOCATION and ACCESS_COARSE_LOCATION
2. Use the code Permissions.RequestAsync<Permissions.LocationWhenInUse>();
3. Create the AAB executable
4. Send It to Google Play

### Expected Behavior
ACCESS_BACKGROUND_LOCATION should not be added if I don't use it.

### Actual Behavior
ACCESS_BACKGROUND_LOCATION is always being added!

### Basic Information
- IDE: Visual Studio 16.10.3
- Platform Target Frameworks: 
  - Android: 11

**Comment by jamesmontemagno** [comment]
This is a warning from Google as you are adding location permissions, but we do not add any permissions to your app. You can double check your final output in obj/Release/100/AndroidManifest.xml.

Double check other libraries you use.
