### ISSUE TITLE
[Bug] Android 10+ No way to show "Allow All The Time" on location permission popup, user must go to settings

### ISSUE THREAD

**Issue by AdamDiament** [xamarin/Essentials#1849]
### Description
On an android 11 device, when requesting LocationAlways permission, the user does not get the "all the time" option on the popup, only "whist using the app" and "only this time".

May be related to https://social.msdn.microsoft.com/Forums/en-US/e8984b33-c525-480f-ac58-c2e6e8a2152d/xamarin-essentials-geolocation-always-on-permission-on-android-doesnt-work-anymore?forum=xamarinforms

I am getting permission like this:

```
var permission = new Permissions.LocationAlways();
var status = await permission.RequestAsync();
```

The android manifest is correctly configured with the following permissions:
```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
```
The only way to get "all the time" permission is to direct the user to the settings page for the app, this isn't very intuitive. Additionally, when I redirect the user to settings programatically, and the user does grant the permission "all the time" through settings, the app still returns "denied" the first time that  await permission.CheckStatusAsync(); is called after returning from the app by using the top left arrow on the settings page.

### Steps to Reproduce

1. Run a fresh install on the reproduction project I have provided, on an android 10 or 11 device. Observe the popup that comes up does not contain the "all the time" permission.

### Expected Behavior
"All the time" permission option is shown on the popup

### Actual Behavior
It isn't

### Basic Information

- Version with issue: 1.7.0- Last known good version?: Although Android 9 works with 1.7
- IDE: Visual Studio 2019 16.10.3 for Windows
- Platform Target Frameworks: 
- Android: Min version 9, compiling for 11, running a samsung galaxy A4 on Android 11
- Nuget packages: Essentials 1.7
### Screenshots

**Android 11, not working**

![permission popup](https://user-images.githubusercontent.com/6513834/125624625-f47182da-9e3a-4036-85d8-4b7ab6e48e47.png)

**Android 9, working correctly (although with the expected single permission request)**
![image](https://user-images.githubusercontent.com/6513834/125626757-b9079f8a-e543-4aed-aa34-ebc9e16379ec.png)

### Reproduction Link

~I am creating a reproduction project, I will add it here shortly~ In my reproduction project, the popup doesn't appear at all on android 11. I may need to raise a new bug. Unless this is known? In the OnRequestPermissionsResult method I do get -1,-1,-1 back but the popup never shows

**Comment by jamesmontemagno** [comment]
See: https://github.com/xamarin/Essentials/issues/1580#issuecomment-742691701

**Comment by AdamDiament** [comment]
Ah! Thanks for the quick response @jamesmontemagno
