### ISSUE TITLE
[Bug] Cannot get location to work on Android 11 even If I have granted my app location permissions

### ISSUE THREAD

**Issue by alirazaethos** [xamarin/Essentials#1861]
### Description
I have my Xamarin Forms app that is using Xamarin.Essentials to get location updates. App is working fine on devices running Android 10 but If I deploy it on a device with Android 11, I can not get location coordinates. 

`Location location = await Geolocation.GetLocationAsync(
                    new GeolocationRequest(GeolocationAccuracy.High, TimeSpan.FromSeconds(10))
                  );`

The code above always return null even If I have provided my App AccessCoarseLocation and AccessFineLocation Permissions in the manifest file. 

@jamesmontemagno 

### Steps to Reproduce

1. Run above piece of code on a device running on Android 11.

### Expected Behavior

Get location coordinates in Location object. 

### Actual Behavior

returns null always. 

### Basic Information

- Version with issue: Android 11
- Last known good version: Android 10
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 11
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by arnelsalarda** [comment]
I am also experiencing the same issue

**Comment by acaliaro** [comment]
Is more complex to give location permissions from Android 11

Here a guide 

[Location ](https://developer.android.com/about/versions/11/privacy/location) 

Maybe there is a new sample for Xamarin Essentials

**Comment by ahoke-cr** [comment]
Also not working for me. I guess we will have to hope that the updated Essentials API in MAUI will address this.

**Comment by jamesmontemagno** [comment]
Hmmm it all still should work with 1 time even on Android 11. It is just background that really changed. I will look into it a bit more.

**Comment by jamesmontemagno** [comment]
Did you select precise or approximate. I think maybe that is a change. Custom permissions may need to be setup. https://developer.android.com/training/location/permissions#request-location-access-runtime

**Comment by ahoke-cr** [comment]
@jamesmontemagno hey James, thanks for following up. It's working for me now. Mistake on my part when writing a DI wrapper for the Geolocation class.
