### ISSUE TITLE
[Bug] Xamarin.Mac App Store rejection when using Xamarin.Essentials

### ISSUE THREAD

**Issue by mschoeffmann** [xamarin/Essentials#1863]
### Description
As soon as Xamarin.Essentials is used, the app gets rejected by the Mac App Store review process.

> We continue to find that your app links against the MapKit framework but does not appear to include Maps functionality. 
> 
> Next Steps
> 
> If your app does include Maps functionality, please respond to this message in Resolution Center with steps on how to locate it within your app.
> 
> If you do not intend to use Maps, please unlink the MapKit framework. If you would like to use Maps, please add the "com.apple.developer.maps" entitlement and submit an updated binary for review.
> 
> Resources
> 
> For information on Maps, please review the Location and Maps Programming Guide.
> 
> If you are using a third-party framework that links against the MapKit framework, you may want to contact the third-party framework provider for help on unlinking from it.

This is because it links to MapKit even if it's not used.

### Steps to Reproduce

1. Create a new Cocoa Mac App Project "test"
2. Project Options > Mac Build > Release > Set Add. MMP Arguments to `--registrar:dynamic --linkplatform`
3. Switch to "Release" and Build All
4. Run the command `otool -L bin/Release/test.app/Contents/MacOS/test | grep MapKit` (= empty result)
5. Add "Xamarin.Essentials" as NuGet package
6. Run the command `otool -L bin/Release/test.app/Contents/MacOS/test | grep MapKit` again (= MapKit result)

### Expected Behavior
Do not link MapKit it not used.

### Actual Behavior
Automatically linked MapKit, which results in App Store rejection. 
`/System/Library/Frameworks/MapKit.framework/Versions/A/MapKit (compatibility version 1.0.0, current version 0.0.0)`

### Basic Information

- IDE: Visual Studio for Mac 8.10.6
- Platform Target Frameworks:
  - macOS:  10.13 and up
- Nuget Packages:
  - Xamarin.Essentials 1.7.0

**Comment by jamesmontemagno** [comment]
Hmmmm, i use it in my app My Stream Timer -> https://github.com/jamesmontemagno/MyStreamTimer/ and it is in the app store currently.

I dont' set any MMP arguments though. I just set:
```
<LinkMode>SdkOnly</LinkMode>
```

**Comment by mschoeffmann** [comment]
Oh, thanks for this hint.
I searched a lot for a solution because the initial "Don't link" setting caused App Store rejections because of GameKit, MapKit and some private network frameworks.
All Google/StackOverflow/... solutions mentioned using `--registrar:dynamic` or better `--linkplatform` as MMP arguments.
But you hint to use `SdkOnly` works perfect here.
Thank you!
