### ISSUE TITLE
[Enhancement] CompassData should include an accuracy property

### ISSUE THREAD

**Issue by rbdavison** [xamarin/Essentials#1864]
## Summary
Adding an accuracy property to the CompassData would enable applications to know the quality of the data being provided and enable the application to alert the user of the device that they should recalibrate the compass.

## API Changes
Add an Enum for the accuracy or use an existing enum. Something along the lines of

    public enum CompassAccuracy
    {
        /// <summary>
        /// Not Calibrated or available in platform
        /// </summary>
        Unknown, 
        /// <summary>
        /// Calibration required
        /// </summary>
        Low, 
        /// <summary>
        /// Calibration recommended but not required
        /// </summary>
        Medium, 
        /// <summary>
        /// Calibration is good. nothing to do.
        /// </summary>
        High,
    }

Add to CompassData something like the following

    public CompassData(double headingMagneticNorth, CompassAccuracy compassAccuracy) : this(headingMagneticNorth)
    {
        CompassAccuracy = compassAccuracy;
    }
    public CompassAccuracy { get; }

## Intended Use Case
When the Compass.ReadingChanged events are raised the developer can query the CompassAccuracy value and raise a notification to the user that the device needs calibration.

    private void Compass_ReadingChanged(object sender, CompassChangedEventArgs e)
    {
        ...
        switch (e.Reading.CompassAccuracy)
        {
            case CompassAccuracy.Unknown:
            case CompassAccuracy.Low:
                NotifyUserCompassCalibrationRequired();
                break;
            case CompassAccuracy.Medium:
                NotifiyUserCompassCalibrationCouldBeBetter();
                break;
            case:
                NotifyUserThatCompassIsAccurate();
                break;
        }
    }

**Comment by jamesmontemagno** [comment]
We are not accepting new feature requests at this time, please open a new ticket over on https://github.com/dotnet/maui
