### ISSUE TITLE
[Enhancement] Default Implementation in .net Standard with ability to Mock

### ISSUE THREAD

**Issue by ackava** [xamarin/Essentials#1865]
## Summary
Instead of throwing exceptions a default implementation in `*.netstandard.cs` can serve with some or empty result.

## API Changes
1. Assume `*.netstandard.cs` running under Operating system like Windows/Linux/Mac
2. Add default implementation to give some empty result
3. Add ability to add mock interface
4. Change class structure to 
AppInfo.shared.cs
```c# 
public partial abstract class AppInfo { 

    // default implementation....
    internal protected virtual string PackageNameImpl() => Assembly.GetCurrentExecutingAssembly().Name;

    // simple redirection to allow existing API to work
    public static string PackageName() => Instance.PackageNameImpl();
}
```
AppInfo.netstandard.cs
```c#
public partial class AppInfo {
         // This will allow mocking, we can optionally hide it from intellisense
         [EditorBrowsable(EditorBrowsable.Never)]
         public static AppInfo Instance { get; set; }  = new AppInfo();
}
```

API.ios.cs
```c#
public partial class AppInfo {
         [EditorBrowsable(EditorBrowsable.Never)]
         public static API Instance { get; }  = new AppInfoForIOS();
}

internal class AppInfoForIOS: AppInfo {
     public override string PackageNameImpl() => GetBundleValue("CFBundleDisplayName") ?? GetBundleValue("CFBundleName");
}
```

e.g.

3. For example, AppInfo can serve details from `Assembly.GetCurrentExecutingAssembly`
4. Share can simply open a process
5. Accelerometer can give empty result, no events fired

## Intended Use Case
Using WPF/GTK is very faster for designing UI with some logic as opposed to in any emulator or UWP. Debugging is lot easier with WPF/GTK.

Ability to add mock implementation will improve testing.

**Comment by jamesmontemagno** [comment]
We are not accepting new feature requests at this time, please open a new ticket over on https://github.com/dotnet/maui
