### ISSUE TITLE
Language for user interface to share with an external application

### ISSUE THREAD

**Issue by atrodriguez88** [xamarin/Essentials#1868]
### Description
Xamarin.Essentials: Share
Ability to change the language of the user interface

### Expected Behavior

![image](https://user-images.githubusercontent.com/24922914/129611801-e3edeaee-b2d4-43a7-acd7-fdfbdb5127ea.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/24922914/129612231-aa23339c-9414-4359-bf99-ca2172792359.png)

**Comment by jamesmontemagno** [comment]
These come from the operating system directly and can not be changed.
