### ISSUE TITLE
Typo on the Preferences API doc page

### ISSUE THREAD

**Issue by charlespetzold** [xamarin/Essentials#187]
In [/docs/en/Xamarin.Essentials/Preferences.xml](https://github.com/xamarin/Essentials/blob/master/docs/en/Xamarin.Essentials/Preferences.xml), the **Remarks** para contains some gibberish: 

"Each platform uses the platform provided native APIââââ‚¬Å¡¬âââ‚¬Å¾¢s for storing application/user preferences:"

**Comment by mattleibow** [comment]
Fixed! Thanks!
