### ISSUE TITLE
Android 12 - Geolocation.GetLocationAsync is throwing PermissionException when ONLY approximate location granted

### ISSUE THREAD

**Issue by ruby-verma** [xamarin/Essentials#1871]
Description
I am running Geolocation sample app on Android 12 device (app still targeting to Android 11) but when i'm try to fetch Currrent location getting following error:-

{Xamarin.Essentials.PermissionException: LocationWhenInUse permission was not granted: Denied

### Steps to Reproduce

1. Launch Application
2. Click on button to get current location
                var request = new GeolocationRequest(GeolocationAccuracy.High, TimeSpan.FromSeconds(5));
                cts = new CancellationTokenSource();
                var location = await Geolocation.GetLocationAsync(request, cts.Token);
3. A dialog displays to choose between approximate location and precise location
4. Choose approximate location and click on only this time

### Expected Behavior
App should get the location

### Actual Behavior
App is not getting location instead PermissionException is logged

### Basic Information

- Platform Target Frameworks: Xamarin.Android (11.4.0.5)
- IDE: Visual Studio Professional 2019 (16.11.1)
- Nuget Packages: Xamarin.Essentials (1.7.0)
- Affected Devices: Pixel 4a (OS 12-beta)

**Comment by jfversluis** [comment]
Our latest versions (and upcoming 1.7.2 version) will have fixes in this area. Please try those (1.7.2 will come out soon) and let us know if this still an issue with those.

**Comment by rubverma** [comment]
Thank you for the update!!
