### ISSUE TITLE
Include Address in Xamarin.Essentials.Contacts

### ISSUE THREAD

**Issue by ammoman** [xamarin/Essentials#1872]
When picking a contact with Contacts.PickContactAsync() or getting all contacts with Contacts.GetAllAsync(), the returned Contact object has most of the pertinent information about the contact, excluding the contact's address.

My app only needs addresses, so I am relying on the old ContactsPlugin by jamesmontemagno to retrieve them.  From what I've read in other comments, addresses are difficult (especially on Android).  Even if the entire address came back as just 1 string, anything would be better than nothing.

**Comment by jfversluis** [comment]
Thanks for the suggestion! Unfortunately this won't be happening for Xamarin.Essentials anymore. If this is still something of interest to you, please check to see if there is an issue for .NET MAUI and if not open an issue there with all the details requested.

Thanks!
