### ISSUE TITLE
Lock Device Orientation API

### ISSUE THREAD

**Issue by wcoder** [xamarin/Essentials#188]
### Description
Ability to work with screen orientation on mobile device (change, lock/unlock).

### API Declaration

- DeviceOrientations DeviceOrientation.CurrentOrientation
- void LockOrientation(DeviceOrientations orientation);
- void UnlockOrientation();

### Migrate from
- [Device Orientation Plugin](https://github.com/wcoder/Xamarin.Plugin.DeviceOrientation)

**Comment by jamesmontemagno** [comment]
We do have the current orientation and screen metrics. We are going to make it more discoverable with #197 which is where we would put something like this.

**Comment by jamesmontemagno** [comment]
Moved the orientation to a new class. Locking will be on the proposal block for future milestones.

**Comment by Mrnikbobjeff** [comment]
Is this actually up for grabs @jamesmontemagno ?

**Comment by Mrnikbobjeff** [comment]
I finished a working implementation for all platforms except tizen (rotating tvos is impossible I believe, though I didn't check 😄). This currently requires changes to our DisplayOrentientation enum, as it needs to cover all orientations and not just horizontal and vertical, as iOS as the only platform requires to set a single specific orientation and does not expose a flag enum.

**Comment by dlandi** [comment]
Hi. I could really use LosckScreenOrientation() from now! What's the status?

**Comment by Burgler-dev** [comment]
Hi, I could use the locking/unlocking to.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
