### ISSUE TITLE
Blazor support - MainThread.BeginInvokeOnMainThread

### ISSUE THREAD

**Issue by Pinox** [xamarin/Essentials#1889]
I know Blazor is not currently supported on Essentials as it throws on a  MainThread.BeginInvokeOnMainThread:

> This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

Would be useful to not throw an error like "not implemented in the portable version of this assembly" with a flag setting or something. Writing cross platform code using Essentials should not throw on MainThread  as there is only one thread in Blazor and will prevent us from replicating code specifically for Blazor.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
