### ISSUE TITLE
Android Designer Mode Compatibility

### ISSUE THREAD

**Issue by Redth** [xamarin/Essentials#189]
Mostly we don't have UI related code so this isn't an issue for us, but there are still some ways our code can fail if running in a Designer or Previewer mode.

Take for instance a subclass of `Activity` which invokes `Preferences.Get("key", "");` from its constructor.  

In the designer, we don't have an instance of Context to use.  The designer obviously doesn't invoke our platform `Init` so we don't know the 'current activity', and `Application.Context` is null.  When one of our API's gets invoked that requires a context, things go badly.

I think we should introduce the internal concept of **Design Mode**.

```csharp
public static partial class Platform
{
    internal static bool DesignMode => Application.Context == null;
}
```

The other part of this is to audit all of our API's to check for this and fail gracefully where appropriate.

Eg: For Geolocation.GetLocationAsync(..) we can return null if we detect DesignMode rather than failing with some exception.  This also means we can skip things like permission checks in this scenario.

Open to discussion and thoughts for more optimal implementations of this concept!

> VS bug [#735674](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735674)

**Comment by jamesmontemagno** [comment]
is this the same as the ios designer flag for xamarin.forms too? how does that work?

**Comment by Redth** [comment]
We will need to ask the iOS team. I think the theme here is make sure we play nice with all the designers...

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
