### ISSUE TITLE
[Bug] [Android] Email.ComposeAsync crashs the app

### ISSUE THREAD

**Issue by queequac** [xamarin/Essentials#1902]
### Description

Within the Pre-Launch Report I get always the following error:

Stacktrace
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.accounts.Account com.android.mail.providers.Account.b()' on a null object reference`
```
FATAL EXCEPTION: main
Process: com.google.android.gm, PID: 11419
java.lang.NullPointerException: Attempt to invoke virtual method 'android.accounts.Account com.android.mail.providers.Account.b()' on a null object reference
	at dgg.Z(PG:3)
	at dgg.onPrepareOptionsMenu(PG:6)
	at com.google.android.gm.ComposeActivityGmail.onPrepareOptionsMenu(PG:1)
	at android.app.Activity.onPreparePanel(Activity.java:4137)
	at gn.onPreparePanel(PG:2)
	at vz.onPreparePanel(Unknown Source:2)
	at tm.onPreparePanel(PG:3)
	at tv.a(PG:192)
	at tv.f(PG:7)
	at tc.run(PG:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8016)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

The issue occurs only on a Samsung device running Android 10. So this might be related to Samsung, but still adding exactly this error multiple times in all my reports. I cannot reproduce it on any physical phone and there was never a customer compaint about this - maybe the samsung device for the pre-launch report is configured strange (people assume it might have no account linked)

Anyway, is there something Xamarin.Essentials could do to overcome this error? Maybe the way it internally calls out to the mail program allows catching this?
Somehow it looks like Gmail crashes and that kills also my app. Might some additional permission (like android.permission.GET_ACCOUNTS) help her? But I don't want to add this quite unpopular permission, just to make a rare bug go away. ;)
Or is this related to AOT/LLVM/r8 in some way I need to some proguard rules?

### Steps to Reproduce

The error occurs then executing the following code:

```
var message = new Xamarin.Essentials.EmailMessage
{
    Subject = "Support request for XYZ",
    To = new System.Collections.Generic.List<string>() { "support@sample.com" }
};
_ = Xamarin.Essentials.Email.ComposeAsync(message);
```

### Expected Behavior

Should not crash the app.

### Actual Behavior

Crashs the app (but only in the pre-launch report and only on one Samsung device, when the test clicks on the button for sending an email)

### Basic Information

- Version with issue: 1.7.0
  - Android: 11.0
- Nuget Packages:
- Affected Devices: Samsung S20 G5

**Comment by MitchBomcanhao** [comment]
we sometimes get crashes highlighted by the pre-launch report and they have nothing to do with our application. if the stacks don't include your code, it is very likely that the issue isn't actually from your code.
