### ISSUE TITLE
[Enhancement] Support opening maps without coordinates

### ISSUE THREAD

**Issue by Almis90** [xamarin/Essentials#1903]
## Summary
Support using Map.OpenAsync without providing the location just to open the maps application. 

## API Changes
I have tested only iOS and the only way I could achieve this is by making my own custom method

    public class MapService : IMapService
    {
        public Task OpenAsync()
        {
            return Task.FromResult(MKMapItem.OpenMaps(new MKMapItem[] { }, null));
        }
    }

so by looking at the source code maybe we can create a new method in Map.shared.cs

        public static Task OpenAsync()
        {
            return PlatformOpenMapsAsync();
        }

and then create a new method PlatformOpenMapsAsync in Map.ios.watchos.macos.cs

        internal Task PlatformOpenMapsAsync()
        {
            return Task.FromResult(MKMapItem.OpenMaps(new MKMapItem[] { }, null));
        }

## Intended Use Case
I have an application where by clicking on the button it opens the map at the provided coordinates, when it opens the map application it has a button called directions that navigates you to that destination. Sometimes I don't have coordinates, but I still want to open the maps and let the user enter the address himself. Right now I cannot do that because I cannot open the map without providing a location.

**Comment by jfversluis** [comment]
Hey @Almis90! Thanks for the suggestion! At this time we're not going to add any new things to Xamarin.Essentials anymore though :( as we're transitioning to .NET MAUI you might want to open the feature request on the [.NET MAUI repo](https://github.com/dotnet/maui) so we can consider it for there.

Thanks!
