### ISSUE TITLE
[Bug][Android11] Email.ComposeAsync throws Xamarin.Essentials.FeatureNotSupportedException

### ISSUE THREAD

**Issue by takla21** [xamarin/Essentials#1907]
### Description
`Email.ComposeAsync()` throws `Xamarin.Essentials.FeatureNotSupportedException` on android 11 devices.

```
{Xamarin.Essentials.FeatureNotSupportedException: Specified method is not supported.
  at Xamarin.Essentials.Email.ComposeAsync (Xamarin.Essentials.EmailMessage message) [0x00007] in d:\a\1\s\Xamarin.Essentials\Email\Email.shared.cs:21 
  at Xamarin.Essentials.Email.ComposeAsync (System.String subject, System.String body, System.String[] to) [0x00000] in d:\a\1\s\Xamarin.Essentials\Email\Email.shared.cs:16 
```

### Steps to Reproduce

```cs
try
{
	await Email.ComposeAsync(subject, body, to);
}
catch (Exception e)
{
	this.Log().LogError(e, "error");
}
```

### Expected Behavior
It should open the client mail app.

### Actual Behavior
It throws Xamarin.Essentials.FeatureNotSupportedException on android 11 devices.

### Basic Information

- Version with issue: 1.7.0
- Last known good version: N/A
- IDE: Visual Studio 2019 16.11.3
- Platform Target Frameworks: 
  - Android: 11.0
- Affected Devices:
  - One plus 7 pro Android 11
  - Pixel 3XL Android 11

**Comment by nzaugg** [comment]
I think this exception is very poorly named. If it was something more like "Android Intent Missing From Manifest" or something like that then it's a better clue of where to start looking. The exception thrown here sounds like it doesn't work because the feature is not implemented in the library.
