### ISSUE TITLE
[Bug] [iOS] Email ComposeAsync not awaited correctly 

### ISSUE THREAD

**Issue by elicul** [xamarin/Essentials#1917]
### Description

Email Compose Async API is async, however, it immediately returns despite not having completed the Email operation.
This is a problem, because when you show the compose email screen to the user it immediately dissapears and the user is not able to send the email.

### Steps to Reproduce

1. Call await Email.ComposeAsync(emailMessage)

### Expected Behavior
Call should block until user is able to send the email or cancel the operation.

### Actual Behavior
The execution immediately proceeds.

### Basic Information

- Version with issue:
iOS: iOS15.1

**Comment by MitchBomcanhao** [comment]
we can also reproduce this on iOS 15.0.

**Comment by jamesmontemagno** [comment]
I am unable to reproduce this on my device. When I send an email it works just fine and brings up the screen....

**Comment by jfversluis** [comment]
This should be fixed in the current version (by #1846)
