### ISSUE TITLE
[Enhancement] Fullscreen property on WebAuthenticator

### ISSUE THREAD

**Issue by monkeypro** [xamarin/Essentials#1921]
## Summary
When opening a login view on an iPad, using Xamarin Essentials WebAuthenticator, the browser window is really small.
It would be nice to be able to set the browser to fill the whole screen.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/2150723/141481982-dacf32f4-8666-473d-903e-2c816cc3ad5a.png)

**Comment by jfversluis** [comment]
Hey @monkeypro ! Thanks for the suggestion! At this time we're not going to add any new things to Xamarin.Essentials anymore though :( as we're transitioning to .NET MAUI you might want to open the feature request on the [.NET MAUI repo](https://github.com/dotnet/maui) so we can consider it for there.

Thanks!
