### ISSUE TITLE
[Android12] Email.ComposeAsync throws FeatureNotSupportedException on Pixel devices

### ISSUE THREAD

**Issue by Alex6511** [xamarin/Essentials#1926]
### Description

After updating to Android 12 on pixel devices, users could no longer use the feature that used the Email.ComposeAsync function. After investigation, I found many reports that this was happening on Android 11 and was fixed by adding intents, so I added the following to the AndroidManifest.xml
```	
	<queries>
		<intent>
			<action android:name="android.intent.action.SENDTO" />
			<data android:scheme="mailto" />
		</intent>
		<intent>
			<action android:name="android.intent.action.VIEW" />
			<data android:scheme="http"/>
		</intent>
		<intent>
			<action android:name="android.intent.action.VIEW" />
			<data android:scheme="https"/>
		</intent>
		<intent>
			<action android:name="android.intent.action.VIEW" />
			<data android:scheme="smsto"/>
		</intent>
	</queries>
```

This fixed the problem on the Android 11 emulator, but when I sent a test version of our .apk to someone who had an Android 12 device, he could no longer install the app. Additionally, the Android 12 emulator still could not use the functionality with the same FeatureNotSupportedException.

### Basic Information

- Version with issue: 1.6.1
- Last known good version: N/A
- IDE: Rider
- Platform Target Frameworks: 
  - Android:  Xamarin.Android 11.1
- Affected Devices: Pixel 4, Pixel 4a

**Comment by omghb** [comment]
```
SystemService.ComposeEmail (System.String emailTo, System.String subject, System.String body, System.String[] attachmentFilePaths)
Xamarin.Essentials.FeatureNotSupportedException: Specified method is not supported.
```

We get the same exception after we updated:
- Android targetSDKVersion from 29 to 30
- Xamarin.Forms from 5.0.0.2012 to 5.0.0.2196
- Xamarin.Essentials from 1.6.1 to 1.7.0

We see the issue on multiple devices:
- Samsung Galaxy S10e / Android 11
- Samsung Galaxy Tab A / Android 11
- Sony Xperia
