### ISSUE TITLE
[Bug] [Android] Permissions LocationAlways Fails on Android 11+

### ISSUE THREAD

**Issue by aritchie** [xamarin/Essentials#1936]
### Description

Permissions.RequestAsync<LocationAlways> will either not return or not open new dialog.  Android 11+ requires that background location permissions are requested separately or they will silently fail to the console.  

FYI - this is partially related to #1912 which I am sending a PR for.  The fixes from this have already been applied in [Shiny Locations]( https://github.com/shinyorg/shiny/blob/master/src/Shiny.Locations.Common/Platforms/Android/PlatformExtensions.cs#L46)

### Steps to Reproduce

1. Spin up an Android 11/12 emulator
2. Run permission sample for Location Always
3. Watch nothing happen 

### Expected Behavior
The permission is requested and returns Denied/Granted or Restricted depending on choices made

### Actual Behavior
Silently fails or returns denied

### Basic Information

- Version with issue: 1.7
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by aritchie** [comment]
@jfversluis If you can pass this within the next couple weeks, I'll have some time to port this over to MAUI during the holidays.

**Comment by jfversluis** [comment]
I will see if I can have a look at what is moving here this week! :)
