### ISSUE TITLE
[Enhancement] Share image and text for supported apps

### ISSUE THREAD

**Issue by agrigg** [xamarin/Essentials#1938]
## Summary
Currently when attempting to share an image on iOS, the title is ignored and just the image is pre-filled. Ideally this would contextually attempt to share the image and the text by creating a custom UIActivityItemSource for files or images specifically for the services that support it. 

## API Changes

For iOS, a custom UIActivityItemSource could be used that returns not just the image / file from GetItemForActivity, but a dictionary with the text and image for ActivityTypes that support it. You can see an example here in Swift of how this is done: [https://www.py4u.net/discuss/1094856](https://www.py4u.net/discuss/1094856)

So, for the ShareFileRequest, a separate UIActivityItemSource could be created similar to the below code sample and used in place of the current ShareActivityItemSource.

```
class ShareImageActivityItemSource : UIActivityItemSource
{
    readonly NSObject item;
    readonly string title;
    readonly string message;

    internal ShareImageActivityItemSource(NSObject item, string title, string message)
    {
        this.item = item;
        this.title = title;
        this.message = message;
    }

    public override NSObject GetItemForActivity(UIActivityViewController activityViewController, NSString activityType)
    {
        if (activityType == UIActivityType.PostToFacebook || activityType == UIActivityType.PostToTwitter)
        {
            return new NSDictionary("text", message ?? title, "image", item);
        }
        else
        {
            return item;
        }
    }

    public override NSObject GetPlaceholderData(UIActivityViewController activityViewController) => item;

    public override string GetSubjectForActivity(UIActivityViewController activityViewController, NSString activityType) => title;
}
```

Other considerations:

- Determine which activity types support image and text

## Intended Use Case
This came up because in our app we want to allow people to share about a volunteer opportunity they are viewing. Initially, we just shared the opportunity name and the URL to sign up using the ShareTextRequest. However, in order to get Instagram to show up a photo has to provided. We switched to using the ShareFileRequest and now Instagram shows up, but the text passed in the Title of the ShareFileRequest does not show up when attempting to share to Instagram, Facebook, etc.

**Comment by jfversluis** [comment]
Hey @agrigg! Thanks for the suggestion! At this time we're not going to add any new things to Xamarin.Essentials anymore though :( as we're transitioning to .NET MAUI you might want to open the feature request on the [.NET MAUI repo](https://github.com/dotnet/maui) so we can consider it for there.

Thanks!
