### ISSUE TITLE
[Bug] Share.RequestAsync on iPad doesn't work

### ISSUE THREAD

**Issue by ShadowOfPhantom** [xamarin/Essentials#1948]
Share.RequestAsync doesn't show share sheet when sharing a file from iPad, works great as always on iPhone

### Steps to Reproduce

On iPad call RequestAsync, in my case it is something like this:  

`await Share.RequestAsync(new ShareFileRequest("FileName", new ShareFile(GetFilePath())));`

Note: iPad simulator shows the same behavior for this as real device does, so if you don't have one you can use simulator and get the same results.
Note [2]: share doesn't work with ShareFileRequest but **it works for example with ShareTextRequest**

### Expected Behavior

Get share sheet to share a file

### Actual Behavior

The screen a bit dims like inactive window but share sheet doesn't appears
here is what I get in the output:
https://pastebin.com/Y6H3mXMu

### Basic Information

- Version with issue: 1.7.0
- Last known good version: don't know really :(
- IDE: Visual studio 2022 Community
- Platform Target Frameworks: 
  - iOS:  15.2

- Affected Devices: iPad Air (4th), iPad pro (M1) and others...

**Comment by BloodShadow174** [comment]
Any updates?

**Comment by FlaynGordt** [comment]
We also have this issue.

**Comment by rugue1** [comment]
This worked for me in 1.7.3
