### ISSUE TITLE
Blazor MAUI Hybrid App : - The type or namespace name 'Essentials' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?) BlazorHybrid (net6.0-android)

### ISSUE THREAD

**Issue by nssidhu** [xamarin/Essentials#1949]
### Description

I am Trying to use Xamarin Essentials in MAUI Blazor Hybrid App.

when i try the following code, i get error

 ```
protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            Xamarin.Essentials.Platform.Init(this, savedInstanceState); // add this line to your code, it may also be called: bundle
            Platform.Init(this, savedInstanceState);

        }

The type or namespace name 'Essentials' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?) BlazorHybrid (net6.0-android)

```

But if i try to Add Xamarin.Essentials Nuget Package Manually,
I get the following Error.

```
Error	XA4215	The Java type `xamarin.essentials.fileProvider` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.	

Error	XA4215	  `xamarin.essentials.fileProvider` generated by: Microsoft.Maui.Essentials.FileProvider, Microsoft.Maui.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null	BlazorHybrid	
	
Error	XA4215	  `xamarin.essentials.fileProvider` generated by: Xamarin.Essentials.FileProvider, Xamarin.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null	BlazorHybrid	
```

### Steps to Reproduce

I am following this document, but with Blazor MAUI Hybrid App.
(https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?tabs=android)

### Expected Behavior
I should be able to Display Map and use its functinalities

### Actual Behavior
compiler Error

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by nssidhu** [comment]
@Eilon  is it possible to use Xamarin Essentials(MAP) in Blazor MAUI Hybrid App ?

**Comment by nssidhu** [comment]
Is there a way to use Third party libraries  that have dependencies on Xamrin.Essentials or Xamarin.Forms in MAUI, 
I am not finding any libraries in MAUI for Displaying Map and Reading QRCode and Displaying QRCode.

**Comment by Eilon** [comment]
Hi @nssidhu , for .NET MAUI you can use the new MAUI Essentials library. I think it's almost the same, except the namespace/assembly/package changed, and of course there have been some changes in functionality. But I think all the major features are the same.

**Comment by nssidhu** [comment]
When i try to add Zxing.Net.Mobile, this is the error that i get how do i resolve this ?
![image](https://user-images.githubusercontent.com/3267605/149052364-15124679-14c8-4b04-be45-5f36768f2ec7.png)

**Comment by jfversluis** [comment]
As Eilon pointed out, Essentials can now be found under Microsoft.Maui.Essentials for .NET MAUI apps.

In regard to the ZXing plugin, I don't think this package is compatible (yet) all plugins now need to be made compatible with .NET 6 and .NET MAUI, so please check in their respective docs and repos if support is already there or planned. Thanks
