### ISSUE TITLE
Version information at runtime after build incremented through AppCenter / AZDO  ?

### ISSUE THREAD

**Issue by stephenhauck** [xamarin/Essentials#1954]
It appears that the Version information is available from the files that get embedded but AppCenter / AZDO allows automatic incrementing of build number .... how do we get this information to display in the app when the user calls in for support and to display in the "About" window ?

![image](https://user-images.githubusercontent.com/12648793/149939146-28e2ac96-1af8-489a-a085-c04311800b54.png)

**Comment by jfversluis** [comment]
I think this is a smart/easy way to just upgrade the right fields in your AndroidManifest.xml/info.plist and from there you should be able to show the version information through our existing APIs: https://docs.microsoft.com/xamarin/essentials/version-tracking

Hope this will help! Closing this one as it's more a question than an issue :)

**Comment by stephenhauck** [comment]
That’s your opinion ….
The tools do it so either enable it or improve the documentation on the CI / CD tools to let us know how to use the feature.

Closing tickets without discussion is shameful .

Stephen

**Comment by stephenhauck** [comment]
@jfversluis thanks for forcing me to do this manually when the CI / CD system offers it as a feature and you simply think manual is better for some reason :(

**Comment by jfversluis** [comment]
Then maybe I didn't understand your question, sorry about that :)

Either way, this is about App Center/Azure DevOps which has little to do with Essentials, but if it does, please use the appropriate template to provide the information that is relevant to this and what you expect from Essentials in this regard. 

The "only" thing the option you highlighted does is increment the number in the app package metadata so that it's picked up by the app stores if you distribute it there. I fail to see how we could possibly inject something in your app with this without using the Essentials APIs I have already pointed out. Like I said; maybe I don't understand the ask here, then please help me understand.

**Comment by stephenhauck** [comment]
It does have to do with App Center somewhat .. how do we get the automatically integrated build information ?
If it's not supported by Essentials that's fine but refer us to the documentation on how to obtain that automatic build number or request it be created as I have not found anything about how to "read the AppCenter auto incremented build number at runtime in Xamarin Forms"

**Comment by stephenhauck** [comment]
That would be great but AppCenter has ZERO support ... 
Been there .. tried them ... they are low level people that want MASSIVE documentation because they have no idea what it does and I just don't have time for that ,, if it's a feature in AppCenter, and I would assume Github or AZDO pipelines then MS (Xamarin Essentials) should support it.

Thanks but it seems CI / CD is not well supported by Xamarin ...

**Comment by jfversluis** [comment]
I can see you're dissatisfied and I'm trying to help you, but I fail to understand how we're not supporting this. You're asking about something that happens at build time, how you can access that at runtime. In case of this version number this can be done by using Essentials and the version tracking APIs.

What am I missing here?

**Comment by stephenhauck** [comment]
You can do it .. it is bound to the bundle like an MDM managed configuration I would guess ?
If CI / CD does it then it should be accessible at runtime in the compiled version.
I know you're trying to help and I appreciate it but it's tiresome that features get rolled out then never supported.
Why would you even offer auto increment builds if you could not access them from inside the app somehow ?

**Comment by jfversluis** [comment]
But I'm telling you you can? Where do you expect the support where it isn't?

This is no different than you updating the version number manually in the files that I already pointed out, making a build and that version number is used in the app stores and can also be shown in your app with `var currentBuild = VersionTracking.CurrentBuild;`

**Comment by stephenhauck** [comment]
That code accesses the MANUAL changes in your files that you have to make and keep up with .. correct ?

**Comment by jfversluis** [comment]
No, because it will increment automatically, that is what that setting in App Center does.

**Comment by stephenhauck** [comment]
Thanks for your help ... If I want to use the timestamp to tie it back to a date and time like I selected above what property is populated in Xamarin Essentials Version structure ?

**Comment by jfversluis** [comment]
The same property because if will fill the same field in the manifest files, it will just have different values. Where I said 1 and 2 the outcome will now be 23912739 or 9023129 (assuming this were valid timestamps).

In fact this even has little to do with Xamarin at all. This is all very much how iOS and Android need their metadata to be provided. The only thing App Center is doing on their side is a very simple token replace in the AndroidManifest.xaml/info.plist file and with Essentials we make the platform APIs available to read the values from those files at runtime.

**Comment by dimonovdd** [comment]
@stephenhauck Hi. It works correctly for me with appcenter:
`$"{AppInfo.Version} ({AppInfo.BuildString})"`

**Comment by stephenhauck** [comment]
OK, I will run some tests but the fact that you have to build and deploy to verify something that could be clearly documented is silly.

It refers to the "Build number format" then you can select "Build ID" which maps back to a property but what is a "build number"

in android -  android:versionCode="3" android:versionName="2.1"
No property called "build number"
iOS  - 
![image](https://user-images.githubusercontent.com/12648793/150009688-afe4614d-4203-4ed0-8030-bd72bbbcf060.png)

**Comment by jfversluis** [comment]
As mentioned; this very much comes down to platform-specific things. You don't have to build and deploy to test it, you can just increment the values yourself locally and start a debug sessions and you will see the values show up in your running app.

When it does go through the pipeline it replace the values you have set manually, so you'll have to trust that to work, other than that it's exactly the same thing.

AndroidManifest documentation: https://developer.android.com/guide/topics/manifest/manifest-element
Apple info.plist versioning documentation: https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion

**Comment by stephenhauck** [comment]
If you say so ... 
I have not been able to find any documentation anywhere that indicates which values in manifest and info.plist get auto incremented ... there's not even a little info callout on the web page that indicates where this value will be affected or show in the system.

Manually changing values when using CI / CD is silly ...

**Comment by jfversluis** [comment]
> Manually changing values when using CI / CD is silly ..

I feel we're not understanding each other, because you don't need to do this 😅

**Comment by stephenhauck** [comment]
On the iOS build settings it should say something like "the Build value will be automatically updated" to match the info.plist property
![image](https://user-images.githubusercontent.com/12648793/150011242-0043c871-1282-46a5-a468-448ce1adb774.png)

On Android it should say something like "The Android version name will be incremented" to match the manifest setting
 android:versionCode="3" android:versionName="2.1"


Having the CI / CD do it removes any knowledge by the developer to do platform specific versioning ... and insulates us from future issues introduced by Xamarin or communications issues with XCode etc... 

Thanks for your help ...
