### ISSUE TITLE
[Bug][Android] Permission for storage write is throwing exception on Android

### ISSUE THREAD

**Issue by abdul-wasey** [xamarin/Essentials#1955]
### Description

I have declared `android.permission.WRITE_EXTERNAL_STORAGE` in my AndroidManifest.xml file, but still getting this exception.
 
{Xamarin.Essentials.PermissionException: You need to declare using the permission: `android.permission.WRITE_EXTERNAL_STORAGE` in your AndroidManifest.xml
  at Xamarin.Essentials.Permissions+BasePlatformPermission.CheckStatusAsync () [0x00055] in D:\a\1\s\Xamarin.Essentials\Permissions\Permissions.android.cs:54 
  at Xamarin.Essentials.Permissions.CheckStatusAsync[TPermission] () [0x00000] in D:\a\1\s\Xamarin.Essentials\Permissions\Permissions.shared.cs:9}

### Steps to Reproduce

Call this method ```await Permissions.CheckStatusAsync<Permissions.StorageWrite>();``` and you will get the exception which is in the description. 

### Basic Information

- Version with issue: 1.7.0
- Last known good version: Not applicable
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android: 10+ 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Samsung S9+ and S10+

**Comment by jfversluis** [comment]
Hey there, thanks for the report! Would you be able to put together a little reproduction project that shows this issue? Or at least show how you have declared that permission and any relevant code? Thanks!

**Comment by jfversluis** [comment]
I'd still appreciate a reproduction. Seems to work fine here :)

I've attached my reproduction project [here](https://github.com/xamarin/Essentials/files/7891716/Repro1955.zip).

![image](https://user-images.githubusercontent.com/939291/150002910-e7b3f1bc-3c69-4999-a6e4-a5c2241559ed.png)

**Comment by abdul-wasey** [comment]
@jfversluis You are trying to repro this on API level 29..
please change the api level to 30 (Andorid 10 emulator) then you will see the exception.
Thanks

**Comment by abdul-wasey** [comment]
@jfversluis Thanks for creating this repro project. 

I have debugged the code of Xamarin.Essentials.Permissions' shared android code 
and found that this code is not getting Write_External_Storage permission from `RequestedPermissions` 
`public static bool IsDeclaredInManifest(string permission)
        {
            var context = Platform.AppContext;
            var packageInfo = context.PackageManager.GetPackageInfo(context.PackageName, PackageInfoFlags.Permissions);
            var requestedPermissions = packageInfo?.RequestedPermissions;

            return requestedPermissions?.Any(r => r.Equals(permission, StringComparison.OrdinalIgnoreCase)) ?? false;
        }`
        
 Thats' why this line throwing the exception,

 https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/Permissions/Permissions.android.cs#L67
 
 Note: It's only happening for Android 10 and above versions.

**Comment by jfversluis** [comment]
Have you also tried running my project? Does that work for you? Because it works for me on Android 10 and also tried Android 11. So it seems there must be something in your project that is triggering this.

**Comment by abdul-wasey** [comment]
Yes, Your project is worked for me.
Closing this issue because that seems to be an issue in my project's manifest file.

Thanks for your time @jfversluis
