### ISSUE TITLE
Add browser customisation APIs

### ISSUE THREAD

**Issue by prashantvc** [xamarin/Essentials#196]
### Description
Essentials Browser does not have API to customise the Browser title and colour.

The plugins has `BrowserOption` class that we can pass when opening a browser object, but there is no alternative for this in the Essentials API

Example: 

```csharp
await CrossShare.Current.OpenBrowser("https://auth.xamarin.com/account/register",
    new BrowserOptions
    {
        ChromeShowTitle = true,
        ChromeToolbarColor = new ShareColor
            {
                A=255,
                R=118,
                G=53,
                B=235
            },
        UseSafariReaderMode = false,
        UseSafariWebViewController = true
});
```

> VS bug [#735673](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735673)

**Comment by mattleibow** [comment]
This may be done by adding a settings type and have properties like `PreferredTitle` and `PreferredTint` or something. UWP does not have a browser tab thing, but does iOS allow for colors or a title.

**Comment by Evolutionlab** [comment]
The old "Share" plugin supported customized colors. Imho you should support that:

```
                await CrossShare.Current.OpenBrowser(uri,
                    new BrowserOptions
                    {
                        SafariBarTintColor     = new ShareColor(0, 73, 138),
                        SafariControlTintColor = new ShareColor(255, 255, 255),
                        ChromeToolbarColor     = new ShareColor(0, 73, 138)
                    });
```

**Comment by Redth** [comment]
I think we need to shy away from adding properties with names specific to one platform.

I think it would be ok to have something like @mattleibow suggested and have `PreferredBackgroundColor` and `PreferredControlColor` with some documentation around what it means on each platform.

**Comment by jamesmontemagno** [comment]
So, System.Drawing.Color is not available in Xamarin.iOS, but instead OpenTK, so for now this work will be delayed until that is fixed. For tracking here: https://github.com/xamarin/xamarin-macios/issues/5273

**Comment by Mrnikbobjeff** [comment]
This can be closed AFAIK

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '1.1.0' that is not in the list of supported values
