### ISSUE TITLE
[Bug] Picker permission requirement for READ_EXTERNAL_STORAGE not allowed with SDK 30 and Up

### ISSUE THREAD

**Issue by norton287** [xamarin/Essentials#1961]
### Description

Can picker be updated to the new permissions model so that apps aren't being rejected for requesting the READ_EXTERNAL_STORAGE?  I hate to lower my target to SDK 28 just to be accepted into the play store and be able to use the picker.

Or if there is a work around please share :)
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by norton287** [comment]
@jamesmontemagno I have been going back and forth with google over this and they keep denying my app submissions so a reasonably quick solution would be good LOL.

**Comment by jamesmontemagno** [comment]
Hmmm I'm still not sure as I am reading -> https://developer.android.com/training/data-storage/shared/documents-files and it says:

```
If your app uses the media store, however, you must request the [READ_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE) permission to access other apps' media files. On devices that run Android 9 (API level 28) or lower, your app must request READ_EXTERNAL_STORAGE permission to access any media file, including the media files that your app created.
```

And their code is pretty much the same as our code as well....

Maybe you need to specify:

```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
    android:maxSdkVersion="28" />
```

with the maxSdkVersion set? hmmmm https://stackoverflow.com/questions/62782648/android-11-scoped-storage-permissions/66366102#66366102

**Comment by jamesmontemagno** [comment]
If you run your app on an API 30/31 emulator does the app crash when trying to pick a file?

**Comment by norton287** [comment]
Have not tried that, it picks fine on my devices with read permission.


From: James Montemagno ***@***.******@***.***)
Reply: xamarin/Essentials ***@***.******@***.***)
Date: February 8, 2022 at 6:21:05 PM
To: xamarin/Essentials ***@***.******@***.***)
CC: John Norton ***@***.******@***.***), Author ***@***.******@***.***)
Subject: Re: [xamarin/Essentials] [Bug] Picker permission requirement for READ_EXTERNAL_STORAGE not allowed with SDK 30 and Up (Issue #1961)

**Comment by norton287** [comment]
Submitting the with permission like you gave got an instant rejection from the play store bot.


From: James Montemagno ***@***.******@***.***)
Reply: xamarin/Essentials ***@***.******@***.***)
Date: February 8, 2022 at 6:21:05 PM
To: xamarin/Essentials ***@***.******@***.***)
CC: John Norton ***@***.******@***.***), Author ***@***.******@***.***)
Subject: Re: [xamarin/Essentials] [Bug] Picker permission requirement for READ_EXTERNAL_STORAGE not allowed with SDK 30 and Up (Issue #1961)

**Comment by norton287** [comment]
Latest rejection

![SmartSelect_20220211-005037_Edge](https://user-images.githubusercontent.com/42098364/153548673-fe5f5efa-c061-4734-8033-8241395dc3b4.jpg)
![SmartSelect_20220211-005126_Edge](https://user-images.githubusercontent.com/42098364/153548685-93a3f19e-5b58-4233-853f-4d81062871cf.jpg)

**Comment by norton287** [comment]
@jamesmontemagno The response from Play Store is that the app does not need ANY permissions to take advantage of SAF or Media API to read external storage.  I have followed the picker documentation and it opens the picker and reads all of the storage on the card with this:

Intent intent = new Intent(Intent.ActionGetContent);
            intent.AddCategory(Intent.CategoryOpenable);
            intent.SetType("*/*");

But I am not familiar enough with Xamarin.Android to deal with selecting something and then processing it.  But I did not need any rights to do that at all.

But I am under a time crunch, my app is ready for testing in the store and I am waiting on a working picker which is needed as part of the functionality of the app as a file manager.  You guys killed all the independent pickers when you released yours so I am stuck with Essentials for a picker solution or I need someone to show me how to implement just a separate picker for android to get it into the store and can move forward.

**Comment by norton287** [comment]
@jamesmontemagno This will show you how to do a picker without permissions on android, it works wonderfully.

[https://github.com/xamarin/xamarin-forms-samples/tree/main/DependencyService](url)

**Comment by norton287** [comment]
Here is my implementation that picks files with no permissions required!

```
using System.IO;
using System.Threading.Tasks;

namespace SimpleBlobManager.Interfaces
{
    public interface IAndroidPickerService
    {
        Task<Stream> GetStreamAsync();
    }
}

```
DependencyService:

```
using Android.Content;

using SimpleBlobManager.Droid;
using System.IO;
using System.Threading.Tasks;
using SimpleBlobManager.Interfaces;
using Xamarin.Forms;

[assembly: Dependency(typeof(AndroidPickerBlobFiles))]
namespace SimpleBlobManager.Droid
{
    public class AndroidPickerBlobFiles : IAndroidPickerService
    {
        public Task<Stream> GetStreamAsync()
        {
            Intent intent = new Intent();
            intent.SetType("*/*");
            intent.SetAction(Intent.ActionGetContent);

            // Start the picture-picker activity (resumes in MainActivity.cs)
            MainActivity.Instance.StartActivityForResult(
                Intent.CreateChooser(intent, "Select File"),
                MainActivity.READ_REQUEST_CODE);

            // Save the TaskCompletionSource object as a MainActivity property
            MainActivity.Instance.PickFileTaskCompletionSource = new TaskCompletionSource<Stream>();

            // Return Task object
            return MainActivity.Instance.PickFileTaskCompletionSource.Task;
        }
    }
}
```

Main Activity Mods:

`internal static MainActivity Instance { get; private set; }`

After Base.OnCreate add:

`Instance = this;`

Then add OnActivityResult:

```
public static readonly int READ_REQUEST_CODE = 1000;
       
        public TaskCompletionSource<Stream> PickFileTaskCompletionSource { set; get; }

        protected override void OnActivityResult(int requestCode, Result resultCode, Intent resultData)
        {
            base.OnActivityResult(requestCode, resultCode, resultData);
            if (requestCode == READ_REQUEST_CODE && resultCode == Result.Ok)
            {
                if (resultData is { })
                {
                    Uri uri = resultData.Data;

                    if (uri is { })
                    {
                        App.PickFileName = dumpImageMetaData(uri);

                        Stream file = ContentResolver.OpenInputStream(uri);
                        PickFileTaskCompletionSource.SetResult(file);
                    }
                    else
                    {
                        PickFileTaskCompletionSource.SetResult(null);
                    }
                }
            }
        }

        private string dumpImageMetaData(Uri uri) {

            // The query, since it only applies to a single document, will only return
            // one row. There's no need to filter, sort, or select fields, since we want
            // all fields for one document.
            ICursor cursor = ContentResolver?.Query(uri, null, null, null, null, null);

            try
            {
                // moveToFirst() returns false if the cursor has 0 rows.  Very handy for
                // "if there's anything to look at, look at it" conditionals.
                if (cursor == null || !cursor.MoveToFirst()) return null;

                var displayName = cursor.GetString(
                    cursor.GetColumnIndex(IOpenableColumns.DisplayName));
                int sizeIndex = cursor.GetColumnIndex(IOpenableColumns.Size);
                string size = null;
                size = !cursor.IsNull(sizeIndex) ? cursor.GetString(sizeIndex) : "Unknown";
                return displayName;
            } finally
            {
                if (cursor != null) cursor.Close();
            }
        }
```

**Comment by jamesmontemagno** [comment]
@norton287 thanks for the code. I am doing a comparison to see what we do. I am testing it out and I think that you are right and we don't need this permission at all. I tested the code by removing the storage permission check and I think it is working properly.

I will get this code fix in for the next release and then you should be able to swap it out.

**Comment by norton287** [comment]
@jamesmontemagno It works great, just no multi-select and there is a chance that the DISPLAY_NAME column can have a null value but other than that it is ok.

I did submit my updated app to the store and immediately got another auto-reject saying that I was asking for read/write permissions but I checked the bundle report in the store and I did not leave those two in it at all.

I check my manifest in my source and Android added a new entry on its own:

`android:grantUriPermissions="true"`

So I am not sure now what triggered the play store scan bot to trip on my submission.

**Comment by norton287** [comment]
@jamesmontemagno when can we expect a new release?

**Comment by norton287** [comment]
@jamesmontemagno When can we expect a release for XF that includes this fix?  I am through with my temporary fix and need a permanent fix for the full roll out to the store.

**Comment by norton287** [comment]
@jamesmontemagno seriously are there issues holding up the release?
