### ISSUE TITLE
[Bug] All documents appear disabled on iOs

### ISSUE THREAD

**Issue by Alextorres950325** [xamarin/Essentials#1962]
### Description
The iOs simulator can't select any file or document, all documents appear disabled. I already checked permissions and everything is well configured

### Steps to Reproduce

1.  Open the FilePicker
2.  All documents appear disabled

### Basic Information

- Version with issue: Xamarin Essentials  1.7.1
- IDE: VS 2022, VS Mac 2019 8.10.
- Platform Target Frameworks: 
  - iOS:  15.2

- Nuget Packages: Xamarin Forms 5.0.0.2337, Xamarin Essentials  1.7.1
- Affected Devices: All iOs physics devices and Simulator

### Screenshots

![image](https://user-images.githubusercontent.com/20004794/151922336-e3e758c0-627c-43d4-8202-79cfc21473d9.png)

**Comment by XamMattia83** [comment]
I have the same problem!!

**Comment by LordOfSmiles** [comment]
I have this problem only on M1 mac.

**Comment by XamMattia83** [comment]
I've tested all with  VS Mac 2019 8.10, Xamarin essentials 1.7.1 and Xamarin Forms 5.0.0.2337. At the end the problem on my side is only on Simulator (using an M1 mac)...no issues on the real device. @Alextorres950325  are you using a custom file type filter or you just call FilePicker.PickAsync()?

**Comment by jfversluis** [comment]
Make sure that you followed the instructions for the entitlements and provide document types you want to pick as described in the Docs: https://docs.microsoft.com/xamarin/essentials/file-picker

Additionally, this might be happening if another app declared your document type, see: https://betterprogramming.pub/how-to-fix-greyed-icons-on-ios-document-browser-and-picker-8dea8a76d6e7

I don't see a bug on our side here for now, if you think there is, please provide a reproduction sample, thanks!

**Comment by codercampos** [comment]
I have the same problem with and M1 but using the simulator. Testing my code with a physical device (iOS 13 Pro Max) allows me to pick a custom options (pdf + docx) or default File types.


This is my current configuration on the M1:

=== Visual Studio Community 2019 for Mac ===

Version 8.10.19 (build 2)
Installation UUID: 95e97d82-132e-4f2f-aea3-881f32a24f28
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 02:44:16 UTC

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/x64/sdk/6.0.102/Sdks
SDK Versions:
	6.0.102
	6.0.101
	5.0.405
	5.0.404
	3.1.416
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.2
	6.0.1
	5.0.14
	5.0.13
	3.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.416

=== .NET 5.0 SDK ===

SDK: 5.0.405

=== Xamarin.Profiler ===

Version: 1.7.0.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.2.1 (19586)
Build 13C100

=== Xamarin.Mac ===

Version: 8.6.0.3 (Visual Studio Community)
Hash: caa899d24
Branch: d17-1
Build date: 2022-01-16 21:16:56-0500

=== Xamarin.iOS ===

Version: 15.2.0.1 (Visual Studio Community)
Hash: 8fd9e6289
Branch: xcode13.1
Build date: 2021-10-26 10:13:56-0400

=== Xamarin.Android ===

Version: 12.2.99.75 (Visual Studio Community)
Commit: xamarin-android/main/398afd4
Android SDK: /Users/codercampos/Library/Android/sdk
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: a5d1934
Java.Interop: xamarin/java.interop/main@32635fd6
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.37.2@51b4821
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0e80ea1

=== Eclipse Temurin JDK ===

Java SDK: Not Found

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Build Information ===

Release ID: 810190002
Git revision: 632b6ca654e2733a685bfc9c6a0686e0a317092b
Build date: 2022-02-09 13:38:14-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.2.1
Darwin 21.3.0 Darwin Kernel Version 21.3.0
    Wed Jan  5 21:37:58 PST 2022
    root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 x86_64

**Comment by SukritJB** [comment]
This still exists, unable to select file on ios 15.4 simulator. Somehow it works on a ios 13.7 simulator. It's on a m1 mac mini

**Comment by mausv** [comment]
Having the same issue. All the docs are disabled on iOS 15.X simulators on an M1 Mac. I was able to debug my app with 14.5 and a physical device.

**Comment by follesoe** [comment]
@jfversluis This is a real bug and persists consistently on the iOS simulator but not on real devices and should not be closed. Multiple reports of the issue still existing.
