### ISSUE TITLE
[Bug] WebAuthenticationCallbackActivity missing android:exported

### ISSUE THREAD

**Issue by johanlangevillecab** [xamarin/Essentials#1963]
### Description
Xamarin.Essentials WebAuthentication do not work with Android 12 because the created activities in AndroidManifest are missing android:export

### Steps to Reproduce
1. Create a Xamarin app
2. Add Xamarin.Esentials WebAuthentication
3. Set Android Target Framework to 12 (S)
4. Build and deploy to Android Emulator with Android 12

### Expected Behavior
Should be able to deploy the app

### Actual Behavior
Get this error:
ADB0010: Mono.AndroidTools.InstallFailedException: Unexpected install output: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl510961283.tmp/base.apk 
	(at Binary XML file line #37): crc640d8d7625cc21797c.WebAuthenticationCallbackActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]

### Basic Information

- Version with issue: 1.7.1
- IDE: Visual Studio 2019
- Platform Target Frameworks: Android 12

**Comment by johanlangevillecab** [comment]
I realized that WebAuthenticationCallbackActivity is declared in my code!

**Comment by sdavis72** [comment]
@johanlangevillecab Did you fix this without changing the target version?  I remove the declaration and it compiles, but when I use it, the exception says I need it.  It being:

**Comment by sdavis72** [comment]
@johanlangevillecab Nevermind.  In my fervor of attempting to fix the myriad of issues upgrading from Xamarin 4 to 5, I had unintentionally removed (commented) my Xamarin.Essentials.Init method.  All is working again as expected.  Thank you GitKraken!

**Comment by fxsth** [comment]
If anyone is struggling with this problem in maui preview >=13, where Essentials is automatically configured (https://github.com/dotnet/maui/wiki/Migrating-to-Preview-13#android):
Just add the android:export to the Activity-Attribute and it works.
`[Activity(NoHistory = true, LaunchMode = LaunchMode.SingleTop, Exported = true)]`
