### ISSUE TITLE
[Enhancement] Directory Picker with Xamarin Essential

### ISSUE THREAD

**Issue by Pelinalpp** [xamarin/Essentials#1967]
If we set FilePickerFileType to "UTType.Folder" in ios, we can use Xamarin.Essentials FilePicker as directory picker. It would be nice if we could do this for android too. Because some developers can want to add folder picker their apps in order to select download directory or sync directory or etc..

The directory picker implementation is an easy feature with intents in android. In my opinion it would be nice if this feature is made for android/ios and added as a feature under xamarin essential.

**Comment by jamesmontemagno** [comment]
We are not accepting new feature requests at this time, will move to .NET MAUI.
