### ISSUE TITLE
Xamarin Forms Android 12 not working

### ISSUE THREAD

**Issue by bluekuen** [xamarin/Essentials#1971]
### Description
I installed shiny in my Xamarin Forms Project and followed the steps on getting started but when i try build and run i get the following error:

Java.Lang.IllegalArgumentException: 'ziehlabegg.zasetmobile: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.'

### Steps to Reproduce

1. install xamarin forms
2. installl shiny
3. Target Android Version 12

### Expected Behavior
Running
### Actual Behavior
Exception
### Basic Information

- Version with issue: latest
- Last known good version: dont know, first time using shiny
- IDE: VS22
- Platform Target Frameworks: Android 12
  - Android:  

- Nuget Packages: Shiny
- Affected Devices: Pixel 6

**Comment by BobbyCannon** [comment]
What was the fix?

**Comment by peterrexj** [comment]
Was there a fix to the problem?

**Comment by WillianDiazFS** [comment]
Any update about this?
