### ISSUE TITLE
[Bug] DeviceDisplay.MainDisplayInfoChanged not fired if app is in background (Android)

### ISSUE THREAD

**Issue by AlleSchonWeg** [xamarin/Essentials#1975]
### Description
If an app, which registered the DeviceDisplay.MainDisplayInfoChanged event, is in background and you rotate the device the event is not fired. Even if the app comes to foreground again.

iOS works as expected.
### Steps to Reproduce

See description.

### Expected Behavior
DeviceDisplay.MainDisplayInfoChanged event should be raised when app comes back to foreground.

### Actual Behavior
DeviceDisplay.MainDisplayInfoChanged is never raised.

### Basic Information

- Version with issue:
- Last known good version: 
- IDE: VS 2022
- Platform Target Frameworks: Android
  - iOS:  
  - Android: 12
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Essentials Version 1.7.1
- Affected Devices: Tested with simulator API 24

**Comment by rs-memosoft** [comment]
+1

**Comment by AlleSchonWeg** [comment]
https://github.com/dotnet/maui/issues/20305
