### ISSUE TITLE
[Bug] Uninstalling an App (either Android or iOS) does not remove Preferences or SecureStorage entries

### ISSUE THREAD

**Issue by norton287** [xamarin/Essentials#1977]
### Description
After uninstalling the app with Preferences and SecureStorage entries, they persist.  You can reinstall the app and the entries are still there.
### Steps to Reproduce

1. Add a Preference or SecureStorage entry
2. Uninstall the app
3. Reinstall the app and the entries will have persisted between the uninstall and reinstall.

### Expected Behavior
The entries should be removed upon uninstall of the application
### Actual Behavior
Entries are persisting and not being removed upon app uninstall
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2022
- Platform Target Frameworks: 
  - iOS:  15
  - Android: SDK 29-31 tested
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin.Essentials current release
- Affected Devices:

**Comment by mattleibow** [comment]
I am not so sure to be honest, I think the default function of both is to save preferences to the cloud. I think you should explicitly disable this in the manifests. 

https://docs.microsoft.com/en-us/xamarin/essentials/preferences?tabs=android#persistence

It can be disabled by following this: https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup

**Comment by norton287** [comment]
You are correct, not sure how I missed that!

**Comment by mattleibow** [comment]
No problem!
