### ISSUE TITLE
[Bug] DeviceInfo.Model returns invalid value for iPhone 12 Pro

### ISSUE THREAD

**Issue by wadebaird** [xamarin/Essentials#1981]
### Description
Calling Xamarin.Essentials.DeviceInfo.Model on my personal iPhone 12 Pro returns "iPhone13,3"

### Steps to Reproduce
1. Call Xamarin.Essentials.DeviceInfo.Model 

### Expected Behavior
returns something similar to 'iPhone 12 Pro'

### Actual Behavior
returns 'iPhone13,3'

### Basic Information

- Version with issue:1.7.1
- Last known good version: Unknown
- IDE: VS 2022 Community
- Platform Target Frameworks: 
  - iOS:  v4.0.30319
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by kcrg** [comment]
This is not a bug, this is how Apple calls its devices -  machine ids.
https://gist.github.com/adamawolf/3048717

**Comment by wadebaird** [comment]
Ah, thanks, I searched and couldn't find anything on the web for 13,3
