### ISSUE TITLE
[Bug] PhoneDialer not working with ios 15.4 if phone number has special characters 

### ISSUE THREAD

**Issue by kumarswamyk28** [xamarin/Essentials#1984]
We are using PhoneDialer for one of our xamarin apps and we are facing issues after updating to ios15.4. Phone Dialer is not throwing any error to catch and give an alternative way for customers. Btw Android works absolutely fine !

### Steps to Reproduce
`try
            {
                PhoneDialer.Open("*727575554444#");
            }
            catch (ArgumentNullException anEx)
            {
                // Number was null or white space
                Console.WriteLine("formatting wrong");
            }
            catch (FeatureNotSupportedException ex)
            {
                Console.WriteLine("FeatureNotSupportedException ");
                // Phone Dialer is not supported on this device.
            }
            catch (Exception ex)
            {
                Console.WriteLine("formatting wrong");
                // Other error has occurred.
            }`

### Expected Behavior
Phone Dialer Should open with given code
### Actual Behavior
Does not do anything nor throw error
### Basic Information

- Version with issue: ios15.4
- Last known good version: 15.3
- Nuget Packages: Xamarin.Essentials 1.7.1

**Comment by trevoriancox** [comment]
This is no doubt related to #1652 

Another test case to reproduce this on a simulator or real iOS device:

PhoneDialer.Open("5555551212#hash");

It will throw FeatureNotSupportedException in a different thread, so it cannot be caught.

Xamarin.Essentials 1.7.1

**Comment by jfversluis** [comment]
I guess the only thing we can do is surface an exception because this is simply [not supported on iOS](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/PhoneLinks/PhoneLinks.html)

> To prevent users from maliciously redirecting phone calls or changing the behavior of a phone or account, the Phone app supports most, but not all, of the special characters in the tel scheme. Specifically, if a URL contains the * or # characters, the Phone app does not attempt to dial the corresponding phone number.
