### ISSUE TITLE
Xamarin Essentials and SQLite issues after updating

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Essentials#1994]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-Essentials-and-SQLite-issues-aft/10012938)._

---
[severity:I'm unable to use this version]
After updating visual studio, I am having an issue with Xamarin Preferences saving values and SQLite saving values.
I dont get an error, just nothing saves from tab to tab.  I am curious if you guys have heard of issues like this from anyone else?

---
#### Feedback Bot on 4/14/2022, 03:29 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
If this happened after an upgrade of Visual Studio I think it's unlikely that this is an issue in Essentials. But if anything I'd need more information ideally in the form of a reproduction project. Closing this for now, let us know if you still have issues.
