### ISSUE TITLE
[Bug] WebAuthenticator - TaskCanceledException: A task was canceled

### ISSUE THREAD

**Issue by sunco007** [xamarin/Essentials#1998]
### Description

I'm working with a new clean app to use the WebAuthenticator. This may work with an external backend in **Php**

I already read [this](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=android), [this](https://github.com/xamarin/Essentials/blob/main/Samples/Samples.Android/MainActivity.cs) and [this](https://github.com/xamarin/Essentials/blob/main/Samples/Samples/ViewModel/WebAuthenticatorViewModel.cs) but still the same error: TaskCanceledException: A task was canceled

System.Threading.Tasks.TaskCanceledException: **A task was canceled**.
  at Xamarin.Essentials.WebAuthenticator.PlatformAuthenticateAsync (Xamarin.Essentials.WebAuthenticatorOptions webAuthenticatorOptions) [0x001e7] in D:\a\1\s\Xamarin.Essentials\WebAuthenticator\WebAuthenticator.android.cs:96 
  at LoginSocialPiano.MainPage.webView_Navigated (System.Object sender, Xamarin.Forms.WebNavigatedEventArgs e) [0x0014e] in C:\Users\XXXX\source\repos\XXXX\LoginSocialPiano\MainPage.xaml.cs:63 

The line 63 is just this: authResult = await WebAuthenticator.AuthenticateAsync(new Uri(datos), new Uri("xamarinessentials://"));

### This is the flow the app uses

If you follow the flow in desktop, it works. Of course, it fails at the end because the DataScheme is not there. The url in the app is just temporal, will change when all works

1- App connects via webview to backend to retrieve a Facebook url, something like this:

https://www.facebook.com/v2.6/dialog/oauth?display=popup&response_type=code&client_id=XXXX&redirect_uri=https%3A%2F%2Fid.tinypass.com%2Fid%2Fapi%2Fv1%2Fidentity%2Flogin%2Fsocial%2Fcallback&scope=email&state=XXXX

2- App then connects via **WebAuthenticator** to that url 

3- User interact and logged in

4- Facebook redirects to my provider (tinypass, piano.io)

5- The provider then calls my backend

6- The backend does some curl stuff

7- Backend redirects to the callback

This are 4 answers tried in the backend

header("location: xamarinessentials://#access_token=123", true, 302);
header("location: xamarinessentials://#access_token=123");
header("location: xamarinessentials://");
header("location: xamarinessentials://, true, 302);

### Expected Behavior

Return to the app and get the parameters

### Actual Behavior

Returns to the app and then says there is an error

### Basic Information

NETStandard.Library: 2.0.3
Xamarin.Essentials: 1.7.2
Xamarin.Forms: 5.0.0.2401
Visual Studio: 2022 - 17.1.4
Android: Real device - LG-X210 with Chrome 95.0.4638.74
Android SDK: 31.0.3
Target: 12.0 S (API 31)
Min ver: 5.0 API 21

### Reproduction Link

https://1drv.ms/u/s!AjVtN9vWQzh3nfAn0Nvyqgsu4AzAkw?e=P205vJ

When working, will clean and shrink the code. For now, I just want to make it work

**Comment by NaingGitHub** [comment]
I also facing the same issue. did you found the solution ? @sunco007
