### ISSUE TITLE
Launcher does nothing when you try to update enterprise app with a URI like itms-services 

### ISSUE THREAD

**Issue by stephenhauck** [xamarin/Essentials#2006]
I am simply trying to update an enterprise app like you can from a URL and it does nothing ... 

the URL is 
var tmpURI = new Uri($"itms-services://?action=download-manifest&url={App.Configuration.AppStoreURL}/manifest.plist");

The AppStoreURL has an HTTPS prefix 
I have tried it as a string as well to no avail 
**If I simply paste the URI into Safari on the iOS simulator it works fine.**

I have even tried to invoke Launcher on the main thread 

![image](https://user-images.githubusercontent.com/12648793/166496589-c4c25647-6b7f-48b4-b328-4d83f6855666.png)

![image](https://user-images.githubusercontent.com/12648793/166496693-920408e6-efb0-449b-a0b6-510317941ff9.png)

I am running on the iOS Simulator on an iPhone 8 iOS 15.4

Am I missing formation of the URI ?

I'm kind of out of options and need a solution /  workaround as soon as possible 

Thanks

**Comment by stephenhauck** [comment]
Bump ... 

- Platform specific workaround ?
- Improper usage ?
- Further configuration of project / app settings required ?

Thanks for any assistance .. I really need this to work ...

**Comment by czuck** [comment]
Does Browser.OpenAsync work?  Do you have ResizeableActivity = false on either your application or activity?

**Comment by stephenhauck** [comment]
Can I pay someone for an answer ?
@jamesmontemagno 
@maddymontaquila

**Comment by stephenhauck** [comment]
Bump ... anyone ?

**Comment by jamesmontemagno** [comment]
The source code for this is very minimal... you could try call it direct and see.

```
        static Task<bool> PlatformCanOpenAsync(Uri uri) =>
            Task.FromResult(UIApplication.SharedApplication.CanOpenUrl(WebUtils.GetNativeUrl(uri)));

        static Task PlatformOpenAsync(Uri uri) =>
            PlatformOpenAsync(WebUtils.GetNativeUrl(uri));

        internal static Task<bool> PlatformOpenAsync(NSUrl nativeUrl) =>
            Platform.HasOSVersion(10, 0)
                ? UIApplication.SharedApplication.OpenUrlAsync(nativeUrl, new UIApplicationOpenUrlOptions())
                : Task.FromResult(UIApplication.SharedApplication.OpenUrl(nativeUrl));
```

1.) Does "CanOpenAsync" return true or false?
2.) Did you try it on a real device?
3.) Read this thread: https://developer.apple.com/forums/thread/86438 you will need real ssl certs it looks like and tls 1.2 on the server

**Comment by stephenhauck** [comment]
"CanOpenAsync" returns true ...
I have not tried it on a real device because pasting the URI into the browser on the iOS simulator functions properly 
Working on platform specific test now

**Comment by stephenhauck** [comment]
OK .. did some exhaustive testing ... 

This is insane ... 

If you take the URL and paste it into the iOS simulator it works fine ...
If you try to use launcher on the iOS simulator it says "I know how to handle this" nd when it does nothing happens
NO ERROR IS THROWN!

It's almost like iOS is not mapping the MIME type appropriately or not passing the correct information to the browser ...

I built and deployed via Appcenter and confirmed it does work on the actual device !

The documentation needs to reflect this in bold but it would be better if we could make it work on the iOS simulator as well!

Thanks @jamesmontemagno for your response ....

**Comment by jamesmontemagno** [comment]
@stephenhauck if you have recommendations on the documentation please send a PR
