### ISSUE TITLE
[Bug] Launcher doesn't open URL if ResizableActivity = false, behavior changes between 1.4 & 1.5

### ISSUE THREAD

**Issue by czuck** [xamarin/Essentials#2007]
### Description

Opening a uri using Launcher.OpenAsync using Version 1.4 on a Pixel 3 XL opens in a browser window full screen.  Using 1.5, the launcher opens the browser in multi window instead of full screen with no other changes to the app.  Adding ResizableActivity=false to either the MainApplication or MainActivity results in the browser not opening at all.

### Steps to Reproduce

1. Run the attached test app.  Press the button "Launch Website" and the web page opens full screen.  Note that is it running Essentials 1.4.0
2. Open NuGet on the solution and install Essentials 1.5.0.  Run the app and press the same button, note that the web page opens in multi screen mode.
3. In MainActivity.cs comment out the activity on lines 8-9 and uncomment the one on 10-11.  Note the only difference is the ResizableActivity=false added on line 10.  Run the app and press the button, nothing happens.  Open MainPage.xaml.cs and add a breakpoint on the Launcher command, line 16.  Press the button again and the breakpoint will hit, continue and observe that still nothing happens.
4. Return MainActivity.cs to it's initial state.  Open MainApplication.cs and uncomment the code.  Run again, again the breakpoint will hit but the web page will not open.
5. Install Essentials 7.2 and repeat steps 2-4.

### Expected Behavior
Upgrading from Essentials 1.4.0 to 1.5.0 shouldn't change how the browser is opened.
Adding ResizableActivity=false shouldn't stip the launcher from opening

### Basic Information

- Version with issue: 1.5.0 - 1.7.2
- Last known good version: 1.4.0
- IDE: VS2019
- Platform Target Frameworks: 
  - Xamarin:16.11.000.197
  - Android: 12.0.0.3
- Android Support Library Version: 
- Nuget Packages:
- NETStandard.Library 2.0.3
- Xamarin.Forms 5.0.0.2401
- Affected Devices: Pixel 3 XL

  
### Reproduction Link

[LauncherTest.zip](https://github.com/xamarin/Essentials/files/8614602/LauncherTest.zip)

**Comment by jamesmontemagno** [comment]
Will be fixed in 1.7.4
