### ISSUE TITLE
[Bug] 拍照默认旋转了90度的问题，如何解决，谢谢

### ISSUE THREAD

**Issue by yaj806** [xamarin/Essentials#2008]
使用 photo = await MediaPicker.CapturePhotoAsync();
获得的照片默认旋转了90度。怎么让他回正。

在IOS真机上测试出现此问题

**Comment by jfversluis** [comment]
Hey there, while I can't read what you're saying, I used a translation service and it seems you're asking about the MediaPicker rotation issue. There has been a lot written about that. Unfortunately, we won't be adding that for Xamarin.Essentials anymore.

You can either use James Montemagno's MediaPlugin or use the MediaGallery that works for both Xamarin.Forms and .NET MAUI: https://github.com/dimonovdd/Xamarin.MediaGallery

We will fix it for .NET MAUI in time. Thanks!
