### ISSUE TITLE
[Bug] Why does Xamarin.Essentials have an upper limit on Xamarin.AndroidX.Browser?

### ISSUE THREAD

**Issue by SaqibS** [xamarin/Essentials#2019]
In a Xamarin.Android project, getting errors having Xamarin.Essentials 1.7.3 and Xamarin.AndroidX.Browser 1.4.0.2.

This is because Xamarin.Essentials has a constraint that Xamarin.AndroidX.Browser < 1.4.0.

I could downgrade either of the packages, trying to figure out which one is less criticial, but also curious why this constraint exists?

**Comment by tranb3r** [comment]
Dependency hell:
Xamarin.Firebase.Auth 121.0.1.7 -> Xamarin.AndroidX.Browser (>= 1.4.0.1) 
Xamarin.Essentials 1.7.3 -> Xamarin.AndroidX.Browser (>= 1.3.0.5 && < 1.4.0)
Xamarin.Forms 5.0.0.2478 -> Xamarin.AndroidX.Browser (>= 1.3.0.6 && < 1.4.0)

**Comment by copang** [comment]
Any new update? I'm looking forward to version 1.7.4 :(

**Comment by AlexanderVanMeerten** [comment]
And for Xamarin.Forms support for Xamarin.AndroidX.Browser 1.4.0

**Comment by Ilker-Ketjapp** [comment]
Any update? PR #2038 is still open

**Comment by AndreyPhilippov** [comment]
Any updates? Since we have this restriction i can't use some other nuget packages requiring Xamarin.AndroidX.Browser >= 1.4.0

**Comment by uwe-neuronation** [comment]
Any updates? I guess it the same issue like #2057 
Is there any workaround already?

**Comment by mohibsheth** [comment]
I'm again having the same problem. 

Unable to resolve dependencies. 'Xamarin.AndroidX.Browser 1.4.0.4' is not compatible with 'Xamarin.Essentials 1.7.5 constraint: Xamarin.AndroidX.Browser (>= 1.3.0.5 && < 1.4.0.3)'

I'm unable to update to 1.4.0.4 due to the constraint with Xamarin.Essentials however I need 1.4.0.4 to update another nuget.

**Comment by RealSourceOfficial** [comment]
+1, I can't use the Xamarin Essentials either

**Comment by Kanat9494** [comment]
I am trying to use Xamarin.Firebase.Auth in net maui

**Comment by lufo88ita** [comment]
This topic was opened 1 year ago! No fix or news?

**Comment by MitchBomcanhao** [comment]
> This topic was opened 1 year ago! No fix or news?

Perhaps the newer beta essentials version with newer android api support will have changes in this area? Am on holidays now so cannot try it but I'd definitely try it if I were you

**Comment by MitchBomcanhao** [comment]
@lufo88ita the nuget page for the new version mentions this as its dependency:

[Xamarin.AndroidX.Browser](https://www.nuget.org/packages/Xamarin.AndroidX.Browser/) (>= 1.0.0)

**Comment by lufo88ita** [comment]
Great, but Xamarin is a product by Microsoft, I will expect the news from a member of the team :-)

**Comment by malotho** [comment]
Xamarin has to be the worst supported product in all Microsoft
