### ISSUE TITLE
[Bug] Launcher: Pixel 4 or newer, Android 12 forces split screen when opening files with default app

### ISSUE THREAD

**Issue by NavaJoey** [xamarin/Essentials#2023]
### Description
On Pixel 4 devices or newer with Android 12, if a file is opened using `Launcher.OpenAsync()` the file is opened in split screen mode adjacent to the source app regardless of whether `android:resizeableActivity` is `false` in the manifest file.

The issue is that when it goes into split screen mode the source app is reloaded and any in-progress state is lost in that app.

I've narrowed the problem down to the following logic in the `PlatformOpenAsync()` method of the `Launcher.android.cs` file:

`#if __ANDROID_24__
            if (Platform.HasApiLevelN)
                flags |= ActivityFlags.LaunchAdjacent;
#endif`

Removing this logic fixes the issue.

### Steps to Reproduce

1. Deploy your Xamarin App to a Pixel 4 or newer device
2. Open a PDF or DOCX file from your Xamarin App using `Launcher`

### Expected Behavior
PDF or DOCX file should be opened in a new window and the source app state should remain as before if `android:resizeableActivity` is `false`

### Actual Behavior
PDF or DOCX file is open adjacent in split screen mode and the source app is reloaded, losing any in-progress state

### Basic Information

- Version with issue:
- Nuget Packages: Xamarin.Forms 5.0.0.2012, Xamarin.Essentials 1.7.1
- Affected Devices: Pixel 4a, Pixel 5

**Comment by joemather** [comment]
Relates to https://github.com/xamarin/Essentials/issues/1817

**Comment by iBobb** [comment]
A side effect of that is that deep linking was working fine but now my app crashes when it is opened. Before that "adjacent" flag was there, it was all good, so i'd be interested in such an option being available

**Comment by djrpascu** [comment]
Does anyone have a workaround for this? Or do we build a local version of XE and apply changes @NavaJoey suggested ourselves?

**Comment by danpowell88** [comment]
The following worked for me inside the MainApplication

```
        public override void StartActivity(Intent intent)
        {
            // Hack to prevent split screen issues, needs to happen here
            // as disabling in attributes causes app to crash
            if (Build.VERSION.SdkInt >= BuildVersionCodes.N)
                intent.RemoveFlags(ActivityFlags.LaunchAdjacent);

            base.StartActivity(intent);
        }
```

**Comment by BillyMartin1964** [comment]
I don't have a problem launching websites, but this happens when I try to use AppInfo.ShowSettingsUI(); and the above code doesn't help:

![image](https://user-images.githubusercontent.com/29313458/201915646-1ca41151-4c4c-467a-add6-2887d1ffe24f.png)

**Comment by kkppstudios** [comment]
I'm seeing issue occur when simply doing a ComposeEmail() call too.

**Comment by andreasbrostencab** [comment]
Great that a fix seems on it's way. 
When can I expect v 1.7.4 (with this fix included?) to be released?

**Comment by BillyMartin1964** [comment]
Thanks James and Gerald. You guys are great. Keep up the amazing work!

**Comment by rutgersc** [comment]
Thanks for the fix! Any idea when this will be available? I saw 1.7.4 on the github release page, but it's not yet available on nuget it seems. @jfversluis

**Comment by kkppstudios** [comment]
Still waiting for 1.7.4 on nuget..

**Comment by Cr15Denis** [comment]
hello friends I found this solution just apply "ResizeableActivity = false," in the MainActivity. https://devblogs.microsoft.com/xamarin/optimizing-android-apps-for-multi-window-mode/

**Comment by samuelGrahame** [comment]
> hello friends I found this solution just apply "ResizeableActivity = false," in the MainActivity. https://devblogs.microsoft.com/xamarin/optimizing-android-apps-for-multi-window-mode/

I have this in my app:

Samsung galaxy note 20 - with the samsung app even without having launch LaunchAdjacent (forked copy) and removing the flag on start activity it still opens LaunchAdjacent.

does anyone have a workout around. (is this related to the edge panel in Samsung where you can specify to open in split view)

**Comment by Cr15Denis** [comment]
I am attaching the problem I had on a Samsung galaxy A13 Android 12, And I am attaching the solution in Xamarin Forms Android.

Problem:


https://user-images.githubusercontent.com/70722700/217024937-e1b6e148-e6d0-43a5-a10c-a3bdb9e68901.mp4

Solution: 


In the Android project, in the file "MainActivity.cs"

![solution](https://user-images.githubusercontent.com/70722700/217025138-c40a3109-e7c2-4408-ba58-5da877934642.png)

Result:


https://user-images.githubusercontent.com/70722700/217025670-ce964867-f603-4b5d-998c-1065494b27ea.mp4


I hope they can also solve the problem. greetings friends

**Comment by Cr15Denis** [comment]
Hello friend, right now I published the solution in the github ISSUE, take a look. greetings
________________________________
De: Samuel ***@***.***>
Enviado: domingo, 5 de febrero de 2023 20:52
Para: xamarin/Essentials ***@***.***>
Cc: Cr15Denis ***@***.***>; Comment ***@***.***>
Asunto: Re: [xamarin/Essentials] [Bug] Launcher: Pixel 4 or newer, Android 12 forces split screen when opening files with default app (Issue #2023)


hello friends I found this solution just apply "ResizeableActivity = false," in the MainActivity. https://devblogs.microsoft.com/xamarin/optimizing-android-apps-for-multi-window-mode/

I have this in my app:

Samsung galaxy note 20 - with the samsung app even without having launch LaunchAdjacent (forked copy) and removing the flag on start activity it still opens LaunchAdjacent.

does anyone have a workout around. (is this related to the edge panel in Samsung where you can specify to open in split view)

**Comment by samuelGrahame** [comment]
Thank you, all solved.
