### ISSUE TITLE
[Bug] FilePicker.PickAsync() returns random results

### ISSUE THREAD

**Issue by formerlymisterhenson** [xamarin/Essentials#2025]
### Description
Whilst I was using FilePicker.PickAsync()  in <= 1.7.0 with no problems, our users reported in our current (Xamarin Forms) app release, that the FilePicker is not working anymore (for us). I was able to reproduce that, without Exceptions or permission problems.
The problem is, that in about 4 of 5 cases PickAsync returns null instead of the file result.

Well, there are not that many things where you could go wrong, I guess:
 ```
try
{
    //Device.BeginInvokeOnMainThread(async () => // did not matter here
    {
        var result = await FilePicker.PickAsync();

        if (result != null) // only 1 in 5 cases
        {
            using var stream = await result.OpenReadAsync();
            ...
        }
    } 
    //);
}
catch (Exception e)
{
    // does not happen
    Log.Error($"blah {e}");
}
```

I was trying to understand what's the problem here and had a look at:
https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/FilePicker/FilePicker.ios.cs

I think there is something suspicious about that DismissHandler thing introduced with https://github.com/xamarin/Essentials/pull/1846
```
documentPicker.PresentationController.Delegate = new Platform.UIPresentationControllerDelegate
{
    DismissHandler = () => GetFileResults(null, tcs)
};
```
So I reverted Essentials to 1.7.0 and it did work fine again. Upgrading to 1.7.1, 1.7.2, 1.7.3 it does not work (reproducible for me).

### Steps to Reproduce (I guess)
1. use FilePicker.PickAsync() on iOS
2. pick a file by tapping one
3. (dialog closes)

### Expected Behavior
PickAsync returns a FileResult.

### Actual Behavior
PickAsync returns in most cases null.

### Basic Information

- Version with issue: 1.7.1, 1.7.2, 1.7.3, **1.8.0**
- Last known good version: 1.7.0
- IDE: VS 17.3 Pre 1.1, **17.9.0 Preview 1.1**
- Platform Target Frameworks: 
  - iOS:  15.5 (physical device iPad Pro 12,9, attached to Mac but also in Release as custom app with App Store), **17.1.1**
  - Android: (not in active development)
  - UWP:  -

**Comment by sekhonitconsultants** [comment]
@formerlymisterhenson  Thanks a million for your post, after trying all left right and centre I had revert Xamarin Essential to 1.7.0 to make file upload work. 
I hope guys will fix it in the future release

**Comment by formerlymisterhenson** [comment]
Would be nice, if someone would have a look in this after 1,5 years??
