### ISSUE TITLE
[Bug] Application hangs when using Connectivity on x86_64 emulator

### ISSUE THREAD

**Issue by Snegovikufa** [xamarin/Essentials#2035]
### Steps to Reproduce

1. Create a new Android application with LLVM and AOT enabled.
2. Add `Connectivity.PlatformConnectionProfiles` somewhere
3. Run app on x86_64 emulator.

### Expected Behavior

Application does not hang.

### Actual Behavior

Application hangs.

### Basic Information
- Platform Target Frameworks: 
  - Android: 12
- Affected Devices: x86_64 emulator, Chromebook with Intel

**Comment by jfversluis** [comment]
See https://github.com/xamarin/Essentials/pull/2036#issuecomment-1845465648
