### ISSUE TITLE
[Bug]  internal static Exception NotImplementedInReferenceAssembly()         {             return new NotImplementedException("This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.");         }

### ISSUE THREAD

**Issue by TimoKinnunen** [xamarin/Essentials#2048]
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by TimoKinnunen** [comment]
What to do to get Plugin.BLE to work on Windows?

I have a working .Net MAUI sample on Android but Windows is difficult?
https://github.com/TimoKinnunen/MauiXAMLBluetoothLE

**Comment by mattleibow** [comment]
Could you open an issue on the Plugin.BLE repository instead? This is the Essentials repository.

**Comment by TimoKinnunen** [comment]
Thank you. Opened a new issue https://github.com/xabre/xamarin-bluetooth-le/issues/626.
