### ISSUE TITLE
[Bug] FilePicker doesn't allow picking any files on iOS

### ISSUE THREAD

**Issue by EpEthan** [xamarin/Essentials#2050]
### Description
I need to import **CSV**/**SQLite3** files in my app. I use `Xamarin.Essentials.FilePicker` and it works perfectly on Android, however when trying it on iOS all the files are greyed-out and I can't select any file.

I use the following file types for Android and iOS:

```csharp
var customFileType =
    new Xamarin.Essentials.FilePickerFileType(new Dictionary<Xamarin.Essentials.DevicePlatform, IEnumerable<string>>
    {
        { Xamarin.Essentials.DevicePlatform.iOS, new string[] {
            "public.comma-separated-values-text",
            "text/csv",
            "comma-separated values",
            "CSV document",
            "csv",
            "public.database",
            "application/x-sqlite3",
            "application/vnd.sqlite3",
            "application/octet-stream",
        } },
        { Xamarin.Essentials.DevicePlatform.Android, new string[] {
            "text/csv",
            "Comma-separated values",
            "CSV document",
            "application/x-sqlite3",
            "application/vnd.sqlite3",
            "application/octet-stream"
        } },
    }) ;
```

I've also tried adding `text/plain` for picking **CSV** files on iOS and it didn't work. In addition, I've tried selecting **PDF** files using `pdf` and it didn't work.

**[StackOverflow Thread](https://stackoverflow.com/questions/74101854/xamarin-essentialss-filepicker-doesnt-allow-picking-any-files-on-ios)**

### Expected Behavior
File-picking dialog shows relevant files (CSV/SQLite3) not greyed out, and they're clickable.

### Actual Behavior
File-picking dialog does not allow to pick any file in iOS.

### Basic Information

- Version with issue: `1.7.3`
- Last known good version: Unknown
- IDE: VS 2022 Community
- Platform Target Frameworks: 
  - iOS: `XCode 14.0` (testing on and iOS 16.0 Simulator)
  - Android: `API 31`  
- Affected Devices: iOS 16.0 Simulator

### Screenshots
![Screenshot_12](https://user-images.githubusercontent.com/31385999/196788125-dd0a1716-869b-41b2-90fe-7a4fb72a50eb.png)
![Screenshot_13](https://user-images.githubusercontent.com/31385999/196788130-9db963ea-d4b4-452c-8ac4-7058216d8345.png)

**Comment by jfversluis** [comment]
On iOS you will have to use the UTType or the reverse domain identifier for these files, see also the example [here](https://learn.microsoft.com/xamarin/essentials/file-picker?tabs=ios#pick-file)

[Here](https://developer.apple.com/documentation/uniformtypeidentifiers/system-declared_uniform_type_identifiers?language=objc) is a list as given by Apple that are built-in, yours might be a custom one.

**Comment by EpEthan** [comment]
I am aware of the `MobileCoreServices.UTType`. I've tried using `MobileCoreServices.UTType.CommaSeparatedText` (resolves to `"public.comma-separated-values-text"`) as well as `MobileCoreServices.UTType.Database` (resolves to `"public.database"`) and neither worked. I wrote their plaintext versions to be more comprehensive.

**Comment by EpEthan** [comment]
I would appreciate if you re-open the bug and check it out
