### ISSUE TITLE
DeviceInfo.Name not working on OS16

### ISSUE THREAD

**Issue by taylorjimbo** [xamarin/Essentials#2059]
Property DeviceInfo.Name return iPad for device running iOS 16

UIDevice.current.name worked on iOS15, but when is does not on iOS16 it returns 'iPad' all the time.

I'm guessing this is an Apple entitlement issue

**Comment by jfversluis** [comment]
Looks like if you add the right metadata to your iOS app it will still work. Let us know if that is not the case. Thanks for the report!
