### ISSUE TITLE
[Bug] Push Notification Permission is not supported by "Permissions" component

### ISSUE THREAD

**Issue by thisisthekap** [xamarin/Essentials#2062]
### Description

The Push Notification permission management for both iOS and Android (for Android >= 13) is not supported by the `Permissions` component.

### Expected Behavior

Being able to manage push notification permissions using Xamarin.Essentials.

### Actual Behavior

Impossible to manage push notification permissions using Xamarin.Essentials, although many other permissions are supported.

**Comment by trampster** [comment]
We need this as well, as we will not be moving to Maui until next year.

**Comment by gitknul** [comment]
You could use the MediaPlugin plugins, specifically the beta-version. It supports the API 33 permissions. 

* https://github.com/jamesmontemagno/MediaPlugin
* https://www.nuget.org/packages/Xam.Plugin.Media/6.0.1-beta

**Comment by jfversluis** [comment]
Unfortunately we won't be adding this to Xamarin.Essentials. See the explanation in the PR #2063

**Comment by nk-alex** [comment]
https://github.com/trailheadtechnology/NotificationApp
