### ISSUE TITLE
Due to old UAP version, X.E won't build with newer VS updates.

### ISSUE THREAD

**Issue by CartBlanche** [xamarin/Essentials#2071]
### Description

Currently uap version is *.16299. Updating to *.19041  should fix the issue.

### Steps to Reproduce

1. Use VS 17.4.* on Windows and try to build a Xamarin.Essentials. 

### Expected Behavior

It builds.

### Actual Behavior

If fails to build.

**Comment by jfversluis** [comment]
"It fails to build" what is the error? Isn't it due to the right SDK not being installed on your machine maybe?

**Comment by jfversluis** [comment]
No response, I'm going to assume you figured something out, thanks!
