### ISSUE TITLE
[CI] Add automated compliance tasks to pipeline

### ISSUE THREAD

**Issue by pjcollins** [xamarin/Essentials#2080]
We are missing a handful of compliance tasks on this rep (policheck and credscan) which should be added to the build pipeline.

**Comment by jfversluis** [comment]
Hey @pjcollins missed this one, sorry. Will add it asap, thanks!

**Comment by pjcollins** [comment]
It looks like there is actually some coverage credscan and policheck through https://github.com/xamarin/XamarinComponents/blob/main/.ci/build.v1.yml, though the policheck task version is out of date. I would recommend onboarding to https://github.com/xamarin/yaml-templates/blob/main/security/full/v0.yml when possible to get the latest versions of the tasks.
