### ISSUE TITLE
[Bug] Usage of Xamarin Essentials is disabled by AndroidX.Browser

### ISSUE THREAD

**Issue by RealSourceOfficial** [xamarin/Essentials#2083]
### Description
Usage of the Xamarin Essentials library is (again) disabled by AndroidX.Browser, as it is 1 version ahead of the max version. Can not downgrade AndroidX.Browser as it is "disabled by project"
### Steps to Reproduce

1. Install Xamarin.AndroidX.Browser 1.4.0.3
2. Install Xamarin.Essentials 1.7.5
3. Compatibility issues

### Expected Behavior
Usage of Xamarin.Essentials
### Actual Behavior
Disabled
### Basic Information

- Version with issue: 1.7.5
- Last known good version: None
- IDE: Visual Studio 2022
- Platform Target Frameworks: 
  - Android: Android 13.0 API 33
- Nuget Packages: CommunityToolkit.Maui 3.1.0, CommunityToolkit.Mvvm 8.1.0, Microsoft.Extensions.Logging.Debug 7.0.0, Xamarin.Essentials 1.7.5, (Xamarin SDK)
- Affected Devices: Android 13.0

### Screenshots

![image](https://user-images.githubusercontent.com/65256422/231022001-b9459ae5-76b9-4e53-ba57-dc07799f3c55.png)

### Reproduction Link

![Project](https://drive.google.com/file/d/1qiTbNAmBf02VRr1NcsNPXc7fVB4baFxq/view?usp=sharing)

**Comment by jfversluis** [comment]
I'm a bit puzzled by this in your report:

> CommunityToolkit.Maui 3.1.0, CommunityToolkit.Mvvm 8.1.0, Microsoft.Extensions.Logging.Debug 7.0.0, Xamarin.Essentials 1.7.5, (Xamarin SDK)

How and why are you using the .NET MAUI Toolkit and Xamarin.Essentials in the same project? If this is a .NET MAUI project, you should not need Xamarin.Essentials anymore.

**Comment by MagicAndre1981** [comment]
@jfversluis Essentials depends on older [Xamarin.AndroidX.Browser version](https://github.com/xamarin/Essentials/blob/35c56205769b1434838ad31ff9c65d5d0c3f50d5/Xamarin.Essentials/Xamarin.Essentials.csproj#L80) . Maybe you should also target Essentials against MonoAndroid13.0 and latest Xamarin.AndroidX.Browser version 1.5.0 🤔

**Comment by jfversluis** [comment]
@MagicAndre1981 sure, but this project uses Xamarin.Essentials in .NET MAUI which shouldn't be needed and is likely causing issues.

**Comment by RealSourceOfficial** [comment]
> I'm a bit puzzled by this in your report:
> 
> > CommunityToolkit.Maui 3.1.0, CommunityToolkit.Mvvm 8.1.0, Microsoft.Extensions.Logging.Debug 7.0.0, Xamarin.Essentials 1.7.5, (Xamarin SDK)
> 
> How and why are you using the .NET MAUI Toolkit and Xamarin.Essentials in the same project? If this is a .NET MAUI project, you should not need Xamarin.Essentials anymore.

I realized I fixed this a while back, but yes I did realize I didn't need it. I have been reading really out-of-date guides on .NET MAUI stuff that used to require it (at least that's what I understand)
