### ISSUE TITLE
[Bug] [Android] [Regression] 1.8.0 Android assembly doesn't appear to contain Xamarin.Essentials.Platform

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Essentials#2097]
### Steps to Reproduce

1. Upgrade Xamarin Forms app using Xamarin Essentials 1.7.7 to 1.8.0
2. Build Android project
3. Observer build errors

### Expected Behavior

No API changes

### Actual Behavior

1>C:\Operations\Build\Home\Sideroads\Source\Sideroads.Xamarin\Sideroads.Android\MainActivity.cs(138,13,138,40): error CS0234: The type or namespace name 'Platform' does not exist in the namespace 'Xamarin.Essentials' (are you missing an assembly reference?)
1>C:\Operations\Build\Home\Sideroads\Source\Sideroads.Xamarin\Sideroads.Android\MainActivity.cs(190,13,190,40): error CS0234: The type or namespace name 'Platform' does not exist in the namespace 'Xamarin.Essentials' (are you missing an assembly reference?)

The lines in question are

`            Xamarin.Essentials.Platform.Init(this, bundle);`

and

`            Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);`

### Basic Information

- Version with issue: 1.8.0
- Last known good version: 1.7.7
- IDE: VS 2022 latest stable
- Platform Target Frameworks: 
  - Android: 13

**Comment by jfversluis** [comment]
I see you mention that you're targeting Android 13 but can you double-check? I've had other reports and they let me know that targeting Android 13 fixed it for them.

Xamarin.Essentials 1.8 now has MonoAndroid13 as the target framework, your project should do the same :)

**Comment by mfeingol** [comment]
That was it, thanks. UI showed using SDK version 13 (which I think is read/written from the manifest), but TargetFrameworkVersion in csproj was still set to 12.

**Comment by jfversluis** [comment]
Thanks for letting me know! I did update the GitHub releases here to make this a little more clearer as well.
