### ISSUE TITLE
Xamarin.Essentials 1.8.0 FilePicker gives NotImplementedInReferenceAssemblyException

### ISSUE THREAD

**Issue by Doug910** [xamarin/Essentials#2101]
### Description
FilePicker worked when using Essentials 1.6.0, when I upgraded to 1.8.0 I get this exception in Android every time.

### Steps to Reproduce

1.  Create a FilePicker test program using Xamarin.Essentials version 1.6.0.
2.  Test the Android implementation and check that it works as expected.
3.  Update Essentials to 1.8.0.
4. Test again on Android.

### Expected Behavior

Get FilePicker displayed and working on device

### Actual Behavior

Get NotImplementedInReferenceAssemblyException when the PickOptions are created.

### Basic Information

- Version with issue: 1.8.0
- Last known good version: 1.6.0
- IDE: Visual Studio 2022
- Platform Target Frameworks: Android API 28
 - Android:  9.0 
 - Nuget Packages: Xamarin.Forms 4.3.0.908675 (same error with later versions), Xamarin.Essentials 1.8.0
- Affected Devices: Android Emulator Pixel 5 Android 9

**Comment by Doug910** [comment]
This exception was caused by Essentials not being initialised, because the Platform.Init line would not compile with a target of API 28, so it was commented out.
It would be a lot more informative to have an "essentials not initialised exception", this would have saved me a lot of time trying to figure out what was wrong.

**Comment by MitchBomcanhao** [comment]
target api 28 has been obsolete for several years now, you wouldn't even be allowed to publish such an app to the store, so your starting position was something that wouldn't be workable on a production environment anyway.

**Comment by Doug910** [comment]
The app is for a particular set of work devices running api 28, I have no plans to publish it. It is a bit annoying being forced to target api 33, just to get the compiler to recognise that Essentials.Platform exists.

**Comment by jfversluis** [comment]
Looks like this has been resolved, thanks!
