### ISSUE TITLE
[Bug] [Bug] Xamarin Essentials connectivity - Android 14 Crash - java.lang.SecurityException:One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts(API level 34)

### ISSUE THREAD

**Issue by abdul-wasey** [xamarin/Essentials#2113]
Xamarin.Essentials (1.8.0) connectivity - Android 14 Crash - java.lang.SecurityException:One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts(API level 34)[Bug] 

### Expected Behavior
The app should not crash while running on Android 14.

### Actual Behavior
The app is crashing while running on Android 14 due to missing flags ( RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED).

### Basic Information

- Platform Target Frameworks: 
  - iOS:  Not affected.
  - Android:  13.2.2.0
  - UWP:   Not affected
  - Affected Devices: Android 14 Only

**Comment by jfversluis** [comment]
Duplicate of #2107
