### ISSUE TITLE
exceptions thrown??

### ISSUE THREAD

**Issue by tele-bird** [xamarin/Essentials#2128]
### Type of issue

Incomplete information

### Description

Please add to your documentation the exceptions thrown by these methods.  thanks

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/xamarin.essentials.browser.openasync?view=xamarin-essentials-android#xamarin-essentials-browser-openasync(system-string-xamarin-essentials-browserlaunchmode)

### Content source URL

https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/Browser.xml

### Document Version Independent Id

e7be783d-b243-a61f-1a2c-ee651aacb12f

### Article author

@dotnet-bot

### Metadata

* ID: 7a52688d-0c2d-da88-9873-7003da5629da 
* Service: **xamarin**
* Sub-service: **xamarin-essentials**

**Comment by jfversluis** [comment]
What exception are you referring to specifically? Because I can see only 1 exception being thrown from Android explicitly in our code?

**Comment by jfversluis** [comment]
No response, so not sure what to fix here. Closing for now.
