### ISSUE TITLE
magnometro xamarin form

### ISSUE THREAD

**Issue by leibnytz2014** [xamarin/Essentials#2135]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/xamarin.essentials.magnetometer?view=xamarin-essentials-android

### Content source URL

https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/Magnetometer.xml

### Document Version Independent Id

f2c77397-2235-4852-0824-e61d9dcd8d9e

### Article author

@dotnet-bot

### Metadata

* ID: 7cb1ed5c-1686-a7c8-be30-c0d30ec7d031 
* Service: **xamarin**
* Sub-service: **xamarin-essentials**

**Comment by jfversluis** [comment]
@leibnytz2014 thank you, but could you maybe specify what the typo is?

**Comment by jfversluis** [comment]
No response so not sure what this is about. Closing for now.
