### ISSUE TITLE
Detect User Interaction API

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#215]
Idea would be to have a way to see if there is any user interaction with the app. Often apps need to lock out functionality or log out the user if it isn't being used for X amount of time.

iOS: https://blog.gaelfoppolo.com/detecting-user-inactivity-in-ios-application-684b0eeeef5b
Android: https://developer.xamarin.com/api/member/Android.App.Activity.OnUserInteraction/
UWP: GetLastInputInfo 

This may be too dependent on locking into the app itself though?

> VS bug [#735672](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735672)

**Comment by MiguelRa** [comment]
Hi! Any plans to implement this in near future?

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
