### ISSUE TITLE
Add alert/dialog API

### ISSUE THREAD

**Issue by tomcurran** [xamarin/Essentials#219]
### Description

Ability to display popup style messages with single or multiple choices for the user. Something I find myself doing frequently to handle errors or ask for a simple user decision without building additional UI. Similar idea to the xamarin forms display alert function ([docs](https://developer.xamarin.com/api/member/Xamarin.Forms.Page.DisplayAlert/p/System.String/System.String/System.String/System.String/))

### Alert API

- `Task Show(string title, string message, string button1)`
- `Task<string> Show(string title, string message, string button1, string button2)`
- `Task<string> Show(string title, string message, string button1, string button2, string button3)`

### Example
``` c#
var alert = await Alert.Show("Big decision", "Do you want ice cream?", "Yes", "No");
if (alert == "Yes")
{
    // handle the successful case
}
else
{
    // wait that can't be!
}
```

**Comment by jgiacomini** [comment]
I think the methods must be suffixed by Async because they return a Task.

"ShowAsync"

**Comment by jamesmontemagno** [comment]
We aren't adding any user interface to this library, only core platform APIs. Forms includes this out of the box and ACR.Dialogs is a good option for this.
