### ISSUE TITLE
SecureStorage - Bring SecAccessible concept to all platforms

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/Essentials#221]
On iOS, we want to have support for surfacting the SecAccessible property on the SecRecord, this is important to control how the data is stored, and to support secrets being backed up when the user has encrypted volumes:

https://developer.xamarin.com/api/type/Security.SecAccessible/

**Comment by Redth** [comment]
We now have a platform specific API for this for iOS, but we should consider how we might expose this functionality in an abstract way and how that would look implementing it on other platforms.  Changing the issue title to reflect the refined goal here.

**Comment by jamesmontemagno** [comment]
I am not sure if this actually is something attainable at all or really needs to be part of the API. Since the concepts don't exist in the other platforms we would be inventing our own mechanism and I don't think that we are in the business to do this.

**Comment by jamesmontemagno** [comment]
I think this is safe to close.

**Comment by newky2k** [comment]
Closing
