### ISSUE TITLE
Email on iOS is not correct

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Essentials#224]
### Description

Sending an email on a device that does not have an email account set up fails. On my device, I am using Outlook and not the default mail client.

This means that `MFMailComposeViewController.CanSendMail` will return false. But in actual fact, this is not what I am expecting as a developer. We need to review the logic that determines whether or not an email can be sent.

### Expected Behavior

The default email client opens - if this is something that exists on iOS.

### Actual Behavior

Throws a `FeatureNotSupportedException` exception if I am not logged into the mail app.

**Comment by jamesmontemagno** [comment]
I am thinking maybe other apps implement:

```
let email = "foo@bar.com"
if let url = URL(string: "mailto:\(email)") {
    UIApplication.shared.open(url)
}
```

Flow would be... 
* 1 see if we can send mail in mail app... if so awesome
* Else see if mailto: works for uri
* else exception
