### ISSUE TITLE
Open Application Settings

### ISSUE THREAD

**Issue by yuv4ik** [xamarin/Essentials#231]
### Description
API that will expose a simple method to take the user to application settings.

### Example
`Xamarin.Essentials.ApplicationSettings.Open();`

<img src="https://user-images.githubusercontent.com/4107020/39725758-892e07fa-5255-11e8-984d-c88f6117dc55.png" width="300" /><img src="https://user-images.githubusercontent.com/4107020/39725990-41c3fa90-5256-11e8-91d3-b997d20cbbc9.png" width="300" />

### Notes
Not sure about the name.
A very simple implementation for iOS and Android can be found [here](https://gist.github.com/yuv4ik/c94f971fb0f7cd2ae86ac571296fd2fb).

**Comment by prashantvc** [comment]
Xamarin.Essentials provides the unified APIs that work on iOS, Android, and **UWP**. 

At the moment UWP does not provide common settings page/pane for apps [[see](https://docs.microsoft.com/en-us/uwp/api/windows.ui.applicationsettings.settingspane)], and makes the proposed APIs inconstant across the platforms.  I propose to close this issue

Any thoughts? @jamesmontemagno @mattleibow

**Comment by jamesmontemagno** [comment]
My thought would be more under AppInfo....

AppInfo.OpenSettings();
