### ISSUE TITLE
Additional Features

### ISSUE THREAD

**Issue by craylward** [xamarin/Essentials#235]
Are any of these on the roadmap?

Local Notifications: https://github.com/edsnider/LocalNotificationsPlugin

Platform Locale Info: 
Java.Util.Locale.Default.ToString();
NSLocale.PreferredLanguages.FirstOrDefault();

Main Thread Detection:
Looper.MyLooper == MainLooper
NSThread.Current.IsMainThread

Phone Call Capable:
Application.Context.PackageManager.HasSystemFeature(PackageManager.FeatureTelephony);
UIApplication.SharedApplication.CanOpenUrl(new NSUrl("tel://"));

BLE Capable:
Application.Context.PackageManager.HasSystemFeature(PackageManager.FeatureBluetoothLe);
(new CBCentralManager()).State != CBCentralManagerState.Unsupported;

**Comment by mattleibow** [comment]
Is there a reason you closed this? This looks like a valid request?

**Comment by craylward** [comment]
Thought about it more and decided against making requests like this as it is explicitly noted in the docs that plugins offer extensibility beyond the Xamarin Essentials. I'll re-open but understand if requests for additional APIs are inappropriate for the Xamarin Essentials issues list.

**Comment by mattleibow** [comment]
Requests for more features is fine. We just mean that we may not add it. We are trying to make sure that all the features work in all places, the plugins have the ability to specialize. 
We are hoping to be able to replace plugins for many of the common use cases, but if we get to a API that we feel doesn't fit in with the overall design, we will leave it out - and you can fall back to the plugins.

**Comment by jamesmontemagno** [comment]
Could you actually open 1 proposal per issue :) In each of them can you outline the use case, how you would use it, and the expected API.
