### ISSUE TITLE
Add Current Culture APIs

### ISSUE THREAD

**Issue by craylward** [xamarin/Essentials#239]
Use Case: Localization in Xamarin Forms projects

In Xamarin Forms projects, in order to obtain the current language of the phone for localizing content, we need access to the platform specific APIs.

Android: Java.Util.Locale.Default.ToString();
iOS: NSLocale.PreferredLanguages.FirstOrDefault();

//Motz Update

API overview:

```csharp
CultureInfo Culture.Current { get; } //gets the current platform UI culture
void Culture.SetLocale(CultureInfo cultureInfo) // sets the current platform culture
```
^ This follows docs outlined: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/text?tabs=vswin

**Comment by jamesmontemagno** [comment]
For reference: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/text?tabs=vswin

**Comment by danielkatz** [comment]
To support Hebrew ICU's "iw" should be remapped to .NET's "he", and subsequently "iw-IL" to "he-IL".
Please see [comment](https://github.com/xamarin/Essentials/pull/336/files#r198381637), [ICU](http://userguide.icu-project.org/locale#TOC-Canonicalization).

**Comment by jamesmontemagno** [comment]
After examining this API we have come to the conclusion that it is not a good fit for Essentials as it can not be properly abstracted across each platform. Documentation has this in place today to outline how to do this via platform specific code.
