### ISSUE TITLE
Add Main Thread Detection

### ISSUE THREAD

**Issue by craylward** [xamarin/Essentials#240]
Use Case: Obtaining the main thread for Xamarin Forms UI navigation from a method that may or may not be running in the background thread.

Part of: Platform

API:
```csharp
- bool IsMainThread { get; }
```

```
void NavigationMethod()
{
   if (Platform.IsMainThread)
   {
      Navigate();
   }
   else
   {
      Device.BeginInvokeOnMainThread(Navigate());
   }
}
```

Android: Looper.MyLooper == MainLooper
iOS: NSThread.Current.IsMainThread

**Comment by jamesmontemagno** [comment]
Yes, I like this! We actually have:

```
Platform.BeginInvokeOnMainThread(Navigate);
```

https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Platform/Platform.shared.cs#L8

This API should live inside of "Platform" and simply be 
```csharp
bool IsMainThread { get; }
```
This naming will match iOS which is good stuff.
