### ISSUE TITLE
Add Phone Call Capable API

### ISSUE THREAD

**Issue by craylward** [xamarin/Essentials#241]
Use Case: Detecting if a Xamarin Forms app is installed on a phone call capable device for determining how to show phone number links in UI.

Android: Application.Context.PackageManager.HasSystemFeature(PackageManager.FeatureTelephony);
iOS: UIApplication.SharedApplication.CanOpenUrl(new NSUrl("tel://"));

**Comment by jamesmontemagno** [comment]
Discussion for this is here: https://github.com/xamarin/Essentials/issues/77
