### ISSUE TITLE
Proposal for an Orientation Sensor

### ISSUE THREAD

**Issue by charlespetzold** [xamarin/Essentials#245]
An orientation sensor combines data from the accelerometer and magnetometer to provide a complete orientation of the device in 3D space. This information is vital for VR and AR applications. One common usage is a "night sky" astronomy program.

On iOS, this information is available from the Device Motion subset of the `CMMotionManager` API.

On Android, it's the `SensorType.RotationVector`  subset of the `SensorManager` API.

On UWP, it's the `OrientationSensor` class.

I think `OrientationSensor` is probably the best name for the class in Xamarin.Essentials, and distinguishes it from an `Orientation` API that might only provide portrait and landscape orientation.

A description of an orientation in 3D space is sometimes given in Euler angles; in roll, pitch, and yaw; or as a 3D rotation matrix. However, all three platforms provide a quaternion, and this is probably the simplest for the Xamarin.Essentials API. (`System.Numerics` includes a `Quaternion` type that can be used for this.) 

In fact, it is extremely easy to create `OrientationSensor` classes using the `Accelerometer` classes as a guide. (In fact, I've already done it.) Rather than passing three numbers to the `shared` partial class, you pass four, and then set an `Orientation` property of type `Quaternion`.

From what I can determine, the three platforms are consistent in the relationship of the quaternion to the orientation of the device (as long as you hold a UWP tablet in portrait mode). So in that sense, it's simpler than the `Accelerometer`!

Although the quaternion might be frightful to some people, it's convertible into other types. For example, the `System.Numerics.Matrix4x4` class has a `CreateFromQuaternion` method. Plus, we can write documentation that describe how to use it. (I wrote several orientation-sensor samples for _MSDN Magazine_ several years ago, and I'd love to port them to Forms + Essentials.)

**Comment by mattleibow** [comment]
This sounds like a nice API, and I feel a game coming on...

**Comment by charlespetzold** [comment]
Let me know if you want a PR with the implementation!

**Comment by mattleibow** [comment]
Create a PR and we will start commenting!
