### ISSUE TITLE
Add Cookie API

### ISSUE THREAD

**Issue by craylward** [xamarin/Essentials#248]
Use Case: Clear browsing data in Xamarin Forms WebViews to force a refresh of web content after first load.  Would also be nice to have Cookie apis available across platforms

// updated by JM

Integration point: Cookies

API:
```csharp
- string Get(string uri);
- bool HasCookies { get; }
-  void Set(string uri, string value);
- void RemoveAll();
- void Remove(string uri);
- bool Accept { get; set; } 
```

Documentation:
* iOS: https://developer.apple.com/documentation/foundation/nshttpcookiestorage
* Android: https://developer.android.com/reference/android/webkit/CookieManager.html (ensure on API 21+ we use new APIs)
* UWP: https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpcookiemanager

**Comment by Redth** [comment]
What would `Accept` do exactly in this case?

**Comment by jamesmontemagno** [comment]
Gets/Sets whether the application's WebView instances should send and accept cookies.

**Comment by Redth** [comment]
It didn't look like we could control this on every platform? 

I think one other area of confusion could also be how this fits/ties into SFSafariViewController and CustomTabs? Do the operations all work for those cases? I thought the point of using the native browser was that cookies for things like auth are shared?  It might be confusing if it's in the Browser API.... Just tossing out some thoughts!

**Comment by jamesmontemagno** [comment]
So i am pretty sure it would only be fore embedded webviews.... me thinks.... and not the native browsers.

I was thinking of a new class called "Cookies"

Seems like each have implementation pionts from what I see.

**Comment by Redth** [comment]
Yeah let's just keep it out of Browser then to avoid confusion :)

I missed a UWP implementation for being able to accept/reject cookies in a web view, but just wanted to check

LGTM

**Comment by jamesmontemagno** [comment]
yeah.... hmmm i think UWP may not have it... hmmmm we could leave that out or just document it?

**Comment by Redth** [comment]
I'd say leave it out. I can't imagine that many use cases for it where at the very least remove all would not be good enough to accomplish having no cookies (eg call that when the view disappears)

**Comment by Redth** [comment]
I am not convinced this is a good fit for Essentials.  Given that `SFSafariViewController` and Custom Tabs are much more prevalent now, and we can't control cookies in those, I fear this will simply add confusion.

I think this belongs in a separate community plugin.  It's not something I've ever seen anyone ask for outside of this issue.  For now I'm going to close this and suggest a community plugin (Plugin.WebViewCookies or something).
