### ISSUE TITLE
Proposal: NFC

### ISSUE THREAD

**Issue by mzhukovs** [xamarin/Essentials#252]
### Description

Xamarin.Forms API for NFC (so tapping into CoreNFC for iOS, Android Beam for Droid, and UWP not 100% sure but maybe something [like this](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Nfc)).

Would be sweet. Either way, thanks a ton for this. The package name says it all.

**Comment by gsmental** [comment]
nice idea

**Comment by mattleibow** [comment]
I started on something with #131 and this is a duplicate of #120
