### ISSUE TITLE
Failing to install on the Android Project

### ISSUE THREAD

**Issue by IeuanWalker** [xamarin/Essentials#255]
### Description
Installing the package into xamarin.forms project fails for the android project. Installs fine for the shared and iOS projects. 
Errer message -

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to add reference. The package 'Xamarin.Essentials' tried to add a framework reference to 'System.Numerics' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
This collection is read-only.			0	

### Steps to Reproduce

1. Install nuget on all projects
2. Successed on shared and iOS
3. Fails for android

### Basic Information

- Version with issue: 0.6.0-preview
- IDE: VS 2017

**Comment by mattleibow** [comment]
@redth I think we can just add the numerics nuget to all the platforms. It should not break anything.

**Comment by IeuanWalker** [comment]
@jamesmontemagno your right this is quite an old but on going project, i just spent the last hour or 2 upgrading xamarin.forms NuGet from version 2.5+ to version 3.0 and it has seemed to have fixed the issue :D

**Comment by EmreB99** [comment]
This issue is still going on.


> **Steps to Reproduce**
> 1. Install nuget on all projects
> 2. Successed on shared and iOS
> 3. Fails for android

Exactly as @IeuanWalker says.

Now, here is the strange thing:
Package wont even be tried to get installed at Android project as this screenshot shows: https://i.ibb.co/S379fhs/SS1.png

And heres the error I get after installation: https://i.ibb.co/c6ZVzvx/SS2.png

**Comment by jamesmontemagno** [comment]
@EmreB99  see: https://docs.microsoft.com/en-us/xamarin/essentials/troubleshooting?context=xamarin/xamarin-forms very easy to fix. Simply install the dependencies first.

**Comment by Kylar182** [comment]
I'm having this issue on brand new projects, old projects, any and all projects. If an out of the box blank project has this error I'm not sure what I'm supposed to do?

**Comment by jamesmontemagno** [comment]
can you post some logs or images of what you are seeing?
