### ISSUE TITLE
Xamarin forms iOS PhoneDialer is not woking throwing error

### ISSUE THREAD

**Issue by jitendrajadav** [xamarin/Essentials#257]
Bug report best practices: [Submitting Issues](SUBMITTING-ISSUES.md)

### Description
Xamarin forms iOS PhoneDialer is not woking throwing error
please find below:
{Xamarin.Essentials.FeatureNotSupportedException: Specified method is not supported.
  at Xamarin.Essentials.PhoneDialer.ValidateOpen (System.String number) [0x0001f] in <717f96720e9544d29cd74351077724c5>:0 
  at Xamarin.Essentials.PhoneDialer.PlatformOpen (System.String number) [0x00000] in <717f96720e9544d29cd74351077724c5>:0 
  at Xamarin.Essentials.PhoneDialer.Open (System.String number) [0x00000] in <717f96720e9544d29cd74351077724c5>:0 
  at KegID.ViewModel.PartnerInfoViewModel+<PlacePhoneCallAsync>d__80.MoveNext () [0x000bd] in C:\Project\...\ViewModel\Dashboard\InfoViewModel.cs:523 }
### Steps to Reproduce

1. Create simple Xamarin forms app implement PhoneDialer works in android but not in iOS
2. 
3. 

### Expected Behavior

It should show PhoneDialer 
### Actual Behavior
Throwing error
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by mattleibow** [comment]
This may because the NuGet is not installed in the iOS project. Can you confirm this?

**Comment by jamesmontemagno** [comment]
Additionally, please fill in all basic information for us in the Issue.

I assume you are trying on a Simulator which I don't believe supports the dialer.

**Comment by jitendrajadav** [comment]
Hi @mattleibow and @jamesmontemagno NuGet is installed and I am checking in iPhone 6 not in simulator.

please check below info:
Microsoft Visual Studio Professional 2017 
Version 15.7.1
VisualStudio.15.Release/15.7.1+27703.2000
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Professional

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40501.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.0.40502.0
Azure Functions and Web Jobs Tools

C# Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.5.2.2566
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.7
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9
Visual C++ for Linux Development

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 16ecf5a30ad868d183c58e4a71a71c23d4ed3ba9.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27703.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

Xamarin   4.10.0.442 (396b18cef)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.264 (fc37cd02e)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.0.19 (HEAD/342b2ce96)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.10.1.177 (7e782c1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jamesmontemagno** [comment]
what number are you putting in? works on my iphone 6 just fine with my phone number

**Comment by jamesmontemagno** [comment]
Specifically this code gets called to validate.

https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/PhoneDialer/PhoneDialer.ios.cs#L12

**Comment by jitendrajadav** [comment]
Hi @jamesmontemagno  I am using this number to make call it won't call  000-867-5309..

**Comment by jamesmontemagno** [comment]
have you tried: 0008675309

I use this to clean phone numbers: https://github.com/xamarinhq/app-myshoppe/blob/c211601734245f75e3f764322f5ad0532e66541e/MyShop/Helpers/Utils.cs

**Comment by jamesmontemagno** [comment]
I am unable to reproduce this at all. Are you sure that the nuget got installed correctly?

**Comment by Indiandotnet** [comment]
Hi,
I know this issue closed but unfortunately, I am getting the same issue.
Although, same code is working fine with Android.  I tried different emulator version. Just for your reference I am using VS 2019 (16.6.0) , Xamarin Existential 1.5.3.2

Below is the error detail

	ex	{Xamarin.Essentials.FeatureNotSupportedException: Specified method is not supported.
  at Xamarin.Essentials.PhoneDialer.ValidateOpen (System.String number) [0x0001a] in d:\a\1\s\Xamarin.Essentials\PhoneDialer\PhoneDialer.shared.cs:13 
  at Xamarin.Essentials.PhoneDialer.PlatformOpen (System.String number) [0x00000] in d:\a\1\s\Xamarin.Essentials\PhoneDialer\PhoneDialer.ios.cs:16 
  at Xamarin.Essentials.PhoneDialer.Open (System.String number) [0x00000] in d:\a\1\s\Xamarin.Essentials\PhoneDialer\PhoneDialer.shared.cs:17

**Comment by xeckuc** [comment]
> Hi,
> I know this issue closed but unfortunately, I am getting the same issue.
> Although, same code is working fine with Android. I tried different emulator version. Just for your reference I am using VS 2019 (16.6.0) , Xamarin Existential 1.5.3.2
> 
> Below is the error detail
> 
> ```
> ex	{Xamarin.Essentials.FeatureNotSupportedException: Specified method is not supported.
> ```
> 
> at Xamarin.Essentials.PhoneDialer.ValidateOpen (System.String number) [0x0001a] in d:\a\1\s\Xamarin.Essentials\PhoneDialer\PhoneDialer.shared.cs:13
> at Xamarin.Essentials.PhoneDialer.PlatformOpen (System.String number) [0x00000] in d:\a\1\s\Xamarin.Essentials\PhoneDialer\PhoneDialer.ios.cs:16
> at Xamarin.Essentials.PhoneDialer.Open (System.String number) [0x00000] in d:\a\1\s\Xamarin.Essentials\PhoneDialer\PhoneDialer.shared.cs:17

I am having the same issue
Same library and VS2019 version.

**Comment by ShannonMcCoy** [comment]
> > Hi,
> > I know this issue closed but unfortunately, I am getting the same issue.
> > Although, same code is working fine with Android. I tried different emulator version. Just for your reference I am using VS 2019 (16.6.0) , Xamarin Existential 1.5.3.2
> > Below is the error detail
> > ```
> > ex	{Xamarin.Essentials.FeatureNotSupportedException: Specified method is not supported.
> > ```
> > 
> > 
> > at Xamarin.Essentials.PhoneDialer.ValidateOpen (System.String number) [0x0001a] in d:\a\1\s\Xamarin.Essentials\PhoneDialer\PhoneDialer.shared.cs:13
> > at Xamarin.Essentials.PhoneDialer.PlatformOpen (System.String number) [0x00000] in d:\a\1\s\Xamarin.Essentials\PhoneDialer\PhoneDialer.ios.cs:16
> > at Xamarin.Essentials.PhoneDialer.Open (System.String number) [0x00000] in d:\a\1\s\Xamarin.Essentials\PhoneDialer\PhoneDialer.shared.cs:17
> 
> I am having the same issue
> Same library and VS2019 version.

Same Issue here. Xamarin.Essentials 1.6.0. VS 2019 Enterprise 16.8.4  iPhone 12 iOS 14.3 Sim

**Comment by mattleibow** [comment]
I think you might need to add the queries things to manifests and plists now. I'm in bed atm so I'll have links tomorrow. But maybe check out the email/dialer since and there might be some links and sample code.

I know @jamesmontemagno wrote them.
