### ISSUE TITLE
Xamarin.Essentials.FileSystem.AppDataDirectory incorrect for IoS

### ISSUE THREAD

**Issue by solomonfried** [xamarin/Essentials#261]
Bug report best practices: [Submitting Issues](SUBMITTING-ISSUES.md)

### Description

Executing Xamarin.Essentials.FileSystem.AppDataDirectory for IoS returns 
/Users/[username]/Library/Developer/CoreSimulator/Devices/B4BE8F73-5219-4DF0-961C-5D2766DE081D/data/Containers/Data/Application/0EFE6CA5-5443-49F1-BD68-36F411308D98/Library

trying to open this directory (for SQLite) fails

The Xamarin documentation for accessing local file systems using Dependency Injection, recommended the following code ([https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/databases]) , which worked and resulted in the following path.

"/Users/[username]/Library/Developer/CoreSimulator/Devices/B4BE8F73-5219-4DF0-961C-5D2766DE081D/data/Containers/Data/Application/0EFE6CA5-5443-49F1-BD68-36F411308D98/Documents/../Library/Databases

This is the code from the Xamarin docs.

        public string GetLocalFileDirectory()
        {
            var docFolder = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
            var libFolder = Path.Combine(docFolder, "..", "Library", "Databases");

            if (!Directory.Exists(libFolder))
            {
                Directory.CreateDirectory(libFolder);
            }
            return libFolder;
        }

As an aside, for UWP and Android, the Xamarin.Essentials call returns the same path as the local call.
UWP = ApplicationData.Current.LocalFolder.Path
Android = Environment.GetFolderPath(Environment.SpecialFolder.Personal);

### Steps to Reproduce

1.  use  Xamarin.Essentials.FileSystem.AppDataDirectory to get a directory
2.  try to write to that directory

### Expected Behavior

write should succeed

### Actual Behavior

Write fails.

### Basic Information

- Version with issue: Latest Xamarin Code.
- Last known good version:
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  11.3  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by mattleibow** [comment]
I am unable to recreate this issue. I installed "sqlite-net-pcl" version "1.4.118 to test, and the operation succeeded:

```csharp
var databasePath = Path.Combine(FileSystem.AppDataDirectory, "people.db");
var db = new SQLiteConnection(databasePath);
db.Execute("CREATE TABLE test_table ( id INT PRIMARY KEY NOT NULL );");
var test_table = db.GetTableInfo("test_table");
```

That directory is pretty much the same - there is no requirement to be in the "Databases" folder.

Apple docs: https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW13

**Comment by solomonfried** [comment]
Thank you and my apologies for missing something obvious.
Since on the other 2 platforms, the directory names matched, my app worked because my subdirectory already existed. It only failed on IOS since the subdir had never been created.

Thanks for all your help.
