### ISSUE TITLE
Xamarin.Essentials.Platform does not contain Init() method

### ISSUE THREAD

**Issue by bndftw** [xamarin/Essentials#262]
Bug report best practices: [Submitting Issues](SUBMITTING-ISSUES.md)

### Steps to Reproduce

1. Added pre-release version 0.6.0 to Android, IOS, PCL project through NuGet package manager.
2. Navigating to MainActivity.cs in the Android project, and selecting the OnCreate method.
3. Typing Xamarin.Essentials.Platform. (and the intellisense completes only with BegininvokeOnMainThread and Equals, referenceEquals methods)

### Basic Information

- Version with issue:
- Last known good version: - 
- IDE: Visual Studio 15 Enterprise
- Platform Target Frameworks: 
  - iOS:  -
  - Android: 6.0
  - UWP:  none

### Screenshots

![kepernyofelvetel 12](https://user-images.githubusercontent.com/18361936/40226605-69e51c82-5a8c-11e8-905d-c44662e4c7b8.png)

![kepernyofelvetel 13](https://user-images.githubusercontent.com/18361936/40226606-6a04ce7e-5a8c-11e8-9e72-09878e683382.png)

Droid package list:
`  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="23.3.0" targetFramework="monoandroid60" />
  <package id="Xamarin.Android.Support.Design" version="23.3.0" targetFramework="monoandroid60" />
  <package id="Xamarin.Android.Support.v4" version="23.3.0" targetFramework="monoandroid60" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="23.3.0" targetFramework="monoandroid60" />
  <package id="Xamarin.Android.Support.v7.CardView" version="23.3.0" targetFramework="monoandroid60" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="23.3.0" targetFramework="monoandroid60" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="23.3.0" targetFramework="monoandroid60" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="23.3.0" targetFramework="monoandroid60" />
  <package id="Xamarin.Essentials" version="0.6.0-preview" targetFramework="monoandroid60" />
  <package id="Xamarin.Forms" version="2.3.0.107" targetFramework="monoandroid60" />
  <package id="Xamarin.Forms.Maps" version="2.3.0.49" targetFramework="monoandroid60" />
  <package id="Xamarin.GooglePlayServices.Base" version="29.0.0.1" targetFramework="monoandroid60" />
  <package id="Xamarin.GooglePlayServices.Basement" version="29.0.0.1" targetFramework="monoandroid60" />
  <package id="Xamarin.GooglePlayServices.Maps" version="29.0.0.1" targetFramework="monoandroid60" />`

**Comment by jamesmontemagno** [comment]
Ensure that the correct dll is getting included, it should be in the MonoAndroid71 folder.

You are building against MonoAndroid60, which is not compatible. You must be using support libraries 25.4.0.2+

You must 1:
* Set your Android Compile to Android 7.1+
* Update your Support Libraries to 25.4.0.2+
* Uninstall Essentials and re-add it as you are getting the netstandard version, not the android version.
