### ISSUE TITLE
Docs to Update for 0.7.0-preview

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#264]
These docs need to be updated or written for 0.7.0-preview 

* [ ] - Guidance on support packages - Setup.md
* [ ] -  *New* Orientation Sensor (Add to roots)
* [ ] - DateTime in Preferences -> Implementation details
* [ ] - *New* Platform APIs Docs (Add to roots)
* [ ] - Platform -> BeginInvokeOnMainThread
* [ ] - Platform -> IsMainThread

//This will continue to grow.

**Comment by charlespetzold** [comment]
The `Platform` class conflicts with the `Platform` property defined by the Xamarin.Forms `Element` class (the base class of `VisualElement`, `View`, and `Page`), which means that any use of `Platform` within one of these classes needs to be fully-qualified:

```
Xamarin.Essentials.Platform.BeginInvokeOnMainThread(() =>
{
    // Run code on main thread
});
```

**Comment by charlespetzold** [comment]
By "DateTime in Preferences -> Implementation details" I assume the implementation details involve the use of the `ToBinary` and `FromBinary` methods?

**Comment by charlespetzold** [comment]
`Platform` might be renamed `CurrentPlatform` to avoid the Forms conflict.
