### ISSUE TITLE
Proposal: Make the IsSupported public for phone dialer, email, SMS

### ISSUE THREAD

**Issue by renemaat** [xamarin/Essentials#266]
**Description**
Currently you can compose an email/sms or open the phone dialer but when the feature is not supported on the device you get an FeatureNotSupportedException. It would be nice if you can check beforehand if the feature is supported and disable/hide the UI if it isn't supported.

**API changes**
Make the IsSupported / IsComposeSupported public so that we can check if the feature is supported.

**Comment by jamesmontemagno** [comment]
Duplicate #77
