### ISSUE TITLE
iOS 9 support

### ISSUE THREAD

**Issue by ninaada** [xamarin/Essentials#269]
Bug report best practices: [Submitting Issues](SUBMITTING-ISSUES.md)

**Comment by thezik** [comment]
+1 for this. Leaving out iOS 9 means leaving out iPad 2 and iPad minis.
Also, for the sake of curiosity, which features are keeping you from giving iOS 9 support?
Maybe the Library may be used on iOS 9 unless some specific functionalities are used?

**Comment by OnShoreDev** [comment]
One feature does not work in iOS 9 is opening a browser with:
`Browser.OpenAsync(uri, launchMode); 

The app crashes.

**Comment by mattleibow** [comment]
@OnShoreDev DO you have a stack trace? Maybe we are using a method that does not exist.

**Comment by jamesmontemagno** [comment]
SFSafariViewController isn't supported on iOS 9 and you would want to use the External launch mode.

**Comment by OnShoreDev** [comment]
> @OnShoreDev DO you have a stack trace? Maybe we are using a method that does not exist.

**Code:** 
`Browser.OpenAsync(uri, launchMode);    //launchMode is external`

**Stack Trace**

> Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[.....Application openURL:options:completionHandler:]: unrecognized selector sent to instance 0x14dd5820
> Native stack trace:
> 	0   CoreFoundation                      0x24d1f933 <redacted> + 150
> 	1   libobjc.A.dylib                     0x244bae17 objc_exception_throw + 38
> 	2   CoreFoundation                      0x24d252b5 <redacted> + 0
> 	3   CoreFoundation                      0x24d22ee1 <redacted> + 700
> 	4   CoreFoundation                      0x24c4e238 _CF_forwarding_prep_0 + 24

**Comment by jamesmontemagno** [comment]
I put in a fix here on openasync, should be fixed up in next patch.

**Comment by OnShoreDev** [comment]
> I put in a fix here on openasync, should be fixed up in next patch.

Great. When is the next patch scheduled?
