### ISSUE TITLE
Error while installing from nuGet

### ISSUE THREAD

**Issue by ajithbabu** [xamarin/Essentials#273]
Hi,
I tried install from nuget but i received this error.
![image](https://user-images.githubusercontent.com/37439027/40719621-c70cc640-6431-11e8-89bb-bc228e1d27ea.png)
Have anyone faced the same and solved?
Thanks,
Ajith

**Comment by jamesmontemagno** [comment]
See: https://github.com/xamarin/Essentials/issues/255
