### ISSUE TITLE
Rejection to iOS App Store - Missing keys in info.plist for features I don't use

### ISSUE THREAD

**Issue by FrancoisM** [xamarin/Essentials#283]
I added Xamarin Essentials to my app. I only use the Email support.
However, I got a rejection email when submitting my app to iOS App Store about missing keys `NSCalendarUsageDecription` and `NSBluetoothPeripheralUsageDescription`.
I don't either calendar or bluetooth in my app.

**Comment by jamesmontemagno** [comment]
Are you using the Permissions Plugin?

We do not use any of those APIs in this library. See: https://github.com/jamesmontemagno/PermissionsPlugin#ios-specific

The other APIs are removed.

The workaround here is to just add those.

**Comment by FrancoisM** [comment]
Good catch.
I'll add these for the moment.

**Comment by Lelelo1** [comment]
Won't adding the permission mean it will be visible in app store?

Also it seem to be [fixed](https://github.com/jamesmontemagno/PermissionsPlugin/issues/159) in PermssionsPlugin. But I don't want to stop using whole Xamarin essentials just to get rid of the permission...?

**Comment by jamesmontemagno** [comment]
He had reported this in the wrong repo @Lelelo1 as he was using the PermissionsPlugin. When we added the permissions api to essentials this was taken into consideration and was never an issue.
