### ISSUE TITLE
Mocking Geolocation

### ISSUE THREAD

**Issue by KristofferBerge** [xamarin/Essentials#284]
Would be nice to be able to mock the calls to the Geolocation class. It's currently a static (sealed) class that does not implement any interface, so injecting my own mock version of the class where I use it doesn't seem to be possible without wrapping it in some other class.

**Comment by Krumelur** [comment]
Not having interfaces was a design decision.

You can read more about it in the readme of this repo at: https://github.com/xamarin/Essentials#where-are-the-interfaces

**Comment by jamesmontemagno** [comment]
Thanks @Krumelur for adding the link, and thanks Kristoffer for bringing up the question. We provide guidance there on how to do mocking if necessary for projects.
