### ISSUE TITLE
OpenMaps API

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#287]
Original Implementations: https://github.com/jamesmontemagno/LaunchMapsPlugin

OpenMaps would do just that... open the maps to a specific destination on the map and allow the developer to specify the direction type. 

## API:

```csharp
Task OpenMapsAsync(Location location, MapLaunchOptions options);
Task OpenMapsAsync(double latitude, double longitude, MapLaunchOptions options);
Task OpenMapsAsync(Placemark placemark, MapLaunchOptions options);
```

### Struct: MapLaunchOptions

```
public MapNavigation MapNavigation {get;set;}
public string Name { get; set; }
```

### Enums:

```csharp
enum MapNavigation
{
    Default,
    Driving,
    Walking
}
```

## Implementations
* iOS: MapItem has this built in
* Android: Launch Intents  to Google Maps else Default app
* UWP: bingmaps: launch uri for maps

**Comment by Mrnikbobjeff** [comment]
I would like to see MapNavigation extended by Location, so that one could possibly also only display the location which was specified instead of looking for a route.

**Comment by Mrnikbobjeff** [comment]
I took a look at your implementation @jamesmontemagno and you return a bool indicating success of the launch operation. As your api does not specify this I reckon we would throw an Exception when a Placemark is unresolvable? I would not like to see a silent failure on an api call.

**Comment by Mrnikbobjeff** [comment]
Also, this could partially benefit from the new Launcher API. On UWP this launches a bingmaps uri. Implementing this would simply be an argument conversion call to format the URI.

**Comment by Mrnikbobjeff** [comment]
I implemented this [here](https://github.com/xamarin/Essentials/pull/354). I tested it on all platforms, I only have to add unit tests and enter the doc info. the updated docs are already pushed, just not filled out yet.

**Comment by jrahma** [comment]
I have 0.9.1-preview installed but I can't get the Map nor OpenMap..

How can I get this function?

**Comment by jamesmontemagno** [comment]
@jrahma  see docs: https://docs.microsoft.com/en-us/xamarin/essentials/maps?context=xamarin%2Fios&tabs=ios

**Comment by jrahma** [comment]
yes solved. sorry.. ,my shared project did not update the xamarin essential while ios and android were updated. Thanks.
