### ISSUE TITLE
Platform conflicts with Platform in XF -> Rename to something else

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#291]
See: https://github.com/xamarin/Essentials/issues/264

We should rename to something else. CurrentPlatform perhaps?

We use this currently for ui thread updates and detection.

**Comment by mattleibow** [comment]
`CurrentPlatform` diverges a bit form the other APIs with a more "noun-based" naming method. Any ideas of better names?

**Comment by jamesmontemagno** [comment]
Yeah, I think something else for V1 would be needed. Not sure what though.

**Comment by Redth** [comment]
`Platform` isn't _just_ used for UI thready things currently, so I think if we name those API's to `MainLoop` we still need to come up with another name for things like Android's `Platform.Init(..)` and `Platform. OnRequestPermissionsResult(..)`.
