### ISSUE TITLE
Wrong API level in the docs (Typo)

### ISSUE THREAD

**Issue by xclud** [xamarin/Essentials#293]
### Description
In the documentation, API level must be 27 rather than 17 as the doc is talking about Android 8.1 and its corresponding API level. This seems to be a typo.

PS: I tried to upload an screenshot to help finding the typo by eye, but my desktop is restricted to some actions. I will upload an screenshot in a later comment.

### Steps to Reproduce

1. [Browse this link.](https://docs.microsoft.com/en-us/xamarin/essentials/get-started?context=xamarin%2Fxamarin-forms&tabs=windows%2Candroid)
2. Scroll down to section 5 under `Installation` heading.
3. Find the sentence `for compiling must be 8.1, corresponding to API level 17` in Android tab.

**Comment by xclud** [comment]
<img width="601" alt="capture" src="https://user-images.githubusercontent.com/12394889/41442160-1124bd94-704b-11e8-8f56-8691b3f60507.PNG">

**Comment by jamesmontemagno** [comment]
Thanks, we have a PR in for it.
