### ISSUE TITLE
Compass orientation

### ISSUE THREAD

**Issue by MKhairyDev** [xamarin/Essentials#298]
Bug report best practices: [Submitting Issues](SUBMITTING-ISSUES.md)

### Description
Compass degree is not correct in the horizontal direction.
### Steps to Reproduce

1. Listen to the ReadingChanged event.
2. get the north degree in both directions ( vertical, horizontal).

### Expected Behavior
compass degree is same in both directions.
### Actual Behavior
compass degree is not the same in both directions.
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  11.3.1
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:0.7.0.17-preview
- Affected Devices:

**Comment by jamesmontemagno** [comment]
I am unable to reproduce this on my end with: https://github.com/jamesmontemagno/app-compass

Ensure that your iOS and Android device are calibrated as often that sensor can get out of sync on Android. Some more info here; https://docs.microsoft.com/en-us/xamarin/essentials/compass?context=xamarin%2Fxamarin-forms&tabs=android#platform-implementation-specifics
