### ISSUE TITLE
[Question] Is there a reason why PRs for full features are not accepted?

### ISSUE THREAD

**Issue by AmrAlSayed0** [xamarin/Essentials#300]
Title<br/><br/>
I didn't find an answer anywhere on this repo.

**Comment by Redth** [comment]
We really want to make sure we get Xamarin.Essentials right.  Part of that is having discussion around what features make sense to include in the project, and after we agree that a feature should become part of it, more discussion around what the API for that feature should look like.

We're happy to consider ideas for new features, and we would encourage you to submit issues with feature proposals, but we don't want anyone spending their time writing PR's before we've all agreed upon what the implementation of a feature looks like.

Hopefully that gives some more insight into how the process looks for adding new features.
