### ISSUE TITLE
More Device Info

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#301]
Hi,

Please add the following to the Device Info:

Device IMEI
Device Serial
Device Language

**Comment by Redth** [comment]
I don't think we'll be able to add support for IMEI and/or Serial.  iOS already restricts getting these and Android is trending this way.  It might be better to have a discussion around a cross platform API for obtaining a unique ID using the recommended API's from each platform.

**Comment by jamesmontemagno** [comment]
I agree here on these as many Android manufacturers don't even set these properly. We do have an open issue for device locale/language already. So will close for now.
