### ISSUE TITLE
Device IP Address and SIM Number

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#302]
Hi,

Please add the following to the Essentials connectivity:

Device IP Address
Device SIM numbers
Device Carrier / Network / Provider.

**Comment by Redth** [comment]
1. Device IP is tricky especially or at least on Android as @jamesmontemagno can attest to based on his experience. Devices have multiple network interfaces these days, and we'd need to expose an API which deals with that.

2. This isn't allowed on iOS.  I think it's still possible on Android and maybe UWP, but I wouldn't be surprised if that is _fixed_ at some point.  This really boils down to bit of a user privacy concern.

3. This one is probably quite possible :)

Honestly I think you'd need to provide a compelling case to use IP address and SIM numbers for us to prioritize adding this.

**Comment by jrahma** [comment]
using IP and SIM is for auditing especially with government or semi government apps (which is my case)... it's used also for authentication to show the current device sim number before sending activation pin.

**Comment by Redth** [comment]
Most apps now ask the user to enter a phone number for some sort of activation code, or better yet, have some sort of proper 2FA setup where this is all part of the flow and the back end can send the code as part of the auth flow.

**Comment by Redth** [comment]
We're not going to add IP / SIM number API's.

We could consider the Carrier/Network/Provider if someone would like to open a new issue with some suggested API specs.

**Comment by Incentnet** [comment]
Redth,
I just saw this post and the timing is interesting as my company is building a Fintech solution right now using Xamarin Forms and was just working on this.  As a Fintech solution it's very important that we collect IP information.  Specifically, in the event that there is fraud and/or hacking involved and an account was compromised we need to be able to provide data back to the financial institution which can be passed along to the authorities to help track down the fraudster.  

The solution we have built does use standard multi factor authentication as was suggested but the need is more for tracking purposes.  In addition, often there are requirements to block certain countries from accessing the solution.  This can be done by IP.  Please consider reopening this and revisiting the decision not to add this to the roadmap.

**Comment by Redth** [comment]
You should still be able to use `System.Net.NetworkInformation` as a cross platform API to get information about network interfaces and their IP addresses.

Sorry, but at this point we're not going to add anything specifically related to these API's.

**Comment by Incentnet** [comment]
Perfect! Honestly, I had not done much research on the issue and I ran across this post.  Sounds like that will provide us with what we need.  I appreciate the response!

**Comment by dinobu** [comment]
We simply have requirements to show the IP of connected network in app settings area.  Customers need this information for they day to day business, that is enough compelling

**Comment by jrahma** [comment]
> Carrier/Network/Provider

Opened a new case #865 for Carrier / Network / Provider

Thanks,
Jassim

**Comment by smhasan** [comment]
> You should still be able to use `System.Net.NetworkInformation` as a cross platform API to get information about network interfaces and their IP addresses.
> 
> Sorry, but at this point we're not going to add anything specifically related to these API's.

I fixed a big issue with this `System.Net.NetworkInformation` 
Thanks
