### ISSUE TITLE
Read Volume Level

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#303]
Hi,

Please add an option in Xamarin Essentials to adjust the device volume

Thanks,
Jassim

> VS bug [#735688](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735688)

**Comment by Mrnikbobjeff** [comment]
I do not think that the api is similar enough to warant inclusion in the Essentials Project.
Android has Android.Media.AudioManager.AdjustVolume(..), which takes a stream for which to change the volume (music, notifications, alarm etc.)
iOS only has one stream as far as I know.
On UWP I am clueless, though a brief google search revealed that Volume can not be changed globally but only for application sounds (I could be very wrong here). 
At glance though this seems too diverse for this Project.

**Comment by jrahma** [comment]
@Mrnikbobjeff well, this applies to Vibrate I guess if I am going to agree with you but I don't because sound is a capability too and we are not doing any media here but just checking if sound is on or off and also turning it on and off.

**Comment by Mrnikbobjeff** [comment]
@jrahma Adjusting volume and getting volume/silent mode state are two different things. Consider adjusting the issue to include the API surface which is desired, that would clarify many things left undefined in your original issue.

**Comment by Redth** [comment]
Yeah we might be able to inquire about the current set volume, but I don't believe adjusting the volume is something that's practical to do in a cross platform way at this point due to inconsistencies (as a user, I don't want most apps controlling my volume which is why I suspect iOS does not allow this).

**Comment by jrahma** [comment]
detecting the volume through Xamarin Essentials is also fine.

**Comment by Redth** [comment]
Would love for someone to do the research on how this works across the various platforms (consistencies/differences) and to propose an API for retrieving this.

**Comment by pictos** [comment]
In android, we can adjust the volume and touch mode. You can view the documents [here] (https://developer.xamarin.com/api/type/Android.Media.AudioManager/)

> var test = (AudioManager) MainActivity.GetSystemService (Context.AudioService);
>
> test.RingerMode = RingerMode.Silent;

In iOS and UWP I found ways to change media volume. There is a CrossMediaPlugin, we can use it as an example: https://blog.xamarin.com/play-audio-and-video-with-the-mediamanager-plugin-for-xamarin/

**Comment by Redth** [comment]
I think we could consider adding:

```csharp
partial class DeviceInfo {
  double CurrentVolumePercent { get; }
}
```

I'd like to see evidence that this can actually be done on iOS, Android, and UWP before we go ahead and mark it ready for implementation.

**Comment by pictos** [comment]
@Redth , I'm confused, is the API is to control the volume of the device or volume for the application?

**Comment by Redth** [comment]
My assumption was for the device (not sure the platforms all support application volume.

**Comment by mattleibow** [comment]
Just thinking about this API... changing the volume. Why would a developer want to do this? This is a very personal thing for an app to do. I am doing something and then the app decides it is time to go loud? Or softer? And, how hard is it to hit the volume rocker?

I think the needs a specific use case as I personally hate it when some app touches my device volume. And, my android phone has 3 volumes - music, alert, phone. What will it change?

This needs a specific use case.

**Comment by Redth** [comment]
Right I don't think we'd ever allow _setting_ of the volume.    I think there _might_ be a use case for reading the current volume.

**Comment by mattleibow** [comment]
And maybe some event for volume changed. An app may want to display some volume overlay when it is changed - sort of like when you change the volume on iOS when playing a movie.

**Comment by Mrnikbobjeff** [comment]
[UWP](https://docs.microsoft.com/en-us/windows/desktop/api/endpointvolume/nn-endpointvolume-iaudioendpointvolume) Integration point
[iOS ](https://developer.xamarin.com/api/type/MonoTouch.AVFoundation.AVAudioSession/) Integration point
[Android](https://developer.xamarin.com/api/type/Android.Media.AudioManager/) Integration point

IAudioEndpointVolume is supported on uwp, though I thoroughly dislike com interop.

My api proposal would be:

public static class Volume
{
  float MusicVolume {get; }
}
where MusicVolume ranges from 0 to 1 on all platforms.

**Comment by Redth** [comment]
The thing that still bugs me about this implementation is Android and the wonky way it deals with volume.

Is the music volume generally what controls playing sounds in apps? Is there a way on Android to play sounds that aren't controlled by the music volume?

**Comment by pictos** [comment]
@Redth , in android we have two volume types, the Media, for streaming and Alarms for ringtone. Below are some code snippets to deal with.

```csharp
am = (AudioManager)CurrentActivity.GetSystemService(Context.AudioService);
am.RingerMode = RingerMode.Vibrate;
//  RingerMode.Vibrate ; RingerMode.Silent ; RingerMode.Normal
```
or you can more general
```csharp
  static void PlataformIncreaseVolume(int volume)
        {
            am = (AudioManager)CurrentActivity.GetSystemService(Context.AudioService);
            am.SetStreamVolume(Stream.Alarm, volume, VolumeNotificationFlags.ShowUi);          
        }
```
In ` am.SetStreamVolume(...)` you use the [Stream Enum](https://developer.xamarin.com/api/type/Android.Media.Stream/) to specify the media type.

Reference : https://developer.xamarin.com/api/member/Android.Media.AudioManager.SetStreamVolume/p/Android.Media.Stream/System.Int32/Android.Media.VolumeNotificationFlags/

**Comment by Redth** [comment]
Yep I definitely understand there are multiple volumes on Android, I guess this goes back to trying to decide what the expected use cases of this API are.

Why would I want to know the volume level in my app?  To detect if it's really low and prompt the user to turn it up if the app needs to play back something? 

From an android perspective which stream types would I be interested in the volume for?

**Comment by Redth** [comment]
So do most ads, and apps generally play media that is controlled by the music stream's volume?

**Comment by Redth** [comment]
I'm just trying to determine which stream(s) developers consuming this API are truly going to be interested in.  Is Music enough? 

You mentioned Ads might want to use this, which is why I ask, does most audio from Ads for example play over the music stream?  I'm trying to get a sense of what are the most common types of audio played, and which stream are they usually played over?

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.

**Comment by Mrnikbobjeff** [comment]
@Redth Virtually all audio is played over the Music stream - I have not encountered a cross platform media app which used any other stream than Music. I think this still fits the 80/20 rule you have for Essentials. If you specifically want to play something over a stream only available on one platform you should do so yourself.  Music volume is so essential that it really should be the only stream we play attention to.

**Comment by jfversluis** [comment]
This won't be happening for Xamarin.Essentials anymore. If this is still of interest to you, please open something on the .NET MAUI repository. Thanks!
