### ISSUE TITLE
init() does not exsits, monodroid 71

### ISSUE THREAD

**Issue by MathieuVedana** [xamarin/Essentials#305]
Bug report best practices: [Submitting Issues](SUBMITTING-ISSUES.md)

### Description
Hello, I have a fresh installation of Essentials that do not works fine in my android project.
As #262 , init() does not exsits but I have a different configuration than @bndftw.

Can you help me to resolve the issue?

Thank you.

### Steps to Reproduce

1. Basic code from guideline:
` protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            // Set our view from the "main" layout resourceC:\GIT\Vedana\VHealth\MyPedometer\MyPedometer\MyPedometer\MyPedometer.Android\Properties\AndroidManifest.xml
            SetContentView(Resource.Layout.Main);
            //Nécessaire pour initialiser Xamarin.essentials
            Xamarin.Essentials.Platform.Init(this, savedInstanceState);`

### Expected Behavior
Platform contain Init()
### Actual Behavior
Platform does not contain Init()
### Basic Information

- Version with issue: 0.7.0.17-preview
- Last known good version: NA
- IDE: VS2017Pro
- Platform Target Frameworks: 
  - Android: 8.1 
 - monoandroid71
- NuGet : System.Numerics.Vectors.4.5.0 and Xamarin.Essentials 0.7.0.17-preview

**Comment by MathieuVedana** [comment]
idem with `OnRequestPermissionsResult()` method.

**Comment by jamesmontemagno** [comment]
Please see the getting started:
https://docs.microsoft.com/en-us/xamarin/essentials/get-started?tabs=windows%2Candroid

 Android version for compiling must be 8.1, corresponding to API level 27. (In Visual Studio, these two versions are set in the Project Properties dialog for the Android project, in the Android Manifest tab. In Visual Studio for Mac, they're set in the Project Options dialog for the Android project, in the Android Application tab.)
