### ISSUE TITLE
Location.CalculateDistance returns wrong results

### ISSUE THREAD

**Issue by ncarandini** [xamarin/Essentials#306]
### Description
The Location.CalculateDistance(Location locationStart, Location locationEnd, DistanceUnits units) return wrong results.

### Steps to Reproduce

1. Create a Xamarin.Forms project and add the Xamarin.Essentials NuGet package (actually 0.6.0-preview)
2. On MainPage.xaml.cs add this code:
```
Location CenterOfRome = new Location(41.891930, 12.511330);
Location NearCenterOfRome = new Location(41.901930, 12.501330);
double knownDistances = 1.386; // the known distance
var distance = Location.CalculateDistance(CenterOfRome, NearCenterOfRome, DistanceUnits.Kilometers);
var deltaDistance = Math.Abs(distance - knownDistances);
```

3. Set a breakpoint on first row and debug the app and take note of the `distance` and `deltaDistance` values.

### Expected Behavior
Distance (km): 1,38610772363843
Delta (km): 0,000107723638428814

### Actual Behavior
Distance (km): 4329,9338611948
Delta (km): 4328,5478611948

### Basic Information

- Version with issue: 0.6.0-preview
- Last known good version: none
- Platform Target Frameworks: All

**Comment by thaihuydang** [comment]
right now, it's still wrong
version: 1.0.1

**Comment by jamesmontemagno** [comment]
@thaihuydang what call are you making?

**Comment by thaihuydang** [comment]
![distance](https://user-images.githubusercontent.com/17990989/52140554-f7786580-2607-11e9-8bd8-c660da3563f6.JPG)
Hi James,
I'm calculating distance around Costco:
Postion1=(37.720134, -122.182552)
Postion2=(37.720266, -122.181969)
distance result=6702.86109710155 miles

**Comment by jamesmontemagno** [comment]
@mattleibow can you look at this asap.

**Comment by jamesmontemagno** [comment]
I could not reproduce this @thaihuydang I even added a test and it is working great for me with your numbers.

**Comment by Gishkori** [comment]
Gishhhhhhhhh
