### ISSUE TITLE
No Exception on Android if Activity is null (due to init not being set)

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#309]
Original Issue: https://github.com/MicrosoftDocs/xamarin-docs/issues/421

### Description

If we try to use an API where the Activity (not context) is required then we get no notification or error that it was null and we should set the Init and track it correctly.

### Steps to Reproduce

1. Install without adding Android Init
2. Call Screenlock functionality
3. Nothing happens

### Expected Behavior

Exception should occure

### Actual Behavior

Nothing happens

**Comment by ydniw** [comment]
Hi, I've upgraded to 0.7.0.17-preview and lost the init on Xamarin.Essentials.Platform.Init, was working fine on previous version.

<img width="704" alt="screen shot 2018-06-23 at 17 17 42" src="https://user-images.githubusercontent.com/19725594/41808555-8d44b194-7709-11e8-98b1-18cb43d12fc5.png">

**Comment by mattleibow** [comment]
Make sure you updated the Android project as well

**Comment by jamesmontemagno** [comment]
@ydniw this most likely means that you are not compiling against Android 8.1. You will want to change that and then uninstall the nuget and re-add it. See: https://blog.xamarin.com/android-apps-google-play-target-api-level-requirements/
