### ISSUE TITLE
An error occurred while installing the package System.Runtime System.Runtime' which was not found in the GAC

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Essentials#312]
I tried to install the package and got this error.
I have iOS and Android projects and library for .NET Standard.
v. 0.7.0.17-preview

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to add reference. The package 'Xamarin.Essentials' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Reference unavailable.			0
```

**Comment by jamesmontemagno** [comment]
Which project is it having issues installing in? Can you try adding to iOS first and then do Android and then do .NET Standard.

**Comment by jamesmontemagno** [comment]
Additionally, can you provide information about what version of Visual Studio you currently are using.

**Comment by jamesmontemagno** [comment]
I can identify that the reference is for some reason in the nuget although I thought we had fixed that up. Will be addressing, but impacts only some machines and not sure why that is to be honest. You can edit the csproj and add it first on Android which should allow the install as a workaround, but would love to know more about your setup and workloads you have installed in Visual Studio.

**Comment by KSemenenko** [comment]
I use Visual Studio 2017 Enterprise 15.7.4

I try to install separately:
Сommon lib .net Standard 2.0 - library was installed immediately.
iOS - also installed.
Android - I got the error Error "System.Runtime System.Runtime' which was not found in the GAC"

At first I had a problem with installing Xamarin.Android.Support.CustomTab and I installed it separately.
Also I installed separately System.Numerics.Vectors, but I think that these problems were caused by a reading error or a file lock.

On your advice I added in cproj  
```
<Reference Include = "System.Runtime" />
```
and after that the package was installed.

I have the usual project of Xamarin.Forms, in Visual Studio installed Productivity Power Tools and ReSharper.
But as I wrote above, I had problems with read/write access due to which I can not install dependencies.

Thank you for your help!
I am ready to answer all your questions.

**Comment by KSemenenko** [comment]
I tried on another project (iOS, Android, UWP, and Shared Library), and there's also a bug in android project, but all dependecy were installed correctly.

**Comment by freever** [comment]
FWIW I had the exact same problem, and also resolved it by adding 
`<Reference Include = "System.Runtime" />` to the Android csproj file

**Comment by jamesmontemagno** [comment]
We have fixed and addressed this for the next preview release, but will leave it open in case anyone runs into this until we ship the next preview.

**Comment by pldeschamps** [comment]
Hello,

I get the same issue with Xamarin.Essentials 1.5.2
Microsoft Visual Studio Community 2019
Version 16.3.5
VisualStudio.16.Release/16.3.5+29411.108
Microsoft .NET Framework
Version 4.8.03752
Installed Version: Community
Xamarin   16.3.0.277 (d16-3@c0fcab7)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
Xamarin Designer   16.3.0.246 (remotes/origin/d16-3@bd2f86892)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.
Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.
Xamarin.Android SDK   10.0.3.0 (d16-3/4d45b41)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@5608fe0abb3
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333
Xamarin.iOS and Xamarin.Mac SDK   13.4.0.2 (e37549b)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

I could not install this version on iOS project.
I could install it on Android project. The project compiles and runs on emulator.
I could install it on UWP project but could not run it:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to add reference. The package 'Xamarin.Essentials' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Reference unavailable.

**Comment by jamesmontemagno** [comment]
That is a different issue @pldeschamps

Can you right click on your packages.config in your android project (an all project) and migrate to package references

**Comment by pldeschamps** [comment]
I did and updated my iOS project to Xamarin.Essentials 1.5.2 and it worked well.
