### ISSUE TITLE
Location plugin doesn't work in an F# Xamarin project

### ISSUE THREAD

**Issue by RyanBuzzInteractive** [xamarin/Essentials#314]
I have already had another thread running on this  (#288 ) , but it turns out it was a more general issue than I initially reported and it ran quite long, so I created this one instead. I hope that's ok.

The location plugin does not work in an F# Xamarin project, here's a sample. It doesn't return after requesting location., even on successive calls, whether you allow or deny permissions.
 
[PureFSharpExample.zip](https://github.com/xamarin/Essentials/files/2127400/PureFSharpExample.zip)

**Comment by dsyme** [comment]
If you change your code to use 

            |> Async.StartImmediate

then it works for me.  This was after upgrading to FSharp.Core 4.5.0.0 and adding a reference to System.Runtime, both of which I recommend you do (I suspect it's irrelevant to your problem - but I really recommend you upgrade all your F# iOS projects like this)

It appears the Geolocation call must be run on the UI thread.  For somewhat historical reasons RunSynchronously silently "refuses" to run the code on the UI thread and instead runs it in the thread pool while blocking the UI thread awaiting the result.

**Comment by dsyme** [comment]
@jamesmontemagno Would it make sense for XE to throw an exception if the `GetLocationAsync` is not invoked on the UI thread? 

@RyanBuzzInteractive I checked the exceptional case (where permission is denied) and it seems to work OK as well.

**Comment by dsyme** [comment]
@RyanBuzzInteractive I do understand that it's not obvious that `RunSynchronously` would have switched the code to the non-UI thread.

If there's another F# issue lurking here please let me know

**Comment by RyanBuzzInteractive** [comment]
Hi @dsyme , thanks for taking the time to look at this. Just trying to make it work here. 

Simply replacing RunSynchronously with StartImmediate didn't seem to help, so I went to update the FSharp Core version but it's not in the nuget packages for some reason. I haven't made a pure Xamarin F# project before, all my libs have it as a package.  I don't seem to be able to change the target version in the iOS Application properties either.

Could you possibly upload your working sample for me to look at?

Cheers :)

**Comment by RyanBuzzInteractive** [comment]
Also, at risk of dragging this back to the other thread topic - I don't see how I can call it in F# from C#. 

I am using a C# front end and an F# back end which uses the plugins. I pass my F# async funcs to C# by wrapping them in a class method which converts them to Tasks which I then await.

Here's a simplified example - can I somehow marshall this to the right thread?
[Example calling from C#.zip](https://github.com/xamarin/Essentials/files/2127795/Example.calling.from.C.zip)

**Comment by RyanBuzzInteractive** [comment]
Aha! I fixed it. I just use |> Async.StartImmediateAsTask in my wrapper class. Phew! Thanks so much for your help.

**Comment by RyanBuzzInteractive** [comment]
A quick note - my build is now failing in VS Mac as that doesn't support StartAsTaskImmediate yet. This isn't a bug with the plugin of course but does mean it can't be used on a Mac with F# until that arrives.

@dsyme do you have any idea if that is likely to be soon? Or is that nothing to do with you? I just need it to build on a Mac in VSTS and currently that isn't possible.

**Comment by dsyme** [comment]
See reply here https://github.com/xamarin/Essentials/issues/288#issuecomment-403908061, cc @nosami
