### ISSUE TITLE
Enhancement - Add Share API to Xamarin.Essentials

### ISSUE THREAD

**Issue by abdu292** [xamarin/Essentials#318]
I apologize if this is already requested/discussed, though my search did not give any result.

Please add/merge share functionality. This way we can have this plugin (something similar what the below link provides) also, part of Essentials package.

https://github.com/jguertl/SharePlugin

Thanks!

**Comment by jamesmontemagno** [comment]
This is :)

**Comment by abdu292** [comment]
Thanks @mattleibow @jamesmontemagno 

Not sure, how I missed it.  Though, I struggle not to miss any tweet/article about Xamarin. Regards!
