### ISSUE TITLE
Docs - 0.8.0-preview

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#327]
- [x] - Power API
- [x] - Rename Platform to MainThread for BeginInvoke and IsMainThread (also should update blog)
- [ ] - [Document DefaultAccessible for iOS](https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs#L11)
- [x] - Location [Calculate Distance helper](https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Types/Location.shared.cs#L54)
- [x] - Altitude in Location
- [x] - Open Settings in AppInfo
- [x] - Remove and RemoveAll from Secure Storage

**Comment by charlespetzold** [comment]
I've created a branch **chape-essentials-0.8.0-preview** in **xamarin-docs.pr** for the updated docs, and I'll see what I can do over the next couple days.
