### ISSUE TITLE
Version conflict detected for Xamarin.Android.Support.Compat

### ISSUE THREAD

**Issue by ben-powley** [xamarin/Essentials#331]
Bug report best practices: [Submitting Issues](SUBMITTING-ISSUES.md)

### Description
Xamarin essentials 0.7.0.17 can't be installed in a project using the Xamarin.Android.Support 27.0.2.1 libraries.

### Steps to Reproduce

1. Install Xamarin.Essentials 0.7.0.17 to Android project containing android support 27.0.2.1 libraries

### Expected Behavior
Package should install correctly.

### Actual Behavior
Package is not installed in the android project.

### Basic Information

- Version with issue: 0.7.0.17
- IDE: Visual Studio 2017 Proffesional
- Android Support Library Version: 27.0.2.1

**Comment by jamesmontemagno** [comment]
Checkout the blog post here: https://blog.xamarin.com/android-apps-google-play-target-api-level-requirements/

Simply install https://www.nuget.org/packages/Xamarin.Android.Support.CustomTabs/ first and then update/install Xamarin.Essentials.

**Comment by ben-powley** [comment]
Thanks @jamesmontemagno !

**Comment by jamesmontemagno** [comment]
More info here for future readers: https://redth.codes/how-to-fix-the-dreaded-version-conflict-nuget-error-in-your-xamarin-android-projects/
