### ISSUE TITLE
 permissions plugin?

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Essentials#335]
I am bit confused about permissions. there is that line in the [documentation](https://docs.microsoft.com/en-us/xamarin/essentials/get-started?tabs=windows%2Candroid)

Does it that mean that we need to use permissions plugin any longer it is handled automatically for us ? when i see through the samples, i dont see anything regarding permissions? 

> 
> To handle runtime permissions on Android, Xamarin.Essentials must receive any OnRequestPermissionsResult. Add the following code to all Activity classes:
> 
> public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
> {
>     Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);
> 
>     base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
> }

otherwise what is that line for? If i have it like below, is it duplicated or correct?
```

  public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            Plugin.Permissions.PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }

```

**Comment by jamesmontemagno** [comment]
At a base level Xamarin.Essentials will request permissions automatically if needed. 

If you are using other plugins that use the permissions plugin or want to manually request/check then your code is correct there to just pass the results to both.

We have a further discussion here: https://github.com/xamarin/Essentials/issues/77
