### ISSUE TITLE
Cannot build in VisualStudio 2017, Windows 

### ISSUE THREAD

**Issue by baskren** [xamarin/Essentials#341]
Bug report best practices: [Submitting Issues](SUBMITTING-ISSUES.md)

### Description

Cannot build in VisualStudio 2017, Windows 

### Steps to Reproduce

1.  Make local clone of main branch 
2. Open Xamarin.Essentials.sln in VisualStudio 2017
3. Attempt to build any platform project in solution

### Expected Behavior

Project builds successfully

### Actual Behavior

1. Upon opening solution, the following errors appear:

| Severity | Code | Description | Project | File | Line | Suppression State |
|---|---|---|---|---|----|---|
| Error | MSB3073 | The command " "\mdoc\5.7.0.1\tools\mdoc.exe" export-msxdoc --out="C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\bin\Debug\netstandard1.0\Xamarin.Essentials.xml" "C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\..\docs\en"" exited with code 3. | Xamarin.Essentials | C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\mdoc.targets | 41 |  
| Error | MSB3073 | The command " "\mdoc\5.7.0.1\tools\mdoc.exe" export-msxdoc --out="C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\bin\Debug\netstandard2.0\Xamarin.Essentials.xml" "C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\..\docs\en"" exited with code 3. | Xamarin.Essentials | C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\mdoc.targets | 41 |  
| Warning | MSB3785 | No SDKs were found for TargetPlatform = Windows v7.0. SDKReference items will not be resolved. If your application requires these references there may be compilation errors. | Xamarin.Essentials | C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets | 2290 |  
| Error |   | The TargetFramework value 'uap10.0.16299' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. | Xamarin.Essentials | C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets | 96 |  
| Error |   | The TargetFramework value 'Xamarin.iOS10' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. | Xamarin.Essentials | C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets | 96 |  
| Error |   | The TargetFramework value 'MonoAndroid81' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. | Xamarin.Essentials | C:\Program Files\dotnet\sdk\2.1.201\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets | 96 |  

2. Building any platform project in the solution (ex: Samples.UWP) :

| Severity | Code | Description | Project | File | Line | Suppression State
|---|---|---|---|---|----|---|
| Error | CS0006 | Metadata file 'C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\bin\Debug\netstandard2.0\Xamarin.Essentials.dll' could not be found | Samples | C:\Users\ben\Development\Xamarin.Essentials\Samples\Samples\CSC | 1 | Active |
| Error |   | The system cannot find the path specified. (Exception from HRESULT: 0x80070003) | Samples.UWP |   |   |  

### Basic Information

- Version with issue:

   Commit: 26c14c7
   Tag: 0.8.0-preview

- Last known good version: n/a

- IDE:

   VisualStudio 2017 Windows 

```
Microsoft Visual Studio Community 2017 
Version 15.7.4
VisualStudio.15.Release/15.7.4+27703.2035
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40601.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

C# Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.19-rc (a4ffc1b)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 173513e369ffb7a1c4d5dccf83696d9aac2ab2d0.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27703.2035
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

Xamarin   4.10.10.2 (35a01d8dc)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.1 (f3257e429)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.12.0.4 (64fece5)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

- Platform Target Frameworks: 
  - iOS:  n/a
  - Android: 8.1 (Oreo)
  - UWP:  Fall Creators Update, (10.0, build 16299)
- Android Support Library Version: 27.0.2.1
- Nuget Packages: Xamarin.Forms 3.1.0.58944
- Affected Devices: n/a

### Screenshots

n/a

### Reproduction Link

n/a

**Comment by baskren** [comment]
Note, building from the command line also fails:

```
C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials>dotnet restore
  Restore completed in 87.83 ms for C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\Xamarin.Essentials.csproj.

C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials>vim Xamarin.Essentials.csproj

C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials>dotnet msbuild Xamarin.Essentials.csproj
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Xamarin.Essentials -> C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\bin\Debug\netstandard1.0\Xamarin.Essentials.dll
C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\Xamarin.Essentials.csproj : error MSB4057: The target "Build" does not exist in the project.
C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\Xamarin.Essentials.csproj : error MSB4057: The target "Build" does not exist in the project.
C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\Xamarin.Essentials.csproj : error MSB4057: The target "Build" does not exist in the project.
  Xamarin.Essentials -> C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\bin\Debug\netstandard2.0\Xamarin.Essentials.dll
```

And, if I comment out all but one of the `<TargetPlatforms>` (ex: Xamarin.Android):
```
C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials>dotnet restore
  Restoring packages for C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\Xamarin.Essentials.csproj...
  Generating MSBuild file C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\obj\Xamarin.Essentials.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\obj\Xamarin.Essentials.csproj.nuget.g.targets.
  Restore completed in 340.34 ms for C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\Xamarin.Essentials.csproj.

C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials>dotnet msbuild Xamarin.Essentials.csproj
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\ben\Development\Xamarin.Essentials\Xamarin.Essentials\Xamarin.Essentials.csproj : error MSB4057: The target "Build" does not exist in the project.
```

**Comment by jamesmontemagno** [comment]
So, you will want to restore the nugets first.

To build run: msbuild Xamarin.Essentials.csproj 

However, it should work in the IDE just fine

Workloads need:

Xamarin
.NET Core
UWP
You will need the following SDKs

Android 8.1 SDK Installed
UWP 10.0.16299 SDK Installed


My assumptions are maybe these SDKs aren't there^

**Comment by baskren** [comment]
The issue was resolved with manually performing a RESTORE and a CLEAN ALL.  Don't know why, but the automatic restores (at solution load and project rebuild) were not sufficient.
