### ISSUE TITLE
Connectivity needs `IsConnected` and `IsReachable()`

### ISSUE THREAD

**Issue by ChaseFlorell** [xamarin/Essentials#342]
### Description
In an attempt to replace the Xam.Plugin.Connectivity api, I discovered that the `IsConnected` property and the `IsReachable()` method are missing.

Is there an alternative approach that you'd have us to, or can these API's  be included in a future version?

### Expected Behavior

need to be able to easily see if the user is connected and if a remote server is available.

### Actual Behavior

IsConnected and IsReachable() are not available in the current version.

### Basic Information

- Version with issue: 0.6.0-preview

**Comment by jamesmontemagno** [comment]
So for IsConnected you will want to use our new API: NetworkAccess:

https://docs.microsoft.com/en-us/xamarin/essentials/connectivity


For IsReachable see: https://github.com/xamarin/Essentials/issues/334
