### ISSUE TITLE
Barometer/Pressure API

### ISSUE THREAD

**Issue by nicolgit** [xamarin/Essentials#348]
### Description

Implements an API that allows to interact with Pressure sensor when available in order to have:

* current pressure

### API

``` csharp
public class Barometer
{
    bool IsMonitoring { get; private set; }
    void Start();
    void Stop();
    event BarometerChangedEventHandler ReadingChanged;
}
```

### Struct BarometerChangedEventHandler 

``` csharp
    public class BarometerChangedEventHandler : EventArgs
    {
        double Pressure {get; private set}; //In Hectopascals (hPA)
    }
```

### Implementation

- Android: https://developer.android.com/guide/topics/sensors/sensors_environment#sensors-using-temp
- iOS: https://stackoverflow.com/questions/26425576/how-to-get-barometric-pressure-ios 
- UWP: https://docs.microsoft.com/en-us/uwp/api/windows.devices.sensors.barometer

**Comment by jamesmontemagno** [comment]
I have updated it after looking at the APIs. This would really be a Barometer API to monitor pressure changes. That is what UWP and Android provide back.

Note that iOS returns a different measurement then Android/UWP

**Comment by nicolgit** [comment]
not sure I am able to work on iOS implementation but on Android and UWP no problem:-)

I also suggest to add a method for direct conversion from hPA to meter from sea level (it is a trivial formula that needs a reference pressure to calculate the altitude...

**Comment by nicolgit** [comment]
...can I fork and help you on this implementation?

**Comment by jamesmontemagno** [comment]
Yup

**Comment by nicolgit** [comment]
Great @Mrnikbobjeff, thank you!!

**Comment by EeKay** [comment]
> not sure I am able to work on iOS implementation but I can contribute for Android and UWP implementation:-)
> 
> I also suggest to add a method for direct conversion from hPA to meter from sea level (it is a trivial formula that needs a reference pressure to calculate the altitude...

@jamesmontemagno is there any reason why this was left out? I know that iOS gives this alongside its pressure result? Or is this in the pipeline? I'm googling the right calculation, would you consider including this as a pull request?

**Comment by jamesmontemagno** [comment]
We introduced tons of great converters: https://github.com/xamarin/Essentials/blob/dev/1.1.0/Xamarin.Essentials/Types/UnitConverters.shared.cs
