### ISSUE TITLE
Updating package fails .... 

### ISSUE THREAD

**Issue by stephenhauck** [xamarin/Essentials#350]
I tried to simply update the android package and it failed with the following error ...

_Severity	Code	Description	Project	File	Line	Suppression State
Error		Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the project to resolve this issue. 
 Inspektion.Android -> Xamarin.Essentials 0.8.0-preview -> Xamarin.Android.Support.CustomTabs 27.0.2.1 -> Xamarin.Android.Support.Compat (= 27.0.2.1) 
 Inspektion.Android -> Xamarin.Android.Support.Design 27.0.2 -> Xamarin.Android.Support.Compat (= 27.0.2).			0_

**Comment by jamesmontemagno** [comment]
Simply update all of your support libraries to 27.0.2.1

https://redth.codes/how-to-fix-the-dreaded-version-conflict-nuget-error-in-your-xamarin-android-projects/
