### ISSUE TITLE
Get the TimeZone from the Latitude and Longitude Location

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#351]
Hi,

Is it possible for the current or future releases of Xamarin Essentials to determine the timezone from the location's latitude and longitude?

Thanks,
Jassim

**Comment by jamesmontemagno** [comment]
Can you specify a bit more what you mean by this? You are saying like if it detects that we are in Seattle then you would want somehow the position to know the timezone? Most likely you could use the DateTime.Now of the device which would be accurate. 

Or there are a lot of options here: https://stackoverflow.com/questions/16086962/how-to-get-a-time-zone-from-a-location-using-latitude-and-longitude-coordinates

I don't think we want to introduce something like this into Essentials as it's core mission is to abstract platform APIs.

**Comment by jrahma** [comment]
I mean if I get the latitude and longitude then is it also possible that Xamarin Essentials will tel me that the current location timezone is +3 GMT or -8 GMT, etc?

Just like what:

[https://developers.google.com/maps/documentation/timezone/intro](https://developers.google.com/maps/documentation/timezone/intro)

gives.. but it will be great if can get it from Xamarin itself..

**Comment by jamesmontemagno** [comment]
There are a few options for you in this area as we provide this functionality via Azure:  https://docs.microsoft.com/en-us/rest/api/maps/timezone/gettimezonebycoordinates

Also, there is a .NET offline open source library to do this:
https://github.com/mj1856/GeoTimeZone

**Comment by jrahma** [comment]
but it will be great if it's also included in Xamarin Essentials so developers can use it for most of the geo stuff. thanks.

**Comment by jamesmontemagno** [comment]
Since timezones can be ever changing they go against our principals for the library and abstracting core APIs of each platform. So this is not a feature that will be on the roadmap.
