### ISSUE TITLE
Add Application State Event API

### ISSUE THREAD

**Issue by aritchie** [xamarin/Essentials#358]
## Description of the Feature

Events for detecting app state transitions (foregrounding & background) in a global fashion.  Allows for good decoupling of services that need to clean up or do something (ie. send a notification as an app goes to background)

## API Declaration

Integration Point: AppInfo

```csharp
public static AppState State { get; private set; }

public delegate void AppStateChangedEventHandler(AppStateChangedEventArgs e);

public class AppStateChangedEventArgs : EventArgs
{
    internal AppStateChangedEventArgs (AppState appState) => AppState = appState;
    public AppState State { get; }
}

public enum AppState
{
    Foreground,
    Background
}
```

## Documentation for supported platforms

* iOS: https://developer.apple.com/documentation/uikit/uiapplication/1622944-willenterforegroundnotification, 
* Android: Requires a bit of black magic, but the necessary mechanics are already in essentials with ActivityLifecycleContextListener - https://github.com/aritchie/deviceinfo/blob/master/Plugin.DeviceInfo/Platforms/Android/AppStateLifecycle.cs
* UWP: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.window.visibilitychanged

Current implementation to port from: https://github.com/aritchie/deviceinfo/tree/master/Plugin.DeviceInfo

EDIT: Updated by @redth to finalize API spec

**Comment by jamesmontemagno** [comment]
I would also add

```csharp
public static AppState State {get; private set;}
```

Then I would use do a custom EventHandler to follow our pattern:

```csharp
 public delegate void CompassChangedEventHandler(CompassChangedEventArgs e);

    public class AppStateChangedEventArgs : EventArgs
    {
        internal AppStateChangedEventArgs (AppState appState) => AppState = appState;

        public AppState State { get; }
    }
```

**Comment by jamesmontemagno** [comment]
I think looks pretty straight forward to me @Redth @mattleibow can comment.

**Comment by Mrnikbobjeff** [comment]
@aritchie Even though I generally support your proposal this will be in conflict with @jamesmontemagno 's proposal to add the State property. All platforms would need to hook to keep the property up to date. Not sure this is possible then.

**Comment by aritchie** [comment]
@Mrnikbobjeff Only android requires a hook, but it gets built into with the top activity mechanics in any case.  The state property can be checked without any hooks on UWP & iOS.

**Comment by Mrnikbobjeff** [comment]
Haha oh no, I was just implementing this and almost done, except for this confusion about the property 🤦‍♂️  . Guess I will abandon this then^^

**Comment by Redth** [comment]
I updated the original issue with the spec.  I think we are ready to implement this.

**Comment by jamesmontemagno** [comment]
After examining this API we have come to the conclusion that it is not a good fit for Essentials as it can not be properly abstracted across each platform. I want to thank you for your effort in this PR and comments on the issue and talking through all of the concerns.
