### ISSUE TITLE
Add IsRemoteReachable to Connectivity like it exists in Xamarin Connectivity plugin

### ISSUE THREAD

**Issue by VincentH-Net** [xamarin/Essentials#360]
### Expected Behavior
I can replace Xamarin Connectivity plugin with Xamarin Essentials Connectivity

### Actual Behavior
Can't replace Xamarin Connectivity plugin with Xamarin Essentials Connectivity:
[IsRemoteReachable](https://jamesmontemagno.github.io/ConnectivityPlugin/PingaHost.html) is not implemented

IsRemoteReachable is commonly useful because it allows the most common connection issues to be placed into one of 2 human-friendly categories:
A) The device has no internet connection
B) The backend service is not available on the internet

IsRemoteReachable allows to report issues in category B to a separate error service (e.g. Raygun) which can have email alerts set on this specific error for backend administrators, thus reducing backend downtime. The app can then show the user a message like "We are currently experiencing an issue with the \<app name\> server. Support personnel has been notified and is working to fix the issue asap".

**Comment by jamesmontemagno** [comment]
Please see: https://github.com/xamarin/Essentials/issues/334
