### ISSUE TITLE
Step Counter API

### ISSUE THREAD

**Issue by nicolgit** [xamarin/Essentials#362]
### Description

Implements an API that allows to interact with integrated Step Counter when available in order to have:

* number of steps taken by the user since the last reboot while the sensor was activated

### API

``` csharp
public class StepCounter
{
    bool IsMonitoring { get; private set; }
    void Start();
    void Stop();
    event StepCounterChangedEventHandler ReadingChanged;
}
```

### Struct StepCounterChangedEventHandler  

``` csharp
    public class StepCounterChangedEventHandler : EventArgs
    {
        DateTimeOffset Timestamp {get; private set}; // time of the most recent pedometer reading
        int TotalSteps {get; private set}; 
    }
```

### Implementation

- Android: https://developer.android.com/guide/topics/sensors/sensors_motion
- iOS: https://developer.apple.com/documentation/coremotion/cmpedometer 
- UWP: https://docs.microsoft.com/en-us/uwp/api/windows.devices.sensors.pedometerreading

> VS bug [#735664](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735664)

**Comment by jamesmontemagno** [comment]
Considerations here is that they would be only when the app is open and is not for background tracking. On Android that would require a service.

**Comment by SatyaRamprasad** [comment]
@jamesmontemagno  Any updates on this feature request(background tracking)

**Comment by jrahma** [comment]
It will be great if you link it to the Location API in Xamarin Essentials to return the current location too

**Comment by Happypig375** [comment]
It would be great if Xamarin.Essentials has all sensors built-in, especially the pedometer.

**Comment by sanjeevmajgotra** [comment]
any update on this? if not then is there any logic using existing apis we can use to accurately detect motion?

**Comment by jamesmontemagno** [comment]
Take a look at Shiny -> https://github.com/shinyorg/shiny it is included in here.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.

**Comment by Happypig375** [comment]
@jfversluis Ok then will .NET MAUI essentials have it

**Comment by Happypig375** [comment]
I can't believe the MAUI team closes issues instead of transferring them but whatever.
New issue here https://github.com/dotnet/maui/issues/16712
