### ISSUE TITLE
Use generic EventHandler<T> for event delegate types

### ISSUE THREAD

**Issue by praeclarum** [xamarin/Essentials#365]
### Description

The `Accelerometer` and possibly other types use custom delegate types for the even handlers. This creates some minor issues:

1. It introduces an unnecessary type in the namespace
2. It makes interpreting the library more difficult

I wonder if you would consider switching to generic `EventHandler<AccelerometerChangedEventArgs>` and friends to keep things simple.

### Basic Information

- Version with issue: 0.8
- Platform Target Frameworks: 
  - iOS: 11

**Comment by Mrnikbobjeff** [comment]
I would support this decision. The default namespace will only become more  cluttered the more xamarin.essentials grows. Removing unnecessary types would probably improve usage experience.
