### ISSUE TITLE
DeviceInfo.Model on iOS

### ISSUE THREAD

**Issue by domagojmedo** [xamarin/Essentials#366]
Is it possible for Model to return actual version of the device? (iPhone 8 instead of just iPhone)

Kinda like this https://github.com/dannycabrera/Get-iOS-Model nuget package

**Comment by jamesmontemagno** [comment]
This API unfortunately is not publicly available and not maintainable. It also requires DllImports and is something we would not want introduce into an official API.

**Comment by stefandevo** [comment]
Don't understand why this is such a problem... Been using that kind of code for years in all our apps without any problem; now it is just unusable; it returns "iPhone" or "iPad" while "Idiom" also... returns 'iPhone" and 'iPad". How stupid is this??

**Comment by jamesmontemagno** [comment]
Let me sync with App Center team to see what they do. My original concern was over private apis.

**Comment by stefandevo** [comment]
Thanks!
