### ISSUE TITLE
SensorSpeed.Ui should be SensorSpeed.UI

### ISSUE THREAD

**Issue by praeclarum** [xamarin/Essentials#367]
Microsoft docs state that two letter acronyms should be capitalized: https://msdn.microsoft.com/en-us/library/ms229043(v=vs.100).aspx?f=255&mspperror=-2147217396#Anchor_2

This is the convention thought .NET with System.IO and UIView, etc.

### Description

Enum property name has wrong casing.

- Version with issue: 0.8

**Comment by jamesmontemagno** [comment]
Good one. We should asses all others that we have. Will need to update this and the docs.

**Comment by jamesmontemagno** [comment]
I evaluated our other Enums and 2 letter acryonyms.

We have:

```
public enum BatteryPowerSource
    {
        Unknown,
        Battery,
        Ac,
        Usb,
        Wireless
    }
```

**Comment by jamesmontemagno** [comment]
I believe Usb should be Usb based on reading some docs. Ac I am not positive on.. I think AC
