### ISSUE TITLE
Suggestion: UserInformation

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#372]
Hi,

I can't see an option to get the user first name, last name and photo

Hope this will be added, at least the user first and last name if photo not possible.

Thanks,
Jassim

**Comment by jamesmontemagno** [comment]
Thanks for the suggestion. This unfortunately isn't an API available across each of the platforms unless you know of the native APIs that are available. Android does have a bit of ability to pull from contacts and iOS has extremely limited capabilities in cloudkit itself. This is more of an oAuth service request.
