### ISSUE TITLE
UWP ScreenMetrics relate to device not window

### ISSUE THREAD

**Issue by freever** [xamarin/Essentials#376]
Hi guys

Great work on this library, it's becoming my Swiss Army knife!

I have a question though. I want to use the information provided by the DeviceDisplay class to figure out how to size elements on my screen. This seems to be a good option on iOS and on Android, but on UWP I'm getting the dimensions of the physical screen rather than the dimensions of the window in which my application is running. 

This makes a certain amount of sense - I mean DeviceDisplay tells you about the Device, right? But it is perhaps a bit of a grey area, since UWP is a hybrid PC/mobile OS. 

In most cases, on Android and iOS, device screen size and rendering window size would be the same thing (although split screen on iPad might be another curve ball). However on UWP, device size and rendering area size are likely to be different most of the time. 

What are your thoughts on this? Should DeviceDisplay refer to application display area or the total available display area on the host hardware? Or should there be another set of ApplicationWidth and ApplicationHeight properties to expose this information? Is this information even available anywhere in the OS APIs, as far as you know?

Thanks a bunch.

**Comment by jamesmontemagno** [comment]
The metrics here are the actual Device metrics:

* iOS: UIDevice.MainScreen
* Android: DisplayMetrics
* UWP: DisplayInformation


So the API is intended. I think we would want to open a new Proposal for the Window/Screen/App Metrics.

**Comment by jamesmontemagno** [comment]
See https://github.com/xamarin/Essentials/issues/385 for new proposal
