### ISSUE TITLE
FileSystem Documents folder API

### ISSUE THREAD

**Issue by GalaxiaGuy** [xamarin/Essentials#377]
### Description

After reading this: 
https://github.com/xamarin/Xamarin.Forms/issues/3192

it seems a common way to get a folder the app can save to that is also visible to the user (and other apps) might be useful.
### API

```csharp
public static partial class FileSystem
{
    public static string DocumentsDirectory { get; }
}
```

One concern I have is, as far as I know:

iOS only lets you save files in a location that is still specific to your app
Android and Windows just have a common public location

Is this difference in behavior an issue? Should the API be more opinionated and created a subfolder for you and return that?

**Comment by jamesmontemagno** [comment]
We decided to not add this currently because Android has permission concerns for developers. However, yes we could most likely provide guidance and just document it in https://docs.microsoft.com/en-us/xamarin/essentials/file-system-helpers.

**Comment by Redth** [comment]
What's the use case for this API? I'm wondering if we can cover the use cases by other means (eg: Sharing a file with the system provided share mechanism instead of just saving it to some shared location)

**Comment by newky2k** [comment]
Seems like this can't happen.
