### ISSUE TITLE
Geolocation startup and location availability question...

### ISSUE THREAD

**Issue by stephenhauck** [xamarin/Essentials#378]
In the documentation you state that the permission will be requested by the plugin.

Is there a startup delay to use the functions to obtain the current location or will asking the permissions spin up the GPS and get it ready ?

**Comment by jamesmontemagno** [comment]
The process is mostly:

* You call "GetLocation"
* We check permissions, prompt if needed (so must be on UI thread)
* If we have permissions we will get location
* if they say no or it is denied already we throw an exception.

You can't start accessing the GPS until you have permissions from your users.

Hope this helps. Let me know if you have any questions.

**Comment by jamesmontemagno** [comment]
We will be adding a position changed in the future :) hoping sooner then later.

**Comment by stephenhauck** [comment]
ok, just wondered if there was a way to accomplish the same functionality with the existing code base I was missing.

:)
