### ISSUE TITLE
DeviceId missing

### ISSUE THREAD

**Issue by matteopiccioni** [xamarin/Essentials#384]
Hello, 
I came from your previous DeviceInfoPlugin package.
I try to use Essential, so I can remove a lot of packages and hope in better loading times in Android

I cant find DeviceId feature.
There is a way to retrieve deviceid with Essential or I have to use DependencyService (for example) ?

Thanks

**Comment by jamesmontemagno** [comment]
See: https://github.com/xamarin/Essentials/issues/61
