### ISSUE TITLE
Add Xamarin.Essentials.MainThread.BeginInvokeOnMainThreadAsync

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Essentials#389]
I suggest adding the function:
``` cs 
Task Xamarin.Essentials.MainThread.BeginInvokeOnMainThreadAsync(Task task)
```
sometimes I need to run a Task on a UI Thread, for example it's navigation, or something else asynchronous.

**Comment by jamesmontemagno** [comment]
I actually don't think this is possible due to how each platform works. iOS just takes an action and you can't register for when it is complete. Same on Android unfortunately.
