### ISSUE TITLE
Phone dialer usage

### ISSUE THREAD

**Issue by domagojmedo** [xamarin/Essentials#390]
On android why does the helper always try to use current locale? I don't see the same formatting for ios or uwp.
What if you want to dial a number from a different locale? 
Should there be a way to call dialer with raw string number you want?

**Comment by jamesmontemagno** [comment]
Yeah, I agree here... let me look.

**Comment by jamesmontemagno** [comment]
So, that is actually the "default" to use.

If the number already has a country code it will use it else will just return the normal one: https://developer.android.com/reference/android/telephony/PhoneNumberUtils#formatNumber So this is good already.
