### ISSUE TITLE
Add phone guid with DeviceInfo

### ISSUE THREAD

**Issue by Moltroon** [xamarin/Essentials#397]
Hello,

Can you add the GUID number with the Xamarin.Essentials.DeviceInfo ?

Thanks

**Comment by jamesmontemagno** [comment]
Can you provide what you mean here?

**Comment by jamesmontemagno** [comment]
Are you perhaps talking specifically about a unique ID? https://github.com/xamarin/Essentials/issues/61

**Comment by jamesmontemagno** [comment]
Yeah, that one I never should have added cause it doesn't do anything special and is different every time.

You just need to use: Guid.NewGuid()

**Comment by Moltroon** [comment]
Ok. Me I use it to generate an unique ID with md5(GUID+userid+date)[:5] to activate a backdoor to assist they users. (empty cache action, passed to test server, etc...) (In simplified)

You found the only person who found him a useful :) Thanks you.

**Comment by jamesmontemagno** [comment]
Tehehe, Once we implement Device Id you will be able to generate this information yourself using the same code that I have in that plugin: https://github.com/jamesmontemagno/DeviceInfoPlugin/blob/master/src/DeviceInfo.Plugin/DeviceInfo.android.cs#L62

It is something that doesn't make sense to add here as it is something developers can put together as you will have all the info :)

**Comment by jamesmontemagno** [comment]
I think if you are just using the "Id" field then that is actually issue #61 and is something we plan to implement in the next sprint, so will be there soon :)
