### ISSUE TITLE
[iOS] SecureStorage publish issues

### ISSUE THREAD

**Issue by stesvis** [xamarin/Essentials#398]
Everything seems to work locally, but when I send the app to the App store it fails with this error:

> ERROR ITMS-90164: "Invalid Code Signing Entitlements. The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. According to the provisioning profile, the bundle contains a key value that is not allowed: '[ "com.veloguide.mobile.prod", "com.veloguide.mobile.dev", "com.veloguide.mobile.staging" ]' for the key 'keychain-access-groups' in 'Payload/VeloGuideApp.iOS.app/VeloGuideApp.iOS'"

I am really not sure how to fix this. Android is all good though.
Is there a problem with KeyChain enabled in iOS?

**Comment by jamesmontemagno** [comment]
Check your entitlements.plist and remove your keys that you aren't using as they aren't needed for publishing.

**Comment by jamesmontemagno** [comment]
When you publish to the app store, Apple checks your entitlements and ensures that you set them up for that app and provisioning profile. Based on your usage you would need to set it up in the portable, but for Essentials they are not needed at all. You may want to create a "EntitlementsDev.plist" and "Entitlements.plist" with different settings.

**Comment by stesvis** [comment]
Thanks @jamesmontemagno I just realized that the key should be
**TEAMID.com.yourcompany.yourapp**
instead of just
**com.yourcompany.yourapp**

**Comment by jamesmontemagno** [comment]
so all good? okay to close?

**Comment by stesvis** [comment]
Yes, I forgot. Thank you.
