### ISSUE TITLE
ScreenMetricsChanagedEventArgs(ScreenMetrics) Constructor

### ISSUE THREAD

**Issue by Powerhelmsman** [xamarin/Essentials#418]
This issue was created by Pooglz from https://github.com/MicrosoftDocs/feedback/issues/540
 
I hope that's just a typo, but I'm thinking maybe not. Unfortunate.
https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.screenmetricschanagedeventargs

"Chanaged" everywhere should be "Changed"

I submit the PR to correct but failed to merge. So I transfer this issue to your queue. You guys can follow up this content issue.

**Comment by jamesmontemagno** [comment]
So in 0.8.0 there was actually a typo in the code, we fixed it for 0.9.0. These docs are auto generated and will be updated in our next release :)
