### ISSUE TITLE
Geocoder crashes on Emulator

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#421]
Hi,

My amarin Essential crashes on Android Emulator with the following error:

> Java.IO.IOException: Service not Available
>   at java.io.IOException: Service not Available
>   at at android.location.Geocoder.getFromLocation(Geocoder.java:136)
> 

but it woks perfectly when I upload it to real device..

How to fix this please?

Thanks,
Jassim

**Comment by jamesmontemagno** [comment]
That is correct, some emulators the geocoder is not available. You should try/catch this method when calling it.

I will add to documentation.
