### ISSUE TITLE
Determine Airplane mode

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#423]
Hi,

Please add a feature to determine the Airplane mode.

Thanks,
Jassim

**Comment by GalaxiaGuy** [comment]
I don't believe iOS exposes airplane mode specifically. Do you actually need to detect airplane mode or do you just need to detect if the device has internet access? There is already `Connectivity`:

https://github.com/xamarin/Essentials/tree/master/Xamarin.Essentials/Connectivity

**Comment by jrahma** [comment]
Nope, airplane mode before making call or sending sms

**Comment by jamesmontemagno** [comment]
After doing research here there is no consistent API to do this across each platform. Connectivity will tell you if you can reach the internet and you can also detect the connection types. This gives you all the data needed.

**Comment by GreatSummit** [comment]
Hi,

Connectivity returns NetworkAccess.Internet on airplane mode on both iOS and Android.
(Xamarin.iOS/Android)

Could you fix this issue as soon as possible?

Thanks.

**Comment by jamesmontemagno** [comment]
Mine returns None on both iOS and Android
