### ISSUE TITLE
Share: Share Documents/Files

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#425]
Hi,

Please add an option to Share Documents with a Title and URL..

For example, share PDF in Whatsapp or Google Drive or One Drive or DropBox..

Thanks,
Jassim

> VS bug [#735659](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735659)

**Comment by mattleibow** [comment]
This is probably related to the #129 and #416 and some other issues. The basic problem is that sharing files may require access to internal/local app files. I think #416 is to address the initial limitation.

**Comment by Redth** [comment]
1.1.0 has file sharing!

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '1.1.0' that is not in the list of supported values

**Comment by mfeingol** [comment]
Nice to see this land! I gave it a spin with code along these lines:

```c#
                string filePath = path to a PDF;
                string contentType = "application/pdf";

                ShareFile share = new ShareFile(filePath, contentType);
                ShareFileRequest request = new ShareFileRequest(Path.GetFileName(filePath), share);
                await Share.RequestAsync(request);
```

It worked, in that a system dialog opens with some apps as options. However, the apps were Gmail, Save to Drive, and Messages, aka generic options. If I use the more traditional approach (e.g. https://www.syncfusion.com/kb/8707/how-to-share-the-pdf-document-in-xamarin-forms-platform), I get PDF-specific options, such as "Drive PDF Viewer".

Is there some setup required before the feature will work as expected?

Thanks.

**Comment by jamesmontemagno** [comment]
You will need to enable the experimental features:

// Enable currently experimental features
            ExperimentalFeatures.Enable(
                ExperimentalFeatures.EmailAttachments,
                ExperimentalFeatures.ShareFileRequest);

Under the hood it calls:

```csharp
            var contentUri = Platform.GetShareableFileUri(request.File.FullPath);

            var intent = new Intent(Intent.ActionSend);
            intent.SetType(request.File.ContentType);
            intent.SetFlags(ActivityFlags.GrantReadUriPermission);
            intent.PutExtra(Intent.ExtraStream, contentUri);

            if (!string.IsNullOrEmpty(request.Title))
            {
                intent.PutExtra(Intent.ExtraTitle, request.Title);
            }

            var chooserIntent = Intent.CreateChooser(intent, request.Title ?? string.Empty);
            chooserIntent.SetFlags(ActivityFlags.ClearTop);
            chooserIntent.SetFlags(ActivityFlags.NewTask);
            Platform.AppContext.StartActivity(chooserIntent);

            return Task.CompletedTask;
```

Which looks pretty much identical to what is in that article, so should work.

**Comment by mfeingol** [comment]
@jamesmontemagno: I spent a little more time on this. Ultimately, it's a question of intent. :-)

My app currently does the following:

```
            Intent intent = new Intent(Intent.ActionView);
            intent.SetDataAndType(contentUri, contentType);
            intent.SetFlags(Android.Content.ActivityFlags.ClearWhenTaskReset | Android.Content.ActivityFlags.NewTask | Android.Content.ActivityFlags.GrantReadUriPermission);
            Android.App.Application.Context.StartActivity(intent);
```

This results in the following system dialog:

![image](https://user-images.githubusercontent.com/218865/54883946-4bdddb80-4e28-11e9-8fd2-203f106f111f.png)

Using the `ActionSend` intent as the code does above results in the following system dialog, which is indeed identical to the one from `Xamarin.Essentials.Share.RequestAsync`:

![image](https://user-images.githubusercontent.com/218865/54883962-762f9900-4e28-11e9-9bde-a68d1ed2d1aa.png)

I have no basis for judging which of the two intents is preferable for an abstraction that involves sharing files. My particular use case is to launch an external viewer, and `ActionView` clearly works better for that. So for Xamarin Essentials, perhaps a different abstraction is needed for launching files, or perhaps some kind of selector on `ShareFileRequest` to specify the precise intention?

**Comment by jamesmontemagno** [comment]
Ahhhhh yes, this makes sense! Good call. The API is still not final so we can easily play around with this. I think we can add an intention on it. Or we can have "ShareFileRequest" and "ViewFileRequest".. @Redth 

The question is... is it different in UWP and iOS at all?

**Comment by jamesmontemagno** [comment]
Re-opening for now since we are reving the API

**Comment by mfeingol** [comment]
UWP distinguishes between launching a file (`Windows.System.Launcher.LaunchFileAsync`) and sharing a file (`Windows.ApplicationModel.DataTransfer.DataTransferManager.ShowShareUI`).

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '1.1.1' that is not in the list of supported values

**Comment by sarthak199526** [comment]
Hi friends for android version > 24 you need to use fileProvider class

use : Uri uri = FileProvider.getUriForFile(MainActivity.this, BuildConfig.APPLICATION_ID + ".provider",fileImagePath);

InsteadOf : Uri uri = Uri.fromFile(fileImagePath);

Just Implemented On my app

Reference : https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

**Comment by mattleibow** [comment]
@JamesMontemagno, maybe this is where we should be using the launcher to open files and the share to share? This may mean we have to extend the launcher apis

**Comment by RhomGit** [comment]
Agreed with @mattleibow above. 
I see this has been open for roughly 9 months but is slated for 1.1.1 … which itself is 22 days overdue. Just to be sure (I have clients requiring this functionality asap) does this mean that it can be expected "soon" or perhaps I should implement an alternative solution until some unknown future date? 

I don't want to appear rude (I am grateful for all of the effort on this project) and I would prefer to use a Xamarin.Essentials function for opening files but its hard to make decisions without knowing a little more. Is work already underway on this?

**Comment by jamesmontemagno** [comment]
@RhomGit the ability to share is already integrated into 1.1.0 and we re-opened this to expand to opening the file. We are working on new features and bug fixes regularly.

**Comment by jamesmontemagno** [comment]
Closing now as API is in 1.2.0-pre shipping soon :)
