### ISSUE TITLE
Feature Request: Download Files

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#426]
Hi,

Please add a feature to download files in Xamarin Forms platform, for example, photoz, documents, etc..

Thanks,
Jassim

**Comment by mattleibow** [comment]
This can already be done with `WebClient` which is available in .NET Standard 2.0: https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient?view=netstandard-2.0

And then if you really want to go hardcore, you can have a look at the source for this baby: https://github.com/dotnet/corefx/blob/master/src/System.Net.WebClient/src/System/Net/WebClient.cs

**Comment by Redth** [comment]
Yeah I'm not sure what value we can add to `HttpClient` or `WebClient`.

If you think there's something missing, please elaborate.

**Comment by Redth** [comment]
One thing that has come to my attention is that we might want to enable _background_ downloading of files such as with `NSUrlSession` on iOS, and perhaps just generic background tasks on Android/UWP.

This might be interesting.  Need to research more details on how NSUrlSession works and how that influences what the xplat API will look like.

**Comment by gsmental** [comment]
property and methods
**FileUrl --string or URI
IsUrlExistsOnServer --bool
ClientAppFilePath --string
DeleteIfAlreadyExists --bool**

and event which will fire during downloading of file and provide information as below
**TotalSizeInBytes --double
DownloadedSizeInBytes --double
Percentage -- decimal (it is option otherwise we have to calculate manually)**

**Comment by mattleibow** [comment]
For Android: https://developer.android.com/reference/android/app/DownloadManager
For UWP: https://docs.microsoft.com/en-us/uwp/api/Windows.Networking.BackgroundTransfer.BackgroundDownloader / https://docs.microsoft.com/en-us/windows/uwp/networking/background-transfers

**Comment by DanielCauser** [comment]
@jrahma I'm using this lib for exactly what you want.
https://github.com/aritchie/httptransfertasks

**Comment by Redth** [comment]
I think we can come up with an event that can be subscribed to while the app is in the foreground, but of course it is possible the event will stop firing once the app enters the background.

**Comment by newky2k** [comment]
As there is a library that provides this functionality already we are going to close this off.
