### ISSUE TITLE
Document which permissions needed for each api

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Essentials#429]
Documentation seems to be not covering which permission is needed for each api. i went through almost all and only connectivity plugin had it written.

**Comment by jamesmontemagno** [comment]
These are all documented under the getting started for each API:

* https://docs.microsoft.com/en-us/xamarin/essentials/connectivity?tabs=android
* https://docs.microsoft.com/en-us/xamarin/essentials/battery?tabs=android
* https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?tabs=android
* https://docs.microsoft.com/en-us/xamarin/essentials/flashlight?tabs=android
* https://docs.microsoft.com/en-us/xamarin/essentials/vibrate?tabs=android

Let me know if something is missing.

**Comment by EmilAlipiev** [comment]
oh ok, beside connectivity none of those plugins i use. thats why I didnt see them and I thought plugins like DeviceInfo , Text-to-Speech, Version Tracking also needs some permissions or maybe not if they arent documented :)

**Comment by jamesmontemagno** [comment]
Nope, they don't need anything special at this point.
