### ISSUE TITLE
App Icon Badges

### ISSUE THREAD

**Issue by c-lamont** [xamarin/Essentials#431]
I think it would be great to have the ability to set the app icon badge number. 

I am aware that Essentials does not want to be involved with UI work, but the badge style can never really be changed so I think it could be a nice easy feature to add.

I am also aware that Android does not fully support badges, but this package does it pretty well: https://github.com/alexrainman/Badge

**Comment by chrisgate** [comment]
@c-lamont are ou confirming this package from your personal usage?

**Comment by c-lamont** [comment]
@chrisgate I have just implemented and tested it on one Android (Samsung) and one iOS (iPhone 5c) device this morning.

**Comment by chrisgate** [comment]
Thanks

**Comment by mattleibow** [comment]
I just want to point out to our other collaborators who may be interested. This plugin basically has custom logic per Android manufacturer. I am not sure if this is something we want to support. @Redth @jamesmontemagno this is very much that you will have to make a call on before we look into this.

**Comment by jamesmontemagno** [comment]
I do not believe that this is maintainable on the Android side and can be re-assessed if there is an official API to do this.
