### ISSUE TITLE
Battery permission is wrong in essentials battery documentation page (should be BATTERY_STATS)

### ISSUE THREAD

**Issue by Verthosa** [xamarin/Essentials#433]
Bug report best practices: [Submitting Issues](SUBMITTING-ISSUES.md)

### Description

In the battery documentation page, it is said that in Android you need the android.permission.BATTERY permission but to be completely correct the permission's name is android.permission.BATTERY_STATS

### Steps to Reproduce

1.  set manifest permission to android.permission.BATTERY
2.  run a demo app using xamarin essentials battery 
3.  receive an error

### Expected Behavior
We can use the battery extention

### Actual Behavior
Permission error 

### Basic Information
use android.permission.BATTERY_STATS instead of android.permission.BATTERY to fix

**Comment by jamesmontemagno** [comment]
Thanks! I have a PR for this going in today.
