### ISSUE TITLE
Maps Question (Multiple pins on map)

### ISSUE THREAD

**Issue by TedMobile** [xamarin/Essentials#438]
I really like the new addition "Maps".

just wondering if it's possible to have multiple pins on the map at the same time and ability to have a click event on the pin.

 In real world we would always show a set of pins on a map and ability to click on them for info.

Is any of the above in the planning

many thanks

**Comment by jamesmontemagno** [comment]
It is a good suggestion. I know that some of the platforms support this:

* iOS: https://developer.apple.com/documentation/mapkit/mkmapitem/1452207-openmaps
* UWP: https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-maps-app#display-multiple-points

I can not find any documentation that would support that Android does at all though: https://developer.android.com/guide/appendix/g-app-intents

I think that this limitation would stop us from being able to introduce this API unless it was for iOS/UWP specifically.

**Comment by NokautBR** [comment]
On Android, are you looking for this?
https://developers.google.com/maps/documentation/android-sdk/marker

**Comment by jamesmontemagno** [comment]
@NokautBR thanks for the link, but this is for embedding a map into your app. From the looks of it there is no intent system that offers this so I don't believe we can add this into the api. Thanks for the suggestion though.
