### ISSUE TITLE
Name is not showing in Map API

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#446]
Hi,

I am trying below code to open the map app as explained in your doc.. The map app is getting opened but with no name for the location..

How can I fix that?

var location = new Location(25.2547667, 55.290913);
var options = new MapsLaunchOptions { Name = "الأوقاف الجعفرية" };

await Maps.OpenAsync(location);

**Comment by jamesmontemagno** [comment]
you need to pass the options in:

await Maps.OpenAsync(location, options);

Also provide information in the future on what platform and devices you are testing.
