### ISSUE TITLE
Feature: App Rating

### ISSUE THREAD

**Issue by adamfisher** [xamarin/Essentials#447]
## Description of the Feature
Provide the ability to rate the mobile application based on specific criteria to improve app store reviews and ratings.

[![](https://user-images.githubusercontent.com/1834711/43689094-f956381e-98c2-11e8-8e75-a686ceb111ec.png)](#)

## API Declaration

This API idea was modeled after the famous `Android-Rate` library since it kind of follows the same pattern **Xamarin.Essentials** follows. This API would depend on the `Preferences` API to store the settings to know when to prompt for a rating.

```csharp
// Added to startup code
AppRate.with(this) // this may be needed for Android context but not iOS
      .WithAppId("com.google.duo") // or the app store appId on iOS
      .WithInstallDays(0) // default 10, 0 means install day.
      .WithLaunchTimes(3) // default 10
      .WithReminderInterval(TimeSpan.FromDays(3))
      .WithDialogTitleText("Rate this app") // < default text
      .WithDialogMessageText("If you enjoy playing this app, would you mind taking a moment to rate it? It won\'t take more than a minute. Thanks for your support!") // < default text
      .WithDialogOkButtonText("Rate It Now") // < default text
      .WithDialogCancelButtonText("Remind Me Later") // < default text
      .WithDialogNoButtonText("No, Thanks") // < default text
      .WithShowCancelButton(true) // default true
      .WithShowNoButton(true) // default true
      .WithDebug(false) // default false
      .monitor();

// Optionally, you could have specified some event handler hooks before monitoring
AppRate.OnButtonClicked += (ButtonType buttonType) => {};

// Optionally, hook into an event to know when a rating should be shown and do it yourself.
AppRate.OnRatingInvoked += (OnRatingInvokedEventArgs ratingConfig) => {
   var dialogTitle = ratingConfig.DialogTitleText;
   var dialogMessage = ratingConfig.DialogMessageText;
   ...
   DisplayAlert(...};

   // return true to indicate you took care of the rating prompt or 
   // false if this was just a hook to know when a rating prompt is shown
   return true;
};
// Manually show a dialog if meets conditions
AppRate.ShowRateDialogIfMeetsConditions();

// Manually show the dialog
AppRate.ShowRateDialog();
```

### Implementations:

I tried to find the most reputable ones in existence. In iOS 10.3, `SKStoreReviewController` was introduced which allows rating directly within the app without any additional setup so the rating API should support falling back to showing an alert on older versions.

* http://hotchemi.github.io/Android-Rate
* https://github.com/UrbanApps/Armchair
* https://github.com/arashpayan/appirater
* https://github.com/nicklockwood/iRate

## Documentation links for supported platforms

- [SKStoreReviewController](https://developer.apple.com/documentation/storekit/skstorereviewcontroller)

**Comment by adamfisher** [comment]
It's possible this could also be an exercise in creating binding libraries for the popular app rating packages but I have never had success in creating those. Pretty much at Xamarin's mercy in gaining access to 3rd party packages. Plus wouldn't be able to invoke this one time cross-platform in Xamarin.Forms so that is another reason it would be great to have this in Essentials so we only have to specify it one time.

**Comment by jamesmontemagno** [comment]
Since this isn't built in natively on all platforms and is only on iOS then this will not be under consideration.

I do have a plugin: https://github.com/jamesmontemagno/StoreReviewPlugin that opens the app store page and such and can request on iOS, however this locks things to google play for Android and isn't ideal for all developers.
