### ISSUE TITLE
Feature Request: App Information - ExitApplication

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#449]
Hi,

Please add **Exit Application** in the App Information to do below DependencyService

iOS:

```
using System;

namespace myApp.iOS
{
    public class CloseApplication : ICloseApplication
    {
        public void closeApplication()
        {
            Thread.CurrentThread.Abort();
        }
    }
}

```
Android:

using System;

```
namespace myApp.Droid
{
    public class CloseApplication : ICloseApplication
    {
        public void ExitApplication()
        {
            var activity = (Activity)Forms.Context;
            activity.FinishAffinity();
        }
    }
}

```

**Comment by acaliaro** [comment]
I think it already exists in Xamarin Forms 

https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.application.quit?view=xamarin-forms

**Comment by jrahma** [comment]
Error CS0120: An object reference is required for the non-static field, method, or property 'Application.Quit()' (CS0120)

**Comment by acaliaro** [comment]
I think you should open a bug in XF repo

**Comment by mattleibow** [comment]
I don't think this will be added. None of the mobile platforms really support this.

In your code, the iOS app is crashing. And the Android app is just closing the Activity. 

Current Forms code for all platforms gives a warning: "Platform doesn't implement QuitApp"
