### ISSUE TITLE
FAQ porting from Settings plugin for decimal values

### ISSUE THREAD

**Issue by Aumnia** [xamarin/Essentials#451]
### Description

Because Preferences does not support decimal when porting from the settings plugin just changing the datatype (say to float) will result in a ```java.lang.String cannot be cast to java.lang.Float``` exception. 

While it is probably a bad idea to change the datatype of a preference already stored on users phones the extra complication here is that the support for decimal was done by [storing the value as a string](https://github.com/jamesmontemagno/SettingsPlugin/blob/cebe39067b34be12db6a35ed743c9e1047d64ae1/src/Plugin.Settings/Settings.dotnet.cs#L59) (hence the exception).

**Comment by jamesmontemagno** [comment]
So, since I never should have supported decimals and store them as strings you can do this:

```
public decimal MyDecimal
{
   get 
  {
       var savedDecimal = Preferences.Get("mykey",  Convert.ToString(0, System.Globalization.CultureInfo.InvariantCulture));

       return Convert.ToDecimal(savedDecimal, CultureInfo.InvariantCulture)
   } 
   set { Preferences.Set("mykey", Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture)); }
}
```

If this isn't super important just give it a different key.
