### ISSUE TITLE
OnScreenMetricsChanged get called lots of times on Physical device

### ISSUE THREAD

**Issue by jaykainlabs** [xamarin/Essentials#453]
Bug report best practices: [Submitting Issues](SUBMITTING-ISSUES.md)

### Steps to Reproduce

1. Download the samples from Github
2. Run it on a physical Android Device
3. Device info page
4. OnScreenMetricsChanged keeps getting called

### Basic Information
I tested Android device only, not sure about iOS and UWP
- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
Do you have a repo project or code? I tested this out and is working fine for me.

**Comment by jamesmontemagno** [comment]
Got it, never mind i found it :) fixing up.
