### ISSUE TITLE
Device Information : Storage Info

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#454]
Hi,

Please add an option in Device to get the Device total space and free space.

Thanks,
Jassim

> VS bug [#735665](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735665)

**Comment by mattleibow** [comment]
I have not really looks at the implementation for this, but we need to make sure that each platform can do this first.

 - Can we distinguish between SD card (external, removable storage), external/non-system storage (embedded, but not the OS) and internal storage (the OS partition)? I know Android has multiple locations that may differ with permissions or other criteria.
 - Can we access the space used, free space, total space?

**Comment by craylward** [comment]
This would be very useful!

https://forums.xamarin.com/discussion/42727/working-with-disk-space-info-in-forms

**Comment by pictos** [comment]
@mattleibow it's possible. I made a simple test using dependency service and it's work fine in Android and UWP, as I don't haven't a Mac i don't testing in iOS, but is implemented. If you want i can implement this in Essentials.
Implementation:
https://github.com/pictos/Dependency

**Comment by Redth** [comment]
Would love someone from the community to make an API spec for this and figure out how to deal with the points @mattleibow pointed out (how to handle different storage devices and/or os partitions, etc).

**Comment by pictos** [comment]
@Redth i made a example implementation, using dependency service, to get free storage in device... I answer the questions in next post

https://github.com/pictos/Dependency (the project)

**Comment by pictos** [comment]
_Can we distinguish between SD card (external, removable storage), external/non-system storage (embedded, but not the OS) and internal storage (the OS partition)? I know Android has multiple locations that may differ with permissions or other criteria._

Yes, we can distinguish the external and internal storage, using the path of folder. In each plataform is like that:

**Android**

```csharp
var fullExternalStorage = Android.OS.Environment.ExternalStorageDirectory.TotalSpace; 
var freeExternalStorage = Android.OS.Environment.ExternalStorageDirectory.UsableSpace;

var fullInternalStorage = Android.OS.Environment.RootDirectory.TotalSpace;
var freeInternalStorage = Android.OS.Environment.RootDirectory.UsableSpace;
```

in Android we have "Android.OS.Environment.IsExternalStorageEmulated" and "Android.OS.Environment.IsExternalStorageRemovable".

With multiple locations we can use the StatFs, when we use a path.

(https://github.com/pictos/Dependency/blob/master/Dependency/Dependency.Android/Services/StorageAndroid.cs)

**iOS**

 We can get free space and total space, they are property of NSFileSystemAttributes. And consequently we were able to calculate the occupied space. If I'm not mistaken, the iOS devices don't have external storage.

```csharp
var applicationFolder = NSFileManager.DefaultManager.GetFileSystemAttributes(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData));
var freeSpace = applicationFolder.FreeSize;
var totalSpace = applicationFolder.Size;

```
(https://github.com/pictos/Dependency/blob/master/Dependency/Dependency.iOS/Services/StorageiOS.cs)

**UWP**

We can get free space and total space using the path and RetrieveProperties "System.FreeSpace" and "System.Capacity", respectively. 
For external storage we can use
```csharp
IReadOnlyList<StorageFolder> folders = await KnownFolders.RemovableDevices.GetFoldersAsync());

```
(https://github.com/pictos/Dependency/blob/master/Dependency/Dependency.UWP/Services/StorageUWP.cs)


 _Can we access the space used, free space, total space?_ 

Yes, we can access total space and free space... And spaceUsed = (total space) - (free space)

**Comment by pictos** [comment]
@mattleibow , before suggesting a spec for the API, I wonder if I've completely answered your questions?

And I ask. Do we want to get the storage information from all connected devices (USB, mobile, etc.) or just SD card and internal storage?

**Comment by pictos** [comment]
I would like to take this implementation. I think the good way is expose a methods, because in UWP this run asynchronously.

``` csharp
public  Task<float> GetFullSizeAsync() => PlataformGetFullSizeAsync();
public  Task<float>GetFreeSizeAsync() => PlataformGetFreeSizeAsync();
public  Task<float> GetUsedSizeAsync() => PlataformUsedSizeAsync();
```

Or we can use Tuples to return all info, like that 
``` csharp
public Task<(float total, float free, float used)> StorageInfo()=> PlataformStorageInfo();
```

**Comment by Mrnikbobjeff** [comment]
First of all you should use ulongs for drive size, as floats are not suited for this. ulong has a greater absolute value range than float and is returned e.g. on iOS, so this would definitely has to be a ulong. Secondly, I am really not in favor of using tuples for this. Such a bloated signature, and if you decide to add properties later on this only gets worse. 
Furthermore, I would like to discuss having Information returned about every given drive whether it is external or not as well as the free, full and total size for each drive. On iOS this would always yield one result, the integrated main drive. For UWP all bets are off how many external devices you can connect (though there will be a sane amount present for most systems), and on Android this would be true in theory but to be honest I don't believe there will be more that 1-2 external drives connected at any given time. We could also add extension methods which gets total available free space for your system by iterating over all present drives.
This is all available across our platforms so there should be no problem there, the links which @pictos provided containt the neccessary information. I would also consider adding an Id for each drive to be able to distinguish them if the need should arise.

**Comment by mattleibow** [comment]
We can always create a struct that has the drive info:

```csharp
struct StorageInfo {
    // the core values from the OS
    ulong TotalBytes;
    ulong FreeBytes;
    ulong UsedBytes;

    // helpers
    double FreeMegabytes => FreeBytes / 1024.0 / 1024.0;
    double FreeGigabytes => FreeBytes / 1024.0 / 1024.0 / 1024.0;

    double UsedPercentage => (double)UsedBytes / (double)TotalBytes;
    double FreePercentage => (double)FreeBytes / (double)TotalBytes;
}
```

**Comment by jamesmontemagno** [comment]
Closing, see https://github.com/xamarin/Essentials/pull/617#issuecomment-567559064
