### ISSUE TITLE
Geolocation GetLocationAsync response times on android

### ISSUE THREAD

**Issue by asfelicetti** [xamarin/Essentials#456]
I am utilizing the Geolocation class to get the current location of the device and I notice specifically on android that the response time can vary greatly, but for the most part is taking > 5 seconds. On iOS that response time is less than <2 seconds. I have tested using both physical and virtual devices on different networks and the results are consistent. I am not sure if this is a bug or not. I am invoking the Geolocation request as follows:

```
GeolocationRequest geolocation = new GeolocationRequest { DesiredAccuracy = GeolocationAccuracy.Medium };
var result = await Geolocation.GetLocationAsync(geolocation); 
```

I have also attempted to set a timeout which results in a quicker response time on Android but I am not sure why that would affect it. 

```
GeolocationRequest geolocation = new GeolocationRequest { DesiredAccuracy = GeolocationAccuracy.Medium, Timeout = TimeSpan.FromMilliseconds(500)};
var result = await Geolocation.GetLocationAsync(geolocation);

```

Also, what is the underlying API/service that this function is calling to retrieve locations, I don't see it documented?

- Version with issue: 0.9.1
- Platform Target Frameworks: <
  - iOS:  11.2
  - Android: 8.1

**Comment by Mrnikbobjeff** [comment]
Okay, to answer your questions: It uses the network and gps provider on android. A timeout returns the best result to date on amdroid by canceling the internal TaskCompletionSource. The shorter the timeout is the less accurate your location might be.

**Comment by asfelicetti** [comment]
Ok thanks that makes sense. How about when I utilize the GeoCoder.GeoCodeAddress function, how is it able to ascertain and get the geocoded street address? What API is that function utilizing to accomplish that?
