### ISSUE TITLE
Optimize All Structs

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#458]
See the updates to display metrics as this can be updated on all structs.

**Comment by Mrnikbobjeff** [comment]
I just wanted to clarify the post I made which I guess somehow promted this ticket. Structs can be compared fast via memcmp if they have no pointers in them (aka most of our structs). We do need to override the equals implementation for structs which contain primitive types with value equality but not memory equality. E.G.
`private struct SampleStruct
{
    public float SampleFloat;
}

private static void Main(string[] args)
{
    SampleStruct f, s;
    f.SampleFloat = 0.0f;
    s.SampleFloat = -0.0f;

    Console.WriteLine(f.Equals(s));  // prints False
    Console.WriteLine(0.0f == -0.0f); // prints True
}`

I do not know the value range of all values of our structs, but if values such as -0.0 are not even in the range of possible values we could also ellide implementing equality for those structs

**Comment by Mrnikbobjeff** [comment]
I made a list of all structs and what kind of change would be advisable:
AccelerometerData: implement IEquatable
CompassData: implement IEquatable
GyroscopeData: implement IEquatable
Locale: change to class, as all containing fields are reference types.
MagnetometerData: implement IEquatable
OrientationSensorData: implement IEquatable
ScreenMetrics: already implements IEquatable

**Comment by jamesmontemagno** [comment]
Basically just copy/paste from screenmetrics :) tehehe once that is in there.

**Comment by jamesmontemagno** [comment]
Should also create tests for all of them.

**Comment by Mrnikbobjeff** [comment]
I would do this real quick, but I would consider elliding the unit test on single value structs. float3 and quaternion both implement iEquatable, so just chain calling the equals method would basically test the used types equal method.

**Comment by Mrnikbobjeff** [comment]
@jamesmontemagno I will ellide the screenmetrics equals as it is already implemented in your branch

**Comment by Mrnikbobjeff** [comment]
I also added unit tests for all cases as you requested
