### ISSUE TITLE
Optimize MainThread

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#461]
Add a hot path to the MainThread.InvokeOnMainThread method to check if it is on main thread and if so do not schedule the work to run on the main thread. This should save some resources, as the check is cheaper than scheduling. As a pr requires an issue, this is the corresponding issue.

**Comment by jamesmontemagno** [comment]
This does this today :) https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/MainThread/MainThread.android.cs

**Comment by jamesmontemagno** [comment]
Ah, I see, missunderstood this. So the advantage here is that today it creates: a new TCS and that wouldn't be necessary if we did this. Re-opening :)
