### ISSUE TITLE
[Documentation] Xamarin.iOS DeviceDisplay.ScreenMetrics from Background

### ISSUE THREAD

**Issue by craylward** [xamarin/Essentials#463]
### Description
When calling DeviceDisplay.ScreenMetrics in Xamarin.iOS from a background thread, receive a UIKitThreadAccessException. 

`UIKit.UIKitThreadAccessException: UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread.`

Is this the expected behavior, or can the DevicDisplay.ScreenMetrics getter be made background safe?

**Comment by jamesmontemagno** [comment]
This is a limitation of iOS and when you can call these methods. We will add documentation for this. @conceptdev

**Comment by jamesmontemagno** [comment]
I think this should probably throw an exception if not on UI thread instead of a generic one from iOS. @Redth

**Comment by jamesmontemagno** [comment]
Added documentation :)
