### ISSUE TITLE
SecureStorage.ios.cs does not properly dispose of objects

### ISSUE THREAD

**Issue by robv8r** [xamarin/Essentials#464]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description

There are many cases in [SecureStorage.ios.cs](https://github.com/xamarin/Essentials/blob/0.9.1-preview/Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs) where disposable objects, such as NSData, SecRecord, NSString, etc., are not disposed.

### Expected Behavior

Prior to exiting a method, any disposable objects that are not returned to the caller should be disposed of.

### Actual Behavior

As mentioned, several types are never disposed in [SecureStorage.ios.cs](https://github.com/xamarin/Essentials/blob/0.9.1-preview/Xamarin.Essentials/SecureStorage/SecureStorage.ios.cs).

### Basic Information

- Version with issue: 0.9.1
- Last known good version: N/A
- IDE: Visual Studio 2017 Enterprise
- Platform Target Frameworks: 
  - iOS:  All

**Comment by robv8r** [comment]
While disposing of `IDisposable` objects is "best practice," in this case, the disposable types encapsulate unmanaged types and/or unsafe operations.  Because most public methods are static and return managed types, a developer using SecureStorage on iOS has no means to dispose of objects instantiated within the implementation.

From a performance perspective, disposing these objects should reduce Garbage Collection overhead.

**Comment by mattleibow** [comment]
Changes merged.
