### ISSUE TITLE
Feature Request: Certificate Pinning

### ISSUE THREAD

**Issue by craylward** [xamarin/Essentials#470]
### Description
Create an API for pinning certificates when using the Xamarin native HttpClient implementations as indicated here: https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/transport-layer-security?tabs=windows

There seems to be a huge gap in the Xamarin System.Net API now that TLS 1.2 is mandatory by many cloud providers. This request probably belongs for in the Xamarin Framework but I'd like to try offering it up here.

**Comment by jamesmontemagno** [comment]
For Cert Pinning there are a few approaches to this and can be accomplished in .net standard code such as: https://github.com/chrisriesgo/xamarin-cert-pinning/blob/master/PinCerts/PinCerts/Security/SslValidator.cs I will work with documentation to outline how to do something like this, but it doesn't fit into the Essentials API set.
