### ISSUE TITLE
Feature Request: Apple Pay and Google Pay

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#472]
Hi,

It will be great if you add an option for Xamarin Forms to utilize Apple Pay and Google Pay.

Thanks,
Jassim

**Comment by jamesmontemagno** [comment]
Thank you for your suggestion. We have a guiding principal of not adding any additional Google Play/Firebase specific APIs which would limit devices that the apps could be deployed on in addition to not handling any payment specific information.

**Comment by jrahma** [comment]
I hope to bring the in-App purchase because it's one of the important packages everyone use now and we are all using the inApBilling packages by @jamesmontemagno so hope it will come under Essentials soon.
