### ISSUE TITLE
GetCurrentLocation never returns when location services is disabled

### ISSUE THREAD

**Issue by KristofferBerge** [xamarin/Essentials#476]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
Android phones failes to fetch location sometimes. No errors are thrown and the awaited method call to GetLocationAsync() never returns.

When debugging the source code I find that the call to GetBestProvider in Geolocation.android.cs/PlatformLocationAsync method returns the passive location provider when the GPS provider is not available. This provider relies on other applications to fetch the location and does not actually initiate any request. I'm not a 100% sure that this is the cause, but relying on the passive provider to fetch could probably cause this if we are not running any other applications that are actively requesting locations themselves at the same time.

https://developer.android.com/reference/android/location/LocationManager#PASSIVE_PROVIDER

### Steps to Reproduce

1. Disable location services
2. Call Geolocation.GetLocationAsync()

### Expected Behavior
Should return that no location could be found

### Actual Behavior
Never returns

### Basic Information

- Version with issue: 0.10.0 and when building from source
- Platform Target Frameworks: Android
  - Android: Tested on 5.0 and 8.1

**Comment by asfelicetti** [comment]
I would also add that I am experiencing the same behavior on iOS, and not just Android. When I call Geolocation.GetLastKnownLocationAsync() It never returns and my application hangs when location services are disabled. Since i cant add a timeout to it like the GetLocationAsync I cant get around the issue.

**Comment by RyanBuzzInteractive** [comment]
@asfelicetti  just a thought, I was having similar issues on iOS and it turned out to be that I was accidentally launching the permission check from a background thread, but it has to be on the UI thread, otherwise exceptions or the initial location aren't propagated back to your code.

**Comment by jamesmontemagno** [comment]
I renamed it. I will be adding some checks for 0.11.0 to see if it is disabled on the device. 

Additionally, we wont check permissions if not on the UI in 0.11.0

**Comment by jamesmontemagno** [comment]
GetLastKnownLocation doesn't query any of the services and would work even if location services are off. Seems like @asfelicetti that maybe a permission issue perhaps. Can you give me your sample code how you are using it.

**Comment by asfelicetti** [comment]
@jamesmontemagno 

I have a viewmodel in my app and one of the functions when i am loading data calls the get lastknown location method to calculate miles from a list of addresses. I loop through the different addresses to calculate miles from the users current location. The first time the method is called after I disable location services it does indeed throw a permission exception as follow ({Xamarin.Essentials.PermissionException: LocationWhenInUse was not granted)}. Subsequent calls to the exact method doesnt throw the same permission exception it just hangs on the getlastlocationasync method. My info.plist has all of the requisite keys as shown below.


Here is the function
public async static Task<double> GetDistanceFromCurrentLocation(GeoCoordinate coordinate)
        {

            try
            {
                var currentLocation = await Geolocation.GetLastKnownLocationAsync();

                if (currentLocation != null)
                {
                    Xamarin.Essentials.Location officeLocation = new Xamarin.Essentials.Location(coordinate.Latitude, coordinate.Longitude);

                    var distance = Xamarin.Essentials.Location.CalculateDistance(currentLocation, officeLocation, DistanceUnits.Miles);

                    return Math.Round(distance, 1);
                }
            }
            catch (FeatureNotSupportedException fnsEx)
            {
                // Handle not supported on device exception
            }
            catch (PermissionException pEx)
            {
                // Handle permission exception
            }
            catch (Exception ex)
            {
                // Unable to get location
            }


            return 0;


        }


info.plist

	
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>This app needs access location when open.</string>

**Comment by jamesmontemagno** [comment]
Got it. I will see what is happening here.

**Comment by jamesmontemagno** [comment]
With my PR this will be fixed and we will throw a  "FeatureNotEnabledException"

**Comment by attrib75** [comment]
This still happens for me on Android for Xamarin Essentials GetLocationAsync never returns when I have location off.

**Comment by kerbooo** [comment]
This still happens for me on Android for Xamarin Essentials GetLocationAsync never returns when I have location off too.

**Comment by Bejasc** [comment]
Also still happening for me an Android.

**Comment by Bejasc** [comment]
@jamesmontemagno would you consider re-opening this for investigation?

**Comment by saiyamshah143** [comment]
+1

**Comment by jamesmontemagno** [comment]
So....

We do look at the providers available:
```
var locationManager = Platform.LocationManager;

            var enabledProviders = locationManager.GetProviders(true);
            var hasProviders = enabledProviders.Any(p => !ignoredProviders.Contains(p));

            if (!hasProviders)
                throw new FeatureNotEnabledException("Location services are not enabled on device.");
```

static readonly string[] ignoredProviders = new string[] { LocationManager.PassiveProvider, "local_database" };

So, the question is.... what providers are showing up on your device....

**Comment by shaks786** [comment]
Happening for me too on both iOS and Android

**Comment by Mrsevic** [comment]
I am still experiencing this issue.

**Comment by mattleibow** [comment]
What devices are you folks using? I can't seem to replicate. Mine immediately throws saying location is disabled.

**Comment by mattleibow** [comment]
In fact, is it possible to open a new issue with your code and more info on the devices? I think this particular issue was fixed and you might be experiencing a new one.

**Comment by Mrsevic** [comment]
Huawei P40 Lite and J5 2016. It is all hapenning with Zebra MC67 based on the feedback from one of our clients.

**Comment by FinnAlberts** [comment]
I'm also experiencing this issue using a Samsung Galaxy J7

**Comment by johng1492** [comment]
It's happening with me too. Essentials 1.6.1. Android 6.0, API Level 23.
