### ISSUE TITLE
andorid and ios and uwp files disappeared in the project after install .Net Core 2.1 SDK

### ISSUE THREAD

**Issue by yanshouwang** [xamarin/Essentials#477]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
andorid, ios and uwp files disappeared in the project after install .Net Core 2.1 SDK
and .Net Core 2.1 SDK is default installed after VS 2017 15.8 version...
this is very disgusting
i think this is common when compile with condition, but  i don't know how to solve this.
### Steps to Reproduce

1. install the .Net Core 2.1 SDK
2. Or update to VS 2017 15.8
3. After that all condition compiled files are gone...

### Expected Behavior
the files are still here.
### Actual Behavior
all these files are gone.
### Basic Information

- Version with issue: with .Net Core 2.1 SDK
- Last known good version: with .Net Core 2.0 SDK
- IDE: VS 2017 Community
- Platform Target Frameworks: 
  - iOS:  11.4
  - Android: 8.1
  - UWP:  16299
- Android Support Library Version: 27.0.2.1
- Nuget Packages: latest
- Affected Devices: none

**Comment by jamesmontemagno** [comment]
Please grab latest source code as there is a fix for this: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Xamarin.Essentials.csproj#L94

oren is working on putting this into his SDK extras
