### ISSUE TITLE
Bug: NetworkAccess shows connected when connected to WiFi with no internet

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#478]
Hi,

If you connect to a WiFi which has no internet connection, for example if the provider disconnected the internet services but you are connected to their router then the Connectivity.NetworkAccess will still show the status as Internet.

This is what I am trying when I connect to WiFi with no internet access:

`await DisplayAlert("Connection!", Convert.ToString(Connectivity.NetworkAccess), "Ok");
`

will return : **Intermet**

```
if (Connectivity.NetworkAccess == NetworkAccess.None)
{
    await DisplayAlert("Error!", "Not Connected", "Ok");
    return;
}
else
{
    await DisplayAlert("Success!", "I am Connected", "Ok");
}

```
will show Success message although no internet services in the WiFi.

Regards,
Jassim

**Comment by jamesmontemagno** [comment]
This is known and a limitation of available Android APIs: https://docs.microsoft.com/en-us/xamarin/essentials/connectivity?context=xamarin%2Fxamarin-forms&tabs=android#limitations
