### ISSUE TITLE
Determine and Request Location Permission

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#481]
Hi,

Does Xamarin Essentials provide a way to determine if the app has permission to access device location?

and if the user skipped or rejected the access at the initial step, is there any way to request the permission again so I have a button for example in my app for (Tap to Access Location) and then Xamarin Essentials will request the permission?

Thanks,
Jassim

**Comment by jrahma** [comment]
First part is [Duplicate](https://github.com/xamarin/Essentials/issues/77) but not sure about requesting the location permission

**Comment by jamesmontemagno** [comment]
Right now it will request the permission for you based on how the system handles it. On iOS a permission can only be requested once and on Android it can be multiple times. If the user declines you will get a permission denied exception.

You can use the Permission Plugin today to handle checking and requesting
https://github.com/jamesmontemagno/PermissionsPlugin

I will open a new proposal for permissions as they are a tad bit tricky.
