### ISSUE TITLE
Inconsistent SecureStorage Async/NotAsync APIs??

### ISSUE THREAD

**Issue by Omarkth** [xamarin/Essentials#494]
Hi,

The SecureStorage APIs are not consistent, we have GetAsync and SetAsync, but then Remove & RemoveAll (not RemoveAsync & RemoveAllAsync)... I understand the reason behind this is the UWP implementation, but I believe that you can unify the APIs in Xamarin.Essentials. If it was up to me, I would make them all synchronous (not Async) 😊.

**Comment by jamesmontemagno** [comment]
Thank you for the feedback. The API is designed based on implementation and when a platform needs things to be Async then the method becomes a Task. This is a design principal for the library.
