### ISSUE TITLE
Adding mocking support for testing

### ISSUE THREAD

**Issue by aloisdeniel** [xamarin/Essentials#496]
### Description

Today, because all APIs are static it is very painfull to test items depending on Xamarin.Essentials : as stated in the documentation, you have to create your own wrappers arounds built-in APIs.

I understood that you made the choice of static APIs for performance reason (no polymorphism resolution and so on), but the overhead of creating wrappers around is noticeable and performance are bad in the end.

So we should have a way to use Essentials APIs during tests.

### Proposal

We could add overridable behaviours into the shared library that wouldn't be included into the platform specific library, but allowing us to mock things during tests. This way end performance wouldn't be affected since this would only be present into shared library.

Here is an example implementation :

```csharp
namespace Xamarin.Essentials.Mocks
{
    public interface IAccelerometer
    {
        bool IsSupported { get; }

        void PlatformStart(SensorSpeed sensorSpeed);

        void PlatformStop();
    }

    public class Accelerometer : IAccelerometer
    {
        public static IAccelerometer Instance { get; set; } = new Accelerometer();

        public bool IsSupported => throw new NotImplementedInReferenceAssemblyException();

        public void PlatformStart(SensorSpeed sensorSpeed) => throw new NotImplementedInReferenceAssemblyException();

        public void PlatformStop() => throw new NotImplementedInReferenceAssemblyException();
    }
}

namespace Xamarin.Essentials
{
    public static partial class Accelerometer
    {
        internal static bool IsSupported => Mocks.Accelerometer.Instance.IsSupported;

        static void PlatformStart(SensorSpeed sensorSpeed) => Mocks.Accelerometer.Instance.PlatformStart(sensorSpeed);

        static void PlatformStop() => Mocks.Accelerometer.Instance.PlatformStop();
    }
}
```

This way, we could inject a custom `IAccelerometer` implementation into the `Accelerometer.Instance`static property to change global behaviour.

All the `Mocks` namespaces could eventually be automatically generated at build time from original APIs.

**Comment by jamesmontemagno** [comment]
Alois, thank you for well outlined issue and proposed example implementation. As mentioned in the [Wiki](https://github.com/xamarin/Essentials/wiki/FAQ-%7C-Essentials) and highlighted that we are not going to introduce any interfaces or mocks inside of this repo.  There are several reasons outlined and additional complexity, overhead, test, etc that would go into this. 

There is a community project that auto-generates the interfaces for you: https://github.com/rdavisau/essential-interfaces

We will continue to work with and listen to the community and monitor this, but for right now will mark as not on roadmap.

**Comment by thomasgalliker** [comment]
@jamesmontemagno, after years of developing Xamarin apps, I still ask myself how you're going to unit test static classes such as the current Accelerometer class? Some devs wrap these classes into their own class and expose an interface which can be used for mocking. My experience is that MOST devs don't take this extra effort and simply DO NOT TEST their code. This leads to low quality apps and lot more overall development effort.
