### ISSUE TITLE
Issue with Xamarin.Essentials: Connectivity - ConnectivityChanged event 

### ISSUE THREAD

**Issue by crazynitha** [xamarin/Essentials#498]
In my Xamarin forms application, I am using **Xamarin.Essentials: Connectivity  Plugin** for handling Network states( Offline & Online condition). In the app I need to display a banner in the application in case there is no network connectivity. For implementing this I am using the below event from **Xamarin.Essentials - Connectivity.**

` Connectivity.ConnectivityChanged += Current_ConnectivityChanged;`

**It is working / firing the events in all the usual cases like.**

Wifi connects / disconnects
3G/4G connects / disconnects

**But there is an issue with the below scenario (steps to reproduce).**

1. Open the application
2. Keep it idle for few hours.
3. Let the device to sleep.
4. After few hours it will call the ConnectivityChanged event with e.NetworkAccess != NetworkAccess.Internet (ie n/w state changes to not connected or no internet access)
5. Let’s the device awake.
6. Observe the ConnectivityChanged event in the app.
7. It won’t fire the connection changed event.
8. If you try to enable or disable the network at this point. It will start firing the event.

**What I have tried**

1. I have tried registering the event and un register it in OnStart ,OnSleep , OnResume events
2. Also, I tried the same in app level page life cycle events

Please find the sample app to reproduce the [issue](https://drive.google.com/open?id=1tscjTqJwi0bTdddlGTe4CUg9Wz5OIA4t)

Note: I have tried the same in **Xam.Plugin.Connectivity library** as well but the result is same. The issue persist in both case.

**Bug Information**

Version Number of Plugin: 0.10.0-preview
Device Tested On: Zebra TC25 Lite, Zebra TC50, Samsung Galaxy S6, Moto G5 Plus, Nexus 6
Simulator Tested On: Tested on real device
Version of VS: VS Professional 2017 with latest update
Version of Xamarin: 3.1.0.697729 (Forms)

**Comment by rkshnair** [comment]
I also noticed the same issue, the **ConnectivityChanged**  event will fire with **No Network**  when the device go to sleep( Only after sometime with sleep). But the same event is not firing back when the device wakes up. Tested and verified the same in Android devices. Yet test on iOS.

**Comment by jamesmontemagno** [comment]
Closing as you can find a deep analysis over here: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/161
