### ISSUE TITLE
How to retrieve permissions user's choice?

### ISSUE THREAD

**Issue by Goldstrike** [xamarin/Essentials#501]
Hello,

We use Xamarin.Essentials in a Xamarin.Forms app to manage Preferences and Geolocation, and this works well.

However I would like to know if there is a way to get the user's answer/choice the first time that the Geolocation is requested, as a pop-up is displayed to ask user if he authorizes the app to access to geolocation. 

**_But is there a way to get the user's answer? 
Or is it possible to get the permission that is specified in the setting for this app?_**

**Comment by jamesmontemagno** [comment]
As of right now we will throw an exception if the user does not have proper permissions and we prompt them when you first try to use the API. I will create a backlog item for Permissions API, however you can use  my Permission Plugin: https://github.com/jamesmontemagno/PermissionsPlugin to do this today.
