### ISSUE TITLE
App Information : Getting Published app's version from PlayStore/app

### ISSUE THREAD

**Issue by gsmental** [xamarin/Essentials#502]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
Thank you for the suggestion, however any APIs that rely specifically on external services are not eligible for Essentials. In this case it is possible to release apps in other app stores (especially on Android) and there are no specific built in APIs for this.
