### ISSUE TITLE
App Information : Getting Published app's version from PlayStore/AppStore/WindowsStore

### ISSUE THREAD

**Issue by gsmental** [xamarin/Essentials#503]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

**Comment by jamesmontemagno** [comment]
Thank you for the suggestion, however any APIs that rely specifically on external services are not eligible for Essentials. In this case it is possible to release apps in other app stores (especially on Android) and there are no specific built in APIs for this
