### ISSUE TITLE
 Taking geolocation sometimes long on Android

### ISSUE THREAD

**Issue by Moltroon** [xamarin/Essentials#506]
### Description
On Android (Huawei P Smart), geolocation can take 0.5 seconds and sometimes it takes 5 seconds for a Lowest demand. Do you have an explanation for this?

### Steps to Reproduce

1. Demand on Android the geolocation

### Expected Behavior
Taking geolocation in 0.5 seconds.

### Actual Behavior
Time of geolocalization oscillating between 0.5 seconds and 5 seconds.

### Basic Information

- Version with issue: **0.10.0-preview**
- Last known good version: **I don't know**
- IDE: **Visual Studio for MAC**
- Platform Target Frameworks:
  - iOS:  **8 working good**
  - Android: **7.1**
- Android Support Library Version: **27.0.2.1**
- Nuget Packages:
  - **PCLStorage**
  - **CurrentActivity**
  - **Xamarin.Forms**
  - **Xamarin.Forms.Maps**
- Affected Devices: **Huawei P Smart**

### Reproduction Link
await Geolocation.GetLocationAsync(new GeolocationRequest(GeolocationAccuracy.Lowest, new TimeSpan(0, 0, 10)))

**Comment by jamesmontemagno** [comment]
Yes, on Android it is highly possible for geolocation to take a good amount of time based on the device. We use the built in APIs (not the Google Play Fused APIs). It is recommended to check the cached location first and then query the location from the device.

We just make the request and wait for it to return.
