### ISSUE TITLE
GeoLocation Calculate Distance 

### ISSUE THREAD

**Issue by asfelicetti** [xamarin/Essentials#507]
I wanted to propose and see if there could be a way to get a more accurate "CalculateDistance". Currently it is point to point per documentation. However is there a way it could better utilize the native maps api and get a better distance estimate. For example when I open Apple Maps from my xamarin forms app with the current location and destination's pre-populated into the map application it provides a default distance using the best calculated route. It would be nice if that could be available from within my forms app without having to navigate away from it.

**Comment by jamesmontemagno** [comment]
In this instance I believe it would return the same thing: https://developer.apple.com/documentation/corelocation/cllocation/1423689-distancefromlocation?language=objc

You would also want it to be consistent between each platform, which is what we offer today. I do not believe here is a built in API on all platforms that gives you the distance with directions.

**Comment by mattleibow** [comment]
This might be a feature for a maps/directions api: provide two (or more) geo-points and return a list of route options.

**Comment by Redth** [comment]
Agreed.  Since it's not natively available, this isn't a good fit for Essentials.  We're not going to bring in an additional dependency for this one feature.
