### ISSUE TITLE
Evaluate throwing if Window is null on UWP

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#510]
Should we be throwing here? https://github.com/xamarin/Essentials/blob/f56c8baf787bbc14246308fb90ed2ba85b6831ba/Xamarin.Essentials/MainThread/MainThread.uwp.cs#L16

 - [x] Check if there is a main window, if not run on current thread
 - [x] Audit usage of any Platform main thread usage and change to shared

**Comment by Redth** [comment]
We should instead check if there IS a main window, and if there isn't we are already on the 'main' thread and can just execute on the current thread.

**Comment by tipa** [comment]
It can still crash here: https://github.com/xamarin/Essentials/blob/b018723477f848b108cb9a67adecb3608d0ab686/Xamarin.Essentials/MainThread/MainThread.uwp.cs#L16
For example, when execute too early, before the main window has been created, for example in the App constructor
![image](https://user-images.githubusercontent.com/2863198/58587291-4d2ee880-825d-11e9-9065-b1fb74446e52.png)

**Comment by jamesmontemagno** [comment]
Do you want to do a PR? or do you want me to?

**Comment by tipa** [comment]
I am failing to get the project running without errors on my machine :(
What I would do is wrap line 16 in a try-catch and return `true` if the `InvalidOperationException` is thrown

**Comment by jamesmontemagno** [comment]
No worries (We recommend VS 2017 as there is a regression on VS 2019 16.1 right now for the multi-targeting stuff we are using).  I put in a PR #803 to fix it up.

**Comment by tipa** [comment]
I think if the issue hasn't been fixed with your PR, as the `InvalidOperationException` can still be thrown, which happens when you access the MainView property before it has been created (try call `MainThread.BeginInvokeOnMainThread(action)` in your apps constructor to reproduce)

**Comment by tipa** [comment]
@jamesmontemagno should I open a new issue regarding this problem?

**Comment by jamesmontemagno** [comment]
It should never throw as we always call IsMainThread and if CoreWindow is null then we return true so it should just fire. 

If you can open with a repro that would be good. Or send down a PR :)

**Comment by tipa** [comment]
Opened a new issue here: https://github.com/xamarin/Essentials/issues/1020
