### ISSUE TITLE
ConnectivityManager.ConnectivityAction Deprecated

### ISSUE THREAD

**Issue by craylward** [xamarin/Essentials#512]
The ConnectivityManager.ConnectivityAction constant has been deprecated in Android API 28. 

[https://developer.android.com/reference/android/net/ConnectivityManager#CONNECTIVITY_ACTION](https://developer.android.com/reference/android/net/ConnectivityManager#CONNECTIVITY_ACTION)

> VS bug [#735657](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735657)

**Comment by cjlotz** [comment]
Hello.  Is there any further progress planned on this?  I see the current implementation hides the compiler warnings that the API has been deprecated and I would like to understand if this actually still works on API 29 and greater.  Can I safely use the current Essentials Network API for Android now that all apps need to at least be targeting API >= 29 to get into the Play Store?

**Comment by jamesmontemagno** [comment]
Yup, everything still works fine.

**Comment by jamesmontemagno** [comment]
I'm going to do a spike on the new stuff as well. The old stuff works and continues to work though. Deprecated is still around for a very long time usually :)
