### ISSUE TITLE
Can we think about Xamarin.Essentials.Droid/Xamarin.Essentials.IOs etc

### ISSUE THREAD

**Issue by gsmental** [xamarin/Essentials#513]
there are thousand of libraries which are providing so many features to specific OSs, but problem is that these libraries takes so many MBs in space, i think we can work on UI specific libraries which will be depend on Xamarin.Essentials like PDF view, File download with progressbar.

**Comment by jamesmontemagno** [comment]
This is not the current goal for Xamarin.Essentials as it is not focused on user interface specific APIs and is for abstracting out platform native APIs of the device.
