### ISSUE TITLE
Geolocation.GetLastKnownLocationAsync() returns null

### ISSUE THREAD

**Issue by ribas1a3** [xamarin/Essentials#519]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
Geolocation.GetLastKnownLocationAsync() returns null when the location service was turned off and turned on.
### Steps to Reproduce

1. Use Geolocation.GetLastKnownLocationAsync() api in your code.
2. Make sure your location service is turned off in the settings.
3. Geolocation.GetLastKnownLocationAsync() gives exception as intended and asks to turn on the "location service".
4. Go back to settings and turn on the location services.
5. Turn calling the Geolocation.GetLastKnownLocationAsync() API again, which returns null.

### Expected Behaviour
1. Geolocation.GetLastKnownLocationAsync() should work once the location permission is granted
### Actual Behaviour
1. Geolocation.GetLastKnownLocationAsync() returns null even when the location permission is turned on.
### Basic Information

- Version with issue:  0.10.0-preview
- Last known good version:
- IDE: VS 2017
- Platform Target Frameworks: 
  - Android: 8.0

**Comment by jamesmontemagno** [comment]
It is completely possible that it returns null and you should check against it as the provider may have cleared it out. This is working as intended.

**Comment by Tommigun1980** [comment]
> It is completely possible that it returns null and you should check against it as the provider may have cleared it out. This is working as intended.

How are you supposed to get a location then?

**Comment by mattleibow** [comment]
You can also just get the location using `GetLocationAsync`. That will force the GPS to get the location.

**Comment by Tommigun1980** [comment]
> You can also just get the location using `GetLocationAsync`. That will force the GPS to get the location.

Thanks. It is still extremely unclear to me what exactly the expected behaviour is so I posted this in the documentation issues section for Geolocation:
https://github.com/MicrosoftDocs/xamarin-docs/issues/2828
