### ISSUE TITLE
Recommendation for Xamarin.Essentials with Unit Testing

### ISSUE THREAD

**Issue by keannan5390** [xamarin/Essentials#520]
This is more of a question rather than a bug report.

I started using Xamarin.Essentials in a new app, I've historically used the various plugins for cross platforms I've needed. So very excited for Xamarin.Essentials and the consolidated location for all these cross platform features.

However, one nice thing with the older plugin model provided was each feature being wrapped in an interface. This meant that any code (specifically view models) interacting with the plugins could easily be unit tested by providing a mock for the plugin. 

Today, as I was adding tests for my view models I realized that it won't be as simple to create unit tests for code that depends on Xamarin.Essentials. The test assembly encounters the following exception (I know this is by design).
```Xamarin.Essentials.NotImplementedInReferenceAssemblyException : This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.```

Is the recommendation here to wrap all of my Xamarin.Essentials interactions in my own interfaces? I was hoping to be able to avoid that if possible.

**Comment by Shan11812** [comment]
May be [this](https://essential-interfaces.azurewebsites.net/) can help

**Comment by jamesmontemagno** [comment]
We have guidance on our wiki: https://github.com/xamarin/Essentials/wiki/FAQ-%7C-Essentials#where-are-the-interfaces

**Comment by follesoe** [comment]
@jamesmontemagno Agreed to the considerations and recommendations written in guidance. I was looking for a way to check if the code was executing on an unsupported platform, but even that call is unsupported. So a few properties to check if something is available would be good.

I.e I was trying to get a cache/temp directory in a simple C# class, that I wanted to do some testing against:

```csharp
CacheDirectory = (DeviceInfo.Platform == DeviceInfo.Platforms.Unsupported) ? 
    Path.GetTempPath() : FileSystem.CacheDirectory;
```

But that is not possible as even the `DeviceInfo` is not available outside a device context.

**Comment by jamesmontemagno** [comment]
I opened a new issue for this: https://github.com/xamarin/Essentials/issues/619 

I think would be a good idea.

**Comment by jamesmontemagno** [comment]
@brandwooddixon please read through: https://github.com/xamarin/Essentials/wiki/FAQ-%7C-Essentials#where-are-the-interfaces

You can also use http://essential-interfaces.azurewebsites.net/ to generate interfaces for you, which is a community project.
