### ISSUE TITLE
Secure Storage: android.security.KeyStoreException on Android 6.0

### ISSUE THREAD

**Issue by Mirksar** [xamarin/Essentials#521]
I have a Xamarin.Forms Android App in the Play Store. I am receiving reports of this error in AppCenter. The error is only happening in Android 6.0. My call to SecureStorage.GetAsync it's inside a try/catch block. The app is using Xamarin.Essentials 0.8

 The stack trace that I'm getting from AppCenter is the following:

`android.security.KeyStoreException: -53212
android.security.KeyStore.getKeyStoreException(KeyStore.java:632)
android.security.KeyStore.getInvalidKeyException(KeyStore.java:712)
android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:53)
android.security.keystore.KeyStoreCryptoOperationUtils.getExceptionForCipherInit(KeyStoreCryptoOperationUtils.java:89)
android.security.keystore.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:263)
android.security.keystore.AndroidKeyStoreCipherSpiBase.engineInit(AndroidKeyStoreCipherSpiBase.java:147)
javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:611)
javax.crypto.Cipher.tryCombinations(Cipher.java:535)
javax.crypto.Cipher.getSpi(Cipher.java:440)
javax.crypto.Cipher.init(Cipher.java:912)
javax.crypto.Cipher.init(Cipher.java:862)
mono.java.lang.RunnableImplementor.n_run(Native Method)
mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
android.os.Handler.handleCallback(Handler.java:743)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:150)
android.app.ActivityThread.main(ActivityThread.java:5621)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)`

**Comment by jamesmontemagno** [comment]
Please update to 0.10.0 as this was already fixed.
