### ISSUE TITLE
Location.TimestampUtc name conflicts with type

### ISSUE THREAD

**Issue by breyed** [xamarin/Essentials#522]
The name of the property `Location.TimestampUtc` is incompatible with its type `DateTimeOffset`. A time zone offset represents a point in time relative to UTC, whereas the name `TimestampUtc` implies the value is in UTC. The property should be renamed `Timestamp` or its type should be changed to `DateTime`.

**Comment by jamesmontemagno** [comment]
I think that it should be changed to DateTime as it is representing a UTC value. @Redth do you remember why we created it as a DateTimeOffset?
