### ISSUE TITLE
Null Exception for AppInfo.Name on iOS

### ISSUE THREAD

**Issue by stoff99** [xamarin/Essentials#523]
Hello @All,

Tested with iOS 12 Simulator and iOS 10 on iPhone 7.

The problem is the function GetBundleValue in AppInfo.ios.cs.
static string GetBundleValue(string key)
           => NSBundle.MainBundle.ObjectForInfoDictionary(key).ToString();

The call:
static string PlatformGetName() => GetBundleValue("CFBundleDisplayName") ?? GetBundleValue("CFBundleName");

First it checks with "CFBundleDisplayName" but this is not set as standard. So the NSBundle.MainBundle.ObjectForInfoDictionary(key) return null. So it came to an NullObjectReference because of .ToString();

Please fix this. Currently i manually implemented the CFBundleDisplayName tag in my Info.plist.

Thx Stefan

**Comment by mattleibow** [comment]
Thanks for reporting this. I will have a look at a fix.

**Comment by stoff99** [comment]
Hi @mattleibow,

thx for the fix. How often do you publish an NuGet update to rollout the bug fixes?
