### ISSUE TITLE
IsRemoteReachable method call isn't public to be used by Network framework

### ISSUE THREAD

**Issue by biozal** [xamarin/Essentials#524]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Steps to Reproduce

1. Current Xam Plugin Connectivity has support for IsRemoteReachable method.
2. Bring in Xamarin Essentials nuget and method isn't available.

### Expected Behavior
The ability to check if a network host is available before calling it.

### Actual Behavior
This functionality is missing.

### Basic Information
Trying to convert over from the Xam.Plugin.Connectivity plugin to Xamarin Essentials

- Version with issue:
- Last known good version:
- IDE: VS Mac/PC
- Platform Target Frameworks: 
  - iOS:  12
  - Android: 9

**Comment by gtbuchanan** [comment]
This was an intentional omission. See #334, #360, and #371.

**Comment by jamesmontemagno** [comment]
Thanks for the suggestion, however we have decided not to add this API. @gtbuchanan has documented the issues here.
