### ISSUE TITLE
Xamarin Essentials project structure.

### ISSUE THREAD

**Issue by ysmoradi** [xamarin/Essentials#527]
This issue is based on https://github.com/xamarin/Essentials/issues/338

Xamarin Essentials is a library which has some characteristics **different than other libraries.**

A library like Json.NET can work across all .NET implementations (.NET/.NET Core/Mono) on all platforms (Windows/Mac/Linux/Android/iOS/WASM/Tizen) with the single code base, because it's not dependent on any native feature of any OS.

On the other hand, a library like Xamarin.Forms.Platform.GTP is intended to work on GTK# projects, so it's target is obviously clear and nobody installs that in a Tizen project for example!

It's feasible for Xamarin.Essentials to work in following scenarios:

- iOS (Mono)
- Android (Mono)
- UWP (Windows 10) (.NET Core)
- Win Forms (Windows 7.1+) (.NET)
- WPF (Windows 7.1+) (.NET/.NET Core 3)
- GTK# (Windows/Mac/Linux) (.NET/.NET Core/Mono)
- Console app (Windows/Mac/Linux) (.NET/.NET Core/Mono)
- Web Assembly (Mono)
- Tizen (.NET Core)
- MacOS (Mono)

But we can't develop Xamarin.Essentials with a single code base, because of using native platform features. So, we've Browser.android | Browser.iOS | Browser.uwp in [Browser implementation of Xamarin essentials](https://github.com/xamarin/Essentials/tree/master/Xamarin.Essentials/Browser).

If we decide to open the door for WPF/Console/WinForms/GTK#/WASM/Tizen/Mac in the future, we've to think about the naming of new implementations.

Example for Browser:

If we use Browser.Windows, it would be useful for WPF/WinForms/Console app on Windows only.
But if we use Browser.GTK, it should work everywhere GTK# works.

The NuGet package is another problem. How can we sheep these stuff to our lovely C# developers? What about msbuild/csproj configurations?

So, let's do something for xamarin essentil's future structure! (: 

@jamesmontemagno @prashantvc @mattleibow

**Comment by jamesmontemagno** [comment]
Thanks for the input here on the structure. We are focused on iOS/Android/UWP for the time being and if we decide to add another platform the multi-targeting will handle these scenarios like other plugins available today.

**Comment by ysmoradi** [comment]
YW :) I'm stay tuned!
