### ISSUE TITLE
Geolocation Position always null

### ISSUE THREAD

**Issue by StargazerNC** [xamarin/Essentials#533]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
I have a Xamarin.Forms app where I'm using Geolocation API to get positions on tap of a button. It takes quite sometime (10/20 seconds) on certain devices and but fails to obtain a position, i.e. the Position class is always null.
This only happens on real devices, though, which I find odd, not on the Android Emulator.  I didn't have this issue before when using GeoLocator Plugin by @jamesmontemagno.

### Steps to Reproduce

1. Open the app
2. Tap the Get Location button

### Expected Behavior
The Position representing my local should be fetched.

### Actual Behavior
No Position representing my local should is fetched, Position class is always null.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 15.8.5
- Platform Target Frameworks: 
  - Android: 8.1 API Level 27 - Oreo (minimum 5.0 API Level 21 - Lollipop) 
- Nuget Packages:
- Affected Devices:

### Screenshots
N/A

### Reproduction Link

I have a GitHub project that reproduces the issue. [Link here](https://github.com/StargazerNC/GeoLocationTest)

**Comment by jamesmontemagno** [comment]
Looking at your code you are requesting both Best and Lowest. 

Best on Android can take a serious amount of time -> 30-120 seconds and I would not recommend this as it tries to use GPS only to triangulate. Medium is a good choice as it uses a combination.

I tested your code on my several devices here locally and everything returned pretty quick in about 5-7 seconds for all 3 calls.

Calling back to back geolocation calls can slow down additional calls based on the android device and what it is spinning up and down. If I removed one of your calls to GetLocationAsync then it sped up the return.

GetLastKnown returned instantly for me. Best took a few seconds and same with Lowest. 

For me it is working as intended.
