### ISSUE TITLE
Text to Speech - 2 Way App Operation

### ISSUE THREAD

**Issue by TonyLugg** [xamarin/Essentials#537]
Is there a way to use Text to Speech similar to how texting is done when the phone is connected via Bluetooth?  Perhaps when a push notification is received, it is read out to the driver and then asks for a reply, which the driver provides via voice and it is converted to text and sent to the app for processing, similar to tapping a notification.

**Comment by jamesmontemagno** [comment]
This sounds like you could do it. You would have to handle the notification response and then just do the text to speed api from the receiving part where necessary. As long as you know the text you want to speak back.
