### ISSUE TITLE
UWP: Value can not be null exeption in Secure Storage

### ISSUE THREAD

**Issue by Agredo** [xamarin/Essentials#542]
If a Key does not exists or the Value is null it is not possible to check if the key is null or empty! 

The UWP app crashes in line 
 if (await ecureStorage.GetAsync("UserName") != null )
{
}

or in line like

var UserName = await ecureStorage.GetAsync("UserName");
if(!string.IsNullOrEmpty(UserName))
{
}

This works perfectly on Android and iOS. 

Workaround: Using [CrossSecureStorage ](https://github.com/sameerkapps/SecureStorage)Plugin

**Comment by jamesmontemagno** [comment]
I can not reproduce this at all. It is working great for me and this is in our test suite today.

**Comment by jamesmontemagno** [comment]
[App33.zip](https://github.com/xamarin/Essentials/files/2461371/App33.zip)
See sample here
