### ISSUE TITLE
UWP: SecureStorage.Remove("xxx") does not work  

### ISSUE THREAD

**Issue by Agredo** [xamarin/Essentials#543]
Removing Key Values in UWP does not work. Android and iOS works perfectly using SecureStorage.Remove("xxx");

The key still exists in UWP (In UWP a empty Key can not be checked [UWP: Value can not be null exeption in Secure Storage #542](https://github.com/xamarin/Essentials/issues/542)). This works for Android and iOS perfectly.

if (CrossSecureStorage.Current.HasKey("xxx"))
{
                MainPage = new ExapmlePage();
}

Workaround: Workaround: Using [CrossSecureStorage](https://github.com/sameerkapps/SecureStorage) Plugin

**Comment by jamesmontemagno** [comment]
I can not reproduce this at all. It is working great for me and this is in our test suite today.

**Comment by jamesmontemagno** [comment]
[App33.zip](https://github.com/xamarin/Essentials/files/2461371/App33.zip)
See sample here
