### ISSUE TITLE
Support continuous location updates

### ISSUE THREAD

**Issue by cmeeren** [xamarin/Essentials#544]
In the [documentation](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation), there seems to be no way to get a continuously updated location (similar to how one can get a continuously updated compass heading). I'd like to get away from my custom geolocation implementation and use Xamarin Essentials, but this continuous location updates is a requirement for me. Is this currently possible? If not, could it be implemented?

**Comment by jamesmontemagno** [comment]
Duplicate of #290
