### ISSUE TITLE
Connectivity

### ISSUE THREAD

**Issue by Smoke1987** [xamarin/Essentials#545]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
To work correctly, Xamarin.Essentials :: Connectivity on the Android platform requires the permission "ACCESS_NETWORK_STATE", "ACCESS_WIFI_STATE", "INTERNET"

### Steps to Reproduce

1. Follow all steps in [Get Started with Xamarin.Essentials](https://docs.microsoft.com/en-us/xamarin/essentials/get-started?tabs=windows%2Candroid)
2. On device with android API-level 21 connect to wi-fi without `Cellular` data
3. Try to get `Connectivity.NetworkAccess` - it's `none`
4. Try to get `Connectivity.Profiles` - it's count = 0

### Expected Behavior
Expected behavior as described in the documentation (meaning the user guide in the installation and configuration of the library)

### Actual Behavior
---

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by Smoke1987** [comment]
It is unfortunate that the documentation, which is the only source of information about the package, from the very first lines begins to misinform the library user ....

**Comment by jamesmontemagno** [comment]
On the Android tab we have setup information: https://docs.microsoft.com/en-us/xamarin/essentials/connectivity?tabs=android

You only need to have ACCESS_NETWORK_STATE  set

The other ones are not required as documented.
