### ISSUE TITLE
SecureStorage.GetAsync weird behaviour

### ISSUE THREAD

**Issue by domagojmedo** [xamarin/Essentials#547]
### Description

Sometimes when calling SecureStorage get key an exception is thrown, as far as I can see it only happens if you call it from constructor 

> 
> Java.Security.GeneralSecurityException: Exception of type 'Java.Security.GeneralSecurityException' was thrown.
>   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <e3004c4e15044c808afc614b576e5033>:0
>   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <e3004c4e15044c808afc614b576e5033>:0
>   at Javax.Crypto.Cipher.DoFinal (System.Byte[] input, System.Int32 inputOffset, System.Int32 inputLen) [0x00052] in <371881fc6a834920894f94cc1ced14fc>:0
>   at Xamarin.Essentials.AndroidKeyStore.Decrypt (System.Byte[] data) [0x0005f] in <ae7ec1005e9b4a7fb1b9a625bb121d27>:0
>   at Xamarin.Essentials.SecureStorage.PlatformGetAsync (System.String key) [0x0003c] in <ae7ec1005e9b4a7fb1b9a625bb121d27>:0
>   at Xamarin.Essentials.SecureStorage.GetAsync (System.String key) [0x00013] in <ae7ec1005e9b4a7fb1b9a625bb121d27>:0
>   at mynamespace.Mobile.Common.Helpers.ApplicationData.GetDataSecure[T] (System.String key) [0x00000] in <8ba8b9033ea146f5acfbeed846c2c769>:0
>   at mynamespace.Mobile.Common.Helpers.ApplicationData.get_AccessToken () [0x00000] in <8ba8b9033ea146f5acfbeed846c2c769>:0
>   at mynamespace.Mobile.Common.mynamespaceService+<>c.<.cctor>b__57_0 () [0x00005] in <8ba8b9033ea146f5acfbeed846c2c769>:0
>   at System.Lazy`1[T].CreateValue () [0x00081] in <8b14e7319e93402a9bb2fdf1ecca245e>:0
>   at System.Lazy`1[T].LazyInitValue () [0x00080] in <8b14e7319e93402a9bb2fdf1ecca245e>:0
>   at System.Lazy`1[T].get_Value () [0x0003a] in <8b14e7319e93402a9bb2fdf1ecca245e>:0
>   at mynamespace.Mobile.Common.mynamespaceService.get_Instance () [0x00000] in <8ba8b9033ea146f5acfbeed846c2c769>:0
>   at mynamespace.Mobile.Droid.Activities.LoginActivity+<Login>d__18.MoveNext () [0x00056] in <7b28c55386da4444928a5c740a828a55>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <8b14e7319e93402a9bb2fdf1ecca245e>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <8b14e7319e93402a9bb2fdf1ecca245e>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <8b14e7319e93402a9bb2fdf1ecca245e>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <8b14e7319e93402a9bb2fdf1ecca245e>:0
>   at mynamespace.Mobile.Droid.Activities.LoginActivity+<LoginWithPin>d__16.MoveNext () [0x0008c] in <7b28c55386da4444928a5c740a828a55>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <8b14e7319e93402a9bb2fdf1ecca245e>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <8b14e7319e93402a9bb2fdf1ecca245e>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <8b14e7319e93402a9bb2fdf1ecca245e>:0
>   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <8b14e7319e93402a9bb2fdf1ecca245e>:0
>   at mynamespace.Mobile.Droid.Activities.LoginActivity+<InputChanged>d__24.MoveNext () [0x000f9] in <7b28c55386da4444928a5c740a828a55>:0
>   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <8b14e7319e93402a9bb2fdf1ecca245e>:0
>   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <371881fc6a834920894f94cc1ced14fc>:0
>   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <371881fc6a834920894f94cc1ced14fc>:0
>   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <371881fc6a834920894f94cc1ced14fc>:0
>   at (wrapper dynamic-method) System.Object.42(intptr,intptr)
>   at javax.crypto.AEADBadTagException
>   at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
>   at javax.crypto.Cipher.doFinal(Cipher.java:1794)
>   at Caused by: android.security.KeyStoreException: Signature/MAC verification failed
>   at android.security.KeyStore.getKeyStoreException(KeyStore.java:1137)
>   at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
>   at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:373)
>   at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
>   at ... 1 more
> --- End of inner exception stack trace ---
>   Java.Lang.Exception: Signature/MAC verification failed
>     at android.security.KeyStoreException: Signature/MAC verification failed
>     at android.security.KeyStore.getKeyStoreException(KeyStore.java:1137)
>     at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
>     at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:373)
>     at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
>     at javax.crypto.Cipher.doFinal(Cipher.java:1794)

### Steps to Reproduce

I can reliably reproduce it only when deploy trough app store, if I deploy from VS in debug or release it all works. Also when deployed it works on most phone, but I had issues on Samsung Galayx S7, S7 mini and S9

### Basic Information

- Version with issue: 0.10.0-preview
- IDE: VS 2017
- Platform Target Frameworks:
  - Android: 8.1

Not sure what else to report/say about the bug, I'm not even sure if it's an Essentials bug. It's just really weird that it happens on some devices after installing from app store

**Comment by jamesmontemagno** [comment]
This has been solved: https://github.com/xamarin/Essentials/issues/448

New release soon.

**Comment by domagojmedo** [comment]
@jamesmontemagno any ETA on 0.11.0?

**Comment by jamesmontemagno** [comment]
Trying today :)

The work around is to try/catch this exception and then remove the key.

This is because when you remove the app from your phone auto backup kicks in. You can turn it off selectively: https://github.com/xamarin/Essentials/pull/540/files which should also work.
