### ISSUE TITLE
Xamarin.Essentials (0.11.0-preview) with Prism Xamarin.Forms 

### ISSUE THREAD

**Issue by mail2mhossain** [xamarin/Essentials#548]
Description
Installation failed for Xamarin.android 

ERROR:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	
Version conflict detected for Xamarin.Android.Support.Compat. Install/reference 
Xamarin.Android.Support.Compat 27.0.2.1 directly to project PgcbApp.Android to resolve this issue. 
 PgcbApp.Android -> Xamarin.Essentials 0.11.0-preview -> Xamarin.Android.Support.CustomTabs 27.0.2.1 -> Xamarin.Android.Support.Compat (= 27.0.2.1) 
 PgcbApp.Android -> Xamarin.Android.Support.Design 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2).	PgcbApp.Android	F:\PGCB\src\PgcbApp\PgcbApp\PgcbApp.Android\PgcbApp.Android.csproj	1

**Comment by jamesmontemagno** [comment]
Please see: https://docs.microsoft.com/en-us/xamarin/essentials/troubleshooting?context=xamarin/xamarin-forms

You will need to ensure your support libraries are upgraded and installed first for 27.0.2.1
