### ISSUE TITLE
Geoloation Library (location.TimeStampUTC has changed to TimeStamp), also 

### ISSUE THREAD

**Issue by minahenin** [xamarin/Essentials#549]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
after updating from 0.10.0 to 0.11.0, I noticed that Location.TimeStampUTC was no longer available and was replaced with Location.TimeStamp

and after I changed it to TimeStamp, I started to get the below error

System.MissingMethodException: System.DateTimeOffset Xamarin.Essentials.Location.get_Timestamp()

### Steps to Reproduce

1. Upgrade to the latest library and try to get location.

### Basic Information

- Version with issue: 0.11.0
- Last known good version: 0.10.0
- IDE: VS 2017 Enterprise 
- Platform Target Frameworks: 
  - Android: 4.4.2

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
This is correct, we have changed this API to TimeStamp, it returns the same value. See: https://github.com/xamarin/Essentials/issues/522

Ensure that ALL of your nugets are updated to the correct version and you did a full clean/rebuild.
