### ISSUE TITLE
Xamarin Live System.ValueTuple.

### ISSUE THREAD

**Issue by eelledge1** [xamarin/Essentials#550]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
When using Xamarin Live for Debugging, Andriod will throw an uncaught error related to System.ValueTuple.
### Steps to Reproduce
1.  Follow all steps for Android setup
2.  Copy & Paste the sample code provided in the documentation.
3. Run the code with Xamarin Live.

### Expected Behavior
You should see the current Latitude & Longitude in the Console.
### Actual Behavior
Uncaught Error
System.ValueTuple
### Basic Information
This is happening on my Gaxaly Note 8 API 26.

When I plug in directly with the USB and build. There is no problem.
- Version with issue: Android API 26 | Xamarin.Essentials v0.11.0-preview
- Last known good version:
- IDE: Visual Studio 2017 Pro
- Platform Target Frameworks: 
   - Android: Android 8.1 (API 27) 
   
- Android Support Library Version: 27.0.2.1
- Nuget Packages:
- Affected Devices: Gaxaly Note 8

**Comment by jamesmontemagno** [comment]
The Xamarin Live Player is not currently supported with Xamarin.Essentials. You could try out https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload
