### ISSUE TITLE
Geolocation.GetLocationAsync() always returns null

### ISSUE THREAD

**Issue by vikingoAR** [xamarin/Essentials#551]
### Description
I work with Xamarin.Forms.Maps and try Xamarin.Essentials. I test with official doc example:

https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?context=xamarin%2Fxamarin-forms&tabs=android

I test on my mobile Samsung J1 Ace (API 22)
If I use **Geolocation.GetLastKnownLocationAsync()** everything works correctly and show me the map.
But if I use for example:
**userLocation = await GeolocationRequest()** the code **return immediately** to the line that called it and userLocation is null. Never throw an exception.
I tried with all the possible parameters.
I could find these lines at the output window:

10-12 20:49:41.802 D/Mono ( 3897): AOT: image 'System.Xml.dll.so' not found: dlopen failed: library "/data/app/com.essentials.geolocation-1/lib/arm/libaot-System.Xml.dll.so" not found
10-12 20:49:41.802 D/Mono ( 3897): AOT: image '/Users/builder/jenkins/workspace/xamarin-android-d15-8/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/lib/mono/aot-cache/arm/System.Xml.dll.so' not found: dlopen failed: library "/data/app/com.essentials.geolocation-1/lib/arm/libaot-System.Xml.dll.so" not found

Does this have any relation?

### Steps to Reproduce
Only run the project

### Expected Behavior
Show the map y my mobile location

### Basic Information
- IDE: Microsoft Visual Studio 17 (v. 15.8.5) Net Framework 4.7.03056
Net Standard Library 2.0.3
- Platform Target Frameworks:
  - Android: 8.1
- Android Support Library Version: 
- Nuget Packages:
Xamarin Forms 3.2.0.871581
Xamarin.Forms.Maps 3.2.0.871581
Xamarin.Essentials 0.10.0 preview
- Affected Devices:
Samsung J1 Ace (Api 22)
Elink H7Z5G tablet (Android 6.0 - API 23)

### Reproduction Link
A Very simple project:
https://github.com/vikingoAR/Maps

**Comment by jamesmontemagno** [comment]
I am unable to reproduce on my Pixel 2 XL in debug or release mode.

Is this a a debug app or release? Did you do AOT or Multi-dex? Anything special?

**Comment by jamesmontemagno** [comment]
Also realize that Best may take a good amount of time getting the specific gps location. Medium is a good recommendation.

I would also try 0.11.0-preview as there are more enhancements there.

**Comment by vikingoAR** [comment]
This is an app in debug mode.
I do not have anything set as AOT or MultiDex. I tried to check them and there is no change.

I did not make any changes to Xamarin's initial project, except for the Nuget packages needed, the information corresponding to the permissions and the Google v2 API key.

I tried using Best, Medium, etc. I also tried the use of CancellationTokenSource. But the results are the same.
Now I tried the same project on an **Elink H7Z5G tablet (Android 6.0 - API 23)** and I get the same behavior.

When I insert a break point in the line **userLocation = await Geolocation.GetLocationAsync (request);** and indicated that Step Into or Step Over, the flow exits IMMEDIATELY and returns to the line that called it, with userLocation null.

**Comment by jamesmontemagno** [comment]
Interesting, will give a look. Thanks for providing more details.

**Comment by SagarPanwala** [comment]
I got the same issue on Yu530 6.0.
One more thing, I'm not sure how to do check is GPSEnable or GPSOn? I tried by restarting device on/off GPS too. But no luck.

**Comment by raymondjstone** [comment]
This issue may not be quite as descibed, I am seeing this effect but ONLY on Android devices 8.0 and above and with location services switched off,


I get an untrappable exception and the code falls out of the procedure

Resolved pending breakpoint at 'CustomFormsMap.cs:334,1' to void MyAberdeenshire.Data.CustomFormsMap.<getlocation>d__38.MoveNext () [0x00032].
10-19 07:43:27.334 D/Mono    ( 1939): Image addref System.Diagnostics.Tools[0xbfa62540] -> System.Diagnostics.Tools.dll[0xdfc52500]: 2
10-19 07:43:27.335 D/Mono    ( 1939): Prepared to set up assembly 'System.Diagnostics.Tools' (System.Diagnostics.Tools.dll)
10-19 07:43:27.335 D/Mono    ( 1939): Assembly System.Diagnostics.Tools[0xbfa62540] added to domain RootDomain, ref_count=1
10-19 07:43:27.344 D/Mono    ( 1939): AOT: image 'System.Diagnostics.Tools.dll.so' not found: dlopen failed: library "/data/app/uk.gov.Aberdeenshire.MyAberdeenshire.Android-IrRgMNONvxV7BBhfSe2EIg==/lib/arm/libaot-System.Diagnostics.Tools.dll.so" not found
10-19 07:43:27.349 D/Mono    ( 1939): AOT: image '/Users/builder/jenkins/workspace/xamarin-android-d15-8/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/lib/mono/aot-cache/arm/System.Diagnostics.Tools.dll.so' not found: dlopen failed: library "/data/app/uk.gov.Aberdeenshire.MyAberdeenshire.Android-IrRgMNONvxV7BBhfSe2EIg==/lib/arm/libaot-System.Diagnostics.Tools.dll.so" not found
10-19 07:43:27.350 D/Mono    ( 1939): Config attempting to parse: 'System.Diagnostics.Tools.dll.config'.
10-19 07:43:27.350 D/Mono    ( 1939): Config attempting to parse: '/Users/builder/jenkins/workspace/xamarin-android-d15-8/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/etc/mono/assemblies/System.Diagnostics.Tools/System.Diagnostics.Tools.config'.
10-19 07:43:27.350 D/Mono    ( 1939): Assembly Ref addref MyAberdeenshire[0xdad3b1c0] -> System.Diagnostics.Tools[0xbfa62540]: 2
10-19 07:43:27.350 D/Mono    ( 1939): Assembly Ref addref System.Diagnostics.Tools[0xbfa62540] -> mscorlib[0xdad3ac20]: 85
Loaded assembly: System.Diagnostics.Tools.dll [External]

**Comment by raymondjstone** [comment]
The code for the above BTW is

Location newdeer = new Location(57.510916, -2.19);
            Constants.isshowinguser = false;
            map.IsShowingUser = Constants.isshowinguser;
            try
            {
                 App.location = await Geolocation.GetLastKnownLocationAsync();
            }
            catch (FeatureNotSupportedException fnsEx)
            {
                App.location = null;
                // Handle not supported on device exception
            }
            catch (PermissionException pEx)
            {
                App.location = null;
                // Handle permission exception
            }
            catch (Exception ex)
            {
                App.location = null;
                // Unable to get location
            }


but no code after App.location = await Geolocation.GetLastKnownLocationAsync();
gets executed

**Comment by frankhaugen** [comment]
I also get this on my test device, (samsung S8). GetLastKnownLocation works fine. I have no special configurations of either phone or project

**Comment by vikingoAR** [comment]
Hello James. This new code works perfectly! Many thanks!

**Comment by pachumon** [comment]
> Hello James. This new code works perfectly! Many thanks!
> I updated my project in case someone needs it.
> Best regards!

@vikingoAR  i am facing some issue with the Geolocation.GetLocationAsync() retuning nothing and not even error when i tried to check your project after pulling it from github it just provides me an empty webview. is there somrhting that i am missing any help would be much appreciated

**Comment by DAMcK-TREC** [comment]
I've been tearing my hair out trying every solution that I can find on the InterWeb but nothing works .... including this one. Got all latest. All location methods return null. The App requested permissions first time used. I set them anyway.

**Comment by Bersez** [comment]
If you go to Settings -> Location -> (it looks different on different devices) My location\ Google Location -> Google Geolocation if this option is disabled, for some reason, even with geolocation enabled, no active coordinate is displayed in any application
