### ISSUE TITLE
Battery BatteryChanged event

### ISSUE THREAD

**Issue by acaliaro** [xamarin/Essentials#554]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
I am using (for the first time) the Battery class.
I don't understand well the "states" when BatteryChanged event raise.
For example. I attach a Zebra TC25 Android device to a usb cable connected to a PC.
The BatteryChanged event raise and I have:
Level 1
State Full
Source AC

But is thould be Source USB and maybe it should be State Charging because it is receiving energy also if it's "full"... or I am wrong?

### Steps to Reproduce
Add this code in App.cs file:

```
        public App ()
        {
                InitializeComponent();

                Battery.BatteryChanged += Battery_BatteryChanged;

                MainPage = new LoginPage();
        }

        private void Battery_BatteryChanged(object sender, BatteryChangedEventArgs e)
        {

            var level = e.ChargeLevel;
            var state = e.State;
            var source = e.PowerSource;
            string s = $"Reading: Level: {level}, State: {state}, Source: {source}";
            Application.Current.MainPage.DisplayAlert("Battery", s, "Ok");
        }
```

### Expected Behavior
Level 1
State Charging
Source USB

### Actual Behavior
Level 1
State Full
Source AC

### Basic Information

- Version with issue: 0.11
- Last known good version:
- IDE: Visual Studio 2017
- Platform Target Frameworks: Android
  - iOS:  
  - Android: 8.1 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Zebra tc25

**Comment by jamesmontemagno** [comment]
These states are set by Android itself: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Battery/Battery.android.cs

You can see that it is returning AC and Full as the status. This means it is plugged in and at full hence the level is 1. 

There are a few differences on iOS/UWP: https://docs.microsoft.com/en-us/xamarin/essentials/battery?context=xamarin%2Fxamarin-forms&tabs=uwp#platform-differences
