### ISSUE TITLE
DeviceDisplay.ScreenMetricsChanged triggered wrong on Android?

### ISSUE THREAD

**Issue by ThumbGen** [xamarin/Essentials#556]
### Description

I am using the DeviceDisplay.ScreenMetricsChanged event to track Orientation changes.
On iOS seems to work fine, but on Android I always get it reversed. 
All metrics are for the old orientation and not the new one. The event is triggered only once.
Also important: First rotation does not trigger any event!

### Steps to Reproduce

1. Register to DeviceDisplay.ScreenMetricsChanged event on Android
2. Rotate the device (I used an emulator)

### Expected Behavior

When rotating from Portrait to Landscape the Metrics in the event args should indicate Landscape.

### Actual Behavior

The event args indicate Portrait.

### Basic Information

- Version with issue: 0.11.0

**Comment by ThumbGen** [comment]
I tried only with simulator, only on Monday I have access to a real device to test.

I just subscribe to the event in OnAppearing and wait for being called (Xamarin Forms).

Will get back with an update as soon as I try the app on a device.

**Comment by ThumbGen** [comment]
Yes, on the real device it works perfectly! Only on emulator not. Feel free to fix (if possible) or close the issue.

Thank you!

**Comment by ThumbGen** [comment]
It works on a real device. Only on emulator not.

**Comment by ThumbGen** [comment]
It works on a real device. Only on emulator not.

**Comment by jamesmontemagno** [comment]
I'll double check what is happening on emulator, assumption is it reports something wrong. Good to know and can document.

**Comment by gtbuchanan** [comment]
We're seeing this same behavior with the latest version on emulators of all API levels we've tried. Was the reason for this ever documented somewhere?
