### ISSUE TITLE
[Secure Storage] Should not throw when removing key that doesn't exist.

### ISSUE THREAD

**Issue by domagojmedo** [xamarin/Essentials#561]
On SecureStorage iOS implementation

    bool RemoveRecord(SecRecord record)
    {
            var result = SecKeyChain.Remove(record);
            if (result != SecStatusCode.Success)
                throw new Exception(string.Format($"Error removing record: {result}"));

            return true;
    }

It's possible to get 

> System.Exception: Error removing record: ItemNotFound

Should that status code maybe not throw exception? We are trying to remove it and it's not there, so the end result is the same.

Stack trace I got

> Xamarin.Essentials KeyChain.RemoveRecord (Security.SecRecord record)
> Xamarin.Essentials KeyChain.SetValueForKey (System.String value, System.String key, System.String service)
> Xamarin.Essentials SecureStorage.SetAsync (System.String key, System.String value, Security.SecAccessible accessible)
> Xamarin.Essentials SecureStorage.PlatformSetAsync (System.String key, System.String data)
> Xamarin.Essentials SecureStorage.SetAsync (System.String key, System.String value)

**Comment by mattleibow** [comment]
Fixed!

**Comment by domagojmedo** [comment]
@mattleibow 
@jamesmontemagno mentioned this issue in Android also, I couldn't get it or track it down. What's the resolution for it?

**Comment by mattleibow** [comment]
It should not throw. It is using `Preferences` under the hood, which is fine for removing keys that do not exist.
