### ISSUE TITLE
Can we make Permission accesible ?

### ISSUE THREAD

**Issue by SagarPanwala** [xamarin/Essentials#563]
This is not the bug.

I'm using camera previewer in app and it needs permission.
I'm also using Xamarin Essentials. But to implement previewer I have ask permission and for that we must have to use separate Permission plugin, even though it is available in Xamarin Essentials.

**Comment by jamesmontemagno** [comment]
There is a permissions plugin that I publish today like you stated, It is being reviewed and analyzed for the future: https://github.com/xamarin/Essentials/issues/504

**Comment by SagarPanwala** [comment]
Great Brother,
Many respect for you.
