### ISSUE TITLE
[Docs] Add reminder note to init

### ISSUE THREAD

**Issue by Depechie** [xamarin/Essentials#565]
When I searched on how to use a specific element of Xamarin Essentials ( in my occasion Geolocation ), I forgot to add the platform specific initialisation needed on Android.

I know it's well documented in the Getting started section, but was wondering if a reminder note could be added in each subsection Getting started part of the docs, pointing to the general one. So we don't forget.

**Comment by mattleibow** [comment]
This sounds intelligent. Not everyone comes into the docs from the index page.

**Comment by jamesmontemagno** [comment]
I'm on it
