### ISSUE TITLE
[Docs] Flashlight turns itself off if doesn't have exclusive lock -> iOS

### ISSUE THREAD

**Issue by mrtnkrstn** [xamarin/Essentials#566]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description

Flashlight turns itself off after a couple of seconds.

### Steps to Reproduce

1. Call `await Flashlight.TurnOnAsync();` in View code

### Expected Behavior

Flashlight turns on, and stays turned on.

### Actual Behavior

Flashlight turns on, but turns off after a couple of seconds.

### Basic Information

- Version with issue: 0.11.0-preview
- Last known good version: NA
- IDE: VS for Mac
- Platform Target Frameworks:
  - iOS:  10.3
- Nuget Packages:
- Affected Devices: iPhone 8+ iOS 12

**Comment by jamesmontemagno** [comment]
Hmmm I was unable to reproduce this at all with the latest. Perhaps another application had exclusive lock on the camera. Can you try again and make sure no background apps were running.

**Comment by mrtnkrstn** [comment]
OK so I did leave out some important info, sorry. Am using this in combination with CardIO (https://github.com/xamarin/XamarinComponents/tree/master/XPlat/CardIO): I have added a button to the CardIO camera screen that triggers the flashlight; it does turn on, but turns itself off within a couple of seconds.

**Comment by jamesmontemagno** [comment]
Yeah, there is nothing we can do here. I will probably have to document this.

I am shocked that CardIO doesn't have this built in....

**Comment by Redth** [comment]
Sounds like they think this should happen automatically in their library: https://github.com/card-io/card.io-iOS-source/issues/40#issuecomment-144195717

In any case I don't think we can do much here, sorry :(
