### ISSUE TITLE
[api-fix] DeviceInfo

### ISSUE THREAD

**Issue by Redth** [xamarin/Essentials#572]
In `DeviceInfo`:

 - Change `Idioms` and `Platforms` to use the same technique `OSPlatform` uses in https://apisof.net/catalog/System.Runtime.InteropServices.OSPlatform
- Add `Watch` as a Platform

**Comment by jamesmontemagno** [comment]
One downside that we found is that you can not switch case over the struct as you would expect :( you can only do if checks
