### ISSUE TITLE
[api-fix] VersionTracking

### ISSUE THREAD

**Issue by Redth** [xamarin/Essentials#581]
Android uses SharedPreferences to store a string of all past version history.  This might grow beyond the allowed max size of a sharedpreference string.  We should:
1. Determine what the max length is
2. Add logic to trim off the oldest version information until the string will fit.

**Comment by mattleibow** [comment]
I am not sure what we should do here...
This tells me there is a limit of 8k chars: https://developer.android.com/reference/java/util/prefs/Preferences#MAX_VALUE_LENGTH

But. I just did a test of 12 *MILLION* characters and all appears to be fine. This was on my Google Pixel 2 XL.

**Comment by jamesmontemagno** [comment]
I think it is actually the string largest length. I think we are fine for now.
