### ISSUE TITLE
[api-fix] Sensors

### ISSUE THREAD

**Issue by Redth** [xamarin/Essentials#582]
- [x] `SensorSpeed`
    - [x] Fix values to be: `Default = 0`, `UI = 1`, `Game = 2`, `Fastest = 3`
    - [x] Fix  viewmodel in sample which is doing an incorrect int cast
- [x] `CompassData`
    - [x] Remove `ApplyLowPassFilter` property and instead pass into `Start` as a default `true` parameter
- [x] `Magnetometer` - documentation should say values are microteslas and use the µ symbol
- [x] On all sensors, throw `InvalidOperationException` if `Start` is called while `IsMonitoring` is `true`
- [x] Add a public `ctor` for all `EventArg` types (for unit testing)
- [x] Add public `ctor` for all structs
- [x] `Gyroscope`
    - [x] UWP needs to convert deg/s to rad/s
    - [x] Document rad/s being the value returned
- [x] `BarometerData.Pressure` 
    - [x] Rename to `PressureInHectopascals` 
    - [x] check conversions are done on each platform
- [x] ~Rename `CompassData.HeadingMagneticNorth` to `HeadingMagneticNorthDegrees`~

**Comment by mattleibow** [comment]
I am going to skip the rename of `HeadingMagneticNorth` since it will always be in degrees since this is the only measurement ever used
