### ISSUE TITLE
TextToSpeech: passing a SpeakSettings without Locale causes errors on all platforms

### ISSUE THREAD

**Issue by powerdude** [xamarin/Essentials#587]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
When calling Speak with a SpeakSetting parameter that doesn't set Locale, NRE's are thrown due to checking for Language.  i.e. calls to `settings?.Locale.Language` should be `settings?.Locale?.Language`
### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
no error
### Actual Behavior
NRE thrown
### Basic Information

- Version with issue: Latest
- Last known good version: none
- IDE:
- Platform Target Frameworks: 
  - iOS:  latest
  - Android: latest 
  - UWP:  latest 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by mattleibow** [comment]
Thanks for reporting this, I reviewed your PR and all looks good. Waiting on CI and other review.

**Comment by Redth** [comment]
Fixed by merging #588 Thanks!
