### ISSUE TITLE
[api-fix] Enum Consistency

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Essentials#593]
We currently have an inconsistency in the code. Here are two types of enums:

```csharp
public enum FirstEnum {
    Item1,
    Item2
}
```

```csharp
public enum SecondEnum {
    Unknown,
    First,
    Second
}
```

 - Should we explicitly add values?
 - Should we explicitly set `Unknown` as `0`?

We should NEVER change the value of an item as things will break, so explicit values will prevent this. But, the only reason we NEED values is the fact we may remove items. But this is also a breaking change.

😸

**Comment by jamesmontemagno** [comment]
New guidance will be to explicitly set all enums :)

**Comment by mattleibow** [comment]
Sounds like a plan
