### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Essentials#599]
To re-en docs, just run:

```
msbuild /m /restore /v:m Xamarin.Essentials /t:rebuild;mdocupdatedocs /p:Configuration=Release
```

This should be run on each change to reduce conflicts, but not essential :)

But it must be run before merging into master as this will be on the docs site.

Update docs:
 - [ ] API docs
 - [ ] main docs are updated
 - [ ] make sure we have specified the units for each sensor
 - [ ] docs to indicate that sensors are static and need to be unsubscribed to avoid leaks

**Comment by mattleibow** [comment]
Besides the API docs, we need to make sure the other docs are updated and make sure we have specified the units for each sensor.

 - https://github.com/xamarin/Essentials/issues/584

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '1.0.0' that is not in the list of supported values

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '1.0.0' that is not in the list of supported values

**Comment by Redth** [comment]
This was relatively painless, with only a couple missed changes.  Kudos to everyone for getting this mostly right in the initial PR :)
