### ISSUE TITLE
Backup exclusion of shared prefs on android in the library itself

### ISSUE THREAD

**Issue by Redth** [xamarin/Essentials#602]
We show in the sample how to exclude Android's shared preferences for the essentials file from backup but let's see if we can find a way to make this included as part of the library.

We might be able to have the application manifest declaration merged and include the XML as a resource file. 

Worth exploring this issue.

**Comment by jamesmontemagno** [comment]
Todo:
* Add a default xml file with 1.0
* Update docs to require this setup and document how to use our file or point to custom file implementation

**Comment by jamesmontemagno** [comment]
After investigating the xml is bundled up into the library and then into the app, however ${applicationdId} doesn't get update in library resources only attributes in the code :( so for this reason we can't add this in. However we will update the docs.
