### ISSUE TITLE
Unique Device Identifier in Device Information

### ISSUE THREAD

**Issue by Weishaupt** [xamarin/Essentials#608]
# Description of the Feature
What I'm missing on the Device Information API is a unique identifier for the device. In a Client/Server communication, I want to make sure to only issue one active access token per device. Thus uniquely identifing the device is required. I would place this functionality in the existing `DeviceInfo` API.

# API Declaration

API: (Enhanced) Device Information

    namespace Xamarin.Essentials
    {
        public static partial class DeviceInfo
        {
            public static string UniqueIdentifier;
        }
    }

# Documentation links for supported platforms

- Apple: [identifierForVendor](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor)
- Android: [ANDROID_ID](https://developer.android.com/reference/android/provider/Settings.Secure#ANDROID_ID) - Note the [behavior changes](https://developer.android.com/about/versions/oreo/android-8.0-changes) from API level 26 onwards.
- UWP: [SystemIdentification](https://docs.microsoft.com/en-us/uwp/api/Windows.System.Profile.SystemIdentification)

**Comment by jamesmontemagno** [comment]
Thanks for the recommendation, however these work really different between each OS and device. After a lot of research we have decided not to add this due to instability of the API. See: https://github.com/xamarin/Essentials/issues/61 for more info.

**Comment by jamesmontemagno** [comment]
See our thread on #61 as it will not be added.
