### ISSUE TITLE
DeviceInfo needs a way to get the ID

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Essentials#61]
This may either be the unique device identifier and/or the installation Id.

APIs:
* iOS: [identifierForVendor](https://developer.apple.com/documentation/uikit/uidevice#//apple_ref/occ/instp/UIDevice/identifierForVendor) This is a unique ID for all of a vendors apps installed on the device. 
* Android: [Build.Serial](https://developer.android.com/reference/android/os/Build.html#SERIAL) now replaced in API 26 with [Build.GetSerial()](https://developer.android.com/reference/android/os/Build.html#getSerial()) not every manufacturer fills this out though and previously I used the Secure.AndroidId
* UWP: [GetSystemIdForPublisher](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.systemidentification.getsystemidforpublisher#Windows_System_Profile_SystemIdentification_GetSystemIdForPublisher) with backup of [GetPackageSpecificToken](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.hardwareidentification.getpackagespecifictoken)

If you are leave a comment here can you please describe why and how you are using it.

**Comment by mattleibow** [comment]
This will be a good reference for the code and the issues: https://github.com/jamesmontemagno/DeviceInfoPlugin

**Comment by mattleibow** [comment]
This commit removes the potential code: https://github.com/xamarin/Caboodle/commit/3f46dd92fbe44064c8301f3ca3e71d66da5750e0

Notably, the Android implementation must use `Build.GetSerial()` on Android O+

**Comment by cklenk** [comment]
This would be great to have! Thanks.

**Comment by Im-PJ** [comment]
yes its needed. that's why im not able to switch from device info plugin.

**Comment by Mrnikbobjeff** [comment]
A device id has a plethora of different usage scenarios. I would love love love seeing this added. 
For UAP we could use the rather newly introduced [SystemInformat](https://docs.microsoft.com/en-us/uwp/api/Windows.System.Profile.SystemIdentification) Type. iOS would probably use the UUID.
I believe the implementation to be very straight forward, so this would be an easy improvement with a high payoff.

**Comment by aherrick** [comment]
@Mrnikbobjeff I don't believe you can programatically get the UDID on iOS.

**Comment by jamesmontemagno** [comment]
@aherrick @Im-PJ @cklenk we would love to know how you are using it so we can get the API correct as they are very different between each platform.

**Comment by Im-PJ** [comment]
once user registers on app on certain device, i was storing device id and doing a check on each login. if the device id is different user is not allowed to login and have to register again. this was to control that company app is being used by user on his device only. basically i need unique device id which doesn't change atleast till the device is reset or OS re-installed.

**Comment by Mrnikbobjeff** [comment]
@aherrick You are correct, apparently the best we could do would be [DeviceIdentifierForVendor](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor?language=objc), which should be sufficient for most purposes

**Comment by cklenk** [comment]
@jamesmontemagno I was using it for licensing purposes, keeping track of a device a user has to enable or disable based on the number of licenses someone had. Thank you for your work!!

**Comment by domagojmedo** [comment]
This would be really nice to have like in @jamesmontemagno DeviceInfoPlugin

**Comment by Mrnikbobjeff** [comment]
Would we need to make this async? On android this requires READ_PHONE_STATE if you use Build.GetSerial()

**Comment by jamesmontemagno** [comment]
Introduction of two APIs:

```csharp
string IdForVendor { get; }
Task<string> GetSerialAsync();
```

### IdForVendor
Represents an Alphanumeric string that uniquely identifies a device to the app's vendor. The value of this property is the same for apps that come from the same vendor running on the same device. A different value is returned for apps on the same device that come from different vendors, and for apps on different devices regardless of vendor. 

On Android this will always be unique per app per device. 

* Android: InstanceID is an option, but requires many dependencies, So opt for Java.Utils.UUID.RandomUUID().ToString(). [Documentation supports this claim](https://developer.android.com/training/articles/user-data-ids#working_with_instance_ids_&_guids). The ID will be stored into private shared preferences.
* iOS: Uses [UIDevice.IdentifierForDevice](https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor)
* UWP: Uses [SystemIdentificationInfo](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.systemidentification.getsystemidforpublisher)


### GetSerialAsync()
This method will attempt to get the system's serial hardware identifier or a unique quid for that system. 

* Android: Requires READ_PHONE_STATE Permission. On Android API 26+ Uses Build.GetSerial(), on lower will use Build.Serial, and as fallback will use AndroidId from secure android provider settings
* iOS: on iOS 11+ will use [device check](https://developer.apple.com/documentation/devicecheck) to generate a unique token for the device. On < iOS 11 will generate a unique NSUUID and for each of these will store into NSUserDefaults to persist.
* UWP: Uses [HardwareIdentification.GetPakageSpecificToken](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.hardwareidentification)

**Comment by jamesmontemagno** [comment]
Yeah, I don't think that is good reading further: https://developer.apple.com/documentation/devicecheck

I don't know or think that this API should be introduced as it is nearly impossible to get correct.

**Comment by jamesmontemagno** [comment]
Essentials here could be used to do all of the Keychain stuff... See SecureStorage as it does all of this. You would only need a way to get the IdentifierForVender, however it is not really reliable as it can change based on how many apps you have installed in general.

Know though that the keychain is transfered over to new devices so the new device would have the same GUID.... so not sure if that is what you are looking for.

I think that is the problem with the "ID" is that developers will want to use it in different ways. Hard for us to give a consistent API across all platforms.

The concept though of doing this would work for you:

```csharp
var id =await SecureStorage.GetAsync("my_id");
if(id == null)
{
   id = System.Guide.NewGuid().ToString();
  await SecureStorage.SetAsync("my_id", id);
}

```

**Comment by freever** [comment]
Great, thanks for the tip!

**Comment by jamesmontemagno** [comment]
After examining this API we have come to the conclusion that it is not a good fit for Essentials as it can not be properly abstracted across each platform. Documentation has this in place today to outline how to do this via platform specific code.

**Comment by 15mgm15** [comment]
@jamesmontemagno If we need still a unique ID what should be the correct approach? `IdForVendor `?

**Comment by jamesmontemagno** [comment]
you could probabloy use this: https://github.com/xamarin/Essentials/issues/61#issuecomment-408977748

however, i would read the ios/android/uwp specific docs and recommendations on how to do this. Android has some new support packages that could handle this somehow, however it is really hard to ever ensure that the same exact ID will come back.

**Comment by gitown** [comment]
Please to take a look at the Unity3D docs, they're able to provide a DUI for almost all platforms (with the exception of iOS which provides a new identifier when the app is reinstalled): https://docs.unity3d.com/ScriptReference/SystemInfo-deviceUniqueIdentifier.html
As an old Unity3D developer, I can say that this feature is really important!
One of the uses case of the DUI: we can save the settings of the app on the cloud using the DUI, if the user uninstall and install the app again, the settings can be retreived form the server using the DUI (especially for Android and UWP).

**Comment by Redth** [comment]
Those docs don't seem to mention how they do things on android which is perhaps the trickiest platform and would require taking additional dependencies we are trying to avoid...

**Comment by gitown** [comment]
> Those docs don't seem to mention how they do things on android which is perhaps the trickiest platform and would require taking additional dependencies we are trying to avoid...

Here is a thread with more details about how they're getting the DUI for Android: https://forum.unity.com/threads/unique-identifier-details.353256/

**Comment by gitown** [comment]
I understand your point of view, but I still think that this feature is very important for developers and will save us lot of time if it will be available out of the box in Xamarin.Essentials!
About the ANDROID_ID, I just read the documentation and found that it returns a consistent and unique value for the combination user/app/device, even if the user uninstall/reinstall the app, unless he decide to wipe or upgrade his device, and I find that this is an acceptable behaviour.
I hope you'll keep considering this feature in a future release of Xamarin.Essentials. And why not creating a poll on your todo list of features to see which of them are more important to your community and then prioritize them.

**Comment by AngeloLazzari** [comment]
Firstly: THANK YOU A LOT GUYS for the really unbelievable work you do to create plugins that millions of people use with our apps.

My situation is this one, i had using plenty of different nugets to get all the Essentials plugin do all in one... the last one i was "cleaning" was the CrossDeviceInfo that i was using to get the device platform and i substituted with the Essentials DeviceInfo ..... good work... BUT, in just in my app i used CrossDeviceInfo.Current.Id, and i really expected to find the Essentials property too, BUT...SURPRISE!! ... no way to get it. So now i have to keep the  CrossDeviceInfo just to get the ID.... 

My need is not to have a 100% UUID, but just an ID that linked with another realtime info of the app will keep the entire ID as "unique" in my "app world"...

i think, just to get things "linear and clean" and not have nuget installed just for one property use, Essetials could give the same ID value as CrossDeviceInfo do.... 

Those were my two cents.... 
thank you very much

**Comment by jrahma** [comment]
Yes this needs to be included in the Xamarin Essentials
