### ISSUE TITLE
Active / Realtime Users

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#614]
Hi,

I suggest to add a feature to get the current active users (logged on or not logged).. so whoever is currently opened the app should count just like the count in Google Analytics for Realtime users.

This will be helpful as an API to be used for reporting purpose.

Thanks,
Jassim

**Comment by jamesmontemagno** [comment]
Do you have a reference of the iOS/Android APIs for the functionality you are seeking? I am not sure exactly if this is part of the OS itself. This seems like perhaps an analytics framework like App Center would deliver.

**Comment by jrahma** [comment]
Nope I don't have but it's an idea..

Well, I guess App Center could be a good option..

I'll try  it..

Thanks
