### ISSUE TITLE
Use LiveReload in Sample project

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#618]
Consider adding [Live Reload](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload) capabilities to Samples project to shorten UI update time. It is super easy to configure, developed by Microsoft and really smoothes UI updating. You could even configure it to only be included in Debug builds.

**Comment by jamesmontemagno** [comment]
No plans on adding this as a dependency as of right now.
