### ISSUE TITLE
Launcher CanOpenAsync seems to hide exceptions

### ISSUE THREAD

**Issue by woutermeuwis** [xamarin/Essentials#628]
### Description
CanOpenAsync has 2 overloads: one accepting an Uri and one accepting a string. 
The one with the string does however simply create a new Uri from said string internally.
The issue I'm experiencing is that when the string is not a valid URI the exception is swallowed, and the method does not return.

### Steps to Reproduce

1. Declare a test string:
`var test = "Test.be";`
2. Call CanOpenAsync 
`var canOpen = await Xamarin.Essentials.Launcher.CanOpenAsync(test);`

### Expected Behavior
Since the string is not a valid uri, the method should either return false, or throw the UriFormatException so the calling code can catch it.

### Actual Behavior
The method simply does not return when the Uri constructor throws an exception.

### Basic Information

- Version with issue: 0.11.0-preview
- Last known good version: None
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - iOS:  12.2.1.10
  - Android: 9.0.0.20
- Nuget Packages: Xamarin.Essentials

> VS bug [#735686](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735686)

**Comment by Mrnikbobjeff** [comment]
Could you elaborate on which Platform this happens? After loading the sample project on UWP and Android I got UriFormatExceptions when testing with your string and the string based overloads.

**Comment by Redth** [comment]
Given it's an async method, are you actually catching the exception?

**Comment by woutermeuwis** [comment]
Apparently I can not reproduce the issue in a sample project so it seems to be we are handling this wrong at our end. This issue can be closed.
