### ISSUE TITLE
Make Essentials ready for non-nullable reference types.

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#631]
Some projects such as YodaTime and similar use [NotNull] and  [CanBeNull] or similar attributes to inform users about contracts. As C# 8.0 brings non-nullable reference types, I thought it might be a good idea to create contracts now so that once 8.0 rolls out we simply can remove the attributes and use the corresponding c# 8.0 nullable syntax. In general I like contracts very much, especially the Resharper info about the bcl function contracts where resharper detects which apis can be called with null and which can not.

> VS bug [#736800](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/736800)

**Comment by Redth** [comment]
This is a good idea.  First step is to just do an audit on the API for any cases where this will need to be applied.

**Comment by Mrnikbobjeff** [comment]
The following API's validate arguments to be not null or should validate: Browser, Clipboard, Connectivity (ConnectionProfiles), Email, Launcher, MainThread, Maps, PhoneDialer, Preferences, SecureStorage, Share, TTS
The following API's have return arguments which would have to be enforced non-nullable (e.g. by returning empty enumerables): AppInfo, DeviceInfo, Geocoding, Geolocation, Sms
All our event based classes are inherently non-nullable as the EventArgs are constructed by value types and thus can not ever be null.

**Comment by Redth** [comment]
So I'm assuming you are proposing defining our own `[NotNull]` and `[CanBeNull]` attributes?  Are these attribute _names_ something like resharper is looking for?

**Comment by Mrnikbobjeff** [comment]
Yes I propose defining them in our own code - this is something which still works with resharper, even if we dont use their predefined attributes. As long as the names match everything is fine. In general I would see the need for four attributes, [CanBeNull],[NotNull], [ItemNotNull] and [ItemCanBeNull]. The first two are used for single elements, the others for collections which can / can not contain null values. A combination of these should be able to let us specify nullability behaviour just as precise as C# 8.0.

**Comment by Mrnikbobjeff** [comment]
Sooo, I installed the preview and we have 130 errors with non-nullable references. Many are hidden from the user in the Platform implementations in the start and stop events. The listeners are assigned null after stopping the sensor and have to be nullable. The main other concern are our DTO's such as EmailMessage or Placemark. We should discuss whether whether we want these objects to implement nullable properties or to remain empty if they  are uninitialized. Other than that we directly pass null in preferences, all other instances are encapsulated in dto's.

**Comment by mattleibow** [comment]
We can also annotate our internal checks with the attributes to help reduce the cases where we KNOW that something is not null.

**Comment by jfversluis** [comment]
This won't be happening for Xamarin.Essentials anymore at this stage. Thank you everyone for the time and effort on this!
