### ISSUE TITLE
Failed to initialize Text to Speech engine. Exception.

### ISSUE THREAD

**Issue by Sergiojoel9877** [xamarin/Essentials#632]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
Failed to initialize Text to Speech engine. Exception.
### Steps to Reproduce

1. Upgrade Xamarin.Essentials to the latest prerelease 0.11.0-preview.

### Basic Information

- Version with issue: 0.11.0-preview
- Last known good version: None of them seems to work on Android 9.0
- IDE: Visual Studio
- Platform Target Frameworks: 28.0.0-preview 8
  - iOS:  
  - Android: 9.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin.Essentials-v0.11.0-preview.
- Affected Devices:

**Comment by Redth** [comment]
Unable to reproduce this locally.

Can you provide a simple reproducible solution for us?

**Comment by jamesmontemagno** [comment]
Additionally, where are you calling the code?

**Comment by Sergiojoel9877** [comment]
Hey guys, here is a reproducible solution. 
https://github.com/Sergiojoel9877/XE.git 
It uses the latest Xamarin Essentials nugget, XamarinForms 3.4.0, and the latest Android Support Libraries 28.0.0.0-preview8
@jamesmontemagno no matter the place [Code Behind, ViewModel], it always gives me that exception.

**Comment by jamesmontemagno** [comment]
I believe your issue is that you are trying to call the speak code on a background task:

**Comment by Sergiojoel9877** [comment]
Just after updating to the 1.0.0 version it got solved. Thanks guys.
