### ISSUE TITLE
Consider using NWPathMonitor for Connectivity on iOS

### ISSUE THREAD

**Issue by Redth** [xamarin/Essentials#633]
See: http://blog.jaredsinclair.com/post/179083065595/til-boy-have-i-been-misusing

We should look at implementing Connectivity with NWPathMonitor.

> VS bug [#740088](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/740088)

**Comment by jamesmontemagno** [comment]
https://medium.com/@rwbutler/nwpathmonitor-the-new-reachability-de101a5a8835

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Essentials is now in maintenance mode, this will not happen anymore for Xamarin.Essentials. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
