### ISSUE TITLE
SecureStorage.SetAsync on iOS not working in 0.11 and 1.0 version

### ISSUE THREAD

**Issue by gsmental** [xamarin/Essentials#635]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
app closes without any error. it take some time before closing. i try with debugging many times. every time it crashes.

### Steps to Reproduce
await SecureStorage.SetAsync("phoneDeviceId", "my Guid");

### Expected Behavior
it should work on iOS but working smoothly in android from 0.10 version
### Basic Information
 visual studio for mac updated version

- Platform Target Frameworks: 
  - iOS:  it should work on iOS but working smoothly in android from 0.10 version
  - Android: it should work on iOS but working smoothly in android from 0.10 version

# using MVVMCROSS 6.1.2 with  .net standard 2.0

> VS bug [#744069](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/744069)

**Comment by kolegs** [comment]
@gsmental Are you developing for iOS simulator? 
I tried it on iPhone 5s, Xr and iPad and it works just fine. It crashes on iOS simulator but it is documented https://docs.microsoft.com/pl-pl/xamarin/essentials/secure-storage?tabs=ios

**Comment by gsmental** [comment]
It crashes on iOS simulator, i did not try on physical device. 
thanx

**Comment by jamesmontemagno** [comment]
When you are on a simulator you must setup entitlements see setup: https://docs.microsoft.com/pl-pl/xamarin/essentials/secure-storage?tabs=ios

**Comment by Redth** [comment]
Testing our sample app, but as James said, this is probably due to entitlements not being setup properly for simulator.
