### ISSUE TITLE
UWP: No definition for Geolocation.MapKey in 1.0

### ISSUE THREAD

**Issue by Agredo** [xamarin/Essentials#638]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description

`Geocoding.MapKey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

var placemarks = (await Geocoding.GetPlacemarksAsync(location)).ToList();
`

### Expected Behavior

A definition for Geolocation.MapKey or edit the [documentation](https://docs.microsoft.com/de-de/xamarin/essentials/geocoding?tabs=uwp) for the new way in 1.0

###Actual Behavior

No definition for Geolocation.MapKey in Xamarin.Essentials 1.0 to use maps UWP.

### Basic Information

Xamarin.Forms 3.4 with Visual Studio 2017 and Xamarin.Essentials 1.0

### Screenshots
![screenshot 7](https://user-images.githubusercontent.com/16531090/49545303-8b1a0800-f8dd-11e8-978d-5087de9da639.png)
![mapkey1](https://user-images.githubusercontent.com/16531090/49545305-8b1a0800-f8dd-11e8-99eb-915c1095a493.PNG)

**Comment by pictos** [comment]
@Agredo  look the [en-us doc](https://docs.microsoft.com/en-us/xamarin/essentials/geocoding?tabs=uwp)... You need to put this line UWP code project:

`Platform.MapServiceToken = "Your-Key";`

**Comment by jamesmontemagno** [comment]
We have a transition guide here: https://github.com/xamarin/essentials/wiki/Release-Notes

**Comment by Agredo** [comment]
Thank you I searched in the docs. Not release notes. :)
