### ISSUE TITLE
[Feature Request] True north heading in Compass

### ISSUE THREAD

**Issue by CalebPourchot** [xamarin/Essentials#641]
It would be great to have an option to return the true north heading or the magnetic heading.

**Comment by mattleibow** [comment]
@jamesmontemagno, we could have a look and see if there was a way to expose some functions/hooks that the dev could pass in something and get the true north. Basically, we can help the dev get this value - even if he has to do some work. Not sure if this is something we want to do, but a thought.

**Comment by jrahma** [comment]
It can be something like this:

```
void Compass_ReadingChanged(object sender, CompassChangedEventArgs e)
{
    var data = e.Reading;

    Compass.PointTo(point_to_latitude, point_to_longitude);
}

```

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
