### ISSUE TITLE
Main Thread question

### ISSUE THREAD

**Issue by stesvis** [xamarin/Essentials#645]
Hello,

I was just wondering if there is a difference between
`MainThread.BeginInvokeOnMainThread`
and 
`Device.BeginInvokeOnMainThread`

Thanks!

**Comment by danielkatz** [comment]
Read the [documentation](https://docs.microsoft.com/en-us/xamarin/essentials/main-thread?context=xamarin/android#running-code-on-the-main-thread).
Both implementations function in the same way, but the Essentials implementation has a bonus mehod `MainThread.IsMainThread`.

**Comment by jamesmontemagno** [comment]
One comes from Xamarin.Forms and one comes from Xamarin.Essentials (can be used in non-forms projects). The code is basically the same between them.
