### ISSUE TITLE
StoreReviewPlugin into Xamarin.Essentials?

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Essentials#648]
is it good to have or possible to have [this ](https://github.com/jamesmontemagno/StoreReviewPlugin)awesome plugin from @jamesmontemagno into xamarin.essentials?

**Comment by jamesmontemagno** [comment]
This one unfortunately no as there is no official api to launch the store on specific platforms and on Android there can be multiple app stores. There is no good consistent API to do this, however you can accomplish this with the Launcher API today just pass the URLs you want.
