### ISSUE TITLE
Connectivity -> Can return the same profile twice

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#649]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
Isn't a huge issue, but no need to be returning the same Profile twice. Sometimes android devices can return cellular multiple times and even an unknown for something like VPN.

### Steps to Reproduce

1. Run on a device (usually android)
2. YMMV but you can get the same profile twice

### Expected Behavior

A profile should only show once.

### Actual Behavior

Usually does, but not always

### Basic Information

- Version with issue: 1.0.0
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  iOS 12
  - Android: Tested on 8.0
  - UWP:  16299

**Comment by stesvis** [comment]
Hello @jamesmontemagno ,

I was going to report that the `Connectivity.ConnectivityChanged` event is fired twice when the connectivity changes. Is it the same bug?

**Comment by jamesmontemagno** [comment]
It is possible, however we do a check to see if all of the values are the same or not.
