### ISSUE TITLE
GetLocalesAsync Add Ability to Return Non-Downloaded Languages

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Essentials#654]
Below i tested only on Android but probably same on IOS and UWP  

### Expected Behavior

It should return all available languages, not only downloaded one. One of the previous version or TextToSpeech plugin used to return all available languages and if languages isnt downloaded, it prompts to download. 

### Actual Behavior
it returns only downloaded language and if i have multiple languages within the phone, for example;

- users phone: German - downloaded locale is German
 - App language: English

GetLocalesAsync returns only German and user cant use texttospeech unless i do some workaround. but if returning all possible locale instead of only already downloaded one, user is prompt to download by the system.
 
- Version with issue: 1.0.0
- Last known good version: TexttoSpeech plugin and one of the pre version

**Comment by jamesmontemagno** [comment]
This is how we designed it to return only available languages on the device. We could most likely return an overload in there... would need to look at each platform though.

I believe in my old plugin that it was a bug that I returned non-available ones and it only did that in < 21 apis

**Comment by newky2k** [comment]
@EmilAlipiev  This is working as designed and the previous 'working' version of the code was actually a bug.  Closing.
