### ISSUE TITLE
Support Android 28.0.0

### ISSUE THREAD

**Issue by gabry90** [xamarin/Essentials#655]
### Description

Please support Android 28.0.0 or ai can't update  xamarin.Android at 28.0.0 for my project

### Steps to Reproduce

None

### Expected Behavior

None

### Actual Behavior

None

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - Android: 8.1
- Android Support Library Version: 27.0.1
- Nuget Packages:
- Affected Devices:

### Screenshots

None

### Reproduction Link

None

**Comment by jamesmontemagno** [comment]
What issue are you seeing. It will work just fine with Support 28.

You may want to install CustomTabs NuGet manually to sync up versions.

**Comment by gabry90** [comment]
during update Xamarin.Android 28.0.0:

[MyProjectName] -> Xamarin.Android.Support.v7.MediaRouter 28.0.0 -> Xamarin.Android.Support.v7.Palette 28.0.0 -> Xamarin.Android.Support.Compat (= 28.0.0) 
 [MyProjectName] -> Xamarin.Essentials 1.0.0 -> Xamarin.Android.Support.CustomTabs 27.0.2.1 -> Xamarin.Android.Support.Compat (= 27.0.2.1).	[MyProjectName].Android

**Comment by jamesmontemagno** [comment]
So yeah, please first install 

Xamarin.Android.Support.CustomTabs 27.0.2.1

Then you can update to 28.0.0 gracefully. See: https://redth.codes/how-to-fix-the-dreaded-version-conflict-nuget-error-in-your-xamarin-android-projects/
