### ISSUE TITLE
Connectivity = NONE only works on IOS but not Android

### ISSUE THREAD

**Issue by Swdvader** [xamarin/Essentials#656]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
Using Essentials connectivity to show connection status.  When there is no connection, Android device shows Local or internet, but not NONE. When there is no connection Android shows LOCAL instead of NONE..  On IOS it works correctly, device shows NONE as expected.

### Steps to Reproduce

In code behind put in simple code for testing and 2 labels in Xaml to display changes.

```csharp
public MainPage()
{
    InitializeComponent();
    Connectivity.ConnectivityChanged += Connectivity_ConnectivityChanged;
}

private void Connectivity_ConnectivityChanged(object sender, ConnectivityChangedEventArgs e)
{
    LabelStatus.Text = "NetworkAccess : " + e.NetworkAccess + "Profile: " + e.ConnectionProfiles;
    UpdateLabels();
    //throw new NotImplementedException();
}

        private void UpdateLabels()
        {
   
            var current = Connectivity.NetworkAccess;
            if (current == NetworkAccess.Internet)
            {
                LabelConnect.Text = "Internet";
            }
            else if (current == NetworkAccess.None)
            {
                LabelConnect.Text = "NONE";
            }
            else if (current == NetworkAccess.Local)
            {
                LabelConnect.Text = "local";
            }

        }
        protected override void OnAppearing()
        {
            UpdateLabels();
        }
```

In XAML just added to labels

```xaml
    <StackLayout>
    
        <Label Text="Welcome to Xamarin.Forms!" x:Name="LabelStatus"></Label>
        <Label Text="Current connection:" x:Name="LabelConnect"></Label>

    </StackLayout>
```

1.    Run app
2.    Shows Wifi or Local correctly
3.   Turn on airplane mode to disable wifi and cell

### Expected Behavior
To display NONE   (IOS displays NONE)

### Actual Behavior
NetworkAccess : LocalProfile
Label update shows Local    (current == NetworkAccess.Local)

### Basic Information

- Version with issue:  Xamarin Essentials Version 1.0.0 /Xamarin Forms 3.1.0.697729
- Last known good version:  never tested, new.
- IDE:
- Platform Target Frameworks:  Tried 8.0(oreo) and 9.0(P)
  - iOS:   
  - Android:    8.1OREO
- Android Support Library Version: 
- Nuget Packages:Xamarin Essentials Version 1.0.0 /Xamarin Forms 3.1.0.697729
- Affected Devices: Android
Testing on Galaxy S9+ running Android 8.0.0

**Comment by jamesmontemagno** [comment]
So, this works fine on my Pixel 2XL in airplane mode.

May I recommend you loop through the ConnectionProfiles and let me know what comes up?

Do you have a VPN or anything setup on the device?

**Comment by jamesmontemagno** [comment]
The connectionprofiles will list all the type of active connections there are. What is output there in the list?

**Comment by Swdvader** [comment]
Ok. I downloaded the app and went to connectivity.  Attache are the 3 screen shots.  First is Cell + Wifi, second is just cell and third is airplane mode, where it shows local and cellular.

![screenshot_20181219-175526_xamarinessentials](https://user-images.githubusercontent.com/14371980/50253322-d8a37400-03b7-11e9-997c-7f8cf4b32732.jpg)
![screenshot_20181219-175533_xamarinessentials](https://user-images.githubusercontent.com/14371980/50253323-d8a37400-03b7-11e9-9015-f78170920c63.jpg)
![screenshot_20181219-175508_xamarinessentials](https://user-images.githubusercontent.com/14371980/50253324-d8a37400-03b7-11e9-9acf-7c1c23e754db.jpg)

**Comment by jamesmontemagno** [comment]
Looks like something on your device is returning a cellular connection... Samsung devices can be odd....

So I need for you to run some code on your device. Can you put this in your MainActivity.cs:

```csharp
var manager = Application.Context.GetSystemService(Context.ConnectivityService) as ConnectivityManager;
                     foreach (var network in manager.GetAllNetworks())
                        {
                            try
                            {
                                var capabilities = manager.GetNetworkCapabilities(network);

                                if (capabilities == null)
                                    continue;

                                // Check to see if it has the internet capability
                                if (!capabilities.HasCapability(NetCapability.Internet))
                                {
                                    
                                    // Doesn't have internet, but local is possible
                                    var info = manager.GetNetworkInfo(network);
                                    // add a breakpoint here and let me know what capabilities is and info. I need as much info as possible
                                    continue;
                                }
                            }
                            catch
                            {
                                // there is a possibility, but don't worry
                            }
                        }
```

**Comment by jamesmontemagno** [comment]
Interesting...

Can you tell me what: info.IsAvailable is?

I am thinking it is:

Airplane: false
Cell+Wifi: true
Wifi: true

But i want to confirm

**Comment by Swdvader** [comment]
Yes this what info.IsAvailable returns.  
Airplane: false
Cell+Wifi: true
Wifi: true

(Netwrokinfo.IsAvailable is obsolete. 'deprecated'.  I was using the below, but ActiveNetworkInfo.IsConnectedOrConnecting)  is now obsolete. 'deprecated'
I was hoping to not use anything that  is obsolete. 'deprecated'

 var ConnectivityManager = (ConnectivityManager)Application.Context.GetSystemService(Context.ConnectivityService);
            var ActiveNetworkInfo = ConnectivityManager.ActiveNetworkInfo;
            if (ActiveNetworkInfo != null && ActiveNetworkInfo.IsConnectedOrConnecting)
                {
                IsConnected = true;
            }
            else
            {
                IsConnected = false;
            }

**Comment by mattleibow** [comment]
I see the `IsAvailable` was _just_ deprecated in 28, so that is still good for pre-28 (although it should still work). Also the `ConnectivityManager.NetworkCallback` type they want us to use was only added in 21.

So pre 21, we have to use `IsAvailable`, 21-27 we can use `IsAvailable` or `NetworkCallback` and in 28+ they want us to use `NetworkCallback`.

Now... I am not sure that we _want_ to use a callback-type mechanism. We are trying to determine what networks are available at a point in time, so `IsAvailable` is just fine. I don't think they are going to remove it any time soon. 

However... We do have an event that we use to notify if the network changes. For this we can switch from a broadcast receiver to the `RegisterNetworkCallback` (21+) or  `RegisterDefaultNetworkCallback` (24+). What we need to determine is if we can get all the same events when _any_ network changes.

**Comment by jamesmontemagno** [comment]
Yeah, i think most of the code is just fine for now and we should update it over time though and put it on the backlog. The new APIs are really complicated :(

You don't want to use ActiveNetworkInfo  as it has issues with multi-sim phones :) I have done this for years now and Android is a pain :)

**Comment by jamesmontemagno** [comment]
At this point we have a PR in to fix this. Once that goes into master there is a development MyGet that you can get, else we will schedule for a release 1.0.1 soon.
