### ISSUE TITLE
No way to show permission rationale when getting location

### ISSUE THREAD

**Issue by RyanBuzzInteractive** [xamarin/Essentials#658]
### Description
When requesting permission it is recommended to show a rationale to the user before presenting them with the system dialog if it is not obvious why you are asking. In addition, on Android it is common to give extra information if it has been previously denied, to add more context.

Here is an example, particularly the ShouldShowRequestPermissionRationale bit.
https://blog.xamarin.com/requesting-runtime-permissions-in-android-marshmallow/

I understand that this may be complex to turn into a cross platform API, and it probably runs wider than just location permissions. The trouble is right now there is no control over the behaviour so we are left with either trying to manually get permissions before Essentials tries, not showing a rationale, or not using Essentials, as far as I can see.

Could we possibly have a way to set a rationale string which would be shown if possible, in the appropriate way for the platform?

**Comment by RyanBuzzInteractive** [comment]
That makes sense, I hadn't thought about it that way.

**Comment by jamesmontemagno** [comment]
Closing this one for now as it is covered in #504 and for now would recommend persmissions plugin if you need deeper integration :)

**Comment by danbo** [comment]
> 
> 
> Closing this one for now as it is covered in #504 and for now would recommend persmissions plugin if you need deeper integration :)

The current status of permissions and how it has changed should be noted in the official [documentation](https://docs.microsoft.com/en-us/xamarin/essentials/get-started?tabs=windows%2Candroid) to save people time from trying to upgrade from the existing standalone plugin.
