### ISSUE TITLE
Add reachability functionality for android

### ISSUE THREAD

**Issue by lavilaso** [xamarin/Essentials#660]
It would be nice to have for android the equivalent of [this](https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Connectivity/Connectivity.ios.reachability.cs), or failing that if it already exists, can someone tell me how to use it in my shared project?

**Comment by jamesmontemagno** [comment]
Please see documentation for Connectivity: https://docs.microsoft.com/en-us/xamarin/essentials/connectivity?context=xamarin%2Fxamarin-forms&tabs=android

and if you are looking for ping items see comments here: https://github.com/xamarin/Essentials/issues/334
