### ISSUE TITLE
Universal Resource Loader

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Essentials#664]
The current implementation of ResouceLoader allows to load resources only from the current assembly. 
I propose to add a new resource manager who can load resources from anywhere. For example, connected libraries, embedded resources and all that.
I think it would be very convenient.

For example, you use the Portable, or .net Standard library to create a UI, and you want to place a common image in it (let's call it MyPicture.png). Now we can not get it just by name. because its real name will be LibraryName.MyPicture.png, but I still wanted to get this resource by its original name.
Therefore, I always use my ResrouceLoad implementation.
So I thought maybe it would be a good idea to add it?

**Comment by KSemenenko** [comment]
Yes, like this, but more convenient to use. 
For example, add methods to work directly with the ImageSource, maybe for fonts, strings. Caching
For example, I sometimes load fonts into SkiaSharp, and caching them would be useful. What do you think @jamesmontemagno , it might be useful?

**Comment by KSemenenko** [comment]
By the way, this ResourceLoader will help here #652  to make it easier to load and cache tracks.

**Comment by mattleibow** [comment]
I'm closing this as I think we have got parts of this request in already.

To load files in the app package, we provide the `FileSystem.OpenAppPackageFileAsync`. Then, to "browse" these files, there is #1551.
For interop with ImageSource, this request needs to be done in the Xamarin.Forms repo as we cannot reference those types as we are the base library.
