### ISSUE TITLE
DeviceInfo.Idiom returning Phone on Tablets (Android)

### ISSUE THREAD

**Issue by danielccunha** [xamarin/Essentials#668]
### Description
I'm using the DeviceInfo API, and when I try to get the device's idiom on a tablet (AVD), it returns DeviceIdiom.Phone. I didn't test it in iOS, just changed to Device.Idiom (Xamarin)

### Steps to Reproduce
1. Check DeviceInfo.Idiom using Xamarin.Essentials on a Tablet

### Expected Behavior
Returns DeviceIdiom.Tablet

### Actual Behavior
Returning DeviceIdiom.Phone

### Basic Information

- Version with issue: 1.0.0
- Last known good version:
- IDE: VS 15.9.4
- Platform Target Frameworks: 
  - iOS:  11.1
  - Android: 8
- Affected Devices: Tablets (It works on Phones)

**Comment by mattleibow** [comment]
Just an FYI for when we look into this... There are quire a few checks and with the final check, I would say the device might be reporting that it is a phone:
https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs#L29-L73

@danielccunha What resolution and what AVD did you pick?

**Comment by danielccunha** [comment]
> Just an FYI for when we look into this... There are quire a few checks and with the final check, I would say the device might be reporting that it is a phone:
> https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs#L29-L73
> 
> @danielccunha What resolution and what AVD did you pick?
I'm using the Nexus 10 AVD, resolution 2560 x 1600 Xh-DPI

**Comment by jamesmontemagno** [comment]
@mattleibow checkout my PR

**Comment by MagicAndre1981** [comment]
I still get phone for [Tablet with Android 9](https://github.com/xamarin/Xamarin.Forms/issues/5708)

```
var device = DeviceInfo.Model;
var manufacturer = DeviceInfo.Manufacturer;
var deviceName = DeviceInfo.Name;
var version = DeviceInfo.VersionString;
var platform = DeviceInfo.Platform;
var idiom = DeviceInfo.Idiom;
var deviceType = DeviceInfo.DeviceType;

 Debug.WriteLine("device: {0}, manufacturer: {1}, deviceName: {2}, version: {3}, platform: {4}, idiom: {5}, deviceType: {6}", device, manufacturer, deviceName, version, platform, idiom, deviceType);

[0:] device: TOSHIBA WT8-A, manufacturer: TOSHIBA, deviceName: TOSHIBA WT8-A, version: 9, platform: Android, idiom: Phone, deviceType: Physical
```

**Comment by jamesmontemagno** [comment]
What are the device dimensions? Please open a new bug as well.

**Comment by MagicAndre1981** [comment]
@jamesmontemagno It is a 8" Tablet with 1280x800 resolution that originally came with Windows 8.1, was upgraded to Win10 and I dual boot it with a x86 Android 9 ROM to test Android apps (I use [adb over network](https://play.google.com/store/apps/details?id=mattiesworld.gotdns.org.adboverethernet&hl=en_US) to deploy the android part of XF app to the tablet and optimize layout with [Hotreload](https://github.com/AndreiMisiukevich/HotReload))

![image](https://user-images.githubusercontent.com/8274816/55378491-7ced9880-5519-11e9-9f3b-9834d8774111.png)
