### ISSUE TITLE
Emoji Version 11.0 support

### ISSUE THREAD

**Issue by gsmental** [xamarin/Essentials#671]
Emoji Version 11.0 supporting  by Twemoji, Google, EmojiOne, Samsung, Microsoft, Apple, Facebook

many times we need to show emoji in various places.
many we want used as a profile pic/avtar.

requirements:
* Unicode to png pic with resolution
* Unicode to bytes/stream/string64 pic with resolution.
* multiple emojis generation 

for reference
https://emojipedia.org/emoji-11.0/

i think you have already experience in this field. you can decide API structure better than me.

**Comment by jamesmontemagno** [comment]
This would be something that goes into Xamarin.Forms as it is custom to the user interface. Thank you for the suggestion though. Would open something there.
