### ISSUE TITLE
Device Informations : Wrong device name

### ISSUE THREAD

**Issue by Zackna** [xamarin/Essentials#675]
### Description
I'm using Xamarin.Essetials 1.0.0 on my project. I would get the device name but i'm getting the model instead.

### Steps to Reproduce

My viewmodel code:
```CSHARP
public class AccueilViewModel : INotifyPropertyChanged
    {
        private string telId;
        private string telName;
        private string telModel;

        public AccueilViewModel()
        {
            this.telId = string.Empty;
            this.telName = DeviceInfo.Name;
            this.telModel = DeviceInfo.Model;
        }
    ...
    }
```
My view code:
```XAML
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:EmployeeTracker.Views"
             xmlns:viewmodels="clr-namespace:EmployeeTracker.ViewModels"
             x:Class="EmployeeTracker.Views.Accueil"
             Title="Details">
    <ContentPage.BindingContext>
        <viewmodels:AccueilViewModel/>
    </ContentPage.BindingContext>
    <ContentPage.Content>
    <StackLayout Margin="0,10,0,0" Orientation="Vertical" HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand">
            <Label Text="Informations"/>

            <StackLayout Orientation="Horizontal">
                <Label Text="Id:"/>
                <Label Text="{Binding TelId}"/>
            </StackLayout>
            <StackLayout Orientation="Horizontal">
                <Label Text="Nom téléphone:"/>
                <Label Text="{Binding TelName}"/>
            </StackLayout>
            <StackLayout Orientation="Horizontal">
                <Label Text="Modèle téléphone:"/>
                <Label Text="{Binding TelModel}"/>
            </StackLayout>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

### Expected Behavior
The name and the model must be differents.

### Actual Behavior
The name and the model are the same (BLN-L21). My phone's name is "Honor 6X"

### Basic Information

- Version with issue: 1.0.0
- Last known good version: unknown
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - Android: Live player (Honor 6X) - Android 7.0 - API 24
- Nuget Packages: Xamarin.Essentials
- Affected Devices: Honor 6X

### Screenshots
Screenshot made from my phone, sorry for the size.
![image](https://user-images.githubusercontent.com/5212439/50693700-fae3f580-1037-11e9-8a1d-725145637f19.png)

**Comment by jamesmontemagno** [comment]
So, for "Model" we use Build.Model... which is what is set by the manufacturer. We can't do much there.

For Name we attempt to get the device name if there is one set and is available else we default to Model. That is what you are seeing here and this looks correct. 

If you look at "BLN-L21" it is the model of the Honor 6X

**Comment by Zackna** [comment]
I know this issue is close, thanks for the answer.
Just to be sure, for the name, only the customized name will get? 
My phone as the default name "Honor 6X", I have not changed it.

**Comment by jamesmontemagno** [comment]
So, it is unfortunate about the "name" of the device which is set by the user as it isn't supported by all manufacturer's as Android is crazy and they can do whatever they want :(

For converting the "model" to the "market name" you will want to look at open source libraries: https://github.com/jaredrummler/AndroidDeviceNames or https://github.com/dannycabrera/GetDroidModel they have to do a manual conversion on the names.

**Comment by Zackna** [comment]
Thanks a lot.
Have a nice day

**Comment by osicka** [comment]
I have had the same issue with certain android devices, on these I use the Bluetooth name instead which is the device name. Can this be returned instead of the model?

            BluetoothAdapter myDevice = BluetoothAdapter.DefaultAdapter;

            if (myDevice != null)
            {
                ret = myDevice.Name;
            }

**Comment by nunosantosgithub** [comment]
Using the BluetoothAdapter requires the "Bluetooth" permission.

To avoid that, I'm using on android:

```
var name = Android.Provider.Settings.Secure.GetString(MainActivity.Current.ContentResolver, "bluetooth_name");

if (!string.IsNullOrEmpty(name))
{
       return name;
}

return DeviceInfo.Name;
```

**Comment by ruby-verma** [comment]
I have had the same issue with android device (latest OS). I resolved it by getting the device name from Settings.Global https://developer.android.com/reference/android/provider/Settings.Global#DEVICE_NAME

var name = Android.Provider.Settings.Global.GetString(Xamarin.Essentials.Platform.AppContext.ContentResolver, "device_name");
if (!string.IsNullOrEmpty(name))
{
          return name;
}

Here this issue can be resolve by Changing https://github.com/xamarin/Essentials/blob/afec3caf260acc75ae7317ce70579b4e1c7b55a2/Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs#L115
to 

        {
            // DEVICE_NAME added in System.Global in API level 25
            // https://developer.android.com/reference/android/provider/Settings.Global#DEVICE_NAME
            if (Essentials.Platform.HasApiLevelNMr1)
                return Settings.Global.GetString(Essentials.Platform.AppContext.ContentResolver, name);
            else
                return Settings.System.GetString(Essentials.Platform.AppContext.ContentResolver, name);
        }
@jamesmontemagno please check, if this make sense.

Thanks,
Ruby

**Comment by AlejandroCoronadoRubio** [comment]
> I have had the same issue with android device (latest OS). I resolved it by getting the device name from Settings.Global https://developer.android.com/reference/android/provider/Settings.Global#DEVICE_NAME
> 
> var name = Android.Provider.Settings.Global.GetString(Xamarin.Essentials.Platform.AppContext.ContentResolver, "device_name");
> if (!string.IsNullOrEmpty(name))
> {
> return name;
> }
> 
> Here this issue can be resolve by Changing
> 
> https://github.com/xamarin/Essentials/blob/afec3caf260acc75ae7317ce70579b4e1c7b55a2/Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs#L115
> 
> 
> to
> ```
>     {
>         // DEVICE_NAME added in System.Global in API level 25
>         // https://developer.android.com/reference/android/provider/Settings.Global#DEVICE_NAME
>         if (Essentials.Platform.HasApiLevelNMr1)
>             return Settings.Global.GetString(Essentials.Platform.AppContext.ContentResolver, name);
>         else
>             return Settings.System.GetString(Essentials.Platform.AppContext.ContentResolver, name);
>     }
> ```
> 
> @jamesmontemagno please check, if this make sense.
> 
> Thanks,
> Ruby

Awesome worked really good, thank you very much!!!

> I have had the same issue with certain android devices, on these I use the Bluetooth name instead which is the device name. Can this be returned instead of the model?
> 
> ```
>         BluetoothAdapter myDevice = BluetoothAdapter.DefaultAdapter;
> 
>         if (myDevice != null)
>         {
>             ret = myDevice.Name;
>         }
> ```

That's a very good idea, especially when you cannot change the device name (android 8.1 in my case).
