### ISSUE TITLE
Introduce GPS status (enabled/disabled) and GPS capability API to GeoLocation class

### ISSUE THREAD

**Issue by jges42** [xamarin/Essentials#678]
**Description:**
At the moment to be clean in using the Geolocation API you have to check if GPS is enabled or even available on the device using native Android code. This prevents me from switching from my own platform specific Implementations for a GeoLocationProvider to Xamarin Essentials. 

**API Declaration:**
```
Task<bool> GeoLocation.CheckGpsAvailability()
Task<bool> GeoLocation.CheckGpsEnabled()

```

**Comment by jamesmontemagno** [comment]
This will be bundled into this: https://github.com/xamarin/Essentials/issues/77
