### ISSUE TITLE
[Feature Request] DeviceId as implemented by Acr.DeviceInfo

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Essentials#679]
Currently I am using a mix of Xamarin.Essentials and ACR.DeviceInfo to get my info about my device.

The only feature missing from making me make the full switch is the DeviceId as implemented by this plugin https://github.com/aritchie/deviceinfo

This is a feature request, what do others think?

**Comment by jamesmontemagno** [comment]
Please see my blog on this topic: https://montemagno.com/unique-device-id-for-mobile-apps/ 

We discussed this heavily in #61  and will not be including this functionality.
