### ISSUE TITLE
ConnectivityChanged event and battery

### ISSUE THREAD

**Issue by stesvis** [xamarin/Essentials#684]
This is just a question as I am trying to investigate some issues i am having with battery consumption.

Is it possible that using the ConnectivityChanged event keeps the app "alive" and causes more battery consumption than normal?

Thanks for any insights!

**Comment by mattleibow** [comment]
It might be the case, but then you can just detach the event. Once all event handlers are removed, the connectivity listeners are shut down.

But, looking at the code, the listeners are pretty standard. What platform are you seeing this on?

**Comment by stesvis** [comment]
So far i've received reports from users on iOS.
I'll have to find a way to detach and attach the listener when needed.

"When needed" is the hard part...

**Comment by mattleibow** [comment]
Depending on where you are using this, you might be able to just unsubscribe when the app goes to sleep, and re-subscribe when the app resumes. If it is a page, then you can do the same for appearing or disappearing.

If things are used all over the place, you can actually create a proxy event. You never actually subscribe to the essentials event for the pages and views, but subscribe to the app. Then, the app subscribes to the event and will alert the pages:

```csharp
class ApplicationClass {
    public static event EventHandler<...> ConnectionChanged;

    public static void OnAppWakeUp() {
        Xamarin.Essentials.Connectivity.Changed += OnConnectivityChanged;
    }
    public static void OnAppSleep() {
        Xamarin.Essentials.Connectivity.Changed -= OnConnectivityChanged;
    }
    private static void OnConnectivityChanged(object sender, ... e) {
        ConnectionChanged?.Invoke(null, e);
    }
}
```

Then, in your pages and views:

```csharp
class PageClass {
    public void DoSomething() {
        ApplicationClass.ConnectionChanged += TheRealHandler;
    }
    public void HidingPage() {
        ApplicationClass.ConnectionChanged -= TheRealHandler;
    }
    private static void TheRealHandler(object sender, ... e) {
        // ...
    }
}
```

That rough code should give you an idea, but obviously you no longer have fine control of the subscription and it will always be subscribed when the app is running. But, when the app is closed, you know for certain the events are shut down.

This might not be the best case if you only have a few pages that check for internet. If that is the case, then you just need to go around and make sure that you are detaching events.

**Comment by mattleibow** [comment]
On a totally separate note, you can detect if you are detaching by tracking the attach/detach:

```csharp
class ApplicationClass {
    private static eventCounter = 0;
    public static event EventHandler<...> ConnectionChanged {
        add {
            Xamarin.Essentials.Conectivity.Changed += value;
            Console.WriteLine($"Attached event: {++eventCounter}");
        }
        remove {
            Xamarin.Essentials.Conectivity.Changed -= value;
            Console.WriteLine($"Attached event: {--eventCounter}");
        }
    }
}
```

That may help, not sure if it will compile, but it may give you an idea. 

This is not the same as my previous comment, as this event is a pure proxy and all handlers are really being attached to the essentials event. But, we get the opportunity to log the attaches and detaches.

**Comment by stesvis** [comment]
I am using Xamarin Forms and Prism (if that matters), my main page is a TabbedPage.
In that tabbed page I attach the ConnectivityChanged event and never detach it.

I use it because people can work offline, and when their internet is back, the app will detect it and sync with the server.

I guess that I COULD move that to App.xaml.cs and attach/detach the handler in Sleep/Resume.

Would that help saving battery?

I also use AppCenter for PushNotifications, so there is a PusNotificationReceived event handler, but obviously you can't detach that or you won't get notifications.

**Comment by stesvis** [comment]
It seems like the ConnectivityChanged event always fires even when detached.
Here's my "simplified" code in App.xaml.cs:

```
protected override async void OnStart()
{
	Connectivity.ConnectivityChanged += Connectivity_ConnectivityChanged;
}

protected override void OnSleep()
{
	Connectivity.ConnectivityChanged -= Connectivity_ConnectivityChanged;
}

protected override async void OnResume()
{
	Connectivity.ConnectivityChanged += Connectivity_ConnectivityChanged;
}

private async void Connectivity_ConnectivityChanged(object sender, ConnectivityChangedEventArgs e)
{
}
```

* I attach the handler **OnStart**
* I detach it **OnSleep**
* I reattach it **OnResume**

Then I tried this:

* Start the app
* Close it (background mode): OnSleep fired, handler detached
* Switch to Airplane Mode
* At this point Connectivity_ConnectivityChanged fired (saying internet is gone)

**Why did it fire again? I detached it OnSleep, how is this possible?**

I set breakpoints and the `Connectivity.ConnectivityChanged += Connectivity_ConnectivityChanged; `was not called anywhere else.

Any help is much appreciated, thank you.

**Comment by mattleibow** [comment]
Just check, maybe it fires start and then resume... Start might be when the app is created, and then resume when it moves into the foreground.
The docs doesn't quite say exactly, but appears to only fire resume when coming out of sleep... https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/app-lifecycle#Lifecycle_Methods

**Comment by stesvis** [comment]
Yes that wasn't the case tho. It fired at start and tried sleep and resume a few times.
Then went to airplane mode while sleeping and it still fired...

**Comment by jamesmontemagno** [comment]
In your sample @stesvis  you are registering twice, so you will always get an event back. Only register OnResume and OnSleep.

**Comment by stesvis** [comment]
Thankks @jamesmontemagno 
But i don't think i can use the ConnectivityChanged event at this point.
I use it do sync with the web service (sometimes they work offline), and it the connectivity changes while the app is sleeping it will never fire.
In my case it probably works best to check if a sync is needed OnResume, and if there is internet attempt to do it.
Provided that listening for connectivity changes is what's causing low battery life..

**Comment by jamesmontemagno** [comment]
The best idea is to setup the notification for then the app is running as you most likely will not get a notification when the app is in the background (this is expected as most OS do not allow this). Listening will not impact the battery life as it is not an active thread or spinning cycles at all. The code is pretty battle tested for about 4 years and have not had this complaint at all. 

Will close out for now as feedback has been provided on implementation.
