### ISSUE TITLE
Unable to upgrade Android Packages Above Versions 27.0.2.1

### ISSUE THREAD

**Issue by AmitManchanda** [xamarin/Essentials#687]
### Description
I was using Android.Compat at 28.0.0.1 version but to install essentials I need to downgrade it from 28.0.0.1 to 27.0.2.1

### Steps to Reproduce

1. Install Xamarin.Essentials for Xamarin.Android with using the updated Libraries of AppCompat and other Android Libraries. 
2. To Install Essentials, Downgrade the Libraries to 27.0.2.1.

### Expected Behavior
It should work with all the libraries above minimum versions required.

### Actual Behavior
Throwing 

Error	NU1107	Version conflict detected for Xamarin.Android.Support.Compat. Install/reference Xamarin.Android.Support.Compat 28.0.0.1 directly to project Abc.Android to resolve this issue. 
 Abc.Android -> Xamarin.Android.Support.v7.MediaRouter 28.0.0.1 -> Xamarin.Android.Support.v7.Palette 28.0.0.1 -> Xamarin.Android.Support.Compat (= 28.0.0.1) 
 Abc.Android -> Xamarin.Android.Support.Design 27.0.2.1 -> Xamarin.Android.Support.Compat (= 27.0.2.1).	Abc.Android

### Basic Information

- Essential Version with issue: 1.0.1
- IDE: Visual Studio 2017, Version 15.9.5
- Android Support Library Version: 27.0.2.1 (Supported) and 28.0.0.1 (Not Supported)

**Comment by AmitManchanda** [comment]
I tried it using this way as well but nuget didn't install Essentials then.

**Comment by AmitManchanda** [comment]
I had applied the same, but still it is throwing me same error.

**Comment by jamesmontemagno** [comment]
By default we installed: 27.0.2.1

I did file -> new

I added: Xamarin.Android.Support.CustomTabs -> 27.0.2.1 and then Xamarin.Android.Support.Compat -> 27.0.2.1

Then I updated all of them and it worked great. Here is 
[App7.zip](https://github.com/xamarin/Essentials/files/2803885/App7.zip)

**Comment by JRGit4UE** [comment]
@AmitManchanda @AmitManchanda  Is this a Nuget issue ('does not resolve versions properly') or a Xamarin issue (why downgrade and then upgrade again)?
Personally _I would like to add Xamarin.Essentials **without** having to remember the **magic tweaks**_
because I have EFCore2.2 and Xamarin.Forms 3.5.0.... in my project, and I am 100% sure, that if I start downgrade things, my project will not work anymore...

**Comment by jamesmontemagno** [comment]
This is a nuget issue. Simple use the stuff I have here: https://github.com/xamarin/Essentials/issues/687#issuecomment-457671569
