### ISSUE TITLE
Use the new UIFeedbackGenerator for iOS for better haptic feedback support

### ISSUE THREAD

**Issue by stanios** [xamarin/Essentials#688]
Use the new UIFeedbackGenerator for iOS in order to produce more controlled haptic feedback. As it stands the Vibration class plays the default vibration for iOS which is -500ms- and there's no way to change that. For a lot of cases 500ms is way too much, the new UIFeedbackGenerator offers 3 types of vibrations.

https://developer.apple.com/documentation/uikit/uifeedbackgenerator

**Comment by jamesmontemagno** [comment]
This is a tricky subject and I already investigate it: https://github.com/jamesmontemagno/VibratePlugin/issues/3

The issue is that it is only in some OS versions and on only some devices. There is no API to actually detect if it is available, which is a shame.

**Comment by mattleibow** [comment]
We might be able to use the ObjC interop to find out if the type exists...

**Comment by jamesmontemagno** [comment]
Sounds scary

**Comment by jamesmontemagno** [comment]
Talked about this today on our call, due to the complexity and limitations we will not be able to roll this into the API itself. Thank you for your feedback on it :)
