### ISSUE TITLE
Detecting wifi connection on ios

### ISSUE THREAD

**Issue by apicquot** [xamarin/Essentials#690]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
I am trying to detect WiFi connection and use the current method:

`public bool IsWifiConnected()
        {
            IEnumerable<ConnectionProfile> profiles = Connectivity.ConnectionProfiles;
            return profiles.Contains(ConnectionProfile.WiFi);
        }`

Unfortunately, the function returns true before the connection is fully established. Is there a way to make a method that connection is fully working  ?

### Steps to Reproduce

1.  
2.  
3.  

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  <12.1 -->

- Affected Devices: iphone 6 and above

**Comment by jamesmontemagno** [comment]
That is the correct approach, you can check the NetworkAccess to see if it is connect to the Internet. Often the systems may report WiFi when connecting or even an in between state. Unfortunately there isn't any super bullet proof way of knowing.
