### ISSUE TITLE
Add ability to share URL

### ISSUE THREAD

**Issue by jefffhaynes** [xamarin/Essentials#691]
There are other similar enhancements but nothing about simply sharing a URL.  Sharing a URL is essentially built-in and there's simply no accommodation in the interface to pass one.

**Comment by jamesmontemagno** [comment]
We support this today! Just set the Uri on the ShareTextRequest
https://docs.microsoft.com/en-us/xamarin/essentials/share?context=xamarin%2Fxamarin-forms&tabs=android

**Comment by jefffhaynes** [comment]
Ugh. Not sure how I missed that. Thanks!


________________________________
