### ISSUE TITLE
DeviceInfo.DeviceType doesn't work properly on Visual Studio Emulator For Android.

### ISSUE THREAD

**Issue by dronishe** [xamarin/Essentials#694]
### Description

DeviceInfo.DeviceType returns DeviceType.Physical when runing on Visual Studio Emulator For Android.

### Steps to Reproduce
1. Create empty Xamarin android project
2. Init Xamarin.Essentials
3. Call DeviceInfo.DeviceType

### Expected Behavior
As written in documentation I expect to get DeviceType.Virtual for app  running in Emulator

### Actual Behavior
Getting DeviceType.Physical for app running in Emulator

### Basic Information

- Version with issue: 1.0.1
- Last known good version:
- IDE: Microsoft Visual Studio Community 2017 (ver. 15.9.5)
- Platform Target Frameworks: 
  - Android: 8.1 

- Android Support Library Version: 27.0.2.1

### Reproduction Link

https://github.com/dronishe/XamarinEssentialDeviceTypeTest

**Comment by dronishe** [comment]
As I can see none of the checks for Emulator in GetDeviceType method in DeviceInfo.android.cs is passed for visual studio emulator for android. 
It seems that additional check should be added to this method:

    Build.Manufacturer == "VS Emulator"

**Comment by tobus2012** [comment]
With the BlueStack emulator on PC the configured phone indicates that it is a real phone and yet it is not a real phone.

How to differentiate a device from an emulator
