### ISSUE TITLE
Extra feature: Clipboard changed event

### ISSUE THREAD

**Issue by SaskiaL** [xamarin/Essentials#696]
I would like to have a clipboard changed event. So that when another app puts something on the clipboard, that my app can pick it up and do something with it.

For instance, if a device has a hardware scanner that scans barcodes and puts the result on the clipboard, our app should get the read barcode.

I have tried to use my old code for the change event ((AddPrimaryClipChangedListener)) together with Clipboard, but then the changed event is no longer triggered.

Kind regards,
Saskia

// Essentials Team Info
Researched a bit:
* Android: Use the [Manager Listener](https://developer.android.com/reference/android/content/ClipboardManager)
* UWP: Easy event to register for [docs](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.clipboard.contentchanged)
*iOS: Need [NSNotificationCenter Observer](https://developer.apple.com/documentation/uikit/uipasteboard#//apple_ref/c/data/UIPasteboardChangedNotification)

API:
```csharp
public static event EventHandler<ClipboardChangedEventArgs> ClipboardChanged;

 public class ClipboardChangedEventArgs: EventArgs
    {

    }
```

We don't need to return any information in the eventargs, because our API should return this. It is a generic clipboard changed, we don't know if it is text or other items....

**Comment by Mrnikbobjeff** [comment]
On IOS this feature might require setting up some code in the app initialization function. Should not be a problem on Android and iOS

**Comment by jamesmontemagno** [comment]
Added documentation, should be pretty easy to do :) Up for grabs :)

**Comment by Mrnikbobjeff** [comment]
Am working on it, a pr should be up before the end of the week 👍

**Comment by jamesmontemagno** [comment]
@Mrnikbobjeff can you base it off of the 1.1.0 branch :)

**Comment by manishkungwani** [comment]
@jamesmontemagno @Mrnikbobjeff looks like the code and docs were done here - https://github.com/xamarin/Essentials/pull/720

What's pending, if anything?
If so, can I pick it up and finish it off.

**Comment by SaskiaL** [comment]
I tried to install version 1.4.0-pre2 to try the new event, but got this error message:
Failed to add reference. The package 'Xamarin.Essentials' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC.

Is this a problem with the package? Or do I need to install extra packages?

Thanks, Saskia

**Comment by manishkungwani** [comment]
Hi,
I'm trying to use the package as well, with no luck.
If this is an open issue, can you please direct me and I will try to fix it.
With Warm Regards,Manish Kungwani 

    On Tuesday, 28 January, 2020, 03:50:40 pm IST, SaskiaL <notifications@github.com> wrote:  
 
 
I tried to install version 1.4.0-pre2 to try the new event, but got this error message:
Failed to add reference. The package 'Xamarin.Essentials' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC.

Is this a problem with the package? Or do I need to install extra packages?

Thanks, Saskia

**Comment by manishkungwani** [comment]
Hi,
I'm trying to use the package as well, with no luck.
If this is an open issue, can you please direct me and I will try to fix it.

With Warm Regards,Manish Kungwani 

    On Thursday, 13 February, 2020, 05:58:51 pm IST, manish kungwani <manishkungwani@yahoo.com> wrote:  
 
 Hi,
I'm trying to use the package as well, with no luck.
If this is an open issue, can you please direct me and I will try to fix it.
With Warm Regards,Manish Kungwani 

    On Tuesday, 28 January, 2020, 03:50:40 pm IST, SaskiaL <notifications@github.com> wrote:  
 
 
I tried to install version 1.4.0-pre2 to try the new event, but got this error message:
Failed to add reference. The package 'Xamarin.Essentials' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC.

Is this a problem with the package? Or do I need to install extra packages?

Thanks, Saskia

**Comment by SaskiaL** [comment]
I have added the package 1.4.0 pre2 again and this time it worked.
I think I had to update some other packages. I'm sorry, I don't remember which package(s) exactly.
I started with a new app and tried it there and that worked. That gave me the idea to check the other nuget packages.

I tried the new onchange event and it works like a charm.

Thanks, Saskia
