### ISSUE TITLE
Browser - Add function to get UserAgent string

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Essentials#701]
### Description
I think it would be convenient to get UserAgent from the browser

**Comment by jamesmontemagno** [comment]
You could only really get it for the webview inside of your application. There could be multiple browsers installed and we can't query that information at all.

If there is an API available that you find then let us know. To my knowledge this isn't available.

**Comment by KSemenenko** [comment]
It's for Android:
``` cs
UserAgent = Java.Lang.JavaSystem.GetProperty("http.agent");
```
It's for iOS:
``` cs
UIWebView agentWebView = new UIWebView();
UserAgent = agentWebView.EvaluateJavascript("navigator.userAgent");
```
It's for UWP:
``` cs
var deviceInfo = new EasClientDeviceInformation();
UserAgent = string.Format("Mozilla/5.0 ({0}; ARM; Trident/7.0; Touch; rv11.0; IEMobile/11.0; {1}; {2}) like Gecko",
deviceInfo.OperatingSystem, deviceInfo.SystemManufacturer, deviceInfo.SystemProductName);
```

Here is the code I use to get this data. @jamesmontemagno

**Comment by mattleibow** [comment]
What is the use case for this anyway? On UWP you are almost making a custom UA. At this point, it is probably better to just create your own for your purposes - especially since you are not a browser.

**Comment by jamesmontemagno** [comment]
Yeah this seems like more of a feature for Xamarin.Forms itself on the Webview, I would open a feature request there.

**Comment by Toldy** [comment]
⚠️ Don't use UIWebViews anymore  :)
