### ISSUE TITLE
Connectivity - Connection speed

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Essentials#702]
I think it would be good to get a quality connection. For example, approximate connection speed, or enum for example
Good speed
Bad speed

In this case, you can understand, for example, that the connection is slow and you should not make requests to the server.

**Comment by jamesmontemagno** [comment]
For connection speed, this API is all of the place as it is not available on iOS, only for WiFi on Android, and UWP I think all.

For WiFi status this is also problematic because it isn't available on iOS so we have decided to leave these out. Thanks for the suggestion though.
