### ISSUE TITLE
Calendar API

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Essentials#703]
### Description
It would be nice to be able to add events to the calendar to the user.

It might also be nice to be able to change the events in the user's calendar.
In my opinion it would be a good functional.

**Comment by KSemenenko** [comment]
https://docs.microsoft.com/en-us/xamarin/ios/platform/eventkit
https://docs.microsoft.com/en-us/xamarin/android/user-interface/controls/calendar

**Comment by pamela032709** [comment]
Hi, will this be implemented? it would be awesome!

**Comment by nickrandolph** [comment]
Just proposed spec for read only calendar api as a first stage to supporting calendar api - https://github.com/xamarin/Essentials/issues/996

**Comment by newky2k** [comment]
#996 provides a spec for this feature, so closing to reduce duplication
