### ISSUE TITLE
Browser does not open on UWP

### ISSUE THREAD

**Issue by NPadrutt** [xamarin/Essentials#706]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
On UWP the implementation for opening the browser does nothing. Android works with the same code.

### Steps to Reproduce

1.  Start Demo App
2.  Click on Open Browser
3.  See that nothing happens.

### Expected Behavior
The Browser should open and the github page should launch

### Actual Behavior
Nothing happens

### Basic Information

- Version with issue: 1.0.1
- Last known good version:
- IDE: Visual Studio 15.9.6
- Platform Target Frameworks: 
  - UWP:  Min: 16299, Target 17763

### Reproduction Link

[App1.zip](https://github.com/xamarin/Essentials/files/2847776/App1.zip)

**Comment by jamesmontemagno** [comment]
Was able to run your sample with no issues here.

**Comment by NPadrutt** [comment]
hey @jamesmontemagno 
I checked it on another computer and there it worked as well.. so it seems to have to do with my computer.
thanks for checking.
