### ISSUE TITLE
Compose Email throws Exception on UWP

### ISSUE THREAD

**Issue by NPadrutt** [xamarin/Essentials#707]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
I try to compose an email message in a UWP application, but an error is thrown. On Android the same code works as expected.

### Steps to Reproduce

1. Start the reproduction app
2. click on Send Email
3. See the error in the output

### Expected Behavior
Either create an Email with the default Email app or offer a dialog to select the email app to use.

### Actual Behavior
Excpetion is thrown:
```
System.ArgumentException: Value does not fall within the expected range.
   at Xamarin.Essentials.Email.PlatformComposeAsync(EmailMessage message)
   at App1.Business.Class1.SendEmail()The program '[30188] App1.exe' has exited with code -1 (0xffffffff).
```

### Basic Information

- Version with issue: 1.0.1
- Last known good version:
- IDE: Visual Studio 15.9.6
- Platform Target Frameworks: 
  - UWP:  Min: 16299, Target: 17763
- Android Support Library Version: 

### Reproduction Link

[App1.zip](https://github.com/xamarin/Essentials/files/2847779/App1.zip)

**Comment by jamesmontemagno** [comment]
I was able to run your sample projects locally with no issues here....

**Comment by NPadrutt** [comment]
hey @jamesmontemagno 
I checked it on another computer and there it worked as well.. so it seems to have to do with my computer.
thanks for checking.

**Comment by SuNNjek** [comment]
I managed to reproduce the bug [here](https://github.com/SuNNjek/Xamarin.Essentials-Crash)

It seems to happen when there are empty email addresses in the Message object. While I know this shouldn't happen I had this problem in an application where you could leave the CC and BCC empty, causing the app to crash.

**Comment by jamesmontemagno** [comment]
Thanks @sunnjek, easy fix.
