### ISSUE TITLE
Request: xamarin.mac support For Xamarin essentials

### ISSUE THREAD

**Issue by mdonogma** [xamarin/Essentials#708]
Given xamarin.mac For Xamarin.forms has been available for more than 18 months - when will the team start looking at adding xamarin.mac support For Xamarin.essentials packages.

Solving oAUTH would be 1'st priority as cannot build enterprise app with xamarin.mac (xamarin forms implementation) without authentication

**Comment by jamesmontemagno** [comment]
Thanks for the request. We are investigating support for other platforms via this issue: https://github.com/xamarin/Essentials/issues/662
