### ISSUE TITLE
Biometrics API

### ISSUE THREAD

**Issue by moljac** [xamarin/Essentials#71]
# Fingerprint API 

### Description

API for Fingerprint scanning.

> VS bug [#735680](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735680)

**Comment by mattleibow** [comment]
I would also say biometrics. on UWP we have Windows Hello, which could basically be anything in the world... face from my surface, fingerprint from my laptop, DNA tester from my secret bunker running Windows IoT...

**Comment by jgiacomini** [comment]
Maybe we name it biometrics and in the first version we only expose fingerprint.

**Comment by jgiacomini** [comment]
I have to develop the abstraction of finguerprint this week for my project.
If you want I can take this one.

**Comment by jgiacomini** [comment]
I just found this plugin which implement finger print reading on the 3 OS : https://github.com/smstuebe/xamarin-fingerprint

**Comment by smstuebe** [comment]
@jgiacomini 4 OS :wink:

**Comment by Redth** [comment]
Just adding a note here.... Android is actually calling their bits 'Biometrics' now too for what used to just support Fingerprint.  I think this helps validate the API naming we had in mind.

**Comment by CarlosMobileAppDeveloper** [comment]
As part of this feature, for security reasons, you should also be able to detect if a new Fingerprint or FaceID has been added. 
Why? If you are using biometrics for authentication, and a new biometric fingerprint or face is added, the user should be required to confirm that new biometric option is valid for authentication in your app.

**Comment by KSemenenko** [comment]
maybe api for FAceID will be good?

**Comment by jrahma** [comment]
This will be great but it should have the following:

1. Verify the fingerprint / face recognition.
2. Get the fingerprint / face recognition and save in employee database for example to verify and authenticate, for example login with face recognition or fingerprint time attendance

**Comment by developer9969** [comment]
Hi
This will be a fantastic feature!! We are stuck with plugins out there that are not longer been supported 
and do not work when coming from the background.
Basically there is not a single xamarin forms plugin that works properly including https://github.com/smstuebe/xamarin-fingerprint

Please give us the basic Biometrics for android/iOS first and build it up as you go along.

All the features other people mentioned are great but not if they have to delay the functionality for ages!!!

Great work!!!

**Comment by alan-araya** [comment]
I agree with @developer9969 the only alternative to this is xamarim-fingerprint. Would be very nice to have this feature on Xamarim.Essentials as Fingerprint is a very common thing this days.

**Comment by DeerSteak** [comment]
xamarin-fingerprint is pretty broken right now. It's throwing exceptions on any device running Android 9 and any non-Samsung device running Android 8 or lower. A Java.Lang.Exception that indicates the device connected isn't a Samsung device. Even wrapping the Xamarin.Forms code in a try/catch block doesn't prevent crashes.

**Comment by Lydecker** [comment]
I 100% agree, that this now an 'Essential' feature for most apps today... Would be great to see this implemented please!

**Comment by anotherlab** [comment]
I would like to see this in Essentials.  It makes sense to expose something intrinsically hardware related to Essentials.  It looks like work on xamarin-fingerprint has stalled.

**Comment by ndastur** [comment]
@jamesmontemagno can I ask if there are any plans to make this part of XE. And possibly if there is a timeline?

**Comment by Redth** [comment]
We do want to add this, but I think it’s safe to assume we will wait until Essentials depends directly on AndroidX and we can use the new biometric AndroidX library.

**Comment by developer9969** [comment]
@Redth great any timeline about the androidx dependency

**Comment by smstuebe** [comment]
I've already done that and released a pre release package with AndroidX. Unfortunately the priorities of MS for supporting AndroidX stable, are not that high :( So I had to create the binding on my own.
Feel free to test and give feedback: https://www.nuget.org/packages/Plugin.Fingerprint/2.0.0-alpha.2

**Comment by ernestoyaquello** [comment]
Any news about this?

**Comment by Mikilll94** [comment]
Any update on this?

**Comment by AndreiZachi** [comment]
UP

**Comment by chaoyebugao** [comment]
Any progress?

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.

**Comment by Happypig375** [comment]
@jfversluis The focus shouldn't be on .NET MAUI as it does not have sensors planned
https://github.com/dotnet/maui/issues/778#issuecomment-881156094
> We have no current plans for this, but do check out Shiny which handles BLE and will be supporting MAUI in the future! https://github.com/shinyorg/shiny
