### ISSUE TITLE
Xamarin.Essentials Launcher does not work for multiple apps

### ISSUE THREAD

**Issue by marcelovidigal** [xamarin/Essentials#710]
Bug report best practices: Submitting Issues

Description

Most of the tests the application does not open. For some reason I do not know the Lyft example app works perfectly, but when I try other apps installed on the device the feature does not work, what I'm trying is to open the application and if it is not installed open the store, pointing to the app to be installed . Is there a way to find out which app's URI is registered? how to get around this? and if the app is not installed direct the store to install.

Steps to Reproduce

1. I'm testing the opening of this app https://play.google.com/store/apps/details?id=siisp.ma.gov.br.siisp.
2. How to discovery a URI from a APP?

**Comment by jamesmontemagno** [comment]
Apps must implement custom URIs and deep linking. It is up to the app developer to implement and document it: https://developer.android.com/training/app-links/deep-linking
