### ISSUE TITLE
Essentials- Geolocation Issue

### ISSUE THREAD

**Issue by vyasaraj999** [xamarin/Essentials#713]
Android permission issue-

Setting up the Geolocation to get a current list of locations using the Essentials geolocation is not working.
1. selecting the button to get the current location when there is no permission set for location on first installation.
2.Permission popup is shown, when pressing ok or deny the spinner keeps on loading. no locations are displayed it shows the spinner.
3.closing the app and opening it again works fine 

Note- Issue is only with the permission in Android, IOS works fine.

**Comment by jamesmontemagno** [comment]
Do you have a code sample?

It seems as though you didn't place the code for permissions as outlined in the getting started guide: https://docs.microsoft.com/en-us/xamarin/essentials/get-started?context=xamarin%2Fxamarin-forms&tabs=windows%2Candroid

**Comment by vyasaraj999** [comment]
yes i missed the setup for permission method on the activity

Thanks for the help..!!

**Comment by nguyenthanhliemfc** [comment]
Get current location not working on Xiao Mi Phone.
It's only show an icon on status bar in very short time and disappear

**Comment by vyasaraj999** [comment]
do you have the code sample that we can look at?

**Comment by nguyenthanhliemfc** [comment]
Yes @vyasaraj999 this is my sample app [LINK](https://github.com/nguyenthanhliemfc/PlacesContact)

**Comment by vyasaraj999** [comment]
Try changing in your NearbySearch method line - 48 
GeolocationRequest request = new GeolocationRequest(GeolocationAccuracy.Medium, TimeSpan.FromMilliseconds(500));
this was the issue it couldn't pass through, just changed the request type

**Comment by nguyenthanhliemfc** [comment]
Thank you @vyasaraj999 . It's running good!

**Comment by AshishInnovantes** [comment]
Please reopen this issue as am also facing the same problem. Below is my code please check


                    var request = new GeolocationRequest(GeolocationAccuracy.Medium, TimeSpan.FromMilliseconds(500));


                    var location = await Geolocation.GetLocationAsync(request);
                    if (location != null)
                    {
                        attendance.SignInLat = location.Latitude.ToString();
                    }
                   else
                    { //prompt that location not recieved}
