### ISSUE TITLE
Improvements to Text-to-Speech

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#715]
For next rev to have: 
•	Get a list of all voices on the system, including identifier, name and language.
•	Find a voice based on its identifier.
•	Get the default voice for a given language.
•	Find the language of the currently selected voice.
•	Find out whether the system is currently speaking or not.
•	Silence any current speech.
•	Speak a string with a given voice, and a given rate.
•	Find the default rate for the selected voice.
•	Allow TTS to work even if the phone is on silent.

**Comment by rscholey** [comment]
Need a way to set the Speak Rate similar to that used in James Text to speech plugin.  I tried the Xamarin Essentials on my Xamaroid phone and it sounds like the lady speaker just took in air from a helium balloon and changing the picture didn't improve things at all.  Have to give up on the Essentials plug in for now until more ways to control are there.

**Comment by jamesmontemagno** [comment]
@rscholey can you open a bug for what you are experiencing so we have more information about the code you are running and also the device you are running it on. From what I have seen it plays back just fine on devices as we use the default speed.

**Comment by rscholey** [comment]
@jamesmontemagno - Can you give an example of how you set the default speed?  I see only two parameters available:  Volume and Pitch.  In my case it works great on iOS but not on an Asus Android phone with OS 8.0.0  Code is Xamarin forms as follows:  

            var settings = new SpeechOptions() 
            {
                Volume = (float?)0.75,
                Pitch = (float)1.0
            };
            await TextToSpeech.SpeakAsync(msg, settings);

**Comment by EmilAlipiev** [comment]
I feel like one of those improvements were already in old texttospeech plugin. If my android phone didnt have tts locale installed for requested language it was popping up to get or install it. Now it just doesnt do anything. I am not sure if it was plugin or my old Sony xperia was handling it but now I have samsung s10 and it doesnt handle

**Comment by ivmirx** [comment]
> Get the default voice for a given language.

It would be great to get a list of available TTS voices if possible. Recently I've got a support request from an Android user complaining that my app used a female voice while all the other apps used a male one.

Another frequent problem is Samsung phones using their own TTS engine that (sometimes?) doesn't support "foreign" languages: I have a language-learning app that needs Spanish TTS while users' operating systems are usually in English. The workaround is to switch to Google's TTS in Android's settings but if it's technically possible to do it from inside the app, it would help a lot.

Thank you!

**Comment by ivmirx** [comment]
> Allow TTS to work even if the phone is on silent.

I've investigated that one on iOS/ipadOS and it seems to be impossible to circumvent. There is also no public API for checking if the silent switch is on, and the only working method is [quite hacky](https://gist.github.com/ivmirx/9611f8d90deed37401695fbfcc67307f).

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
