### ISSUE TITLE
[enhancement] Print

### ISSUE THREAD

**Issue by amirvenus** [xamarin/Essentials#718]
Printing a document directly from an app is arguably an essential part of modern apps (especially the corporate apps). 

While it is possible to implement printing using DI on each platform, I recently had a project targeting UWP, WPF, macOS, iOS and Android. 

I had to spend a lot of time implementing Print functionality on each platform and still, it's buggy on UWP and couldn't figure out a way to do it on macOS so I ended up using Device.OpenUri to open the document in a browser which basically means distracting the user by leaving the app. 

I suggest that Xamarin Essentials Print should offer two features as the bare minumum:

1. Discovering available printers (on the network, bluetooth, attached to the device, etc.)
2. Printing a document by sending it directly to the printer albeit allowing the user to interact with native print dialogs of each platform (i.e choosing Colour, number of pages and copies, etc.)

**Comment by amirvenus** [comment]
Any news and updates?

**Comment by johnshardman** [comment]
For info - I have a printing NuGet at https://github.com/johnshardman/Printing . I am about to update this from my local version which has improved UWP support (i.e. adds printing of WebViews and URLs). I just need to sort out one packaging issue (see https://forums.xamarin.com/discussion/177235/how-to-specify-an-additional-location-for-asset-files-in-a-nuget-built-using-vs2017 ) before publishing the latest version.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
