### ISSUE TITLE
Connectivity Never Fires ConnectivityChanged on Xamarin iOS

### ISSUE THREAD

**Issue by comfr3ak** [xamarin/Essentials#719]
### Description

Using Xam Essentials Connectivity and it works correctly on UWP and Android but the ConnectivityChanged event never fires on iOS when disconnecting WiiFi or changing access points. 

### Steps to Reproduce

1. Connect to Xamarin Essentials Connectivity.ConnectivityChanged event on iOS device
2. Launch app, and then change WiFi connection or do a "forgot" to disconnect WiFi
3. Event never fires

### Expected Behavior

ConnectivityChanged should at least fire as "None" when WiFi is not connected to an access point

### Actual Behavior

ConnectivityChanged does not fire at all

### Basic Information

- Version with issue: 1.0.1
- Last known good version: 
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS: 12 
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
Unable to reproduce this here. Everything working as expected with our sample. 

See: https://youtu.be/6n9JkbYA-7c
