### ISSUE TITLE
Browser.OpenAsync() does nothing on iOS

### ISSUE THREAD

**Issue by tonivuc** [xamarin/Essentials#725]
### Description
Browser.OpenAsync() works on Android 8.1 but not on iOS 12.1
Tried with Android Emulator and iOS Simulator

### Steps to Reproduce

1. Try to use Browser.OpenAsync() in an empty default project
2. Run the iOS simulator

### Expected Behavior
Opens a specified website within the app

### Actual Behavior
Stays on the page where the method was called, as if the method was ignored.

### Basic Information

- Version with issue:  1.0.1
- Last known good version: ??
- IDE: Visual Studio 15.9.5
- Platform Target Frameworks: 
  - iOS:  12.1
  - Android: 8.1  
- Android Support Library Version: 28.0.0.1
- Nuget Packages: NETStandard.Library, Xamarin.Forms, Xamarin.Essentials, Default Xamarin.Android support packages
- Affected Devices: iOS Simulator

### Reproduction Link
You can create an empty default project and try, or use this default project with my one added line:
https://drive.google.com/drive/folders/10-2MgVRA1YwPTqb9sQJqCuCNLIPKpHe9?usp=sharing

**Comment by jamesmontemagno** [comment]
This is because the UIViewController is not available yet. 

You have 2 options:

1.) pass in "External" 
2.) put it anywhere else like OnAppearing or after the UI has appeared:

```
protected override void OnAppearing()
        {
            base.OnAppearing(); Browser.OpenAsync("https://www.reddit.com/r/programming/", BrowserLaunchMode.SystemPreferred);
        }
```

**Comment by tonivuc** [comment]
Thank you James!

**Comment by rgustavsson** [comment]
Hi!
I have a similiar issue but it occurs in a different way.
I have a webview and a js bridge between the web and the app. The web tells the app to open the url in the browser via the js bridge and the app executes this line:

```
Browser.OpenAsync(url, BrowserLaunchMode.SystemPreferred)
```
but nothing happens in iOS. BrowserLaunchMode.External does work though.

Not sure how "This is because the UIViewController is not available yet." would apply in my scenario. 

What should I look for?

**Comment by rgustavsson** [comment]
I'm sorry. 
I realised I had added .Wait() to the .OpenAsync method and that was the cause of failure when executing to iOS. Case closed!
