### ISSUE TITLE
Some time giving cached location or Last Location

### ISSUE THREAD

**Issue by jangra1981** [xamarin/Essentials#726]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### In few Android devices , the GEO location API giving last cached or Saved Lat and Long. Not giving as fresh Lat Long every time. May be due to weak GPS signal or Internet speed. Following is code i am using to get always fresh Lat Long. If i don't put timeout then some times the Geo location request doesn't come back.

  try
                {

                    var request = new GeolocationRequest(GeolocationAccuracy.Best, TimeSpan.FromSeconds(10));
                    position = await Geolocation.GetLocationAsync(request);
                    if (position == null)
                    {
                        utility.ShowMsg("Unable to fecth location", "T", 0);
                        return;
                    }
                }
                catch (FeatureNotSupportedException fnsEx)
                {
                    utility.ShowMsg(fnsEx.Message.ToString(), "T", 0);
                    return;
                }
                catch (PermissionException pEx)
                {
                    utility.ShowMsg(pEx.Message.ToString(), "T", 0);
                    return;

                }
### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
It should always give fresh lat long and if unable to get it then return some error but doesn't give the last location.

### Actual Behavior
Giving Cached Location sometimes.
### Basic Information

- Version with issue: Current Stable Version of Xamarin Essential. 1.0.1
- Last known good version:
- IDE: Visual Studio Community Edition
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: Minimum Android Version Set as 4.1 and Maximum Android Version set as 9.0

- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
The position that is returned has a time stamp on it that you can check :) I believe that is what you are looking for. 

Here I am checking to see if it is older than 1 minute: https://github.com/xamarinhq/app-geocontacts/blob/master/src/GeoContacts/GeoContacts/Services/Geolocation.cs#L20

**Comment by jangra1981** [comment]
Ok, you mean to say even to get fresh location always, we first need to check last location and it's time with current time. If that difference is less than 1 minute then it's ok to use that same location else get fresh location.

So we can throw message to user if time difference between last location and current location is more than 1 minute ?
