### ISSUE TITLE
Flashlight State Missing

### ISSUE THREAD

**Issue by Crisfole** [xamarin/Essentials#727]
The flashlight API does not implement a means of reading the flashlight state.

I see in the issues history that it was part of the initial proposal, but did not get implemented in the initial version merged in, so there is probably a great reason, but I couldn't find another issue documenting that reason (if present). This issue is requesting the feature, or documentation that the feature is infeasible.

If it is _not_ infeasible, then a related feature would be subscribing to state changes; perhaps an API something like:

```
public static partial class Flashlight
{
  public static bool State {
    get
    {
      throw new NotImplementedException("Platform Specific!");
    }
  }

  public static event StateChanged;

  protected void OnStateChanged(bool newState)
  {
    StateChanged?.Invoke(this, new FlashlightStateChangedEventArgs(newState));
  }
}
```

The code for _reading_ state looks extremely straightforward in both Android and iOS...:

```
// Android:
camera.GetParameters().FlashMode == Android.Hardware.Camera.Parameters.FlashModeTorch;

//iOS
capturedevice.TorchActive;
```

**Comment by jamesmontemagno** [comment]
@mattleibow can comment, but I assume there was a technical limitation. 

Android is actually pretty tricky on how it was implemented and gaining exclusive lock.

**Comment by Crisfole** [comment]
I assumed as much. An unrelated comment: Xamarin.Essentials uses Camera rather than the classes in the `Camera2` namespace. Eventually it'll stop working.

**Comment by Mrnikbobjeff** [comment]
@Crisfole Essentials supports Android 4.4, and Camera2 has support for Android 5.0 onward. @jamesmontemagno After looking over android docs and the source this should be dpable on android, on newer platforms we can register a torch mode callback which enables us to update the torch mode. I briefly tested @Crisfole 's suggestion and it does work on a physical device on android.

**Comment by mattleibow** [comment]
Closing this as we have added Camera2 support.
