### ISSUE TITLE
[iOS] Map.OpenAsync does nothing when opening an invalid placemark

### ISSUE THREAD

**Issue by lanarchyste** [xamarin/Essentials#729]
### Description

When I want to open the navigation map on iOS with a malformed address, nothing is displayed and no exception is raised, whether on an emulator or a real device

With Android, if the address is malformed, the navigation map still opens on an address that is closest to it.

### Steps to Reproduce

```
var placemark = new Placemark
{
    CountryName = "France",
    CountryCode = "FR",
    Locality = "BONCHAMP",
    PostalCode = "53400",
    Thoroughfare = "3 rue des peupliers"
};
var options = new MapLaunchOptions
{
    NavigationMode = NavigationMode.Driving,
};

await placemark.OpenMapsAsync(options);
```

### Expected Behavior

One of the following behaviors :
- The map open with the most approximate address
- The map open with no address filled
- The OpenMapAsync method returns a boolean to see if the map is opened or not
- An exception is raised indicating that the address is unknown

### Actual Behavior

The navigation map does not open and it is not possible to know if the map was displayed or not

### Basic Information

- Version with issue: 1.0.1
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - iOS: 12.2
  - Android: 9.0
- Android Support Library Version: 28.0.0.1
- Nuget Packages:
     Xamarin.Forms 3.6.0.220655
- Affected Devices: all iOS devices

**Comment by jamesmontemagno** [comment]
We pass this information off to the core SDK so it is out of our control at this point. I would recommend opening lat/long

**Comment by lanarchyste** [comment]
In my test case, when the address is invalid, the method 
`code.GeocodeAddressAsync (address.Dictionary)` 
returns an exception.

Why not use this exception (and others) to return a boolean indicating whether the card is open or not?

In addition, the use of the MKMapItem.OpenMaps return variable could also be used to indicate whether the card is open or not.

The plugin LaunchMapsPlugin allow to have this indication, why not reuse this code?
