### ISSUE TITLE
Xamarin.Essentials 1.0.1 is blocking NuGet updates with the last Xamarin.Forms release

### ISSUE THREAD

**Issue by ylatuya** [xamarin/Essentials#733]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description

The NuGet update command fails to restore packages when upgrading nuget packages to the latest Xamarin.Forms release 3.6.0.220655  with the follwing error:

> Version conflict detected for Xamarin.Android.Support.Compat. Install/reference Xamarin.Android.Support.Compat 27.0.2.1 directly to project LienzoSharpDemo.Android to resolve this issue. 
 LienzoSharpDemo.Android -> LienzoSharpDemo -> LienzoSharp.Skia.Forms -> Xamarin.Essentials 1.0.1 -> Xamarin.Android.Support.CustomTabs 27.0.2.1 -> Xamarin.Android.Support.Compat (= 27.0.2.1) 
 LienzoSharpDemo.Android -> Xamarin.Forms 3.6.0.220655 -> Xamarin.Android.Support.v4 27.0.2 -> Xamarin.Android.Support.Compat (= 27.0.2).
Restore failed.

This seems caused because Xamarin.Essentials requires Xamarin.Android.Support.Compat 27.0.2 and the last version of Xamarin.Forms requires Xamarin.Android.Support.Compat  27.0.2.1

Removing Xamarin.Essentials, upgrading Xamarin.Forms and adding back Xamarin.Essentials only moves the error from the upgrade step to the restore step.

### Steps to Reproduce

1. Checkout the repo https://github.com/ylatuya/lienzosharp
2. Try to upgrade packages

### Basic Information

- Version with issue: 1.0.1
- Last known good version:
- IDE: vs4mac

### Reproduction Link

https://github.com/ylatuya/lienzosharp

**Comment by jamesmontemagno** [comment]
Update all of your support libraries to 27.0.2.1 and then install Xamarin.Essentials. This will fix it up for you.

**Comment by ylatuya** [comment]
Shouldn't this be fixed in the Xamarin.Essentials NuGet package by defining version ranges that include build versions?
<package id="Xamarin.Android.Support.CustomTabs" version="27.0.2.1" allowedVersions="[27.0.2,27.0.3)" />

**Comment by ylatuya** [comment]
Also the issue is a bit more complex than that and it can't be fixed by updating the support libraries as those are pulled in from the Xamarin.Forms nuget packages, they are not referenced manually from the application.
The project has the following structure:
LienzoSharpDemo: .netstandard library with share code that references the Xamarin.Forms NuGet
LienzoSharpDemo.Android: Android application that references the Xamarin.Forms NuGet package
LienzoSharp.Core: .netstandard library without dependencies
LienzoSharp.Skia.Forms: .netstandard library that references Xamarin.Essentials and SkiaSharp.View.Forms (that also pulls Xamarin.Forms)

As a user I shouldn't be adding manually any reference to the Android Support Libraries as they are automatically pulled from the Xamarin.Forms dependency.

**Comment by jamesmontemagno** [comment]
The templates align so file->new works correctly. There are a lot of versions of Xamarin.Forms and we align with the latest as close as possible to avoid conflicts. Unfortunately this how NuGet works and is telling you to install specific versions as they are dependencies that need to align. 

You can easily adjust it via: https://github.com/xamarin/Essentials/issues/687#issuecomment-457671569

We also have this documented in our troubleshooting guide. 

We spent a lot of time on this issue and we have more closely aligned dependencies in Xamarin.Forms 3.6 and 4.0 so it will be less of an issue for developers.

**Comment by jamesmontemagno** [comment]
Also see: https://redth.codes/how-to-fix-the-dreaded-version-conflict-nuget-error-in-your-xamarin-android-projects/

We hope with AndroidX in general this will go away, but v28 also great enhanced a lot of this.

**Comment by ylatuya** [comment]
Thanks a lot for the info, it explains everything now
