### ISSUE TITLE
IOS: Object reference not set to an instance of an object in CLLocationManager

### ISSUE THREAD

**Issue by moustafashaban** [xamarin/Essentials#740]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
I have the following error from the App center, and I am unable to fix it, it is maybe related to the main location class, 

please see the attached image:

**note**, I am getting this error from ios application only, Android is fine

### Steps to Reproduce

unable to reproduce it on my device, only get it from app center (from users)

### Screenshots

![image](https://user-images.githubusercontent.com/42233556/54515767-1fc8e300-496e-11e9-856b-02e8bf4d0ded.png)

**Comment by jamesmontemagno** [comment]
Do you have any code in your app for handling location authorization in your AppDelegate?

**Comment by moustafashaban** [comment]
no
