### ISSUE TITLE
Geolocation Speed not always available 

### ISSUE THREAD

**Issue by inetZombieBKW** [xamarin/Essentials#742]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Steps to Reproduce

1. Run the following sample code:
 var request = new GeolocationRequest(GeolocationAccuracy.Medium);
                var location = await Geolocation.GetLocationAsync(request);

                if (location != null)
                {
                    Console.WriteLine($"Latitude: {location.Latitude}, Longitude: {location.Longitude}, Speed: {location.Speed}");
                }

### Expected Behavior
Speed should be returned

### Actual Behavior
Speed is never returned

### Basic Information

- Version with issue: 1.1.0
- Platform Target Frameworks: iOS
  - iOS:  12.1.4 (16D57)
- Nuget Packages: Xamarin.Essentials
- Affected Devices: iPhone X, iPhone X Plus

**Comment by jamesmontemagno** [comment]
So speed is not guaranteed to be returned by the specific devices for all device location requests. Most likely when we implement updates you will get them as the data becomes available. We only return what each platform gives us at the specific request.

**Comment by trampster** [comment]
Is there any update on this? What would you recommend for applications that need the speed, should we call the Android API directly instead of using Xamarin.Essentials?

**Comment by trampster** [comment]
For anyone else finding this the Xamarin.Essential implementation uses both the GPS and Network location provider, and it returns the first update that meets your specified accuracy requirements.

However only GPS updates include speed, and it is quite likely the first location update will come from the Network provider which doesn't have to wait for a lock, but also doesn't have speed data.
