### ISSUE TITLE
Xamarin.Essentials: File System Helpers UWP error!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [xamarin/Essentials#747]
I put a file in root of UWP project Build Action is Content
On UWP Access to the path 'C:\Users' is denied! 
I use Windows 10 1809

**Comment by jamesmontemagno** [comment]
Hey there. Can you please provide a sample project or source code sample.

**Comment by nguyenthanhliemfc** [comment]
This my [github sample code](https://github.com/nguyenthanhliemfc/App1). Please take a look when you have free time!
Thank you!

**Comment by jamesmontemagno** [comment]
I just ran your sample and it worked great....

![image](https://user-images.githubusercontent.com/1676321/55017459-00edd080-4fae-11e9-8563-4139365a3146.png)

**Comment by nguyenthanhliemfc** [comment]
It's error after code at line 42!

**Comment by jamesmontemagno** [comment]
This is a helper for items bundled into the app like you used in your sample and worked perfectly for me. 

If want to read a file from a directory you will want to use System.IO.

Closing since the sample provided worked.

**Comment by nguyenthanhliemfc** [comment]
@jamesmontemagno Thanks you!
