### ISSUE TITLE
geolocation fix

### ISSUE THREAD

**Issue by timc1969** [xamarin/Essentials#756]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by picatextra** [comment]
I think accuracy is not the best, the GPS needs some time to "fix" his position. 
you only grabe the first result of each provider. (in Android)

**Comment by jamesmontemagno** [comment]
Closing due to now update and not enough information.

**Comment by Ahmed17Hamdy** [comment]
The location that comes back is not correct, it comes far away from the desired location
