### ISSUE TITLE
Error "GRPC failed" when geolocating an address on Android

### ISSUE THREAD

**Issue by lanarchyste** [xamarin/Essentials#759]
### Description

When the GetLocationsAsync method is called, an IOException exception is thrown with the following stacktrace :

```
Java.IO.IOException: grpc failed
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in System.Runtime.ExceptionServices.ExceptionDispatchInfo line 12
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 62
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 40
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task task) in System.Runtime.CompilerServices.TaskAwaiter line 8
at System.Runtime.CompilerServices.TaskAwaiter`1[[System.Collections.Generic.IEnumerable`1[[Xamarin.Essentials.Location, Xamarin.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult() in System.Runtime.CompilerServices.TaskAwaiter`1[[System.Collections.Generic.IEnumerable`1[[Xamarin.Essentials.Location, Xamarin.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]0
at Kibati.Service.Geocoding.GeocodingService+<GetPosition>d__5.MoveNext() in Kibati.Service.Geocoding.GeocodingService+<GetPosition>d__5 line 163
```

Here is the code of my application:
```
using XGeocoding = Xamarin.Essentials.Geocoding;

if (!_connectivity.IsConnected())
    return new PositionExtended();

var locations = await XGeocoding.GetLocationsAsync(address.ToLongReadableAddress());
var location = locations?.FirstOrDefault();
if (location != null)
{
    var position = new Position(location.Latitude, location.Longitude);
    return new PositionExtended(position, false);
}

locations = await XGeocoding.GetLocationsAsync(address.ToShortGeolocateAddresss());
location = locations?.FirstOrDefault();
if (location != null)
{
    var position = new Position(location.Latitude, location.Longitude);
    return new PositionExtended(position, true);
}

return new PositionExtended();
```

### Basic Information

- Version with issue: 1.1.0
- IDE: Visual Studio fro Mac 2017
- Platform Target Frameworks:
  - Android: 9.0
- Android Support Library Version: 28.0.0.1
- Affected Devices: SM-G390F on Android 8.1.0

**Comment by jrahma** [comment]
I have the same error on Android too. Here is my code:

```
try
{
    var request = new GeolocationRequest(GeolocationAccuracy.Best);
    var location = await Geolocation.GetLocationAsync(request);

    if (location != null)
    {
        user_latitude = location.Latitude;
        user_longitude = location.Longitude;

        await DisplayAlert("country", Convert.ToString(user_latitude), "OK");

        var placemarks = await Geocoding.GetPlacemarksAsync(user_latitude, user_longitude);

        var placemark = placemarks?.FirstOrDefault();

        if (placemark != null)
        {
            country_code = placemark.CountryCode;
            country_name = placemark.CountryName;

            await DisplayAlert("country", country_code, "OK");

            ImageSignupCountryFlag.Source = "https://www.zeera.online/flags/" + country_code + ".png";
            // LabelSignupCountryName.Text = country_name;

            LabelSignupCountryCode.Text = "+971";
        }
    }
}
catch (Exception ex)
{
    await DisplayAlert("Error", ex.Message, "OK");

}

```

**Comment by khadeeja-alif** [comment]
I got the same issue on my android device: Samsung S8

**Comment by andyngo95** [comment]
I have the same issue on Android devices. Then, I solved this issue by reducing the work in main thread. I thought my app was having a heavy work so I moved all get location method to background thread.

**Comment by khadeeja-alif** [comment]
Getting the same issue in other Samsung devices too . Samsung J6

**Comment by jamesmontemagno** [comment]
If you get this issue it is via the device itself. I got it once on an emulator, but called it again and it worked fine. This is the device specific call. I will continue to debug and look into any enhancements, but that would be the recommendation right now.

**Comment by alexandresanlim** [comment]
In Wifi connection worked fine but in 3g or 4g connection is fail.

**Comment by justinimel** [comment]
Any updates on this? I am having this issue as well.

**Comment by tsjdev-apps** [comment]
I also noticed this. The error does not always occur, but now and then. I test on an Android device with Android 9.0 and try to find the position to multiple addresses.

**Comment by jamesmontemagno** [comment]
We use core Android APIs and this comes from Android itself in some situations: https://stackoverflow.com/questions/47331480/geocoder-getfromlocation-grpc-failed-on-android-real-device There isn't anything that we can change or due here. Closing for this reason.

**Comment by arifulislamiut** [comment]
SomeTimes Geocoder failed when latitude and longitude contain above 3 decimal places, or it may be said that Geocoder can not decode every latitude and longitude. you need to limit latitude and longitude upto 3 decimal places. complete code
`

        DecimalFormat df = new DecimalFormat();

        df.setMaximumFractionDigits(3);

        double lat = Double.parseDouble(df.format(currentUserLocation.latitude));

        double lon = Double.parseDouble(df.format(currentUserLocation.longitude));

        Geocoder geocoder = new Geocoder(myContext, Locale.getDefault());

        List<Address> addresses  = geocoder.getFromLocation(lat,lon, 1);

        String cityName = addresses.get(0).getLocality();
`

source:
[https://stackoverflow.com/a/57923661/9312023](url)

**Comment by mpapadis** [comment]
I have the same issue with Ulefone Armor 2 (android 7.0). 
Has anyone found a workaround?

**Comment by isness** [comment]
I have this issue as well. I really need a workaround. Tried using Geocoder from Xamarin.Forms.Maps, but it results in the same error. Is there some other service we could use?

**Comment by Jyoshnarani** [comment]
Hello Friends,

I have solution for exception "java.io.ioexception grpc failed"

Code: 

try { 
Geocoder geocoder = new Geocoder(MainActivity.this, Locale.getDefault());
 List addresses = geocoder. getFromLocation(latitude, longitude, 1); 
List<Address> addresslist = addresses; 
String address = addresslist.get(0).getAddressLine(0); 
Log.d("add",address);
 } catch (IOException e) { 
e.printStackTrace();
}
