### ISSUE TITLE
Please support interact with Infrared!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [xamarin/Essentials#760]
As the title, Please support interact with Infrared!
I want to use my phone to control FAN, TV and any device have Infrared.
Thank you!

**Comment by jamesmontemagno** [comment]
The infrared API is only available on a few select devices and from my understanding is not a standard api across iOS/Android/Windows. So in this case we will not look to implement this API. Thank you for the suggestion.

**Comment by nguyenthanhliemfc** [comment]
Thank you James!
