### ISSUE TITLE
Essentials- Geolocation Issue

### ISSUE THREAD

**Issue by AshishInnovantes** [xamarin/Essentials#764]
Setting up the Geolocation to get a current list of locations using the Essentials geolocation is not working.

Its working in some devices but not in "OnePlus 3T having Android 8.0"
Below is my code please check

               var request = new GeolocationRequest(GeolocationAccuracy.Medium, 
               TimeSpan.FromMilliseconds(500));

                var location = await Geolocation.GetLocationAsync(request);
                if (location != null)
                {
                    attendance.SignInLat = location.Latitude.ToString();
                }
               else
                { //prompt that location not recieved}

### Expected Behavior 
To return Lat Long of the user

### Actual Behavior
returns null (empty)

### Basic Information

- Version with issue:1.1.0
- IDE: Visual Studio 2017
- Platform Target Frameworks: .NET Standard 2.0
  - Android: **Android 8.0**
- Android Support Library Version: 28.0.0.1
- Nuget Packages: 1.1.0
- Affected Devices: **OnePlus 3T**  **Android 8.0**

**Comment by jamesmontemagno** [comment]
In this instance you are only giving it 500ms to return which may not be enough time. I would recommend increasing the timeout.
