### ISSUE TITLE
Xamarin Forms, IOS :  ShareFileRequest Title is ignore, only image is getting shared 

### ISSUE THREAD

**Issue by Abhijeet-Xamarin** [xamarin/Essentials#766]
### Description 
ShareFileRequest has 2 parameters, one is title & other is path. But in actual implementation fie title is not getting shared. 
Tested only on iOS

### Steps to Reproduce
 ExperimentalFeatures.Enable("ShareFileRequest_Experimental");
 Share.RequestAsync(new ShareFileRequest(
                           Xamarin.Forms.Application.Current.Resources["MessageTitle"].ToString()
                           , new ShareFile(path)));

### Expected Behavior
1. Title should get shared, otherwise how to pass link with file ? 

### Actual Behavior
1. Only file is getting shared. (Image )

### Basic Information

- Version with issue: Xamarin Essentials 1.1.0, Xamarin Forms 3.6.0  
- IDE: Visual Studio For Mac 
- Platform Target Frameworks: 
  - iOS: Deployment Target 12.1

**Comment by Nandulucky** [comment]
Perfect working thanks!.

**Comment by Abhi-Tech9** [comment]
Yes its working now, waiting for other features like sharing text with image.

**Comment by jamesmontemagno** [comment]
Glad it is working, we didn't make any changes :) will close out.

**Comment by robinne** [comment]
Hi there, I'm using this feature for the first time with Xamarin.Essentials 1.5.3.2. 
`await Share.RequestAsync(new ShareFileRequest("My File", new ShareFile(filename)));`
I expect "My File" to show as the file being saved, but instead, the name of the actual file "iTrackIt" is being shown.
![title](https://user-images.githubusercontent.com/1094409/88250307-0586cf80-cc5c-11ea-8233-f72e8aeab89d.jpg)

Any ideas? The file is a sqlite database \some\file\location\itrackit.db
