### ISSUE TITLE
[ENHANCEMENT] Missing share options OpenBrowser

### ISSUE THREAD

**Issue by felipecds** [xamarin/Essentials#768]
### Description
On BrowserLauncherOptions, I can't set an option to show the default share options in CustomTabs. I think iOS have a related functionality.

### Steps to Reproduce
1. Instantiate a new BrowserLauncherOptions. 

### Expected Behavior
When calling OpenAsync, the browser will show a share option.

### Actual Behavior
When calling OpenAsync, the browser don't have the share options.

### Basic Information

- Version with issue: 1.1.0
- Last known good version:
- IDE: Visual Studio 2019 Professional
- Platform Target Frameworks:

**Comment by jamesmontemagno** [comment]
Can you add a bit more detail as to what you mean by "default share options"

**Comment by felipecds** [comment]
Sure.

It's the option configured when you set this option in CustomTabs:

CustomTabsIntent customTabsIntent = new CustomTabsIntent.Builder().addDefaultShareMenuItem().build()

**Comment by jamesmontemagno** [comment]
Thanks for the info. This is a tricky one as there is no equivalent on iOS/UWP and would be an Android specific. We don't have a great way of handling this today and try to keep the API consistent. We will keep it in our backlog to discuss.

**Comment by davehump** [comment]
Cannot be implemented cross-platform as the feature is only available on android
