### ISSUE TITLE
Feature/Capability Availability/Status API's

### ISSUE THREAD

**Issue by Redth** [xamarin/Essentials#77]
There's been a lot of discussion around handling checking of device capabilities and feature availability at runtime.  This should be a central place to formulate our strategy around these types of API's.

Keep in mind we want to grow the API surface as conservatively as possible.  Once an API is public in our first stable release, it lives forever.

We also want to remember that the reason for adding any API's is to make developers' experiences delightful in consuming our library.

## Purpose

The purpose of any sort of `Status` or `Availability` query on a feature is to see if it's usable or not when called.  This means in almost every case, the developer doesn't really care about the actual _state_ of availability, but rather that they can _use_ the feature.

There's one exception to this: When something might be unavailable, but _could be made available_ through code (eg: prompting the user, etc).

NOTE: This is _not_ to be confused with missing or lack of granted permissions for a feature.

### Capabilities class

[One strategy](https://github.com/xamarin/Caboodle/issues/36) was to introduce a `Capabilities` class.  I dislike this strategy for a couple of reasons:

 1. It's separated from the actual class being used, and much less discoverable.  If I'm working with Location, if while I'm typing `Location.` I see `Location.Availability`, it might prompt me with the idea that I should or at least _could_ check to see if the feature works at runtime before using it.
 2. Capabilities is in a sense tightly coupled to pretty much every other class.

One suggestion is we could have a property in each class which just calls into the Capabilities class.  I also dislike this idea as it introduces ambiguity (we'll end up with people writing code like `if (Geolocation.IsAvailable && Capabilities.HasGeolocation)` to be safe.  It also means more code paths to test and maintain.

### Exceptions

Regardless of the strategy we use around checking for feature/capability availability, users won't be _required_ to check these before attempting to _use_ them, so we will still need to throw exceptions such as `NotSupportedException` at runtime if a particular API is unavailable at the time of invocation.

So, the exception strategy is to simply omit any API for checking availability and have the developer rely on exception handling to detect when things are not supported or available.  

The benefit to this approach is we can always add other API's for checking availability down the road as this exception work will be done regardless.

Where this approach becomes a bit messy is with statuses where a developer may be able to do something to enable or have the user enable a feature and try again.  For example, this becomes a bit messy:

```csharp
Position p;

try {
    p = await Geolocation.GetPositionAsync ();
} catch (GeolocationDisabledException) {
    // Prompt user to enable geolocation
    await DoSomethingToGetTheUserToEnable ();

    // Try getting location again
    try {
        p = await Geolocation.GetPositionAsync ();
    } catch (Exception ex) {
        // Not gonna happen
    }
}
```

### Status or Availability properties

Given the purpose of these API's, most cases where such an availability API would be useful could be distilled down to mostly a true/false basis.  However, we want to avoid `bool` still as using an `enum` allows for more possible values in the future if necessary.

Most cases could use a simple enum such as:

```csharp
public enum SmsStatus {
	Unavailable,
	Ready
}
```

And the class would implement a simple property:

```csharp
public static partial class Sms {
	public static SmsStatus Status { get; }
}
```

In cases where we might want to provide another status to indicate something is unavailable but may be able to be made available we would introduce another status value:

```csharp
public enum GeolocationStatus {
	Unavailable,
	Disabled,
	Ready
}
```

And the class implements:

```csharp
public static partial class Geolocation {
	public static GeolocationStatus Status { get; }
}
```

In this case, `GeolocationStatus.Disabled` would indicate to the developer that the device may be capable of providing location data, but that feature is for some reason disabled (perhaps the user turned off location services on android).  This could be a queue for the developer to prompt the user to enable location services.

There are also other possibilities for the naming convention here:

 - Status
 - Availability
 - SupportLevel

> VS bug [#735684](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735684)

**Comment by jamesmontemagno** [comment]
Yeah, I think this makes some logical sense. I do worry that some APIs may require some weird async calls to query this information, such as requiring a permission first... but in general they would need the permission first even to get the statue... maybe that could be exposed as well in the enum.

I like it. I just want to make sure that we don't have multiple enums for multiple "features" 

Right now for the SMS i see that there is the background one that only works on 1 platforms. I don't think this is a great practice to have can send sms and can send background. confusing. Make it 2 different classes or remove the background as it only supports android, or only put it in the android project... thoughts?

**Comment by Redth** [comment]
I think we will end up with multiple enums here out of necessity.. or at least perhaps 3 distinct ones:

```csharp
enum Status {
  Unavailable,
  Ready
}

enum Status2 {
  Unavailable,
  Disabled
  Ready
}

enum Status3 {
  PermissionRequired,
  Unavailable,
  Disabled
  Ready
}
```

This sort of quickly spirals out of control.  What I prefer not to see is one giant enum with all possibilities, as if then I'm checking `Sms.Status` it looks like to me as a developer, it could be `PermissionRequired`, `Unavailable`, `Disabled`, `Ready`, when in reality, the API will only ever return `Unavailable` or `Ready`.  I don't want this ambiguity to cause developers testing for cases that will never happen.

**Comment by Redth** [comment]
In this sense, it almost makes more sense to have a particular enum for each status...

**Comment by jamesmontemagno** [comment]
I think maybe we just have one enum with Status that combines all potential status? And then each class has the ability to have 1 property that describes the API.

**Comment by Redth** [comment]
This falls exactly into the case I don't love... which is where asking for a Status on something yields an enum which can be compared to many statuses that don't actually apply in the given context.

**Comment by jamesmontemagno** [comment]
I almost think there is a difference between this which is focused on complex functionality and the "is the API supported on this machine".

Ideally we avoid all is this supported type of work.

**Comment by jrahma** [comment]
Why can't this be a new extension? Xamarin.Essenstials.Capabilty ....

**Comment by jrahma** [comment]
Add IsVPNConnected to check if the phone is connected through VPN

**Comment by jrahma** [comment]
Add Contact Capability tc check if the app has permission to Contacts

**Comment by jrahma** [comment]
Add Calendar Capability tc check if the app has permission to Calendar

**Comment by jrahma** [comment]
Add Camera Capability tc check if the app has permission to Camera

**Comment by jrahma** [comment]
Add Photos Capability tc check if the app has permission to Photos

**Comment by jrahma** [comment]
Add Bluetooth Capability tc check if Bluetooth is on or off

**Comment by jrahma** [comment]
Add WiFi Capability tc check if WiFi is on or off

**Comment by jrahma** [comment]
Add AirplaneMode Capability tc check if AirplaneMode is on or off

**Comment by jrahma** [comment]
Add MobileData Capability tc check if MobileData is on or off

**Comment by jrahma** [comment]
Add Notifications Capability tc check if app has permission to Notifications

**Comment by jrahma** [comment]
Add Siri Capability tc check if app has permission to Siri

**Comment by jamesmontemagno** [comment]
@jrahma yes, these would all be under consideration. there is no need to request all of them.

**Comment by jrahma** [comment]
Great... Thanks...

**Comment by GuidoNeele** [comment]
Have you guys bitten the bullet yet about this issue?

**Comment by Redth** [comment]
Not yet.  Once we schedule this one for work in the future, we'll have some more API discussions around it to gather more opinions and see if we can agree on a spec.

**Comment by Dbquity** [comment]
I support the idea of the distinct enums where each enum contains only the values that are relevant.
In addition to what @Redth writes, the possible outcomes of an enum also nicely drives statement completion such as laying out the cases of a switch statement. (I am not so concerned about it spinning out of control, because in the end you will make sure to have only the outcomes and combinations you truly need.)

It may be worth considering sharing the numerical values of same outcomes across all enums. And if you would assign a particular bit to each of these outcomes and decorate with the [Flags] attribute there is a certain style of programming that you enable, which would come in handy once or twice I am sure :-)

Something like

```
[Flags]
public enum CapabilityAvailabilities {
    PermissionRequired = 0b0000_0001,
    Unavailable = 0b0000_0010,
    Disabled = 0b0000_0100,
    Ready = 0b1000_0000
}

[Flags]
public enum UnavailableDisabledReadyAvailabilities {
    Unavailable = CapabilityAvailabilities.Unavailable,
    Disabled = CapabilityAvailabilities.Disabled,
    Ready = CapabilityAvailabilities.Ready
}

[Flags]
public enum DisabledReadyAvailabilities {
    Disabled = CapabilityAvailabilities.Disabled,
    Ready = CapabilityAvailabilities.Ready
}
```
is what I have in mind.

Hope it is useful input :-)

**Comment by mattleibow** [comment]
On a sidenote, for the `[Flags]` I found that using `1 << 1` and `1 << 2` was easier to read. But, continue other discussions...

**Comment by r2d2rigo** [comment]
Is this being worked on? I'm in the process of migrating a code base from the old Plugin libraries to the unified Xamarin Essentials one and there some missing features, mainly `IsGeolocationAvailable`/`IsGeolocationEnabled`.

**Comment by jges42** [comment]
Please, Xamarin Essentials needs this capabilities API. Otherwise all GPS related code is still surrounded by all that os specific cermony to check weather or not gps has been disabled.

**Comment by WilkoSki** [comment]
Any update on this? it's been in discussion for well over a year now.

Having just gone through the process of migrating away from all the Xam.Plugin.... components to Essentials I can honestly say it's more painful than it should be.

Simple things such as checking if secure storage is supported, ends up needing to be wrapped with a function or service class due to the need to catch an unsupported exception.

**Comment by aismaniotto** [comment]
@WilkoSki I also doing this migration and also hurting my self. I don't know if I will be able to change the Xam.Plugin.Geolocator for the Geolocation from Essentials. I don't know if I will able to know if the the GPS is disabled, without permission ou unavaiable. :(

**Comment by mattleibow** [comment]
Time has passed, thoughts have been made.

I do like what https://github.com/xamarin/Essentials/issues/77#issuecomment-422545778 suggested. We probably need to make sure we try out as many APIs. I think having the multiple enums might be better as each API may have it's own set. Sharing values is cool.

Many things may only have two states, so this may not be too bad - SMS, Email, AppleAuth - but for the GPS, that will be better to have it's own states. Even other devices, such as Vibrate, that really only has 2 states as well.

**Comment by MitchBomcanhao** [comment]
We're also interested in these capabilities checks, as the Essentials plugin missing these means that we have to dumb down a few features in our application in order to adapt.
knowing that we're not getting a location because the device cannot get one, as opposed to simply not getting a location at all is very useful and enables a number of advanced scenarios.

**Comment by ElteHupkes** [comment]
It seems most people (myself included) arrive here after finding these features gone between the `Xam.Plugin.(...)` and the `Xamarin.Essentials` version, which leads me to wonder what the rationale was behind not including them in the first place. I get that this API is preferably as stable and consistent as possible, but I personally don't see any large issues with any of the approaches.

It looks like the availability flags are quite specific to the capability, so they should likely not be a single enum. I'm personally in favor of just having the booleans back. They're easy to discover through autocomplete (no need to check enum values), more concise in conditionals (`if (Status)` vs `if (Status == StatusEnum.Available)` and it's what most people would be migrating from anyway.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
