### ISSUE TITLE
Hybrid AOT and share files crash

### ISSUE THREAD

**Issue by nexxuno** [xamarin/Essentials#770]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
I know that both Hybrid AOT and File Sharing are experimental features but I'm trying to ask for help anyway.

### Steps to Reproduce

Try and share a file with a code like this with app build with hybrid AOT enabled:

```
        private async Task ShareLogFileAsync(string x)
        {
            await Share.RequestAsync(new ShareFileRequest
            {
                Title = "Kml File Share",
                File = new ShareFile(x)
            });
        }
```

### Expected Behavior
File share opens normally, as it does when debugging the app **without** Hybrid AOT

### Actual Behavior
There is a crash:

Xamarin Exception Stack: System.InvalidProgramException: Invalid IL code in Xamarin.Essentials.FileBase:PlatformGetContentType (string): IL_0000: ret at Xamarin.Essentials.FileBase.GetContentType () <0x7dac8943b0 + 0x0004c> in <c688d9a6e9d6460b9774623a154de3ee>:0 at Xamarin.Essentials.Share.PlatformRequestAsync (Xamarin.Essentials.ShareFileRequest request) <0x7dac899df4 + 0x0005f> in <c688d9a6e9d6460b9774623a154de3ee>:0 at Xamarin.Essentials.Share.RequestAsync (Xamarin.Essentials.ShareFileRequest request) <0x7dac899c38 + 0x0002f> in <c688d9a6e9d6460b9774623a154de3ee>:0 at BeltMap.PageModels.DebugPageModel+<ShareLogFileAsync>d__27.MoveNext () <0x7dadff1500 + 0x000a7> in <1bf623de21a54cb48127b9bcf0ea9499>:0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7db325116c + 0x000e0> in <f32579baafc1404fa37ba3ec1abdc0bd>:0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7db325107c + 0x000df> in <f32579baafc1404fa37ba3ec1abdc0bd>:0 at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7db3251010 + 0x0002f> in <f32579baafc1404fa37ba3ec1abdc0bd>:0 at BeltMap.PageModels.DebugPageModel+<<-ctor>b__25_1>d.MoveNext () [0x00068] in <1bf623de21a54cb48127b9bcf0ea9499>:0 at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) <0x7db3250b48 + 0x00058> in <f32579baafc1404fa37ba3ec1abdc0bd>:0 at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () <0x7daf89fc28 + 0x0001b> in <263adecfa58f4c449f1ff56156d886fd>:0 at Java.Lang.Thread+RunnableImplementor.Run () <0x7daf904274 + 0x0002f> in <263adecfa58f4c449f1ff56156d886fd>:0 at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) <0x7daf5e31f4 + 0x0004f> in <263adecfa58f4c449f1ff56156d886fd>:0 at (wrapper dynamic-method) System.Object.8dce2b2f-4da0-42b2-ae9b-620739ac9c0f(intptr,intptr) Thread 1: 0 dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2) 1 java.lang.Thread.getStackTrace(Thread.java:1558) 2 java.lang.Thread.getAllStackTraces(Thread.java:1608) 3 com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:943) 4 com.microsoft.appcenter.crashes.WrapperSdkExceptionManager.saveWrapperException(WrapperSdkExceptionManager.java:50) 5 mono.java.lang.RunnableImplementor.n_run(RunnableImplementor.java:-2) 6 mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30) 7 android.os.Handler.handleCallback(Handler.java:891) 8 android.os.Handler.dispatchMessage(Handler.java:102) 9 android.os.Looper.loop(Looper.java:207) 10 android.app.ActivityThread.main(ActivityThread.java:7470) 11 java.lang.reflect.Method.invoke(Method.java:-2) 12 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 13 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) Thread 846: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:178) 2 java.lang.Daemons$Daemon.run(Daemons.java:103) 3 java.lang.Thread.run(Thread.java:784) Thread 847: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Object.wait(Object.java:422) 2 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188) 3 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209) 4 java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:232) 5 java.lang.Daemons$Daemon.run(Daemons.java:103) 6 java.lang.Thread.run(Thread.java:784) Thread 848: 0 java.lang.Thread.sleep(Thread.java:-2) 1 java.lang.Thread.sleep(Thread.java:386) 2 java.lang.Thread.sleep(Thread.java:327) 3 java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:342) 4 java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:364) 5 java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:281) 6 java.lang.Daemons$Daemon.run(Daemons.java:103) 7 java.lang.Thread.run(Thread.java:784) Thread 857: 0 java.lang.Thread.sleep(Thread.java:-2) 1 java.lang.Thread.sleep(Thread.java:386) 2 java.lang.Thread.sleep(Thread.java:327) 3 android.zrhung.appeye.AppEyeUiProbe$AppEyeUIPChecker.run(AppEyeUiProbe.java:157) 4 java.lang.Thread.run(Thread.java:784) Thread 859: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Thread.parkFor$(Thread.java:2163) 2 sun.misc.Unsafe.park(Unsafe.java:358) 3 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230) 4 java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:461) 5 java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362) 6 java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937) 7 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091) 8 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 9 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 10 java.lang.Thread.run(Thread.java:784) Thread 860: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:386) 2 android.os.Looper.loop(Looper.java:169) 3 android.os.HandlerThread.run(HandlerThread.java:65) Thread 862: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:386) 2 android.os.Looper.loop(Looper.java:169) 3 android.os.HandlerThread.run(HandlerThread.java:65) Thread 863: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:386) 2 android.os.Looper.loop(Looper.java:169) 3 android.os.HandlerThread.run(HandlerThread.java:65) Thread 872: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:386) 2 android.os.Looper.loop(Looper.java:169) 3 android.os.HandlerThread.run(HandlerThread.java:65) Thread 873: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Thread.parkFor$(Thread.java:2163) 2 sun.misc.Unsafe.park(Unsafe.java:358) 3 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230) 4 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101) 5 java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467) 6 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091) 7 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 8 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 9 java.lang.Thread.run(Thread.java:784) Thread 874: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Thread.parkFor$(Thread.java:2163) 2 sun.misc.Unsafe.park(Unsafe.java:358) 3 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230) 4 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101) 5 java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467) 6 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091) 7 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 8 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 9 java.lang.Thread.run(Thread.java:784) Thread 876: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Thread.parkFor$(Thread.java:2163) 2 sun.misc.Unsafe.park(Unsafe.java:358) 3 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230) 4 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101) 5 java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467) 6 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091) 7 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 8 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 9 java.lang.Thread.run(Thread.java:784) Thread 877: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Thread.parkFor$(Thread.java:2163) 2 sun.misc.Unsafe.park(Unsafe.java:358) 3 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230) 4 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101) 5 java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467) 6 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1091) 7 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 8 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 9 java.lang.Thread.run(Thread.java:784) Thread 878: 0 java.lang.Object.wait(Object.java:-2) 1 com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:101) 2 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 3 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 4 java.lang.Thread.run(Thread.java:784) Thread 879: 0 java.lang.Object.wait(Object.java:-2) 1 com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:311) 2 com.android.okhttp.okio.AsyncTimeout.access$000(AsyncTimeout.java:40) 3 com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:286) Thread 883: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Thread.parkFor$(Thread.java:2163) 2 sun.misc.Unsafe.park(Unsafe.java:358) 3 java.util.concurrent.locks.LockSupport.park(LockSupport.java:190) 4 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059) 5 java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548) 6 du.b(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):17) 7 du.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):13) Thread 884: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Thread.parkFor$(Thread.java:2163) 2 sun.misc.Unsafe.park(Unsafe.java:358) 3 java.util.concurrent.locks.LockSupport.park(LockSupport.java:190) 4 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059) 5 java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548) 6 ee.a(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):12) 7 ee.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):8) Thread 885: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Thread.parkFor$(Thread.java:2163) 2 sun.misc.Unsafe.park(Unsafe.java:358) 3 java.util.concurrent.locks.LockSupport.park(LockSupport.java:190) 4 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059) 5 java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548) 6 ee.a(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):12) 7 ee.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):8) Thread 886: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Thread.parkFor$(Thread.java:2163) 2 sun.misc.Unsafe.park(Unsafe.java:358) 3 java.util.concurrent.locks.LockSupport.park(LockSupport.java:190) 4 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059) 5 java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548) 6 ee.a(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):12) 7 ee.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):8) Thread 887: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Thread.parkFor$(Thread.java:2163) 2 sun.misc.Unsafe.park(Unsafe.java:358) 3 java.util.concurrent.locks.LockSupport.park(LockSupport.java:190) 4 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059) 5 java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548) 6 ee.a(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):12) 7 ee.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):8) Thread 889: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:386) 2 android.os.Looper.loop(Looper.java:169) 3 android.os.HandlerThread.run(HandlerThread.java:65) Thread 890: 0 java.lang.Thread.sleep(Thread.java:-2) 1 java.lang.Thread.sleep(Thread.java:386) 2 java.lang.Thread.sleep(Thread.java:327) 3 com.google.maps.api.android.lib6.impl.ft.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):15) 4 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 5 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 6 java.lang.Thread.run(Thread.java:784) Thread 891: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Thread.parkFor$(Thread.java:2163) 2 sun.misc.Unsafe.park(Unsafe.java:358) 3 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230) 4 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101) 5 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1132) 6 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849) 7 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092) 8 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 9 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 10 java.lang.Thread.run(Thread.java:784) Thread 894: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:386) 2 android.os.Looper.loop(Looper.java:169) 3 com.google.maps.api.android.lib6.gmm6.store.d.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):96) 4 com.google.maps.api.android.lib6.gmm6.store.aa.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):12) Thread 895: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:386) 2 android.os.Looper.loop(Looper.java:169) 3 com.google.maps.api.android.lib6.gmm6.store.d.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):96) 4 com.google.maps.api.android.lib6.gmm6.store.aa.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):12) Thread 896: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:386) 2 android.os.Looper.loop(Looper.java:169) 3 com.google.maps.api.android.lib6.gmm6.store.d.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):96) Thread 897: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:386) 2 android.os.Looper.loop(Looper.java:169) 3 com.google.maps.api.android.lib6.gmm6.store.d.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):96) 4 com.google.maps.api.android.lib6.gmm6.store.aa.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):12) Thread 898: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:386) 2 android.os.Looper.loop(Looper.java:169) 3 com.google.maps.api.android.lib6.gmm6.store.d.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):96) Thread 899: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:386) 2 android.os.Looper.loop(Looper.java:169) 3 com.google.maps.api.android.lib6.gmm6.store.d.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):96) 4 com.google.maps.api.android.lib6.gmm6.store.aa.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):12) Thread 900: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:386) 2 android.os.Looper.loop(Looper.java:169) 3 com.google.maps.api.android.lib6.gmm6.store.d.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):96) 4 com.google.maps.api.android.lib6.gmm6.store.aa.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):12) Thread 901: 0 android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2) 1 android.os.MessageQueue.next(MessageQueue.java:386) 2 android.os.Looper.loop(Looper.java:169) 3 com.google.maps.api.android.lib6.gmm6.store.n.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):29) Thread 904: 0 java.lang.Object.wait(Object.java:-2) 1 com.google.maps.api.android.lib6.gmm6.vector.bg.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):135) Thread 905: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Thread.parkFor$(Thread.java:2163) 2 sun.misc.Unsafe.park(Unsafe.java:358) 3 java.util.concurrent.locks.LockSupport.park(LockSupport.java:190) 4 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059) 5 java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442) 6 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092) 7 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 8 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 9 java.lang.Thread.run(Thread.java:784) Thread 906: 0 java.lang.Thread.sleep(Thread.java:-2) 1 java.lang.Thread.sleep(Thread.java:386) 2 java.lang.Thread.sleep(Thread.java:327) 3 com.google.maps.api.android.lib6.gmm6.vector.p.run(:com.google.android.gms.dynamite_mapsdynamite@16089081@16.0.89 (100400-239467275):12) Thread 907: 0 java.lang.Object.wait(Object.java:-2) 1 java.lang.Thread.parkFor$(Thread.java:2163) 2 sun.misc.Unsafe.park(Unsafe.java:358) 3 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230) 4 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101) 5 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1132) 6 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849) 7 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092) 8 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 9 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 10 java.lang.Thread.run(Thread.java:784)

### Basic Information

- Version with issue: 1.1.0 and latest stable Xamarin.Forms
  - Android: target is 28

**Comment by jamesmontemagno** [comment]
I believe you will want to file this with: https://github.com/xamarin/xamarin-android as it is an AOT issue.

**Comment by nexxuno** [comment]
Ok I'll do. But I'm starting to think it's a problem on our build machine setup. If it isn't I'll open on the xamarin andorid github. Thanks.
