### ISSUE TITLE
Image withing Share

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#774]
Hi,

In below code, why can't I also include an image?

```
await Share.RequestAsync(new ShareTextRequest
{
    Subject = "Samana",
    Text = "Hey! try this app.",
    Uri = "https://play.google.com/store/apps/details?id=com.softnames.samana",
    Title = "Samana"
});

```

Thanks,
[Jassim](https://www.zeera.online)

**Comment by jamesmontemagno** [comment]
Please see sharing files: https://docs.microsoft.com/en-us/xamarin/essentials/share?context=xamarin%2Fandroid&tabs=android#files

**Comment by jrahma** [comment]
What I mean is something like this....

1. Image, 2. Text and 3. URL.... all in the same Share message



![IMG-6728](https://user-images.githubusercontent.com/6236241/56906093-9bac6400-6ab2-11e9-8c39-caa593905a25.jpg)

**Comment by jamesmontemagno** [comment]
From my knowledge this is not possible and not consistent across apps. The official apis support one or the other, but not both.
