### ISSUE TITLE
DeviceInfo.Idiom return Phone instead of Tablet on Android 9 (x86)

### ISSUE THREAD

**Issue by MagicAndre1981** [xamarin/Essentials#775]
As [requested by](https://github.com/xamarin/Essentials/issues/668#issuecomment-478735630) @jamesmontemagno I open a new issue.

### Description

I want to check if my app runs on phone or tablet to apply different margin/Padding settings, but I always get the return value that device is a phone.

### Steps to Reproduce

run this code:

```
var device = DeviceInfo.Model;
var manufacturer = DeviceInfo.Manufacturer;
var deviceName = DeviceInfo.Name;
var version = DeviceInfo.VersionString;
var platform = DeviceInfo.Platform;
var idiom = DeviceInfo.Idiom;
var deviceType = DeviceInfo.DeviceType;

 Debug.WriteLine("device: {0}, manufacturer: {1}, deviceName: {2}, version: {3}, platform: {4}, idiom: {5}, deviceType: {6}", device, manufacturer, deviceName, version, platform, idiom, deviceType);
```

### Expected Behavior

idiom is Tablet

### Actual Behavior

idiom is Phone

> [0:] device: TOSHIBA WT8-A, manufacturer: TOSHIBA, deviceName: TOSHIBA WT8-A, version: 9, platform: Android, **idiom: Phone**, deviceType: Physical

### Basic Information

- Version with issue: 1.1.0
- Last known good version: n/a
- IDE: VS2017 15.9
- Platform Target Frameworks: 
  - iOS:  
  - Android:  9/API 28 
  - UWP:   
- Android Support Library Version: 28.0.0.1  
- Nuget Packages: https://www.nuget.org/packages/Xamarin.Essentials/1.1.0
- Affected Devices: Toshiba Encore 8, which is a 8" Tablet with 1280x800 resolution that originally came with Windows 8.1, was upgraded to Win10 and I dual boot it with a [x86 Android 9 ROM](https://sourceforge.net/projects/blissos-x86/files/Official/bleeding_edge/Generic%20builds%20-%20Pie/) to test the android part of XF app and optimize layout with [Hotreload](https://github.com/AndreiMisiukevich/HotReload))

### Screenshots

![image](https://user-images.githubusercontent.com/8274816/55378491-7ced9880-5519-11e9-9f3b-9834d8774111.png)

**Comment by MagicAndre1981** [comment]
Xamarin.Forms [also reports wrong data](https://github.com/xamarin/Xamarin.Forms/issues/5708).

**Comment by MagicAndre1981** [comment]
Here is a screenshot of your [essentials sample app](https://github.com/xamarin/Essentials/blob/master/Samples/Samples/View/DeviceInfoPage.xaml):

![image](https://user-images.githubusercontent.com/8274816/56903732-26826400-6a9d-11e9-9eb2-dd60390aa33e.png)

**Comment by jamesmontemagno** [comment]
Most likely this is putting it under the 600dp ratio

Can you tell me what this returns for you in your MainActivity OnCreate:

```csharp
 var metrics = Application.Context.Resources?.DisplayMetrics;

var minSize = Math.Min(metrics.WidthPixels, metrics.HeightPixels);
var isWide = minSize * metrics.Density >= tabletCrossover;
```

Would love to know the: WidthPixel, HeightPixels, and Density.

If you want to go further you can debug our code directly:
You will want to add this code to your MainActivity and debug through it to see where it is getting set to phone:

```csharp
      int tabletCrossover = 600;
        DeviceIdiom GetIdiom()
        {
            var currentIdiom = DeviceIdiom.Unknown;

            // first try UIModeManager
            using (var uiModeManager = UiModeManager.FromContext(this))
            {
                var uiMode = uiModeManager?.CurrentModeType ?? UiMode.TypeUndefined;
                currentIdiom = DetectIdiom(uiMode);
            }

            // then try Configuration
            if (currentIdiom == DeviceIdiom.Unknown)
            {
                var configuration = this.Resources?.Configuration;
                if (configuration != null)
                {
                    var uiMode = configuration.UiMode;
                    currentIdiom = DetectIdiom(uiMode);

                    // now just guess
                    if (currentIdiom == DeviceIdiom.Unknown)
                    {
                        var minWidth = configuration.SmallestScreenWidthDp;
                        var isWide = minWidth >= 600;
                        currentIdiom = isWide ? DeviceIdiom.Tablet : DeviceIdiom.Phone;
                    }
                }
            }

            // start clutching at straws
            if (currentIdiom == DeviceIdiom.Unknown)
            {
                var metrics = Application.Context.Resources?.DisplayMetrics;
                if (metrics != null)
                {
                    var minSize = Math.Min(metrics.WidthPixels, metrics.HeightPixels);
                    var isWide = minSize * metrics.Density >= tabletCrossover;
                    currentIdiom = isWide ? DeviceIdiom.Tablet : DeviceIdiom.Phone;
                }
            }

            // hope we got it somewhere
            return currentIdiom;
        }

        static DeviceIdiom DetectIdiom(UiMode uiMode)
        {
            if (uiMode.HasFlag(UiMode.TypeNormal))
                return DeviceIdiom.Unknown;
            else if (uiMode.HasFlag(UiMode.TypeTelevision))
                return DeviceIdiom.TV;
            else if (uiMode.HasFlag(UiMode.TypeDesk))
                return DeviceIdiom.Desktop;

            return DeviceIdiom.Unknown;
        }
```

**Comment by MagicAndre1981** [comment]
@jamesmontemagno 

here is the output:

![image](https://user-images.githubusercontent.com/8274816/56911706-d8299100-6aad-11e9-9ad1-960ea7f34e5b.png)

**Comment by MagicAndre1981** [comment]
ok, I was able to find a setting in the ROM options and changed 587 to 600 and now the official code works.

![image](https://user-images.githubusercontent.com/8274816/56913076-0492dc80-6ab1-11e9-921d-69446bfbec7e.png)

![image](https://user-images.githubusercontent.com/8274816/56913181-3e63e300-6ab1-11e9-8736-5ef804e7f698.png)

**Comment by Depechie** [comment]
I know this is closed... but I would still expect that Essentials tries using the hardware capabilities check instead of just using the sizing.
For android you would check :
https://developer.android.com/reference/android/content/Context#TELEPHONY_SERVICE
https://stackoverflow.com/questions/5196833/android-device-phone-call-ability
