### ISSUE TITLE
Device Type returns Physical instead of Virtual if I run UWP app in a VMware Guest VM

### ISSUE THREAD

**Issue by MagicAndre1981** [xamarin/Essentials#776]
### Steps to Reproduce

run the [Essentials Sample app](https://github.com/xamarin/Essentials/tree/master/Samples/Samples.UWP) inside a Windows 10 VM that is powered by VMware Workstation.

### Expected Behavior

`static DeviceType GetDeviceType()` returns `DeviceType.Virtual`

### Actual Behavior

`static DeviceType GetDeviceType()` returns `DeviceType.Physical`

### Basic Information

- Version with issue: 1.1.0
- Last known good version: n/a
- IDE: VS2017 15.9
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  16299  
- Android Support Library Version: 
- Nuget Packages: 
- Affected Devices: Windows 10 1803 VM hosted by Vmware Workstation

### Screenshots

![image](https://user-images.githubusercontent.com/8274816/56907126-ed99bd80-6aa3-11e9-89d4-e0310b1c6bf4.png)

![image](https://user-images.githubusercontent.com/8274816/56907264-29cd1e00-6aa4-11e9-896a-3504d4d83a76.png)

### Reproduction Link

your sample:

https://github.com/xamarin/Essentials/tree/master/Samples

### possible Fix

change `var isVirtual = deviceInfo.SystemProductName == "Virtual";` to `var isVirtual = deviceInfo.SystemProductName.Contains("Virtual");`

at https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/DeviceInfo/DeviceInfo.uwp.cs#L64

![image](https://user-images.githubusercontent.com/8274816/56908719-29825200-6aa7-11e9-8f74-d3fd76f1c804.png)

![image](https://user-images.githubusercontent.com/8274816/56908804-533b7900-6aa7-11e9-9262-d48899868645.png)

**Comment by jamesmontemagno** [comment]
This is the expected behavior as it is running on a physical piece of hardware. The only time it  should return Virtual is if it is on an emulator for development purposes. I think your check is fine, however we wouldn't want to introduce this into the API as we couldn't manage that list.

**Comment by MagicAndre1981** [comment]
@jamesmontemagno 

this API should be still correctly detect VMs, because VMs can cause graphic glitches because of the emulated graphic card so that app developers can use it to minimize graphical effect usage.

The list is small:

https://social.technet.microsoft.com/wiki/contents/articles/942.hyper-v-how-to-detect-if-a-computer-is-a-vm-using-script.aspx

only add xen and parallels:

System Manufacturer: Parallels Software International Inc.
System Model: Parallels Virtual Platform

**Comment by jamesmontemagno** [comment]
Thank you for the additional information. Will re-open.

**Comment by MagicAndre1981** [comment]
> Thank you for the additional information. 

using Contains detects nearly all VMs (Vmware **Virtual** Platform, Parallels **Virtual** Platform, **Virtual**box, **Virtual** Machine (for Hyper-V). Only [Xen](https://wiki.xenproject.org/wiki/Xen_FAQ_Design_and_in_Depth#How_can_I_tell_if_my_OS_is_running_on_a_physical_machine_or_a_virtual_machine_.3F) returns `HVM domU`
