### ISSUE TITLE
UWP does not save preferences when providing a shared name.

### ISSUE THREAD

**Issue by dberroa** [xamarin/Essentials#777]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
When trying to save preferences using the preferences class for UWP and providing a share name, it does not save. If remove the share name, then it works as expected where my bool gets saved and retrieved.

### Steps to Reproduce

1. Create xamarin forms project and include UWP.
2. Install xamarin essentials to all projects.
3. Insert code to save a bool set to true to preferences with a shared name. This can be in the constructor or make a toggle switch and bind it to a view model (what I did). 
4. Read from preferences the bool you saved and see wrong value of false.

I wrote my save and get lines like this.

```
//Save the should upload setting.
Preferences.Set("SHOULD_UPLOAD", true, "com.company.appname");

//Get the should upload setting.
boo should_upload = Preferences.Get("SHOULD_UPLOAD", false);
```

### Expected Behavior
Expect preference to be saved with shared name.

### Actual Behavior
Does not save with shared name. It doesn't work if I do the following of removing the shared name:

```
//Save the should upload setting.
Preferences.Set("SHOULD_UPLOAD", true);
```

### Basic Information

- Version with issue:
- Last known good version: Never tried a previous version.
- IDE: Visual Studio 2019 Community Release.
- Platform Target Frameworks:
  - UWP:  Build 17763
- Affected Devices:

**Comment by jamesmontemagno** [comment]
you need to pass the group name to the Get:

```
boo should_upload = Preferences.Get("SHOULD_UPLOAD", false, "com.company.appname");
```
