### ISSUE TITLE
Connectivity Limitation Question

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#778]
> Limitations
> It is important to note that it is possible that Internet is reported by NetworkAccess but full access to the web is not available. Due to how connectivity works on each platform it can only guarantee that a connection is available. For instance the device may be connected to a Wi-Fi network, but the router is disconnected from the internet. In this instance Internet may be reported, but an active connection is not available.
> 

Hi,

Is there any future plan to fix this limitation and make it works?

Thanks,
Jassim

**Comment by jamesmontemagno** [comment]
This is a limitation of each OS itself. There is no fix for it unfortunately.
