### ISSUE TITLE
Text to speech locale

### ISSUE THREAD

**Issue by chrisfoulds** [xamarin/Essentials#779]
### Description
Failure to get the correct language to play back the speech

### Steps to Reproduce
The docs say use.
var locales = await TextToSpeech.GetLocalesAsync();
// Grab the first locale
var locale = locales.FirstOrDefault();

This returns korean on my Pixel2, when my devices language is en-GB , which is the last locale in the list.
On my Huawei P20 Pro it returns German with en-GB in the middle of the list

### Expected Behavior
en-GB to be returned as it's the devices language or have a routine that matches the devices locale to one of the ones returned.

### Actual Behavior
Random other languages

### Basic Information

- Version with issue: 1.1.0
- Last known good version: None

**Comment by jamesmontemagno** [comment]
This just queries the machine itself and is returned. It does no sorting on it, nor would we know how to apply one. If you don't pass a locale in it will be the systems default.

**Comment by jrahma** [comment]
Same Problem. getting ko when my language is en

Honor 10 Lite device
