### ISSUE TITLE
Issue with Preferences in UWP

### ISSUE THREAD

**Issue by srmunn** [xamarin/Essentials#780]
**Description**
The code below works fine on iOS and Android devices, but fails in UWP.

**Steps to Reproduce**
```
private const string DEVICEIDKEY = "deviceID";
private static readonly string DEVICEIDDEFAULT = Guid.NewGuid().ToString();

public static string DeviceID
{
       get { return Preferences.Get(DEVICEIDKEY, DEVICEIDDEFAULT); }
       set { Preferences.Set(DEVICEIDKEY, value); }           
}
```
**Expected Behaviour**
Saves and returns a Guid as a string.

****Actual Behaviour**
in UWP, it always returns the default value (a new guid).

**Basic Information**
- Version with issue: 1.1.0
- Last known good version: None.
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - UWP:  17134
- Affected Devices: Windows 10 Tablet - Fusion 5

**Comment by jamesmontemagno** [comment]
Are you setting the Device Id Somewhere?

I just ran this test and it worked flawless:

```
        public PreferencesViewModel()
        {

            var tst = DeviceID;
            DeviceID = "hello";
            tst = DeviceID;
        }



        string key = "deviceID";

        public string DeviceID
        {
            get { return Preferences.Get(key, System.Guid.NewGuid().ToString()); }
            set { Preferences.Set(key, value); }
        }
```

**Comment by srmunn** [comment]
Remove the hello line and then run the app the Guid will match, but then close the app and then run it again and you will get a different Guid - it is not saving it with UWP, but works fine in Android and iOS.

Thanks

**Comment by jamesmontemagno** [comment]
When you do a Get it will return your default value, which is a New Guid every time. This is the correct functionality. It should be a constant that you set.

**Comment by srmunn** [comment]
How can that be correct functionality when iOS and Android save it and retrieve it fine. It has to be a bug in UWP because when its got its default value the first time it will have been saved and then shouldn't change when the app runs again.

**Comment by jamesmontemagno** [comment]
I would need your sample to test it... from my testing:

1.) When you do a Get and you have never set it on all 3 platforms it returns the default value
2.) If you ask to get it again it will return that same value of the default
3.) If you re-start your app it will return a different guid because you generated a new one. 

Can you post your actual code and how you use it.
