### ISSUE TITLE
Please provide support for toast message as well

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/Essentials#781]
I need Toast message for android, iOS and Windows. 

So please provide support for it as well. I dont want to use renderer or other plugins

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
Thanks for the suggestion. We do not include new UI implementations into Xamarin.Essentials. I would recommend adding a feature request to Xamarin.Forms.
