### ISSUE TITLE
[Feature Request] SSID Wifi Network

### ISSUE THREAD

**Issue by biapar** [xamarin/Essentials#782]
Is there the support to show SSID Wifi Network?

**Comment by jamesmontemagno** [comment]
This API is not available, but we will leave this here at a feature request as we would need to do some validation to see if it is possible.

**Comment by biapar** [comment]
Thank you. I see that maybe possible to read the SSID with SDK iOS and Android API

**Comment by mattleibow** [comment]
The trick might be with iOS... That system is very protective of things like this.

**Comment by Mrnikbobjeff** [comment]
iOS supports getting the said from your currently connected WiFi: https://developer.apple.com/documentation/systemconfiguration/1614126-cncopycurrentnetworkinfo

**Comment by jamesmontemagno** [comment]
I think that we want to think about this API a bit and how we want to structure it. Maybe it should be in a class called WiFi just like UWP or should it be in Connectivity? @Redth ? I don't think we can get a lot of information off of iOS/Android like we can from UWP.

* Android: https://developer.android.com/reference/android/net/wifi/WifiInfo
* iOS: https://developer.apple.com/documentation/systemconfiguration/1614126-cncopycurrentnetworkinfo
* UWP: https://docs.microsoft.com/en-us/uwp/api/windows.devices.wifi

**Comment by Redth** [comment]
For iOS this basically requires Core Location to be enabled and approved by the user.  I'm not a big fan of this for that reason alone.  Honestly this feels like a bit of an edge case for an app... It might have to just remain something we leave out for now and you make your own dependency service for.

**Comment by jamesmontemagno** [comment]
Marking as wont implement due to ^
