### ISSUE TITLE
Mail to multiple addresses wrong on Outlook.

### ISSUE THREAD

**Issue by rdeveen** [xamarin/Essentials#784]
### Description
Mail to multiple addresses in To, CC of BCC are not separated correctly. Using comma (,) is not correct with Outlook on Windows using Xamarin.Forms UWP. 

### Steps to Reproduce
```c#
await Xamarin.Essentials.Email.ComposeAsync(new Xamarin.Essentials.EmailMessage()
{
     To = new List<string>() { "me@github.com", "other@github.com" },
});
```
### Expected Behavior
Email message with To: me@github.com; other@github.com

### Actual Behavior
Email message with To: me@github.com, other@github.com

### Basic Information
Email addresses are seperated by ;

**Comment by jamesmontemagno** [comment]
So, on UWP we call the native APIs for EmailMessage: https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.email.emailmessage

We add a EmailRecipient to each and the native API handles the rest. So, this would be out of our control and would be a bug either in UWP  Outlook.

You can look at the code and call it natively if you desire and will get the same result: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Email/Email.uwp.cs
