### ISSUE TITLE
Getting misc. bytes of data at end of URI.

### ISSUE THREAD

**Issue by Latency** [xamarin/Essentials#785]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description

Getting extra bytes in URI

### Steps to Reproduce

Share -> Mail -> 
Share -> Copy Clipboard ->

### Expected Behavior

URI is getting set with the string correctly.

### Actual Behavior

URI + "%E2%80%8B"

### Basic Information

- Version with issue:   Xamarin.Essentials (1.1.0)
- Last known good version:
- IDE:   VS2019
- Platform Target Frameworks: Standard 2.0
  - iOS:  
  - Android:  
  - UWP:  Windows 10, version 1903 (10.0; Build 18362)
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
Can you please add a sample code example.

**Comment by Latency** [comment]
**NOTE**:  I am only experiencing this problem in UWP.

I have a share callback that I am using in my form which looks like this:
```
    private static async void Share_Callback() {
      var asm = Assembly.GetExecutingAssembly();
      var request = new ShareTextRequest {
        Text = Properties.Resources.Share_Text,
        Title = asm.Product(),
        Uri = Properties.Resources.Share_URI,
        Subject = asm.Product()
      };
      await Share.RequestAsync(request);
    }

```
This will then proceed to popup the UWP dialog in which I wish to select one of the many icons.
**NOTE**:  I am getting the same results for all.   I believe it is an issue within the System library according to my debugging.  Please confirm!

Step 1:
![Untitled](https://user-images.githubusercontent.com/788296/58924099-4e499500-86f7-11e9-847c-25c12a55fd65.png)

Step 2:
  Paste contents to notepad or PFE.
![Untitled2](https://user-images.githubusercontent.com/788296/58924256-09722e00-86f8-11e9-88ae-499410630338.png)

**Comment by jamesmontemagno** [comment]
I was unable to reproduce this in Windows version 1909. we do no encoding, so seems like a windows bug perhaps that has been fixed.
