### ISSUE TITLE
placemark always null on UWP?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [xamarin/Essentials#791]
Thank you for a great Xamarin Team and Microsoft!
I using Geocoding to get the current City name. Every thing working fine on Android and iOS.
But on UWP "placemark" always return null
`var request = new GeolocationRequest(GeolocationAccuracy.Medium);
                var location = await Geolocation.GetLocationAsync(request);

                if (location != null)
                {
                    try
                    {

                        var placemarks = await Geocoding.GetPlacemarksAsync(location.Latitude, location.Longitude);
                        var placemark = placemarks?.FirstOrDefault();
                        if (placemark != null)
                        {
                            CityName = placemark.Locality;
                        }
                        else
                        {
                            CityName = "Soc Trang";
                        }
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine("PlaceMark Error: " + e.Message);
                    }
                }`

This is MainPage.xaml.cs of UWP project
`Platform.MapServiceToken = "BingMapAPI";
            LoadApplication(new MyApp.App());`

**Comment by jamesmontemagno** [comment]
What are your lat/long?

This is from our samples:
![image](https://user-images.githubusercontent.com/1676321/58125581-c11a2280-7bc5-11e9-98a4-5c18d3af1106.png)

**Comment by nguyenthanhliemfc** [comment]
![Untitled](https://user-images.githubusercontent.com/17796649/58169161-47b02c00-7cba-11e9-8e72-9ebe31457123.png)
@jamesmontemagno

**Comment by jamesmontemagno** [comment]
@nguyenthanhliemfc worked perfect for me
![image](https://user-images.githubusercontent.com/1676321/58212687-85a25580-7ca4-11e9-9dfa-580c642df759.png)
