### ISSUE TITLE
Xamarin.Essentials Map not showing destination name (with Internet)

### ISSUE THREAD

**Issue by el-jamesaranda** [xamarin/Essentials#792]
### Description
**MapLaunchOptions** **Name** attribute doesn't display properly on Google Maps App (on Android device), but only when device is connected to Internet (via wifi or data).

### Steps to Reproduce

1. **using Xamarin.Essentials** statement included.
2. Variable **options** created: 
`var options = new MapLaunchOptions
     {
            Name = "Home"
      };`
     
3. **OpenAsync** method called:

     `await Map.OpenAsync(location, options);`

     **location** variable already created with lat and long values.

### Expected Behavior

Google Maps App displays with the correct location and location name ("Home" in this case).

### Actual Behavior

Google Maps App displays with the correct location and location name **BUT** only when device isn't connected. If it's connected (via wifi or data), the correct location is shown, but location name's value is lat and long.

### Basic Information

- Version with issue: Xamarin.Essentials (1.1.0)
- Last known good version: --
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin.Essentials
- Affected Devices: Only tested on Xiaomi Mi A2

### Screenshots

![Screenshot_20190520-155624](https://user-images.githubusercontent.com/45106990/58051852-e7ce4f80-7b18-11e9-9599-58d49832d1d3.png)

**Comment by jamesmontemagno** [comment]
We simply call the native APIs to open it and it is up to google maps at that point so out of our hands.

**Comment by deejayjay** [comment]
@jamesmontemagno: Is there a way this issue can be addressed? This seems to be working in the older versions of Google Maps. The newer versions just display the coordinates.
