### ISSUE TITLE
Send Mail Using Xamarin Essentials - EmailAttachment AttachmentName not set

### ISSUE THREAD

**Issue by SJPrinsloo** [xamarin/Essentials#793]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description

Attachment name Prior to change = "102358816_6_-1_F_20170730044000_5!6!23_1.pdf"
string newShareFileName = "1021 (Dummy).pdf"

EmailAttachment emailAttachmentObject = new EmailAttachment(fullPath);
emailAttachmentObject.**AttachmentName** = newShareFileName;
### Steps to Reproduce
1. Set the New AttachmentName to the "newShareFileName "
2.  var message = new EmailMessage
                {
                    Subject = subject,
                    Body = body,
                    To = recipients
                };
        message.Attachments.Add(emailAttachmentObject );
        await Email.ComposeAsync(message);
3. Android Attaches this attachment to the email client (gmail) but didn't set it to the new fileName and still shows the fileName "102358816_6_-1_F_20170730044000_5!6!23_1.pdf"

### Expected Behavior
Attachment should have shown the new FileName ["1021 (Dummy).pdf"] and not the old name "102358816_6_-1_F_20170730044000_5!6!23_1.pdf".

### Actual Behavior
Attachment is using the old fileName "102358816_6_-1_F_20170730044000_5!6!23_1.pdf"

### Basic Information

- Version with issue:
- IDE: Visual Studio 2019 Community Edition
- Platform Target Frameworks: Android and ios
   - Android: Android 7.0 - API 24 
- Nuget Packages: Xamarin Essentials 1.1.0
- Affected Devices: Samsung Galaxy S6 - SM-G920F

### Screenshots
![Screenshot](https://user-images.githubusercontent.com/29392987/58096352-2d505280-7bd5-11e9-82c6-893daa1774dd.JPG)

**Comment by jamesmontemagno** [comment]
@Redth can you look at this. From looking through the code I only see we use this on UWP/iOS as it is required. 

I don't think we want to make copies of files, so I just need to document this as expected on Android.

**Comment by jamesmontemagno** [comment]
So, yes, this needs to be release noted here as it is used on UWP/iOS and has no effect on Android and uses the file on disc name. We do not plan on changing the name or copying it around. @Redth is this correct

**Comment by SJPrinsloo** [comment]
Hi there,

Just for interest sake did you find the issue with this, and is there maybe a time estimate for this fix.

Kind Regards,

**Comment by jamesmontemagno** [comment]
So, we are changing the functionality in 1.2.0 to not allow setting the name as it isn't really something we wanted to expose.

**Comment by jamesmontemagno** [comment]
Closing now that we have the PR into master to address this.
