### ISSUE TITLE
Browser.OpenAsync on Android doesn't really close the opened tab

### ISSUE THREAD

**Issue by georgemichailou** [xamarin/Essentials#798]
### Description
Android doesn't close the tab but it is on background.

### Steps to Reproduce

1. Call Browser.OpenAsync with BrowserLaunchMode.SystemPreferred
2. Tap X icon for close the opened tab
3. Tap android button to close applications and i found here previous closed tab is still there

### Expected Behavior
Like iOS.

### Basic Information
- Xamarin.Forms:  4.0.0.425677
- Android: 9.0 API Level 28
- Nuget Packages: 1.1.0
- Affected Devices: emulators and samsung galaxy s8

### Screenshots

![61121195_2350802261909954_4644443884317835264_n](https://user-images.githubusercontent.com/14372162/58326850-aef2eb00-7e36-11e9-8bc7-17662be650c5.jpg)
![Simulator Screen Shot - iPhone Xʀ - 2019-05-24 at 15 12 01](https://user-images.githubusercontent.com/14372162/58326859-b1eddb80-7e36-11e9-9683-496585564191.png)

**Comment by jamesmontemagno** [comment]
We hand this off to Chrome Custom Tabs, so pretty sure it is completely out of our control. We can check, but every browser may handle it different, I use chrome and it works very different.

**Comment by georgemichailou** [comment]
I understand @jamesmontemagno . I change my default browser and working perfect with chrome. A lot of browsers out there, i dont now if you can use by default chrome and ovveride the user browser selection.

**Comment by jamesmontemagno** [comment]
Will close out as there is not much I can do here from what I have read.
