### ISSUE TITLE
Tap and hold gesture. 

### ISSUE THREAD

**Issue by haavamoa** [xamarin/Essentials#799]
Today I implemented my own Tap and hold effect in order to tap and hold an item in a list to trigger a `ICommand`. I was wondering if you could make this a part of the shared Xamarin Essentials Api (like the other gestures we have available) (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/)  

Here is my implementation :
https://github.com/haavamoa/TeamTimer/commit/1fa625a2f40974fe67070f5b2e2ac4ed37343728

Read; I had to create a `TapOrTapAndHold` Effect to not remove ordinary tapping.

**Comment by jamesmontemagno** [comment]
Thanks for the suggestion. Xamarin.Essentials doesn't take on any UI specific work as that would all go in Xamarin.Forms.

**Comment by haavamoa** [comment]
Allright, I will post it as a issue in Xamarin Forms.
