### ISSUE TITLE
Emailing with multiple File attachments fails

### ISSUE THREAD

**Issue by rajeshtamda** [xamarin/Essentials#800]
### Description
I am using below code to add attachments and compose an email using Xamarin essentials.

![Screenshot (19)](https://user-images.githubusercontent.com/2899370/58553698-3a072300-8233-11e9-9317-8314482a5882.png)

When I select gmail as an option I am able to see that my 'To', 'Body', 'Subject' fields are properly prepopulated with in the compose window of gmail app except that I don't see the attachments already attached in that email.

### Expected Behavior

![IMG_20190529_164121](https://user-images.githubusercontent.com/2899370/58553912-cc0f2b80-8233-11e9-9887-d6c22e17bf96.jpg)

### Actual Behavior

![IMG_20190529_154759](https://user-images.githubusercontent.com/2899370/58553919-ce718580-8233-11e9-9d0e-e3c5e67951d4.jpg)

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2017 professional
- Platform Target Frameworks: net standard 2.x 
  - iOS:  <11.0 and above-->
  - Android: <8.0 and above --> 
  - UWP:  <17134 and above--> 
- Android Support Library Version: <28.0.0.1 -->
- Nuget Packages:  Xamarin forms 3.4.6, Xamarin.Essentials: 1.1.0
- Affected Devices: RealMe C2 , POCO F1 and so on ….

**Comment by jamesmontemagno** [comment]
I just tested on my Pixel 2XL running 9.0 and worked for me here sending a zip file.

Please add a reproduction so I can test it out.

**Comment by rajeshtamda** [comment]
Tested existence of issue on Android 9.0, it could be happening with other android versions as well.

I have attached demo project to demonstrate the same.

If you comment out attaching either of the 2 files you can observe that output is as expected but when trying to attach both of them together, it fails.

[EmailDemo.zip](https://github.com/xamarin/Essentials/files/3236857/EmailDemo.zip)

**Comment by rajeshtamda** [comment]
Also note that when I select outlook as the email option on UWP it isn't working with single attachment as well.

**Comment by jamesmontemagno** [comment]
Ahhh, i read this wrong and now see it is multiple attachments. I think i see it thanks!

Yes, not every email client may support attachements, on UWP we call the native APIs for EmailMessage: https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.email.emailmessage

You can look at the code and call it natively if you desire and will get the same result: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Email/Email.uwp.cs

**Comment by jamesmontemagno** [comment]
All fixed up in #804  Thanks for the report

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '1.1.1' that is not in the list of supported values

**Comment by newky2k** [comment]
Fixed by #804 and merged
