### ISSUE TITLE
Tracking Xamarin Forms Essentials always showing prev version blank

### ISSUE THREAD

**Issue by Swdvader** [xamarin/Essentials#801]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
Tracking not working for Essentials on Android

### Steps to Reproduce
       Android (galaxy s9+)
1.    In App.xaml.cs of project placed code for testing
2.    Xamarin.Essentials.VersionTracking.Track();
3.   string checkPrev= Xamarin.Essentials.VersionTracking.PreviousVersion;

All values except prev are filled.  After I re run the application, it still shows the same information and the prev is blank.

### Expected Behavior

First time debugged should be blank
Second time debugged should show version

### Actual Behavior
Always showing blank.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - Android: MIn 23 Target 28 PIE

**Comment by jamesmontemagno** [comment]
You need to manually change your AndroidManifest file and re-run app and ensure you aren't uninstalling your app. 

Unable to reproduce.

**Comment by Swdvader** [comment]
When I re ran the app without it being uninstalled it worked correctly.  Thank you.
