### ISSUE TITLE
SMS: InvalidOperationException in iOS PlatformComposeAsync

### ISSUE THREAD

**Issue by chrisstaley** [xamarin/Essentials#807]
### Description
I'm getting crash reports logged in AppCenter that have this info:

> Application Specific Information:
> *** Terminating app due to uncaught exception 'SIGABRT', reason: 'System.InvalidOperationException'
> 
> Xamarin Exception Stack:
> System.InvalidOperationException: 
>   at System.Threading.Tasks.TaskCompletionSource`1[TResult].SetResult (TResult result) <0x103050344 + 0x0004b> in <50aa8c853ba54c99b7836ba4b45a5828#ce6fa466e25885e0cbec812108e17229>:0
>   at Xamarin.Essentials.Sms+<>c__DisplayClass4_0.<PlatformComposeAsync>b__0 (System.Object sender, MessageUI.MFMessageComposeResultEventArgs e) <0x1043c2980 + 0x00043> in <e643d57771c64c089955fd89d4553201#ce6fa466e25885e0cbec812108e17229>:0
>   at MessageUI.Mono_MFMessageComposeViewControllerDelegate.Finished (MessageUI.MFMessageComposeViewController controller, MessageUI.MessageComposeResult result) <0x10379e5c4 + 0x00067> in <0a1822a59db24dc39fecdd861b632885#ce6fa466e25885e0cbec812108e17229>:0
>   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
>   at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) <0x1037a9bec + 0x000ef> in <0a1822a59db24dc39fecdd861b632885#ce6fa466e25885e0cbec812108e17229>:0
>   at MyApp.Mobile.iOS.Application.Main (System.String[] args) <0x102b64004 + 0x00017> in <2143ee47062d4bda9d11d7598cf5ce99#ce6fa466e25885e0cbec812108e17229>:0

I was wondering if you could provide any guidance on what to look at next. If you need any other details, let me know.

### Steps to Reproduce
The users were sending an SMS message in iOS (i.e. via the `Sms.ComposeAsync()` method).

### Basic Information

- Version with issue: 1.1.0
- Platform Target Frameworks:
  - iOS: 12.8
- Affected Devices: various iPhones (e.g. 8 and XS Max)

**Comment by newky2k** [comment]
@chrisstaley can you provide the code that leads upto the call to Sms.ComposeAsync().  Is it when the call is made or when they have composed the message and close the dialog?

**Comment by chrisstaley** [comment]
I have created a class that I use to send the SMS messages. It looks like this:

```C#
    public class SendSmsMessageCommand
    {
        private readonly IMessageBoxService _messageBoxService;

        public SendSmsMessageCommand(IMessageBoxService messageBoxService)
        {
            _messageBoxService = messageBoxService;
        }

        public async Task ExecuteAsync(string phoneNumber, string messageText = null)
        {
            string errorMessage = null;

            try
            {
                var smsMessage = new SmsMessage(messageText, new[] {phoneNumber});

                await Sms.ComposeAsync(smsMessage);
            }
            catch (FeatureNotSupportedException)
            {
                errorMessage = "This feature is not supported on your device.";
            }
            catch (Exception e)
            {
                Log.Logger.Error(e, "There was an error while sending an SMS message.");

                errorMessage = "There was an error while sending the SMS message.";
            }

            if (string.IsNullOrWhiteSpace(errorMessage) == false)
            {
                await _messageBoxService.ShowAsync(errorMessage, "Whoops!");
            }
        }
    }
```

Unfortunately, these errors were logged in AppCenter, so I don't have the exact repro steps, which is frustrating for me as well.

**Comment by mattleibow** [comment]
Maybe something happened somewhere that made the `TaskCompletionSource` invalid...

I see the error is for `TaskCompletionSource.SetResult`. A solution would maybe be to use `TrySetResult` and avoid the exception.

Or, it could be that the callback is happening twice and the second time is throwing...

**Comment by jamesmontemagno** [comment]
Very curious... can probably do some checks around it. Haven't seen this in my tests at all though. Does it happen a lot or just a small amount?

**Comment by chrisstaley** [comment]
@jamesmontemagno It _is_ very rare, but it _does_ cause the app to crash when it happens.

As an idea of how rare:
- We launched the app in Mid may.
- We average around 400 user sessions per day in iOS (we have a very limited/targeted audience).
- We've only seen three instances of the error captured by AppCenter.
