### ISSUE TITLE
Browser.OpenAsync strips away fragment from the URL

### ISSUE THREAD

**Issue by appsourcers** [xamarin/Essentials#808]
### Description
Fragment part of the URL is being stripped away after call to the `Browser.OpenAsync(string uri)`

### Steps to Reproduce

1. Call `Browser.OpenAsync` with the URL that has a fragment part
e.g `Browser.OpenAsync("https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md#ios-specific-concerns")`

### Expected Behavior
Native browser is loaded and the URL is `https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md#ios-specific-concerns`

### Actual Behavior
Native browser is loaded and the URL is `https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md`

### Basic Information

- Version with issue: 1.1.0
- Last known good version: N/A
- IDE: Visual Studio for Mac 8.0.9 (build 5)
- Platform Target Frameworks: 
  - iOS:  12.8.0.2 
  - Android: 9.2.3.0  
  - UWP:  N/A
- Android Support Library Version: N/A
- Nuget Packages: Xamarin.Essentials (v1.1.0)
- Affected Devices: All iOS and Android devices

### Reproduction Link
https://github.com/appsourcers/Browser.OpenAsync.Issue

**Comment by jamesmontemagno** [comment]
Fixed and pending release in 1.2.0-pre

**Comment by TomONeill** [comment]
Well... `mailto:something@github.com` results in `mailto://github.com`. Are we really supposed to verify each and every url and redirect it to the right intent?

```
startswith("mailto:") {
    var strippedMail = url.getMailAddress();
    var msg = new MailMsg(strippedMail);
    Email.Compose(msg);
}
elsif (startswith(tel:) {
    var strippedTel = etc.
}
else {
    Browser.Open(url)
}
```

**Comment by mattleibow** [comment]
@TomONeill I would suggest opening a new issue for that because it is a different issue and we should be handling that.
