### ISSUE TITLE
CREATEMULTIDEXMAINDEXCLASSLIST Issue

### ISSUE THREAD

**Issue by brad-dixon** [xamarin/Essentials#810]
### Description
The below error occurs for me during both a debug and release build on my local machine ...

`/Users/{user}/{company}/{project}/Droid/CREATEMULTIDEXMAINDEXCLASSLIST: Error: Can't write [/private/var/folders/zx/cg5_6s3930q1f4t896hrk7t00000gn/T/9rugjo7k.1ft.jar] (Can't read [/Users/{user}/{company}/{project}/Droid/obj/Debug/lp/78/jl/bin/classes.jar(;;;;;;!META-INF/MANIFEST.MF)] (Duplicate zip entry [classes.jar:android/arch/lifecycle/LiveData$1.class])) ({project}.Droid)`

... and this only seems to happen when Xamarin.Essentials is added.  If I remove it, the project builds without issue.

There is another issue open here ...

https://github.com/xamarin/XamarinComponents/issues/579

... but I do not have `Xamarin.Google.Guava` installed on this project so apologies if this is already open elsewhere.

### Basic Information

Given it looks related, the project has multidex turned on due to the inclusion of a package that was added around 12 months ago.

The project is targeting `Android 9.0 (API Level 28)` but also tried on `8.1` and still got the same error.

Happy to provide more information where appropriate.

Apologies if this isn't linked to Essentials but it's the only thing I currently have to go on.

### Version

Visual Studio version information attached.

[Version Info.pdf](https://github.com/xamarin/Essentials/files/3279444/Version.Info.pdf)

**Comment by jamesmontemagno** [comment]
It could be that you have some libraries already added in and now this puts you over the multi-dex limit. In your project settings simply turn on multi-dex.

**Comment by brad-dixon** [comment]
Thanks James. Yes, understood but you may have missed in my description, multidex was turned on 12 months ago just before we went live with the app.

Another package pushed it over the top, hence why it’s been on for so long.

On 14 Jun 2019, at 5:18 am, James Montemagno <notifications@github.com<mailto:notifications@github.com>> wrote:


It could be that you have some libraries already added in and now this puts you over the multi-dex limit. In your project settings simply turn on multi-dex.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_xamarin_Essentials_issues_810-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAHLLEWRMQRS4NGCGHFIS7VTP2KMNBA5CNFSM4HXFARU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXUYJRY-23issuecomment-2D501843143&d=DwMCaQ&c=ybHZaEq7Z1pnRWlRRBea1Q&r=_NniVtqW93k3f_vN_e_kdC74KuTNwT45UlXTMNScoZI&m=XwYD6ogIRu_WTnIWpMJZIgNx0KYTHovnUOm_I6E9HSk&s=LIP6M6mdorn2wM4TRWaRxXk26aAbuVjEvtWL80lqob8&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHLLEWTXN765Z2BALXURAVDP2KMNBANCNFSM4HXFARUQ&d=DwMCaQ&c=ybHZaEq7Z1pnRWlRRBea1Q&r=_NniVtqW93k3f_vN_e_kdC74KuTNwT45UlXTMNScoZI&m=XwYD6ogIRu_WTnIWpMJZIgNx0KYTHovnUOm_I6E9HSk&s=IxWH-cVXth_rsDptVAF_EmHCrJLNCcuM_LRZzQh9fCI&e=>.

----------------------------------------------------------------------
Email Disclaimer: This email and any attachments may contain confidential information of MMG. It may also be legally privileged and/or the subject of copyright. If you are not an intended recipient, you may not copy, forward, disclose, save or use any part of it. If you have received this email in error, please notify the sender and delete the email and your reply from your system. Although this email has been checked for viruses and other defects, no responsibility can be accepted for any loss or damage arising from its receipt or use. MMG respects your privacy.

**Comment by jamesmontemagno** [comment]
Ah, i see that comment now in there. Is it using the D8/R8 settings?

**Comment by jamesmontemagno** [comment]
@Redth  any insight into this.... seems like a weird multi-dex issue... perhaps different dependencies from other nugets.

**Comment by Redth** [comment]
This isn't really specific to essentials, it's just that you're hitting the max # of methods in the main dex file for the android app.  One way to help mitigate this is to enable proguard to link away unused bits of native java code to bring the overall dex count down.

I'd try proguard and try again.

**Comment by brad-dixon** [comment]
@redth, yeah, was kinda wondering if there was a limit to multidex. Not used to these ceilings that exist in Android. Will try a few things and feed back to the both of you.

**Comment by brad-dixon** [comment]
@Redth @jamesmontemagno time for a stiff drink I think!  It's lucky it's Friday afternoon here where I am.

Not having any luck, after reading through this issue ... https://github.com/xamarin/xamarin-android/blob/master/Documentation/guides/D8andR8.md ... and the instructions on how to apply the d8/r8, I tried the following combinations with the associated results.

> Multi-Dex = **On**, Dex Compiler = **dx**, Code Shrinker = **proguard**

```
...
  Task "Desugar"
...
    Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 5
    	at org.objectweb.asm.ClassReader.a(Unknown Source)
    	at org.objectweb.asm.ClassReader.a(Unknown Source)
    	at org.objectweb.asm.ClassReader.a(Unknown Source)
    	at org.objectweb.asm.ClassReader.b(Unknown Source)
    	at org.objectweb.asm.ClassReader.accept(Unknown Source)
    	at org.objectweb.asm.ClassReader.accept(Unknown Source)
    	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:391)
    	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
    	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
    	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2732,3): error : java.lang.ArrayIndexOutOfBoundsException :  5
  Done executing task "Desugar" -- FAILED.
Done building target "_CompileToDalvikWithDx" in project "MyProject.Droid.csproj" -- FAILED.
Target "_CleanGetCurrentAndPriorFileWrites" skipped. Previously built unsuccessfully.
Done building project "MyProject.Droid.csproj" -- FAILED.
```

> Multi-Dex = **On**, Dex Compiler = **d8**, Code Shrinker = **proguard**

The logs here are a little more verbose and is far too much to drop in to this thread.  Bottom line, a lot of checking on classes but no distinct and called out errors, that I can see.  I really need an expert to decipher a lot of what I am seeing, bottom line however, the below conclusion to the build ...

```    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.D8.targets(49,5): error MSB6006: "java" exited with code 1.
  Done executing task "Proguard" -- FAILED.
Done building target "_CompileToDalvikWithD8" in project "MyProject.Droid.csproj" -- FAILED.
Target "_CleanGetCurrentAndPriorFileWrites" skipped. Previously built unsuccessfully.
Done building project "MyProject.Droid.csproj" -- FAILED.
```

> Multi-Dex = **On**, Dex Compiler = **d8**, Code Shrinker = **r8**

```
...
  Task "R8"
      processing ClassesZip, JavaLibrariesToEmbed...
...
    R8 : warning : Missing class: com.samsung.android.fingerprint.FingerprintManager$EnrollFinishListener
    R8 : warning : Missing class: com.samsung.android.fingerprint.FingerprintIdentifyDialog$FingerprintListener
    R8 : warning : Missing class: com.samsung.android.fingerprint.IFingerprintClient$Stub
    R8 : error : Compilation can't be completed because some library classes are missing.
    Compilation failed
    The command exited with code 1.
  Done executing task "R8" -- FAILED.
Done building target "_CompileToDalvikWithD8" in project "MyProject.Droid.csproj" -- FAILED.
Target "_CleanGetCurrentAndPriorFileWrites" skipped. Previously built unsuccessfully.
Done building project "MyProject.Droid.csproj" -- FAILED.
```

As you can imagined, I've Googled (sorry, Binged) the bejesus out of the above but nothing has jumped out and helped me.

I'm fairly unclear at this point if I've hit some kind of hard ceiling, the errors don't point it to being that.  I've had a look through the nuget packages being included and there's virtually nothing I can remove without having to rework the entire project ... not to mention I inherited this bad boy from a previous developer.

The inclusions I made for Essentials was nothing more than Geolocation and Connectivity and @jamesmontemagno based on what I read here ... https://montemagno.com/optimizing-xamarin-apps-libraries-with-the-linker/ ..., and my limited understanding of the linker, Essentials has been fully "linkerized" so should the compiler not be stripping everything else away that's not being used?  Having said that, it may very well be doing that but is still pushing me over the edge.  I hope my understanding is correct.

If you guys have no other suggestions, do you think it's worth closing this and throwing it over the fence to the `Xamarin.Android` team?

Again, thanks for your help, massively appreciated.

**Comment by jamesmontemagno** [comment]
Thanks for the write up, it is hard to know without knowing all the dependencies and seeing what is in there. Assumption is that we have a few support libraries in there. Even though it is fully linker safe there is still native code that gets called and that adds to the dex count at the and of the day (even if it is just 1 method in Essentials).

@JonDouglas and @jonathanpeppers may be able to help out, but perhaps if we had a sample or knew what nugets you had we could figure it out. We can share that privately and start up a thread.

**Comment by jonathanpeppers** [comment]
> Multi-Dex = On, Dex Compiler = d8, Code Shrinker = r8

You should not need multidex if you have a code shrinker. You may be hitting an issue I saw when using r8+multidex: https://github.com/xamarin/xamarin-android/commit/34ee4735646d3c6df46bb0b8369c502f0f69d7ca

But let's recap...

### What settings are for Debug and which ones Release?

* Debug - you want fast builds, you sacrifice APK size / startup time for a faster "developer loop".
* Release - you want your APK to be small & startup fast, at the tradeoff of a longer build. Hopefully you are running these on CI, anyway.

So Debug these are the settings that make sense:
* Linker is off
* Code Shrinker is off
* Multidex is on--*only* if your app hits the dex limit without it

Release:
* Linker is on
* Code Shrinker is on -- if you want to use it, you may need proguard rules
* Multidex should be off if you are using the Code Shrinker (should keep you under the dex limit)

### Also 🤦‍♂ 

There is an issue in VS 2019 16.1, where this dropdown won't let you "unselect" a code shrinker:

![image](https://user-images.githubusercontent.com/840039/59517488-50df8380-8e89-11e9-9a3c-4374e461ec89.png)

If you hit this, you can edit the `csproj` file manually to workaround. Just remove `<AndroidLinkTool>` completely.

### Questions

* After you configure your app as prescribed above for Debug/Release? does it work?
* Does your app work without the new d8/r8 settings? (Using dx and either no code shrinker or proguard)

Hope that helps!

**Comment by brad-dixon** [comment]
@jonathanpeppers thanks for the clarification and the targeted approach for the settings.

The good news is, I've managed to get everything building and there's no doubt that this has been a learning experience for me.

There's no bad news as such but something that definitely came into play but was a little more hidden away was the "Desugar" step.  If it's set in .csproj, that setting doesn't appear (at least I couldn't find it) when you open up the project properties in VS 2019 for Mac.  I added it after reading your blog to see if it would help me.  Of course, it didn't, at least, it didn't when needing to play with the other key build properties.

When I made the settings you suggested above, "Desugar" often got in the way.  I had it set but it didn't want to play with the settings you had provided in your last suggestion. 

Good news though, I do have "None" however as an option for the Code Shrinker setting so Windows is clearly different in that regard.

Now, before, I go on, I think the actual root cause of my issue was something to do with me needing to up the target version of the build to accommodate Essentials along with `Xamarin.Android.Arch.Lifecycle.LiveData` being somewhat out of whack when moving to target 9.0 ...!

Then when @jamesmontemagno and @Redth mentioned proguard and d8/r8, I made changes to the project to accommodate the new settings and through a comedy of errors, builds stopped working and different errors started to appear.  The one thing that I thought I was sure of though is that Multidex was very much a requirement but as it turns out and as you already know Jonathan, it's not.

So I got curious and today and I performed a build on all of the different combinations (ignoring those that were called out in your d8/r8 blog post) of the 5 major settings that had come into the mix throughout this whole thing.  This was the result ...

![image](https://user-images.githubusercontent.com/30847578/59580814-f9097c80-9115-11e9-9bed-4a6c1e0d587d.png)
As you can see, multiple different combinations allowed for a successful build but more interestingly, no Multidex in a lot of those cases.  You can also see that Multidex on with Desugar on was never successful, so I was always up against it given I thought Multidex was a must for this project.

I figure you guys are all over that stuff already but for anyone else who comes across this thread, they may very well find it useful.

Refinement of the APK size or build speed is not currently something I am concerned with.  Just getting the thing to build again was my biggest challenge and now I have a whole heap of options from a settings perspective, noting that `Debug` and `Release` will typically be different, which is nothing new.

So thanks to you guys for helping me through this.  I very much appreciate it.

Thanks again!!!

**Comment by jonathanpeppers** [comment]
@brad-dixon `<AndroidEnableDesugar>` is a setting you should probably just remove, as Google has moved support to d8 for this.

_What is doing?_ It "desugars" Java 8+ code so that it will run on Android. It removes the "syntactic sugar".

If you hit an error saying something like "dx failed, XYZ is not supported", then your app uses a Java library using Java 8+ features. You would be better off just using `<AndroidDexTool>d8</AndroidDexTool>` instead in that case. It supports desugaring by default.

@brad-dixon if there is a combination here, that seems like it _should_ work. Can you post a bug on [xamarin-android](https://github.com/xamarin/xamarin-android/issues) with a [build log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)?
