### ISSUE TITLE
Xamarin Essetntial NoSQL

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#811]
Hi,

It will be great if you add a feature to write, read and query NoSQL files.

User can create a NoSQL file for employee for example:

```
{
  "Employees" : [
  {
      "userId":"rirani",
      "jobTitleName":"Developer",
      "firstName":"Romin",
      "lastName":"Irani",
      "preferredFullName":"Romin Irani",
      "employeeCode":"E1",
      "region":"CA",
      "phoneNumber":"408-1234567",
      "emailAddress":"romin.k.irani@gmail.com"
  },
  {
      "userId":"nirani",
      "jobTitleName":"Developer",
      "firstName":"Neil",
      "lastName":"Irani",
      "preferredFullName":"Neil Irani",
      "employeeCode":"E2",
      "region":"CA",
      "phoneNumber":"408-1111111",
      "emailAddress":"neilrirani@gmail.com",
      {
            "Leaves":
            {
                  ................
                  ................
                  ................
            }
      }
  }
]

```
and they can query and update

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by Happypig375** [comment]
This is not really tied to mobile platforms and can be its own library that can work everywhere.

**Comment by jamesmontemagno** [comment]
On this it isn't something that each platform really offers and there are a lot of options for databases out there today. So, for that reason of it not being a native platform API this wont be added to the roadmap, but thank you for the suggestion.
