### ISSUE TITLE
Any chance to have a keybardless Entry field?

### ISSUE THREAD

**Issue by dinobu** [xamarin/Essentials#816]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
It would be useful if you want to enter in a focused entry using your custom buttons.  Or if you want to scan barcode into entry using HID scanner (2nd keyboard) without having to pop up keyboard on each scan

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
To have some kind of input view such as Entry that allows receiveing programatic Focus call without popping up soft keyboard in Xamarin.Forms Android, iOS, and UWP

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by Happypig375** [comment]
Anything related to UI should be in Xamarin.Forms.

**Comment by jamesmontemagno** [comment]
As @Happypig375 mentioned head over to http://github.com/xamarin/xamarin.forms to post.

**Comment by dinobu** [comment]
> As @Happypig375 mentioned head over to [http://github.com/xamarin/xamarin.forms](https://github.com/xamarin/xamarin.forms) to post.

Thanks, already done so ... there have been request for that functionality since 2016 btw but I created couple of my own
