### ISSUE TITLE
Cannot access a disposed object.  Object name: 'Android.App.UiModeManager'.

### ISSUE THREAD

**Issue by PawKanarek** [xamarin/Essentials#817]
### Description
My tv app was alive for a long time and that was just one and only time when exception occurred, sadly i cannot give you any logical steps to reproduce 
### Steps to Reproduce

1. Run app for a very long time, navigate trough many pages. Use method Xamarin.Essentials.DeviceInfo.get_Idiom alot 
### Basic Information

- Platform Target Frameworks: 
  - Android: AndroidTV 8.0
- Android Support Library Version: 
  - Xamarin.Android.Support.v17.Leanback 28.0.0.1
- Nuget Packages:
  - Xamarin.Essentials 1.1.0
  - Xamarin.Forms 3.5.0.274416

### CallStack
```
Object name: 'Android.App.UiModeManager'.
06-17 15:46:08.331 I/mono-stdout(21017): Object name: 'Android.App.UiModeManager'.
 at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <286213b9e14c442ba8d8d94cc9dbec8e>:0 06-17 15:46:08.336 I/mono-stdout(21017):  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <286213b9e14c442ba8d8d94cc9dbec8e>:0 

  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualInt32Method (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <286213b9e14c442ba8d8d94cc9dbec8e>:0 
06-17 15:46:08.337 I/mono-stdout(21017):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualInt32Method (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <286213b9e14c442ba8d8d94cc9dbec8e>:0 
06-17 15:46:08.337 I/mono-stdout(21017):   at Android.App.UiModeManager.get_CurrentModeType () [0x0000a] in <95d915721ad748108ff096dce8f8f32c>:0   at Android.App.UiModeManager.get_CurrentModeType () [0x0000a] in <95d915721ad748108ff096dce8f8f32c>:0 
  at Xamarin.Essentials.DeviceInfo.GetIdiom () [0x00011] in D:\a\1\s\Xamarin.Essentials\DeviceInfo\DeviceInfo.android.cs:36 

06-17 15:46:08.338 I/mono-stdout(21017):   at Xamarin.Essentials.DeviceInfo.GetIdiom () [0x00011] in D:\a\1\s\Xamarin.Essentials\DeviceInfo\DeviceInfo.android.cs:36 
  at Xamarin.Essentials.DeviceInfo.get_Idiom () [0x00000] in D:\a\1\s\Xamarin.Essentials\DeviceInfo\DeviceInfo.shared.cs:19 
  at DroidScreenDimensionsService.GetScreenHeightPx () [0x0002c] in <a56b9e699651428c80f4659ffa1f75bb>:0 
06-17 15:46:08.338 I/mono-stdout(21017):   at Xamarin.Essentials.DeviceInfo.get_Idiom () [0x00000] in D:\a\1\s\Xamarin.Essentials\DeviceInfo\DeviceInfo.shared.cs:19   
```

**Comment by PawKanarek** [comment]
@jamesmontemagno  what do you think. I should protect calls to property  Xamarin.Essentials.DeviceInfo.Idiom in my code or you could add some protection [in line 36 here](https://github.com/xamarin/Essentials/blob/6d34616d82e572e51e3ade48da3ce853e98a6b87/Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs#L36)?

**Comment by jamesmontemagno** [comment]
Very very strange. We are about to ship 1.2.0-pre and will include a built in try/catch for it. Although it shouldn't ever be an issue.

**Comment by PawKanarek** [comment]
I agree with you that shouldn't happen :) Ill leave here just little more explanation to this strange exception.
My AndroidTV app has navigation based on MVVMCross library, and it has a lot (30-40) activities and its main purpose is to watch video(obviously). So navigation here is a bit different than navigation in the Xamarin.Forms where we have in general just 1 Activity per application. 

Long story short, exception happened when app was alive for a bit longer period of ~45 min  (all time in foreground) combined with action that supposed to navigate user to new Activity inside app. So maybe there is problem with context switching in my app, or maybe Essentials.Platform.AppContext was already disposed when app was calling Xamarin.Essentials.DeviceInfo.GetIdiom, but how as its reference to Android Application.Context?

Your fix will surly do the work, and Xamarin.Essentials will be safer lib, but im afraid that there is something wrong with my app overall...

**Comment by jamesmontemagno** [comment]
@PawKanarek i don't know or think if it is an issue with your app at all. COuld just be some weird garbage collection going on. Would be good to monitor it thought.  

Closing as we have a fix in.
