### ISSUE TITLE
UWP Geolocation - user not prompted for allowing location

### ISSUE THREAD

**Issue by ckrempp91** [xamarin/Essentials#819]
### Description
During utilization of the Geolocation API of Xamarin.Essentials it was discovered that the prompt for permission access does not display for Windows 10 (UWP) devices. [Here](https://github.com/MicrosoftDocs/xamarin-docs/issues/1541) is the location of the original issue mentioned within the Microsoft Docs of Xamarin Essentials Geolocation.

Here is the sample code that was provided within the original bug report:
```
try
{
var request = new GeolocationRequest(GeolocationAccuracy.High, TimeSpan.FromSeconds(10));
var location = await Geolocation.GetLocationAsync(request);
}
catch (PermissionException pEx){
...pEx = LocationWhenInUse always comes up..no prompt to user for allowing location
when looking at the app settings in Windows 10 for the App ..position is greyed out.
}
```

I can confirm using this code will have the issue still using latest version 1.1.0

I have confirmed that the "Location" checkbox is checked under the "Capabilities" portion of the `Package.appxmanifest` file as stated [here](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?context=xamarin%2Fandroid&tabs=uwp#tabpanel_CeZOj-G++Q_uwp).

Note - I have also attempted to use the the `CrossPermissions.Current.RequestPermissionsAsync` call to force the prompt to appear, but it does not display either. The response has the requested permission with a status of "Granted", but then the `Geolocation.GetLocationAsync` fails with the same `PermissionException`
```
var permissionResult = await CrossPermissions.Current.RequestPermissionsAsync(Permission.LocationWhenInUse);
var location = permissionResult.TryGetValue(Permission.LocationWhenInUse, out var locPermission) && locPermission == PermissionStatus.Granted
? await Geolocation.GetLocationAsync(new GeolocationRequest(desiredAccuracy, TimeSpan.FromSeconds(timeoutInSeconds ?? 30)))
: null;
```

I believe the request call does not work because per the PermissionsPlugin documentation the UWP version only supports "Location", but the Geolocation API needs "LocationWhenInUse" as shown [here](https://github.com/jamesmontemagno/PermissionsPlugin#windows-10-uwp).

### Expected Behavior
The app would prompt the user with a permission request to use the "Location" permission

### Actual Behavior
PermissionException is always thrown like so:
```
Xamarin.Essentials.PermissionException: LocationWhenInUse was not granted.
   at Xamarin.Essentials.Permissions.RequireAsync(PermissionType permission)
   at Xamarin.Essentials.Geolocation.PlatformLocationAsync(GeolocationRequest request, CancellationToken cancellationToken)
```

### Basic Information

- Version with issue: 1.1.0
- Last known good version: Unknown
- IDE: Visual Studio 2019 16.1.1
- Platform Target Frameworks:
  - iOS:  [Xamarin.iOS 12.10.0.153] Target = 12.2
  - Android: [Xamarin.Android 9.3.0.22] Target SDK = 27
  - UWP: Windows 10 SDK 10.0.16299.0

**Comment by jamesmontemagno** [comment]
Can you put together a very small sample that we can test out please.

**Comment by freever** [comment]
Hi @jamesmontemagno, I can confirm this issue in 1.3.1 and have put together a very simple repro:
https://github.com/freever/UWPLocationRepro

**Comment by freever** [comment]
@ckrempp91 Did you ever find a workaround for this? I'm totally stuck, can't use essentials for location on UWP.

**Comment by jamesmontemagno** [comment]
I pulled down your app and it asked immediatelly
![image](https://user-images.githubusercontent.com/1676321/66706070-897e5500-ece3-11e9-9084-8339d76313ea.png)


Is location turned on on your machine?

**Comment by freever** [comment]
Hi James

Thanks for getting back to me. You're quite right, my machine did not have location switched on. Total user fail. 

I was however somewhat misled by the PermissionException... should this case not throw a FeatureNotEnabledException or FeatureNotSupportedException instead?

**Comment by jamesmontemagno** [comment]
So.... it is actually unfortunate as we would like to, however the API just returns "denied" :( and this is true if the user actually denied it or if it was disabled :(

I will document this though.

**Comment by freever** [comment]
Great, thanks again for your help.

**Comment by praveeen-x** [comment]
Getting an error while reproducing. But when the location is pre-set as ON it is working fine.
