### ISSUE TITLE
android clipboard:Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by juepiezhongren** [xamarin/Essentials#820]
protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            Xamarin.Essentials.Platform.Init(this, savedInstanceState);
            kkkk();
        }

        public void kkkk() {
            Task.Run(async () => {
                while(true) {
                    try {
                        var text = await Clipboard.GetTextAsync();

                        if(text.StartsWith("搞起来:")) {
                            var ss = text.Replace("搞起来:","").Split("___");
                            if(ss.Length == 2) {
                                var (fileName, url) = (ss[0], ss[1]);

                                var buf = await new HttpClient().GetByteArrayAsync(url);

                                using(FileStream fs = new FileStream($"/storage/emulated/0/DCIM/Camera/{fileName}.png",FileMode.Create,FileAccess.Write)) {
                                    await fs.WriteAsync(buf,0,buf.Length);
                                    fs.Close();
                                }
                            }
                        }
                        await Task.Delay(1000);
                    } catch(System.Exception e) {
                        await Task.Delay(1000);
                    }
                }
            });
        }

**Comment by jamesmontemagno** [comment]
The clipboard server needs to be created on the UI Thread, so your workaround would be to call:

Clipboard.HasText;

before you call this method.

**Comment by Happypig375** [comment]
Can this be improved? e.g. catching and calling `BeginInvokeOnMainThread`?

**Comment by jamesmontemagno** [comment]
This is a tricky one and needs some discussion as you shouldn't attempt to access the clipboard from the non-ui thread in general. 

We probably need to do some checks when getting any of the Android services as they all would have this issue, but in general we would just throw an exception saying you need to access it from the UI thread.

**Comment by jamesmontemagno** [comment]
I have added docs about the clipboard: https://github.com/MicrosoftDocs/xamarin-docs/pull/1812
