### ISSUE TITLE
UWP SecureStorage size limit

### ISSUE THREAD

**Issue by jjallen37** [xamarin/Essentials#821]
### Description
When calling `SecureStorage.SetAsync` on UWP with a string longer than ~8K characters, an error is thrown. 

System.Runtime.InteropServices.COMException error is thrown.
> The size of the state manager setting value has exceeded the limit.
>
> Error trying to write application data container value
-----
I believe this is due to the UWP size limit of values stored (https://stackoverflow.com/questions/34496371/unhandled-exception-the-size-of-the-state-manager-setting-value-has-exceeded-th).

I would expect it to store strings of arbitrary length like in iOS and Android because nothing is mentioned in the documentation.

- Platform Target Frameworks: 
  - UWP:  Fall Creators Update 16299

**Comment by jamesmontemagno** [comment]
Probably just need to document this. Thanks for the report.

**Comment by newky2k** [comment]
Could we capture the length and run a check on it on UWP?

**Comment by jamesmontemagno** [comment]
I have added documentation and will close now.
