### ISSUE TITLE
Sign in with Apple ID

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#822]
Hi,

Referring to this [issue](https://github.com/xamarin/Xamarin.Forms/issues/6430).

[https://github.com/xamarin/Xamarin.Forms/issues/6430](https://github.com/xamarin/Xamarin.Forms/issues/6430)

With the new Sign in with Apple ID coming with iOS 13, I hope this will be added to Xamarin Forms as a separate XF Nuget Package to help using this feature

Thanks,
[Jassim](https://www.softnames.com)

**Comment by jamesmontemagno** [comment]
This would most likely just be a core API or something supported by Xamarin.Auth on the different platforms. Auth isn't part of the Xamarin.Essentials API surface at this point.
