### ISSUE TITLE
Time out on java class cast exception

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Essentials#830]
Set a preference in xamrian forms 4.0 and I am getting the following where WarehouseFromId is a long 
Where WarehouseFromId  is long being passed in from a construtor.

      public long WarehouseFromId { get; set; }

  Preferences.Set("WarehouseFromId", WarehouseFromId);

Unhandled Exception:
```
Java.Lang.ClassCastException: <Timeout exceeded getting exception details>
```

**Comment by jamesmontemagno** [comment]
This means at some point you used this ID for a different value type. You will ha e to change the ID completely or remove it first before setting it.

**Comment by davidbuckleyni** [comment]
Hi James,
  I am using this through debug is the session for the preferences kept alive during a debug session or does it die with the session.

**Comment by jamesmontemagno** [comment]
Preferences are fully persisted throughout and after the session. You can uninstall the app and re-install it.

If you have more code examples of how you are getting and setting and using it that would be helpful.

**Comment by jamesmontemagno** [comment]
Closing out as answered above ^
