### ISSUE TITLE
[Bug] Java.Lang.Exception: -49

### ISSUE THREAD

**Issue by gabry90** [xamarin/Essentials#831]
### Description
Crash detected on my appcenter dashboard

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
No Crash!

### Actual Behavior
Crash when call SetAsync on SecureStorage

### Basic Information

- Version with issue: latest sable
- Last known good version: ?
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android: 7.0
  - UWP: 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: ZenFone 3 Max (ZC520TL)

### Screenshots

`android.security.KeyStoreException: -49
android.security.KeyStore.getKeyStoreException(KeyStore.java:685)
android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:132)
android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:217)
android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
javax.crypto.Cipher.doFinal(Cipher.java:2056)
mono.android.animation.ValueAnimator_AnimatorUpdateListenerImplementor.n_onAnimationUpdate(Native Method)
mono.android.animation.ValueAnimator_AnimatorUpdateListenerImplementor.onAnimationUpdate(ValueAnimator_AnimatorUpdateListenerImplementor.java:30)
android.animation.ValueAnimator.animateValue(ValueAnimator.java:1346)
android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1258)
android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1306)
android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:905)
android.view.Choreographer.doCallbacks(Choreographer.java:709)
android.view.Choreographer.doFrame(Choreographer.java:641)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
android.os.Handler.handleCallback(Handler.java:836)
android.os.Handler.dispatchMessage(Handler.java:103)
android.os.Looper.loop(Looper.java:208)
android.app.ActivityThread.main(ActivityThread.java:6267)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)`

`JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
Cipher.DoFinal (System.Byte[] input)
AndroidKeyStore.Encrypt (System.String data)
SecureStorage.PlatformSetAsync (System.String key, System.String data)
SecureStorage.SetAsync (System.String key, System.String value)
CampaignService.SaveCampaign (System.Boolean incrementalLocalVersion)
CampaignService.SetupCampaign ()
CampaignService.LoadCampaign (System.Collections.Generic.List`1[T] campaign)
MainScene.LoadData ()
MainScene.OnAppearing ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.60(intptr,intptr)
javax.crypto.IllegalBlockSizeException
android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
javax.crypto.Cipher.doFinal(Cipher.java:2056)
mono.android.animation.ValueAnimator_AnimatorUpdateListenerImplementor.n_onAnimationUpdate(Native Method)
mono.android.animation.ValueAnimator_AnimatorUpdateListenerImplementor.onAnimationUpdate(ValueAnimator_AnimatorUpdateListenerImplementor.java:30)
android.animation.ValueAnimator.animateValue(ValueAnimator.java:1346)
android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1258)
android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1306)
android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:905)
android.view.Choreographer.doCallbacks(Choreographer.java:709)
android.view.Choreographer.doFrame(Choreographer.java:641)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
android.os.Handler.handleCallback(Handler.java:836)
android.os.Handler.dispatchMessage(Handler.java:103)
android.os.Looper.loop(Looper.java:208)
android.app.ActivityThread.main(ActivityThread.java:6267)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
Caused by: android.security.KeyStoreException: -49
android.security.KeyStore.getKeyStoreException(KeyStore.java:685)
android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:132)
android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:217)
android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
... 20 more`

**Comment by davehump** [comment]
@gabry90  Do you have some more details on this issue?

**Comment by nuno-silva** [comment]
FYI this is probably due to a broken KeyStore on the ZC520TL running Android 8.1. See e.g. [google/tink#339](https://github.com/google/tink/issues/339#:~:text=small,keystore%20implementations).

**Comment by jfversluis** [comment]
No response for a looooooong time. Closing this one.
