### ISSUE TITLE
[Enhancement] Merge Email API with Share API

### ISSUE THREAD

**Issue by saadsaifse** [xamarin/Essentials#834]
## Summary
Sharing files to other apps also include email apps such as Gmail etc. If user selects the email app, there is no option to specify email Subject and Body text. This feature is rather provided by separate Email API and is not integrated with the Share API. Functionality wise, that means, asking the user specifically whether he wants to send an email or share to other apps. This is not efficient, as user could still see email clients in Share option. 

## API Changes

I would suggest to write separate handlers for each targeted app that Share API takes to handle the app specific arguments while sharing and populating them in the target app.

**Comment by jamesmontemagno** [comment]
When using the Email API it targets and uses Email specific APIs on each platform.

Android uses intents and any number of apps can accept a generic share intent. So if a developer wants to do a generic share for any app then you would want to use that API, else you would want Share. Email also provides the ability to do many things that Share can not such as multiple attachments and information specific to Email.

Share is usually used for sharing links, text, or an image to other social apps.

Hope this clarifies the use case for each API.
