### ISSUE TITLE
[Bug] possible race condition in Android MainThread

### ISSUE THREAD

**Issue by eli-darkly** [xamarin/Essentials#838]
### Description
I'm not 100% sure this is a bug— I may just be confused about how this stuff works in Android. But, in the Android implementation of [MainThread](https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/MainThread/MainThread.android.cs), this code makes me nervous:

```
static Handler handler;

// ...

static void PlatformBeginInvokeOnMainThread(Action action)
{
    if (handler?.Looper != Looper.MainLooper)
        handler = new Handler(Looper.MainLooper);
    handler.Post(action);
}
```

This method could be called from many threads at once, but `handler` seems to be accessed and modified in a non-thread-safe way. It could change between the first and second lines of the method, in which case different threads would each create their own `Handler` instance; is that OK?

Also, assuming it is possible for `Looper.MainLooper` to change (I don't know why it would, but again I don't know Android very well, and I'm assuming that if it could not change then we wouldn't be bothering with this lazy initialization logic at all)— if it changes in between the second and third lines, we are now posting to an obsolete `Handler` instance that points to the wrong `Looper`; is that OK?

At the very least I would expect this field to be `volatile`.

### Steps to Reproduce
I haven't reproduced it; this is a theoretical problem.

**Comment by jamesmontemagno** [comment]
Thanks for the detailed issue.

Reference code: https://github.com/xamarin/Xamarin.Forms/blob/62dfadabf2bb1f3211deed33b17b0a462c1ba2d9/Xamarin.Forms.Platform.Android/Forms.cs#L530 Will follow up with the team here, however I do not think there are any issues with the source code or usage, but will provide more details.

**Comment by jamesmontemagno** [comment]
This is a good optimization to add `volatile` in and we will do that :)
