### ISSUE TITLE
[Enhancement] Essentials.Share Open In Browser

### ISSUE THREAD

**Issue by jamesdlow** [xamarin/Essentials#841]
## Summary
When using Essentials.Share to share a URL, it would be great if there was an option to open in the default web browser on iOS and Android.

**Comment by jamesdlow** [comment]
There is an example for the iOS side of the code here:

[https://forums.xamarin.com/discussion/9579/sharing-a-url-to-the-browser-with-uiactivityviewcontroller](url)

**Comment by Redth** [comment]
This functionality is available in the Browser API: https://docs.microsoft.com/en-us/xamarin/essentials/open-browser?tabs=android

**Comment by jamesdlow** [comment]
I didn't mean a programmatic way to open the browser, I meant that one of the options in the share dialog is to open in browser (along with copy / facebook / twitter).
