### ISSUE TITLE
[Enhancement] Essentials.Share Additional Commands

### ISSUE THREAD

**Issue by jamesdlow** [xamarin/Essentials#842]
## Summary
On the iOS share dialog, an application is able to specify addition icons/commands that the user can click, along with the default options presented by the OS. This allows a single action dialog for sharing or doing another related action that the application might specify. Android may have a similar feature.

It would be great if you could implement passing additional icons/actions to the share dialog as a list to be shown on the share dialog.

**Comment by Redth** [comment]
Can you point to the Apple documentation for this functionality?  

This would have to be supported on Android and likely UWP in some capacity to consider adding this feature.  If you have more information about these platforms as well that would be helpful in considering this.

**Comment by jamesdlow** [comment]
I don't have the Apple documentation, but here is some code that implements it on iOS:
[https://github.com/pegli/TiActionSheetPicker](url)
