### ISSUE TITLE
[Bug] Email.ComposeAsync() can crash on iOS

### ISSUE THREAD

**Issue by tipa** [xamarin/Essentials#843]
### Description
Email.ComposeAsync() can crash on iOS [here ](https://github.com/xamarin/Essentials/blob/2dd6bc0ea61bb6c0a14097e3d4f585baa950100e/Xamarin.Essentials/Email/Email.ios.cs#L79) because `NSUrl.FromString(url)` can return `null`

### Steps to Reproduce
cannot reproduce locally :(

### Expected Behavior
Should throw FeatureNotSupportedException

### Actual Behavior
SIGABRT: Value cannot be null. Parameter name: url

```
UIApplication.OpenUrl (Foundation.NSUrl url, Foundation.NSDictionary options, System.Action`1[T] completion)
UIApplication.OpenUrl (Foundation.NSUrl url, UIKit.UIApplicationOpenUrlOptions options, System.Action`1[T] completion)
Email.ComposeWithUrl (Xamarin.Essentials.EmailMessage message)
Email.ComposeAsync (Xamarin.Essentials.EmailMessage message)
Email.ComposeAsync (System.String subject, System.String body, System.String[] to)
```

**Comment by newky2k** [comment]
Fixed by #848
