### ISSUE TITLE
[Enhancement] Essentials.AppInfo Open phone notifications UI

### ISSUE THREAD

**Issue by mateuswolkmer** [xamarin/Essentials#844]
## Summary

Open the phone's notification page directly from the App.

## API Changes

Currently there is the `AppInfo.ShowSettingsUI()` method where it is possible to open the app settings page on the phone. I'm an Android user, so I don't know if there is a page for notifications on the iOS, but in most apps I use, there is an option to change the app's notification settings, and that opens the OS's notifications page directly.

It is possible to implement it in Android by using the [notifications constant](https://developer.android.com/reference/android/provider/Settings.html#ACTION_APP_NOTIFICATION_SETTINGS) where currently the ApplicationDetailsSettings is called:
https://github.com/xamarin/Essentials/blob/08979e6dffe4ea1363396b3f7d7ea844444162b1/Xamarin.Essentials/AppInfo/AppInfo.android.cs#L43
I'm not sure how to do it in iOS or even if this page exists, but it would be very helpful if this was implemented. Let me know if a pull request (at least for the Android) would help.

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
