### ISSUE TITLE
[BUG] Subsequent SMS Composition Fails

### ISSUE THREAD

**Issue by tmyvett** [xamarin/Essentials#845]
It seems the functionality to compose an SMS message via the Sms.ComposeAsync method only works the first time you try to send a SMS message to the default SMS application. If you try to send another message while the default SMS app is running in the background nothing happens. The user will need to close the default SMS app by removing it from recent apps then try again from your custom app to send the formatted SMS message to the default app.

### Steps to Reproduce

1. Create a basic interface with a button to send a hard coded message to a phone number using the Sms.ComposeAsync() method and send the custom message over to the default SMS app.
2. Go back to your test app and try to send another message.
3. No message is transferred to the default SMS app.

### Expected Behavior
It is assumed that the creation of subsequent messages would be transferred over to the default SMS without having to close the SMS app before sending the custom message.

### Actual Behavior
It is not possible to send subsequent messages from custom code to the default SMS once the app is running in the background or is in "Recent" apps list.

### Basic Information

- Version with issue:v1.2.0
- Last known good version: Unknown
- IDE: Visual Studio 2017 Xamarin Forms
- Platform Target Frameworks: 5.1 to 9.0
  - Android: 9.0 
- Nuget Packages: v1.2.0

**Comment by jamesmontemagno** [comment]
Unable to reproduce this with my Pixel 2 XL and the default Android messages app. We send an intent to they system and the receiving app is the one that needs to respond. There is nothing that Essentials could do if the messaging app doesn't respect it.
