### ISSUE TITLE
[Bug] Lack of support for tvOS

### ISSUE THREAD

**Issue by jpiechowiak** [xamarin/Essentials#846]
### Description
According to [documentation](https://docs.microsoft.com/en-us/xamarin/essentials/platform-feature-support?context=xamarin/tvos), many of Xamarin.Essentials features from tvOS are supported. In reality, in nuget package there is no DLL which targets tvOS. 
When you install this package in app project for tvOS, then .netstandard20 target is actually used.
This version of library actually lacks of support for features like Preferences or SecureStorage.
  
### Steps to Reproduce

1. Create tvOS application 
2. Install Xamarin.Essentials to startup project
3. Use os specific feature - for example Preferences

### Expected Behavior
Preferences feature is working 

### Actual Behavior
Application crashes with error:
"Xamarin.Essentials.NotImplementedInReferenceAssemblyException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation."

### Basic Information

- Version with issue: 1.1, 1.2
- Last known good version: none
- IDE: Visual Studio 2017
- Platform Target Frameworks: tvOS
- Affected Devices: All Apple TV Boxes

Please add proper support to tvOS (dedicated platform target) according to your documentation. We started development of Apple Tv and Xamarin.Essentials is already a crucial part of our SDK.

EDIT:
I see that there is some support for tvOS in 1.3. Is there any release date for 1.3?

**Comment by mattleibow** [comment]
I believe it is out: https://www.nuget.org/packages/Xamarin.Essentials/1.3.0-pre

You should be able to test out tvOS, watchOS and Tizen with that version.

**Comment by jamesmontemagno** [comment]
Thanks for the feedback, I have clarified this in the docs: https://github.com/MicrosoftDocs/xamarin-docs/pull/1943

We just announced version 1.3-pre last week and usually keep the pre-releases there for a few weeks to get feedback.
