### ISSUE TITLE
Android - DeviceDisplay.MainDisplayInfo.Height returns invalid screen dimensions?

### ISSUE THREAD

**Issue by paleicikas** [xamarin/Essentials#852]
Xamarin.Forms (latest), Xamarin.Essentials (latest) 

### Description

Why Resources.DisplayMetrics.HeightPixels and DeviceDisplay.MainDisplayInfo.Height do not match? In my opinion its a bug.

### Steps to Reproduce

<pre>
Debug.Write($"#1 w: {Resources.DisplayMetrics.WidthPixels}, h: {Resources.DisplayMetrics.HeightPixels}, d: {Resources.DisplayMetrics.Density}");
Debug.Write($"#2 w: {DeviceDisplay.MainDisplayInfo.Width}, h: {DeviceDisplay.MainDisplayInfo.Height}, d: {DeviceDisplay.MainDisplayInfo.Density}");
</pre>

Output:

[0:] #1 w: 1080, h: 1794, d: 3
[0:] #2 w: 1080, h: 1920, d: 3

**Comment by Happypig375** [comment]
`Resources.DisplayMetrics.HeightPixels` includes screen space not occupied by the current app.

**Comment by paleicikas** [comment]
I see, but its absolutely useless property

**Comment by Happypig375** [comment]
`DeviceDisplay.MainDisplayInfo.Height` does what it says - the height of the entire phone screen.
Vote for #385 instead.

**Comment by jamesmontemagno** [comment]
This was adjusted in the latest version to be device display, which is now in sync: https://github.com/xamarin/Essentials/issues/745. Issue #385 is the feature request you are asking for. 

There are instances where developers may need app size and others where they want device size. App size is next to implement.
