### ISSUE TITLE
[Bug] OnMainDisplayInfoChanged fires on pages which have been opened but no longer in stack

### ISSUE THREAD

**Issue by BrianJSavage** [xamarin/Essentials#854]
I am using modal navigation, a page is opened with await Navigation.PushModalAsync(new SamplePage)), then dropped from the stack using await PopModalAsync().

After dropping SamplePage, when the device is rotated OnMainDisplayInfoChanged() fires on SamplePage, and other pages in the stack, but not on pages which haven't been in the stack and have OnMainDisplayInfoChanged() in the code behind.

My app is a business to business app which collects data using a selection of several pages. Lets say each has 8 label/input pairs which work fine in portrait mode but need scrolling in landscape. So I split the 8 into 2 blocks of 4 and display the blocks side by side or vertically depending upon DeviceDisplay.MainDisplayInfo.Orientation.

I have placed OnMainDisplayInfoChanged() on each of these pages to detect if the user rotates the device while on that page, and I assumed that it would only fire on the top of stack page, or at least only on pages in the stack, but as I say it fires on pages which "have" been in the stack, but not on pages which "haven't" been in the stack.

Aslo, when device is rotated on SamplePage, OnMainDisplayInfoChanged() fires on that page, then all the OnMainDisplayInfoChanged() pages in the stack fire, including SamplePage again firing, so the processing when SamplePage rotates gets done twice.

Visual Studio 16.1.6
Xamarin forms 4.1.0.555618
Xamarin Essentials 1.1.0

- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
Would need a code sample here to detect what is going on. The event is fired at a device level, not a page level. You will need to unsubscribe from events when you navigate.

**Comment by jamesmontemagno** [comment]
Closing based on feedback above ^
