### ISSUE TITLE
[Bug] EmailAttachments dont work on UWP Desktop if using Outlook

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Essentials#859]
### Description
Using Email Api to attach file on uwp app opens outlook but doesnt attach file

### Steps to Reproduce

```
var message = new EmailMessage
{
      Subject = "Subject",
      Body = "Body"
};

var serializedItem = "Test";
var fn = "File.txt";
var file = Path.Combine(FileSystem.CacheDirectory, fn);
File.WriteAllText(file, serializedItem);

message.Attachments.Add(new EmailAttachment(file));

await Email.ComposeAsync(message).ConfigureAwait(false);
```

### Expected Behavior
Attach file to email

### Actual Behavior
File not attached

### Basic Information

Apparently this is a know issue: https://docs.microsoft.com/en-us/windows/uwp/contacts-and-calendar/sending-email

> Attachments that you add to an email by using the EmailAttachment class will appear only in the Mail app. If users have any other mail program configured as their default mail program, the compose window will appear without the attachment. This is a known issue.

It would be good to mention this somewhere in the wiki and also get a bit more info from microsoft on why this is an issue and if it is going to be fixed at some point in the future

**Comment by JKennedy24** [comment]
This is my workaround so far:

                    //https://github.com/xamarin/Essentials/issues/859
                    if (Device.RuntimePlatform == Device.UWP)
                    {
                        var fn = "CallFile.txt";
                        var file = Path.Combine(FileSystem.CacheDirectory, fn);
                        File.WriteAllText(file, serializedDiaryCall);

                        message.Attachments.Add(new EmailAttachment(file));
                    }
                    else
                    {
                        message.Body = string.Format("serializedDiaryCall\r\n\r\n{0}", message.Body);
                    }

But obviously doesnt work for actual attachments, images, etc

**Comment by jamesmontemagno** [comment]
Thanks for the feedback and I have added this into the documentation: https://github.com/MicrosoftDocs/xamarin-docs/pull/1953
