### ISSUE TITLE
Camera Resolution!

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#864]
Hi,

Is it possible to get the camera resolution using Xamarin Essentials?

Perhaps it's something to look into it..

Thanks,
[Jassim](https://www.zeera.online)

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
