### ISSUE TITLE
AppInfo: CPU, RAM and Disk usage

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#866]
Hi,

It will be great if you add an option to determine how much CPU and RAM an app is consuming at the point of calling the code, for example:

AppInfo.CurrentCPUUsage()
AppInfo.CurrentMemoryUsage()
AppInfo.TotalDiskUsage()

Thanks,
[Jassim](https://www.zeera.online)

**Comment by VladislavAntonyuk** [comment]
I would extend the list with
AppInfo.TotalMemory()
AppInfo.StorageCapacity()

**Comment by jrahma** [comment]
```
AppInfo.StorageTotalCapacity()
AppInfo.StorageAvailableCapacity()

```

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
