### ISSUE TITLE
[Bug] Geolocation.GetLocationAsync() skipped with no error nor exception

### ISSUE THREAD

**Issue by pldeschamps** [xamarin/Essentials#868]
I wrote all the Description, Expected Behavior, Actual Behavior, Etc and clicked on:
"It looks like this is your first time opening an issue in this project!
Be sure to review the contributing guidelines"
When I came back on the Issue editing page, all my work was lost unfortunately...

**Comment by pldeschamps** [comment]
### Description
OK, let's start again.
Geolocation used to work. I changed the code and it doesn't work anymore.
I checked out the former code that still works. I thought it was because I use Task<> here but even if I refactor the code not to be async, it does not work anymore.

A XAML view is binded with a class GeoLocationUpdateViewModel whose constructor is:
```
        public GeoLocationUpdateViewModel()
        {
            Position = Position.BuildPositionAsync().Result;
```
The class Position looks for the device location:
```
        private async Task<Position> InitializeLocationAsync()
        {
            try
            {
                var request = new GeolocationRequest(GeolocationAccuracy.Medium, TimeSpan.FromSeconds(3));
                location = await Geolocation.GetLocationAsync(request);
                if (location != null)
```

### Steps to Reproduce

### Expected Behavior
To get the position, rise an error or catch an exception
### Actual Behavior
if async, the app freezes.
if I refactor the code nto to be async, the line:
```
location = await Geolocation.GetLocationAsync(request);
```
sends back to the caller and location is null.

### Basic Information

- Version with issue: Xamarin.Essentials 1.2.0
- Last known good version:
- IDE: VS 2017
- Platform Target Frameworks: 
 
  - Android: 8.1
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: VS Emulator and Huawei ANE-LX1 (P20 Lite)
The location is authorized

### Screenshots

### Reproduction Link

**Comment by jamesmontemagno** [comment]
This code is freezing your device:  Position = Position.BuildPositionAsync().Result;

Please read through: https://montemagno.com/c-sharp-developers-stop-calling-dot-result/

If you need to do some async work in a constructor (bad practice) you could do:

```csharp
Position.BuildPositionAsync().ContinueWith((t)=>
{
//access t here
});
```

However, you should try to call a method from your on appearing of the page to start querying the location.

**Comment by pldeschamps** [comment]
@jamesmontemagno ,
right, I paid attention not to freeze the app in the Position class and forgot the dot_result in the GeoLocationUpdateViewModel class.
I will rewrite that this week.
Thanks for reading and for your answer.
