### ISSUE TITLE
[Bug] Browser Translucency

### ISSUE THREAD

**Issue by BradleyDHobbs** [xamarin/Essentials#869]
Just wondering if anyone has a workaround for this issue: 

https://github.com/jguertl/SharePlugin/issues/42

In short, the SFSafariViewController is adding a translucent layer therefore making it impossible to match the color to the apps theme color.

I can provide more info and a sample project if needed, however the link above describes the issue perfectly. The ticket was closed but issue is not resolved with the move to Essentials. Could also be an Apple issue but I'm not sure.

Thanks

**Comment by jamesmontemagno** [comment]
From the thread there is actually no solution for this as apple does not expose any API. Unfortunately it is out of our hands :(
