### ISSUE TITLE
[Enhancement] Let set a origin for the share dialog (iPad)

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Essentials#874]
Currently the share window appears at the top left of the app on the iPad. All native share dialogs come up at the control that started the share or at least in the very center of the whole screen. 

It would be great if there is a option to place the share dialog to another origin or at least let it pop in the center instead of the corner pointing to nothing.

**Comment by jamesmontemagno** [comment]
I am open to proposals here on this idea. It is very tricky and need to make it very much known it is an iOS/iPad only feature you know .....

**Comment by jfversluis** [comment]
I think this is possible for a while now, right?

If not: I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
