### ISSUE TITLE
[Bug] Xamarin.Essentials Share not working on iOS

### ISSUE THREAD

**Issue by tekmun** [xamarin/Essentials#875]
### Description

The Share Sheet does not show any icons of other apps on iOS 12.4 and iOS 13 (beta 5)

### Steps to Reproduce

1. Create a Xamarin.Forms app to consume Xamarin.Essentials Share
2. Click on that icon to show Share Sheet
3. 

### Expected Behavior

Share Sheet with icons of other applications

### Actual Behavior

Share Sheet is empty except with three dots icon only

### Basic Information

- Version with issue: iOS 12.4, iOS 13 beta 5
- Last known good version: iOS 12.3
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![Screenshot 2019-08-02 at 6 05 20 pm](https://user-images.githubusercontent.com/5379906/62362806-5f285280-b550-11e9-9dd3-ae30cbe84c00.png)

**Comment by jamesmontemagno** [comment]
Is this on the simulator of physical device?

**Comment by tekmun** [comment]
Physical device.  iPhone XR.

**Comment by tekmun** [comment]
I found the error.  Instead of using Text to contain the message in ShareTextRequest class, I use URL (because the message contains a URL). Changing it to Text field solves this issue.

**Comment by jamesmontemagno** [comment]
Can you share the code that didn't work and what did work so we can take a look at it?

**Comment by tekmun** [comment]
Previously, the code is
`        await Share.RequestAsync(new ShareTextRequest
        {
          Title = title,
          Url = message,
        });`
To solve the bug, I change it to
`        await Share.RequestAsync(new ShareTextRequest
        {
          Title = title,
          Text = message,
        });`
message can be (Genesis 1:1, ESV) xxx,  [Bible Moments] http://www.biblemoments.com.cn

**Comment by jamesmontemagno** [comment]
Interesting... this should work.... @newky2k can you triage this?

**Comment by jamesmontemagno** [comment]
@tekmun do you have a full sample of what "title" and "message" was set to?

was it:

```csharp
var title = "Share";
var message = "(Genesis 1:1, ESV) xxx, [Bible Moments] http://www.biblemoments.com.cn";
```

Just want to get a repro on this.

**Comment by jamesmontemagno** [comment]
You would want to do:

```csharp
var title = "Share";
var message = "(Genesis 1:1, ESV) xxx, [Bible Moments]";
var uri = "http://www.biblemoments.com.cn";
```

and then:

```csharp
await Share.RequestAsync(new ShareTextRequest
            {
                Uri = uri,
                Title = title,
                Text = message
            });
```

Tested this out and works great
