### ISSUE TITLE
Android E-Mail HTML

### ISSUE THREAD

**Issue by merlinsmike** [xamarin/Essentials#880]
Yes, I know HTML in e-mail has a disclaimer and there was a bug where this transpired, but the issue was closed hence a new issue.  Also, one could argue that this is not a bug but a feature request but in any case ...

I would like to use this package but really want a nice HTML e-mail to result, and on Android even Gmail is not really working with HTML with this package. on IOS it seems good, at least for Gmail.

A trivial sample with a bit of color and bold:
mail.Body = "<body
Hi this is Mike! <span style="color: #ff0000;"> In Red! Bold...
";

mail.BodyFormat = EmailBodyFormat.Html;
Sends the e-mail and looks like "Hi this is Mike! In Red! Bold...". No red or bold but close! My rather more complex real HTML comes out as gibberish. Again, works fine on IOS using Gmail.

Note that when I use System.Net.Mail.SmtpClient the HTML is always rendered correctly at the destination e-mail client. In this code I use an alternate view -
// Create HTML view
AlternateView HTMLEmail = AlternateView.CreateAlternateViewFromString(body, null, "text/html");
// add image to html version of email
HTMLEmail.LinkedResources.Add(logo);
mail.AlternateViews.Add(HTMLEmail);

Of course this is quite different approach, but it sure seems like this should be doable, especially since it does work on IOS. Any help will surely be appreciated! And jamesmontemagno, I am using many of your fine packages successfully, and you have been a real asset to the community!

Regards,
Mike

**Comment by jamesmontemagno** [comment]
So, we are calling into the Android APIs directly for the intent system. It is up to the application itself to support what we pass. You can see that this is a common issue: https://stackoverflow.com/questions/2007540/how-to-send-html-email 

Out of our control really of what we can do as we call the necessary API : https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Email/Email.android.cs#L30
