### ISSUE TITLE
Geolocation inside Accelerometer blocks UI

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#881]
Hi,

I am trying to run Geolocation inside Accelerometer but it's blocking my UI and causing app crash after sometimes

Please see the attached sample..

[MyCompass.zip](https://github.com/xamarin/Essentials/files/3479862/MyCompass.zip)

Thanks,
[Jassim](https://maxmon.softnames.com)

**Comment by jamesmontemagno** [comment]
Yes, this code will cause serious issues in your app. You are requesting geolocation perhaps hundreds of times a second.

You can easily check the Cached location as that instantly returns on each platform.

You should ideally check geolocation one time with the API or use a different plugin or the native APIs if you need location callbacks.

You could do something where you get location and handle it with a ContinueWith and then get the location again after that as long as the page is alive. You would also want a cancelation token incase your app has been closed or the user navigates away.

```csharp
            Xamarin.Essentials.Geolocation.GetLocationAsync(new Xamarin.Essentials.GeolocationRequest { DesiredAccuracy = Xamarin.Essentials.GeolocationAccuracy.Low, Timeout = TimeSpan.FromSeconds(10) }).ContinueWith((t) =>
             {
                 if (t.Exception != null)
                 {
                     var results = t.Result; // location
                     
                 }

                 //could get location again now if you needed too
             });
        }
```

Also, be aware that we have built in unit converters for everything: https://docs.microsoft.com/xamarin/essentials/unit-converters?WT.mc_id=docs-github-jamont

**Comment by jrahma** [comment]
I tried that James but it just give 9 latitude and 0 longitude

```
private void Accelerometer_ReadingChanged(object sender, AccelerometerChangedEventArgs e)
{
    Xamarin.Essentials.Geolocation.GetLocationAsync(new Xamarin.Essentials.GeolocationRequest { DesiredAccuracy = Xamarin.Essentials.GeolocationAccuracy.Default, Timeout = TimeSpan.FromSeconds(10) }).ContinueWith((t) =>
    {
        if (t.Exception != null)
        {
            var results = t.Result;

            current_latitude = results.Latitude;
            current_longitude = results.Longitude;
        }
    });

    System.Diagnostics.Debug.WriteLine("current_latitude is " + Convert.ToString(current_latitude));
    System.Diagnostics.Debug.WriteLine("current_longitude is " + Convert.ToString(current_longitude));

    LabelCurrentLatitude.Text = "Latitude: " + Convert.ToString(current_latitude);
    LabelCurrentLongitude.Text = "Longitude: " + Convert.ToString(current_longitude);
}

```

**Comment by jrahma** [comment]
Putting the Location inside the Accelerometer causing the app to start on just blank page.

if I remove the Accelerometer.Start then it will show the page

[TheCompass.zip](https://github.com/xamarin/Essentials/files/3490099/TheCompass.zip)

**Comment by jamesmontemagno** [comment]
You can not put geolocation queries inside of the accelerometer like that. You will lock up the device with so many requests. You should only get location when you need it in your app.

**Comment by jamesmontemagno** [comment]
Run these two things independently not together.

**Comment by jamesmontemagno** [comment]
We also have a compass API: https://docs.microsoft.com/en-us/xamarin/essentials/compass?tabs=android

**Comment by jrahma** [comment]
@jamesmontemagno I tried that but it seems setting custom location is not possible?

[https://forums.xamarin.com/discussion/comment/385733#Comment_385733](https://forums.xamarin.com/discussion/comment/385733#Comment_385733)
