### ISSUE TITLE
[Enhancement] Compass should provide 3D direction

### ISSUE THREAD

**Issue by dotMorten** [xamarin/Essentials#884]
## Summary
The compass currently open provides the direction of the device along the Y axis. Ie the' Up' on the display. But when you for instance go 3D, you need the heading along the Z axis (ie 'through' the lens).

## API Changes

The reading event args needs to provide a 3D Vector Matrix that describes the direction of the compass, compensated for the device orientation.

## Intended Use Case

You can't possible know which axis I'm interested to get the heading for, so the API shouldn't assume I want the direction towards the top of the screen. Granted this is the common scenario, but when you use the device to point towards something (especially in 3D), it needs to be able to specify the heading relative to that direction.

**Comment by jamesmontemagno** [comment]
Does the Orientation sensor give you some of the needed info here: https://docs.microsoft.com/en-us/xamarin/essentials/orientation-sensor ?

**Comment by Lelelo1** [comment]
I am looking for heading for which the user is facing. Going landscape the heading is changed +- 90 degrees - while the used is looking in the same direction.
Looking at the second answer in this SO question: https://stackoverflow.com/questions/13358364/iphone-offset-with-compass-heading-values-between-landscape-right-and-landscape - would solve the problem on iOS I think.

@dotMorten
Isen't what you want the magnetometer maybe? I know there are some sensor fusion libraries as well - But I was able to implmented one of them in my own app though: https://github.com/xioTechnologies/Open-Source-AHRS-With-x-IMU/blob/master/x-IMU%20IMU%20and%20AHRS%20Algorithms/x-IMU%20IMU%20and%20AHRS%20Algorithms/AHRS/MadgwickAHRS.cs

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
