### ISSUE TITLE
Barometer Sensor Speed not used?

### ISSUE THREAD

**Issue by jonasrembratt** [xamarin/Essentials#888]
When starting the `Barometer`, setting the speed doesn't appear to have any effect whatsoever. Whether I pass `Fastest`, `Game`, `UI` or `Default` I get aprox. one update per second.

### Steps to Reproduce

1. Assign `Barometer.Changed` handler capable to measure intervals between updates
2. Start `Barometer` with different `SensorSpeed` values

### Expected Behavior
`Fastest` `SensorSpeed` value should produce (significantly) shorter update intervals than, fore example, `UI`.

### Actual Behavior
No significant difference in sensor update intervals.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS Enterprise v15.9.15
- Platform Target Frameworks: 
  - iOS:  12.4
- Nuget Packages:
  Xamarin.Essentials 1.2
- Affected Devices:
  iPhone

**Comment by jamesmontemagno** [comment]
Yes, this is only used on Android and UWP as they have an API to handle intervals. iOS does not, so it doesn't apply. I will update the documentation to reflect this.
