### ISSUE TITLE
[Bug][help wanted] FileShare not work in android

### ISSUE THREAD

**Issue by 632575987** [xamarin/Essentials#892]
### The code like this:

```csharp

 private async void BtnXlsxFile_Clicked(object sender, EventArgs e)
        {
            try
            {
                FileInfo fi = new FileInfo(CurrXlsx);
                await Share.RequestAsync(new ShareFileRequest
                {
                    Title = fi.Name,
                    File = new ShareFile(CurrXlsx)
                });
            }
            catch (Exception ex)
            {
                await DisplayAlert("error", ex.Message, "I know");
            }

        }

```

the code works well on ios but seems to failed in android. when I clicked the share button and select the destination, the target app cant receive the file, Or the xlsx file is not supported on android?

**Comment by 632575987** [comment]
CurrXlsx has been set to $"{FileSystem.CacheDirectory}/Xlsx/test.xlsx"

**Comment by newky2k** [comment]
@632575987 Can you please provide some details about you project(android version, VS version etc), and a sample project where the issue is demonstratable.  

Thanks

**Comment by jamesmontemagno** [comment]
You have to have apps that support the share protocal. You may want to try the Launcher API to open the file. See: https://github.com/xamarin/Essentials/issues/974
