### ISSUE TITLE
[Enhancment] iOS: Throw Exception when attachment file can't be loaded

### ISSUE THREAD

**Issue by MKuckert** [xamarin/Essentials#896]
### Description

I'd like to catch a well-defined exception containing specific information about the attachment file path in question when the loading of a file attachment for a mail fails.

One could leverage the `NSData.FromFile` overload with a `out NSError` argument to check for a load failure and throw an exception.

### Steps to Reproduce

1. Create a mail with an invalid attachment file name. It's sufficient to use a real file but with `file:///` prefix.
2. Try to send the mail
3. Crash

### Expected Behavior

A well-defined exception is thrown containing at least the attachments file path. It's impossible to resolve the errornous file path when sending multiple attachments.

### Actual Behavior

An `ArgumentNullException` is thrown from `controller.AddAttachmentData(data, attachment.ContentType, attachment.AttachmentName);`stating that `attachment` is null. The real cause is `NSData.FromFile` a line above failing to load the file.

### Basic Information

- Version with issue: 1.3.0
- Last known good version: none
- IDE: Rider
- Platform Target Frameworks: 
  - iOS: 11.0
- Nuget Packages:
- Affected Devices: all

**Comment by bares43** [comment]
This PR https://github.com/xamarin/Essentials/pull/1341 should fix it.
