### ISSUE TITLE
Geolocation.GetLocationAsync() seems to return latest know position if device gps is blocked.

### ISSUE THREAD

**Issue by japero** [xamarin/Essentials#900]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
I have been testing gps lately to get situation where it is lost. I put device on tinfoil bag but for some reaosn Geolocation.GetLocationAsync always returns loaction info. After debugging this I noticed that TimeStamp in response does not change! So it seems to me that it returns GetLastKnowPosition information? Why so? Is there other way of determining that gps is lost?

### Steps to Reproduce

1. Start gps and get loactions. 
2. Put device to tinfoil bag or similar to block gps signal

### Expected Behavior
Gps location should not be reseived and GpsFixLost could be determined by that.
### Actual Behavior
Last known location is received.
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Vs2017 Xamarin
- Platform Target Frameworks: 
  - Android: 9.0
- Nuget Packages:  Xamarin.Essentials 1.3.0
- Affected Devices: Tested on Samsung Galaxy Tab2 and SM-T395

**Comment by jamesmontemagno** [comment]
The system will return what it deems to be the valid location. We simply query the device and see what it says. The timestamp would be best way. There is no current API in Essentials to detect if it is disabled. This would need to be written with some platform specific code. There is an open issue around this already that we are investigating. Closing as this is as expected via the system and out of our control, however noting that the API to determine if GPS is disabled would be an enhancement.

**Comment by japero** [comment]
Thanks for clarifying this issue.
