### ISSUE TITLE
ConnectivityChanged event fired only once 

### ISSUE THREAD

**Issue by alphagamer7** [xamarin/Essentials#901]
### Description
For internet connectivity check,
I have used Connectivity.ConnectivityChanged += Connectivity_ConnectivityChanged; as in the example with relevant Connectivity_ConnectivityChanged function. ConnectivityChanged event only gets fired once, from when I Connect -> Disconnect. When I reconnect back, the event doesn't get fired. Any idea why?
### Steps to Reproduce

1. Run sample application of  Xamarin.Essentials: Connectivity or[ Reachability sample ]((https://github.com/xamarin/ios-samples/tree/master/Reachability)
2. Turn off internet connection -> event gets fired
3. Turn on internet connection -> event doesn't fire anymore

### Expected Behavior
Event should get fired when switching network from online to offline and vice versa.
### Actual Behavior
ConnectivityChanged event only gets fired once
### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS for Mac
- Platform Target Frameworks: 
  - iOS:  12.4
- Nuget Packages: Xamarin.Essentials: Connectivity
- Affected Devices: iPhoneXR Simulator

**Comment by Bronson15** [comment]
I'm having the same issue. Any updates or workarounds?

**Comment by Bronson15** [comment]
#855 states this is a simulator issue. Test on a physical device and it should work fine.
