### ISSUE TITLE
[Bug] CanOpenAsync never completes on UWP

### ISSUE THREAD

**Issue by breyed** [xamarin/Essentials#905]
On UWP, `Launcher.CanOpenAsync("waze://").Result` never returns.

### Basic Information

- Version with issue: 1.2.0
- Platform Target Frameworks:
  - UWP:  18362

**Comment by jamesmontemagno** [comment]
Your issue here is that you are using `.Result`, which will most likely lock your user interface. Checkout this blog for more info: https://devblogs.microsoft.com/xamarin/getting-started-with-async-await/

Works with async/await usage such as:
```csharp
private async void Button_Clicked(object sender, EventArgs e)
        {
            var success = await Launcher.CanOpenAsync("waze://");
        }
```

**Comment by breyed** [comment]
I knew that the blocking call to `Result` was a hack, but since I just use UWP as a debugging platform (faster startup and better breakpoints), I didn't really care about locking up the UI for a moment. I didn't realize that the blocking call could cause a deadlock, however, and so created this issue assuming a problem with the UWP-specific code. Good to know it really does work. Thanks.
