### ISSUE TITLE
Device.UUID

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#906]
Hi,

Please add Device.UUID to Xamarin Essentials.

This can be the real UUID provided by the manufacturer (Apple, Google) or a UUID generated by Xamarin Essentials based on some algorithm

This will make it easier for developer to use this UUID instead of them having to combine several IDs to get a unique ID

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by sparkist97** [comment]
I looked and there you go
https://montemagno.com/unique-device-id-for-mobile-apps/

**Comment by jrahma** [comment]
Then it means it’s possible to add it to Essential with just one line of code

**Comment by jamesmontemagno** [comment]
As we have discussed previously we are not adding this to the API. As outlined in previous requests and in the blog.
