### ISSUE TITLE
[Enhancement] Enable source link support to allow stepping into code

### ISSUE THREAD

**Issue by MagicAndre1981** [xamarin/Essentials#908]
## Summary

Now that [Visual Studio for Mac supports Source link since 8.3 preview like Visual Studio 2017/2019](https://blog.verslu.is/xamarin/xamarin-forms-xamarin/sourcelink-support-xamarin-forms/) to step into code of NuGet packages, Essentials should also [follow Forms and implement SourceLink](https://github.com/xamarin/Xamarin.Forms/pull/6886).

![image](https://user-images.githubusercontent.com/8274816/65234280-8f15c000-dad4-11e9-8eef-919962b6470b.png)

## API Changes

no changes required, only add [this into](https://github.com/dotnet/sourcelink#using-source-link-in-net-projects) into `Directory.Build.props` in root of solution.

## Intended Use Case

you can look how the code works or find bugs faster

**Comment by jamesmontemagno** [comment]
We actually do this already: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Xamarin.Essentials.csproj#L38-L48

**Comment by jamesmontemagno** [comment]
@jfversluis  Can you validate ^^

**Comment by jfversluis** [comment]
Settings look good and with the 1.3.1 version of Essentials and VSMac with SourceLink support, all seems to work just fine!

![image](https://user-images.githubusercontent.com/939291/65372021-9b338600-dc6a-11e9-817a-f7d96f9de6bc.png)

**Comment by MagicAndre1981** [comment]
> Settings look good and with the 1.3.1 version of Essentials 

I [hit this SDK bug](https://github.com/dotnet/sdk/issues/1458) again in VS2017, the PDB was not copied to output and so not loaded during debug and so I was not able to step into the code. After manually loading the PDB I can step into code.

Maybe also [upload PDBs to nuget symbol server](https://github.com/dotnet/sourcelink#using-sourcelink):

```
<IncludeSymbols>true</IncludeSymbols>
<SymbolPackageFormat>snupkg</SymbolPackageFormat>
```

**Comment by jfversluis** [comment]
Add this point there is no support for the `snupkg` format on the Mac side. And this will probably also not be available on Windows when used with iOS or Android whenever that support comes in. So at this time it has no added value to add that as well.

The SDK bug is unfortunately out of our hands.

**Comment by jamesmontemagno** [comment]
Closing out as it works! <3
