### ISSUE TITLE
[Bug] Maps do not work with Waze

### ISSUE THREAD

**Issue by katkusmt** [xamarin/Essentials#909]
### Description
Opening a location with lat/long on the app called "Waze" does not open the location correctly (most likely the signature passed is wrong). The application is very widely used and would be cool to get support for it.
### Steps to Reproduce
1. Create location using lon/lat
2. Create options for walking or driving
3. Select Waze as the app to navigate
### Expected Behavior
Opens the location with an active navigation mode or allowing to click to navigate to the location
### Actual Behavior
Either the Waze app bugs out and shows a grey map or the location is nonsensical and in the middle of the ocean.
### Basic Information
- Version with issue: 1.2.0
- Last known good version: did not find any
- IDE: VS Community for Mac 8.2.5
- Platform Target Frameworks: 
  - Android: 8.0
### Screenshots
https://imgur.com/a/Z6UDjp5 -> first image shows how it appears in Waze, second one is Google Maps (which is fine)
EDIT: coordinates to reproduce the behavior above -> https://imgur.com/a/BMb2vKB

**Comment by jamesmontemagno** [comment]
Looks like Waze does not support the standard geo: tag which is what we use when you use the `Map` API. this is out of our control as this is what the official google docs recommend opening maps. We can't control what each app does or doesn't do.

Here is a good article on how to launch Waze directly and you can use the Launcher API to do it: https://stackoverflow.com/questions/14628644/display-geopoint-in-waze-on-android

**Comment by katkusmt** [comment]
@jamesmontemagno thanks!
