### ISSUE TITLE
[Bug] phone dialer on android dont call extension

### ISSUE THREAD

**Issue by dgarcia4598** [xamarin/Essentials#912]
### Description
Cant call number with extension example "5555555,4" 

### Expected Behavior
when user press send button need to call the main number, after 3 second have to automatically call the extension number 
### Actual Behavior
just call de entire number.. 
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - Android: 7

**Comment by jamesmontemagno** [comment]
Do you have an example of this working on normal Android? Like can you show me an intent that works?

**Comment by manishkungwani** [comment]
@jamesmontemagno the following intent works on native Android:

```
String phonenumber = "03012345,1234,#31#,98765"; // , = pauses
encodedPhonenumber = URLEncoder.encode(phonenumber, "UTF-8");
startActivity(new Intent(Intent.ACTION_CALL, Uri.parse("tel:" + encodedPhonenumber)));
```
Can I try to fix this bug?

**Comment by manishkungwani** [comment]
@dgarcia4598 can you try to use the PhoneDialer as follows:

`PhoneDialer.Open("5555555%2C4")`

And check whether it dials the extension correctly.

If this doesn't work, can you please try:

`Launcher.Open("tel:5555555%2C4")`
