### ISSUE TITLE
[Enhancement] Intercept URL navigation

### ISSUE THREAD

**Issue by mr5z** [xamarin/Essentials#913]
## Summary
Could we have an event listener for every URL navigation it will do once the Browser is launched?
This can be used for the following cases:

- Authentication process
- Payments

The developer would then listen to a certain URL and decide if they want to [dismiss the browser](https://github.com/xamarin/Essentials/issues/763)

## API Changes

I'm actually not sure which APIs are going to get affected.

## Intended Use Case

For example, the developer decided to use this for payments. Here is what I have in mind:

```
Browser.UrlInterceptor += async (sender, e) =>
{
    var targetUri = new Uri("custom_schema://payment_success");
    if (e.Url == targetUri)
    {
        var browser = sender as Browser;
        await browser.DismissAsync();
        var queryString = e.Url.Query;
        // process the query string
        toastService.Show("Payment successful!");
    }
};
```

**Comment by hiraldesai** [comment]
Hi @Redth / @jamesmontemagno - just checking to see if this is going to get attention any time soon. As per my [comment here](https://github.com/xamarin/Essentials/issues/763#issuecomment-569120535), our app was rejected by Apple App Store for using `Launcher` to do OAuth and it's not possible to use `Browser` for OAuth in its current state.

I will use the information to make a decision on whether to write custom code for our app and get it published. If time permits, I might try and see if I can contribute to this feature also.

**Comment by jamesmontemagno** [comment]
I commented on that thread, however we have not decided on any APIs for this yet as enhancement requests are just requests.

**Comment by hiraldesai** [comment]
No worries, thank you for the update James!

**Comment by mattleibow** [comment]
Closing this for a few reasons:
- we can't intercept the new OS browsers
- we can't intercept other browser apps
- auth should be done with WebAuthenticator
