### ISSUE TITLE
[Enhancement] Migrate Support Library dependencies to AndroidX

### ISSUE THREAD

**Issue by heytherewill** [xamarin/Essentials#916]
## Summary
Xamarin AndroidX support is in preview. Xamarin.Essentials only depends on [3 `Xamarin.Support.*` packages](https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Xamarin.Essentials.csproj#L74-L76). A pre-release version that migrates those packages to AndroidX would be very welcome.

## API Changes
None; the changes are abstracted away

## Intended Use Case
Users who want to migrate to AndroidX without using the intermediate migration packages

**Comment by jamesmontemagno** [comment]
It is on our list and we will be aligning it when Xamarin.Forms migrates. This will make it easier on everyone that is upgrading packages.

**Comment by Redth** [comment]
This is done in the upcoming 1.5 release
