### ISSUE TITLE
[Bug] DeviceDisplay.MainDisplayInfo.Density leaks GREF per call.

### ISSUE THREAD

**Issue by SigmaInfini** [xamarin/Essentials#917]
### Description

When I call DeviceDisplay.MainDisplayInfo.Density ,
it leaks 2 GREF per 1 call in Android.
 (1) android.view.WindowManagerImpl.
 (2) java.lang.Class<android.view.WindowManagerImpl>

Finally, it causes GC Inifitiy-loop.
like this:

I/monodroid-gc(12698): 46105 outstanding GREFs. Performing a full GC!
I/art     (12698): Starting a blocking GC Explicit
I/art     (12698): Explicit concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 39% free, 3MB/5MB, paused 926us total 13.562ms
D/Mono    (12698): GC_TAR_BRIDGE bridges 23015 objects 23016 opaque 0 colors 23015 colors-bridged 23015 colors-visible 23015 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 4.13ms tarjan 11.64ms scc-setup 4.43ms gather-xref 0.57ms xref-setup 0.21ms cleanup 3.59ms[0:] GetDensity 22996 times. in 221241 [msec]
D/Mono    (12698): GC_BRIDGE: Complete, was running for 1594.62ms
D/Mono    (12698): GC_MAJOR: (user request) time 41.60ms, stw 42.86ms los size: 0K in use: 0K
D/Mono    (12698): GC_MAJOR_SWEEP: major size: 2416K in use: 1651K

I/monodroid-gc(12698): 46106 outstanding GREFs. Performing a full GC!
I/art     (12698): Starting a blocking GC Explicit
I/art     (12698): Explicit concurrent mark sweep GC freed 17(576B) AllocSpace objects, 0(0B) LOS objects, 39% free, 3MB/5MB, paused 946us total 13.593ms
D/Mono    (12698): GC_TAR_BRIDGE bridges 23016 objects 23017 opaque 0 colors 23016 colors-bridged 23016 colors-visible 23016 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 4.08ms tarjan 11.50ms scc-setup 4.43ms gather-xref 0.53ms xref-setup 0.22ms cleanup 3.58ms
D/Mono    (12698): GC_BRIDGE: Complete, was running for 1596.88ms
D/Mono    (12698): GC_MAJOR: (user request) time 41.28ms, stw 42.17ms los size: 0K in use: 0K
D/Mono    (12698): GC_MAJOR_SWEEP: major size: 2416K in use: 1683K

### Steps to Reproduce

1. Make Xamarin.Forms Project including Android.
2. Add Button , and its click event

```
        private void Button_Clicked(object sender, EventArgs e)
        {
            var sw = Stopwatch.StartNew();

            for (int i=0;i<50000;i++)
            {
                var density = DeviceDisplay.MainDisplayInfo.Density;

                Debug.WriteLine($"GetDensity {i+1} times. " +
                    $"in {sw.ElapsedMilliseconds} [msec]");
            }
        }
```
3. Run,Android in real device.

### Expected Behavior
Just done.

### Actual Behavior
Finally,GC Infinite loop.

debug log :
[0:] GetDensity 1 times. in 32 [msec]
[0:] GetDensity 2 times. in 117 [msec]
[0:] GetDensity 3 times. in 125 [msec]
[0:] GetDensity 4 times. in 139 [msec]
  ......
[0:] GetDensity 22979 times. in 178614 [msec]
[0:] GetDensity 22980 times. in 178623 [msec]
[0:] GetDensity 22981 times. in 178628 [msec]
[0:] GetDensity 22982 times. in 178633 [msec]
[0:] GetDensity 22983 times. in 178638 [msec]
10-07 12:24:57.215 D/Mono    (12698): DllImport attempting to load: '/system/lib/liblog.so'.
10-07 12:24:57.216 D/Mono    (12698): DllImport loaded library '/system/lib/liblog.so'.
10-07 12:24:57.216 D/Mono    (12698): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
10-07 12:24:57.216 D/Mono    (12698): Searching for '__android_log_print'.
10-07 12:24:57.216 D/Mono    (12698): Probing '__android_log_print'.
10-07 12:24:57.216 D/Mono    (12698): Found as '__android_log_print'.
10-07 12:24:57.222 I/monodroid-gc(12698): 46080 outstanding GREFs. Performing a full GC!
10-07 12:24:57.377 I/art     (12698): Starting a blocking GC Explicit
10-07 12:24:57.392 I/art     (12698): Explicit concurrent mark sweep GC freed 8504(298KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 3MB/5MB, paused 928us total 14.495ms
10-07 12:24:58.891 D/Mono    (12698): GC_TAR_BRIDGE bridges 23002 objects 23003 opaque 0 colors 23002 colors-bridged 23002 colors-visible 23002 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 4.92ms tarjan 14.11ms scc-setup 5.69ms gather-xref 0.71ms xref-setup 0.22ms cleanup 3.51ms
10-07 12:24:58.891 D/Mono    (12698): GC_BRIDGE: Complete, was running for 1607.32ms
10-07 12:24:58.891 D/Mono    (12698): GC_MAJOR: (user request) time 57.87ms, stw 59.38ms los size: 0K in use: 0K
10-07 12:24:58.891 D/Mono    (12698): GC_MAJOR_SWEEP: major size: 2416K in use: 1682K
10-07 12:24:58.891 I/monodroid-gc(12698): 46081 outstanding GREFs. Performing a full GC!
10-07 12:24:59.018 I/art     (12698): Starting a blocking GC Explicit
10-07 12:24:59.032 I/art     (12698): Explicit concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 39% free, 3MB/5MB, paused 930us total 13.557ms
10-07 12:25:00.540 D/Mono    (12698): GC_TAR_BRIDGE bridges 23002 objects 23003 opaque 0 colors 23002 colors-bridged 23002 colors-visible 23002 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 4.15ms tarjan 11.64ms scc-setup 4.44ms gather-xref 0.54ms xref-setup 0.19ms cleanup 3.56ms
10-07 12:25:00.540 D/Mono    (12698): GC_BRIDGE: Complete, was running for 1606.47ms
10-07 12:25:00.540 D/Mono    (12698): GC_MAJOR: (user request) time 41.46ms, stw 42.32ms los size: 0K in use: 0K

It seems to me,
Mono detect so much GREF ,
so it try GC to reduce them.
But,GREF is not Reduced.
Thats causes GC Inifite loop,
it makes my app hung.

And,GREF Dump is:
global reference table dump:
   Last 10 entries (of 42324):
     42323: 0x6fb39390 java.lang.Class<android.view.WindowManagerImpl>
     42322: 0x12cd48c8 android.view.WindowManagerImpl
     42321: 0x6fb39390 java.lang.Class<android.view.WindowManagerImpl>
     42320: 0x12cd48c8 android.view.WindowManagerImpl
     42319: 0x6fb39390 java.lang.Class<android.view.WindowManagerImpl>
     42318: 0x12cd48c8 android.view.WindowManagerImpl
     42317: 0x6fb39390 java.lang.Class<android.view.WindowManagerImpl>
     42316: 0x12cd48c8 android.view.WindowManagerImpl
     42315: 0x6fb39390 java.lang.Class<android.view.WindowManagerImpl>
     42314: 0x12cd48c8 android.view.WindowManagerImpl
   Summary:
     23363 of java.lang.Class (270 unique instances)
     18743 of android.view.WindowManagerImpl (1 unique instances)
       140 of java.nio.DirectByteBuffer (137 unique instances)
        17 of java.lang.ref.WeakReference (17 unique instances)
         4 of dalvik.system.PathClassLoader (2 unique instances)
         3 of java.lang.String (2 unique instances)
         2 of android.opengl.EGLSurface (1 unique instances)
         2 of android.opengl.EGLContext (1 unique instances)
         2 of android.opengl.EGLDisplay (1 unique instances)
         2 of java.lang.ThreadGroup (2 unique instances)
         2 of android.content.res.Resources (2 unique instances)
         2 of android.content.ContentProvider$Transport (2 unique instances)
         2 of android.app.LoadedApk$ReceiverDispatcher$InnerReceiver (2 unique instances)
         2 of android.content.res.ColorStateList (2 unique instances)
         1 of md51558244f76c53b6aeda52c8a337f2c37.PowerSaveModeBroadcastReceiver
         1 of mono.android.animation.ValueAnimator_AnimatorUpdateListenerImplementor
         1 of md51558244f76c53b6aeda52c8a337f2c37.VisualElementTracker_AttachTracker

So,It seems to me that,
DeviceDisplay.MainDisplayInfo.Density leak 2 GREF.
1st ,  android.view.WindowManagerImpl.
2nd, java.lang.Class<android.view.WindowManagerImpl>

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android: Min 5.0 , Target 9.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
.NET Standard.Library 2.0.3
Xamarin.Essentials 1.1.0
Xamarin.Forums 4.0.0.425677

- Affected Devices:
Tekwin A10B (Android 7.1 - API 25)

**Comment by SigmaInfini** [comment]
[20191007_density_bug.txt](https://github.com/xamarin/Essentials/files/3695497/20191007_density_bug.txt)

This is the full debug log.

**Comment by jamesmontemagno** [comment]
Was able to reproduce on emulator after about 15K calls. Pretty edge case, but investigating what is going on here.
