### ISSUE TITLE
[Enhancement] TimeZoneChangedEvent

### ISSUE THREAD

**Issue by johnwmcintosh** [xamarin/Essentials#920]
## Summary

Detecting when a running Xamarin app crosses into a new timezone is too complicated. I propose an cross-platform Essential that invokes an event (much like the Connectivity api) that we can handle.

## API Changes

In order to facilitate proper date handling, a new event is added to the Essentials platform that fires whenever the timezone changes on any platform.

A consumer would only see the new event that can be implemented. The handler would give us a place to call TimeZoneInfo.ClearCachedData()

This would close the gap exposed by https://docs.microsoft.com/en-us/dotnet/api/system.timezone.currenttimezone?view=netstandard-2.1#notes-to-callers

"If the system's local time zone subsequently changes, the CurrentTimeZone property _does not reflect this change_. If you need to handle time zone changes while your application is running, use the TimeZoneInfo class and call its ClearCachedData() method."

## Intended Use Case

My app displays data that is managed in SharePoint. I use the SharePoint API. Some fields are datetimes, which the API gives as Utc formatted as string in the XML. 

My SharePoint resides in Pacific Time and the customers want to see the date times as Pacific Time regardless of which timezone they are in. The app also can download files from SharePoint. The file's timestamp gets set to its SharePoint's item timestamp (in PT) for business reasons.

Since the app is for mobile devices, the mobile device may cross timezones while the app is open. The problem is that, when interrogating the file's timestamp, .NET automatically translates it to the Local time. This will be based on the timezone at the time the app was started, not the timezone we might find ourselves in since nothing in Xamarin let's me know it changed.

**Comment by Mrnikbobjeff** [comment]
[UWP](https://docs.microsoft.com/de-de/windows/uwp/launch-resume/use-a-maintenance-trigger)
[iOS](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622992-applicationsignificanttimechange?language=objc)
[Android](https://stackoverflow.com/questions/31398324/is-there-an-android-event-listener-for-change-in-the-timezone-of-the-device)
[Tizen](https://developer.tizen.org/ko/development/guides/web-application/device-settings-and-systems/time-and-date-management?langswitch=ko)

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.
