### ISSUE TITLE
[Enhancement] DeviceInfo -> Detect Device Theme (Dark Mode)

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#923]
## Summary
Provide ability to detect the mode/theme of the device. Dark Mode / Light Mode.

## API Changes

```csharp
public enum UserInterfaceStyle
{
   Unknown,
   Default,
   Dark,
   Light
}
```

Add to DeviceInfo:

```csharp
public UserInterfaceStyle UserInterfaceStyle{ get; }
```

Implementation:
* Android: https://github.com/jamesmontemagno/Hanselman.Forms/blob/themes/src/Android/Helpers/Environment.cs
* iOS: https://github.com/jamesmontemagno/Hanselman.Forms/blob/themes/src/iOS/Helpers/Environment.cs
* UWP: https://stackoverflow.com/questions/38734615/how-can-i-detect-windows-10-light-dark-mode

I do not think it is smart that we detect changes as that is at an app level IMHO.

## Intended Use Case
Enable easier theming of light/dark themes of apps.

**Comment by manishkungwani** [comment]
@jamesmontemagno can I take this up?

**Comment by jamesmontemagno** [comment]
It is already in progress @manishkungwani

**Comment by huangjinshe** [comment]
Why did you close it? We really need this when app startup, then we could use the right theme.

**Comment by DamianMehers** [comment]
> Why did you close it? We really need this when app startup, then we could use the right theme.

It looks like it was merged and available as [AppInfo. PlatformRequestedTheme](https://github.com/xamarin/Essentials/blob/develop/Xamarin.Essentials/AppInfo/AppTheme.shared.cs)

**Comment by huangjinshe** [comment]
@DamianMehers  Thanks.

**Comment by jamesmontemagno** [comment]
Yes, there is a bug on iOS currently that will be fixed in 1.5.2 that you have to call it OnStart/OnResume and not in the constructor

**Comment by huangjinshe** [comment]
@jamesmontemagno Thank you for let me know, but do you mean I need to use it in OnStart/OnResume before the bug fixed(after that I can use it anywhere)? or you mean I need to use it always in OnStart/OnResume?

**Comment by jamesmontemagno** [comment]
You can always use it there. Just right now on iOS it won't work in your app constructor.

**Comment by huangjinshe** [comment]
@jamesmontemagno Sure, Thanks again.
