### ISSUE TITLE
[Bug] Could not find any available provisioning profiles

### ISSUE THREAD

**Issue by eincioch** [xamarin/Essentials#934]
### Description
I am using xamarin / Essentials "SecureStorage", and trying to emulate my project force me to a Provisioning, and I only need to debug on iOS.

### Steps to Reproduce

1. Create a Xamarin.Forms project
2. Add Xamarin Essentials, with SecureStorage
3. Ask me for my application to have Provisioning

### Expected Behavior
It should run smoothly, and without provisioning

### Actual Behavior
I think that for a debugging development environment you should not ask that the project be provisioned.

### Basic Information

- Version with issue: Xamarin.Essentials v.1.3.1
- Last known good version: It doesn't work with any version, so far
- IDE: Visual Studio Enterprise 2019
  - iOS:  11.1 (13)

### Screenshots
![image](https://user-images.githubusercontent.com/12565944/66845286-60ed9980-ef35-11e9-86cd-59da4686202a.png)

**Comment by jbravobr** [comment]
My guess is that you need to do this:

[image: Screen Shot 2019-10-15 at 12.41.55.png]

**Comment by mattleibow** [comment]
@jbravobr I think the image is missing from the comment.

**Comment by jamesmontemagno** [comment]
If you are using a simulator please look at: https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?context=xamarin%2Fxamarin-forms&tabs=ios

**Comment by jamesmontemagno** [comment]
This error seems to just be about a provisioning profile for your app and not anything with Essentials.

**Comment by eincioch** [comment]
Hi James Montemagno, although this is true, I attach documentation!
It should be optional when provisioning is being developed (have paid iOS account).
In Android Studio, I have no problems running my app, I think it should be the same, with iOS.

----------------------------------------------------------------------------------------------------------
https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/free-provisioning?tabs=macos

 Important

Automatic provisioning allows Visual Studio for Mac or Visual Studio 2019 to automatically set up a device for developer testing. However, automatic provisioning is not compatible with free provisioning. In order to use automatic provisioning, you must have a paid Apple Developer Program account.

**Comment by VladislavAntonyuk** [comment]
Create application in XCode with the same I’d as your app. run it on target device. Then switch to visual studio and run your app

**Comment by jamesmontemagno** [comment]
There is nothing here that we can do as this is a restriction of the OS and handled via Apple.

**Comment by eincioch** [comment]
It only remains to pay Apple the $ 99 annually. Is this correct?.

**Comment by VladislavAntonyuk** [comment]
If you run on simulator or your own device you do not need to pay ( the app will work 7 days, after that you have to reinstall it)

**Comment by jamesmontemagno** [comment]
You can run it with the free cert from apple like @VladislavAntonyuk.

See: https://docs.microsoft.com/xamarin/ios/get-started/installation/device-provisioning/free-provisioning?tabs=macos&amp;WT.mc_id=docs-github-jamont
