### ISSUE TITLE
[Enhancement] Xamarin.Essentials: Device Information add device id

### ISSUE THREAD

**Issue by eincioch** [xamarin/Essentials#938]
## Summary
It will be possible to add, within the Device Information if unique device id.

## API changes

**Add -> This is what I would add.**

// Id Device (Physical)
var id_device = DeviceInfo.**IdDeviceType**;

## Intended use case
I need to obtain the unique ID of the IMEI device, to validate that only one digital token is activated on a single device for the user.

**Comment by jamesmontemagno** [comment]
We do not plan on implementing this: https://github.com/xamarin/Essentials/issues/61

**Comment by eincioch** [comment]
You could contemplate adding, not only the serial number, but also how to obtain the IMEI of a device.

**Comment by jamesmontemagno** [comment]
We decided against this information and to leave it up to developers as not every device has an IMEI number. It is very tricky because everyone wants something similar and consistent and if we can't provide that then we don't want to add it in.
