### ISSUE TITLE
[Bug] Validate ColorConverters and others don't get linked out

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Essentials#939]
https://twitter.com/Jarenaut/status/1184839759690174464

**Comment by Jarenaut** [comment]
Hi,  i tried with api 27 and api 28 and just failed with essentials ColorConverters.  Regards

**Comment by jamesmontemagno** [comment]
@Jarenaut can you share a snippet of code so I can try to debug it.

**Comment by jamesmontemagno** [comment]
Unable to validate here after adding samples, working well.
