### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by yshteinm** [xamarin/Essentials#940]
I know about FFImageLoading but it would be great if there was official support for SVG (or other vector format) in Essentials. I would like to see support in Controls (like image button), background images (like inside Image View), if possible ToolBar, etc.

**Comment by jamesmontemagno** [comment]
Thanks for the recommendation, however we have decided that Essentials will focus on core APIs and not user interface. Xamarin.Forms would be the best place for this or use of SkiaSharp which already has SVG support.
