### ISSUE TITLE
Essentials'' BackgroudingWork

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#941]
Hi,

I know each platform has its own backgrounding methodology but same thing applies to almost all features Xamarin Essentials introduced

That is why I think it will be great if Xamarin Essentials will also add a Xamarin Forms' BackgroudingWork to execute backgrouding tasks with/without interval

For example:

`BackgroudingWork.Start("theID", Every.30Minutes, Start.Immediatelly, DoWork());`

Which should run the background task even if the app is in background or killed

**Comment by jamesmontemagno** [comment]
Duplicate of: https://github.com/xamarin/Essentials/issues/409

Would recommend looking into Shiny: https://github.com/shinyorg/shiny
