### ISSUE TITLE
[Bug] Xamarin Essential Share in iOS 13

### ISSUE THREAD

**Issue by tnaznen** [xamarin/Essentials#942]
### Code
await Share.RequestAsync(new ShareTextRequest
                {
                    Uri = "https://www.google.com",
                    Title ="Share the link"
                });

### Screenshots
![image](https://user-images.githubusercontent.com/28263359/67118474-f47fce00-f1b2-11e9-842c-a9d86aaf0f84.png)

**Comment by Mikilll94** [comment]
I also have this bug.

**Comment by jamesmontemagno** [comment]
It looks like this is a core issue with iOS itself as native code also seems to yield the same result: https://stackoverflow.com/questions/59452071/how-to-share-text-and-url-to-reminders-on-ios-13

I did validate that it does not work, however this looks to be an Apple bug.

An option here should be to have a way to exclude certain apps from the share sheet.

**Comment by jamesmontemagno** [comment]
Will close via: https://github.com/xamarin/Essentials/issues/1044

**Comment by jamesmontemagno** [comment]
I can validate that in iOS 12 it works in reminders just fine.

**Comment by g4mb10r** [comment]
@jamesmontemagno This issue is back with the latest Xamarin.Essentials.
