### ISSUE TITLE
Launcher.TryOpenAsync on Android 10 not open APP

### ISSUE THREAD

**Issue by wuhuangjia** [xamarin/Essentials#945]
When using Launcher.TryOpenAsync in Xamarin.Forms on Android 10, return True, but not launched APP

- Version with issue: Essentials 1.3.1
- IDE: VS 4 Mac
- Android: 10

**Comment by manishkungwani** [comment]
@wuhuangjia can you share the link that you tried to open. Also, what app were you expecting to be opened by the launcher?

**Comment by manishkungwani** [comment]
@wuhuangjia please see the attached video, the link seems to work fine for me. Using Android 10 on One Plus 7T.

**Comment by wuhuangjia** [comment]
@manishkungwani thank you very much, we will close this issue, and will figure out at our side, and if have any luck, we update this thread, thank you again
