### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by akoranteng** [xamarin/Essentials#947]
### Steps to Reproduce

1. Attempted to open Xamarin Essentials project(Latest version)
2. Performed Rebuild operation on solution. Got errors, see attached
3.  Performed Rebuild operation on library project. Got errors, see attached
![Screen Shot 2019-10-24_ErrorforlibraryProject](https://user-images.githubusercontent.com/13998322/67474161-041f6c80-f622-11e9-888a-bda2636aa24c.png)
![Screen Shot 2019-10-24_errorforAndroidProject](https://user-images.githubusercontent.com/13998322/67474177-097cb700-f622-11e9-8d4e-827f1c1e56df.png)

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
Give this branch a try: https://github.com/xamarin/Essentials/tree/feature/vsm-mt

**Comment by akoranteng** [comment]
I gave the above link a try and it works just as expected. The landing page is very intuitive with the graphic attached to each menu item. Just to make life easier for other developers visiting the link stated in the documentation link: Can we update to point to this new link for the branch you stated. The documentation link points to branch.I have attached the link stated in the documentation for your reference.
![Screen Shot 2019-10-27_Currentlink_XamarinDocumentation](https://user-images.githubusercontent.com/13998322/67636312-bc107c00-f8a5-11e9-82aa-798114c26f0b.png)

**Comment by jamesmontemagno** [comment]
Closing out as it is now in master. thanks for the feedback

**Comment by akoranteng** [comment]
James,

I am glad this bug has been solved. I will keep digging through your Xamarin Essentials solution and finding it of immense benefit to the Xamarin developer community. I have following it starting with your Xamarin plugin demo
project days and have seen it really evolve. I have been following your Xamarin show series and your other podcast series and one of my dreams is to be on your show someday as I develop my Xamarin coding skills. I am also thinking of writing an application where users can perform a search feature for topics for your Xamarin show series. I live in Boston so we may meet at a User group someday when you are in town.

Regards

Alex Koranteng
________________________________
