### ISSUE TITLE
[Bug] ITMS-90809: Deprecated API Usage: UIWebView 

### ISSUE THREAD

**Issue by HTUlv412** [xamarin/Essentials#948]
### Description
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more 
### Steps to Reproduce

1. Publish any app with your library into apple store.

### Expected Behavior
App  being approved.
### Actual Behavior
App get rejected.
### Basic Information

- Version with issue: Current
- Last known good version: N/A
- IDE: N/A
- Platform Target Frameworks: 
  - iOS:  13.1
  - Android: N/A
  - UWP:  N/A
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
See: https://github.com/xamarin/Xamarin.Forms/issues/7323
