### ISSUE TITLE
[Bug] Android FileShare to Viber has unexpected behavior but works fine when sending to Skype or Telegram

### ISSUE THREAD

**Issue by IgorKravchenko10** [xamarin/Essentials#951]
Hi! I am using FileShare as described in [documentation](https://docs.microsoft.com/ru-ru/xamarin/essentials/share?tabs=android#files)
I have a strange behavior when sharing image to Viber. When I share several different images to Viber it shows first image. Perhaps it is not Essentials problem but other applications shares images without problems. In Skype and Telegram all images show fine. I have recorded video with sharing to Viber and Skype.
https://www.youtube.com/watch?v=3eFR1nJuAAY - Viber
https://www.youtube.com/watch?v=hTBYscpL-vc - Skype

### Steps to Reproduce

1. Share first image to Viber.
2. Share second image to Viber.
3. Result: all images are same.

- Version with issue: Essentials 1.3.1. Forms 4.3.0.908675
- IDE: Visual Studio 2019 Preview
- Platform Target Frameworks: 
  - Android: 7.1 and 9 
- Affected Devices: Samsung Galaxy S8+, Nexus 6

**Comment by jamesmontemagno** [comment]
This would be a bug against Viber unfortunately as we just follow normal share intent practices.
