### ISSUE TITLE
[Enhancement] Add Stream overloads to Launcher and Share APIs

### ISSUE THREAD

**Issue by slang25** [xamarin/Essentials#955]
## Summary
I'd like to be able to take a file downloaded with a `HttpClient`, and pass it to the launcher or share APIs, and have them just "do the right thing".

## Intended Use Case
Specifically on Android, where supported I'd like it to persist the stream and use FileProvider to securely present it.

**Comment by mattleibow** [comment]
This is not possible on many platforms, especially android. The share operation is a request to the OS and it must be a file path/uri. There is no way to pass actual objects since the other app is in another process.
