### ISSUE TITLE
[Enhancement] Add a Barcode Reader.

### ISSUE THREAD

**Issue by volkan-akkus-tr** [xamarin/Essentials#956]
## Summary
Barcode reader would be extremely valuable. There are - partial - solutions. Support is an issue.

## Intended Use Case
Xamarin Forms is very well suited for LOB applications. Barcode reader is a very useful and missing part.

**Comment by MitchBomcanhao** [comment]
Would the opposite also be true, ie, being able to generate a barcode in app?

**Comment by Happypig375** [comment]
Will this be more suitable for Xamarin.Essentials instead?

**Comment by rdeveen** [comment]
Not only Barcode but also QR-Code reader would be fine.

**Comment by domagojmedo** [comment]
Would this work by integrating zxing or writing new solution from scratch? I have no idea how complex reading barcode/QR code is

**Comment by RhomGit** [comment]
Ref: https://github.com/xamarin/Xamarin.Forms/issues/7934

**Comment by mattleibow** [comment]
This feature has quite a nice implementation with ZXing: https://github.com/Redth/ZXing.Net.Mobile
You can check out the samples on how to integrate this.
