### ISSUE TITLE
[Enhancement] Add ColorConverter for complimentary colors

### ISSUE THREAD

**Issue by mrlacey** [xamarin/Essentials#957]
## Summary
Add a way to get a [complimentary color](https://en.wikipedia.org/wiki/Complementary_colors) for any color to the `ColorConverters` class.

A complementary color is a color on the opposite side of the color wheel. (e.g. Red-Green, Purple-Yellow, etc.)
![color wheel](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS62FL4Op09iw8vHN3YWDWVW2PpqTvd9MPbzTcv5btrlpRaWINrkg&s)

Having access to such functionality is useful when you need more than just a single color but are working with a user or system provided color (such as an accent color). I've done this in a lot of apps in the past and wondered if it would be useful to others and be a good fit for this library.

## API Changes

This would require a single addition to the `ColorConverters` class.

The signature would look like this to match the existing conventions of the class.

```
public static Color GetCompliment(Color original) {}
```

## Intended Use Case
There is no single color you can combine with an existing color and ensure it works well (is clearly visible) on both a white and black (light and dark) background. 
If you want to use a user-defined color in the UI and then want to add a secondary color (for emphasis or just to add some visual interest) then you need the selected colors compliment.

Hopefully adding this functionality to the essentials library will also encourage developers to think more about how they use colors in their apps and consider using more than just a single one.

**Comment by Redth** [comment]
@mrlacey do you have an example of the calculation that is required to find the compliment?

**Comment by mrlacey** [comment]
> @mrlacey do you have an example of the calculation that is required to find the compliment?

It should only require moving the hue value +/- 180.
I went to test this with the `ConvertToHsl` and `FromHsl` methods already in that class but I think I've found bugs in their implementations. Investigating further now.

**Comment by mrlacey** [comment]
Not a bug, just undocumented methods not behaving as I expected.

@Redth the logic looks something like this ;)

```csharp
    public static Color GetCompliment(Color original)
    {
        // Divide each byte value by 255 as method expects a value between 0 and 1.
        ConvertToHsl(original.R / 255f, original.G / 255f, original.B / 255f, out var h, out var s, out var l);

        // Multiply by 360 as `ConvertToHsl` specifies it as a value between 0 and 1.
        h *= 360;

        // Add 180 (degrees) to get to the other side of the circle.
        h += 180;

        // Ensure still within the bounds of a circle.
        h %= 360;

        // multiply by 100 as `ConvertToHsl` specifies them as values between 0 and 1.
        return FromHsl(h, s * 100, l * 100);
    }
```

Happy to raise a PR if this looks like a useful addition, and I even have tests.

**Comment by Redth** [comment]
@mrlacey yeah a PR would be appreciated!  These are such small / simple methods that they are worth including since they don't add much bulk even though they might not be commonly used.  In any case the linker can take care of unused methods in these cases, so I think including it is definitely worth it!
