### ISSUE TITLE
[Bug] Upgrade to iOS 13 causes some preferences to be missing

### ISSUE THREAD

**Issue by ericvandamme** [xamarin/Essentials#961]
### Description

Upgrade to iOS 13 causes some preferences to be removed. Code works fine if reinstalled on iOS 13.

### Steps to Reproduce

1.  Configure app in iOS 12.x
2.  Upgrade to iOS 13
3.  Some preferences are missing (but not all)

### Expected Behavior

Preferences that were configured properly in iOS 12 would remain after the upgrade to iOS 13.

### Actual Behavior

Some preferences are confirmed removed, regardless if they are in SecureStorage or regular preferences.

### Basic Information

- Version with issue: 1.3.0
- Last known good version: Unknown
- IDE: Visual Studio 2019
- Platform Target Frameworks:
  - iOS:  Target 8.0, Built with Xcode 11
- Nuget Packages: Xamarin.Essentials (1.3.0), Xamarin.Forms (4.2.0.848062)
- Affected Devices:
  - iOS 13 (all devices)

### Testing Status

Unfortunately, once upgraded to iOS 13, I cannot revert to 12 to retest.

### Sample Code

```
const string BackupGuidKey = "backupkey";
const string BackupGuidDefualt = null;
public static Guid? BackupGuid {
   get {
      if (Guid.TryParse(Preferences.Get(BackupGuidKey, BackupGuidDefualt), out Guid guid))
         return guid;
      else return null;
   }
   set {
      if (value.HasValue)
         Preferences.Set(BackupGuidKey, value.GetValueOrDefault().ToString());
      else if (Preferences.ContainsKey(BackupGuidKey))
         Preferences.Remove(BackupGuidKey);
      }
}
```

**Comment by naweed** [comment]
Hi,

I am facing a similar issue. In my iOS app, after upgrading to v13, some of the preferences are getting lost. Any update on when this can be fixed? Or if I can downgrade to a lower version for the time being?

Thanks
Naweed

**Comment by ericvandamme** [comment]
> Hi,
> 
> I am facing a similar issue. In my iOS app, after upgrading to v13, some of the preferences are getting lost. Any update on when this can be fixed? Or if I can downgrade to a lower version for the time being?
> 
> Thanks
> Naweed

I am just happy this isn't just me.

Just curious, but the settings I find impacted tend to be ones that are new to the app. Older preferences (like username/password) see to be unaffected in general. It seems to be preferences introduced in the past 4 months.

**Comment by naweed** [comment]
Yes, it is only happening to new users of the app. Older users are fine.

And I suspect that this is not an issue with Xamarin Essentials. I am facing the same issue in Xam.Plugins.Settings (3.1.1).

Looks like Apple broke something :)

Regards
Naweed

**Comment by jamesmontemagno** [comment]
From what i have seen the API hasn't changed or been modified at all. There are cases where sometimes things go missing (I have not experienced this in 8 years of development), but there are some blogs otu there: https://damir.me/the-mystery-of-the-disappearing-nsuserdefaults-keys/ , however this seems to be when things are accessed from under lock screen or background. 

I mean there is is not much we can do here at all except to have you file a radar with apple as it would be a bug in their system. So will close out.
