### ISSUE TITLE
[Enhancement] Share feature throws different exceptions across platforms.

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#963]
### Description
The only platform to validate share request data is Tizen, all others will throw nullreferenceexceptions if passed null via invalid constructed sharerequests. We should validate the share request equally across all platforms

### Expected Behavior
All platforms throw ArgumentNullException
### Actual Behavior
NullReferenceException on Android in FileProvider
### Basic Information

- Version with issue: 1.3.1
- Last known good version: None

**Comment by RodgerLeblanc** [comment]
I'll work on this one.

**Comment by mattleibow** [comment]
Thanks @RodgerLeblanc!

**Comment by RodgerLeblanc** [comment]
Can't tell you why, but this repo is ineligible for Hacktoberfest.

![image](https://user-images.githubusercontent.com/6235690/95026212-bf87b800-065d-11eb-93cb-c37628b159b8.png)

This repo has some issue with the `hacktoberfest` label, so you might want to fix this.
You probably can add the `hacktoberfest` tag to the repo to make it eligible manually, or get in touch with Hacktoberfest team to understand why this repo was marked as ineligible.

**Comment by mattleibow** [comment]
@RodgerLeblanc  I added the tag. I see the rules are still changing. Thanks to the "nice" folks in the community.
