### ISSUE TITLE
Update Map.ios to not use deprecated functions

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#964]
### Description

`GLGeocoder.GeocodeAddressAsync` has been superceded by the new and improved GeocodeAdress, which takes user locale and region into consideration to improve suggestions. It has been officially deprecated but has no deprecated attribute, it is only visible in the docs/method comments.

**Comment by jamesmontemagno** [comment]
So, we are using https://developer.apple.com/documentation/corelocation/clgeocoder/1423509-geocodeaddressstring which is not deprecated currently. There is the ability to use a Region or Locale to. 

Yes, there is a way of passing in a Region and Locale, but a region would have to be specified as a circular region and the locale is specific to iOS locale settings. So I don't think that it is worth investing unless they actually deprecate this method as they wouldn't apply to any of the other platforms.

**Comment by Mrnikbobjeff** [comment]
I believe you are incorrect, we use [this](https://docs.microsoft.com/en-us/dotnet/api/corelocation.clgeocoder.geocodeaddressasync?view=xamarin-ios-sdk-12#CoreLocation_CLGeocoder_GeocodeAddressAsync_Foundation_NSDictionary_) overload, taking a NSDictionary and not a string. Take a look at our usage [here](https://github.com/xamarin/Essentials/blob/c5e0e873d3a3f94c2781164683a46ea61dc573ef/Xamarin.Essentials/Map/Map.ios.watchos.cs#L50). The first link clearly states that the overload we are using is deprecated, unless I am missing something

**Comment by jamesmontemagno** [comment]
Oh, yes I thought you were talking about: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Geocoding/Geocoding.ios.tvos.watchos.cs#L23

**Comment by jfversluis** [comment]
Seems like this has been addressed long ago, yay us!
