### ISSUE TITLE
[Enhancement] Redundant allocation in TextToSpeech.Android

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#965]
### Description
The c# spec allows anonymous functions delegates to be cached, method group conversions may not be cached though and have to be allocated delegate instances every time. We have several instances in Xamarin.Essentials where we use method group conversions for brevity allowing them to allocate unnecessarily.

**Comment by mattleibow** [comment]
Duplicate of https://github.com/xamarin/Essentials/issues/1029
