### ISSUE TITLE
[Bug] Intialization Type Preferences Location

### ISSUE THREAD

**Issue by alaskanrogue** [xamarin/Essentials#967]
### Description
Having deployed to a device for debugging, subsequent debugging sessions utilize previously set preferences. Starting the deployed instance directly on same device, the previously set preferences are not utilized.

### Steps to Reproduce

1. Create code to set/get a preference with success indicators on a device
2. Run and set preference if not already present in VS debug mode
3. Re-run in VS debug mode and get preference; confirm if original value
4. Run directly on device; confirm if originally set value 

### Expected Behavior
Original value confirmed

### Actual Behavior
Original value not confirmed

### Basic Information

- Version with issue: 1.3.1
- Last known good version: NA

- IDE: VS2019 Preview 2

- Platform Target Frameworks: 
  - Android:  28.0.3

  Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Nokia 5

**Comment by jamesmontemagno** [comment]
Are you saying that when you debug the app it is working great. But then you uninstall and install a release version and it isn't using your debug preferences?

This would be as expected.

**Comment by alaskanrogue** [comment]
Debugging leaves an executable on the device (phone) which is what I am executing from the menu icon.  I am not uninstalling and installing a release version or even debug version, e.g. manual uninstall; I am aware of that expectation.

**Comment by jamesmontemagno** [comment]
So is your steps:

1.) Launch the app in debug
2.) Set a preference
3.) stop debugging
4.) Launch the app in debug
5.) check the preference again

This will work just fine if you are using standard debug setting and have it preserver your settings between launch:
![image](https://user-images.githubusercontent.com/1676321/71303338-2e648080-236c-11ea-9643-25ad47d32878.png)

Watch to see if the app get uninstalled. I am unable to reproduce this locally with the sample app and is working fine.

**Comment by alaskanrogue** [comment]
Upon initial debug deployment using the IDE, the app sets the preference. On subsequent debugging with the IDE with the app is able to retrieve preference. However, as the app is deployed to the device, it is executable without the IDE from the device; it is the same deployed binary. That executing instance however doesn't see the preference. I can determine that because the preference is the parameter to a switch in the UI path followed, e.g. setup vs setup completed.

**Comment by jamesmontemagno** [comment]
So, I followed your steps as far as I can see: https://www.youtube.com/watch?v=TkjoWyxyBvo&feature=youtu.be if you record a video or walk step by step I can try to reproduce, but it is working alright here.

**Comment by alaskanrogue** [comment]
I have the same results with the emulator which I typically don't use; I use a Nokia 5 directly on which the issue seen. Since the filing of the issue, I have continued development but am dealing now with another issue of the executable not fully loading when started from the phones menu. That issue may be related to similar random startup issue when connecting to Firebase when debugging from the IDE. Let's put this on hold until I solve that issue and can film the phone itself for you.

**Comment by mattleibow** [comment]
@alaskanrogue is this still an issue? Were you able to determine the reason for the preferences getting lost?
