### ISSUE TITLE
[Bug] In the UnitConverters class, the 2 methods AtmospheresToPascals and PascalsToAtmospheres are reversed

### ISSUE THREAD

**Issue by jimmccurdy** [xamarin/Essentials#968]
### Description

UnitConverters class, the 2 methods AtmospheresToPascals and PascalsToAtmospheres are reversed.

### Steps to Reproduce

Not applicable

### Expected Behavior

Methods should return the correct values

### Actual Behavior

Wrong values returned 

### Basic Information

- Version with issue: All versions
- Last known good version: None
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
Fixed and awaiting release.
