### ISSUE TITLE
[Bug] Geolocation Course always zero

### ISSUE THREAD

**Issue by capsicumDreams** [xamarin/Essentials#973]
### Description

I get location updates in a real (Android) device just fine - but Course _always_ remains zero.

### Steps to Reproduce

1. get location updates

    `GeolocationRequest = new GeolocationRequest(GeolocationAccuracy.Best, TimeSpan.FromSeconds(12));`
    `var location = await MainThread.InvokeOnMainThreadAsync(() => Geolocation.GetLocationAsync(GeolocationRequest, cancel.Token));`
    

2. Check location.Course

### Expected Behavior

Course should update and report True track/course, as per API.

### Actual Behavior

Course always remains zero.

### Basic Information

- Version with issue: 1.3.1
- Last known good version: n/a
- IDE: Visual Studio Community 2019 Preview 16.4.0 Preview 3.0
- Platform Target Frameworks:
  - Android: 9.0 Pie
- Affected Devices:
 - Android

**Comment by jamesmontemagno** [comment]
Some android devices may not return this at all or randomly, we just set whatever the OS tells us: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Types/LocationExtensions.android.cs#L31
