### ISSUE TITLE
Sharing on Android does not give all available options

### ISSUE THREAD

**Issue by dustin-hitzing** [xamarin/Essentials#974]
I am trying to open an embedded xlsx file that I saved to disk. The code works and the file share drawer opens, however Microsoft Excel does not appear in the list of options even though it is installed. I originally thought this may have to do with Microsoft Intune so I made a new application and deployed to a phone that is not managed by Intune.
NOTE: This works fine in iOS. Only Android experiences this issue.

- Version with issue: 1.3.1
- Last known good version: unknown
- IDE: VS4 Mac
  - Android: 9
- Affected Devices: Samsung Galaxy S9

**Comment by jamesmontemagno** [comment]
I will test this out, but the app needs to accept the file format that is specified. I will ask the team :)

**Comment by dustin-hitzing** [comment]
[CopyToExcelApp.zip](https://github.com/xamarin/Essentials/files/3815671/CopyToExcelApp.zip)

This is a zip file with the app

**Comment by jamesmontemagno** [comment]
So, Excel on Android does not accept the "share file" they only accept "open file". This is what you would want to use:

```csharp
 await Launcher.OpenAsync(new OpenFileRequest("Excel Files", new ReadOnlyFile(filePath))));
```
