### ISSUE TITLE
Pitch gives wrong values after 180 degrees turn in yaw/heading

### ISSUE THREAD

**Issue by Lelelo1** [xamarin/Essentials#976]
### Description

When starting the iPhone using `OrientationSensor` I have found values for when the device is laying flat on a table and held vertical in portrait. They are roughly 0 when flat and 0.68 in vertical and I use these to make a fade effect in my app.

When held vertical and the device is rotated around z axis 180 degrees though - the value (X) won't stay 0.68 but goes back to to 0.

My fade effect kicks in as if the I would have put the device back on the table - when I am rotating around Z axis (rotation around with my chair).

Here is a nice illustration of the axises:
https://developer.apple.com/documentation/coremotion/getting_processed_device-motion_data/understanding_reference_frames_and_device_attitude

### Steps to Reproduce

1. Place the iPhone on a table
2. Log the X value to console
3. Note how the value goes up as you put the device vertical in portrait 
4. turn the device around z axis 180 degrees and notice the value drop back to 0 
### Expected Behavior
The X value should remain the same when rotating the device around z axis
### Actual Behavior
The X value is around 0 after 180 degree z axis rotation. No matter how it is turned around x axis in this position.

### Basic Information

- Version with issue: 1.3.1
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  13.4.0.2
- Nuget Packages:
- Affected Devices: iPhone 6

**Comment by Lelelo1** [comment]
I can currently avoid the problem by looking at when z orientation is nearing 180 degrees - and restart:

```
if(z >= 0.38 || z <= -0.38)
{
    // Console.WriteLine("restart!");
       OrientationSensor.Stop();
       OrientationSensor.Start(SensorSpeed.UI);
}
```

This resets the reference frame

**Comment by jamesmontemagno** [comment]
We return the core values from iOS: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/OrientationSensor/OrientationSensor.ios.watchos.cs

There isn't anything that we can do in here, looks like you have a workaround for your use case.

**Comment by Lelelo1** [comment]
I am experiencing the same issue when in vertical portait - rotating to landscape. This should not cause a change in pitch - which is putting the phone back on the table.

Note that essentials currently take from the quaternion property:

![Screenshot 2019-11-13 at 20 09 01](https://user-images.githubusercontent.com/42244983/68795677-b52d8b80-0651-11ea-8498-a2b97ed94981.png)

I think that is causing the axises not being independent from each other.

**Comment by jamesmontemagno** [comment]
Will re-open and link to: #981

**Comment by Lelelo1** [comment]
I made a service - but taking the `Roll`, `Pitch` and `Yaw` directly from the `Attitude` property did not solve the problem with unindependent axises - and it did not matter which `CMAttitudeReferenceFrame` I used.

**Comment by janusw** [comment]
> ### Steps to Reproduce
> 
>     1. Place the iPhone on a table
> 
>     2. Log the X value to console
> 
>     3. Note how the value goes up as you put the device vertical in portrait
> 
>     4. turn the device around z axis 180 degrees and notice the value drop back to 0
> 
> 
> ### Expected Behavior
> 
> The X value should remain the same when rotating the device around z axis

I don't actually think this is a bug. Could you explain why you expect X to remain the same?

Note that a quaternion is not like a 3-vector. In simple cases it can be related to a vector and an angle, but in the general case it represents a combination of multiple rotations (typically 3) around different axes, so a direct interpretation of the components (x, y, z, w) can be tricky.

I don't see a good reason why the X component should remain the same in the setup you describe. If you have one, please share it.

Currently the only OrientationSensor bug I see on iOS lies in the fact that a unit quaternion is returned upon starting the sensor (so that all the following quaternions are relative to the start position and one cannot get an absolute orientation, see #981). But AFAICS fixing that will not affect the behavior you describe.

**Comment by Lelelo1** [comment]
My use case is to fade in a camera view whenever the phone is in vertical portrait. And fade it out when the phone is horizontal. This fade effect happens when the heading is changing or the roll is changing.
I recently tried this is in cad. And i'ts seem to be the standard. Changing the orientation in one axis changes the orientation in another axis. (Very unpractical to work with).

There is also the same problem in a scenario where attitude reference frame has been set so that [north is along x axis](https://developer.apple.com/documentation/coremotion/cmattitudereferenceframe), the phone is started so the heading is 0 - and we start the compass. Now rotating the phone in roll and pitch will change the heading giving from OrientationSensor, while north is in the same position (obviously) and the compass continues to give the accurate heading.

This can probably be closed though as I believe I had a false assumption in how vectors and rotation works. Wether or not it would be good for my use case to work with a quaternion or not - it would be great if someone could point me in the right direction.

**Comment by Lelelo1** [comment]
In short what happens talking in degrees...

* phone is tarted laying on table: 0 x degrees.
* the phone is life up to vertical: 45 x degrees
* phone is rotated in z axis with 180 degrees: x is 0 degrees: //<-- ?!
* phone is put on the tabl: x is 0 degrees.

I am currently trying to solve this without restarting sensor as I need OrententionSensor elsewhere in the tap to track a different rotation.

**Comment by Lelelo1** [comment]
> I made a service - but taking the `Roll`, `Pitch` and `Yaw` directly from the `Attitude` property did not solve the problem with unindependent axises - and it did not matter which `CMAttitudeReferenceFrame` I used.

In contrary - the roll pitch and yaw seem to be correct when taken from the `Attitude` property. It was difficult to determine this due to performance issues reading from the sensors in my test service.

**Comment by jamesmontemagno** [comment]
I don't know if there is anything we can do here unless you found a fix using native apis that are different than ours. We return the raw values back out. https://github.com/xamarin/Essentials/pull/988 has some fixes based on @janusw, however I am not sure if that is impacting you. 

So based on discussion I will close and please re-open a new issue if you find this to be in error.

**Comment by Lelelo1** [comment]
The issue was properly caused when trying to represent orientation with euler angles. And had nothing to do with the values
