### ISSUE TITLE
Add Weight conversion to UnitConverters

### ISSUE THREAD

**Issue by munkii** [xamarin/Essentials#978]
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
Xamarin Essentials currently has conversions for distance, temperature and others. I feel that it should include Weight to such as Kilograms to Pounds. To be honest I have forked the repro here https://github.com/munkii/Essentials and was about to submit a PR when I read the contribution rules. 

If I understand them correctly you want something raised as an issue before it is considered for a PR

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

Add conversions for

- Pounds to Kg
- Pounds to stones
- Stones to pounds 
- Kg to pounds

**Comment by jamesmontemagno** [comment]
Send the PR! :)

**Comment by jamesmontemagno** [comment]
Merged and awaiting release
