### ISSUE TITLE
[Enhancement] keyboard

### ISSUE THREAD

**Issue by mknotzer** [xamarin/Essentials#984]
## Summary

infos about the  keyboard

## API Changes

methods:
bool IsVisible
long Height
string Layout
Event OnDisplay
Event OnDisappear
Event OnLayoutChanged

**Comment by Happypig375** [comment]
How will this be implemented for UWP Desktop?

**Comment by jfversluis** [comment]
I think at this point it's safe to say that this won't be making it's way into Xamarin.Essentials anymore. Keep your eye on .NET MAUI for all new development! Thanks for all input and efforts here.

Some of this will be added to .NET MAUI for .NET 8 or is available through the .NET MAUI Community Toolkit.
