### ISSUE TITLE
[Bug] share on Android doesn't give all options

### ISSUE THREAD

**Issue by kavitap810** [xamarin/Essentials#985]
Hi ,
Using this package for  File Share functionality.
On iOS , it works fine and it also gives option  "Save to Device".
However, on android "Save to device" option is not available.
My code : 
                await Share.RequestAsync(new ShareFileRequest
                    {
                        Title = Title,
                        File = new ShareFile(file)
                    });

**Comment by jamesmontemagno** [comment]
The share functionality is determined by the operating system and what apps can handle it. They will be different based on what the user has installed and what the OS can do. This is why it is not there on Android.

**Comment by kavitap810** [comment]
Hi James,
Thanks for your response. 
I am saving a .kml file which is just like text file, and I have apps that support it.Still, It is not showing Save to Device option on android.
Also, I tried with sharing simple text file ,though I have apps to open .txt file it doesn't show Save to device option on Android
Sample Code tried : 
                await Share.RequestAsync(new ShareTextRequest
                {
                    Text = Title,
                    Title = "Share Text"
                });
Does this mean android doesn't support "Save to Device" feature?
Looking forward to your response.

**Comment by jamesmontemagno** [comment]
I have never seen a "Save to Device" option in Android
