### ISSUE TITLE
+[Enhancement] Extend Share to allow multiple files

### ISSUE THREAD

**Issue by bobwhitten** [xamarin/Essentials#989]
## Summary
Add new share type would allow a list or array of files to be shared.

## API Changes

Add new class ShareFilesRequest, which has a list of ShareFile in place of a single one.

Add new overload for RequestAsync() taking this type.

## Intended Use Case

```
var fn =  "Attachment.txt";
var file = Path.Combine(FileSystem.CacheDirectory, fn);
File.WriteAllText(file, "Hello World");

var fn2 =  "Attachment2.txt";
var file2 = Path.Combine(FileSystem.CacheDirectory, fn2);
File.WriteAllText(file, "Hello Universe");

var filesToShare = new List<ShareFile>();
filesToShare.Add(new ShareFile(file));
filesToShare.Add(new ShareFile(file2));

await Share.RequestAsync(new ShareFilesRequest
{
    Title = Title,
    Files = filesToShare;
});

```

**Comment by jamesmontemagno** [comment]
Question would be if all platforms support this?

**Comment by keisenb** [comment]
This would be really useful!

**Comment by johnbeans** [comment]
I need this, too.

**Comment by mattleibow** [comment]
This was added in #1445 and is available on the preview feed: https://aka.ms/xamarin-essentials-ci/index.json
