### ISSUE TITLE
UnauthorizedAccessException: Access to the path is denied [Bug] 

### ISSUE THREAD

**Issue by RogerSchmidlin** [xamarin/Essentials#995]
using code from the essential example. Works fine on iOS and most Android versions. But I have one Oppo Android phone on 6.0 that throws an exception when trying to share my local pdf. As you can see in my code snippet, I am copying my local file to the cache directory for other apps to access it. Any ideas?

`

            try
            {
                var message = new EmailMessage
                {
                    Subject = subject,
                    Body = body,
                    To = recipients
                };

               var fn = "Attachment.txt";
               var file = Path.Combine(FileSystem.CacheDirectory, fn);
               File.WriteAllText(file, "Hello World");

                message.Attachments.Add(new EmailAttachment(file));
                await Email.ComposeAsync(message);
                successful = true;
            }
            catch (FeatureNotSupportedException fbsEx)
            {
                // Email is not supported on this device
            }
            catch (Exception ex)
            {
                // Some other exception occurred
            }
`

**Comment by acaliaro** [comment]
can be this?

https://developercommunity.visualstudio.com/content/problem/668413/access-to-the-path-is-denied-xamarin-project-for-a.html?childToView=822034#comment-822034

**Comment by RogerSchmidlin** [comment]
I don't get an exception when copying the file. I get the exception when calling ComposeAsync()

**Comment by RogerSchmidlin** [comment]
I upgraded my visual studio to the preview version and it DID fix the problem. Wow, I would never look there. Thanks @acaliaro for your tip!

**Comment by jamesmontemagno** [comment]
Closing as it seems fixed there.
